### ISSUE TITLE
CTCP_VERSION broke

### ISSUE THREAD

**Issue by Inso-m-niaC** [Nicotine-Plus/nicotine-plus#1001]
Nicotine+ version:  3.0.1.dev1
Operating System/Distribution: Windows

### Describe the bug
_ctcpmsgs_ either stays False or later switches to a False state, depending on conditions. I tried checking/unchecking repeatedly until a True state was achieved, it soon switched back to False. i also set True while not running, started app, it switched to False. 

I don't know for sure, but it may be from this commit [https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/574718941](url)

**Comment by mathiascode** [comment]
The boolean has been flipped since the inception of the feature, no idea why though. Seems to be completely broken since that commit though.
