### ISSUE TITLE
v3.0 not starting on macos big sur 11.2.1

### ISSUE THREAD

**Issue by js-d-coder** [Nicotine-Plus/nicotine-plus#1002]
Nicotine+ version:  3.0.0
Operating System/Distribution: macos big sur 11.2.1

### Describe the bug
1. Installed version 3.0.0 [from](https://github.com/Nicotine-Plus/nicotine-plus/releases/download/3.0.0/macos-installer.zip)
2. attempted to open the application (after allowing it from security setting)
3. System dialog says application exited with 255

### Expected behavior

Application should open

### Steps to reproduce the bug

1. Install version 3.0.0 [from](https://github.com/Nicotine-Plus/nicotine-plus/releases/download/3.0.0/macos-installer.zip)
2. open the application (after allowing it from security setting on first install)

### Additional context
Help me to provide logs, stacktraces.

**Comment by mathiascode** [comment]
Could you open Nicotine+ in the terminal, and post the output?

**Comment by js-d-coder** [comment]
@mathiascode Pardon me but I am not sure how I can do that. I can't find that command in `PATH` variable. I tried dragging the app into terminal I turned out to be a folder.

**Comment by js-d-coder** [comment]
@mathiascode 

```
> Desktop/Nicotine+.app/Contents/MacOS/Nicotine+ 
[3344] Error loading Python lib '/Users/jibran/Desktop/Nicotine+.app/Contents/MacOS/Python': dlopen: dlopen(/Users/jibran/Desktop/Nicotine+.app/Contents/MacOS/Python, 10): no suitable image found.  Did find:
	/Users/jibran/Desktop/Nicotine+.app/Contents/MacOS/Python: code signature in (/Users/jibran/Desktop/Nicotine+.app/Contents/MacOS/Python) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Users/jibran/Desktop/Nicotine+.app/Contents/MacOS/Python: stat() failed with errno=1

```

**Comment by mathiascode** [comment]
Does this package launch for you? https://github.com/mathiascode/nicotine-plus/actions/runs/588609021

**Comment by js-d-coder** [comment]
@mathiascode yes, it does. and looks exactly like on gnome.
