### ISSUE TITLE
Make opening of Window's file manager (File Explorer) more generic

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1004]
### Describe the solution you'd like
If I had to guess, Nicotine+ is explicitly calling `explorer.exe` and passing it arguments when performing an action such as `Open Folder` on a downloaded file. This will trigger File Explorer, but not all users may be using File Explorer as their Windows file management software.

Apparently there is a more generic way, at least, as much is hinted by [this post](https://resource.dopus.com/t/some-folders-not-open-in-opus/27189/2) on the forums of one File Explorer replacement:

> ... you may need to ask the software authors to change how they open folders, unless they have a reason for only using Explorer. In general, if they use ShellExecute on the folders, they just need to use a null verb and it will trigger the default file manager. Using "open" as the verb may do the wrong thing.

I'm not sure of the exact details as to how this works, but perhaps Nicotine+ could make this happen? The end result should be that nothing changes for File Explorer users, but those that use a replacement for it, will be able to use what they prefer.

Thanks.

**Comment by mathiascode** [comment]
This is already the case if you clear the file manager command on older Nicotine+ installations. See
https://github.com/Nicotine-Plus/nicotine-plus/commit/25e090d7c185a49a62860129aa13c761b064dd8b#diff-ff84e58d5fdb0ddcd333036f7a3725e44dd737541fc7c854029e2493fc4e9aa3
https://github.com/Nicotine-Plus/nicotine-plus/commit/b28b459e630c1cb6532f33009c6acd551e5e8321#diff-8638210f4ce1a12ae4a9fdcb692fadc1e666e692b08015cd3d9ad726d4760506

**Comment by redactedscribe** [comment]
Perfect, thanks!
