### ISSUE TITLE
missing python req in setup.py

### ISSUE THREAD

**Issue by starenka** [Nicotine-Plus/nicotine-plus#1006]
There's a missing dependency in `setup.py` on current master (installing from src): 
`Cannot find gdbm or semidbm, please install either one.`

(semidbm is installable via pypi for me on cpython3.9)

**Comment by mathiascode** [comment]
To my knowledge, there is no way to specify a fallback dependency. I don't want to force semidbm as a dependency either, as this is mainly intended for the Windows build, where gdbm isn't available, and most other systems have gdbm preinstalled.

**Comment by starenka** [comment]
well, when installing from src, one uses a virtualenv, which does not have (well, shouldn't have) access to global/system sitepackages and thus you need to install the deps via pypi....

**Comment by mathiascode** [comment]
Trouble is that GDBM support is built into Python, and does not reside in site-packages. You need the system-wide gdbm dependency.

It's a rather unfortunate situation, where semidbm is essentially unmaintained, and pushing a dead dependency to all pip users isn't ideal. If only Python's built-in dumbdbm wasn't utterly worthless...

> you provide `pygobject` as a dep already and your're not relying on "system" availability either

It's rather useless on its own though. GTK and related tools are still required as system dependencies.

**Comment by starenka** [comment]
Oh, ok. My bad. I've just updated the src, but haven't checked the https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/DEPENDENCIES.md  'cause I didn't know something has changed... 

> It's rather useless on its own though. GTK and related tools are still required as system dependencies.
Yep, but still you need to fetch it from pypi or install systemwide and use global site packages (which is pita with multiple projects and python versions)

Feel free to close this issue, sorry your time.

**Comment by mathiascode** [comment]
No problem. It's a good thing we added that dependency check, since scanning a large share essentially lasts forever without either dependency (dumbdbm is incredibly slow).

**Comment by starenka** [comment]
I don't know anything about gdbm, but i read it is just kv store? What is the advantage of using *dbm over pickled dict or sqlite (both built in?).

**Comment by mathiascode** [comment]
It's required for the shelve module (dbm + pickled objects as values). I'm not very fond of this solution, but it's been in place for many, many years before I joined the project. At some point I'd like to look into using sqlite or similar, but there are simply too many other things to do that either have higher priority or are more emotionally rewarding, especially as I'm the only active developer on this project.

At least pickle is no longer used for saving the downloads list and local copies of user shares, since Nicotine+ 3.0.0.
