### ISSUE TITLE
"About Nicotine+" menu displays "Credits" tab improperly

### ISSUE THREAD

**Issue by EwanGreen4** [Nicotine-Plus/nicotine-plus#1007]
Nicotine+ version:  3.0.0

Operating System/Distribution: Arch Linux

### Describe the bug
All forms of Markdown styling in the Credits (GtkAboutDialog) display improperly

![image](https://user-images.githubusercontent.com/36348486/108960573-5a942500-7633-11eb-8db8-f79565b56547.png)

### Expected behavior

| Expected | Actual |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/36348486/108961978-5537da00-7635-11eb-99ba-dae72d60b6f5.png) | ![image](https://user-images.githubusercontent.com/36348486/108962231-b1026300-7635-11eb-8cb4-54b031ba6e03.png) |

### Steps to reproduce the bug
Open "About Nicotine+" menu, go to "Credits" tab. 

This is an example issue. There are many more issues of the same nature, caused by giving the GtkAboutDialog window Markdown text to display when it is unsupported or configured improperly (I am not sure which). From the looks of it, all it can display right now is plaintext;  Most prominently, I see sub-headers and bullet lists suffering from this issue. The [user(at)email(dot)com] email syntax used is unfamiliar to me, so I'm not entirely sure if this is an issue of the same type, an issue of the same situation with a different markup language, or intended behavior.

**Comment by mathiascode** [comment]
The contents are mostly copied directly from the AUTHORS.md file. It could probably be converted to pango markup in the about dialog, or simplified to plain text, depending on what looks better.

The email addresses are formatted this way to discourage spam and scraping.
