### ISSUE TITLE
Nicotine+ 1.4.1 don't handle invalid characters in Windows

### ISSUE THREAD

**Issue by aquila-XP** [Nicotine-Plus/nicotine-plus#101]
Hi gfarmerfr,

Please fix these bugs that I encountered on the Windows 10 x64 OS:
1-st bug: It seems that Nicotine+ 1.4.1 is not handling invalid characters on Windows OS.
I tried to download a file with this name: _http:::www.war3z.altervista.org:madonna.mp3_ from a user that is using a Mac-OS and I get these messages:

`Failed download: user murgoros, file @@fujqk\Downloads\Keygen App 2018 v1 2 0-macOS-CASHMERE\Keygen.App.2018.v1.2.0-macOS-CASHMERE\Keygen App.app\Contents\Resources\dosdevices\z:\Users\murgocisugipule\Desktop\Documents\http:::www.war3z.altervista.org:madonna.mp3`
`Download I/O error: [Errno 22] invalid mode ('ab+') or filename: u'F:\\nicotine-downloads\\incompletefiles\\INCOMPLETEcf88f4d5033c568bb5f57a62c35e825ahttp:::www.war3z.altervista.org:madonna.mp3'`

2-nd bug: When I try to download multiple files with the same filename, but different in size, the first file is downloaded in "nicotine" folder, the next two files are stuck in "incompletefiles" folder with these filenames: INCOMPLETE[hash1]filename.ext and INCOMPLETE[hash2]filename.ext and the following files don't download anymore.
Can you please change the code of Nicotine+ 1.4.1 so that will download multiple files with the same filename by adding (1), (2), (3) ... like these: filename(1).ext, filename(2).ext, filename(3).ext and so on.

**Comment by mathiascode** [comment]
On Linux, the second bug doesn't seem to occur on the master branch at least. We don't have any Windows builds set up for testing (yet) though.
