### ISSUE TITLE
Hot keys

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1010]
There is a great lack of standard manipulations such as Ctrl-Z in the fill line to reverse the input history. This needs to be implemented globally.
 Ctrl-C to copy the selected element (copying the path should remain in the context menu.). The update mentioned this feature, but I still haven't seen it. The implementation can be copied from the official client, there everything is fine with it, here it is not enough. That is, I chose an element, whether it is a file or a directory, when clicked, the name of the element itself is copied for the convenience of further search. This function is needed globally*.

Nicotine+ version 3.0.1
FreeBSD 12.2 amd64

**Comment by mathiascode** [comment]
> There is a great lack of standard manipulations such as Ctrl-Z in the fill line to reverse the input history. This needs to be implemented globally.

Anything else in addition to Ctrl-Z?

> Ctrl-C to copy the selected element (copying the path should remain in the context menu.). The update mentioned this feature, but I still haven't seen it. The implementation can be copied from the official client, there everything is fine with it, here it is not enough. That is, I chose an element, whether it is a file or a directory, when clicked, the name of the element itself is copied for the convenience of further search. This function is needed globally*.

This functionality works fine on my system, and is implemented for all views containing file lists (https://github.com/Nicotine-Plus/nicotine-plus/commit/7d104e08702b018106f6ed439aa3ef14698b530d). Does Ctrl-C have no effect on your end?

**Comment by 82d** [comment]
auto-completion of the search often interferes if you want to add a secondary insert to the line by clicking the mouse wheel.
thereby pushing the data out of the clipboard,
you need to pre-enable disabling the auto-complete option in the settings.

**Comment by mathiascode** [comment]
> Ctrl + C absolutely does not work on either FreeBSD or Linux. checked in the stable
> 3.0.2

I assume you're using a non-Latin keyboard layout? Looks like a couple of our keyboard shortcuts need to be modified to take other keyboard layouts into account.

**Comment by 82d** [comment]
```
$locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_ALL=ru_RU.UTF-8

```

**Comment by mathiascode** [comment]
Ctrl-C should now work in the unstable version. Can you verify that this is the case?

**Comment by 82d** [comment]
doesn't work

**Comment by mathiascode** [comment]
Who knew keyboard shortcuts are so difficult to implement... What's your GTK version, and could you check if it's broken in Linux too? For me, it works on Arch Linux with the Russian keyboard layout enabled, GTK 3.24.26.

**Comment by 82d** [comment]
gtk2-2.24.33
gtk3-3.24.24
On both systems, Xfce4 is installed. and on Arch Linux, it also does not work.

**Comment by 82d** [comment]
3.0.3.dev1 ctrl + c still doesn't work

**Comment by mathiascode** [comment]
Do the T (abort), R (retry) or Delete (abort and clear) keys work on transfers in the download/upload views?

**Comment by 82d** [comment]
T works, Delete works. R doesn't work. when I press R, it behaves like a normal character, calling the search bar.

**Comment by mathiascode** [comment]
Thanks, at least the key mapping seems to work. Does https://github.com/Nicotine-Plus/nicotine-plus/commit/239ec4c38c23d5284f24cff42f8cfbdb2d5bf138 help with the Ctrl-C situation?

**Comment by 82d** [comment]
No, it's still the same

**Comment by mathiascode** [comment]
Could you test the following branch, enable "statistics" debug logging in the log pane, and post the output you get when pressing Ctrl-C in the search list? https://github.com/mathiascode/nicotine-plus/tree/shortcutlog

**Comment by 82d** [comment]
I put all the checkboxes, but when you click the log is not written.
![Снимок экрана_2021-03-16_11-57-42](https://user-images.githubusercontent.com/15121782/111258097-e0adf500-864e-11eb-8b9b-6a5709f26bdd.png)

**Comment by 82d** [comment]
there is no need to choose anything in the settings?

**Comment by mathiascode** [comment]
> there is no need to choose anything in the settings?

There's nothing in the settings that control keyboard shortcuts, so that shouldn't be necessary.

I'm rather confused at this point. No logging would mean that the whole key-press-event isn't activated for some reason, but the working shortcuts in downloads/uploads would imply otherwise for those lists. I added the same logging for the download list, could you check if anything happens when you press keys there? https://github.com/mathiascode/nicotine-plus/tree/shortcutlog

**Comment by 82d** [comment]
ok I'll check now
ok I'll check now

**Comment by 82d** [comment]
when I do copy file path, copy URL, copy folder URL through the context menu in the downloads window, nothing happens in the logs.

**Comment by mathiascode** [comment]
That's to be expected, there's only logging for keyboard presses.

**Comment by 82d** [comment]
I didn't quite understand what to do in the last experience? I tried it with a different keyboard, without any changes. what else can I do for the test?

**Comment by mathiascode** [comment]
Is anything logged if you press keys while a file is selected in your list of downloads (where you tested the T (abort), R (retry) or Delete (abort and clear) keys)? Ideally I'd like to know what the logged Ctrl-C key combination looks like on your system, so I can see why the Ctrl-C functionality is not being activated.

**Comment by 82d** [comment]
```
KeyPress event, serial 37, synthetic NO, window 0x6600001,
    root 0x14b, subw 0x0, time 13640750, (68,118), root:(1465,1218),
    state 0x10, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
```
KeyRelease event, serial 37, synthetic NO, window 0x6600001,
    root 0x14b, subw 0x0, time 13788432, (-355,155), root:(1042,1255),
    state 0x10, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False
```

```
KeyRelease event, serial 37, synthetic NO, window 0x6600001,
    root 0x14b, subw 0x0, time 13764117, (-407,316), root:(990,1416),
    state 0x14, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (03) ""
    XFilterEvent returns: False
```

**Comment by mathiascode** [comment]
Thanks, looks like your Ctrl key is reported as Super_L (133), while it's Control_L (37) on my system. Have the keys been swapped?

**Comment by 82d** [comment]
No, it's my fault that I hurried and copied the wrong output. now I have corrected it as it is. ctrl has code 37.

**Comment by 82d** [comment]
I sent the LOG file to the mail from a short session where I used ctrl + c, R, T many times.
I also noticed that R acts resume only in the download window.

**Comment by 82d** [comment]
just because of the heavy turnover of logs, I couldn't identify anything useful.

**Comment by mathiascode** [comment]
> I also noticed that R acts resume only in the download window.

Looks like this shortcut needs to be added for the upload window. I'll do this soon.

I don't see the expected output in the log. Can you verify that the following line exists in your cloned copy of the repo? https://github.com/mathiascode/nicotine-plus/commit/5e9a6c145dd0eafab4b9b5c6b954bb7db43f3261

If not, try cloning with this command: `git clone -b shortcutlog --depth 1 https://github.com/mathiascode/nicotine-plus`

**Comment by 82d** [comment]
there was no this line, installed (git clone). reinstalled it in a new way, now it is being copied. but only file patch.
```
04:16:13 Keys pressed in download list: <flags GDK_CONTROL_MASK | GDK_MOD2_MASK of type Gdk.ModifierType> 54
04:16:13 Keys pressed in download list: <flags GDK_CONTROL_MASK | GDK_MOD2_MASK of type Gdk.ModifierType> 54
04:16:13 Keys pressed in download list: <flags GDK_CONTROL_MASK | GDK_MOD2_MASK of type Gdk.ModifierType> 54
```

**Comment by mathiascode** [comment]
I didn't realize SoulseekQt allows highlighting individual columns. I think GTK only allows highlighting a full row. In that case, we could somewhat easily copy the folder and file name in the grouped mode, depending on the selected row, while ungrouped mode would require more thought. Which list mode (grouped by folder, grouped by user, ungrouped) do you use, and what data do you usually need for searching?

Since the shortcuts work in the repo you cloned, they should work in master/unstable too. Can you verify that you have the latest changes from master, and check if Ctrl-C copies the file path there?

**Comment by 82d** [comment]
in the master version, everything worked.
in most cases, I need to copy only the name of the file or the name of the directory without the full path (let the option to copy the full path or the links remain in the context menu). ideally, I would like to see individual blocks copied . such as User, Patch, Filename, Status, Queue, Size, Time

**Comment by gits68** [comment]
Hi, Could you add Ctrl-Tab/Shift-Ctrl-Tab to switch to next/previous tab ?
For instance, it switches from next/previous field...

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/1489 https://github.com/nicotine-plus/nicotine-plus/issues/1490
