### ISSUE TITLE
Cannot Add Users to Buddy List

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#1011]
Nicotine+ version:  3.0.1
Operating System/Distribution: Linux Mint 20

### Describe the bug
cannot add users to the buddy list through the right click menu or dialog box in the buddy list window

### Expected behavior
add username to buddy list

### Steps to reproduce the bug
try to add user to lilst 

### Additional context
Screenshots, logs, stacktraces or relevant information.
i did try restarting the client,,

**Comment by mathiascode** [comment]
Sorry about this, I'll release 3.0.2 shortly.
