### ISSUE TITLE
Version 3.0.1 and 3.0.2's Nicotine+.exe detected as a virus by Malwarebytes

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1012]
It's unlikely there is a virus packed into these installers (false positive), however I just thought I'd make it known that versions `3.0.1` and `3.0.2` (not ~~prior~~ 3.0.0) are detected as dangerous by Malwarebytes. The type of virus (`Malware.AI`) links to [their online resource](https://blog.malwarebytes.com/detections/malware-ai/).

Ideally, an exception in the antivirus software's rules shouldn't be necessary.

Thanks.

**Comment by mathiascode** [comment]
False positives seem to have appeared for older installers as well. I'm guessing someone has abused PyInstaller to spread malware too many times. Not sure what can be done other than reporting our installers as uninfected somehow.

**Comment by mathiascode** [comment]
Seems like some measures were taken to reduce false positives in the development version of PyInstaller. I'll check if the changes help.

**Comment by mathiascode** [comment]
Any difference with these builds? https://github.com/mathiascode/nicotine-plus/actions/runs/610534363

**Comment by paulbismuth** [comment]
Windows Defender was also reporting `3.0.2` as `Program:Win32/Wacapew.C!ml` malware.

Using the builds you linked @mathiascode, windows defender doesn't report on them anymore 👍

**Comment by mathiascode** [comment]
Thanks, I'll replace the installers shortly.

**Comment by redactedscribe** [comment]
Was about to test this. Good to hear. Thanks @paulbismuth!

**Comment by mathiascode** [comment]
@redactedscribe I think it may have been resolved today. In the list on VirusTotal, Malwarebytes now seems clean.

**Comment by redactedscribe** [comment]
As far as I can tell, it has been.

**Comment by mathiascode** [comment]
The 3.0.6 installer/package was rebuilt earlier today. Can you check if it solves the issue for you?
https://github.com/Nicotine-Plus/nicotine-plus/releases/tag/3.0.6

**Comment by elislider** [comment]
thanks! I had checked for a new version but missed that note from earlier today. I reinstalled and no virus warnings yet...
