### ISSUE TITLE
Complete file remains in Incomplete Downloads folder

### ISSUE THREAD

**Issue by EwanGreen4** [Nicotine-Plus/nicotine-plus#1019]
Nicotine+ version:  3.0.2
Operating System/Distribution: Arch Linux

### Describe the bug
When files finish downloading (reach 100%), instead of finalizing the download and obtaining the "finished" status, file will sometimes remain in the download queue and stagnate at 100%. If you abort the download, the file will remain aborted as expected. When you retry the download, it will indefinitely be "waiting for download". File remains in Incomplete Downloads folder, with complete metadata, despite being fully downloaded & valid as a music file.

### Expected behavior
File finished downloading, moves to destination folder with name changed & status changed to "finished".

### Steps to reproduce the bug
Download a file & wait for it to finish.

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://user-images.githubusercontent.com/36348486/110487254-a373c100-80aa-11eb-9788-c2230c19f821.png)
File idling in Downloads tab
![image](https://user-images.githubusercontent.com/36348486/110489114-5b559e00-80ac-11eb-9edb-2ac0c56af4df.png)
Complete file idling in Incomplete Downloads folder

**Comment by mathiascode** [comment]
Could you try the unstable version, and see if the problem persists (https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md)? Download queuing was mostly changed recently.

**Comment by EwanGreen4** [comment]
Sounds good. Please let me know when it gets figured out so we can continue to figure out the initial issue.

**Comment by mathiascode** [comment]
I'm guessing the download folder is on an external drive? The error message is quite vague, so I'm not entirely sure what's going on. Is the target location writable?

I get the same stacktrace when I disconnect the drive where the download location is set, but the error is "[Errno 13] Permission denied" in this case.

**Comment by EwanGreen4** [comment]
The drive is mounted & I have write perms.

**Comment by mathiascode** [comment]
Is this an NTFS or FAT drive? In that case, the colon in the folder path could explain the issue.

**Comment by EwanGreen4** [comment]
FAT32

**Comment by mathiascode** [comment]
The issue should be fixed in this branch: https://github.com/mathiascode/nicotine-plus/tree/pathcharacterfix

Could you test it by downloading a folder name containing invalid characters ([? : > < | * "])?

**Comment by EwanGreen4** [comment]
This new branch seems to be working well. No Error 22, file with colon in the path downloads fine. However, the download progress bar displays no text when it should say "0 %". Thanks for your help.

**Comment by mathiascode** [comment]
`the download progress bar displays no text when it should say "0 %"`
Which files does this apply to? Does the bar update once the file starts downloading? Could you send a screenshot?

**Comment by EwanGreen4** [comment]
![image](https://user-images.githubusercontent.com/36348486/110847380-17a89300-826a-11eb-91b3-2133cf4b7ee2.png)
It applies to all files. It acts normally once it begins the download.

**Comment by mathiascode** [comment]
Thanks, this seems to happen if the list was previously empty, and none of the downloads have progressed past 0% yet. As soon as a single download reaches 1%, every percentage bar becomes visible. Likely a regression in GTK, but I'll have to investigate.
