### ISSUE TITLE
Random crash on Raspbian

### ISSUE THREAD

**Issue by EhotPotaskun** [Nicotine-Plus/nicotine-plus#103]
My Nicotine crashes randomly, i think it is happening when i interacting with interface, scroll the list, click on buttons etc.

Here is some crash logs i got 

[nico2.txt](https://github.com/Nicotine-Plus/nicotine-plus/files/4087228/nico2.txt)
[nico.txt](https://github.com/Nicotine-Plus/nicotine-plus/files/4087229/nico.txt)

I was encounter this crash more often using 1.2 version from Raspbian repo, than built it from 11 Jan master, now i face it a little less often i think.

**Comment by mathiascode** [comment]
Is this still an issue on master?
