### ISSUE TITLE
Quicker access to speed throttling?

### ISSUE THREAD

**Issue by mxmilkiib** [Nicotine-Plus/nicotine-plus#1031]
### Describe the solution you'd like
Sometimes I like downloads to to go full pelt, but my connection isn't great and sometimes I would like to watch a few YouTube videos and I need to restrict the download bandwidth.

Instead of having to go into the settings dialog every time, how about having a feature like qBbittorrent where clicking on the download info in the bottom status bar directly brings up a download speed throttling dialog (and the same for upload speed)?

**Comment by mathiascode** [comment]
Clicking the speed info now opens the download/upload preferences. The option of specifying alternative speed limits will be added here in the future, as well as a status bar button for enabling these limits.
