### ISSUE TITLE
Critical UnicodeDecodeError on startup: 'utf-8' codec can't decode byte 0x92 in position 12: invalid start byte

### ISSUE THREAD

**Issue by vctls** [Nicotine-Plus/nicotine-plus#1038]
Nicotine+ version:  3.0.3
Operating System/Distribution:
Windows 10 20H2 build 19041.867
French locale

### Describe the bug
I just installed version 3.0.3
When I start the program, it immediately crashes with the following error:
> Type: <class 'UnicodeDecodeError'>
> Value: 'utf-8' codec can't decode byte 0x92 in position 12: invalid start byte

then every time I click OK, the following error keeps popping up, until I kill the process:
> Type: <class 'AttributeError'>
> Value: 'NoneType' object has no attribute 'shutdown_notification'

See screenshots.

I rolled back to 3.0.2 and it's working fine.

### Steps to reproduce the bug
Not sure. Could it be the French local causing trouble again?

### Additional context
![image](https://user-images.githubusercontent.com/18054077/113337658-5f31b480-9328-11eb-8485-369f68de6555.png)
![image](https://user-images.githubusercontent.com/18054077/113337630-52ad5c00-9328-11eb-80ca-6a51eb486bac.png)

**Comment by mathiascode** [comment]
Can you check if the issue is fixed in the unstable build?

**Comment by vctls** [comment]
Yep, it's working now.
