### ISSUE TITLE
You have no privileges left. They are not necessary, but allow your downloads to be queued ahead of non-privileged users. [Question]

### ISSUE THREAD

**Issue by Scapehips** [Nicotine-Plus/nicotine-plus#1039]
What does this mean?

**Comment by mathiascode** [comment]
There's a "Get Privileges" menu item for donating to Soulseek. You receive download privileges in return, meaning less waiting time for your downloads to start, if the user you're downloading from has a lot of queued uploads.

**Comment by Scapehips** [comment]
Okay I will donate something just to support Soulseek!
