### ISSUE TITLE
Bitrate not shown for most music in search results

### ISSUE THREAD

**Issue by lope** [Nicotine-Plus/nicotine-plus#104]
![image](https://user-images.githubusercontent.com/2905035/73347294-0849ce80-4290-11ea-8eed-d392ddaac631.png)

**Comment by mathiascode** [comment]
Is this still an issue on the master branch? I can't reproduce it.

**Comment by mathiascode** [comment]
I'd say we can close this issue. I haven't been able to reproduce it on any OS I've tested on, and the version in the screenshot is pretty old (1.2.16).
