### ISSUE TITLE
'utf-8' codec can't encode characters(surrogates not allowed)

### ISSUE THREAD

**Issue by BachoSeven** [Nicotine-Plus/nicotine-plus#1043]
Nicotine+ version:  3.0.3 (But I can _also_ reproduce on current master version.)
Operating System/Distribution:
Arch Linux

### Describe the bug
After updating, on startup I always get the following warning:
```
23:31:51 Can't save wordindex.db: 'utf-8' codec can't encode characters in position 3-5: surrogates not allowed
```

Seems related to, but not a duplicate of(I think), #1038.

**Comment by mathiascode** [comment]
If you upgrade Nicotine+ and remove your .db files, this will no longer happen.

One of your shares files has a file name that can't be decoded to utf-8 though, so I suggest correcting it instead. Since this issue isn't unique to 3.0.3, I assume you've recently started sharing a problematic file.

**Comment by BachoSeven** [comment]
I see. Thanks for the explanation, I think I found the file, it has this file name:
```
Why Won���t You Make Up Your Mind (Instrumental).flac
```
which escaped looks like this
```
Why\ Won$'\324'$'\307'$'\326't\ You\ Make\ Up\ Your\ Mind\ \(Instrumental\).flac
```

**Comment by BachoSeven** [comment]
Indeed, updating to master fixed the issue, and then I also tried re-installing 3.0.3 and removing the problematic glyphs in the name, which also solved it.
