### ISSUE TITLE
Nicotine+ 1.4.2, Debian 9 (64 bit) : Can't get shared files + current downloads disappeared : since the last but one update, from branch master

### ISSUE THREAD

**Issue by zebulon-1st** [Nicotine-Plus/nicotine-plus#107]
Console output, when (but not always) I ask shared files from someone of my friends-list :
```
Traceback (most recent call last):
  File "nicotine-plus/pynicotine/gtkgui/frame.py", line 1351, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "nicotine-plus/pynicotine/pynicotine.py", line 1619, in PierceFireWall
    self.userbrowse.InitWindow(i.username, msg.conn.conn)
  File "nicotine-plus/pynicotine/gtkgui/userinfo.py", line 99, in InitWindow
    w = self.subwindow(self, user, conn)
TypeError: __init__() takes exactly 5 arguments (4 given)
```

**Comment by kiplingw** [comment]
Hey @zebulon-1st. Can you confirm if this happens on the latest deb from the unstable daily PPA?

**Comment by zebulon-1st** [comment]
Debian don't use PPA. It's Ubuntu specific.

**Comment by kiplingw** [comment]
I'm aware of that. But provided the dependencies are satisfied, it should at least install. The Debian downstream package is updated on a glacial time frame.

**Comment by zebulon-1st** [comment]
Do you have an URL for this PPA ?
From the Nicotine+ website (https://www.nicotine-plus.org/), there is only a Ubuntu/Debian PPA stable link (https://launchpad.net/~kip/+archive/ubuntu/nicotine+), which gives nothing else than an error page : "This page does not exist..."

**Comment by zebulon-1st** [comment]
( I don't understand why it exists so many different Nicotine+ website/pages, and none have the sale version in it as the last -- it's really helpless )

**Comment by kiplingw** [comment]
@zebulon-1st, take a look in the [README.md](https://github.com/Nicotine-Plus/nicotine-plus#ubuntu-ppa-unstable). The unstable PPA is there. The URL on the website is old. I don't have access to it. Sorry.

**Comment by zebulon-1st** [comment]
Well, I didn't succeed using the PPA (on `apt update`, error « ... NO_PUBKEY 6CEB6050A30E5769 ... »). So I tried from the GITDEB, which has been more successful.

I ran it from a console (to see errors on output) `/usr/bin/nicotine` (package version is 1.4.1+git20180205200457.ab570f8-1) :
\- No error at start.
\- The current downloads, which had disappear are back shown.
\- I can get shared files list from users

It seems to be ok with this version.

---
The previous I used was v1.4.2, from the git repository, branch master.

I should still using this 1.4.1, I think.

**Comment by alekksander** [comment]
i confirm its unable to browse shares 
`1.4.2-kip2-202002261716~ubuntu18.04.1`

**Comment by kiplingw** [comment]
@lene 's PR hasn't been merged yet because he's not done with it yet, but this may be something that he's already fixed in #106. You might want to try again with his branch.

**Comment by mathiascode** [comment]
Is this still happening on the master branch? If so, is it linked to a specific username?

**Comment by alekksander** [comment]
not for me

**Comment by zebulon-1st** [comment]
Since Nicotine+ requires python 3.7, I can't use it anymore. My Debian (9, stretch) can only have python 3.5 max. I have to use back Nicotine+ v1.4.2 :[

**Comment by mathiascode** [comment]
Perhaps we can reduce it to 3.5. I'll do some testing.

**Comment by mathiascode** [comment]
@zebulon-1st Python 3.5 is now the minimum requirement. :)

**Comment by zebulon-1st** [comment]
@mathiascode cool, thx !

**Comment by mathiascode** [comment]
Let us know if you still encounter the issue.

**Comment by zebulon-1st** [comment]
Nicotine+ (1.4.3, at the moment) run ok.

The initial error messages don't appear again. Even with I ask files from a user in my friend list.

---
I have these warnings, from GTK:
```
(nicotine:24492): Gtk-WARNING **: Allocating size to GtkWindow 0x55d572ea2520 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
(nicotine:24492): Gtk-WARNING **: Allocating size to GtkVPaned 0x55d5731f8d70 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
and many of (sorry, end is written in French).
```
(nicotine:24492): Gtk-WARNING **: Failed to measure available space: Aucun chemin d'accès pour atteindre l'hôte cible
```

**Comment by mathiascode** [comment]
I suppose we can close this then. There are some minor GTK issues here and there that will be fixed eventually, but they shouldn't affect usability.

**Comment by zebulon-1st** [comment]
Oh, yes, sorry, I think I can "Close and comment", right now.
