### ISSUE TITLE
Nicotine over Lokinet? 

### ISSUE THREAD

**Issue by danrobi11** [Nicotine-Plus/nicotine-plus#112]
Hi. Im just a regular non-technical user. But I think Lokinet would be the perfect network transport for Nicotine.
- 'Lokinet is an open source layer 3 protocol. Your real IP address isn't revealed to Lokinet addresses. Lokinet can carry any IP based protocol. Lokinet is like a VPN, it accepts all data types, this makes it easy to integrate with your application. All data that travels through Lokinet is encrypted and bounced through multiple nodes hiding the true origin' https://lokinet.org/
https://www.youtube.com/watch?v=UrAAczDfiBY
Thanks!

**Comment by kiplingw** [comment]
Thanks @danrobi11. I'm not familiar with Lokinet, but my guess is this isn't an option. We didn't create the SoulSeek protocol. We just re-implement it in the Nicotine+ python implementation. There ultimately isn't anything prohibiting us from changing how this protocol works, such as the transport to UDP, adding SSL, etc, other than it will simply stop talking to other clients (most of which probably aren't Nicotine+).
