### ISSUE TITLE
images seem to be integrated from the launch directory if they have special names

### ISSUE THREAD

**Issue by kristopolous** [Nicotine-Plus/nicotine-plus#113]
So as you can see below if you have a file named "empty.jpg" in the directory you launch the application from, it just drops it into the client as depicted.

When running strace on it, I can see it finds 2 images, the other one being in a dropdown menu.

These paths should probably be fixed. I can do this if you want, or anyone else, shouldn't be hard.

![fromhome](https://user-images.githubusercontent.com/231761/79169904-9ec36180-7da2-11ea-937c-c16ce85d1b37.png)

**Comment by kristopolous** [comment]
wait, didn't realize there's a 1.4 branch ... ignore this for now.

**Comment by kristopolous** [comment]
problem persists in 1.4.1 ... let me try master

**Comment by kristopolous** [comment]
yep. bug is still real. ok, needs to be fixed.
![persistence](https://user-images.githubusercontent.com/231761/79170320-e0a0d780-7da3-11ea-81d5-fa2a3d38ae07.png)

**Comment by kiplingw** [comment]
Thanks @kristopolous. PR welcome. I should be able to merge that as soon as you're ready. Thanks for finding that.

**Comment by kristopolous** [comment]
@kiplingw ok, thanks, feel free to close this as per whatever you policies are

**Comment by kristopolous** [comment]
hey as an aside, that was pretty fast ... do you just follow your email closely or is there some kind of special notification app you have for your phone? I could use something like that

**Comment by kiplingw** [comment]
Click the "Watch" button up at the top [here](https://github.com/Nicotine-Plus/nicotine-plus/). :)

**Comment by kristopolous** [comment]
ah yeah, I have a zoo of about 200 of them ... 95% of the conversations I don't have time to get into and will resolve without my participation, problem is I can't tell what 95% that is. I guess it's time for a new tool.
