### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexdelorenzo** [Nicotine-Plus/nicotine-plus#119]
The [commit](https://github.com/Nicotine-Plus/nicotine-plus/commit/4ec8b3d36ed7e369ef7a9ce338cdedcd0125c3e9) that creates the [COPYING file](https://github.com/Nicotine-Plus/nicotine-plus/blob/master/COPYING) says that the project is "Relicense[d] under GPLv3 and LGPLv3".

Just clarifying if this is dual-licensed or not.

**Comment by kiplingw** [comment]
My understanding is it's not. It's GPLv3.
