### ISSUE TITLE
Please update Nicotine to work on the latest Ubuntu (20.04)

### ISSUE THREAD

**Issue by CHJ85** [Nicotine-Plus/nicotine-plus#123]
Hi there.
Do you think you could please repackage Nicotine for Ubuntu 20.04?
That'd be great. Because the latest packaged version is for 19.10 and it asks for GTK+ 2.24, which is dated. When I did "sudo apt install gtk+-", it wants to delete a ton of stuff in order to be installed.
If you wish to keep the current format of Nicotine (with GTK+2), I suggest you package it in a container such as Flatpak, Snap or AppImage instead of using PPAs.
Moreover, you'll have an easier job if you use the python3 dependencies as they're already available in the main repo.

**Comment by kiplingw** [comment]
> Hi there.
> Do you think you could please repackage Nicotine for Ubuntu 20.04?

Thanks @CHJ85, but please use the search feature before opening a new issue. In particular, see PR #106.

> That'd be great. Because the latest packaged version is for 19.10 and it asks for GTK+ 2.24, which is dated. When I did "sudo apt install gtk+-", it wants to delete a ton of stuff in order to be installed.

Yes, we're aware of that.

> If you wish to keep the current format of Nicotine (with GTK+2), I suggest you package it in a container such as Flatpak, Snap or AppImage instead of using PPAs.

We're not going to package in Flatpak, Snap, or AppImage. Those do not have the robustness and practical field experience that Debian based packages have had for nearly two decades.

> Moreover, you'll have an easier job if you use the python3 dependencies as they're already available in the main repo.

Yup. Just hold tight and we will have the porting work done soon.

**Comment by CHJ85** [comment]
Okay thanks 😀
