### ISSUE TITLE
(Feature Request) Stream option

### ISSUE THREAD

**Issue by danrobi11** [Nicotine-Plus/nicotine-plus#126]
Hello
In the 'Search Files' section, right click on a file, click the 'stream' option and watch instantly.
The file would have to be in a supported format like, m4v 
Any thoughts?

**Comment by kiplingw** [comment]
When you say stream, do you mean begin buffered playback as it downloads?

**Comment by danrobi11** [comment]
@kiplingw Yes mostly. I wouldnt mind having the choice to not download, just stream would be handy too. Im just trowing that around. I know theres big python upgrade, thats real cool!

**Comment by kiplingw** [comment]
Well streaming and downloading are the same thing. Streaming just implies you're doing something with what you are downloading before it is transferred in its entirety. The issue here is that not all files are streamable, and just looking at the file extension isn't always enough.
