### ISSUE TITLE
Version 3.0.4 flagged by Windows Defender

### ISSUE THREAD

**Issue by Eridyne** [Nicotine-Plus/nicotine-plus#1329]
Platform: Windows 10 (21H1)
Version: Nicotine+ 3.0.4 (x86-64)

nicotine+.exe is flagged on install or extraction as a trojan by Windows Defender.
Approaching a third of the engines used by Virustotal detect it, as well, though typically as something generic.

**Comment by mathiascode** [comment]
Looks like they never learn. Thanks for reporting, I'll check if there's a way to mitigate this false positive.

**Comment by mathiascode** [comment]
I've increased our PyInstaller version. These new builds seem better, at least for now. https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/743608722

**Comment by Eridyne** [comment]
Can confirm. The new build does not trigger any flags by Windows Defender, on install, run, or manual scan.

**Comment by redactedscribe** [comment]
Malwarebytes falsely detected 3.0.4 as infected.
The 3.0.5 dev build you linked is considered clean.
