### ISSUE TITLE
File Manager and Media Player events are buggy

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1335]
Nicotine+ version: 3.0.5dev1
Operating System/Distribution: Windows 10

### Describe the bug
Editing the File Manager and Media Player events don't save. In fact, they do, but each time the Preferences is opened, the value reverts to `xdg-open $` and pressing Apply/OK will overwrite what you had set before, which, for _File Manager_, leads to:

```plaintext
[Warn] Failed to open file path: Problem while executing command ['xdg-open', '<path>'] (1 of 1)
```

I can't seem to make a media player launch via Send to Player, no matter what I set the _Media Player_ value to. And even entering random text doesn't produce a Warn log. I've tried:
```plaintext
media-player.exe $
"C:\path\to\media-player.exe" $
C:\\path\\to\\media-player.exe $
C:/path/to/media-player.exe $
<blank>
$
```

Nothing happens: no log, no program launches.

### Expected behavior
The Preferences should show the value set and not be overwritten by the default value the field has been assigned.

### Additional context
I have not tested the two Run commands above these options, but I assume they work. Might be worth verifying.

**Comment by mathiascode** [comment]
Thanks for reporting this! Seems like I accidentally introduced the `xdg-open $` issue some day ago, but there's also another issue where custom commands are not restored when the preferences dialog is first opened, wiping any previously saved command. This is apparently a bug from 2016... https://github.com/Nicotine-Plus/nicotine-plus/commit/efb49b0c5a82e3e0e372ae850ccfebcb8f82ac65

**Comment by redactedscribe** [comment]
@mathiascode In case you missed the point about the Media Player command, it still doesn't do anything (even after your latest commit ~30 minutes ago). I can't get anything to launch.

The command strings are remembered now though.

Thanks.

**Comment by mathiascode** [comment]
Strange. An absolute path works fine on my end, e.g. `C:\Program Files (x86)\Windows Media Player\wmplayer.exe $`

**Comment by redactedscribe** [comment]
@mathiascode It's happening again. Maybe it's only files that have just been downloaded that won't be sent to the player?

I wanted to test whether that was the case, but upon using the Disconnect and Connect functions, the completed files were cleared from the Downloads list.
