### ISSUE TITLE
The shared folders are not shared anymore

### ISSUE THREAD

**Issue by NelsonSR** [Nicotine-Plus/nicotine-plus#1338]
Nicotine+ version:  3.0.4-202104072302~ubuntu21.04.1
Operating System/Distribution: Debian GNU/Linux 10.9 «Buster»

### Describe the bug

The shared folders are not shared (private nor public). A BrowseShares request causes hang-ups of some functions like transfer queue, file searching, and tabs closing. The main menu is still functional allowing disconnection and closing.

### Expected behavior

The public shared folder should be accessible.

### Steps to reproduce the bug

Browse public shares.
Wait for a BrowseShares request.

### Additional context
Screenshots, logs, stacktraces or relevant information.

The shared folder permission hasn't changed, the permission was 755 (changed to 775 with no improvement). A possible cause was the resetting of the configuration due to the home partition filled up.

~/.nicotine/config
`shared = [('Music', '/opt/music'), ('eBooks', '/var/calibre_library')]`

~/.nicotine/logs/debug/debug_1618466808.log
`[Warn] Exception during parsing SharedFileList: a bytes-like object is required, not 'NoneType'`

**Comment by mathiascode** [comment]
This should be fixed in the unstable build.

**Comment by NelsonSR** [comment]
I use the stable release so I guess I'll have to wait some time to get that fix.
