### ISSUE TITLE
Pausing a download

### ISSUE THREAD

**Issue by asorel1942** [Nicotine-Plus/nicotine-plus#1339]
Stupid question, how do I pause downloads in the interface? The context menu for clearing groups from the Downloads queue has a "clear paused" option, which implies the ability to pause downloads exist, but I can't seem to find how to do so.

**Comment by mathiascode** [comment]
Downloads only change to the `Paused` state on startup if they were aborted the previous session. The behavior seems to have been introduced here: https://github.com/Nicotine-Plus/nicotine-plus/commit/e46925e3f71fa5451059adf6e6a84a01c875467a

There's no technical difference between pausing and aborting downloads in the Soulseek network, so I think we should revert that commit to reduce confusion.
