### ISSUE TITLE
Copy/Paste keyboard shortcuts broken on Mac

### ISSUE THREAD

**Issue by hackedy** [Nicotine-Plus/nicotine-plus#1342]
Nicotine+ version:  3.0.4
Operating System/Distribution: macOS Big Sur 11.2.3

### Describe the bug

There appears to be a problem with keyboard shortcuts in text inputs in the application. I've noticed this mainly in the search box, where things like command-A, command-C, and command-V don't do anything.

### Expected behavior

Pressing command-V pastes from my OS clipboard, etc.

### Steps to reproduce the bug

Copy text in another application. Switch to Nicotine+ and click on the search bar. Hit command-V. Nothing happens.

### Additional context

Right clicking and selecting "Paste" from the context menu works, so it appears to be just the keyboard shortcuts.

**Comment by mathiascode** [comment]
I think GTK handles these shortcuts, so I'm not sure what the issue could be. Do our custom keyboard shortcuts (e.g. Ctrl+H to toggle away status, Ctrl+C in the search list to copy a file path, or Ctrl+F to open the search bar in the log pane or chatrooms)?

**Comment by hackedy** [comment]
Ah, my mistake. It's binding clipboard operations to ctrl-<key> and not cmd-<key>. All those other keyboard shortcuts you listed work except for ctrl+H, but i might be using it in the wrong place or something.

**Comment by mathiascode** [comment]
We have some inconsistent behavior. I believe the Ctrl+H shortcut is actually Cmd+H on macOS right now, while those other custom shortcuts I mentioned need to be rewritten to support Ctrl/Cmd depending on the platform.

I'm still not sure why the search entry shortcuts are using Ctrl, as GTK should automatically use Cmd as far as I understand.

**Comment by mathiascode** [comment]
This should be fixed, but I can't confirm right now. Can someone check if Command-C, Command-V, Command-A, as well as our shortcuts listed in Menu -> Help -> Keyboard Shortcuts, work properly?

**Comment by mathiascode** [comment]
It looks like we removed the macOS key theme from our macOS builds by mistake. This should be fixed now.
https://github.com/Nicotine-Plus/nicotine-plus/commit/3e4daf2f7e0f73ca640f32923020627c842e6fe1

**Comment by 2V3EvG4LMJFdRe** [comment]
Hmm, it doesn't work on my end. Just as before, ctrl instead of cmd.

**Comment by mathiascode** [comment]
Are you sure you have the latest changes? I managed to test the changes now, and all shortcuts now use Command instead of Ctrl on my end.

**Comment by 2V3EvG4LMJFdRe** [comment]
I have tried again and it works with cmd natively like you said.
