### ISSUE TITLE
Notifications tray icons aren't removed automatically

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1354]
Nicotine+ version: 3.0.5
Operating System/Distribution: Windows 10

### Describe the bug
Notifications produced by completed downloads create tray icons that do not get removed until the user mouses over them. They can build up and create a large number of them. This isn't new to 3.0.5.

![notifications](https://user-images.githubusercontent.com/25013746/115958349-c4d02580-a50f-11eb-9633-6f59ab312fe4.jpg)

### Expected behavior
Notifications tray icons should disappear without needing to mouse-over them.

**Comment by redactedscribe** [comment]
The icons are still lingering with v3.0.6. I've seen this happen with some other programs in the past, so it could be a Windows notification thing.

**Comment by Inso-m-niaC** [comment]
It is the plyer notifications module.

Anyway, i have been working on this [module](https://pastebin.com/WufD3drR "module") just recently, and it works great in my IDE. The window (not just the NID) is destroyed after each use.

**Comment by mathiascode** [comment]
@redactedscribe Can you check if this PR works fine on your system? #1379 
Windows build: https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/837062578

**Comment by redactedscribe** [comment]
As far as I can tell, it looks to be fixed. None of those white icons after a notification.
