### ISSUE TITLE
Headless support

### ISSUE THREAD

**Issue by depsterr** [Nicotine-Plus/nicotine-plus#1362]
### Describe the solution you'd like
It would be nice to have an option to simply run nicotine-plus without the ui components, such that it would simply read the config and start sharing files.

### Additional context
Nicotine-plus is (in my opinion) the most mature soulseek client. All of the headless (no UI, works without X), clients I've tried have been less then stellar, or non-functional. I'd like to be able to share files from my server 24/7.

**Comment by toofar** [comment]
It's not really no-X but I wanted to check you know about [xvfb](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml)? I run nicotine under https://github.com/Xpra-org/xpra myself so I can attach to it when I feel like it.

**Comment by mathiascode** [comment]
There is now experimental support for headless mode under the command `nicotine --headless`. While it does successfully connect to the server, it hasn't been tested beyond this point yet.

**Comment by mathiascode** [comment]
The mode is now documented, and can be launched using `nicotine -n` or `nicotine --headless`. Please report any potential issues you find.

**Comment by depsterr** [comment]
great to hear, thanks!

**Comment by papuSpartan** [comment]
so does the client not yet have thin-client functionality?

**Comment by slook** [comment]
No is doesn't yet, but some groundwork has already been laid for future development of a CLI interface, and there is a discussion about it with a testing branch which has some basic functionality, see: https://github.com/mathiascode/nicotine-plus/tree/cli-commands-test
