### ISSUE TITLE
Support for macOS High Sierra

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [Nicotine-Plus/nicotine-plus#1366]
### Describe the solution you'd like
I've attempted to run the new macOS builds on High Sierra, and though they can be opened, the app never actually appears and its icon is gone from the dock almost as soon as it loads. Normally, apps requiring "version and up" on macOS are be blocked from opening and marked with a "block" overlay symbol, but because this is not the case here I believe the app is mostly compatible with High Sierra. It may be a quick fix. 

### Additional context
Because of all the great improvements worked on, particularly the revival of a maintained macOS version, I really would love to use this app. SoulseekQt has pretty poor support on macOS, and iSoul is abandoned and broken.

I've also tried to install Nicotine+ with homebrew, but I can't find anything to open after the process finishes successfully.

**Comment by mathiascode** [comment]
Since we currently use Homebrew packages for generating the macOS builds, and Homebrew no longer supports High Sierra, this would require more effort. I'm not opposed to a switch to potential alternatives, as long as our packaging workflow remains straightforward: https://github.com/Nicotine-Plus/nicotine-plus/blob/master/.github/workflows/packaging.yml

**Comment by 2V3EvG4LMJFdRe** [comment]
I wouldn't mind being left behind with just one working compiled High Sierra version instead of changing the whole workflow, if that's a more reasonable request. Either way, I'm not a programmer and barely understand how to compile, so I'm afraid I can't help there. 

I'm stuck on High Sierra because I rely on Nvidia support, and gathering from the hackintosh community and Github requests I've found on other projects, I wager there's a group of people out there who'll find this useful too.

**Comment by mathiascode** [comment]
I've tried to adapt alternatives such as Nix and MacPorts for several hours, without results. Nix seemed promising at first, but seems to choke when running PyInstaller.

Since High Sierra is no longer supported by Apple, I don't have much desire to work on this further. Unfortunately I don't have a macOS High Sierra environment, so I can't generate a manual build. I'm not sure if Homebrew works at all on older macOS versions at this point, but if it does, you could try installing the dependencies (https://github.com/Nicotine-Plus/nicotine-plus/blob/master/packaging/macos/dependencies-packaging.sh) and run Nicotine+ from git (https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md#run-nicotine-from-a-folder).

**Comment by 2V3EvG4LMJFdRe** [comment]
Thanks a lot for all the effort, I couldn't ask for more than that despite the outcome. I'm close to getting it to work the way you describe it. When I attempt to launch it with git, I'm only missing one dependency called pygobject. When I try to install it with pip, It calls for a newer version of libffi. I've installed it with brew, but because it's not found in pip, pyobject fails to install. From what I gather, I have to tell pip about these export= flags from the newer libffi. How can I do this?

![Sat May  8 15:57:52 -04 2021](https://user-images.githubusercontent.com/11010067/117552199-f53bb780-b017-11eb-944f-9f657d8e4126.png)

![Sat May  8 15:57:54 -04 2021](https://user-images.githubusercontent.com/11010067/117552212-01277980-b018-11eb-869b-ac4c14dfb351.png)

Because it feels like were one step away from getting this to work, I'm not gonna close this.

**Comment by 2V3EvG4LMJFdRe** [comment]
It's been installed successfully with brew, but when I run Nicotine I get:

```
cd nicotine-plus
./nicotine
Cannot find pygobject, please install it.
```

**Comment by mathiascode** [comment]
Looks like pip is the only way. Have you tried the suggested `export PKG_CONFIG_PATH...` command?

**Comment by 2V3EvG4LMJFdRe** [comment]
I'm sure that will work, but I don't know how to do it. I mean, where should I write those lines?

**Comment by mathiascode** [comment]
It's a command, so you could run it in the Homebrew window before attempting to install pygobject with pip.
```sh
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
pip install pygobject
```

**Comment by 2V3EvG4LMJFdRe** [comment]
And we're in!

![Sun May  9 00:06:47 -04 2021](https://user-images.githubusercontent.com/11010067/117560458-ef67c580-b05b-11eb-9641-b2d45a944882.png)

Just one more thing. How can I run this as a normal macOS app with its own icon? I have tried the latest provided Catalina build just in case it'd work now, but it does close immediately just the same. Opening it from the terminal outputs the following:

```
REDACTED-iMac:~ REDACTED$ /Users/REDACTED/Downloads/Nicotine+.app/Contents/MacOS/Nicotine+ 
Traceback (most recent call last):
  File "_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_certifi.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "ssl.py", line 98, in <module>
ImportError: dlopen(/Users/REDACTED/Downloads/Nicotine+.app/Contents/MacOS/lib-dynload/_ssl.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/REDACTED/Downloads/Nicotine+.app/Contents/MacOS/lib-dynload/../libcrypto.1.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/REDACTED/Downloads/Nicotine+.app/Contents/MacOS/lib-dynload/../libcrypto.1.1.dylib
[83437] Failed to execute script pyi_rth_certifi
```

**Comment by mathiascode** [comment]
You could use the commands here to generate your own .dmg package: https://github.com/Nicotine-Plus/nicotine-plus/blob/673bb7c580677563c9714648fab54b122d4bec4d/.github/workflows/packaging.yml#L125-L136

I believe I've managed to create functional builds for older macOS versions though. Could you check if this one works on your system (the macos-installer artifact)? https://github.com/mathiascode/nicotine-plus/actions/runs/825101952

**Comment by 2V3EvG4LMJFdRe** [comment]
Great! Well, actually it doesn't work, but I think we found the fix already. When I open it from the terminaI I get the `Cannot find pygobject, please install it` message we found before. So I think you just need to include that export flag somehow. 

After using the export flag, one last thing I had to do to get it running was to install another dependency I was missing, which I got with `pip install semidbm`. It may not be needed now that I already have it, just putting it out there.

**Comment by mathiascode** [comment]
> Great! Well, actually it doesn't work, but I think we found the fix already. When I open it from the terminaI I get the `Cannot find pygobject, please install it` message we found before. So I think you just need to include that export flag somehow.

Is this an error from your own generated build, or the one I provided a link to in my last message? If the build provided in the link doesn't start, could you attach the error from the terminal? I'd like to ship it as an official build with support for older macOS versions.

**Comment by 2V3EvG4LMJFdRe** [comment]
That'd be great. I forgot to specify, it's an error with the build you provided in your message.

```
Last login: Sun May  9 00:20:27 on ttys002
redacted-iMac:~ redacted$ /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/Nicotine+
Cannot find pygobject, please install it.
redacted-iMac:~ redacted$ 
```

**Comment by mathiascode** [comment]
This build should provide a more specific error message: https://github.com/mathiascode/nicotine-plus/actions/runs/825734371

**Comment by 2V3EvG4LMJFdRe** [comment]
Indeed:

```
Last login: Sun May  9 13:26:17 on ttys000
redacted-iMac:~ redacted$ /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/Nicotine+
Traceback (most recent call last):
  File "nicotine", line 232, in <module>
  File "nicotine", line 209, in run
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "pynicotine/gtkgui/frame.py", line 31, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "gi/__init__.py", line 40, in <module>
ImportError: dlopen(/Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/gi/_gi.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/gi/../libpcre.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/gi/../libpcre.1.dylib
[88600] Failed to execute script nicotine
redacted-iMac:~ redacted$ 
```

**Comment by mathiascode** [comment]
Thanks! Can you check if this build works better? https://github.com/mathiascode/nicotine-plus/actions/runs/825867791

**Comment by 2V3EvG4LMJFdRe** [comment]
I'm afraid it doesn't, but I'm sure you're close:

```
Last login: Sun May  9 15:02:39 on ttys000
redacted-iMac:~ redacted$ /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/Nicotine+
Traceback (most recent call last):
  File "nicotine", line 232, in <module>
  File "nicotine", line 209, in run
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "pynicotine/gtkgui/frame.py", line 31, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "gi/__init__.py", line 40, in <module>
ImportError: dlopen(/Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/gi/_gi.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/gi/../libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/redacted/Downloads/macos-installer/Nicotine+.app/Contents/MacOS/gi/../libintl.8.dylib
[90303] Failed to execute script nicotine
redacted-iMac:~ redacted$
```
Think it's only the last line that changed, now pointing to a different dylib file.

**Comment by mathiascode** [comment]
Unfortunately, it seems like this approach will not work on macOS 10.13. I believe these builds work on 10.14 though, which is at least better than our current minimum version of 10.15.

If your managed to create your own build, you'll have to stick with that.

**Comment by 2V3EvG4LMJFdRe** [comment]
That's okay! You were very helpful all along, I have managed to build a working .app with your instructions. I think anyone who stumbles upon this will have enough documentation to build one themselves too. High five, and case closed.
