### ISSUE TITLE
Add added date-time column for wishlist items

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1369]
### Describe the solution you'd like
A date and time presented next to each wishlist item so that the list can be sorted alphabetically (current is A-Z), or by the date added of the wishlist search term.

### Additional context
The reason why this would be useful in my case is that I often find that I add a wishlist item for the name of an album for example, but due to how people name files and folders, it may not match anything, so I also add a wishlist item for one of the more unique tracks names from the album in the hopes of it matching an individual file, and leading me to find a folder containing the full album. Though the approach is often effective, remembering which terms I want to later delete is a chore due to the terms being sorted A-Z, i.e. not grouped with the album name (if it were sorted by date).

The column should not only be aware of the date added, but the time added too, so that ordering won't be A-Z per date, but all terms sorted by age, so-to-speak. Sorting by date could be beneficial in other use cases too, such as pruning very old terms.

Nicotine v3.0.6

**Comment by slook** [comment]
Nice idea. Perhaps the Date/Time implementation you've suggested would be too complex to implement.

I would think there would already be some Index or ID number that could be used to provide the desired function if this was exposed to a sortable column in the list?

**Comment by mathiascode** [comment]
Either method will require a new config structure for the wishlist, since items are currently stored in a plain list where recently searched items are moved to the end.

**Comment by slook** [comment]
The ugly 'Add Wish' checkbox could be removed from the Results header-bar... if the 'Wishlist' button acquired a string from either the current open search-tab, or if the Search text-box has the focus and is not empty, then instant insertion of the desired string into the Wishlist dialog box is done. This should happen automatically without any further manual user interaction.

This would remove the need for a text-box within that Dialog box, and enable the user to add items into their Wish List from typed Search History without using cumbersome copy and paste operations.

Ideally, the caption of the button would change between "Add Wish" and "Wish List", depending upon if a new string is available or not. Either way, it would always open the dialog box to view the list-items, **at which point the MOST RECENTLY ADDED ITEM will be highlighted (based upon the implementation of either method suggested above)** to show that the user's request has been successful, regardless of it's position in the sorted ListView.

In a perfect world, the 'Search Wishlist' dialog-box needs upgrading to a bubble-box, to match the style of the 'Room List' bubble-box.

Sorting by recently added as per @redactedscribe suggestion may help to enable the interface to be simplified, so perhaps a new config structure should be considered as a part of a wider Wishlist overhaul. For me personally, I don't really know if recently searched items are better static or at the top, the management of the list is a chore imo so I have never used the feature beyond a couple of items at a time. I have a list elsewhere.

**Comment by mathiascode** [comment]
Moved to https://github.com/nicotine-plus/nicotine-plus/discussions/1604
