### ISSUE TITLE
Malware detection

### ISSUE THREAD

**Issue by polbyte** [Nicotine-Plus/nicotine-plus#1373]
Nicotine+ version:  3.0.6
Operating System/Distribution: 
Windows 10 (64 bit)

### Describe the bug
HitmanPro.Alert detect malware, Gen:Variant.Bulz.448589 

### Expected behavior
Launching this program blocked by HitmanPro.Alert

### Steps to reproduce the bug
Sorry, I´m not really an expert, I hope that you will solve this bug as soon as you can, I love this program.

### Additional context
Screenshots, logs, stacktraces or relevant information.
![malware-nicotine](https://user-images.githubusercontent.com/51519952/117629832-d99cf200-b17a-11eb-81c3-28e42011d909.jpg)

**Comment by mathiascode** [comment]
Can you check if these builds work? https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/829113388

**Comment by mathiascode** [comment]
Unfortunately, good certificates cost an absurd amount of money (for a small FOSS project) each year, so it's not really an option for us.

**Comment by Inso-m-niaC** [comment]
I had no idea money was involved. Too bad.

On another note: I have come up with a method to send windows balloon tips to Nicotine's Gtk Statusicon. And tray icon functionality is preserved 100% But, i need help to turn it into a module.

**Comment by mathiascode** [comment]
I'm interested in implementing it, I just had other urgent work to do today. Give me a moment.
