### ISSUE TITLE
Change menu action on macOS

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [Nicotine-Plus/nicotine-plus#1377]
### Describe the solution you'd like
I want to request the ability to change the "Prefer dark mode" setting from the View menu, as most programs allowing for a theme change do. I'd use this to be able to control the setting with an Automator script and create a day/night theme schedule.

I also want to point out that the items placed under File should probably go under the main Nicotine+ entry per standards of macOS.

### Additional context
Some images for comparison:

![Mon May 10 16:15:03 -04 2021](https://user-images.githubusercontent.com/11010067/117719515-7d9e9180-b1ab-11eb-9a9c-73a719e18bd9.png)
![Mon May 10 16:15:13 -04 2021](https://user-images.githubusercontent.com/11010067/117719523-7f685500-b1ab-11eb-9107-b77417c861f7.png)
![Mon May 10 16:15:23 -04 2021](https://user-images.githubusercontent.com/11010067/117719527-8000eb80-b1ab-11eb-9acd-729865b4275f.png)

**Comment by mathiascode** [comment]
I've added a Command+, shortcut to avoid disabling the 'Preferences' menu item, but I'm not going to complicate the menu logic further.

**Comment by mathiascode** [comment]
The first request was implemented in this commit. :)
https://github.com/Nicotine-Plus/nicotine-plus/commit/d63cda54f175beb9ca66da7ab8ea7e648cd82bbb
