### ISSUE TITLE
Limit Buddy Shares to Trusted Buddies

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1382]
### Describe the solution you'd like
Currently, if a user is added to your Buddy List, they automatically have access to your Buddy Shares (assuming you have them enabled).

Users on your Buddy List may not actually be more than acquaintances, or only be on your list for the sake of adding a comment to remember who they are, i.e. they're not really your friend (someone you trust).

For this reason, an option to limit _which_ buddies can access your Buddy Shares could be useful, for example, by adding an option next to the "Buddy Shares" checkbox in the Preferences: "Limit Buddy Shares to trusted buddies only". This would require you to have a user on your Buddy List _and_ to have marked them as _Trusted_ via the Buddy List.

Thanks!

Nicotine+ v3.0.7.dev1

**Comment by mathiascode** [comment]
Due to the need for more fine-grained control over shares (https://github.com/Nicotine-Plus/nicotine-plus/issues/991, https://github.com/Nicotine-Plus/nicotine-plus/issues/910), I'm leaning towards a per-share permissions dialog with these preferences.

**Comment by redactedscribe** [comment]
When you say "these preferences", what do you mean?

I'm having a hard time understanding how your response negates my feature request. Based on my intuition, I imagine there'd only need to be a simple check to see whether a user is a buddy and also that they are trusted, to decide whether they can access your Buddy Shares.

Judging by your response, it's not as simple as I had hoped for. In any case, hopefully the idea can be reconsidered at a point in time that makes better sense to do so.

**Comment by redactedscribe** [comment]
When you say "these preferences", what do you mean?

I'm having a hard time understanding how your response negates my feature request. Based on my intuition, I imagine there'd only need to be a simple check to see whether a user is a buddy and also that they are trusted, to decide whether they can access your Buddy Shares.

Judging by your response, it's not as simple as I had hoped for. In any case, hopefully the idea can be reconsidered at a point in time that makes better sense to do so.
