### ISSUE TITLE
Window Preview Shows Preferences Window

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#1397]
Nicotine+ version:  3.0.6
Operating System/Distribution: Window 10

### Describe the bug
When the cursor hovers over the preview of the window from the icon in the start bar, it shows the preferences window even though it isn't open

### Expected behavior
to show a preview of the main program window

### Steps to reproduce the bug
hover cursor over the nicotine+ icon on the start bar then hover over the nicotine+ preview 

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
I can't test this right now, but does this happen when header bars are disabled (Menu -> View -> Use Header Bar)?

**Comment by woollarding** [comment]
Well, now I cannot get it to do that again... maybe there was something
weird on my end. I have updated to the new version of 3.0.6 since then..

**Comment by woollarding** [comment]
so, sorry, I just woke up and am still a little slow ... it is doing it,
both with and without header bar, I forgot I had to hover over the preview
window that pops up above the icon to get it to show the properties window.
