### ISSUE TITLE
Improvement ideas for the search result filters

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1400]
### Describe the solution you'd like
Currently, it's possible to have a "Maximum results per search visible at a time" smaller than "Maximum total results per search". I haven't taken the time to prove it, but I like to keep the former smaller than the latter to help keep Nicotine+'s memory footprint reasonable and its performance from degrading.

Assuming: "Maximum results per search visible at a time": `250`, and "Maximum total results per search" `1000`.

I have some usability improvement ideas for when configured as above:
- Allow pressing the "Results (250)" (specifically the number part) that is shown at the top of each search (above the search result filters). Pressing the button would instantly show any hidden results (i.e. those >250), which could sometimes be more convenient than using the filters to see if any of the possibly 750 hidden results contain what you're looking for.
- When there are hidden results, an asterisk could be placed next to the number, "Results ( 250 * )", giving you a cue to click it. The asterisk could also appear after filtering via the search result filters: "Results ( 123 * ), and clicking it would clear the filters _and_ show all potential 1000 results. Alternatively to an asterisk (which is a bit obscure), a "Show All" button (or similar) could be placed next the the results count and perform the same actions I described.

Other ideas:
- I miss being able to _turn off_ the Result Filters, _not just hide them_, as used to be possible via the main UI. Maybe the "Results Filters" button could be given a Ctrl + click feature to toggle their on/off state, instead of the default plain click which currently just toggles their visibility.
  - Ideally the state would be per set of search results, just as is the state of whether the filters are currently displayed or not. The benefit of being able to toggle the filters on/off is to quickly see any differences _without_ losing the values set in your search filter fields (toggling the active state shouldn't also toggle the fields' visibility - only the plain single-clicking function should do so).
  - The obscurity of this function may not matter due to it being a less used feature I imagine; a tooltip could help reveal its presence: "1 active filter(s) (Ctrl-click to toggle active state)", when deactivated: "Deactivated (Ctrl-click to toggle active state)". The UI should probably reflect this active state by dimming/graying the fields, anything to show that they're disabled.

- A quick way to clear an individual search result filter field without clearing them all could be nice. E.g. the typical "X" to the right of a field. If not done well, these Xs to clear can sometimes be quite annoying to target and click intentionally/successfully.
  - After having thought about it, the icons inside of each search field could be used for this very purpose: on mouse-over, replace the icon with an "X" which then clears the field if pressed (I'd argue that it shouldn't also _set_ the blank field, only _clear_ it).
  - On closer inspection, the icons already double as a method to set the search result filters as a whole (i.e. Enter). This is somewhat convenient since there is no other mouse method to set the filters. If a "Set" button (i.e. to Enter via click) was introduced to the left of the "<x" Clear button, repurposing these icons as I propose wouldn't be a loss of functionality. A "Set" button should likely be present regardless since it's less obscure than having to press a field's icon (assuming wanting to set them via mouse interaction).

Hopefully those make sense and can at minimum serve as some inspiration.

Thanks!

```
Nicotine+ v3.1.0.dev1
```

**Comment by mathiascode** [comment]
> Currently, it's possible to have a "Maximum results per search visible at a time" smaller than "Maximum total results per search". I haven't taken the time to prove it, but I like to keep the former smaller than the latter to help keep Nicotine+'s memory footprint reasonable and its performance from degrading.
> 
> Assuming: "Maximum results per search visible at a time": `250`, and "Maximum total results per search" `1000`.
> 
> I have some usability improvement ideas for when configured as above:
> 
>     * Allow pressing the "Results (250)" (specifically the number part) that is shown at the top of each search (above the search result filters). Pressing the button would instantly show any hidden results (i.e. those >250), which could sometimes be more convenient than using the filters to see if any of the possibly 750 hidden results contain what you're looking for.
> 
>     * When there are hidden results, an asterisk could be placed next to the number, "Results ( 250 * )", giving you a cue to click it. The asterisk could also appear after filtering via the search result filters: "Results ( 123 * ), and clicking it would clear the filters _and_ show all potential 1000 results. Alternatively to an asterisk (which is a bit obscure), a "Show All" button (or similar) could be placed next the the results count and perform the same actions I described.

I think this is needlessly complex, and tries to solve something that shouldn't be an issue. If there are any _proven_ concerns about memory usage and performance, these should be addressed instead (this is something I've focused on improving, and could do more work on it if necessary). You're essentially shooting yourself in the foot by going as low as 250.

**Comment by redactedscribe** [comment]
That's fair. Maybe we shouldn't be allowed to do so if there is no real upside?

Unless there's anything you see fit to implement from what was suggested, this issue can be closed now.

**Comment by mathiascode** [comment]
I've previously thought about removing the "Maximum total results per search" option, since it doesn't serve a large purpose anymore.

This can stay open, I'll take a look at the other suggestions at some point. :)

**Comment by slook** [comment]
> I have some usability improvement ideas... ...Hopefully those make sense and can at minimum serve as some inspiration.

Thank you @redactedscribe indeed your ideas have a valid basis... and yes this has also inspired @mathiascode and myself to look into what exactly causes these types of UI obstructions when using the Result Filters features, as well as some other possible solutions you might be interested in, see issues #1498 #1499 #1500

**Comment by mathiascode** [comment]
Is this still something you want?

**Comment by slook** [comment]
> Add option to "Deactivate search result filters when Result Filters bar is hidden (Alt+R)" as a checkbox in Preferences > Searches > Search Result Filters

The OP's suggestion to synchronize the enabling/disabling of the result filters along with the toolbar visibility is a good one, yes.

**Comment by redactedscribe** [comment]
Thanks for the improvements!
