### ISSUE TITLE
Windows Defender / Trojan:Win32/Zpevdo.B ...False Positive?

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#1401]
Nicotine+ version:  3.0.6
Operating System/Distribution: Window 10

### Describe the bug
this morning nicotine just randomly shut down and windows defender said something about Trojan:Win32/Zpevdo.B 
i googled it and saw some things about false positive? i had to close windows defender to reinstall the application. not sure if this is to do with nicotine or something on my end, but i thought i would mention it

### Expected behavior
not to do that 

### Steps to reproduce the bug
turn on windows defender, 
which i would like to be able to do.. so any assistance is really appreciated, if there is anything i can do to help troubleshoot please do not hesitate to ask

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
This is mitigated in unstable, see https://github.com/Nicotine-Plus/nicotine-plus/issues/1373

Since Nicotine+ 3.1.0 won't be out for a while, I could regenerate the 3.0.6 Windows packages with the changes.

**Comment by woollarding** [comment]
That sounds great, thank you for all the work you do. Nicotine makes
soulseek so much better, it's good to see all the active development.

**Comment by mathiascode** [comment]
Thanks for your kind words! I've now replaced the 3.0.6 Windows packages/installers, so you can just re-download. :)
