### ISSUE TITLE
problem with access to some users.

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1405]
there is a user who has hidden files and I am in his list and have access to them. sometimes I can't download his files, they are queued and nothing happens.with the general search they are visible, but opening its directory it is it freezes and does not give any information about the error. this goes away after he does a second scan.
I checked that I tried to access his files through the standard client soulseekqt. I did not find such a problem in it, downloaded the necessary files, turned off and started nicotine+. immediately, I tried to open its directory, but it did not work. the uploaded files are queued. again, this will pass if he rescans the directory, but after a while it may happen again.
it has a standard client, all ports are open.

FreeBSD 12.2-RELEASE-p6
Nicotine+ 3.1.0.dev1

**Comment by mathiascode** [comment]
Can you enable debug logging (Menu -> View -> Show Log Pane and Menu -> View -> Show Debug Log Controls), enable 'Messages", 'Connections' and 'Transfers' categories, attempt to do what you described, and send me the output?

**Comment by 82d** [comment]
I'll do it when it happens again

**Comment by mathiascode** [comment]
Does this still happen with the latest changes in unstable? It doesn't look like a connection issue according to the logs, as a connection is established (an info bar would also appear if this didn't succeed), but it's strange that no response is sent to the GetSharedFileList message.

**Comment by 82d** [comment]
there was no such error in the latest versions yet.

**Comment by mathiascode** [comment]
Presumably fixed, feel free to re-open if the issue persists.
