### ISSUE TITLE
Wishlists aren't being searched

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#1410]
### Describe the bug
I appear to be getting no "(Wish) ..." searches appearing since upgrading to the latest build. I have quite a few wishlist items and none have appeared in ~20 minutes.

I saw some commit talking about text orientation, probably unrelated, but I use tabs down the left side for my search result tabs.

**Comment by redactedscribe** [comment]
This probably isn't a bug as I'm seeing some now. I'll reopen the issue if there seems to be an actual problem.

**Comment by redactedscribe** [comment]
I'm not sure what exactly to report, but the wishlist results seem much less frequent than before. The tab bar for the results used to be near full, and now maybe only a quarter, and I've had the program open for some hours.

Maybe the frequency at which wishlists items are searched for was changed? Something seems different, and therefore possibly broken.

**Comment by mathiascode** [comment]
I'm not sure what could be wrong here. Wishlist functionality hasn't been touched in a long time, and the server still sends us a wishlist interval of 720 seconds.

**Comment by redactedscribe** [comment]
I must be imagining things then. I have more wishlist tabs open now, it just seemed quite a bit slower than before.

On a related note however, is it possible for searches to consider the folder name that a file exists in? I noticed that a query for ABC for example wouldn't return any results, but a query for a song XYZ did, and the folder XYZ existed in contained ABC in its name. Either there was a timing issue in what I experienced, or folder names aren't considered as valid search results.

**Comment by mathiascode** [comment]
The server decides which search requests go through or not. Searches for certain artists and albums are blacklisted, so no results will be returned for those. It's also possible that searches partially containing a blacklisted word don't go through, such as "tor_pedo_".

**Comment by redactedscribe** [comment]
That makes sense. Thanks.
