### ISSUE TITLE
Every downloaded file remains as "INCOMPLETE[number]Filename"

### ISSUE THREAD

**Issue by Casualreporter** [Nicotine-Plus/nicotine-plus#1411]
Every file i download remains in the incomplete directory with a filename of the type  "INCOMPLETE[number]Filename", although it appears to be correctly completed. This doesn't happen with regular soulseek client.

Sysinfo : 
System:
  Kernel: 5.4.118-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
  parameters: BOOT_IMAGE=/boot/vmlinuz-5.4-x86_64 
  root=UUID=2cdd9729-d081-4f66-a6a6-d810429d0474 rw udev.log_priority=3 
  sysrq_always_enabled 
  Desktop: Cinnamon 4.8.6 tk: GTK 3.24.29 vt: 7 dm: LightDM 1.30.0 
  Distro: Manjaro Linux base: Arch Linux 
Machine:
  Type: Desktop Mobo: Micro-Star model: B450M PRO-M2 (MS-7B84) v: 1.0 
  serial: <filter> UEFI: American Megatrends v: 2.40 date: 12/17/2018 
Battery:
  Message: No system battery data found. Is one present? 
Memory:
  RAM: total: 7.79 GiB used: 1.92 GiB (24.6%) 
  RAM Report: permissions: Unable to run dmidecode. Root privileges required. 
CPU:
  Info: 8-Core model: AMD Ryzen 7 2700 bits: 64 type: MT MCP arch: Zen+ 
  family: 17 (23) model-id: 8 stepping: 2 microcode: 800820D cache: L2: 4 MiB 
  bogomips: 102416 
  Speed: 2054 MHz min/max: 1550/3200 MHz boost: enabled Core speeds (MHz): 
  1: 2054 2: 1908 3: 1377 4: 1376 5: 1377 6: 1378 7: 1378 8: 1376 9: 1326 
  10: 1339 11: 1316 12: 1366 13: 1286 14: 1365 15: 1376 16: 1377 
  Flags: 3dnowprefetch abm adx aes aperfmperf apic arat avic avx avx2 bmi1 
  bmi2 bpext clflush clflushopt clzero cmov cmp_legacy constant_tsc cpb cpuid 
  cr8_legacy cx16 cx8 de decodeassists extapic extd_apicid f16c flushbyasid 
  fma fpu fsgsbase fxsr fxsr_opt ht hw_pstate ibpb irperf lahf_lm lbrv lm mca 
  mce misalignsse mmx mmxext monitor movbe msr mtrr mwaitx nonstop_tsc nopl 
  npt nrip_save nx osvw overflow_recov pae pat pausefilter pclmulqdq pdpe1gb 
  perfctr_core perfctr_llc perfctr_nb pfthreshold pge pni popcnt pse pse36 
  rdrand rdseed rdtscp rep_good sep sev sha_ni skinit smap smca sme smep ssbd 
  sse sse2 sse4_1 sse4_2 sse4a ssse3 succor svm svm_lock syscall tce topoext 
  tsc tsc_scale v_vmsave_vmload vgif vmcb_clean vme vmmcall wdt xgetbv1 xsave 
  xsavec xsaveerptr xsaveopt xsaves 
  Vulnerabilities: Type: itlb_multihit status: Not affected 
  Type: l1tf status: Not affected 
  Type: mds status: Not affected 
  Type: meltdown status: Not affected 
  Type: spec_store_bypass 
  mitigation: Speculative Store Bypass disabled via prctl and seccomp 
  Type: spectre_v1 
  mitigation: usercopy/swapgs barriers and __user pointer sanitization 
  Type: spectre_v2 mitigation: Full AMD retpoline, IBPB: conditional, STIBP: 
  disabled, RSB filling 
  Type: srbds status: Not affected 
  Type: tsx_async_abort status: Not affected 
Graphics:
  Device-1: AMD Mars LE [Radeon HD 8530M / R5 M240] vendor: Sapphire Limited 
  driver: radeon v: kernel alternate: amdgpu bus-ID: 1f:00.0 
  chip-ID: 1002:6607 class-ID: 0300 
  Display: x11 server: X.Org 1.20.11 driver: loaded: ati,radeon 
  unloaded: modesetting alternate: fbdev,vesa display-ID: :0 screens: 1 
  Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.2x8.0") 
  s-diag: 414mm (16.3") 
  OpenGL: renderer: AMD OLAND (DRM 2.50.0 5.4.118-1-MANJARO LLVM 11.1.0) 
  v: 4.5 Mesa 21.0.3 direct render: Yes 
Audio:
  Device-1: AMD Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 
  Series] 
  vendor: Sapphire Limited driver: snd_hda_intel v: kernel bus-ID: 1f:00.1 
  chip-ID: 1002:aab0 class-ID: 0403 
  Device-2: AMD Family 17h HD Audio vendor: Micro-Star MSI 
  driver: snd_hda_intel v: kernel bus-ID: 21:00.3 chip-ID: 1022:1457 
  class-ID: 0403 
  Sound Server-1: ALSA v: k5.4.118-1-MANJARO running: yes 
  Sound Server-2: JACK v: 1.9.18 running: no 
  Sound Server-3: PulseAudio v: 14.2 running: yes 
  Sound Server-4: PipeWire v: 0.3.28 running: no 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: Micro-Star MSI driver: r8169 v: kernel port: f000 bus-ID: 1b:00.0 
  chip-ID: 10ec:8168 class-ID: 0200 
  IF: enp27s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  IP v4: <filter> type: dynamic noprefixroute scope: global 
  broadcast: <filter> 
  IP v6: <filter> type: noprefixroute scope: link 
  WAN IP: <filter> 
Bluetooth:
  Message: No bluetooth data found. 
Logical:
  Message: No logical block device data found. 
RAID:
  Message: No RAID data found. 
Drives:
  Local Storage: total: 1.13 TiB used: 137.73 GiB (11.9%) 
  SMART Message: Required tool smartctl not installed. Check --recommends 
  ID-1: /dev/sda maj-min: 8:0 vendor: Western Digital 
  model: WDS240G2G0A-00JH30 size: 223.58 GiB block-size: physical: 512 B 
  logical: 512 B speed: 6.0 Gb/s rotation: SSD serial: <filter> rev: 0000 
  scheme: GPT 
  ID-2: /dev/sdb maj-min: 8:16 type: USB vendor: Toshiba model: MQ04UBF100 
  size: 931.51 GiB block-size: physical: 512 B logical: 512 B 
  rotation: 5400 rpm serial: <filter> scheme: MBR 
  Optical-1: /dev/sr0 vendor: ATAPI model: iHAS124 F rev: CLDM 
  dev-links: cdrom 
  Features: speed: 48 multisession: yes audio: yes dvd: yes 
  rw: cd-r,cd-rw,dvd-r state: running 
Partition:
  ID-1: / raw-size: 22.98 GiB size: 22.49 GiB (97.89%) used: 10.37 GiB (46.1%) 
  fs: ext4 dev: /dev/sda5 maj-min: 8:5 label: N/A 
  uuid: 2cdd9729-d081-4f66-a6a6-d810429d0474 
  ID-2: /boot/efi raw-size: 99 MiB size: 95 MiB (95.96%) 
  used: 27.7 MiB (29.1%) fs: vfat dev: /dev/sda2 maj-min: 8:2 label: N/A 
  uuid: F27D-3EB2 
  ID-3: /media/toshiba raw-size: 931.51 GiB size: 931.51 GiB (100.00%) 
  used: 99.47 GiB (10.7%) fs: ntfs dev: /dev/sdb1 maj-min: 8:17 
  label: TOSHIBA EXT uuid: 7C7468E37468A21E 
  ID-4: /media/win raw-size: 200 GiB size: 200 GiB (100.00%) 
  used: 27.86 GiB (13.9%) fs: ntfs dev: /dev/sda4 maj-min: 8:4 label: N/A 
  uuid: 0CEE8225EE8206E4 
Swap:
  Alert: No swap data was found. 
Unmounted:
  ID-1: /dev/sda1 maj-min: 8:1 size: 499 MiB fs: ntfs label: N/A 
  uuid: 2070DD5970DD366E 
  ID-2: /dev/sda3 maj-min: 8:3 size: 16 MiB fs: <superuser required> 
  label: N/A uuid: N/A 
USB:
  Hub-1: 1-0:1 info: Full speed (or root) Hub ports: 10 rev: 2.0 
  speed: 480 Mb/s chip-ID: 1d6b:0002 class-ID: 0900 
  Device-1: 1-6:2 info: Logitech Keyboard K120 type: Keyboard,HID 
  driver: hid-generic,usbhid interfaces: 2 rev: 1.1 speed: 1.5 Mb/s 
  power: 90mA chip-ID: 046d:c31c class-ID: 0300 
  Device-2: 1-7:3 info: Logitech Unifying Receiver type: Keyboard,Mouse 
  driver: logitech-djreceiver,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s 
  power: 98mA chip-ID: 046d:c534 class-ID: 0301 
  Hub-2: 2-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 speed: 10 Gb/s 
  chip-ID: 1d6b:0003 class-ID: 0900 
  Hub-3: 3-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 
  speed: 480 Mb/s chip-ID: 1d6b:0002 class-ID: 0900 
  Hub-4: 4-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.0 speed: 5 Gb/s 
  chip-ID: 1d6b:0003 class-ID: 0900 
  Device-1: 4-3:2 info: Toshiba America External USB 3.0 type: Mass Storage 
  driver: usb-storage interfaces: 1 rev: 3.0 speed: 5 Gb/s power: 896mA 
  chip-ID: 0480:0901 class-ID: 0806 serial: <filter> 
Sensors:
  System Temperatures: cpu: 39.4 C mobo: 0 C gpu: radeon temp: 34.0 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 305 Uptime: 23m wakeups: 0 Init: systemd v: 247 tool: systemctl 
  Compilers: gcc: 10.2.0 Packages: pacman: 1156 lib: 375 flatpak: 0 
  Shell: Bash v: 5.1.8 running-in: gnome-terminal inxi: 3.3.04

**Comment by mathiascode** [comment]
Only thing I can think of is some kind of permission error with the download folder. Are there any errors in the log pane?

**Comment by Casualreporter** [comment]
Yeah, the download paths were incorrectly configured. I didn't read the log panel because for some odd reason it always gives a message about a failed download, while the download is in fact completed, so i always ignore it.
One question : if an error was encountered during the download, why it's reported as complete?

**Comment by mathiascode** [comment]
Could you post the errors you've received so far, so I could take a look at the issue?

I've now pushed a fix for the issue where these downloads were marked as finished.

**Comment by Casualreporter** [comment]
Unfortunately, it doesn't give any specific error, just download failed. It seems to me that this happens at the beginning of the download, but in the end the file is downloaded correctly.

**Comment by mathiascode** [comment]
Is "download failed" the literal message you're getting? I can't find any location in the codebase that would yield a similar message. Which file and user is causing this?

**Comment by Casualreporter** [comment]
I'm starting to think that this is a translation error. I'm not using the english version and i didn't found any way to switch the language, so i don't know exactly how the original literal message should be. But the message is printed every time a download starts, for every file and every user; maybe is just a message about the download starting?

**Comment by Casualreporter** [comment]
I casually managed to find the error: in the file po/it.po i left a comment. As i thought is a wrong translation, is just a message about the started download.

**Comment by mathiascode** [comment]
Good catch! I've updated the string with your suggestion.

As a side note, these download started/finished messages can be turned off in the next version of Nicotine+, if desired.
