### ISSUE TITLE
Exclamation point in the chat tab bar i have not seen before

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#1413]
Nicotine+ version:  3.0.6(updated)
Operating System/Distribution: Windows 10

### Describe the bug
there was an icon at the far right of the tabs under chat, hovering over it said something about unread messages, when i clicked on it i got this

Nicotine+ has encountered a critical error and needs to exit. Please copy the following error and include it in a bug report:

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'get_text'
Traceback:   File "pynicotine/gtkgui/widgets/iconnotebook.py", line 580, in on_unread_notifications_menu

then nicotine+ closed, restarted and i don't see that icon now

### Expected behavior
im not sure what that is so im not sure.. 

### Steps to reproduce the bug
i don't know, sorry 

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
The icon is supposed to show a list of unread tabs, but there's an error that breaks it when you close tabs in 3.0.6. It's currently fixed in unstable.
