### ISSUE TITLE
Tried unpacking zip, scanner shows  Gen:Variant.Bulz.495404

### ISSUE THREAD

**Issue by vongoh** [Nicotine-Plus/nicotine-plus#1414]
I tried installing the latest windows build 3.06.  On unpacking the zip Bitdefender says:

``
The file C:\Program Files\Nicotine+\Nicotine+.exe is infected with Gen:Variant.Bulz.495404 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean
``

Thoughts?

**Comment by mathiascode** [comment]
False positive, looks like AV vendors have started flagging us again. There's nothing that can be done other than reporting the false positives, unfortunately.
