### ISSUE TITLE
in Download tab, the Queue Position column is empty

### ISSUE THREAD

**Issue by gits68** [Nicotine-Plus/nicotine-plus#1416]
Nicotine+ version:  3.0.6
Operating System/Distribution: Windows 10

### Describe the bug
The Queue Position column is empty in the Download tab

### Expected behavior
Queue position of files

### Steps to reproduce the bug
none

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Queue positions are requested every three minutes, so it could take some time for it to display. Is there a file that never displays a queue position?

**Comment by mathiascode** [comment]
I haven't found a case where queue positions don't appear. Feel free to reopen the issue if you've found one.
