### ISSUE TITLE
It's possible to open more than one instance of Nicotine+

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1418]
Is this something that should be happening? Maybe there is a use for it.

An "Allow multiple instances" option may be useful to make it optional.

**Comment by mathiascode** [comment]
I'm guessing this is some Windows-specific quirk. On Unix-based systems, only one instance can be open at a time.

Allowing multiple instances would add complexity around supporting multiple config files and DBs for shared files, which isn't something I want to do.

**Comment by slook** [comment]
Another instance of the application can occur by running with the `--headless` command line switch for example `nicotine -n`

**Comment by mathiascode** [comment]
I don't recommend doing that without also specifying the --config and --user-data arguments, since a shares db can only be accessed by a single instance.

**Comment by mathiascode** [comment]
Single-instance behavior now works properly in Windows: https://github.com/nicotine-plus/nicotine-plus/commit/3840952eb2d0f4626cf1e5bc89fc6c0894e6d36e

**Comment by majkinetor** [comment]
> Single-instance behavior now works properly in Windows: https://github.com/nicotine-plus/nicotine-plus/commit/3840952eb2d0f4626cf1e5bc89fc6c0894e6d36e

I can't confirm this. I can open multiple instances (portable version, Windows 10)

![image](https://github.com/nicotine-plus/nicotine-plus/assets/85767/727cf60d-9fcb-499f-a2c4-4aae679946fe)

**Comment by mathiascode** [comment]
Is gdbus.exe running? I can't reproduce the issue when downloading the portable zip, and launching the Nicotine+.exe multiple times. It only starts a single instance.

**Comment by majkinetor** [comment]
Regarding my portable installation, I just copy new version over the previous one.

**Comment by mathiascode** [comment]
> Regarding my portable installation, I just copy new version over the previous one.

Ah, that would explain it. There's probably a mix of old and new dlls causing issues (and gdbus.exe also moved from the lib folder to the root recently).

**Comment by majkinetor** [comment]
Yeah... not sure why I did that. Thanks.
