### ISSUE TITLE
Force download a filtered file

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1419]
### Describe the solution you'd like
When downloading a folder, all items within it are added to your Downloads list. This includes any files that are filtered, such as "folder.jpg". Most of the time, this is great, but if by chance I want to download the filtered file, it'd be convenient if it showed an additional context menu option "Force download" or something to overrule the filter, as there doesn't appear to be another way to download the file. One must open the preferences and disable the filter, save, then choose Retry on the file to, then enable your filters again after downloading. Not the hardest task, but a simpler and more intuitive method could be nice.

Nicotine+ v3.1.0.dev1

**Comment by mathiascode** [comment]
This needs design ideas, preferably something that isn't easily clicked/activated by accident, and doesn't add more noise to our context menus.

**Comment by slook** [comment]
Surely, it should be only the Download Folder functions that are affected by the Download Filters.

If the user explicitly demanded a Download File(s), then this explicit user selection / instruction is unambiguous, they want the file(s). If they don't want it, then the user already has the ability to simply de-select it, or just not click on it.

- My idea: The Download Filters should not be applied to individual file downloads at all, only Folders, no extra menu override options are needed. Perhaps change a label or two in Preferences > Downloads to include the word "Folder" somewhere.

Anyway I've long thought the "Download Filters" name conflicts with "Result Filters", it is confusing... consider:
**"Exclusions for Folder Downloads:"** or something along those lines?

**Comment by redactedscribe** [comment]
There are two approaches: override the download filters when choosing to download items from the Search Files tab, or, override the filters after the fact via the Downloads tab.

If using the latter approach, maybe there could be logic to say using Retry on a file that was filtered will ignore the filters and download it instead, but only if Retry was used on a selection/file, and not on a folder. This keeps the action being explicit: Retry on a folder and the download filters are honoured, Retry on a file/selection and the download(s) is forced. For selections that qualify for a force download, the label could read "Retry (override filter)". In most cases, you want your filters to filter, so perhaps this two-step process (download files, then go through and force the filtered files) would be fine as it should be uncommon for the user for the user to want to do this, else why do they have a given filter in place to begin with?

It is however simpler using the first of the two approaches as there need only be one step. Though additional context menu items is something @mathiascode wants to avoid, I think it would be a sleek experience if a checkbox was added to the top of the context menu, checkable specifically _without the context menu closing_, labelled "Ignore Download Filters". This would mean one could right-click a file/folder as normal, set the download filters to be bypassed, and proceed to click the desired download option. This checkbox would _not_ be the same option as the Preferences' "Enable download filters" option, but rather an option that augments the _current_ download action, i.e. if you right-click another file/folder, the checkbox would default to being unchecked and one would need to re-check it to bypass the filters for the next download action. This aims to meet the requirement of not being "easily clicked/activated by accident", as it's on a per-download basis so user errors would be minimal (all they must do is re-download and _not_ check the checkbox next time).

Both ideas solve the issue alone, but perhaps it's not a matter of either-or: sometimes you'll know prior to downloading that you'll want every file and to ensure nothing is filtered, in other cases, you may realise that you do actually want that folder.jpg as you couldn't find any better image online, for example.

@slook's idea of only applying to folders is a nice simplification, and I think it could be what users want in most cases, so I think it's a valid option too.

On a side note, reducing the duplicity of the download options could be done via combining the Download File(s) To.../Download Folder(s) To... entries with the non-"To..." variants. Tooltips could be used to say holding Ctrl on-click (or some other modifier) will let you specify a location to download to. But maybe this would obscure the feature? I for one only rarely use downloading to a custom location, so maybe these don't need to be displayed up-front.

**Comment by slook** [comment]
I agree that downloads with the "Filtered" status are a stubborn pain, and it is baffling to work out what this means unless you know what your looking for. Some users think that it is related to the Result Filters which puts them off using that feature.

I think @redactedscribe 's suggestion about the Retry/Resume overriding/disregarding the Download Filters is a satisfactory remedy for the issue, as no additional context menus are needed. Perhaps the "Resume" label(s) can be changed to "Retry" for this case, this would be a good enough indicator that force downloading a Filtered file is possible by clicking this button.

Ultimately the whole situation could be avoided by only applying the Download Filters to Download Folder functions, as applying them to individual files is a just a hindrance in my opinion, but I guess everyones specific use patterns vary so perhaps I could be mistaken. Unfortunately, the logic for the Download Filters is in the transfers module, by which the origin of the download action is forgotten by then, so this will require significant changes to the Download mechanisms and won't be easy to implement (idk, perhaps some sort of "type=file/folder" flag argument can be passed between the functions?).

Regarding your side note, whilst I agree that modifier keys are very useful for shortcuts, I am against any function being totally dependent on those keys for execution. Furthermore, our popover menus don't support displaying the shortcut bindings nor do they support in-menu tooltips, so combining menu features is not possible. However, thanks to some recent work by @mathiascode on the keybinding mechanics, modified Click events will be possible now, so in future this could enable such actions at the point of adding a download to the queue with a 'Shift override' to indicate this download will be unfiltered, and a 'Ctrl override' to indicate a custom destination folder dialog is required for this download.

I have started to experiment with using modified activation events on the "Return" key in https://github.com/nicotine-plus/nicotine-plus/pull/1587 please feel free to give [/gtkgui/userbrowse.py](https://github.com/slook/nicotine-plus/blob/patch-3/pynicotine/gtkgui/userbrowse.py) a go, and I would appreciate your feedback on it (just imagine the Return key is Double-Click). Lessons learned during this experiment may help in the case of Filtered files in the Downloads transferlist.py module we are discussing here.

**Comment by cproensa** [comment]
> I think @redactedscribe 's suggestion about the Retry/Resume overriding/disregarding the Download Filters is a satisfactory remedy for the issue, as no additional context menus are needed. Perhaps the "Resume" label(s) can be changed to "Retry" for this case, this would be a good enough indicator that force downloading a Filtered file is possible by clicking this button.

simple enough and i think solves the initial isse, which i also have found myaself in, several times...
I'd be ok even if the "resume" text is kept unchanged. Indeed, the first time i was in this situation, my instinct was to use "resume" to make it download (without success, as we alredy know...)

> However this idea would make the Filters less effective if the user wishes to Pause/Resume for some other reason.

Idk, if the "filtered" is a state assigned when created in the queue, and is not persistent... If so, once the user "force download" the item and the state is different than "filtered", the normal pause/resume actions should be the only ones available.

**Comment by slook** [comment]
> Idk, if the "filtered" is a state assigned when created in the queue, and is not persistent... If so...

Afaik the state is checked against the current Download Filters configuration every time the stored download is initialized/resumed, so it is persistent.

**Comment by mathiascode** [comment]
My issue with ignoring the filter when resuming, is that you could bypass it unintentionally if you resume user/folder rows.

I would be fine with a "Force download" menu item that's only visible when the selection contains a filtered file.

> simple enough and i think solves the initial issue, which i also have found myself in, several times...

Out of curiosity, why are you using download filters?

**Comment by cproensa** [comment]
> I would be fine with a "Force download" menu item that's only visible when the selection contains a filtered file.

thats what i was supporting too

> Out of curiosity, why are you using download filters?

First, because there were some enabled by default.
After a couple of situations like this, i opted to diable them. But i can see their utility, and if i could manually force certain files, i would probably enable them for all images, and then pick one image, if needed, in the downloads tab.

**Comment by mathiascode** [comment]
> "if the selection is only of one, filtered, file"

I like this idea, and it would require minimal changes in our code. I'll give it a try.

**Comment by mathiascode** [comment]
Download filters were disabled by default a while back, but I've also removed `folder.jpg` from the default filters in https://github.com/nicotine-plus/nicotine-plus/commit/a15973fc23018cd12f805f7d83dd9423443165e7. It didn't fit in with the rest of the default filters for junk files.
