### ISSUE TITLE
Tab go out off the screen where there are many, they should use several lines instead.

### ISSUE THREAD

**Issue by zebulon-1st** [Nicotine-Plus/nicotine-plus#1420]
### Describe the solution you'd like
In the main tabs (Downloads, Uploads, Search files, ...), when there are a lot of child tabs, they go off the screen, which is impractical, as you have to scroll to reach them again, which can be quite annoying.
Instead, it would be better if the child tabs occupied several lines, so that they all remain visible on the screen and are directly accessible.

**Comment by mathiascode** [comment]
This isn't possible with GTK. I'll check if I can restore scroll-wheel functionality on tabs, to make scrolling somewhat easier at least.

**Comment by zebulon-1st** [comment]
>_This isn't possible with GTK._

Oh. That's sad.

>_I'll check if I can restore scroll-wheel functionality on tabs, to make scrolling somewhat easier at least._

That would be great. Thx.
