### ISSUE TITLE
Search main tab: wish tabs always extra.

### ISSUE THREAD

**Issue by zebulon-1st** [Nicotine-Plus/nicotine-plus#1422]
### Problem
In the main search tab, files found from the whishes list are placed in a new tab (with the search words preceded by the word "(Wish)"), even when a tab containing the search words already exists. This results in two tabs instead of one.

### Solution
It would be better if, in the case where a tab already exists with the desired search words, that this tab is then renamed with the term "(Wish)" added in front of the search words, instead of systematically opening a new one.

(This would shorten the long line containing all those tabs that cannot be on several lines).

**Comment by mathiascode** [comment]
Due to several edge cases to take into consideration when implementing this, I'd rather avoid the complexity.
