### ISSUE TITLE
Can't click anything when in fullscreen

### ISSUE THREAD

**Issue by ktfjulien** [Nicotine-Plus/nicotine-plus#1423]
When I maximize the app, the UI becomes "transparent" and I can't click anything. It looks fine and like I'm focused, but when I try to click anything, it registers on whatever application is behind Nicotine+. Trying to drag it out of full screen also doesn't work. I can click on the three buttons in the top right, when I hit un-maximize, the program behaves properly again.
If you'd like a video demonstration I'd be happy to show you.

Thanks.

**Comment by mathiascode** [comment]
What's your Nicotine+ version and OS? A video demonstrating the issue would be good to have.

**Comment by ktfjulien** [comment]
Windows 10 Pro 21H1. Version 3.0.6 of N+. Where can I send one in, Is there a discord?

**Comment by mathiascode** [comment]
Uploading a screen recording on https://streamable.com/ or a similar service is fine.

**Comment by mathiascode** [comment]
I tried to reproduce this issue in an older installation of Windows 10, but wasn't able to. Could you check the following points?

- Disable the header bar (Menu -> View - Enable Header Bar). Does the issue still occur?
- Does the issue occur in other GTK-based programs, such as Gaphor? https://gaphor.org/download.html

**Comment by ktfjulien** [comment]
Sorry for the wait, got busy.

When I went to record the issue and try out your suggestions, the problem went away. I haven't been able to recreate it since, fullscreen is working properly. I reinstalled and it still hasn't come back.

**Comment by mathiascode** [comment]
Seems like a fluke. Feel free to reopen the issue if you can reproduce the issue again.
