### ISSUE TITLE
Finished Downloads Autoclearing

### ISSUE THREAD

**Issue by AlreadyFree** [Nicotine-Plus/nicotine-plus#1427]
Nicotine+ version:  3.0.6
Operating System/Distribution: Windows 7

### Describe the bug
Finished downloads are autoclearing even the the setting for it is unchecked in the settings.

**Comment by mathiascode** [comment]
If you're talking about finished downloads clearing when restarting Nicotine+, this behavior has been changed in the unstable version.

**Comment by AlreadyFree** [comment]
Yes it's doing it after a restart. I thought it was doing it after a time even before restarting. But maybe I was wrong about that. I'll check out the unstable version. Thanks.

**Comment by AlreadyFree** [comment]
I can confirm the unstable version is working, so this issue is closed.
