### ISSUE TITLE
Color Username to match online status

### ISSUE THREAD

**Issue by AlreadyFree** [nicotine-plus/nicotine-plus#1429]
### Describe the solution you'd like
Any chance to implement color matching of usernames in the transfers tab to their status (green/orange/red) to more easily see when a user goes offline? Or a colored dot by their name would work too, but changing the username font color to match their online status seems like it would probably be easier.

**Comment by mathiascode** [comment]
Is the "User logged off" status of active and queued transfers not enough?

**Comment by AlreadyFree** [comment]
It's just a lot faster to review the status of a long transfer list with color coded names. I guess I'm just used to that since I'm still adjusting from moving from the official client and the status is colored coded there in the transfer list. It was just a suggestion, but I thought it would be an improvement.

**Comment by mathiascode** [comment]
Fair enough. Since the official client also seems to track statuses for each user in the transfer list, doing so shouldn't be an issue for us either.

**Comment by AlreadyFree** [comment]
Awesome! Thanks

**Comment by mathiascode** [comment]
This request is blocked until we've ported the remaining user lists to the new TreeView class.

**Comment by DeathStalker77** [comment]
Just wondering what the current status of this is?  :-)

**Comment by mathiascode** [comment]
> Just wondering what the current status of this is? :-)

I still need to port tree/listviews from Gtk.TreeView to Gtk.ColumnView, then I'll start looking into feature requests related to them. This will happen at some point after 3.3.0, the good news however is that preparation work to make this port easier was recently finished.

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/2940.

The plan is to grey out transfer rows with the "User logged off" status.

**Comment by Rings4** [comment]
> Closing in favor of #2940.
> 
> The plan is to grey out transfer rows with the "User logged off" status.

Sounds good, how about the other statuses? As mentioned above, on my soulseek I had green = completed, light blue = transferring, dark blue = queued, and red = cancelled/aborted. Ideally these different statuses would be able to have their colours set up how the user likes it in the settings.

**Comment by slook** [comment]
> how about the other statuses?

See https://github.com/nicotine-plus/nicotine-plus/issues/2940#issuecomment-2299619263

**Comment by Rings4** [comment]
> > how about the other statuses?
> 
> See [#2940 (comment)](https://github.com/nicotine-plus/nicotine-plus/issues/2940#issuecomment-2299619263)

Wonderful to hear, thank you!
