### ISSUE TITLE
Question: 1.4.3 - Columns Hiding?

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#143]
Hello,

In Linux using 1.4.1, when I searched for a Song, the Columns; User - Filename - Size etc... I could right click on them and hide them.

In 1.4.3, does it also have the ability to hide these columns, because if it does, I'm not seeing it?

THANKS

**Comment by zniavre** [comment]
after 15years of nic+ i did not know this option but it works in 1.4.3 for me at least  :o)

**Comment by 0pLuS0** [comment]
@zniavre When you know something, please share it.

So how did you get this to work?

```P.S. I forgot to mention I am using Linux.```

**Comment by zniavre** [comment]
i just try what you told about right click and it works ... 

slackware yeah i saw your discussion about compiling...
im also using linux ubuntu after 10years of gentoo

**Comment by mathiascode** [comment]
Any errors in the terminal when attempting to right-click?

**Comment by 0pLuS0** [comment]
@zniavre  thanks...

@mathiascode 

Nothing in the term when doing a Right Click, and now I notice a very faded outline of a window trying to appear when I try and right click.

Could this be because Slack 14.2 uses an older GKT3? gtk+3-3.18.9

THANKS

**Comment by mathiascode** [comment]
Could be, but I suspect something else is going on. I'll create a Slack installation to investigate.

**Comment by 0pLuS0** [comment]
@mathiascode 

Ok...

But I see this ```Port to Python3``` listed, I thought Nicotine+ is compiled/running against Python3?

THANKS

**Comment by kiplingw** [comment]
Nicotine+ isn't compiled. It's written in Python and interpreted with the Python 3 interpreter.

**Comment by 0pLuS0** [comment]
@kiplingw 

Yes I know my bad, not sure what I was thinking... :(

I'm just trying to figure out why  this ```Port to python3 #99``` is being mentioned?

Thanks

**Comment by mathiascode** [comment]
I simply added this issue to my investigation list of Python3/GTK3 regressions: https://github.com/Nicotine-Plus/nicotine-plus/issues/99#issuecomment-631780155

**Comment by 0pLuS0** [comment]
I cloned from the Master Nictone Branch and this now works! 

THANKS
