### ISSUE TITLE
How to access option to close only window (keep sharing files)?

### ISSUE THREAD

**Issue by 2ver** [Nicotine-Plus/nicotine-plus#1435]
Nicotine+ used to ask me if I wanted to completely close the app or just the window every time I pressed the "kill window" keybinding in my window manager. I'm pretty sure I accidently clicked "remember my choice" one time and now I cannot find a setting to change that anywhere. Am I complely overlooking something or is it really not there after you check the "remember" box?

**Comment by alekksander** [comment]
https://i.imgur.com/xZL0pMS.png

**Comment by alekksander** [comment]
![Uploading Screenshot_20210626_092122.png…]()

**Comment by alekksander** [comment]
![Screenshot_20210626_092122](https://user-images.githubusercontent.com/3148302/123505538-f7a5af80-d65f-11eb-80e4-61e1d4432d02.png)

**Comment by 2ver** [comment]
Thank you! I went through the settings at least three times but I guess I sort of skimmed over the icons tab since it didn't make much sense to me to have that setting there. Maybe a search of some sort could be beneficial for the settings page? Regardless, thanks :)

**Comment by mathiascode** [comment]
> since it didn't make much sense to me to have that setting there. Maybe a search of some sort could be beneficial for the settings page? Regardless, thanks :)

Correct, I think the location of this setting doesn't make sense anymore. The exit dialog used to mention closing to the tray at one point, but this has since been changed. I'm not quite sure where this setting could be moved without creating a new settings page, any ideas are welcome.

A search feature would likely require rewriting the settings dialog, so I'd rather not implement it.

**Comment by mathiascode** [comment]
I think I'll move the tray settings to the notifications page.

**Comment by mathiascode** [comment]
Current status as follows. UI-related settings are now unified under a single page.
![ui](https://user-images.githubusercontent.com/8754153/123556240-b7931980-d792-11eb-9eac-421e67563448.png)
![tray](https://user-images.githubusercontent.com/8754153/123556239-b6fa8300-d792-11eb-81f1-1d753d99e959.png)

**Comment by alekksander** [comment]
where did the icons settings go?
