### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 82d** [Nicotine-Plus/nicotine-plus#1436]
Nicotine+ has encountered a critical error and needs to exit. Please copy the following error and include it in a bug report:

Type: <class 'KeyError'>
Value: '@@emhci\\My OldSkool Collection 1991 - 1995'
Traceback:   File "/usr/home/user/Desktop/BOX/git/nicotine-plus/pynicotine/gtkgui/userbrowse.py", line 1053, in on_search
    path = self.dir_store.get_path(self.directories[directory])

Nicotine+ 3.1.0.dev1
FreeBSD 12.2-RELEASE-p6

**Comment by mathiascode** [comment]
Were you doing something special when this occurred? I'm not sure how a desync between the shares list and directory list is possible.

**Comment by 82d** [comment]
refresh files view the shared folder of one of the users. at the same time, it seems that my ip address has changed.
