### ISSUE TITLE
parameter reconnect every

### ISSUE THREAD

**Issue by gits68** [nicotine-plus/nicotine-plus#1439]
### Describe the solution you'd like
would it be possible to have a reconnect_every parameter in General->Server in minutes ?
or maybe the Automatic renew port mapping works if UPnP is disabled ?

### Additional context
sometimes, uploads maybe staled and it is needed to disconnect/reconnect to restart pending uploads.
also, sometimes, the download queue are short (25 files), and it is needed to disconnect/reconnect to requeue "too many files" every 10 or more minutes or the files are requeued only if the remote user disconnect/reconnect...

**Comment by mathiascode** [comment]
> sometimes, uploads maybe staled and it is needed to disconnect/reconnect to restart pending uploads.

Is this a hypothetical situation, or does this still happen today? I know this was an issue in the past, but I thought I had fixed all causes in recent months.

> also, sometimes, the download queue are short (25 files), and it is needed to disconnect/reconnect to requeue "too many files" every 10 or more minutes or the files are requeued only if the remote user disconnect/reconnect...

Selecting the files and pressing 'Retry' should work.

**Comment by gits68** [comment]
> > sometimes, uploads maybe staled and it is needed to disconnect/reconnect to restart pending uploads.
> 
> Is this a hypothetical situation, or does this still happen today? I know this was an issue in the past, but I thought I had fixed all causes in recent months.

well, this seems to be fixed since a month ago.
 
> > also, sometimes, the download queue are short (25 files), and it is needed to disconnect/reconnect to requeue "too many files" every 10 or more minutes or the files are requeued only if the remote user disconnect/reconnect...
> 
> Selecting the files and pressing 'Retry' should work.

I know, but recently, someone only have a queue limit of 20 files while a 10 parts collection have 200 files, have to have an eye every 20 downloaded files to fill up 20 another files, this take me 2 weeks bcoz the user stay connected not so long and I often miss the time ie was connected or forgot to refill the queue.

**Comment by mathiascode** [comment]
> I know, but recently, someone only have a queue limit of 20 files while a 10 parts collection have 200 files, have to have an eye every 20 downloaded files to fill up 20 another files, this take me 2 weeks bcoz the user stay connected not so long and I often miss the time ie was connected or forgot to refill the queue.

I could probably add a timer that periodically retries such files, but the interval has to be somewhat long. After all, the limit exists for a reason, and I don't want to be responsible for excessive download requests from Nicotine+ clients.

**Comment by mathiascode** [comment]
> I could probably add a timer that periodically retries such files, but the interval has to be somewhat long. After all, the limit exists for a reason, and I don't want to be responsible for excessive download requests from Nicotine+ clients.

Looks like SoulseekQt also re-queues these files. From the changelog at http://www.slsknet.org/news/changelog:

`Treat downloads denied with 'too many files' or 'too many megabytes' as queued so that they'll be automatically requeued.`

I'll check what the interval is in SoulseekQt and do something similar.

**Comment by mathiascode** [comment]
Additional information: https://www.slsknet.org/news/node/3025
