### ISSUE TITLE
Shift + Mouse wheel a fall

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1440]
Nicotine+ 3.1.0.dev1
FreeBSD 12.2-RELEASE-p6
Frequent falls during certain actions. 
Shift + Mouse wheel
this happens regularly but not so often. I noticed that the fall is always caused by the action of the mouse wheel with the Shift key held down.

**Comment by mathiascode** [comment]
I'm not sure what "fall" means in this case. Could you elaborate?

**Comment by 82d** [comment]
the app is shutting down

**Comment by mathiascode** [comment]
Perhaps this is a GTK-related regression on your system. Have you checked if other GTK programs have similar issues? Afaik, we don't do anything special when scrolling that would cause something like this.

**Comment by 82d** [comment]
not anywhere else. I haven't seen Nicotine+ on the stable version either. I have falls mostly all because of this. maybe it's not just the Shift + Mouse wheel. but it definitely happens during some action.

**Comment by 82d** [comment]
now I have specially switched to the stable version to observe.

**Comment by 82d** [comment]
I used the stable version all evening, deliberately did everything to try to cause a fall as it was in the dev version. crash did not happen everything works as it should. the conclusion is that the dev versions are crashing for some reason.

**Comment by mathiascode** [comment]
Thanks! It's good that this isn't a GTK regression, but there have been so many changes to Nicotine+ since 3.0.6 that the issue could be caused by anything. I'll install FreeBSD 12.2 and try to reproduce the issue. If that doesn't work, we can perhaps start looking into getting some backtraces.

**Comment by mathiascode** [comment]
@82d Could you try the latest unstable? Another crash issue was fixed, which most likely caused this one too.

**Comment by 82d** [comment]
ок

**Comment by mathiascode** [comment]
Any crashes so far?

**Comment by 82d** [comment]
so far, this has not happened. only unfortunately I didn't use it very often. but in the background, it was constantly open.

**Comment by 82d** [comment]
the falls stopped happening. I will write immediately if I notice.

**Comment by mathiascode** [comment]
Probably taken care of in the other crash fix, feel free to reopen if needed.
