### ISSUE TITLE
Global Connect/Disconnect concept for chat rooms

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1443]
### Describe the solution you'd like
A global connect/disconnect feature for the chat rooms you are a part of. Currently to achieve this one would need to leave every chat room individually and re-join each one when wanting to "reconnect". A connect/disconnect feature would not leave or join, but just determine if you are connected or not.

**Comment by mathiascode** [comment]
Why is this feature required in addition to the global disconnect state?

**Comment by redactedscribe** [comment]
Having thought about it, I have no good argument for it being a required feature, but it could potentially be nice to have. In my case, I don't use the chat rooms for more than checking if anything interesting has be said, and rarely. The only real downside I experience is the random messages from random people, which I assume come messaging users from the user list: the more rooms I'm in, the more chance of spam. If I was disconnected, I wouldn't receive these. I'd be fine if a user could message me directly if they've done so via User(s) > Send Message via a shared file of mine, but whether or not that's coupled with the chat room messaging, I don't know, and so may be a lot of work. Ultimately, I'd say it's an inessential feature which needs a stronger argument for its implementation.

**Comment by slook** [comment]
Agreed I think adding a secondary Connect/Disconnect paradigm would cause unnecessary confusion. The functions of the slsk network protocol are inseparably linked, to separate them artificially would be considerable effort for little gain.
