### ISSUE TITLE
Critical error upon attempted chat

### ISSUE THREAD

**Issue by therabbitgirl** [nicotine-plus/nicotine-plus#1446]
Nicotine+ version:  3.1.0.dev1
Operating System/Distribution: Ubuntu GNU/Linux

### Describe the bug
Upon attempting to type into a chatroom, Nicotine+ experiences a critical error and must exit.

### Expected behavior
Message typed being sent to the chat without a critical error requiring the closing of the app?

### Steps to reproduce the bug
Open a chat room, try to chat, used to work fine, not sure when it stopped working.

### Additional context

Screenshots, logs, stacktraces or relevant information.

Nicotine+ has encountered a critical error and needs to exit. Please copy the following error and include it in a bug report:

Type: <class 'TypeError'>
Value: send_message() takes 2 positional arguments but 3 were given
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/widgets/textentry.py", line 426, in on_enter
    self.send_message(self.entity, text)"
Type: <class 'TypeError'>
Value: send_message() takes 2 positional arguments but 3 were given
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/widgets/textentry.py", line 426, in on_enter
    self.send_message(self.entity, text)

**Comment by mathiascode** [comment]
I believe I fixed this in https://github.com/nicotine-plus/nicotine-plus/commit/c334c27d0484e2c716a0f4d961fe93a290b01674. The error should go away if you update to the latest unstable.
