### ISSUE TITLE
Anyone willing to maintain an official Nicotine+ Debian package?

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#1448]
We would greatly appreciate if someone had the time to reintroduce and maintain the official Nicotine+ Debian package, which was previously removed when Nicotine+ still used Python 2: https://tracker.debian.org/pkg/nicotine

If you're interested, or know anyone else who would be interested in maintaining the official Debian package, please let us know! Thank you. :)

We have unofficial Debian packaging for our PPAs, which could be reused: https://github.com/nicotine-plus/nicotine-plus/tree/master/debian

Relevant links:  
https://www.debian.org/doc/manuals/developers-reference/ch05.html#reintroducing-pkgs  
https://mentors.debian.net/intro-maintainers

Relevant downstream bug reports:  
https://bugs.debian.org/955514
https://bugs.debian.org/966000  
https://bugs.debian.org/990852
https://bugs.debian.org/1004401

**Comment by mathiascode** [comment]
CC @kiplingw @pabs3

**Comment by kiplingw** [comment]
I don't have time, otherwise I would. Thanks for opening the issue @mathiascode.

**Comment by Rabioli** [comment]
I would be willing to do it throught the open SUSE Build Service, not only the Debian repo but others that also their build service manage, I would need help however and guidance as I was trying to make it run on my end I have problems installing it with pip even with all dependencies met. It says something about cairo and a missing confing file.

**Comment by kiplingw** [comment]
Whoever do it would probably be best positioned to do so if they were already an official Debian Developer.

**Comment by slook** [comment]
Debian devs have updated the open bug about this at link:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990852

On there, Kip Warner <kip@thevertigo.com> (Senior Software Engineer) seems very interested to package a .deb onto Debian buster testing or stable repo's with modern GTK3 dependencies and etc, so it might be worth following up on that bug report.

I am unsure if Kip would be willing to build from source, but he sure seems keen to pull the package in from the PPA tree.

Well done everybody for getting the project working properly again, and good luck getting it back into the main repo, the slsk community appreciates it!

**Comment by mathiascode** [comment]
> Debian devs have updated the open bug about this at link:
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990852
> 
> On there, Kip Warner [kip@thevertigo.com](mailto:kip@thevertigo.com) (Senior Software Engineer) seems very interested to package a .deb onto Debian buster testing or stable repo's with modern GTK3 dependencies and etc, so it might be worth following up on that bug report.
> 
> I am unsure if Kip would be willing to build from source, but he sure seems keen to pull the package in from the PPA tree.

Kip Warner is @kiplingw, see his response above:

`I don't have time, otherwise I would. Thanks for opening the issue @mathiascode.`

> Well done everybody for getting the project working properly again, and good luck getting it back into the main repo, the slsk community appreciates it!

Thank you!

**Comment by francisuk1989** [comment]
With maintaining a PPA system for Debian is the hosting and a older versions of python...I know Ubuntu have launchpad etc but most repos i seen is self hosting for Debian.

I was thinking of something similar for ARM64 devices under raspbian what is Debian 10 and self hosting files for the public so devices like, Raspberry Pi 3/4, Apple M1 chipsets and mostly small single board computers (SBCs)

**Comment by mzf-guest** [comment]
Hello, I'm working on nicotine package reintroduction in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004401

As the package have been removed, I must follow the reintroduction process which is usually time consuming with lots of peer review. So don't expect the package availability before months.

Best,
François

**Comment by slook** [comment]
Hello François,

That is very kind, thank you. Welcome to the Nicotine+ Team!

If there is anything you need then please let us know and we will be glad to assist.

**Comment by SwampRabbit** [comment]
@mzf-guest I'm guessing this is it on Salsa?
https://salsa.debian.org/mzf/nicotine

I can say this, it builds in pbuilder/sbuild and runs no problem, for what that is worth.  I'm guessing standards checks and reviews may show some things to improve.

If you need anything just let me know, I need to do more with Salsa in general.

**Comment by mathiascode** [comment]
Let us know if there's anything we can improve in our own Debian packaging (best practices etc) as the package inclusion process continues. Ideally our packaging would be as close to downstream as possible. :)

**Comment by mzf-guest** [comment]
Thanks all for the warm welcome!

@SwampRabbit I've moved the salsa repo to the python team, in order to co-maintained the package for better quality and long-time support: https://salsa.debian.org/python-team/packages/nicotine

@mathiascode I agree to keep both debian packaging as close as possible. However, Debian policy is very strict and some differences will occur (changelog, removing duplicate license files in uncommon folders, upstream metadata, package tests, etc.).

**Comment by slook** [comment]
@mathiascode Please un-pin this issue, since the project now has Debian package maintainers who have established a downstream repo.

**Comment by mathiascode** [comment]
@mzf-guest A couple of notes/questions about the packaging so far:

- Could you update the description, preferably to the one we use upstream? If this isn't possible, could you change the old SoulSeek spelling to Soulseek, and remove "and tries to look like PySoulSeek" (which is not true anymore).
- The permission fix for ipcountrydb.bin isn't necessary anymore since 3.2.1.
- Is there a reason `gir1.2-ayatanaappindicator3-0.1` and `gir1.2-gspell-1` aren't included as optional dependencies?

Thanks for your work so far.

**Comment by mzf-guest** [comment]
Hello,

I've just updated the package description and removed the permission fix. I'll upload a new version as soon as the package passes the [NEW queue](https://ftp-master.debian.org/new/nicotine_3.2.2-1.html).

For `gir1.2-ayatanaappindicator3-0.1` and `gir1.2-gspell-1`, why are they optional dependencies? and what happen with/without these packages? Does nicotine detects them and add features at run-time? 
Answer to these questions will help to define which [dependency control field](https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends) should be used.

Thanks!
François

**Comment by mathiascode** [comment]
Thanks! Another question: shouldn't `python3-gdbm` and `gir1.2-gtk-3.0` also be listed as dependencies under Depends, or is Build-Depends enough?

> For `gir1.2-ayatanaappindicator3-0.1` and `gir1.2-gspell-1`, why are they optional dependencies?

Since they don't provide vital functionality (spell checking in chat and tray icon), they are optional to make it easier to run Nicotine+ on different systems (especially Windows and macOS).

> and what happen with/without these packages? Does nicotine detects them and add features at run-time? 

If `gir1.2-gspell-1` isn't installed, the spell checking functionality will be disabled.
If `gir1.2-ayatanaappindicator3-0.1` or `gir1.2-appindicator3-0.1` isn't installed, Nicotine+ will fall back to the old Gtk.StatusIcon tray icon implementation, which is deprecated and unsupported in Wayland.

These dependencies are listed under `Recommends` in our Debian packaging.

**Comment by mathiascode** [comment]
@mzf-guest Any update on my previous points? There's also the corrected copyright file that can be applied downstream: https://github.com/nicotine-plus/nicotine-plus/blob/cf565c0aa4dd02f268d52f687ae0450e6eae3620/debian/copyright

**Comment by mzf-guest** [comment]
@mathiascode nicotine is still in the [NEW queue](https://ftp-master.debian.org/new/nicotine_3.2.2-1.html), waiting for final review before entering the archive. Once it's done, I'll update the copyright and the dependencies. It is very common that packages stay several months in the NEW queue so better be patient.

**Comment by mathiascode** [comment]
Thank you, that's fine. Just wanted to make sure the points were acknowledged.

**Comment by mzf-guest** [comment]
The package have been rejected for missing copyright mentions. I'm updating with the new release (3.2.4) and I'm trying to fix all the rejection remarks (see below). Please note that some remarks does not take account of recent @mathiascode updates (Thanks to you!).

```

+----------------------+
|   REJECT reasoning   |
+----------------------+

Copyright for po/* wrong.  It's "Nicotine+ Translators".

Copyright notices for Lene Preuss and Mutnick missing.

.xml.in files say they have CC0-1.0 licensed parts.

.../themes/class/README.md says there is public domain and LGPL-3+ work in
there.

socket_localhost_22420.log looks like an actual chat log, so would be
copyright its participants?  We probably can't include it in Debian.

What is the license/coypright for vbr44.mp3?

+----------------------+
|    Other comments    |
+----------------------+

A number of copyright notices for *.py not included.

Copyright notice for "Nicotine+ Team" not in d/copyright.

+----------------------+
|         N.B.         |
+----------------------+

This review may not be exhaustive.  Please check your source package
against your d/copyright and the ftpmaster REJECT-FAQ, throughly,
before uploading to NEW again.
```

**Comment by mathiascode** [comment]
- `Copyright for po/* wrong.  It's "Nicotine+ Translators".` Why don't names of translators work here?
- `themes/classic` is not shipped with Nicotine+, only included in the repo
- `socket_localhost_22420.log` I'll remove this file, it was never implemented in the tests anyway
- `What is the license/coypright for vbr44.mp3?` Main project license (GPL3+)
- `Copyright notice for "Nicotine+ Team" not in d/copyright.` The copyright notices were changed to `Nicotine+ Contributors` in 3.2.4. Is this is relevant anymore?

**Comment by mathiascode** [comment]
Please note the following changes related to copyright notices before packaging Nicotine+ 3.2.6:
25a81b2504352ded1121aa5f9e681b2dc9dbe7be
fb73d4d6dc68d0ddc74ceba26d5c9d66057fa9a9

There were some duplicate copyright notices added in https://salsa.debian.org/python-team/packages/nicotine/-/commit/276981187415c712f35c461bb06982e2e82642f7 that should be removed/merged with previous ones.

**Comment by slook** [comment]
There is a confusing duplicated item on the copyright list, same dev appears twice with two different spellings and dates:

https://salsa.debian.org/python-team/packages/nicotine/-/blob/master/debian/copyright#L21
           2006-2017 Adam Cécile (eLvErDe)

https://salsa.debian.org/python-team/packages/nicotine/-/blob/master/debian/copyright#L45
           2008-2009, 2013 eL_vErDe <gandalf@le-vert.net>

**Comment by slook** [comment]
@mzf-guest The current stable version is 3.2.8 and 3.2.9 will be released soon.

**Comment by mzf-guest** [comment]
After several attempts, nicotine is finally back to Debian! https://tracker.debian.org/news/1461941/accepted-nicotine-325-1-source-all-into-unstable/

Thanks all for your help and for your positive attitude despite the numerous rejections :smiley: 

Update to a more recent release should follow.

Best,
François

**Comment by mathiascode** [comment]
Great, thanks! Let me know if you have any questions about anything in the future.

**Comment by mathiascode** [comment]
@mzf-guest For some reason the Debian bug tracker is silently dropping my emails at the moment, so I'll just post my response to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071203 here:

> The package is missing python3-gi and gir1.2-gtk-4.0 runtime dependencies. Nicotine+ uses GTK 4 by default since 3.3.0.
> 
> Speaking of dependencies, python3-gdbm is no longer used since 3.3.0.

**Comment by mzf-guest** [comment]
Thanks for the pointers! I'll update the Debian package to 3.3.4 and update the dependencies.
