### ISSUE TITLE
select ValueError: too many file descriptors in select() (Windows)

### ISSUE THREAD

**Issue by electronicdreamer** [nicotine-plus/nicotine-plus#1456]
Nicotine+ version:  Latest package built (3.1.0), don't see the bug in 3.0.6
Operating System/Distribution: Windows 10 x64

After doing a search with results (tried with `grimes` and `number girl`), the log is spammed with "select ValueError: too many file descriptors in select()" messages and it doesn't stop.

![image](https://user-images.githubusercontent.com/1419129/126358770-936a2b8c-7efd-47b0-ac44-d800e6129e86.png)

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/c443e0e8b8be7901bc1f7b8f78a12272b0331d48 https://github.com/nicotine-plus/nicotine-plus/commit/07bb992726b9f71e2286aad6bb7ccd4a39a598d1 should fix this. Can you test if the latest unstable is fine?

**Comment by electronicdreamer** [comment]
Just tested, seems fine, no error message 👍
