### ISSUE TITLE
Clicking on taskbar doesn't minimise window (Windows)

### ISSUE THREAD

**Issue by electronicdreamer** [nicotine-plus/nicotine-plus#1460]
Nicotine+ version:  3.1.0.dev1  •  GTK 3.24.30
Operating System/Distribution: Windows 10 x64

Clicking on the Nicotine taskbar icon when the window is active should minimise the window (same as other applications).
Instead window is taken out of focus (greyed out) but it stays maximised.

**Comment by electronicdreamer** [comment]
Oh, I'm sorry, I didn't see an already existing issue mention it's a GTK issue.

**Comment by Inso-m-niaC** [comment]
You can restore that native windows behaviour by going to 'Menu > View > Use Header Bar' and uncheck the box.

**Comment by electronicdreamer** [comment]
Works great, thanks

**Comment by Inso-m-niaC** [comment]
Alternatively, clicking the tray icon minimizes it to tray and works with 'use header bar' both checked and unckecked.
