### ISSUE TITLE
Nicotine+ database needs recovery

### ISSUE THREAD

**Issue by tzotsor** [nicotine-plus/nicotine-plus#1467]
Nicotine+ version:  3.1.0-1
Operating System/Distribution: Linux Manjaro - Kernel Linux 5,14 Experimental (issue persists with other versions)

### Describe the bug

Nicotine+ starting and closing after crash report - apparently database needs recovery
I'm also unable to uninstall Nicotine+

### Expected behavior

Open

### Steps to reproduce the bug
-
### Additional context
Screenshots, logs, stacktraces or relevant information.

Type: <class '_gdbm.error'>
Value: Database needs recovery
Traceback:   File "/usr/lib/python3.9/threading.py", line 1234, in invoke_excepthook
    hook(args)
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2506, in on_critical_error_threading
    raise args.exc_value
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/pynicotine/slskmessages.py", line 2226, in make_network_message
    msg.extend(self.pack_object(len(self.list)))
  File "/usr/lib/python3.9/shelve.py", line 99, in __len__
    return len(self.dict)
![Screenshot_2021-08-03_12-38-11](https://user-images.githubusercontent.com/88376170/127995985-5bbf5830-4792-4ba0-ba8c-48d137d3475d.png)

**Comment by mathiascode** [comment]
Looks like a corrupted shares database. Does rescanning your shared files do anything?

Try running `nicotine --rescan` from the command line if you're unable to use Nicotine+.

**Comment by tzotsor** [comment]
Thank you so much for your help, man. The issue seems to be fixed, N+ started normally.

I know it's different issue and I got no clue it could be related to the one above, but I noticed that now the listening port is closed:
"Port: 2234/tcp CLOSED. Your router and/or Soulseek client needs to be configured correctly."
Any idea how to open it? got a Huawei Home GatewayHG658 v2, not listed here http://www.pcwintech.com/port-forwarding-guides.

**Comment by mathiascode** [comment]
Can you verify that UPnP is enabled for the router and Nicotine+? UPnP should take care of port forwarding automatically. If this still results in a closed port, could you enable the `Miscellaneous` debug logging category (Menu -> View -> Show Log Pane + Show Debug Log Controls), restart Nicotine+, and post the log output?

**Comment by tzotsor** [comment]
Yes, UPnP is enabled in router in Nicotine+ and router.
Here is the log:

18:41:20 [Misc] Loading plugin handler
18:41:20 Connecting to server.slsknet.org:2242
18:41:20 [Misc] Creating Port Mapping rule via UPnP...
18:41:20 [Misc] UPnP: Discovering... delay=2 seconds
18:41:20 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:41:20 [Misc] UPnP: Sent M-SEARCH IP request 1
18:41:20 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:41:20 [Misc] UPnP: Sent M-SEARCH PPP request 1
18:41:20 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:41:20 [Misc] UPnP: Sent M-SEARCH IGD request 1
18:41:20 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:41:20 [Misc] UPnP: Sent M-SEARCH IP request 2
18:41:20 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:41:20 [Misc] UPnP: Sent M-SEARCH IGD request 2
18:41:20 Listening on port 2234
18:41:20 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nLOCATION: http://192.168.1.1:37215/upnpdev.xml\r\nSERVER: Linux UPnP/1.0 Huawei-ATP-IGD\r\nCACHE-CONTROL: max-age=86500\r\nEXT: \r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nUSN: uuid:00e0fc37-2525-2828-2502-9c69d13649cd::urn:schemas-upnp-org:service:WANIPConnection:1\r\nDATE: Tue, 03 Aug 2021 15:47:42 GMT'
18:41:20 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nLOCATION: http://192.168.1.1:37215/upnpdev.xml\r\nSERVER: Linux UPnP/1.0 Huawei-ATP-IGD\r\nCACHE-CONTROL: max-age=86500\r\nEXT: \r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:00e0fc37-2525-2828-2500-9c69d13649cd::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nDATE: Tue, 03 Aug 2021 15:47:42 GMT'
18:41:20 Connected to server server.slsknet.org:2242, logging in...
18:41:21 1704 privileged users
18:41:21 You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
18:41:22 [Misc] UPnP: 2 device(s) detected
18:41:22 [Misc] Trying to redirect external WAN port 2234 TCP => 192.168.1.14 port 2234 TCP
18:41:22 [Misc] Adding port mapping (00e0fc37-2525-2828-2500-9c69d13649cd, TCP, 2234, 192.168.1.14, 2234)
18:41:22 [Misc] Adding port mapping (192.168.1.14 2234/TCP) at url "192.168.1.1:37215/ctrlu/WANIPConnection_1"
18:41:22 [Misc] UPnP: Add port mapping request headers: {'Host': '192.168.1.1:1900', 'Content-Type': 'text/xml; charset=utf-8', 'SOAPACTION': '"urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"'}
18:41:22 [Misc] UPnP: Add port mapping request contents: <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"><NewRemoteHost></NewRemoteHost><NewExternalPort>2234</NewExternalPort><NewProtocol>TCP</NewProtocol><NewInternalPort>2234</NewInternalPort><NewInternalClient>192.168.1.14</NewInternalClient><NewEnabled>1</NewEnabled><NewPortMappingDescription>NicotinePlus</NewPortMappingDescription><NewLeaseDuration>86400</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>
18:41:22 [Misc] UPnP: Add port mapping response: b'<?xml version="1.0"?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n<s:Body>\n<u:AddPortMappingResponse xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"/>\n</s:Body>\n</s:Envelope>\n'
18:41:22 [Misc] Managed to map external WAN port 2234 to your local host 192.168.1.14 port 2234.

Thank you!!

**Comment by tzotsor** [comment]
I'm sorry, that's the last version:

18:52:18 [Misc] Loading plugin handler
18:52:18 Connecting to server.slsknet.org:2242
18:52:18 [Misc] Creating Port Mapping rule via UPnP...
18:52:18 [Misc] UPnP: Discovering... delay=2 seconds
18:52:18 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:52:18 [Misc] UPnP: Sent M-SEARCH IP request 1
18:52:18 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:52:18 [Misc] UPnP: Sent M-SEARCH PPP request 1
18:52:18 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:52:18 [Misc] UPnP: Sent M-SEARCH IGD request 1
18:52:18 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:52:18 [Misc] UPnP: Sent M-SEARCH IP request 2
18:52:18 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:52:18 [Misc] UPnP: Sent M-SEARCH IGD request 2
18:52:18 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nLOCATION: http://192.168.1.1:37215/upnpdev.xml\r\nSERVER: Linux UPnP/1.0 Huawei-ATP-IGD\r\nCACHE-CONTROL: max-age=86500\r\nEXT: \r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nUSN: uuid:00e0fc37-2525-2828-2502-9c69d13649cd::urn:schemas-upnp-org:service:WANIPConnection:1\r\nDATE: Tue, 03 Aug 2021 15:58:40 GMT'
18:52:18 Listening on port 2234
18:52:18 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nLOCATION: http://192.168.1.1:37215/upnpdev.xml\r\nSERVER: Linux UPnP/1.0 Huawei-ATP-IGD\r\nCACHE-CONTROL: max-age=86500\r\nEXT: \r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:00e0fc37-2525-2828-2500-9c69d13649cd::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nDATE: Tue, 03 Aug 2021 15:58:40 GMT'
18:52:19 Connected to server server.slsknet.org:2242, logging in...
18:52:19 1704 privileged users
18:52:19 You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
18:52:21 [Misc] UPnP: 2 device(s) detected
18:52:21 [Misc] Trying to redirect external WAN port 2234 TCP => 192.168.1.14 port 2234 TCP
18:52:21 [Misc] Adding port mapping (00e0fc37-2525-2828-2500-9c69d13649cd, TCP, 2234, 192.168.1.14, 2234)
18:52:21 [Misc] Adding port mapping (192.168.1.14 2234/TCP) at url "192.168.1.1:37215/ctrlu/WANIPConnection_1"
18:52:21 [Misc] UPnP: Add port mapping request headers: {'Host': '192.168.1.1:1900', 'Content-Type': 'text/xml; charset=utf-8', 'SOAPACTION': '"urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"'}
18:52:21 [Misc] UPnP: Add port mapping request contents: <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"><NewRemoteHost></NewRemoteHost><NewExternalPort>2234</NewExternalPort><NewProtocol>TCP</NewProtocol><NewInternalPort>2234</NewInternalPort><NewInternalClient>192.168.1.14</NewInternalClient><NewEnabled>1</NewEnabled><NewPortMappingDescription>NicotinePlus</NewPortMappingDescription><NewLeaseDuration>86400</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>
18:52:21 [Misc] UPnP: Add port mapping response: b'<?xml version="1.0"?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n<s:Body>\n<u:AddPortMappingResponse xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"/>\n</s:Body>\n</s:Envelope>\n'
18:52:21 [Misc] Managed to map external WAN port 2234 to your local host 192.168.1.14 port 2234.

**Comment by mathiascode** [comment]
The log looks fine. Perhaps your ISP is blocking incoming traffic, or using CGNAT, which prevents port forwarding?

**Comment by tzotsor** [comment]
The port is now open, just like that...
I have no idea what was wrong, I was planning to contact the ISP.
Fingers crossed...
Thank you so much for your help, I really appreciate it!!!
