### ISSUE TITLE
Double-click on search result to start download

### ISSUE THREAD

**Issue by syphant** [nicotine-plus/nicotine-plus#1469]
In the official Soulseek client, there is an option in Settings to enable "download when double-clicking folder" (or similarly worded).
This allows you to immediately start downloading a folder listed in the search results by double-clicking on it.
I do not see this is an option in Nicotine+, but I believe it would be a very useful feature addition.

**Comment by mathiascode** [comment]
I noticed that SoulseekQt only seems to download files visible in the search results for a specific folder. Wouldn't it make more sense to request all the files in the folder, like the right-click menu item does?

**Comment by syphant** [comment]
> I noticed that SoulseekQt only seems to download files visible in the search results for a specific folder. Wouldn't it make more sense to request all the files in the folder, like the right-click menu item does?

Interesting, I’ve never noticed this myself because I almost always use broad search terms that match the name of the folder itself. 

To answer your question, I agree that would make more sense. Possibly it would be simpler to implement this in the way it currently functions in SoulseekQt, then eventually modify this as you’ve described if there is demand?

Context: I have zero development experience, I’m just a fan of this project.

**Comment by mathiascode** [comment]
I opted for the same behavior as the right-click menu, for consistency. Since nobody has requested this feature previously, I assume there won't be many opinions on this matter.

**Comment by hejops** [comment]
As far as I can tell, the current double-click action defaults to `Download File(s)`; can a config option be added to select `Download Folder(s)` (as in https://github.com/nicotine-plus/nicotine-plus/issues/917)?
