### ISSUE TITLE
left click does not work on users nickname in rooms

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#147]
is it not supposed to display options with left click over niclkname in rooms ?

**Comment by mathiascode** [comment]
Was this working in the GTK2 version?

**Comment by zniavre** [comment]
for sure...

**Comment by zniavre** [comment]
Version 1.2.7 Release (25th February 2007)
CHAT
 * Usernames in the chat room log now have hotspots associated with them,
   meaning they can be left-clicked on to load the same popup as you have in
   the users list.

**Comment by zniavre** [comment]
it's closed but i do not know where ask about this fix 

it works with users below the "old messages above" but it should works with user above as 1.4.2 does
