### ISSUE TITLE
Make an android fork?

### ISSUE THREAD

**Issue by 154pinkchairs** [nicotine-plus/nicotine-plus#1470]
Since the only Soulseek client for Android is no longer developed and doesn't work on 4.0 and higher, the only ways to access Soulseek are via newalbum.club, which has very limited functionality or via Linux emulation which is resource heavy and often requires a few peripherals to be used comfortably (no aarch64 version that would run on termux too), or VNC to computer. It would be great if an Android fork was made with most people listening to music on their smartphones.

**Comment by mathiascode** [comment]
We don't have the manpower for this. Your best option is the new Seeker client, which is actively developed: https://play.google.com/store/apps/details?id=com.companyname.andriodapp1
