### ISSUE TITLE
Consider bumping listen socket backlog length

### ISSUE THREAD

**Issue by toofar** [nicotine-plus/nicotine-plus#1471]
### Describe the solution you'd like

Nicotine sets the listen socket connection backlog to [just 1](https://github.com/nicotine-plus/nicotine-plus/blob/5477e7c/pynicotine/slskproto.py#L519). That means the kernel will not wait for the application to be ready if any new connections come in while it is already handling one. I imagine this can lead to hard to debug connection issues.

`man 2 listen` says:
> Since  Linux 5.4, the default in this file is 4096; in earlier kernels, the default value is 128.

So I suggest omitting that parameter and letting the system pick a value.

### Additional context
Hello again. I use netdata in mostly its default config to monitor my server where nicotine runs. It has been filling my mailbox with networking related errors for some time now (like forever). Specifically these warnings:

1m tcp syn queue cookies - ip.tcp_syn_queue
1m tcp accept queue overflows - ip.tcp_accept_queue
1m tcp accept queue drops - ip.tcp_accept_queue

Searching previously (for example https://old.reddit.com/r/linuxadmin/comments/b71asg/netdata_iptcp_accept_queue/) I've bumped the global kernel controls (net.ipv4.tcp_max_syn_backlog and net.core.somaxconn) but I've still been getting warnings regularly.
Some helpful stackoverflow user (https://serverfault.com/questions/518862/will-increasing-net-core-somaxconn-make-a-difference/519152#519152) points out that the kernel limit is just the default and applications can set a lower limit if they like, and the kernel will just report drops with no indication of what limit caused them to be dropped. Nicotine sets it to just 1 and it has so since as far back as the git history goes https://github.com/nicotine-plus/nicotine-plus/blob/5477e7c/pynicotine/slskproto.py#L519

Here are some pictures, they include the netdata explanations for the accept and syn queues and what my server was doing. Note that nicotine was not under load at this time, I only had one user trying to download from me, so this would have been just background stuff like searches I suppose.

This one is on the latest master (df29dbff2e08). All I did was change the argument of listen() from 1 to 1024 (arbitrary choice) and restarted the application. You can see the number of syn cookies and drops goes right down.

![2021-08-15_12-26_nicotine_listen_overflows_new_version-annotated](https://user-images.githubusercontent.com/7419144/129464173-80256b6e-1b09-484a-b45e-924331eb8266.png)

Regarding the accept queue, I was running on a commit from May (cfab0182a2e6) because I'm lazy and hadn't bothered upgrading. The picture looked much worse on that one, including accept drops. I heard you did some speedups recently so presumably nitotine is much faster in triaging new connections now. I would not be surprised if there were accept queue drops even on the latest version when under load though

![2021-08-15_12-26_nicotine_listen_overflows-annotated](https://user-images.githubusercontent.com/7419144/129464230-583d056b-f2d1-42a2-967b-8937d7660647.png)

**Comment by mathiascode** [comment]
Thanks for the report, this is something I've overlooked. Seems like the backlog length has been set to 1 since the very first versions of PySoulSeek.

If you can confirm that omitting the backlog parameter on the latest master improves the situation, I can commit this change. Python seems to set it to 128 by default: https://github.com/python/cpython/blob/ed524b4569b1e4a166886c880018418d46284378/Modules/socketmodule.c#L3411

**Comment by toofar** [comment]
Okay I changed it to use the python default over an hour ago, downloaded some stuff, saw some stuff get uploaded, not seeing a significant difference to when it was 1024
 
![2021-08-15_12-26_nicotine_listen_overflows_128](https://user-images.githubusercontent.com/7419144/129466266-5efaed58-bac8-4705-8b36-b606817ecded.png)
