### ISSUE TITLE
Generate releases hashes?

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1473]
Would it possible to generate hashes for Nicotine+ releases? It may be as simple as [using this](https://github.com/marketplace/actions/generate-release-hashes).

The generated text file could be read instead of downloading the files to determine their hashes, useful for command-line installers (package managers) like [Scoop](https://github.com/lukesampson/scoop) which can [check for updates](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#adding-autoupdate-to-a-manifest).

The default of sha256 would be fine, though others will do for Scoop's purposes. I think Scoop just needs the checksum to appear anywhere in the text file, though if you wanted to generate the hashes through your own method, [more elaborate formats](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#adding-hash-to-autoupdate) would work too, such as json, or anything with structure since Scoop can use regex.

Thanks.

**Comment by redactedscribe** [comment]
@mathiascode Nicotine+ will be available to download on Windows via Scoop's Extras bucket once the [pull request](https://github.com/lukesampson/scoop-extras/pull/6656) is accepted.

Since Nicotine+ doesn't support checking for updates and relies upon package managers to handle that, and since Windows users have no means to know when an update is available (other than check the site/repo), it may be worth mentioning that they can use Scoop to install the program and keep it up-to-date. It should work indefinitely unless paths/structures related to the .zips change (but these can be amended with a future pull request as is common for Scoop manifests).

**Comment by mathiascode** [comment]
There is an option to manually check for updates (Menu -> Help -> Check Latest Version), but yes, it's unlikely that anything will be done beyond that, especially after the recent negative backlash related to Audacity. Once the pull request is accepted, I could probably add a notice in the readme.

**Comment by mathiascode** [comment]
Are you going to maintain the scoop package in the future? It doesn't look like much effort is required, but I'd rather not pick up any additional packaging responsibilities personally.

**Comment by redactedscribe** [comment]
When Scoop fails to download/update, a notice is shown, and a clickable link generating a new GitHub issue is displayed, so anybody is welcome to bring attention to it / fix the manifest. I will likely see any problem via Scoop if it stops working and I can make the changes. Downloads via Scoop aren't usually considered official, so the README wording could reflect that; a convenience without necessarily a guarantee.

**Comment by redactedscribe** [comment]
Does Nicotine+ have any cli commands (on Windows)? The addition of "nicotine+.exe" to the user's path has been removed by review, which may or may not be ideal, dependant on your answer.

**Comment by redactedscribe** [comment]
@mathiascode [nicotine-plus.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/nicotine-plus.json) manifest has now been merged into the scoop-extras bucket.

**Comment by redactedscribe** [comment]
@mathiascode Scoop updated Nicotine+ to v3.2.0, no packaging maintenance required:

![nicotine_plus_scoop_update](https://user-images.githubusercontent.com/25013746/146660963-ceb03c46-b7e6-4894-b18d-e1061fef5f8c.png)

Confirmed as working. Consider adding Scoop as a source to obtain Nicotine+ from. It's just as, if not more popular than Chocolatey (by GitHub stars, Scoop has near double).

**Comment by mathiascode** [comment]
Is the command `scoop install nicotine-plus`?

**Comment by redactedscribe** [comment]
Yes.

1. Add [the extras bucket](https://github.com/ScoopInstaller/Extras) (i.e. [an official repo](https://github.com/ScoopInstaller/Scoop#known-application-buckets)): `scoop bucket add extras`
2. `scoop install nicotine-plus`
3. `scoop update nicotine-plus` to update when there's a new release.

The user must always both check for updates and update manually via Scoop (unless they choose to automate this via their own methods).

There's a [wiki](https://github.com/ScoopInstaller/Scoop/wiki) with a [Quick Start guide](https://github.com/ScoopInstaller/Scoop/wiki/Quick-Start) for any additional help.

**Comment by slook** [comment]
> the process used by Chocolatey ... actually, it seems [v3.2.0 is waiting for the maintainer](https://community.chocolatey.org/packages/nicotine-plus/3.2.0) to fix some verification checks

@majkinetor is the maintainer. There is [errors in the Chocolatey installer script](https://gist.github.com/choco-bot/40d2b0c3679c4c41166465180d5b0c49#file-install-txt-L461) that needs a look into.

**Comment by majkinetor** [comment]
@slook, the automatic package didn't work as it was changed to use msi instead of exe which required intervention. I fixed it now:

- https://community.chocolatey.org/packages/nicotine-plus/3.2.0

> It's just as, if not more popular than Chocolatey (by GitHub stars, Scoop has near double).

Don't be ridiculous - Chocolatey is way more popular then Scoop and has x2 more packages. It also supports embedded packages unlike scoop, so you depend on network.

 You are judging by irrelevant metric (GitHub stars).  I wish that Scoop can replace it but so far it lags behind.

**Comment by redactedscribe** [comment]
Wasn't my intention to be ridiculous, just seemed like people were more interested in Scoop due to it's GitHub popularity.

**Comment by majkinetor** [comment]
I am just kidding m8.  I understand that people are more interested in scoop, as they probably should be. I don't work for anybody so I am interested in what works the best. The major problem with Scoop is that you depend on network availability. Chocolatey was like that before, and it still is partially. However, mainstream packages are mostly embedded. This means that your CI/CD can last for decade+ without 404 that is typical for scoop after a year or two.
