### ISSUE TITLE
Mac Intel El Capitan 10.11.6

### ISSUE THREAD

**Issue by francisuk1989** [nicotine-plus/nicotine-plus#1474]
Is it possible someone could make a Intel El Capitan 10.11.6 build for Mac OS X

I think it would benefit everyone that owns 2008-2012 Mac Pro due to them having 4 bay drives.

**Comment by mathiascode** [comment]
I've previously attempted to create official builds for 10.13, but it turned out to be too cumbersome in the end. Using newer macOS versions to generate builds for old versions is generally a no-go, and I'm not sure if Homebrew provides any packages for 10.11 anymore. If you can get Homebrew running somehow, you should be able to install GTK3/Python deps and generate a Nicotine+ build.

**Comment by francisuk1989** [comment]
Thanks for trying to build an image
however with homebrew i think im going to have the same error as i did in pip, it just seems to be failing on two what are;

pygobject for using GObject introspection with Python 3;

```
  Building wheel for pycairo (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/s0/35n1fkk97gx2fx9q3fcvhygw0000gn/T/tmpj5108859
       cwd: /private/var/folders/s0/35n1fkk97gx2fx9q3fcvhygw0000gn/T/pip-install-se9p5j6r/pycairo_a36e39caf3bb4d30aa4adffecf38b84b
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.9
  creating build/lib.macosx-10.9-x86_64-3.9/cairo
  copying cairo/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/cairo
  copying cairo/__init__.pyi -> build/lib.macosx-10.9-x86_64-3.9/cairo
  copying cairo/py.typed -> build/lib.macosx-10.9-x86_64-3.9/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
Failed to build PyGObject pycairo
ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly
```

**Comment by francisuk1989** [comment]
@mathiascode Regarding GTK 4 https://github.com/nicotine-plus/nicotine-plus/issues/1475
Do you think GTK 4 will work for this Mac version? Willing to give this ago and more then report back.

https://nicotine-plus.github.io/nicotine-plus/doc/PACKAGING.html im a little stuck on this.

export NICOTINE_GTK_VERSION=4
e**xport ARCH=x86_64** << Whats this for Intel Mac? CPU is a Intel.
**pacman --noconfirm -S --needed mingw-w64-$ARCH-python** << Help with this ago?
python3 packaging/windows/dependencies_core.py
python3 packaging/windows/dependencies_packaging.py

**Comment by mathiascode** [comment]
> Thanks for trying to build an image however with homebrew i think im going to have the same error as i did in pip, it just seems to be failing on but i know this isnt nicotine package.

Judging by the output, you probably need to install pkg-config:

`brew install pkg-config`

If you're running pip outside Homebrew, it won't work, since you need the GTK dependency from Homebrew (gtk+3 or gtk+4).

**Comment by mathiascode** [comment]
> @mathiascode Regarding GTK 4 #1475
> Do you think GTK 4 will work for this Intel Mac version? Willing to give this ago and more then report back and be more then happy to build and host at my github with maybe a warning at experimental use?
> 
> https://nicotine-plus.github.io/nicotine-plus/doc/PACKAGING.html im a little stuck on two things.
> 
> export NICOTINE_GTK_VERSION=4
> e**xport ARCH=x86_64** << Whats this for Intel Mac? CPU is a Intel.
> pacman --noconfirm -S --needed mingw-w64-$ARCH-python Help with this for Mac If not can install Arch Linux for compiling
> python3 packaging/windows/dependencies_core.py
> python3 packaging/windows/dependencies_packaging.py
> 
> ```
> FransMacPro8Core:~ fran$ python3
> Python 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) 
> [Clang 6.0 (clang-600.0.57)] on darwin
> ```

Sorry, there are no written packaging instructions for macOS yet. You have to follow https://github.com/nicotine-plus/nicotine-plus/blob/master/.github/workflows/packaging.yml for now.

This would result in the following commands for installing dependencies:
```
export NICOTINE_GTK_VERSION=4
python3 packaging/macos/dependencies_core.py
python3 packaging/macos/dependencies_packaging.py
```

Then create the dmg file:
```
pyinstaller packaging/macos/nicotine.spec
rm -rf dist/Nicotine+/
codesign --deep --entitlements packaging/macos/entitlements.plist --options runtime --sign - dist/Nicotine+.app
python3 packaging/macos/create_dmg.py
```

**Comment by francisuk1989** [comment]
Thanks @mathiascode Will give the build ago and report back 👍

**Comment by francisuk1989** [comment]
@mathiascode Sorry to keep bugging you, Hope i become to some help whoever eles sees this.
GK4 is a no go and gives warning about older Mac (Cant upgrade to newer becouse of an 2008 Mac Pro.)

However GK2 compiled fine without no errors however i have two issues

1) when i try and lunch it (heres the logs)
FransMacPro8Core:~ fran$ /Users/fran/Desktop/Nicotine+.app/Contents/MacOS/Nicotine+ ; exit;
Cannot find gdbm or semidbm, please install either one.

2)
The DMG file size is 900 something MB.

**Comment by mathiascode** [comment]
Try `brew install gdbm`

**Comment by francisuk1989** [comment]
@mathiascode 
brew install gdbm
Warning: gdbm 1.20 is already installed and up-to-date.
To reinstall 1.20, run:
  brew reinstall gdbm
Franciss-Mac-Pro:nicotine-plus francis$ brew reinstall gdbm
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://ftp.gnu.org/gnu/gdbm/gdbm-1.20.tar.gz
Already downloaded: /Users/francis/Library/Caches/Homebrew/downloads/0cb378cb017689a5fbb0e33492142d2754ff33eb33fd30d5668090ae407924c6--gdbm-1.20.tar.gz
==> Reinstalling gdbm 
==> ./configure --enable-libgdbm-compat --without-readline --prefix=/usr/local/Cellar/gdbm/1.20
==> make install
🍺  /usr/local/Cellar/gdbm/1.20: 38 files, 916.2KB, built in 27 seconds

**Comment by mathiascode** [comment]
I suppose the Python installation doesn't include gdbm support for some reason. You might have to install semidbm instead:
`pip install semidbm`

**Comment by francisuk1989** [comment]
No joy on pip or pip2 @mathiascode

**Comment by slook** [comment]
Try looking for a package called "python3-gdbm"

**Comment by francisuk1989** [comment]
> Try `brew install gdbm`

Thanks @slook but was already suggested by @mathiascode but no joy.

**Comment by slook** [comment]
What is selected choice of:
`update-alternatives --config python`

And:
`python --version`

Also, what is the output please copy paste:
`pip3 list`

**Comment by francisuk1989** [comment]
@slook Remember this is a Mac system not a Linux system as so :)

update-alternatives --config python
-bash: update-alternatives: command not found

update-alternatives --config python3
-bash: update-alternatives: command not found

python --version
Python 2.7.10

python3 --version
Python 3.9.7

**Comment by slook** [comment]
Yeah I am aware of that @francisuk1989 and my knowledge of your platform is minimal I have never owned a Mac.

However I recently had a very similar error to yourself on my legacy 'nix machine when I had installed the latest version of Python but what infact was needed was an older one.

Thanks for sending your pip list this might be useful for @mathiascode to look at.

**Comment by francisuk1989** [comment]
appreciate the help and I was thinking of the same @slook is either

1) Go to python 3.5 or 3.8 but i think i would need to clean up brew's python 3.9 or install a fresh copy of Mac OS X.
2) install Arch Linux on my spare laptop and do from there but signing will be a issue just before creating dmg file.

**Comment by slook** [comment]
I was able to get it working with Python 3.5 but not Python 3.8 - whilst it installed okay, the os didn't like it.

can you not run N+ from local git folder?

**Comment by francisuk1989** [comment]
Not sure if Mac can run from Git

**Comment by mathiascode** [comment]
You need to install Homebrew first, so you can use the python3 package provided by Homebrew. Then, you issue the pip command.

`brew install python3`

**Comment by francisuk1989** [comment]
This is the first thing i did is issued brew install python3 and gives me 3.9 version.

**Comment by mathiascode** [comment]
What was the issue with the 3.9 version provided by Homebrew? It should provide pip3 out of the box.

> No joy on pip or pip2 @mathiascode

What was the error?

Regarding the pycairo issue, it says `No package 'cairo' found`. Have you tried `brew install cairo`?

**Comment by francisuk1989** [comment]
> What was the issue with the 3.9 version provided by Homebrew? It should provide pip3 out of the box.
> 
> > No joy on pip or pip2 @mathiascode
> 
> What was the error?
> 
> Regarding the pycairo issue, it says `No package 'cairo' found`. Have you tried `brew install cairo`?

Sorry there is pip3 but not pip or pip2 for Mac.

Will give brew install cairo  later on this evening.

**Comment by mathiascode** [comment]
Sorry, I misunderstood. I meant python3 and pip3 in any case, I'm just used to `pip` and `python` invoking `pip3` and `python3` on my system.

**Comment by francisuk1989** [comment]
I have come to a stop on this as OpenSSL 1.1.1l s having issues with Brew and have to wait for the next release off 1.1.1m, i  did report this to brew but because is a older MacOS is nothing they going to do.
I will close this issue for now and reopen when a release of openSSL 1.1.1n released and hopefully comping will work again for older Macs

Thanks again for all your help.
