### ISSUE TITLE
M1 Mac support?

### ISSUE THREAD

**Issue by ghost** [nicotine-plus/nicotine-plus#1475]
I was wondering when there would be an update to the app such that it runs natively on the M1 MacBooks. I tried the regular macOS installer and the app stutters and lags... a lot. I can barely search for anything in the search bar, the app won't maximize properly, scrolling stutters a lot; these are just some of the problems when the app is run through Rosetta 2.

**Comment by mathiascode** [comment]
This would require https://github.com/actions/virtual-environments/issues/2187

**Comment by mathiascode** [comment]
You could try running Nicotine+ in Homebrew (https://github.com/nicotine-plus/nicotine-plus#stable-mojave1014), which should be native, to verify if the lag is a result of Rosetta 2 or GTK 3. The performance of GTK 3 has been notoriously bad on macOS, and GTK 4 supposedly fixes some of these issues.

**Comment by francisuk1989** [comment]
Interesting, So would the OP need to do export ARCH first for the Apple M1 ?

export ARCH=arm64
NICOTINE_GTK_VERSION=4 nicotine

**Comment by slook** [comment]
@samstator please can you try disabling `Menu > View > Use Header Bar` and let us know if it makes any difference. Thanks.

**Comment by mathiascode** [comment]
The header bar is now force disabled in the unstable version of Nicotine+.

**Comment by mathiascode** [comment]
Current blockers for native M1 support:
- No M1 support in GitHub Actions at the moment (for automatically generating Nicotine+ builds): https://github.com/actions/virtual-environments/issues/2187
- PyGObject-related crashes: https://gitlab.gnome.org/GNOME/pygobject/-/issues/455 https://github.com/Homebrew/homebrew-core/issues/84905

**Comment by mathiascode** [comment]
The PyGObject-related crash is apparently fixed now: https://gitlab.gnome.org/GNOME/pygobject/-/issues/489#note_1495088

**Comment by toineenzo** [comment]
@mathiascode Maybe this would make it possible? https://github.com/actions/runner-images/issues/2187#issuecomment-1293622278
Cirrus say they offer unlimited minutes for free for open-source projects in our [Cirrus CI offering](https://cirrus-ci.org/guide/macOS/). But for Cirrus Runners we only do paid plans.

**Comment by slook** [comment]
The current CI test suite wouldn't pick up on the types of problems that M1 Mac users seem to encounter, such as #2223 for example.

**Comment by Vexariboerl** [comment]
From my experience I can say that Nicotine+ UI is kind of choppy (definitely not smooth) on my M1 Mac Mini, but it feels the same on my Intel iMac. For me it is totally usable, even though smooth scroll would be nice.

**Comment by mathiascode** [comment]
> then perhaps this issue can be closed

This issue will remain open until we have native M1/M2 builds, i.e. not running with the Rosetta 2 compatibility layer. Since Homebrew doesn't support universal binaries, instead splitting packages in x86_64 and arm64, we need macOS arm64 runners for creating separate builds.

> From my experience I can say that Nicotine+ UI is kind of choppy

How does the GTK 4 version of Nicotine+ (current master branch, https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos) compare to the stable version, which uses GTK 3? GTK 4 is supposed to improve performance on macOS, but since I only have access to macOS through a virtual machine, I can't really verify this.

**Comment by jackturnbull** [comment]
> How does the GTK 4 version of Nicotine+ [...] compare to the stable version

In my experience, much much better. I've also noticed the display lag under GTK 3 but given that it never freezes up completely, put up with it. I've found the nightlies to be much better here. Thanks for the tip!

**Comment by toineenzo** [comment]
GTK4 is much smoother then GTK3! But a native built would still be much better ;)

**Comment by mathiascode** [comment]
Apple Silicon runners for GitHub Actions are scheduled for Q4 2023 (October-December). Once they are available, we should be able to start providing M1/M2 builds of Nicotine+.

https://github.com/github/roadmap/issues/528

**Comment by aratuk** [comment]
Tried to package manually on Apple Silicon.

`python3 packaging/macos/setup.py bdist_dmg
Traceback (most recent call last):
  File "/Users/ian/Build/nicotine-mac/nicotine-plus/packaging/macos/setup.py", line 282, in <module>
    add_gtk()
  File "/Users/ian/Build/nicotine-mac/nicotine-plus/packaging/macos/setup.py", line 233, in add_gtk
    add_pixbuf_loaders()
  File "/Users/ian/Build/nicotine-mac/nicotine-plus/packaging/macos/setup.py", line 111, in add_pixbuf_loaders
    open(os.path.join(SYS_BASE, loaders_file), "r", encoding="utf-8") as real_file_handle:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'`

I think it's expecting an older version of gdk-pixbuf that may predate the m1 arch. The version of that package that I have installed, 2.42.10_1, doesn't appear to have a loaders.cache, or I would try linking to it. Tried running `gdk-pixbuf-query-loaders --update-cache` but it didn't produce the expected file 🤔

**Comment by aratuk** [comment]
Okay, got it packaged.

`sudo sh -c '/opt/homebrew/Cellar/gdk-pixbuf/2.42.10_1/bin/gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'`
Generates loaders.cache at the expected location. Would have created it elsewhere and linked it, but the file is itself nothing but a reference to the absolute paths of other files, so  🤷🏻‍♂️

And then I ran into the same problem with glib schemas. Homebrew has glib binaries and the schemas themselves as separate packages.
`sudo /opt/homebrew/Cellar/glib/2.76.2/bin/glib-compile-schemas --targetdir=/usr/local/share/glib-2.0/schemas/ /opt/homebrew/Cellar/gsettings-desktop-schemas/44.0/share/glib-2.0/schemas`

Then `python3 packaging/macos/setup.py bdist_dmg` works as expected, and creates a usable Apple silicon-native application bundle (in a dmg) 😁

**Comment by toineenzo** [comment]
@aratuk Great! Mind sharing the .app / dmg so i can test :)?

**Comment by aratuk** [comment]
Sure, here you go! 👍 
[Nicotine+-3.3.0.dev5.dmg.zip](https://github.com/nicotine-plus/nicotine-plus/files/11521430/Nicotine%2B-3.3.0.dev5.dmg.zip)
(It's in a zip because Github doesn't allow dmgs in comments.)

**Comment by toineenzo** [comment]
> Sure, [here you go](https://github.com/aratuk/nicotine-plus-appl/releases/tag/3.3.0dev5)! 👍
Thanks! I tried it out but unfortunately it doesn't want to launch for me. Instantly closes. Also tried it by signing the .app with my Ad Hoc and developer signature, but no luck

**Comment by toineenzo** [comment]
> Sure, [here you go](https://github.com/aratuk/nicotine-plus-appl/releases/tag/3.3.0dev5)! 👍

Thanks! I tried it out but unfortunately it doesn't want to launch for me. Instantly closes. Also tried it by signing the .app with my Ad Hoc and developer signature, but no luck

**Comment by aratuk** [comment]
Hmm, sorry it isn't working for you!

I'd suggest following the same steps I did on your own machine. Or… assuming you have homebrew and git installed, here's a bash script that replicates the process I followed. Save this text as nicotine.sh and execute it with `sh nicotine.sh`. It'll ask for your password to create some of the files in correct locations. (Of course, you should always review the commands in a script before executing it, so look at it in an text editor first.)

[nicotine.txt](https://github.com/nicotine-plus/nicotine-plus/files/11523708/nicotine.txt)

When the application has finished building, it is located in the packaging/macos/build/ subfolder as a .dmg file.

**Comment by toineenzo** [comment]
Thanks @aratuk ! That worked for me. But not all icons are showing correctly for me 
<img width="1512" alt="image" src="https://github.com/nicotine-plus/nicotine-plus/assets/4921397/b629939b-2d8a-4183-a0b4-f59bab9f6ef1">

**Comment by aratuk** [comment]
Glad it (mostly) works for you! I noticed the same thing with the icons, and I think it must be due to a difference between the default homebrew configuration of one of the dependencies and the way it's set up in the normal deployment environment in Github Actions on this repo. Perhaps the GSettings schemas are different than the ones provided in the 'gsettings-desktop-schemas' package, and my script should point to a different folder for creating gschemas.compiled 🤔 I'll see if I can figure it out, but I can't say I'm an expert on GDK.

As for the export settings function, I'm not sure why it produces a crash. I checked the latest Intel build artifact here, and it doesn't have that issue, so thank you for letting me know!

**Comment by mathiascode** [comment]
> As for the export settings function, I'm not sure why it produces a crash. I checked the latest Intel build artifact here, and it doesn't have that issue, so thank you for letting me know!

This typically happens when the gschemas.compiled file is missing.

I haven't checked the contents of your .dmg file, but I noticed that it's a lot smaller than the Intel builds. IIRC, the Apple Silicon Homebrew packages use different paths sometimes, so it's possible that some required files weren't included when packaging.

**Comment by mathiascode** [comment]
@aratuk https://github.com/nicotine-plus/nicotine-plus/commit/ba2a38b874f39b4237c7d22230858548a2f699ee should fix the issue with missing files. Could you try generating a .dmg again?

Could you also check if the latest unstable build on https://nicotine-plus.org/doc/TESTING.html#macos runs? I enabled hardened runtime, but it might require further changes.

**Comment by slook** [comment]
Nicotine+ 3.3.0rc1 (Release Candidate 1) is available now at link:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos

If somebody here wants to package an M1 port to test and report back findings, that would be great.

**Comment by mathiascode** [comment]
Packaging instructions are available here: https://nicotine-plus.org/doc/PACKAGING.html#macos

Once GitHub starts providing free Apple Silicon CI runners (https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587), we can start building packages automatically.

**Comment by joeynotjoe** [comment]
I just followed the packaging instructions on a MacBook M1 Pro, the app is working great. Using significantly less CPU than the Intel build in my usage, as well. Thanks!

**Comment by mathiascode** [comment]
> I just followed the packaging instructions on a MacBook M1 Pro, the app is working great. Using significantly less CPU than the Intel build in my usage, as well. Thanks!

Nice! Did you compare to the Intel build of Nicotine+ 3.2.9 or 3.3.0rc2?

**Comment by kgantchev** [comment]
> Apple Silicon runners for GitHub Actions are scheduled for Q4 2023 (October-December). Once they are available, we should be able to start providing M1/M2 builds of Nicotine+.   

Might I make a suggestion here? Feel free to use [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Comment by mathiascode** [comment]
Alright, giving FlyCI a shot. For anyone interested, arm64 macOS builds are now available for testing here: https://nicotine-plus.org/doc/TESTING.html#macos

If there are any problems, please open a new issue.

**Comment by kgantchev** [comment]
@mathiascode thanks for giving [FlyCI](https://flyci.net) a try. Please let us know if you run into any trouble. Our team is here to sort out any issues.

Web: [flyci.net](https://flyci.net/) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci) | Discord: [FlyCI](https://discord.gg/JyCjh439da)

**Comment by mathiascode** [comment]
Somewhat awkward timing, but it looks like GitHub has started providing M1 runners for free: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

I'll most likely switch to GitHub's runners for consistency with our other CI jobs, and due to more free usage provided per month, but FlyCI seems like a great service if you need a paid plan or M2 runners.

@kgantchev Thanks for recommending FlyCI, I wish you all the best. From what I've seen in the past few days, FlyCI runners work well. :)

**Comment by kgantchev** [comment]
@mathiascode No problem. We appreciate the fact that you gave FlyCI a try. Please keep in mind that the M1 runners by GitHub eat into your 2,000 minutes and the rate at which they eat into them at [a much faster rate](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes):  "*Using 1,000 macOS minutes, would consume 10,000 minutes included in your account.*"

Staying with FlyCI will allow you not to eat into your 2000 free minutes provided by GitHub. So yo get more minutes in total.

**Comment by kgantchev** [comment]
@mathiascode No problem. We appreciate the fact that you gave [FlyCI](https://flyci.net) a try. 

Please ignore my previous comment on the free tier "limits" for public repos. I was looking at the wrong part of the documentation. Still glad you were part of our Beta.

**Comment by kgantchev** [comment]
@mathiascode I double-checked the [offering from GitHub](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/):

Processor | vCPU | RAM (GB) | Storage| Free Minutes |
-- | -- | -- | -- | -- | -- | --
FlyCI: M1 | 4 | 7 | 28 | 500 |
-- | -- | -- | -- | -- | -- | --
GitHub | M1| 3 | 7 | 14 |  ? | 200 |
-- | -- | -- | -- | -- | -- | --

GitHub's [Free Tier is indeed 2000 minutes](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes). Using [GitHub's MacOS M1 runners](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes) do come with these restrictions: "*using 1,000 macOS minutes, would consume 10,000 minutes included in your account.*" In short, you'll end up with a maximum of 200 mins/month with GitHub's runners and they're only offering 3 vCPUs while we're offering 4 VCPUs and double the storage.

**Comment by mathiascode** [comment]
As far as I know, those limits only apply to private repositories: https://github.com/orgs/community/discussions/70492

Which the billing page for the nicotine-plus organization seems to confirm:

![](https://github.com/nicotine-plus/nicotine-plus/assets/8754153/2ca04621-102d-4e23-87a3-ba3dc5dea823)

**Comment by kgantchev** [comment]
@mathiascode I guess it's back to _"Please ignore my previous comment on the free tier 'limits' for public repos. I was looking at the wrong part of the documentation. Still glad you were part of our Beta."_ 😁 😄
