### ISSUE TITLE
Raspbian support

### ISSUE THREAD

**Issue by diegomadero** [nicotine-plus/nicotine-plus#1476]
### Describe the solution you'd like
I'm running N+ in a RaspberryPi4 with Rasbian (Debian Buster). But I'm having some issues with my current N+ version (1.2.16) that seems to be solved in the stable version. So I wanted to install N+ from the PPA for Ubuntu/Debian, but i'm getting this error:
```

$ sudo add-apt-repository ppa:nicotine-team/stable
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find 


```

**Comment by mathiascode** [comment]
You might have to add the repository directly to `/etc/apt/sources.list`. Try adding the following line:

`deb http://ppa.launchpad.net/nicotine-team/stable/ubuntu bionic main`

then

```
sudo apt update
sudo apt install nicotine
```

**Comment by mathiascode** [comment]
Out of curiosity, which issues were you facing in 1.2.16?

**Comment by diegomadero** [comment]
Thanks! It worked. I only had to add the key 
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6CEB6050A30E5769`
This is the issue I was having (Some error scanning my Shared folders). But it seem to be fixed now with the upgrade :) Thanks! 
https://github.com/Nicotine-Plus/nicotine-plus/commit/98f3dfa285656763e6c095ae22a6ae61ee98b764
