### ISSUE TITLE
SourceForge project page is very outdated

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1477]
Nicotine+ version: All old, current and future versions.

Operating System/Distribution: Windows only, but could potentially be others.

### Describe the bug
The page at https://sourceforge.net/projects/nicotine-plus/ is seriously outdated:

- 1.2.16 is the latest version available from the page at that URL, which is now very old and considered obsolete.

- The title of the page "Nicotine-Plus: PyGTK2 Soulseek Client" is not indicative of the projects current GTK3 interface.

### Expected behavior
The current version -which is at least Nicotine+ 3.1.1 - should be available from the SourceForge project page. Or the page should be taken down so that is doesn't appear in the SERPs.

The title of the page should be renamed to "Nicotine+" to match the newer branding.

### Steps to reproduce the bug
Visit the URL https://sourceforge.net/projects/nicotine-plus/

### Additional context
"Brought to you by: daelstorm, el_verde" indicates the previous devs who are no longer active and seem to have abandoned the project page on SourceForge, which makes the nicotine-plus project seem inactive.

Basic guidance is provided in the "Taking Over Abandoned Projects" page in the SourceForge support wiki at link:
https://sourceforge.net/p/forge/documentation/Abandoned%20Projects/

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/discussions/1594
