### ISSUE TITLE
GNU Guix project page is outdated

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1478]
Nicotine+ version:  All old, current and future versions.
Operating System/Distribution: x86_64-linux, i686-linux, armhf-linux, aarch64-linux, powerpc64le-linux

### Describe the bug
The page at https://guix.gnu.org/en/packages/nicotine+-2.1.2/ is outdated:

- 2.1.2 is the latest version available from the page at that URL, which is now very old and considered obsolete.

- The URL of the project page "/nicotine+-2.1.2" creates problems for maintaining a current package on that web page, and is therefore not good for SEO or end-user updates now that the project is stable and frequently updated.

### Expected behavior
The current version -which is at least Nicotine+ 3.1.1 - should be available from the GNU Guix project page. Or the page should be taken down so that is doesn't appear in the SERPs.

The URL of the page (name of the package) should be renamed to "nicotine-plus" to match the main GitHub project page, so that a package can be maintained on the GNU Guix package distribution repo and user-facing website.

### Steps to reproduce the bug
Visit the URL https://guix.gnu.org/en/packages/nicotine+-2.1.2/

### Additional context
Resolving this bug could help to remedy the perception that Nicotine+ is a dead project, which obviously it is not.

There is no indication of whom maintains the Guix project page. Contact details are provided , which may be helpful for a project dev to regain control of the GNU repo and Guix project page, at the following link:

https://guix.gnu.org/en/contact/

"Guix is currently maintained by Ludovic Courtès, Marius Bakke, Maxim Cournoyer, Tobias Geerinckx-Rice and Mathieu Othacehe. Please use the mailing lists for contact. For sensitive issues, you can reach them using the guix-maintainers@gnu.org private alias."

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/discussions/1594
