### ISSUE TITLE
Open Source Libs project page is outdated

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1479]
Nicotine+ version:  All old, current and future versions.
Operating System/Distribution: All.

### Describe the bug
The page at https://opensourcelibs.com/lib/nicotine-plus displays an old static version of README.md - from which the latest version is 2.1.1 which is now obsolete and appears on first page of the SERPs for the search query "nicotine-plus", making end-users and upstream think that Nicotine+ is still unmaintained.

### Expected behavior
The page on this website should display the current [README.md](https://github.com/nicotine-plus/nicotine-plus#readme)

Or if the Open Source Libs website is not capable of embedding the live document, then some unique content needs to be created that is version agnostic and simply links to the [Nicotine+ main project page on GitHub](https://github.com/nicotine-plus/nicotine-plus).

### Steps to reproduce the bug
Visit the URL https://opensourcelibs.com/lib/nicotine-plus

### Additional context
The Open Source Libs website appears to be run by a gentleman called Mike, see link:
https://opensourcelibs.com/contact

"You can contact Mike by emailing: opensourcelibs@gmail.com "

Mike's website does not feature any Login functionality that would allow user's to update hosted static content directly, therefore static content which is version agnostic needs to be created for submission to Mike's email address (see above).

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/discussions/1594
