### ISSUE TITLE
PythonRepo project page is outdated

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1480]
Nicotine+ version: All old, current and future versions.
Operating System/Distribution: Windows, MacOS, Linux, BSD, All

### Describe the bug

As mentioned in #1479 ...

> Unfortunately, there seem to be similar cases: https://pythonrepo.com/repo/Nicotine-Plus-nicotine-plus-python-miscellaneous

The page at [PythonRepo](https://pythonrepo.com/repo/Nicotine-Plus-nicotine-plus-python-miscellaneous) displays an old static version of README.md - from which the latest version is 3.0.2 which is not the current version, making end-users and upstream think that Nicotine+ is still unmaintained.

### Expected behavior

> Ideally the page on this website should be a simple page that's automatically generated from the readme's markdown.

It would be ideal when posting to some random site where embedding hyperlinked .md is not possible, then it would be prudent to use some static content for the 'Overview' section that is version agnostic, to ensure that soulseekers are not confused.

### Steps to reproduce the bug
Visit the URL https://pythonrepo.com/repo/Nicotine-Plus-nicotine-plus-python-miscellaneous

### Additional context
The maintainer of the PythonRepo profile/page needs to be made known to @mathiascode

**Comment by mathiascode** [comment]
Closing since there's no course of action.
