### ISSUE TITLE
Add deb repo for Debian

### ISSUE THREAD

**Issue by 35609902357** [nicotine-plus/nicotine-plus#1486]
Debian 11 is the first release to not package Nicotine+, they [dropped it for good](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955514).

The Readme asks Debian users to add a PPA to their system. Notoriously PPAs are problematic for Debian, they often end up breaking something. A Debian repository should be added as a way to distribute the applications for Debian users.

Ubuntu users will also benefit from the repo because they use the same repo-system Debian uses, but Debian doesn't use Ubuntu's PPAs.

**Comment by 35609902357** [comment]
@mathiascode what do you think?

**Comment by mathiascode** [comment]
OBS looks interesting, and I could potentially look into it, but it's not high priority at the moment. Too many other things going on in the issue tracker.

**Comment by now0clock** [comment]
I've been using the 'org.nicotine_plus.Nicotine' Flatpak running on Debian (GNOME) for quite a while now. It works great, The gnome-software plugin makes it easy to update/upgrade for new releases. I also have Ubuntu 21.04 on another pc with the PPA for nic+ in my sources.list which also works ok, despite a few critical errors I found a workaround for. I'm more of a Debian person though. I recommend using the Flatpak version for Debian.. https://flathub.org/apps/details/org.nicotine_plus.Nicotine

In your Debian terminal see:
`apt show gnome-software-plugin-flatpak`

Here's a simple guide: https://flatpak.org/setup/Debian/

Then do two more commands,

`flatpak install flathub org.nicotine_plus.Nicotine`

`flatpak run org.nicotine_plus.Nicotine`

and it should run fine.

**Comment by mathiascode** [comment]
> despite a few critical errors I found a workaround for

Could you mention what these errors are, if they can be fixed in Nicotine+ itself?

**Comment by now0clock** [comment]
@mathiascode 
> Could you mention what these errors are, if they can be fixed in Nicotine+ itself?

[Nicotine+ ubuntu critical error.txt](https://github.com/nicotine-plus/nicotine-plus/files/7272916/Nicotine%2B.ubuntu.critical.error.txt)

Nic+ would crash almost instantly in Ubuntu after running it. What I ended up doing was opening settings (quickly!) before the critical error window showed up with what's in the txt file^. It took me a few tries, but I instantly went to Preferences > General > Network and disabled "Auto-connect to the server on startup" I exported a backup.tar.bz2 while I was in there just in case. I disabled plugins, disabled auto join chat rooms, disabled notifications, and closed all chat tabs. Killed the nicotine process, then restarted. No more critical error. Connected to the server manually and it worked fine again..

**Comment by mathiascode** [comment]
Looks like https://github.com/nicotine-plus/nicotine-plus/issues/1569, which will be fixed in Nicotine+ 3.2.0.

**Comment by 35609902357** [comment]
@mathiascode There's also [MPR](https://mpr.hunterwittenborn.com/)

**Comment by slook** [comment]
Closing since #1448 supersedes, the suggested intrim measures shall not be required.
