### ISSUE TITLE
Implement Ctrl-Z undo for text entries

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#1489]
Support for text undo is present in GTK 4, but needs a custom implementation in GTK 3.

**Comment by slook** [comment]
I don't know if users are really that desperate for text undo support? so I wouldn't break your back over this.

Besides, the various History features already seem to provide enough ways of recovering previous queries in a more logical way.

**Comment by mathiascode** [comment]
If more people want this, feel free to add a reaction to the issue.

**Comment by 82d** [comment]
what does GTk 3 need for this?

**Comment by mathiascode** [comment]
> what does GTk 3 need for this?

Keybindings, history tracking, the whole logic for a undo/redo function essentially.

**Comment by mathiascode** [comment]
Since GTK 4 support in Nicotine+ is mostly finished (https://github.com/nicotine-plus/nicotine-plus/issues/15549), I don't think it's worth implementing this for GTK 3 anymore.

**Comment by slook** [comment]
The above link should be https://github.com/nicotine-plus/nicotine-plus/issues/1554 (without the "9" at the end)
