### ISSUE TITLE
Assign the File Search Results graphical tree model to any column (GtkTreeView)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1493]
### Describe the problem
When customizing the order of the columns in either "Group by Folder" or "Group by User" mode, the user is forced to have the 'User' column as the first column at the far left, because the graphical tree model appears to be rendered specifically for being in the User column and is not tolerant of the other columns sharing space with it.

It creates a garbage layout if any other columns are set to be the first column, the tree branches end in dead space if for example result values in the Folder column are assigned to it, but it is not designed for that column so it looks bad.

It is restrictive that there is no provision for it to be drawn in another column position, if that should be what is desired for any particular use case scenario.

### Describe the solution you'd like
Perhaps it would be nice if the User column could be positioned at any column position along the width of the table, in which case the graphical tree model would need to follow the User column's position, as per the operator's personal preference.

Although, who knows perhaps it would also be useful if the Folder column shares a column with the graphical tree model if desired, but the tree branches would then need to be re-dawn as per the differences in the nodes provided by the Folder results so that it would look correct.

- Preferably, at the very least, it would be nice for the tree to rendered in whatever User column position is desired, as an alternative to it being stuck on the left-most column, if possible?

- Ideally, a suitable tree model could be rendered into any appropriate column (Folder being the main alternative), (perhaps even visible in multiple positions), and then switched or toggled on/off by means of a context menu option in the Results table header bar or some other such?

The Search Files window is what I consider to be Nicotine+'s main screen, as this is what is visible for the majority of the time the client is being actively interacted with by Soulseekers, so I feel it is very important that the Results table widget provided by GtkTreeView looks tidy and is user friendly, but currently neither of these things about it are true (imho no offense intended!).

### Additional context
See Link:
https://www.gnu.org/software/guile-gnome/docs/gtk/html/GtkTreeModel.html#GtkTreeModel

**Comment by mathiascode** [comment]
So, you basically want either:

1. expanders always follow the user column
2. expanders are always in the left-most column, but can be shown/hidden?

**Comment by slook** [comment]
It is not appropriate for any other column to be with the expanders, so option 1 seems like the most practical:

> 1. expanders always follow the user column

**Comment by mathiascode** [comment]
The grouped views mostly resemble SoulseekQt's, and I don't want to change our implementation too much. I think a combined column would result in additional issues, such as sorting and potential complexity. The expanders are also a key feature of the grouped modes, so I don't want to hide them.

We could potentially hide the tree lines if some rows are empty, to make the appearance less jarring. I tried attaching the expanders to the user column, but it looks awkward to me.

**Comment by slook** [comment]
Thank you for looking into it

> I don't want to change our implementation too much

Sorry I already wrote issue #1494 before I read your message! Still, perhaps if you saw my vision you would change your mind.

The ultimate idea I have is less of a "change" and more of an "addition", where there would always be the option to retain the existing functionality.

> a combined column would result in additional issues, such as sorting and potential complexity

Yes, I very much guessed that this kind of thing would likely present a significant barrier, and carries a high risk of introducing new bugs or other undesirable quirks.

Having the flexibility of the expanders sitting well with the folders is great, are they still stuck to the left?

**Comment by mathiascode** [comment]
This isn't something I'll implement for now. We can perhaps revisit this when implementing https://github.com/nicotine-plus/nicotine-plus/issues/1494 (it would make more sense for that layout imo), but always forcing the expander to be positioned in the user column also feels awkward if you move the column far to the right.
