### ISSUE TITLE
Search Scope button pop-up menu items positioned above top of screen (Linux)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1495]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: Linux (MX18.3 and MX19.4)

### Describe the bug
When the Nicotine+ window is in it's default maximized state, or otherwise positioned at the top of the screen, the 4 options in the Search Scope pop-up menu (Global; Buddies; Rooms; User) are awkward to get to because they disappear off the top and scroll controls appear in the menu, when anything other than 'Global' is selected. This UI bug looks worst when 'User' is selected:

![nicotine-plus Search Scope button pop-up menu UI bug](https://user-images.githubusercontent.com/88614182/131235454-311dd446-e66a-45fe-98de-34386863d0de.png)

This could be difficult for a new user to realize that there are other options in that menu, because a manual action is required to make the menu scroll up so that all 4 options are visible.

### Expected behavior
The pop-up menu should appear below the button, in a similar fashion to the DropDown-ComboBox next to it.

### Steps to reproduce the bug

1. Maximize the Nicotine+ main window, or position it at the top of the screen.
2. Select 'User' from the Search Scope menu in the Search Files tab.
3. Press the button to make another selection.
4. The menu is borked.

### Additional context

On MX 18:
![nicotine-plus Search Scope list position above top of screen UI obstruction](https://user-images.githubusercontent.com/88614182/131235562-aacf69e9-8f00-4026-9f5c-fcd9fcb86140.png)

On MX 19:
![nicotine-plus Search Scope button pop-up menu UI bug on MX19](https://user-images.githubusercontent.com/88614182/131235569-6bc096f4-d393-4916-81fc-d14aa7bbe290.png)

**Comment by mathiascode** [comment]
I didn't think this issue was possible to resolve, but I managed to find a workaround.

**Comment by slook** [comment]
FYI @mathiascode it seems that your excellent workaround also needs applying to the 'Room type' pop-up menu in Chat Rooms:
![nicotine-plus Chat Room type menu scroll off top of screen](https://user-images.githubusercontent.com/88614182/131703614-cfca6ac9-6f7b-48a6-ae9d-c0c5ea2b4786.png)
(MX18, MX19) 3.1.2.dev1  •  GTK 3.22.11

**Comment by slook** [comment]
Fixed in https://github.com/nicotine-plus/nicotine-plus/commit/5ece70f92b95da9aff3b5438de8b29beb69d0b8f
