### ISSUE TITLE
Filter bar layout issues (Result Filters)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1497]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: Linux (MX18 and MX19)

### Describe the bug
After using the Include and/or Exclude result filter(s), the text entry box loses it's non-default custom 'Text Entry Background Color' (as defined in Preferences > General > User Interface).

Even after the Result Filter is cleared, the custom color is lost forever until the search child-tab is closed, which makes it/them appear to be greyed-out.

The other Result Filter text entry boxes (Type, Size, etc) are not affected.

This UI bug has been present ever since Nicotine+ 3.0.x (GTK3).

### Expected behavior
These two text entry boxes should retain their custom color settings as per the user's Preferences, like all the other UI interface objects in N+ do.

Ideally, active text entry boxes (that are not empty) could be highlighted brighter to indicate what Result Filter(s) are in use (but that would require an additional custom color Preference 'Text Entry Highlighted Background Color' which is beyond the scope of this issue), but in any case, UI controls definitely should not get dimmer unless they are disabled.

### Steps to reproduce the bug

1. Define a custom 'Text Entry Background Color' in Preferences > General > User Interface).
2. Use the Include or Exclude text entry box to apply a Result Filter in Search Files.
3. The color is changed to OS theme default.
4. Clear the active filters.
5. The color is still borked.

### Additional context
This bug was noticed by one of my DJ/producer student's who has a learning difficulty.

MX18:
![nicotine-plus Custom Text Entry Background Color lost in Include and Exclude text entry boxes (Result Filters) MX18](https://user-images.githubusercontent.com/88614182/131250131-05b0da6c-05e4-456a-b1bf-446059a367d1.png)

MX19:
![nicotine-plus Custom Text Entry Background Color lost in Include and Exclude text entry boxes (Result Filters) MX19](https://user-images.githubusercontent.com/88614182/131250139-7143ec92-1f60-495b-b96c-aa0f11e84ad4.png)

As can be seen from the MX19 image, the Result Filter pane suffers from a quirky UI layout on narrow width viewports, due to the responsive stacking obstructed by the Free Slot, Clear and Help buttons. The behaviour is less than ideal, suggesting that overall UI enhancement(s) of the Result header / Result Filter pane layout are needed to better support narrow width viewport scenarios.

If the user requires custom UI colors due to an impairment, or to workaround a slightly dodgy high-contrast/dark GTK theme, then this UI bug becomes an accessibility issue, see link:
[Guidance on Applying WCAG 2.0 to Non-Web Information and Communications Technologies (WCAG2ICT) Success Criterion 3.2.2: On Input](https://www.w3.org/TR/wcag2ict/#consistent-behavior-unpredictable-change)

**Comment by mathiascode** [comment]
The main issue is fixed, but

> As can be seen from the MX19 image, the Result Filter pane suffers from a quirky UI layout on narrow width viewports, due to the responsive stacking obstructed by the Free Slot, Clear and Help buttons. The behaviour is less than ideal, suggesting that overall UI enhancement(s) of the Result header / Result Filter pane layout are needed to better support narrow width viewport scenarios.

I currently don't know how to fix this with the with the widgets provided in GTK. I could separate the country field from the end of the bar, but this would result in a large gap between these sections.

**Comment by slook** [comment]
I was thinking to move a couple items from the Filter bar, and put them in the header bar instead, something like this...

![nicotine-plus File Search Result Filters panel needs better responsive layout](https://user-images.githubusercontent.com/88614182/131263203-d93b259a-2e0a-49c8-ab9f-947a58ed0daa.png)

**Comment by slook** [comment]
Closing this Bug in favor of https://github.com/nicotine-plus/nicotine-plus/discussions/1535#discussioncomment-1444130, since the main problem with the text entry background color was resolved in https://github.com/nicotine-plus/nicotine-plus/commit/276473929b34cf020a3cfdd268e67ed2d5d64576
