### ISSUE TITLE
Fix missing Alt+F accelerator for Result Filter bar show/hide button (Search Files)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1500]
### Describe the solution you'd like
F is usually for "Find" but in the case of the Search Files interface it is also appropriate for the 'Include' text entry "Filter" parameter, because this functions very well like a Find facility and is already implemented.

`Ctrl+F` would need to show the Filter bar it was hidden, and then jump the focus to the 'Inlcude' text entry box so it is ready for user input.

`Alt+F` would make sense, the 'Result _Filters' toggle button needs a key accelerator anyway, then this should allow both show and hide of the bar.

Please note a special Escape mechanism may be required so that a TextBox entry field Clear operation that may be implemented in the future is not obstructed, so `Esc` to hide the Filter bar may not be appropriate here, see issue #1499 

### Additional context
This enhancement is suggested to improve accessibility, see link:
[Guidance on Applying WCAG 2.0 to Non-Web Information and Communications Technologies (WCAG2ICT) Success Criterion 2.4.5: Multiple Ways](https://www.w3.org/TR/wcag2ict/#navigation-mechanisms-mult-loc)

"Providing an opportunity to navigate software programs in more than one manner can help people find information faster. Users with visual impairments may find it easier to navigate to the correct part of the software program by using a search, rather than scrolling through a large navigation bar using a screen magnifier or screen reader."

**Comment by mathiascode** [comment]
> `Alt+F` would make sense, the 'Result _Filters' toggle button needs a key accelerator anyway, then this should allow both show and hide of the bar.

The accelerator is present, but not working for some reason.

**Comment by slook** [comment]
In which case @mathiascode this issue should be changed from Enhancement to Bug

**Comment by mathiascode** [comment]
> `Ctrl+F` would need to show the Filter bar it was hidden, and then jump the focus to the 'Inlcude' text entry box so it is ready for user input.

This should be implemented now.

**Comment by slook** [comment]
Yes, and I like the way it Selects All the previous query. In the long-run I think the hide toggle behavior would be more suited to the Alt+F accelerator implementation, whereas Ctrl+F would be expected to jump the focus to the Inlcude entry box even it was already visible.

Right now tho this current implementation works well, because there is no other escape mechanism yet so it's good to be able to get back into the TreeView. Nice job.

**Comment by slook** [comment]
I have made a blunder here @mathiascode the `Alt+F` key conflicts with the native **_File** menu (with Header Bar off), blocking essential key navigation both ways. 

Therefore, it must be changed. I suggest `Alt+R` for "_Result Filters" or "_Refine" or "_Refine Search".

**Comment by slook** [comment]
@mathiascode please Re-open this issue as the accelerator I suggested conflicts with the native _File menu. Sorry.

Note: the three minor accelerator label issues are blocking #1518
