### ISSUE TITLE
Primary Tab Bar fails to surrender focus after second mouse-click (Main Window)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1502]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: MX18

### Describe the bug
When a main window Tab is clicked more than once in sequence it fails to surrender focus like it should for all subsequent mouse-clicks on any tab.

The most obvious example is the 'Search Files' tab, which passes focus nicely the first time, but not the second time, nor the third.

Thereafter, the ugly focus rectangle becomes visible, then if the user selects another tab, say Downloads, then the TreeView isn't passed the focus, so scrolling up doesn't work. Edit: with the Up key.

### Expected behavior
The main window Primary Tab Bar should behave in the same way no matter how many times it is clicked.

For example if the user clicks 'Search Files' then the search text entry box should always be focused ready for entry, even if they are already on the Search Files tab. Infact, the user may have good reason to believe that it is the purpose of that item.

The focus rectangle should never appear because it looks ugly and serves no useful purpose now that issue #1485 has been implemented. Enabling arrow-key tab navigation upon mouse-click increases the chance of collisions in the main interface, so it's better if this is not allowed when clicked on with the mouse. Afterall, if the user has clicked a tab with the mouse, they must intend to use that for selecting tabs and not keys.

### Steps to reproduce the bug
Click on any Primary Tab more than once with the mouse.

1. Select a Download half way down the list
2. Click on Search Files tab bar
3. Click on Search Files tab bar again and again,
4. Be frustraited that nothing happens, give up trying to search,
5. Click on Downloads tab bar
6. Try scrolling Up with the `Up` key
7. Try scrolling Down with `Down` key, but it doesn't work the first time.
8. Conclude that the interface must be laggy.

### Additional context
This UI bug is an accessibility issue because it causes a keyboard block.

**Comment by mathiascode** [comment]
This isn't possible, but I've set default focus widgets for all primary tabs at least.

**Comment by slook** [comment]
Thanks @mathiascode .

Please see https://github.com/nicotine-plus/nicotine-plus/commit/becab4dd047129c4ec700088de4c1e6719e1b37d#commitcomment-55758106
