### ISSUE TITLE
Put the options for Tab Label Colors into the Tab section (Preferences)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1505]
### Describe the solution you'd like
As title.

Also, Chat Colors into Chat catagory

### Additional context
The Tab Colors are difficult to find at the bottom.

None of the options in the Chat Colors section of General > User Interface category are actually about UI elements, so they don't seem to belong there. Besides, the User Interface category is too long.

**Comment by mathiascode** [comment]
I don't think it's worth splitting out chat colors from the UI section. I've rearranged the layout a bit, let me know what you think.

**Comment by slook** [comment]
Yes I have commented in https://github.com/nicotine-plus/nicotine-plus/commit/4f7902742f4aeb29c8ee799e665ecb6a15a7d786#commitcomment-55730299

**Comment by slook** [comment]
I agree, now that you have put the correct Sections in the better order, the Preferences now make a lot more logical sense (at the standard width).

There remains some issues regarding the size of the window, but that is unrelated to this issue.
