### ISSUE TITLE
Scrap the redundant 'Clear All Colors' button from User Interface catagory (Preferences)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1506]
### Describe the problem
These two buttons look dangerous to me:
![nicotine-plus Default Color and Clear All Color](https://user-images.githubusercontent.com/88614182/131440666-b7aeb7f0-1912-4593-a50c-f5a2a94728de.png)

Which one? Decisions decisions...   <-- DECIDED: keep "Default Colors"

### Additional context
Having these buttons here is redundant, separate functions are provided elsewhere in the dialog (editable textboxes, default buttons) to return individual settings to default if required.

At a quick glance, as these buttons are at the bottom the icons on them look like Reload and Cancel for the Preferences window. It will be interesting to know how many users have clicked them by mistake!

If the Color options are going to be split up into several different sections and categories, then these buttons won't make sense anymore. 

It is not clear to me what the Clear Colors button does? How is that different from Default Colors? Why are there two separate buttons? It's very confusing.

**Comment by mathiascode** [comment]
"Default Colors" makes more sense to keep, and I personally find it useful. "Clear Colors" has been there from the beginning, but I'm not sure what it's needed for.

**Comment by slook** [comment]
I haven't clicked it, I'm guessing it will clear all the text boxes with the Hex values. That is not a useful function to have, an it's icon is very misleading because it looks like a "Back" button.
