### ISSUE TITLE
Dialog box drawn larger than small screen size makes OK and Apply buttons invisible (Preferences)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1508]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: MX 19.4
Display Resolution: 800 x 600

### Describe the bug
When opening the Preferences window on a display that is only 800px wide, the OK and Apply buttons are completely inaccessible because it hangs off the right of the viewport.

To make matters worse, the OK and Apply buttons are in a non-standard location for users who are not familiar with GTK3 apps.

It is also taller than the screen, making some options inaccessible.

If you were not familiar with this window, it might not look obvious that there is any problem, so it appears that the only option is to Cancel, then any Preferences data the user has set will be lost.

The Export dialog has the same problem, there is no Save button on that screen when viewed on a 800x600 display.

### Expected behavior
When this and any dialog box is opened, it must not be allowed to draw itself larger than the screen size minus any taskbar(s). This should be checked OnLoad, then resized if needed, then re-centered, before it becomes visible.

The Preferences window has a responsive layout and can mostly handle being sized to it's hard minimum 641px narrow, apart from some inconsistent stacking of Chat Label Colors; List and Search Colors; etc, whose TextBox fields should ideally be much smaller to prevent odd stacking below 735px, a hard minimum of 640 should be possible if the Color options were fixed. On my GTK theme, it looks nicest at about 800x700 imo.

On viewports of =< 800x600, it might be simpler and user-friendly to load any dialog(s) maximized.

Also, the Preferences window, nor any other dialog, do not need it's own TaskBar button in the OS, because the parent N+ window is not selectable whilst it is deactiveated.

### Steps to reproduce the bug

1. Set the display resolution to 800x600
2. Open the Preferences window
3. The OK and Apply buttons cannot be seen.
4. The only option is to Cancel.
5. Any Preferences data the user has set might be lost if the OK button cannot be found.

### Additional context
![nicotine-plus Preferences window too wide](https://user-images.githubusercontent.com/88614182/131444024-f14db7d8-02d2-4fd5-ba2e-dd8a6c9c88b6.png)
This UI bug is an accessibility issue, because it prevents a keyboard-less user from using the mouse to operate the dialog box.

**Comment by slook** [comment]
Keyboard Shortcuts window also affected a similar UI bug, but only on the first time, see screenshots:

MX18:
![nicotine-plus Keyboard Shortcuts opens in a strange position the first time MX18](https://user-images.githubusercontent.com/88614182/131539620-67faa80c-b529-49c4-ae03-18449e42e966.png)
= 1366 x 768

MX19:
![nicotine-plus Keyboard Shortcuts opens in a strange position the first time MX19](https://user-images.githubusercontent.com/88614182/131540518-5eb48ab4-72d4-4645-8e52-193517829c20.png)
= 800 x 600 (note also that fixed dialog is just a few pixels off from being ideal for 800x600-24px taskbar) = 800x575

- **After the first time, it is fine and displays in the center like it should.**

**Comment by mathiascode** [comment]
> Keyboard Shortcuts window also affected a similar UI bug, but only on the first time, see screenshots:

See https://github.com/nicotine-plus/nicotine-plus/commit/c137d69e0c7082505775469b7909984b83baaceb#commitcomment-55661310

Can you check what the behavior is like in other GNOME apps?

**Comment by slook** [comment]
No, the problem is still keyboard shortcut window wonky the first time open.

**Comment by mathiascode** [comment]
Yes, I know, the commit did not claim to fix any positioning issue. I'm asking you to verify if the issue occurs in the keyboard shortcuts window of other GNOME apps on your system. I've personally seen it happen elsewhere too, which points to this being a GTK bug in the shortcuts window.

**Comment by slook** [comment]
I dont know where any other of those windows exist?

Give me an example of an app that's got one.

**Comment by mathiascode** [comment]
Gedit, Nautilus, Epiphany, GNOME calculator, any standard GNOME apps essentially.

**Comment by slook** [comment]
I dont have any GNOME apps installed. Running them requires a lot of extra runtime dependancies to be added and I'm not sure it's compatible with my OS?

**Comment by slook** [comment]
Yes you were right, exactly same problem, see screenshot:

![gedit keyboard shortcut window gtk bug](https://user-images.githubusercontent.com/88614182/131546442-9b602f10-3f0e-448d-9c23-1cdbfbbf0303.png)

However, this bug shows up even worse in Gedit because it always shows in the wonky position the 2nd, 3rd and so on.

Whereas, N+ it is only on the first time, after that it is perfect in the center.

**Comment by mathiascode** [comment]
I think it has something to do with the window contents loading slightly after the window is displayed. We hide the dialog after it's shown the first time, instead of recreating it each time, which mitigates the issue somewhat.

**Comment by slook** [comment]
Yes but I do not move it manually, it centers itself.

**Comment by mathiascode** [comment]
The window is hidden but semi-reset, so it appears at its original position (centered) again.

**Comment by slook** [comment]
Cool, so then if it is capable of centering itself the second time, then why can't it do it the first time I wonder?

**Comment by mathiascode** [comment]
> Perhaps as a workaround you can preload it hidden, before the user opens it for real.

I tried, but this didn't work. What seems to work is to show and hide the window immediately on first load, then show it again for real.

**Comment by slook** [comment]
Confirm this GTK bug also exists on MX19 Buster running Gedit, see screenshot:

![gedit keyboard shortcut window gtk bug png MX19](https://user-images.githubusercontent.com/88614182/131549574-5646f62b-f1ea-48db-81c1-be5404e6fa1a.png)

**Comment by slook** [comment]
Yes!!! You have finessed it again :-)

MX Linux 19.4 (Debian 10 Buster):
![nicotine-plus Keyboard Shortcuts opens in a strange position the first time MX19 FIXED](https://user-images.githubusercontent.com/88614182/131553700-9de3ad7f-0c92-4d49-88b1-cb54bfe0d627.png)
(800 x 600)


MX Linux Continuum 18.3 (Debian 9 Stretch LTS):
![nicotine-plus Keyboard Shortcuts opens in a strange position the first time MX18 FIXED](https://user-images.githubusercontent.com/88614182/131553279-70ab91da-9781-4ef3-b187-03b89538d7ea.png)
(1366 x 768)


Wow that is so much better, someone could actually use a computer like that now!
