### ISSUE TITLE
Show list of logged private chat users

### ISSUE THREAD

**Issue by Rings4** [nicotine-plus/nicotine-plus#1509]
### Describe the solution you'd like
One of the features holding me back from transitioning from SoulSeek-qt to Nicotine+ is the fact that closing a chat completely hides it. I want to be able to see all my past chats in a list, the same way the qt client does. Please refer to image.

### Additional context
![image](https://user-images.githubusercontent.com/32050292/131620919-3e20fa33-44e1-4b59-86be-e33c4a937158.png)

**Comment by slook** [comment]
This additional feature would perhaps be too complex to implement at this time.

However, I agree with @Rings4 underlying sentiment that an easier way(s) to save chats is needed, for example a "`S`ave Room Log... (Ctrl+S)" option in the room messages context-menu would be very useful for when 'Log chatrooms by default' is turned off (the factory setting). Besides, the infinite room logs can become rather large so I imagine few users have this turned on.

Then at least, the user would be able to keep important chats without having to manually create a text file by themselves.

The default/suggested filenames would ideally need to be easy to sort such as:
- 'roomname yyyy-mm-dd hh:mm [username].log'

and stored in the default profile .nicotine/logs/rooms folder since there is no other better place for it.

**Comment by mathiascode** [comment]
@slook I don't think this is relevant for this issue report. What's being asked for is a list for all past private conversations, even after the tabs have been closed. Clicking on a user in the list re-opens the conversation in a new tab.

**Comment by slook** [comment]
> Clicking on a user in the list re-opens the conversation in a new tab.

Oh I see, thanks I didn't know that.

>  I don't think this is relevant for this issue report.

I agree that makes my suggestion an entirely separate matter then.

**Comment by Rings4** [comment]
> @slook I don't think this is relevant for this issue report. What's being asked for is a list for all past private conversations, even after the tabs have been closed. Clicking on a user in the list re-opens the conversation in a new tab.

Exactly my thoughts, thanks. 

Yeah, I know you can reopen a chat from your user list. But I don't add everyone I chat with to my user list unfortunately. Wish it worked the same as qt.

**Comment by mathiascode** [comment]
I was thinking about introducing a user history popover similar to the chat room list, containing a list of logged users and the last message in the conversation. This would allow the list to be accessed from any chat tab, without the need to scroll to a special "Message List" tab when many tabs are open, and would also be easier to implement.

**Comment by Rings4** [comment]
> I've been thinking about introducing a user history popover similar to the chat room list, containing a list of logged users and the last message in the conversation. This would allow the list to be accessed from any chat tab, without the need to scroll to a special "Message List" tab when many tabs are open, and would also be easier to implement.

What a coincidence for you to respond after 5 months of inactivity in this issue just as I linked this issue to someone on another site. It's as if you saw me post it on that other site haha.

Sure, that sounds good. I'd like for the last line of each chat to be displayed similar to Qt as well. Hope that's doable!

**Comment by mathiascode** [comment]
> What a coincidence for you to respond after 5 months of inactivity in this issue just as I linked this issue to someone on another site not even 5 minutes ago. It's as if you saw me post it on that other site haha.

I did. ;)

The TODO list for this project is always quite large, but I'll implement this feature request when I have time.

> Sure, that sounds good. I'd like for the last line of each chat to be displayed similar to Qt as well. Hope that's doable!

Should be doable by reading the last line in the log file.

**Comment by Rings4** [comment]
> > What a coincidence for you to respond after 5 months of inactivity in this issue just as I linked this issue to someone on another site not even 5 minutes ago. It's as if you saw me post it on that other site haha.
> 
> I did. ;)
> 
> The TODO list for this project is always quite large, but I'll implement this feature request when I have time.
> 
> > Sure, that sounds good. I'd like for the last line of each chat to be displayed similar to Qt as well. Hope that's doable!
> 
> Should be doable by reading the last line in the log file.

Oh you did! Ha, what luck! 

Awesome, much appreciated! I'd love nothing more than to finally start using this client since I really appreciate that it keeps track of uploads. I love keeping track of that kind of stuff.

Would be super convenient if you can also figure out how to import chats from qt like #1685 suggested. As well, would it be possible to import our userlists complete with ignored and unshared lists?

**Comment by mathiascode** [comment]
I've implemented a basic history view in https://github.com/nicotine-plus/nicotine-plus/commit/7d71260e0455ec13348443ccdca343683ba1291e. It can be polished further at a later point, if desired.
