### ISSUE TITLE
menu separator does not follow gtk+ rules

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#151]
with 2 different gtk+ themes, separators in menus are not well displayed it looks like padding 10px instead of 1px (or 2) 
sorry for that i am theme monomaniac ...

**Comment by mathiascode** [comment]
I noticed this too when not using the default theme. I'll look into it.

**Comment by zniavre** [comment]
are you using adwaita theme ?

**Comment by mathiascode** [comment]
Yeah
