### ISSUE TITLE
Chat view context-menu Copy has no function when nothing is selected (Chat)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1512]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: Linux (MX18, MX19), All

### Describe the bug
When no selection is highlighted in the the chat messages view, selecting 'Copy' from the context-menu does nothing.

### Expected behavior
The 'Copy' option should be disabled so that it is greyed-out when no copy operation is possible.

While URL's are underlined, provision for copying the URL into the clipboard is normally expected without requiring a manual selection.

### Steps to reproduce the bug
Right-click on the message view, and select copy.

### Additional context
This UI bug is most frustrating when trying to copy a username or an underlined URL, a function expected but not provided, see screenshot: 
![nicotine-plus Chat view context-menu Copy is not disabled when nothing is selected (Chat)](https://user-images.githubusercontent.com/88614182/131658229-a4ba97fd-27cc-46ff-8ded-42c1bdb96af3.png)

**Comment by Nachtalb** [comment]
Or it could be made to copy the whole message. Which is useful when trying to quote someone, instead of painstakeingly selecting the whole message.

**Comment by slook** [comment]
That's a great idea @Nachtalb do you know how to implement this?

**Comment by slook** [comment]
Python 3.5 runtime error:
`TypeError: Argument 1 does not allow None as a value`
see https://github.com/nicotine-plus/nicotine-plus/commit/abad3025a9f51f83efd9f4b121ba17b7a5ab020e#commitcomment-56118918
