### ISSUE TITLE
Alt+M for Send _Message conflicts with native _Mode menu in User Info

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1515]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: All

### Describe the bug
As title.

Essential navigation block occurs with header bar disabled when pressing `Alt+M`

### Expected behavior
The button needs to be labelled "_Private Chat" anyway because that's what the Tab is called, see screenshot...

`Alt+P`

### Additional context
![nicotine-plus Send Message rename to Private Chat (User Info)](https://user-images.githubusercontent.com/88614182/131783557-ca748eb2-a631-43cd-af60-0e5f0dd59bb0.png)

(IT translation requires checking see https://github.com/nicotine-plus/nicotine-plus/pull/1518)

**Comment by mathiascode** [comment]
> The button needs to be labelled "_Private Chat" anyway because that's what the Tab is called, see screenshot...

"Browse Files" is not labelled "User Browse" either. All buttons follow the same pattern.

**Comment by slook** [comment]
Perhaps it is to avoid ambiguity. Perhaps change the accelerator to a different character then.
