### ISSUE TITLE
Add entry to local debug log to identify exact Python version being used at runtime

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1521]
### Describe the solution you'd like
As title, somewhere in init, as close to the start as possible.

N+ version string would also be handy.

### Additional context
I am aware that N+ forces it's own selection and does not use the system default. However, it is difficult for me to determine what it has chosen if multiple versions are present on a particular system.

**Comment by mathiascode** [comment]
> I am aware that N+ forces it's own selection and does not use the system default.

We don't force any particular Python version ourselves.

**Comment by slook** [comment]
Thank you, this is very useful.

For anyone interested, log output looks like this (searching for "Loading Nicotine+" will always find the start of each session):
[2021-09-03 18:49:42] [Misc] Loading Nicotine+ 3.1.2.dev1, using Python 3.5.3 (default, Apr 5 2021, 09:00:41)
