### ISSUE TITLE
Resolve GTK 3.20 validation mismatch "Property 'X align' of object class 'name="xalign"' is deprecated" (all *.ui files)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1522]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: Platform independent.

### Describe the bug
As title.

These errors seem to relate the to size and position properties of widgets, but also opacity, visible, stretch, fill, and suchlike.

If a property of referenced objects was depreciated in 3.20, then later versions of GTK will also be mismatched but the error may not be reported correctly, or at all, in modern IDE's.

It is a loose theory that these pieces of old code may then throw exceptions that are not handled, and instead throw GTK-CRITICAL and GTK-WARNING debug messages relating to gtk_widget_get_mapped: gdk_window_is_visible: gdk_window_show_internal: gtk_widget_set_opacity: gtk_widget_queue_draw: and others, depending on the runtime environment may encounter page faults or panics instead of GTK-WARNING messages.

Users running N+ on systems with over 32GB of RAM have reported errors that lead to kernel panic or BSOD when the application has been running for a couple of days, which may or may not be related to this bug.

Newer platforms are less likely to handle deprecated errors gracefully, and therefore more likely to simply crash if such an exception is encountered. This may at least partially explain why Nicotine+ only ever crashes on newer systems, yet is very stable on older legacy systems where clients are routinely up for months at a time between routine hardware maintenance.

Every .ui file on the master branch is affected by this bug. Other types of files may also be affected that are yet to be tested.

### Expected behavior
Code validation errors should not be present in any file on the tree.

The same stability is required for the application on modern platforms as currently exists on older legacy platforms. 

Therefore, all files will need to be validated using much older versions of GTK authoring packages to validate properties that have now been fully deprecated in the years since the codebase was acquired.

Resolving these errors may reduce the GTK-CRITICAL and GTK-WARNING messages that appear at runtime, which may be leading to crashing and other issues reported on more modern platforms that do not exist on legacy platforms.

### Steps to reproduce the bug

1. Load any .ui file into Glade 3.20 (year 2015)
2. Goto File > Properties
3. Select Toolkit Version Required GTK+ "3.20" (latest)
4. Verify
5. Multiple repeating errors are displayed for each widget (as title).

### Additional context
![nicotine-plus GTK Validation Mismatch](https://user-images.githubusercontent.com/88614182/131935783-bf940f6c-3341-4230-9314-0a3b06b43ef7.png)

```
[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:SecondPaned:__glade_unnamed_40:__glade_unnamed_41] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:SecondPaned:Interests:__glade_unnamed_31] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_30:dirsshared] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_28:__glade_unnamed_29] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_27:filesshared] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_25:__glade_unnamed_26] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_24:speed] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_22:__glade_unnamed_23] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_21:queuesize] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_19:__glade_unnamed_20] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_18:slotsavail] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_16:__glade_unnamed_17] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_15:uploads] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_13:__glade_unnamed_14] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_11] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_6:__glade_unnamed_7] Property 'X align' of object class 'Label' is deprecated
```
_Example shown is ./nicotine-plus/pynicotine/gtkgui/ui/interests.ui_

**Comment by mathiascode** [comment]
> [Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:SecondPaned:__glade_unnamed_40:__glade_unnamed_41] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:SecondPaned:Interests:__glade_unnamed_31] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_30:dirsshared] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_28:__glade_unnamed_29] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_27:filesshared] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_25:__glade_unnamed_26] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_24:speed] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_22:__glade_unnamed_23] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_21:queuesize] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_19:__glade_unnamed_20] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_18:slotsavail] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_16:__glade_unnamed_17] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_15:uploads] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_12:__glade_unnamed_13:__glade_unnamed_14] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_10:__glade_unnamed_11] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_5:MainPaned:InfoVbox:__glade_unnamed_6:__glade_unnamed_7] Property 'X align' of object class 'Label' is deprecated
> ```

These deprecation warnings are incorrect. While the xalign property was deprecated for GtkMisc-based widgets, it wasn't for GtkLabel, and still exists in GTK 3 and GTK 4.

**Comment by mathiascode** [comment]
> Resolving these errors may reduce the GTK-CRITICAL and GTK-WARNING messages that appear at runtime

Getting rid of these errors would be ideal, but they're not related to deprecations. Some of them may only occur in certain GTK versions, possibly due to an old GTK bug, or in certain rare situations due to a code flaw in Nicotine+, and can be somewhat difficult to debug as a result.

**Comment by slook** [comment]
> Since Nicotine+ has been ported to GTK 4, I've also verified that all deprecated features have been removed/replaced when possible

It sounds like you are on top of the situation @mathiascode , which is very reassuring. However, I would encourage that wherever there might be a chance of ambiguity then alternative procedures need to be sought for the 37 *.ui files affected.

This is an interesting yet highly frustrating topic. I wish I could contribute to help you resolve these sorts of complex matters, but unfortunately my skills are woefully lacking in this area, so there is a high chance this is just a red herring.

> While` the xalign property was deprecated for GtkMisc-based widgets, it wasn't for GtkLabel

The issue is not with the GtkLabel widget, rather 'Label' is a reference to an object class. See links:

https://docs.gtk.org/gtk3/class.Alignment.html
"GtkAlignment has been deprecated in 3.14 and should not be used in newly-written code. The desired effect can be achieved by using the GtkWidget:halign, GtkWidget:valign and GtkWidget:margin properties on the child widget."

https://docs.gtk.org/gtk3/property.Alignment.xalign.html
"Deprecated since:	3.14
Use gtk_widget_set_halign() on the child instead."

**Comment by mathiascode** [comment]
> > Since Nicotine+ has been ported to GTK 4, I've also verified that all deprecated features have been removed/replaced when possible
> 
> Well for some reason this one has been missed, I believe it is somehow possible to replace "xalign" with gtk_widget_set_halign() on the child object instead, but exactly how to do this is beyond my understanding.

halign and xalign are not the same. See https://docs.gtk.org/gtk3/property.Label.xalign.html

> but rather the 'Label' definition is just an unhelpful reference to object class name="xalign"

Object class refers to `<object class="GtkLabel">` in the ui file.

If you read the GTK documentation, GtkLabel inherits properties from GtkMisc. The xalign property is deprecated in GtkMisc since GTK 3.14, as seen here: https://docs.gtk.org/gtk3/property.Misc.xalign.html

A separate xalign property was later added to GtkLabel in GTK 3.16. This property is not deprecated, see https://docs.gtk.org/gtk3/property.Label.xalign.html

Hence, the deprecation notice in this older version of Glade is erroneous. If you open the UI files in modern versions of Glade, or run Nicotine+ with `G_ENABLE_DIAGNOSTIC=1 nicotine`, no deprecation notices will be shown.

**Comment by slook** [comment]
I appreciate your insight, however the specifics of the issue are beyond my comprehension and ability.

> the deprecation notice in this older version of Glade is erroneous

While this may be the case, I still think my suggestion is worth a try, just in case you are wrong. The old version Glade I used is compatible with versions thru 3.0 > 3.20 so it should be accurate as to the new implementation of xalign since 3.16 ?

**Comment by mathiascode** [comment]
The problem is that halign doesn't control the text position inside the label widget like xalign does, creating an ugly gap before the text in this case:

halign/no xalign:

https://user-images.githubusercontent.com/8754153/132039745-9287864a-9862-48c5-8b06-daa6db45d15f.mp4

xalign:

https://user-images.githubusercontent.com/8754153/132040110-89934bea-312f-431b-b8e1-8b4fcd716b22.mp4

`The xalign property determines the horizontal alignment of the label text inside the labels size allocation. Compare this to GtkWidget:halign, which determines how the labels size allocation is positioned in the space available for the label.`

**Comment by mathiascode** [comment]
More recent versions of Glade with correct behavior:

![](https://user-images.githubusercontent.com/8754153/132041597-2a8e705f-d474-4744-8516-3a5463add034.png)
![](https://user-images.githubusercontent.com/8754153/132041599-3b0a64c2-8d24-4157-8e5b-c130f9cbed5f.png)
![](https://user-images.githubusercontent.com/8754153/132041603-a71ecec7-d70c-4b4a-b891-241427f83931.png)
![](https://user-images.githubusercontent.com/8754153/132041602-333116dc-aa02-416e-94b0-bc50c614cc95.png)
![](https://user-images.githubusercontent.com/8754153/132041605-73d006a4-d88a-4731-bf8e-2dbb6d92a805.png)

**Comment by slook** [comment]
GTK 3.20:
![GTK 3 20-shares](https://user-images.githubusercontent.com/88614182/132042186-468d3ceb-fddb-4dec-9378-c37208554744.png)
```
[Main:__glade_unnamed_4:__glade_unnamed_6] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_4:__glade_unnamed_5] Property 'X align' of object class 'Label' is deprecated[Main:__glade_unnamed_1:__glade_unnamed_2] Property 'X align' of object class 'Label' is deprecated
```

**Comment by mathiascode** [comment]
Please look at the recordings/screenshots/documentation I sent. Glade is far from perfect software, and has messed up plenty of times in the past: https://blogs.gnome.org/christopherdavis/2020/11/19/glade-not-recommended/

Glade's current maintainer has essentially abandoned it in favor of writing a new solution from scratch: https://gitlab.gnome.org/jpu/cambalache

Can we please stop? There's nothing wrong with the xalign property of the GtkLabel widget, it's just Glade being stupid.

**Comment by slook** [comment]
> Glade is far from perfect software, and has messed up plenty of times... it's just Glade being stupid

I see, I didn't know that I am unfamiliar with GTK

> Can we please stop?

Or course.

**Comment by mathiascode** [comment]
Thank you. I will investigate GTK-CRITICAL and GTK-WARNING errors in due time.

**Comment by slook** [comment]
For future reference, for when the time comes...

Here's a log file from a short idle test which was successful, as usual, no crashes on this distro very stable. Preferences opened a few times and flicked between tabs but didn't download/upload any files nor chat, just an idle test.

Don't know if it's useful or not, probably not. The GTK errors seemed to appear both upon interaction (but not always) and also seem to pop up by themselves at idle (but only sometimes). Recorded it here for ease of reference, even though it is not specifically relevant to the bug in this issue.

_Testing environement: MX Linux 19.4 (Debian 10 Buster) Virtual Machine:_
Single thread. 2048MB RAM. 800x600 generic display (Oracle VirtualBox).
```
setup@VBoxMX:~/Git/nicotine-plus$ git pull
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 96 (delta 82), reused 73 (delta 59), pack-reused 0
Unpacking objects: 100% (96/96), done.
From https://github.com/nicotine-plus/nicotine-plus
   8e318af2..5ece70f9  master     -> origin/master
Updating 8e318af2..5ece70f9
Fast-forward
 pynicotine/gtkgui/chatrooms.py            |   3 +
 pynicotine/gtkgui/frame.py                |  52 +++++--
 pynicotine/gtkgui/search.py               |  44 +++---
 pynicotine/gtkgui/settingswindow.py       |   2 +
 pynicotine/gtkgui/ui/dialogs/wishlist.ui  | 111 -------------
 pynicotine/gtkgui/ui/downloads.ui         |  15 +-
 pynicotine/gtkgui/ui/mainwindow.ui        | 302 ++++++++++++++++++------------------
 pynicotine/gtkgui/ui/popovers/wishlist.ui | 133 ++++++++++++++++
 pynicotine/gtkgui/ui/search.ui            |  15 +-
 pynicotine/gtkgui/ui/settings/ban.ui      |  34 ++--
 pynicotine/gtkgui/ui/settings/geoblock.ui |  34 ++--
 pynicotine/gtkgui/ui/settings/log.ui      |   1 -
 pynicotine/gtkgui/ui/uploads.ui           |   9 +-
 pynicotine/gtkgui/wishlist.py             |  51 +++---
 14 files changed, 445 insertions(+), 361 deletions(-)
 delete mode 100644 pynicotine/gtkgui/ui/dialogs/wishlist.ui
 create mode 100644 pynicotine/gtkgui/ui/popovers/wishlist.ui
setup@VBoxMX:~/Git/nicotine-plus$ ./nicotine
[2021-09-01 05:34:30] Connecting to server.slsknet.org:2242

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 05:34:30.926: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[2021-09-01 05:34:30] Listening on port 2234
[2021-09-01 05:34:31] Connected to server server.slsknet.org:2242, logging in...
[2021-09-01 05:34:31] Rescanning normal shares...
[2021-09-01 05:34:31] 1685 privileged users
[2021-09-01 05:34:31] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
[2021-09-01 05:34:32] 0 folders found before rescan, rebuilding...
[2021-09-01 05:34:32] 0 folders found after rescan
[2021-09-01 05:34:32] Finished rescanning public shares
[2021-09-01 10:06:35] Rescanning normal shares...
[2021-09-01 10:06:36] 0 folders found before rescan, rebuilding...
[2021-09-01 10:06:36] 0 folders found after rescan
[2021-09-01 10:06:36] Finished rescanning public shares
[2021-09-01 10:07:10] Rescanning normal shares...
[2021-09-01 10:07:11] 0 folders found before rescan, rebuilding...
[2021-09-01 10:07:11] 0 folders found after rescan
[2021-09-01 10:07:11] Finished rescanning public shares
[2021-09-01 10:08:30] Rescanning normal shares...
[2021-09-01 10:08:30] 0 folders found before rescan, rebuilding...
[2021-09-01 10:08:30] 0 folders found after rescan
[2021-09-01 10:08:30] Finished rescanning public shares

(org.nicotine_plus.Nicotine:24923): Gtk-WARNING **: 10:17:49.655: gtk_window_set_titlebar() called on a realized window

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:16.706: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:18:16.706: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:18:16.706: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:16.706: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:16.707: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:18.710: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:18:18.711: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:18.711: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:18.711: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:39.660: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:18:39.660: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:18:39.661: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:39.661: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:39.661: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:41.665: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:18:41.666: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:41.666: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:18:41.666: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:19:10.884: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:19:10.884: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 10:19:10.885: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:19:10.885: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 10:19:10.885: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
[2021-09-02 03:40:10] Disconnected from server server.slsknet.org:2242
[2021-09-02 03:40:10] The server seems to be down or not responding, retrying in 15 seconds
[2021-09-02 03:40:25] Connecting to server.slsknet.org:2242
[2021-09-02 03:40:26] Connected to server server.slsknet.org:2242, logging in...
[2021-09-02 03:40:26] 1685 privileged users
[2021-09-02 03:40:26] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:22.855: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 22:18:22.856: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 22:18:22.856: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:22.856: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:22.857: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:24.860: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 22:18:24.861: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:24.861: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:24.861: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:26.065: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 22:18:26.066: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 22:18:26.066: gdk_window_show_internal: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:26.067: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:26.067: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:28.070: gtk_widget_get_mapped: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gdk-CRITICAL **: 22:18:28.070: gdk_window_is_visible: assertion 'GDK_IS_WINDOW (window)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:28.070: gtk_widget_set_opacity: assertion 'GTK_IS_WIDGET (widget)' failed

(org.nicotine_plus.Nicotine:24923): Gtk-CRITICAL **: 22:18:28.070: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
[2021-09-03 01:47:07] Disconnected from server 10.0.2.15:50838
setup@VBoxMX:~/Git/nicotine-plus$ 
```
Exit was normal (pressed Ctrl + Q).
No crashes or issues. UI looks normal.
Resource usage was stable at about 2-5% CPU throughout
Total running time = 20 Hours approx.

**Comment by mathiascode** [comment]
GTK warnings should be fixed in https://github.com/nicotine-plus/nicotine-plus/commit/0543b5e768897ed4bdf0920e1d8624657c1f19e3
