### ISSUE TITLE
Show Similar Users button disappears off window edge due to widget alignment issues (Interests tab)

### ISSUE THREAD

**Issue by slook** [nicotine-plus/nicotine-plus#1523]
Nicotine+ version: 3.1.2.dev1  •  GTK 3.22.11
Operating System/Distribution: MX18, MX19, others

### Describe the bug
As title.

UI bug always present when the viewport is narrow such as when side-by-side (see screenshot below)

### Expected behavior

The Show Similar Users button should be aligned to the left, so that it is always visible.

Also note all three panels on the Interests user interface have strange alignment problems that make it unusable unless maximized. The left-hand 'My Interests' panel does not need to be resizable.

It would perhaps be more appropriate to place the button in the left-hand 'My Interests' panel

### Steps to reproduce the bug

1. Goto Interests tab
2. Unmaximize the main window set to narrow width
3. Adjust the width of the panels
- Many alignment problems are evident

### Additional context
This UI bug is an accessibility problem.

_The mouse cursor indicates where the missing button should be:_
![nicotine-plus Interests tab layout problems on small screens Show Similar Users button disappears off edge](https://user-images.githubusercontent.com/88614182/131990075-5edd1672-ad8c-43f1-a26b-6a9982a2b443.png)
Implementing a fix for this widget alignment issue would probably need issue #1522 to be addressed at the same time (Edit: Done, unrelated to this issue).

**Comment by slook** [comment]
_This is what my proposed improvements looklike at half width on my 1366px wide screen (=683px):_
![nicotine-plus Interests tab proposed layout improvements](https://user-images.githubusercontent.com/88614182/132039261-4888f43f-8068-4369-8ba1-6ab289b74517.png)

As you can see from the above screenshot the 'Show users with similar interests' button is much less likely to disappear now.

**Comment by mathiascode** [comment]
How about something like this? I tried to create something more permanent without the hacky panes. The layout reflows when the window becomes smaller.

![](https://user-images.githubusercontent.com/8754153/132054041-1c319211-7a50-4dd1-8ef9-f064b6848522.png)
![](https://user-images.githubusercontent.com/8754153/132054137-36dc1f85-848b-4fc9-8da1-15f1d1252413.png)

**Comment by slook** [comment]
Yes! Your responsive layout is ace... the three horizontal tile idea was never going to work.

But what has happened to the Unrecommendations pane?

**Comment by mathiascode** [comment]
> But what has happened to the Unrecommendations pane?

Items with a negative rating are located at the bottom of the recommendations list. In my opinion, it doesn't make sense to use vertical space for a separate list that most people wouldn't care about.

**Comment by slook** [comment]
Cool, your right they have + and - score ratings anyway so this is totally obvious (anyway "Unrecommendations" is even a proper word!)

I'm glad you binned off all the refresh buttons that seemed pointless, it's so fast to load anyway.

- I have one further suggestion for your layout:

The only question I seem to get asked a lot is something like...
      ......._"sorry to sound like a total monkey, but how the hell do I setup my profile on here?"_

Then I respond "it's in Preferences > User Info", then they say...
      ......._"thanks, I would have never have thought to look in there, thought the User Info tab didn't work"._

Perhaps (until the User Info tab can be made capable of modifying the local user profile) there can be a nice big fat button, clearly labelled "Personal Info..." just below 'Personal Disinterests', to provide another shortcut to the User Info settings?

**Comment by mathiascode** [comment]
> One of the main common question I seem to get asked a lot is something like...
> ......._"sorry to sound like a total monkey, but how the hell do I setup my profile on here?"_
> 
> Then I respond "it's in Preferences > User Info", then they say...
> ......._"thanks, would have never have thought to look in there, thought the User Info tab didn't work"._

We should probably add a label to the settings button in the user info tab.

**Comment by slook** [comment]
It looks excellent!

Unfortunately, at the smallest width, the refresh buttons are just off by a smidge :(
Like a spacer label widget or something needed there? Or left-aligned.

> the refresh buttons that seemed pointless, it's so fast to load anyway. (pretty much instant).

Ideally, all the refreshes just happen upon tab load, then every time something is liked/disliked?

**Comment by mathiascode** [comment]
> Ideally, all the refreshes just happen upon tab load, then every time something is liked/disliked?

The server seems to have some kind of rate limit on refreshes, and I don't want to cause excessive traffic/server load. It's safer to leave it empty like Soulseek NS.

**Comment by slook** [comment]
Interesting, I see. I suppose if it were populated upon tab load, then user's would wonder why it doesn't update when they like/dislike.

**Comment by mathiascode** [comment]
> Moreover, the position of the Recommendations Refresh, is way too close to the Similar User Refresh, see...
> ![nicotine-plus Interests tab Refresh button position](https://user-images.githubusercontent.com/88614182/132071204-d9ffd905-243b-410b-a526-5d1400777c9e.png)
> ^ This is too easily confused imo, that was one of the main problems with the original layout.

Dark themes and their poor contrast, the separator is almost invisible... I'll see what I can do.

**Comment by mathiascode** [comment]
Better now?

**Comment by slook** [comment]
Yes! Ideal.

A problem arises when Buddy List Always Visible.
![nicotine-plus Interests tab Refresh button position](https://user-images.githubusercontent.com/88614182/132072190-69d70bc6-4ed0-4611-950b-78d19b4d3719.png)

The pane serves no useful purpose in this tab, and there is already list of Similar Users so is confusing.

**Comment by mathiascode** [comment]
Well, it's called "Buddylist Always Visible" after all. If someone enabled the feature, they should hopefully understand the meaning of those words.

**Comment by slook** [comment]
I agree, this is not major.

Whilst on the subject, is it intentional that the Buddy List is docked into the Chat Rooms tab, as opposed to the Private Cat tab?

**Comment by mathiascode** [comment]
I don't know, I didn't implement those options. I assume it might have been useful at a time when the room user list still supported drag and drop, but that's no longer the case.

**Comment by slook** [comment]
Yeh, I gathered and that when the reorganisng, it seems the Private Chat tab seems to be lacking a way of starting new chats with other users.

**Comment by mathiascode** [comment]
> Yeh, I gathered and that when the reorganisng, it seems the Private Chat tab seems to be lacking a way of starting new chats with other users

There's the text entry/dropdown though?

> Perhaps even, it would be a good default setting.

I don't think so personally, the buddy list is used for more than just chatting.

In any case, it could probably be added as an option.

(found the original chatroom buddy list commit: https://github.com/nicotine-plus/nicotine-plus/commit/50589065d10b03cc69411489d5b86fc22848dcb0)

**Comment by slook** [comment]
> In any case, it could probably be added as an option.

I agree that "Buddy List in Private Chat Tab" would be an essential option to have.

Note while you are in there the menuitem label for "Buddylist in Chatroom" is incorrect it should be "Buddy List in Chat Rooms" (Combinedwords are programmer and server admin slang!).

**Comment by mathiascode** [comment]
> True, but the Private Chat tab is empty on first-run, and those blank empty tabs makes the client UI look unfiinished imo, from an asthetic angle to look consistant with the Chat Room tab. Also, accessibility wise,

I've been thinking about some quick start pages with short descriptions and/or items when no secondary tabs are open.

> Note while you are in there the menuitem label for "Buddylist in Chatrooms" is incorrect it should be "Buddy List in Chat Rooms" (Combinedwords are programmer and server admin slang!).

Thanks. Still the occasional string left from the early days sometimes. ;)

**Comment by mathiascode** [comment]
For the private chat tab, https://github.com/nicotine-plus/nicotine-plus/issues/1509 would also be implemented at some point.

**Comment by slook** [comment]
Yes some guideance is much needed in a couple of areas, where the interface does not look so obvious to use.

The more we make progress and improve things, the more ideas come up. We have to draw a line somewhere I think!

I have a list of about 10 or so enhancements, but I am conscious that this might not be a priority.

Certainly, after the release of 3.1.2, I think our efforts have been so significant that a round like this will not be needed nor desired by either us or the users, I didn't realize that that my initial feedback was going to lead to this ongoing interaction.

Some seperate space for noting development ideas and prioritizing desired improvements is needed for long-term goals of the project.

**Comment by mathiascode** [comment]
I would slow down with the enhancements a bit unless it's a usability bug or other important bug, it's indeed becoming a bit overwhelming.

Perhaps it's also time to enable the GitHub discussions tab? I've noticed that it's becoming more difficult to keep track of all the comments and edits in different locations in this repo.

**Comment by slook** [comment]
> I would slow down with the enhancements a bit

Certainly I am becoming very conscious that us two are the only ones on here, and that our discussions have been very technically focused but at times due to my own fault this has become convoluted.

After whenever you release 3.1.2 it will not look so good to have many issues in the tracker, because that gives the impression that there are many problems with the client, which isn't the case.

I think there needs to be a clear distinction, so that people who browse your repo can understand clearly that client is no longer under development and is infact a finished product.

This is especially true also with future testing that you may ask me to do (which I am more than happy to), where long error logs and other such data will put people of using N+ if these pages become fraught with critical looking problems (of course they wont understand that this is a normal part of debugging and development).

**Comment by slook** [comment]
Ideal. Looks like it could work okay. It seems to be fairly open for anyone to edit.

I wonder if it would be possible to perhaps constrain the permissions somewhat? Whilst still of course allowing for public discussion in certain catagories?
