### ISSUE TITLE
Nicotine crashes upon quitting

### ISSUE THREAD

**Issue by afincato** [nicotine-plus/nicotine-plus#1525]
Nicotine+ version:  3.1.0
Operating System/Distribution: macOS 11.5.2

### Describe the bug

when quitting the program (with `cmd` + `q`) i received an error message (suggesting me to report the bug).

### Expected behavior

the program quits as it should.

### Steps to reproduce the bug

- open Nicotine+ 3.1.0
- do some searches
- quite the program with `cmd` + `q`

### Additional context

```
Type: <class 'ValueError'>
Value: Invalid file descriptor: -1
Traceback:   File "/usr/local/opt/pygobject3/lib/python3.9/site-packages/gi/_ossighelper.py", line 92, in signal_notify
    def signal_notify(source, condition):
  File "/usr/local/Cellar/nicotine-plus/3.1.0/libexec/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2553, in on_quit
    self.save_state()
  File "/usr/local/Cellar/nicotine-plus/3.1.0/libexec/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2559, in save_state
    self.np.quit()
  File "/usr/local/Cellar/nicotine-plus/3.1.0/libexec/lib/python3.9/site-packages/pynicotine/pynicotine.py", line 320, in quit
    self.protothread.abort()
  File "/usr/local/Cellar/nicotine-plus/3.1.0/libexec/lib/python3.9/site-packages/pynicotine/slskproto.py", line 556, in abort
    self.server_disconnect()
  File "/usr/local/Cellar/nicotine-plus/3.1.0/libexec/lib/python3.9/site-packages/pynicotine/slskproto.py", line 546, in server_disconnect
    self.close_connection(self._connsinprogress, i)
  File "/usr/local/Cellar/nicotine-plus/3.1.0/libexec/lib/python3.9/site-packages/pynicotine/slskproto.py", line 717, in close_connection
    self.selector.unregister(connection)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 534, in unregister
    key = super().unregister(fileobj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 250, in unregister
    key = self._fd_to_key.pop(self._fileobj_lookup(fileobj))
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
```

**Comment by slook** [comment]
Thank you for taking the time to report this @afincato 

I am personally not qualified to know what the exact cause of this issue is, or if it would be fixed in the most recent revision of Nicotine 3.1.1 or not, but if there is no particular reason why you still need to use the previous revision, then it might be worth a go. Link:

[Download Installer (Catalina/10.15 and newer)](https://github.com/nicotine-plus/nicotine-plus/releases/latest/download/macos-installer.zip)

Please note I can't see anything that jumps out at me in the changelog that specifically addresses the problem you reported, but I could be wrong about that, I've not tried any MacOS version myself.

> i received an error message (suggesting me to report the bug).

I am unclear if you say this bug is reproducible or not... Please can you clarify if the issue occurred only once, or is it all the time, some of the time?

Should the error be encountered again in the future with the current revision, then other MacOS users would be interested to have it fixed for future versions, so please do post again on here if you require further assistance to resolve the problem.

**Comment by francisuk1989** [comment]
@afincato Also what Mac?
Reason im asking im wondering if the one with a Apple M1/ARM chipset?

**Comment by afincato** [comment]
Thanks both!

I upgraded Nicotine with brew to the latest version. Tried a few downloads and that works. I noticed though that the UI is quite slow (eg the cursor), but things work (this reminded me why I switched back to Soulseek QT, UI responsiveness).

> Reason im asking im wondering if the one with a Apple M1/ARM chipset and suffer the same as this issue also? #1475

I use a MacBook Pro 15 from 2015, and upgraded to Big Sur a few months ago.

> I am unclear if you say this bug is reproducible or not... Please can you clarify if the issue occurred only once, or is it every time you press Cmd+Q, or just some of the time?
now Cmd+Q works as expected, no issue. I wonder what could have been. To give more context, yesterday before opening Nicotine+ I was trying to download a few things with Soulseek QT and it crashed on me twice after an item would be added to the download queue. Not sure if somehow my computer had to clear up some network congestion from Soulseek before being operative again.

I think we can close. Appreciated the fast response!

**Comment by slook** [comment]
You're welcome :-)

It should be not be the case the the UI is unresponsive. This is not normal behaviour so it requires further investigation.

As the first troubleshooting step, please can you deselect `Menu > View > Use Header Bar`

When you have done this and tested it for a while, please respond to let us know if this has made any difference or not.

**Comment by francisuk1989** [comment]
Welcome @afincato is also been reported under issue #1475 as i mentioned above however your Macbook has an Intel x64 CPU so is not the newer M1 CPU, So in that case is possible that is a GTK 3 possible behaver, There is GTK 4 but this is in beta but would be good for feedback for Mac users for any speeds improvements

If you wiling to build and compatible a GTK 4 with brew

```
brew update
brew upgrade
brew cleanup
NICOTINE_GTK_VERSION=4 nicotine
python3 packaging/macos/dependencies_core.py
python3 packaging/macos/dependencies_packaging.py
pyinstaller packaging/macos/nicotine.spec
rm -rf dist/Nicotine+/
codesign --deep --entitlements packaging/macos/entitlements.plist --options runtime --sign - dist/Nicotine+.app
python3 packaging/macos/create_dmg.py
```

**Comment by afincato** [comment]
i tried to build Nicotine+ with GTK4 and it seems to run fine! when doing searches the input text does not lag, changing tab and moving the cursor goes smooth.

i noticed that with `brew` i would need to run the app on the terminal, a python application icon would open the GUI window and the app backend server would run in the terminal... ops.

then for completeness i tried to install the latest dmg of Nicotine+ (instead of installing it with `brew`) (eg running GTK3).

(i closed Nicotine+ GTK4 and copied the Nicotine+ GT3 on the desktop instead of dragging it to the Applications folder)

i did `Menu > View > Use Header Bar` and did some searches: the text input would still lag a bit, but the cursor and tab change would act smoothly.

upon Cmd + Q i got this other error:

```
Type: <class 'ValueError'>
Value: Invalid file descriptor: -1
Traceback:   File "pynicotine/gtkgui/frame.py", line 2550, in on_quit
  File "pynicotine/gtkgui/frame.py", line 2556, in save_state
  File "pynicotine/pynicotine.py", line 320, in quit
  File "pynicotine/slskproto.py", line 551, in abort
  File "pynicotine/slskproto.py", line 541, in server_disconnect
  File "pynicotine/slskproto.py", line 669, in close_connection
  File "selectors.py", line 534, in unregister
  File "selectors.py", line 250, in unregister
  File "selectors.py", line 226, in _fileobj_lookup
  File "selectors.py", line 42, in _fileobj_to_fd
```

i am more than happy to run the hand-compiled GTK4 version of the UI as it seems to work perfectly! (:

if i made some mistake along the way please tell me, but it seems that GTK4 is performing much better.

**Comment by francisuk1989** [comment]
> i tried to build Nicotine+ with GTK4 and it seems to run fine! when doing searches the input text does not lag, changing tab and moving the cursor goes smooth.
> 
> i noticed that with `brew` i would need to run the app on the terminal, a python application icon would open the GUI window and the app backend server would run in the terminal... ops.
> 
> then for completeness i tried to install the latest dmg of Nicotine+ (instead of installing it with `brew`) (eg running GTK3).
> 
> (i closed Nicotine+ GTK4 and copied the Nicotine+ GT3 on the desktop instead of dragging it to the Applications folder)
> 
> i did `Menu > View > Use Header Bar` and did some searches: the text input would still lag a bit, but the cursor and tab change would act smoothly.
> 
> upon Cmd + Q i got this other error:
> 
> ```
> Type: <class 'ValueError'>
> Value: Invalid file descriptor: -1
> Traceback:   File "pynicotine/gtkgui/frame.py", line 2550, in on_quit
>   File "pynicotine/gtkgui/frame.py", line 2556, in save_state
>   File "pynicotine/pynicotine.py", line 320, in quit
>   File "pynicotine/slskproto.py", line 551, in abort
>   File "pynicotine/slskproto.py", line 541, in server_disconnect
>   File "pynicotine/slskproto.py", line 669, in close_connection
>   File "selectors.py", line 534, in unregister
>   File "selectors.py", line 250, in unregister
>   File "selectors.py", line 226, in _fileobj_lookup
>   File "selectors.py", line 42, in _fileobj_to_fd
> ```
> 
> i am more than happy to run the hand-compiled GTK4 version of the UI as it seems to work perfectly! (:
> 
> if i made some mistake along the way please tell me, but it seems that GTK4 is performing much better.

@mathiascode

**Comment by slook** [comment]
@afincato As a result of your bug report, a fix has been implemented which avoids this crash on similar MacOS systems. Thank you for posting the error logs which helped to identify the issue.

You can [run from git](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md)/brew or download and install the [latest Unstable version of Nicotine+ for MacOS](https://github.com/nicotine-plus/nicotine-plus#unstable-catalina1015-or-newer) which also includes further optimizations for GTK4 support that you may be interested in testing out, this is still a work in progress for Nicotine+ 3.2.0 so please feel free to post on here should you encounter any further issues. Thank you for your time and feedback.

**Comment by afincato** [comment]
Thanks for your work!

I just had some time to try the new version out (using the pre-compiled, *unstable* version for macOS) and upon launching Nicotine I got this error:

```
Nicotine+ Version: 3.2.0.dev1
GTK Version: 
Python Version: 3.9.7 (default, Sep  3 2021, 12:45:31) 
[Clang 12.0.0 (clang-1200.0.32.29)]

Type: <class 'KeyError'>
Value: 'protocols'
Traceback:   File "pynicotine/gtkgui/frame.py", line 2517, in on_critical_error_response
  File "pynicotine/gtkgui/frame.py", line 971, in on_report_bug
  File "pynicotine/utils.py", line 153, in open_uri
```

Manually pulling down from git and running the pip installation command, then running `nicotine` from the terminal correctly runs Nicotine+, and the UI is quite responsive!

Could it be something with the DMG packaging going wrong?

**Comment by slook** [comment]
Why is there no GTK version reported? That's strange, but unrelated as the failure occurred in an area with an URL handler.

There has been a commit added https://github.com/nicotine-plus/nicotine-plus/commit/0976348a1919072a3c92abb4f2ac88508a6b74b9 please can you test the Unstable installer again if you can, and verify if this fixes the issue or not?

**Comment by afincato** [comment]
Latest Unstable installer works perfectly. Thanks!
