### ISSUE TITLE
Plugin System Expansion

### ISSUE THREAD

**Issue by Nachtalb** [nicotine-plus/nicotine-plus#1542]
As mentioned by @slook here https://github.com/nicotine-plus/nicotine-plus/pull/1541 it would be great to expand the plugin architecture. This issue shall serve as throwing ideas around and see what comes out of it. 

I do think that expanding the plugin architecture would require a refactor of a bigger part of code in N+, so just keep that in mind. 

Here are some ideas from my side.

- Provider / Adapter / Interface architecture with [zope.interface](https://pypi.org/project/zope.interface/) (and maybe more). An example here would be [Plone CMS](https://plone.org/), an incredible powerful CMS build on top of the [Zope suite](https://zope.org/).
- Exposing a greater portion of N+ as safe to use API for plugins.
- Expanding the current plugin system with more high-level functionality (eg. easily providing menu options or status bar buttons etc) and providing more hooks like eg. triggering a hook before a command is run in order to override the outcome like with [notification events](https://github.com/nicotine-plus/nicotine-plus/blob/13d8786eecb136c4ee1f1172864ed58d1dd11cd9/pynicotine/chatrooms.py#L128-L139). 

Things that need to be addressed either way:
- Being able to run commands other than `/me`. In other words, cutting down [this behemoth](https://github.com/nicotine-plus/nicotine-plus/blob/13d8786eecb136c4ee1f1172864ed58d1dd11cd9/pynicotine/gtkgui/widgets/textentry.py#L215) into a command handler or something alike
- A Plugin should not be able to crash the entire N+ instance as its easily possible now
- During my plugin development I noticed various quirks like built-in python modules not being available like `dataclasses` and `html` even tho the python version reported by the plugin through `sys` is `3.9.4`. 
- At the moment it is not possible to load relative modules without path injection: https://github.com/Nachtalb/more-upload-stats/blob/40e7c523e4b3edd958a158d062edfbd243b1c4a9/__init__.py 
- Expanding command help window with plugin commands and providing auto-complete funtionality

I am still fairly new to the whole N+ base so please enlighten me if I got some stuff wrong etc. :)

**Comment by slook** [comment]
Thank you for raising this subject @Nachtalb you have some valid points here, and I agree that everybody would benefit from a better plugin system in future versions, as custom functionality will be desirable to cover a wide range of use cases.

It would seem your knowledge is clearly sufficient to understand possible ways that this can be implemented cleanly. This could be very helpful for the project and it's long term goals.

This is far beyond by own expertise but @mathiascode will be best placed to help with your initial investigations. Please be aware that it may take some time for you to receive a proper response to your above points.

In the meantime please make sure that your dev box is running the latest unstable from the Git master branch, see link: 
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md

**Comment by Nachtalb** [comment]
I am closing this issue in favour of the discussion happening here: https://github.com/nicotine-plus/nicotine-plus/discussions/1540
