### ISSUE TITLE
(Feature Request) Upload tab when someone uploads from you

### ISSUE THREAD

**Issue by francisuk1989** [nicotine-plus/nicotine-plus#1544]
### Describe the solution you'd like
I would like to see on the Upload tab when someone uploads from you, So for example, if one user is upload from you
(Uploading to (xx) xx been the user or numbers

if more then one is been uploading from you (uploading to 2 user)

Something short and not too long.

**Comment by mathiascode** [comment]
This could probably be placed in the status bar, next to the number of active downloads/uploads.

**Comment by francisuk1989** [comment]
> This could probably be placed in the status bar, next to the number of active downloads/uploads.

Good idea but for now it dosnt show how many users are uploading from me unless i go to my uploads tab.

**Comment by mathiascode** [comment]
> Good idea but for now it dosnt show how many users are uploading from me unless i go to my uploads tab.

Do you want a number of total queued/uploading users, or just ones currently uploading?

**Comment by francisuk1989** [comment]
just how many are currently uploading from me.

**Comment by mathiascode** [comment]
> just how many are currently uploading from me.

This information should already be present in the status bar, next to the download/upload speeds. Am I missing something?

**Comment by francisuk1989** [comment]
> > just how many are currently uploading from me.
> 
> This information should already be present in the status bar, next to the download/upload speeds. Am I missing something?

I was asking for the Uploads Tab bar. :) i know is in present in the status bar but when look on a 27" screen all the way at top. 👍

**Comment by francisuk1989** [comment]
It wont matter now because https://github.com/nicotine-plus/nicotine-plus/commit/0821179eee303a74b2b1c5e21eb83e04c12e80c5 has been done

**Comment by mathiascode** [comment]
> there was no status bar at top for Mac users

I'm talking about this status bar at the _bottom_ of the window:

![](https://user-images.githubusercontent.com/8754153/132396208-cc7551db-ffa0-45d8-8f21-be4acfdc46d1.png)

**Comment by francisuk1989** [comment]
> > there was no status bar at top for Mac users
> 
> I'm talking about this status bar at the _bottom_ of the window:
> 
> ![](https://user-images.githubusercontent.com/8754153/132396208-cc7551db-ffa0-45d8-8f21-be4acfdc46d1.png)

oh, haha.
I thought you mean at the top, Yeah thats good enough for me then.
