### ISSUE TITLE
Arch Linux GTK 4.4.0 crashes upon quitting if double login

### ISSUE THREAD

**Issue by francisuk1989** [nicotine-plus/nicotine-plus#1552]
Nicotine+ version:  3.2.0.dev1  GTK 4.4.0
Operating System/Distribution: Arch Linux

### Describe the bug
I was logged in on my other machine but i was trying to sign in on my arch linux but I get this error and then quits without no error messages on display (just terminal messages)

### Expected behavior
I expected to get an error message on display telling me im signed into somewhere eles

### Steps to reproduce the bug
clone nicotine-plus && cd nicotine-plus

### Additional context

```
[2021-09-07 01:45:47] Enabled plugin Leech Detector

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.

python3: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by mathiascode** [comment]
Is this reproducible each time? I didn't experience this issue when signing in in another Soulseek client, the message dialog appeared as usual.

**Comment by mathiascode** [comment]
Do you still experience this issue?

**Comment by mathiascode** [comment]
Closing for now, feel free to reopen the issue.
