### ISSUE TITLE
Crashes when sending emoji 

### ISSUE THREAD

**Issue by Quorthon13** [nicotine-plus/nicotine-plus#1556]
Nicotine+ version:  
Windows/3.1.1

### Describe the bug
I try to insert an emoji through the Win + "."  hotkey and this pops up on my upper left corner of the screen: 
![popup](https://user-images.githubusercontent.com/44161862/132529586-e97de1b2-864e-4527-b103-cd1dc87df995.png)

After clicking anywhere these weird question marks appear on the chat box:
![question-marks](https://user-images.githubusercontent.com/44161862/132529658-280d9184-9b37-44b7-9e82-14e96cf0c772.png)

If I try to send this to chat I get this UnicodeDecodeError and the client crashes:
![critical-error](https://user-images.githubusercontent.com/44161862/132529722-657915c4-452f-4406-b69e-5b053af90ea8.png)

### Expected behavior
Send the emoji.

### Steps to reproduce the bug
- Insert an emoji through the Win + "."  hotkey.
- Press any key.
- Try to send the weird text in chat.

**Comment by slook** [comment]
Thank you for your bug report @Quorthon13 

It would be appreciated for ease of reference if you could paste your screenshots to embed them directly into your OP (above, click Edit), if possible. This would greatly help other user's who may be facing the same issue.

**Comment by Quorthon13** [comment]
Done.

**Comment by mathiascode** [comment]
Does the GTK emoji picker (Ctrl + ".") work as usual?

**Comment by Quorthon13** [comment]
Oh, I didn't know that existed.
Yes, it works just fine.

**Comment by zniavre** [comment]
Please add this shortcut in help > keyboard layout ... 
in fact i even did not know it exists before ( and in another applications) 
thank you

**Comment by slook** [comment]
That is a good idea @zniavre if the shortcut was added to the Editing section of the Keyboard Shortcuts window.

It would be ideal if the text entry unicode error was avoided, perhaps there are other situations that could lead to this crash.

**Comment by Quorthon13** [comment]
I wasn't very clear on the issue about this, but the windows emoji picker
shows just fine. The issue I described happens AFTER I select the emoji.

Em qua, 6 de out de 2021 19:52, Mat ***@***.***> escreveu:

**Comment by mathiascode** [comment]
A screen recording would be appreciated. I didn't experience this issue even after selecting a few emojis (is a specific emoji causing this?)

**Comment by Quorthon13** [comment]
> @Quorthon13 , please provide your system's locale / language / country settings., along with a screen recording if possible.

**Keyboard layout:** US - international
**Region:** Brazil
**System language:**  Portuguese (Brazil)

**Comment by Quorthon13** [comment]
> 
> 
> Please could you try to paste the strange question marks that appear in the chat box into a comment on here? Or perhaps post an emoji directly

Weirdly, I can't paste the question marks anywhere outside Nicotine+. I've tried it in this reply, in VSCode and in Paint(why not). They don't show in the clipboard history either.
Pasting them inside Nicotine+ does work though.



> Also, could you identify if the problem occurs with other text entry boxes in the application, such as the search, user info or a result filter, etc.

Yes, it happens on any text boxes:
![image](https://user-images.githubusercontent.com/44161862/136471006-e5d6e491-c962-4fae-aaba-162c6ac82bc9.png)
(Clicking Apply/OK also crashes the client.)

One other thing: selecting any emoji OUTSIDE of Nicotine+ and pasting them in the chat works as intended.

**Comment by Quorthon13** [comment]
Can confirm that the issue is related to language settings, more specifically, the keyboard layout.
![image](https://user-images.githubusercontent.com/44161862/136478042-567bb245-c79c-430c-b07f-3d603d2da880.png)
The bug happens with the first two portuguese layouts, but after changing to the default US keyboard it works as intended.

**Comment by mathiascode** [comment]
Closing in favor of #2014

**Comment by mathiascode** [comment]
As far as I can tell, this is fixed in the development build of Nicotine+ / GTK 4.
