### ISSUE TITLE
Moving mouse over the dragging-point of a column/frame doesnt change the mouse pointer

### ISSUE THREAD

**Issue by MarkoIndaco** [nicotine-plus/nicotine-plus#1561]
Nicotine+ version:  3.1.1  (GTK 3.24.21)
Operating System/Distribution: Linux Mint 20.1 (Cinnamon 4.8.6) - kernel 5.4.0-81 

### Describe the bug
When I move the mouse over a frame/column border for resize, the mouse pointer icon don't change, making believe that it is not possible to resize (but resize works). 

### Expected behavior
Resize frame/column

### Steps to reproduce the bug
Move the pointer over a column/frame border. The mouse pointer should change to alert the user that it is possible to resize

### Additional context
I try with GParted (as GTK software) and the pointer icon change as aspected

**Comment by mathiascode** [comment]
I tried a fresh installation of Linux Mint 20.1 with Cinnamon, and the cursor changes fine for me. Does the issue happen in every list/treeview? Could you attach a screen recording demonstrating the issue?

**Comment by mathiascode** [comment]
Closing, since I can't reproduce the issue and there has been no response yet. Feel free to re-open the issue.
