### ISSUE TITLE
Uploads with special characters in path cancelled

### ISSUE THREAD

**Issue by heavytrip** [nicotine-plus/nicotine-plus#1564]
Nicotine+ version: 3.2.0.dev1
Operating System/Distribution: OpenBSD 6.9

### Describe the bug
On my uploads tab I regulary see a lot of users with unfinished and 'cancelled' transfers, usually 1-2 tracks from full albums/compilations they download and those 'cancelled' uploads are always with some special character in path (in filename or in folder name), like: ä, ö, á, é, í, õ etc.

### Additional context
![report](https://user-images.githubusercontent.com/80105108/133355717-e6dd62f0-5d29-4ece-a513-067a62c2b1c9.png)

**Comment by mathiascode** [comment]
Thanks for the bug report. Could you email me (see my profile) your username + a few usernames for the failed uploads?

**Comment by mathiascode** [comment]
If you remove the .db files at ~/.local/share/nicotine and rescan, uploads should work fine again.

This was a bug in previous versions of Nicotine+, which unfortunately persists unless you force a rescan of unchanged folders. File paths were not always encoded in utf-8 in user browse responses, causing filename mismatches when utf-8 was used everywhere else.

I'll add some kind of flag or versioning system for the file databases to rebuild them when running Nicotine+ 3.2.0 for the first time.

**Comment by heavytrip** [comment]
I removed all .db files, rescaned my shares and uploads work, at least for me. I tested file transers with problematic characters with official client on Windows 10, everything seems to be ok, so there shouldn't be any problem on my side. But those problematic users still shows up with Cancelled status (when I clear Finished/failed transfers they're back again after a while), possibly they use outdated/buggy client?

**Comment by mathiascode** [comment]
> But those problematic users still shows up with Cancelled status (when I clear Finished/failed transfers they're back again after a while), possibly they use outdated/buggy client?

Since the invalid file paths are still stored in their download lists, the downloads will keep failing until the users re-add the downloads.

**Comment by heavytrip** [comment]
Ok, thanks for clarifying.
