### ISSUE TITLE
Critical Error that I'm getting after updating

### ISSUE THREAD

**Issue by h8uthemost** [nicotine-plus/nicotine-plus#1572]
I just start the application and what I get is printed below. I hit Ok then Nicotine just quits. 
I'm using Debian Testing, last time I use Testing.

Thanks for any help

```
Nicotine+ Version: 3.2.0.dev1
GTK Version: 3.22.11
Python Version: 3.5.3 (default, Apr  5 2021, 09:00:41) 
[GCC 6.3.0 20170516]

Type: <class 'KeyError'>
Value: 'nicotine'
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/pynicotine.py", line 396, in network_event
    self.events[i.__class__](i)
  File "/usr/lib/python3/dist-packages/pynicotine/pynicotine.py", line 1357, in user_left_room
    self.chatrooms.user_left_room(msg)
  File "/usr/lib/python3/dist-packages/pynicotine/chatrooms.py", line 167, in user_left_room
    self.ui_callback.user_left_room(msg)
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/chatrooms.py", line 330, in user_left_room
    self.joinedrooms[msg.room].user_left_room(msg.username)
```

**Comment by slook** [comment]
Thanks for your sending in your crash report @h8uthemost a fix has been implemented to avoid this critical error.

- **Please update to [latest Unstable](https://github.com/nicotine-plus/nicotine-plus#ubuntudebian-unstable) or [git pull](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md) , and then let us know if this resolves the issue on your system.**

Out of interest, which exact branch of Debian Testing are you running that comes with Python 3.5.3 ?! This is the oldest supported Python runtime that Nicotine+ currently supports, it's the same very outdated package as in Debian 9 Stretch LTS (oldoldstable).
