### ISSUE TITLE
UPnP stopped working with current unstable build

### ISSUE THREAD

**Issue by vodzl** [nicotine-plus/nicotine-plus#1580]
Nicotine+ version:  3.2.0.dev1 portable
Operating System/Distribution:
Win10, x64, TL-WR743ND

### Describe the bug
Hello,
UPnP has stopped working after latest changes.
It was working flawlessly since it was fixed a few months ago.
Several day old unstable build has UPnP working.
Probably related to #1566 (it was working for me at that time)
16:45:06 UPnP error: UPnP does not work on this network
16:45:06 Failed to automate the creation of UPnP Port Mapping rule.

**Comment by slook** [comment]
Thanks for this report @vodzl please can you post the output of the [Miscellaneous] Debug Logging category.

_Menu > View > Show Debug Log Controls_

**Comment by vodzl** [comment]
Yes, sure here it is:
`18:15:09 Loading GTK 3.24.30
18:15:09 Loading Nicotine+ 3.2.0.dev1, using Python 3.9.7 (default, Sep 22 2021, 08:13:19)  [GCC 10.3.0 32 bit]
18:15:09 [Misc] Creating Port Mapping rule via UPnP...
18:15:09 [Misc] Loading plugin handler
18:15:09 [Misc] UPnP: Discovering... delay=2 seconds
18:15:09 Connecting to server.slsknet.org:2242
18:15:09 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:15:09 [Misc] UPnP: Sent M-SEARCH IP request 1
18:15:09 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:15:09 [Misc] UPnP: Sent M-SEARCH PPP request 1
18:15:09 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:15:09 [Misc] UPnP: Sent M-SEARCH IGD request 1
18:15:09 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:15:09 [Misc] UPnP: Sent M-SEARCH IP request 2
18:15:09 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
18:15:09 [Misc] UPnP: Sent M-SEARCH IGD request 2
18:15:09 Listening on port 2234
18:15:09 Connected to server server.slsknet.org:2242, logging in...
18:15:10 1681 privileged users
18:15:10 You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
18:15:10 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=100\r\nDATE: Fri, 24 Sep 2021 18:15:09 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:1900/igd.xml\r\nSERVER: ipos/7.0 UPnP/1.0 TL-WR743ND/2.0\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nUSN: uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf37::urn:schemas-upnp-org:service:WANIPConnection:1\r\n\r\n'
18:15:10 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=100\r\nDATE: Fri, 24 Sep 2021 18:15:09 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:1900/igd.xml\r\nSERVER: ipos/7.0 UPnP/1.0 TL-WR743ND/2.0\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n'
18:15:11 [Misc] UPnP: %s device(s) detected
18:15:11 UPnP error: UPnP does not work on this network
18:15:11 [Misc] Traceback (most recent call last):
  File "pynicotine/upnp.py", line 333, in update_port_mapping
  File "pynicotine/upnp.py", line 364, in _update_port_mapping
RuntimeError: UPnP does not work on this network
18:15:11 Failed to automate the creation of UPnP Port Mapping rule.`

**Comment by slook** [comment]
@mathiascode I don't know if it's relevant, on my network UPnP is expected to not work and there has always been a logged Traceback similar to the OP but with additional information shown about [line 333](https://github.com/nicotine-plus/nicotine-plus/blob/bfeeaac1d9a9d87f2b2d77ba43ebf2dfa1cffd84/pynicotine/upnp.py#L333) and [line 364](https://github.com/nicotine-plus/nicotine-plus/blob/bfeeaac1d9a9d87f2b2d77ba43ebf2dfa1cffd84/pynicotine/upnp.py#L364) (raise):

```
16:21:46 Loading Nicotine+ 3.2.0.dev1, using Python 3.5.3 (default, Apr  5 2021, 09:00:41) [GCC 6.3.0 20170516]
...
16:21:47 [Misc] UPnP: %s device(s) detected
16:21:47 UPnP error: UPnP does not work on this network
16:21:47 [Misc] Traceback (most recent call last):
  File "/home/sli/Git/dev/nicotine-plus/pynicotine/upnp.py", line 333, in update_port_mapping
    local_ip_address = self._update_port_mapping(listening_port)
  File "/home/sli/Git/dev/nicotine-plus/pynicotine/upnp.py", line 364, in _update_port_mapping
    raise RuntimeError("UPnP does not work on this network")
RuntimeError: UPnP does not work on this network
16:21:47 Failed to automate the creation of UPnP Port Mapping rule.
```

**Comment by mathiascode** [comment]
The latest unstable build contains additional logging. Could you share the output once you've downloaded the build?

**Comment by slook** [comment]
I can confirm N+ now reports the correct number devices on my network: `17:16:49 [Misc] UPnP: 0 device(s) detected` amongst other additional details. 

How about you @vodzl does your debug log now include the data needed to diagnose your issue? Please post another full log output.

**Comment by vodzl** [comment]
I think this is an extra logging you asked for:

> 19:50:10 Loading GTK 3.24.30
19:50:10 Loading Nicotine+ 3.2.0.dev1, using Python 3.9.7 (default, Sep 22 2021, 08:13:19)  [GCC 10.3.0 32 bit]
19:50:10 [Misc] Creating Port Mapping rule via UPnP...
19:50:10 [Misc] UPnP: Discovering... delay=2 seconds
19:50:10 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
19:50:10 [Misc] UPnP: Sent M-SEARCH IP request 1
19:50:10 Connecting to server.slsknet.org:2242
19:50:10 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
19:50:10 [Misc] UPnP: Sent M-SEARCH PPP request 1
19:50:10 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
19:50:10 [Misc] UPnP: Sent M-SEARCH IGD request 1
19:50:10 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
19:50:10 [Misc] UPnP: Sent M-SEARCH IP request 2
19:50:10 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
19:50:10 [Misc] UPnP: Sent M-SEARCH IGD request 2
19:50:10 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=100\r\nDATE: Fri, 24 Sep 2021 19:50:08 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:1900/igd.xml\r\nSERVER: ipos/7.0 UPnP/1.0 TL-WR743ND/2.0\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nUSN: uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf37::urn:schemas-upnp-org:service:WANIPConnection:1\r\n\r\n'
19:50:10 [Misc] UPnP: Device description response from http://192.168.0.1:1900/igd.xml: <?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
	<specVersion>
		<major>1</major>
		<minor>0</minor>
	</specVersion>
<URLBase></URLBase>
	<device>
		<deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>
		<presentationURL>http://192.168.0.1:80/      </presentationURL>
		<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      		<manufacturer>TP-LINK</manufacturer>
                         		<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          		<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      		<modelName>TL-WR743ND</modelName>
                      		<modelNumber>2.0</modelNumber>
                             		<modelURL>http://192.168.0.1:80</modelURL>
        	<serialNumber>none</serialNumber>
		<UDN>uuid:060b7353-fca6-4070-85f4-1fbfb9add62c</UDN>
		<UPC>00000-00001</UPC>
		<serviceList>
			<service>
				<serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:L3Forwarding1</serviceId>
				<controlURL>/l3f</controlURL>
				<eventSubURL>/l3f</eventSubURL>
				<SCPDURL>/l3f.xml</SCPDURL>
			</service>
		</serviceList>
		<deviceList>
		<device>
			<deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>
			<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      			<manufacturer>TP-LINK</manufacturer>
                         			<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          			<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      			<modelName>TL-WR743ND</modelName>
                      			<modelNumber>2.0</modelNumber>
                             			<modelURL>http://192.168.0.1:80</modelURL>
        		<serialNumber>none</serialNumber>
			<UDN>uuid:254e9977-8964-49f3-b8d5-51acb7bd40fc</UDN>
			<UPC>00000-00001</UPC>
			<serviceList>
				<service>
					<serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType>
					<serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>
					<controlURL>/ifc</controlURL>
					<eventSubURL>/ifc</eventSubURL>
					<SCPDURL>/ifc.xml</SCPDURL>
				</service>
			</serviceList>
			<deviceList>
				<device>
					<deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>
					<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      					<manufacturer>TP-LINK</manufacturer>
                         					<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          					<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      					<modelName>TL-WR743ND</modelName>
                      					<modelNumber>2.0</modelNumber>
                             					<modelURL>http://192.168.0.1:80</modelURL>
        				<serialNumber>none</serialNumber>
					<UDN>uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf37</UDN>
					<UPC>00000-00001</UPC>
					<serviceList>
						<service>
						<serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
						<controlURL>/ipc</controlURL>
						<eventSubURL>/ipc</eventSubURL>
						<SCPDURL>/ipc.xml</SCPDURL>
						</service>
					</serviceList>
				</device>
			</deviceList>
		</device>

		<device>
			<deviceType>urn:schemas-wifialliance-org:device:WFADevice:1</deviceType>
			<presentationURL>http://192.168.0.1:80/      </presentationURL>
			<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      			<manufacturer>TP-LINK</manufacturer>
                         			<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          			<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      			<modelName>TL-WR743ND</modelName>
                      			<modelNumber>2.0</modelNumber>
                             			<modelURL>http://192.168.0.1:80</modelURL>
        		<serialNumber>none</serialNumber>
			<UDN>uuid:565aa949-67c1-4c0e-aa8f-f349e6f59311</UDN>
			<UPC>00000-00001</UPC>
			<serviceList>
				<service>
					<serviceType>urn:schemas-wifialliance-org:service:WFAWLANConfig:1</serviceType>
					<serviceId>urn:wifialliance-org:serviceId:WFAWLANConfig1</serviceId>
					<controlURL>http://192.168.0.1:1910/WFAWLANConfig/control</controlURL>
     					<eventSubURL>http://192.168.0.1:1910/WFAWLANConfig/event</eventSubURL>
     					<SCPDURL>http://192.168.0.1:1900/wfc.xml</SCPDURL>
     				</service>
			</serviceList>
		</device>

	</deviceList>
</device>
</root>
19:50:10 [Misc] UPnP: Device details: service_type 'urn:schemas-wifialliance-org:service:WFAWLANConfig:1'; control_url 'http://192.168.0.1:1910/WFAWLANConfig/control'
19:50:10 [Misc] UPnP: Invalid service type for device, ignoring: urn:schemas-wifialliance-org:service:WFAWLANConfig:1'
19:50:10 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=100\r\nDATE: Fri, 24 Sep 2021 19:50:08 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:1900/igd.xml\r\nSERVER: ipos/7.0 UPnP/1.0 TL-WR743ND/2.0\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n'
19:50:10 Listening on port 2234
19:50:10 [Misc] UPnP: Device description response from http://192.168.0.1:1900/igd.xml: <?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
	<specVersion>
		<major>1</major>
		<minor>0</minor>
	</specVersion>
<URLBase></URLBase>
	<device>
		<deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>
		<presentationURL>http://192.168.0.1:80/      </presentationURL>
		<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      		<manufacturer>TP-LINK</manufacturer>
                         		<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          		<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      		<modelName>TL-WR743ND</modelName>
                      		<modelNumber>2.0</modelNumber>
                             		<modelURL>http://192.168.0.1:80</modelURL>
        	<serialNumber>none</serialNumber>
		<UDN>uuid:060b7353-fca6-4070-85f4-1fbfb9add62c</UDN>
		<UPC>00000-00001</UPC>
		<serviceList>
			<service>
				<serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:L3Forwarding1</serviceId>
				<controlURL>/l3f</controlURL>
				<eventSubURL>/l3f</eventSubURL>
				<SCPDURL>/l3f.xml</SCPDURL>
			</service>
		</serviceList>
		<deviceList>
		<device>
			<deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>
			<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      			<manufacturer>TP-LINK</manufacturer>
                         			<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          			<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      			<modelName>TL-WR743ND</modelName>
                      			<modelNumber>2.0</modelNumber>
                             			<modelURL>http://192.168.0.1:80</modelURL>
        		<serialNumber>none</serialNumber>
			<UDN>uuid:254e9977-8964-49f3-b8d5-51acb7bd40fc</UDN>
			<UPC>00000-00001</UPC>
			<serviceList>
				<service>
					<serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType>
					<serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>
					<controlURL>/ifc</controlURL>
					<eventSubURL>/ifc</eventSubURL>
					<SCPDURL>/ifc.xml</SCPDURL>
				</service>
			</serviceList>
			<deviceList>
				<device>
					<deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>
					<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      					<manufacturer>TP-LINK</manufacturer>
                         					<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          					<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      					<modelName>TL-WR743ND</modelName>
                      					<modelNumber>2.0</modelNumber>
                             					<modelURL>http://192.168.0.1:80</modelURL>
        				<serialNumber>none</serialNumber>
					<UDN>uuid:9f0865b3-f5da-4ad5-85b7-7404637fdf37</UDN>
					<UPC>00000-00001</UPC>
					<serviceList>
						<service>
						<serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
						<serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
						<controlURL>/ipc</controlURL>
						<eventSubURL>/ipc</eventSubURL>
						<SCPDURL>/ipc.xml</SCPDURL>
						</service>
					</serviceList>
				</device>
			</deviceList>
		</device>

		<device>
			<deviceType>urn:schemas-wifialliance-org:device:WFADevice:1</deviceType>
			<presentationURL>http://192.168.0.1:80/      </presentationURL>
			<friendlyName>Wireless Router TL-WR743ND</friendlyName>
      			<manufacturer>TP-LINK</manufacturer>
                         			<manufacturerURL>http://www.tp-link.com</manufacturerURL>
          			<modelDescription>Wireless Router TL-WR743ND</modelDescription>
      			<modelName>TL-WR743ND</modelName>
                      			<modelNumber>2.0</modelNumber>
                             			<modelURL>http://192.168.0.1:80</modelURL>
        		<serialNumber>none</serialNumber>
			<UDN>uuid:565aa949-67c1-4c0e-aa8f-f349e6f59311</UDN>
			<UPC>00000-00001</UPC>
			<serviceList>
				<service>
					<serviceType>urn:schemas-wifialliance-org:service:WFAWLANConfig:1</serviceType>
					<serviceId>urn:wifialliance-org:serviceId:WFAWLANConfig1</serviceId>
					<controlURL>http://192.168.0.1:1910/WFAWLANConfig/control</controlURL>
     					<eventSubURL>http://192.168.0.1:1910/WFAWLANConfig/event</eventSubURL>
     					<SCPDURL>http://192.168.0.1:1900/wfc.xml</SCPDURL>
     				</service>
			</serviceList>
		</device>

	</deviceList>
</device>
</root>
19:50:10 [Misc] UPnP: Device details: service_type 'urn:schemas-wifialliance-org:service:WFAWLANConfig:1'; control_url 'http://192.168.0.1:1910/WFAWLANConfig/control'
19:50:10 [Misc] UPnP: Invalid service type for device, ignoring: urn:schemas-wifialliance-org:service:WFAWLANConfig:1'
19:50:10 Connected to server server.slsknet.org:2242, logging in...
19:50:11 1681 privileged users
19:50:11 You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
19:50:11 [Misc] UPnP: 0 device(s) detected
19:50:11 UPnP error: UPnP does not work on this network
19:50:11 [Misc] Traceback (most recent call last):
  File "pynicotine/upnp.py", line 340, in update_port_mapping
  File "pynicotine/upnp.py", line 371, in _update_port_mapping
RuntimeError: UPnP does not work on this network
19:50:11 Failed to automate the creation of UPnP Port Mapping rule.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/d17a4028bfca70244ce4237a1a605f431cfa5b60 should fix this. Can you confirm?

**Comment by vodzl** [comment]
Yes. Thank you! There is no UPnP port forwarding success message but port test tells it is open and last log message is:
20:39:15 [Misc] Managed to map external WAN port 2234 to your local host 192.168.0.100 port 2234.

**Comment by slook** [comment]
@vodzl Thank you for taking the time to report this so promptly, as others will be less likely to suffer the same regression, the update is likely to make the UPnP more robust for everybody.

@mathiascode I suggest assigning the success message into the Standard Log, otherwise there is no evidence that UPnP is enabled unless there is an error. Also prepend message with "UPnP: "...

`UPnP: External WAN port 2234 successfully mapped to your local host 192.168.0.100 port 2234`

**Comment by mathiascode** [comment]
Done in https://github.com/nicotine-plus/nicotine-plus/commit/2d52abc9bd7950e7d66dcc3e7da88c42f09fdb46
