### ISSUE TITLE
Trigger Browse Files once when online for Buddy List

### ISSUE THREAD

**Issue by frametheanimals** [nicotine-plus/nicotine-plus#1583]
### Describe the solution you'd like
From the Buddy List you can currently enable notifications when a user is online. This is nice but if the buddy is not online long it can be difficult to browse their files and queue file downloads. It would be nice to be able to trigger "Browse Files" once when a buddy appears online. So if you don't catch them online you still can browse their files and enqueue a download for later.

**Comment by slook** [comment]
This custom functionality sounds like a job for a plugin developer, but I don't think that hooks currently exist for notification of Buddy Notify that would enable the new Browse Files tab to be created, although I could be mistaken about this. Your suggestion certainly warrants some further investigation.

**Comment by mathiascode** [comment]
Perhaps a user status notification for plugins would be enough? You could parse the online notify preference from the config.

**Comment by slook** [comment]
@frametheanimals Thank you for your suggestion it's a good idea, this feature has now been added as a built-in plugin that comes with the [latest build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus#download-nicotine) 3.2.0.dev1 in the 'Unstable' branch.

`Preferences > Plugins > Automatic User Browse > Add [usernames]`

Please let us know if you have any further queries or suggestions.
