### ISSUE TITLE
Let the leech plugin browse user files, rather than user info

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#1589]
The current leech plugin bases its information on the server provided information, which is often not accurate.
Specifically, if a user has an external info, which is not available at startup, the user info shows no shared files and gets a stern warning.

Usually that same user fires up his external drive and his files come online a few moments later.

As discussed on IRC, please consider getting the information from browsing people's files. The official client uses that method as well AFAIK. At least, I regularly see people automatically browse my files, when I start a download.

Thanks for your consideration.

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/1565
