### ISSUE TITLE
Wishlist 

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1591]
FreeBSD 12.2-RELEASE-p6
Nicotine+ 3.2.0.dev1

critical. missing a button to quickly add a search result to the Wishlist

![Снимок экрана_2021-10-04_16-29-21](https://user-images.githubusercontent.com/15121782/135828431-392ba9c5-d17a-4126-b179-f76c147b1b04.png)

**Comment by 82d** [comment]
this is one of the functions that many people use most often, which for some reason you have pushed into the background. you left the filter menu, the hint button. perhaps you need them. but I almost never had to use them. restore the add button as it was in version 3.1 because every time you do a few clicks to add a line through the corresponding menu absolutely not a convenient solution when it needs to be done regularly.

**Comment by slook** [comment]
We're currently in the process of moving away from the ugly checkbox we had before...

The `Wishlist` button now has this combined functionality, the query is inserted into the text entry box. Confirm with Enter key or press + icon in the popover dialog.

Admittedly, I agree with you @82d the button's label could ideally change to `+ Add Wish` if the query is not already in the Wishlist.

Perhaps also to fully restore the original functionality, adding the item without confirmation would be a good idea?

**Comment by 82d** [comment]
think about it. those who add something new to their list all the time are not only not familiar with the fact that instead of one click you have to do two and through the unusual pop-up menu. although at first glance it may seem logical, but from the practical side I declare that there is little convenience in this, making several clicks instead of one as before, the Enter button is also not at all in a convenient accessible position to exclude involuntary movement of the mouse towards the icon +

**Comment by 82d** [comment]
there is also such a poelanie so that for convenience you can delete a line in the wishes window with the Delite key

**Comment by slook** [comment]
> making several clicks instead of one as before

I agree it is needed to make this button one-click and change to `+ Add Wish` when the query isn't in the Wishlist.

> so that for convenience you can delete a line in the wishes window with the Delite key

Good idea. This will be possible to implement.

**Comment by 82d** [comment]
it would be possible to make an option when pressing the Wishlist key, the result would be added automatically to the list and in the pop-up window immediately a line with this request was selected for further correction or deletion.

**Comment by 82d** [comment]
it would also be nice to make this button labeled Wishlist with a pencil icon highlighted with an alternative color during the result that is already available in the list.

**Comment by slook** [comment]
> a line with this request was selected for further correction or deletion.

This is the current behaviour no?

**Comment by 82d** [comment]
I have a problem with reopening. I want it to be selected immediately when adding before the initial closing of the window. it has only now become noticeable that a cropped result is being added. that is, not the full string that was filtered through the search.

**Comment by slook** [comment]
> the full string that was filtered

To my knowledge, the Result Filters have never had any influence on the phrase that gets added to the Wishlist.

**Comment by 82d** [comment]
cuts the search result in half when trying to add it to the list. it can be written as a bug.

**Comment by 82d** [comment]
example:
`Underground Evolution Walk On Water`
added only:
`Underground Evolutio`

**Comment by 82d** [comment]
that is, only the visible part of the words from the tab is trying to be added
![Снимок экрана_2021-10-04_19-02-50](https://user-images.githubusercontent.com/15121782/135848283-3db20d08-4230-41a5-88ad-f77591118ced.png)
.

**Comment by slook** [comment]
You're right.

@mathiascode Please can you escalate this Enhancement to a Bug, because long Wishlist items are truncated when added from an open Search Files tab.

**Comment by slook** [comment]
_Additionally, it's possible to re-add "(Wish)" tabs, and the label is included in the string which needs to be excluded:_

![nicotine-plus Wishlist truncation](https://user-images.githubusercontent.com/88614182/135861024-5570d8fb-da92-48ce-bc7b-1dba783101ed.png)

**Comment by mathiascode** [comment]
The wrong string is indeed used, thanks for reporting that. I'm not sure about changing the "Wishlist" button functionality on the fly, since I tend to open the wishlist without the intention of adding the current search. I would prefer a separate button where the old checkbox was, but perhaps with a similar look to the "Result Filters" button:
"+ Add Wish"
"– Remove Wish"

**Comment by slook** [comment]
idk about "Remove Wish", bit long. What about "Wished" ... nah that's no good either.

**Comment by 82d** [comment]
if there is a question of the fact that the old flag could look ugly, then this issue can be solved by the coordinating method. you need to format the button that opens the panel with the filter results. you need to rename this button, for example, to "options" and, by clicking in a row with filters, set the old type checkbox next to the free slot checkbox
![Снимок экрана_2021-10-04_21-27-36](https://user-images.githubusercontent.com/15121782/135871137-4a2d0b28-fcc4-4dcd-b42b-de6e6d534926.png)
.
