### ISSUE TITLE
get date in transfert total up/dl statistic 

### ISSUE THREAD

**Issue by zniavre** [nicotine-plus/nicotine-plus#1598]
conversation in Irc nicotine room

<zniavre> good afternoon
<zniavre> i Can't remeMber if i already ask or request in statistic transfert if it's possible to add date of last reseting ?
<zniavre> or numbers of days in total up/dl
<zniavre> eg: now i can see 149go uploaded but i do not know how long does it take
* Han votes up this request.
* Han is at 800Gb, but since when...

voila ...  :o) 

if other users are thinking same way maybe it is cool to get it ?

**Comment by mathiascode** [comment]
It's possible, but we obviously wouldn't know the start date for existing installations, since there's no such data previously available. It would either be 'unknown' until you reset again, or start counting from the day a new build with this functionality is installed, which isn't accurate.
