### ISSUE TITLE
Wishlist quick search

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1599]
I think this will greatly speed up and facilitate the process when I most often need to press this button to check if there is any track in the list. then it is searched immediately when typing the first letters of the name. I won't have to press tab every time, and besides, I don't need to copy the result to add it to the list when it's not there.

_Nicotine+ 3.2.0.dev1
FreeBSD 12.2-RELEASE-p6_

**Comment by 82d** [comment]
> The list box has an interactive search which selects the first item that begins with letters as you type. To activate it:
> 
>     1. open the Wishlist with `Alt+W`,
> 
>     2. then press `Tab` once to start typing your query,
> 
>     3. then use the `Up` and `Down` arrow keys to browse matching results.
> 
> 
> Edit: I will add the Ctrl+F shortcut to be available from the text entry also, this begins the search-as-you-type feature no matter what widget (TextEntry or ListView) has the focus.

Yes, I know about the tab search. this idea is to start the search automatically without additional clicks immediately after opening the list.

**Comment by mathiascode** [comment]
Would text completion for the text entry work in this case?

**Comment by slook** [comment]
> Would text completion for the text entry work in this case?

If https://github.com/nicotine-plus/nicotine-plus/pull/1602 was applied, then yes also implementing text completion would serve the purpose well.

[_"Fixed: Items that already exist were not highlighted if added from the text entry."_](https://github.com/nicotine-plus/nicotine-plus/pull/1602)
