### ISSUE TITLE
Wishlist hot key

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1600]
I think it's very convenient to link the list to hotkeys. ctrl+w it will be convenient.

_Nicotine+ 3.2.0.dev1
FreeBSD 12.2-RELEASE-p6_

**Comment by slook** [comment]
I suppose Alt+Return (File Properties) isn't affected by translations, but of course letters may well be. Thank you for pointing this out.

**Comment by 82d** [comment]
`ctrl+F` now a is displaying the filters line. what if it reassigns to Wishlist?

**Comment by slook** [comment]
> Ctrl+F should always triggers some form of search or filtering, not wishlist.

Agreed, I think the current `Alt+W` and `Alt+S` mnemonic shortcuts make sense the way it currently is. The solution would be to find a way of getting the accelerator programmatically for insertion into a tagged property within Shortcuts.ui at runtime, such as [gtk-label-get-mnemonic-keyval()](https://developer-old.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-get-mnemonic-keyval) but I don't know how to implement this.
