### ISSUE TITLE
auto-search is not active (3.2.0.dev1)

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1605]
_Nicotine+ 3.2.0.dev1
FreeBSD 12.2-RELEASE-p6_

using the developed version of auto, the search never returned the results found. I have launched the stable version to check if this is the case. for some time, 3 results were obtained. after the release of the spogo dev version, auto search shows no signs.

**Comment by slook** [comment]
Are you referring to Wishlist search here? It might be worth pointing out that the server sends the client a search interval, usually 720 seconds, which might be misleading the results of your concurrent testing between versions if you are using the same slsk account.

**Comment by 82d** [comment]
> Sorry I don't properly understand the scenario that leads up to the problem you are having. You are going to need to be more specific, please describe your issue using other words.

I'm the one apologizing. but really. I just saw the first time the auto search results appeared. it just happened. so it's probably OK. it may be a coincidence or my personal incident.
