### ISSUE TITLE
very bright free slot icon (3.2.0.dev1)

### ISSUE THREAD

**Issue by 82d** [Nicotine-Plus/nicotine-plus#1606]
Nicotine+ 3.2.0.dev1

it seems to me that the orange element stands out strongly, which is always there, regardless of the status of this button. I think the icon itself is normal, but it might not have a dunny emblem in the form of an exclamation mark. a clean icon would not stand out as the function itself is practically not very significant
![Снимок экрана_2021-10-10_15-38-46](https://user-images.githubusercontent.com/15121782/136688904-be807e04-7266-4807-baad-9a889d14475a.png)
.

**Comment by alekksander** [comment]
it's related to Your theming.
here is how it looks on kde with light theme:
![8JSP54t](https://user-images.githubusercontent.com/3148302/136690711-d5765058-4f1e-4099-911c-8da269e56360.png)
:

**Comment by 82d** [comment]
> it's related to Your theming. here is how it looks on kde with light theme: ![8JSP54t](https://user-images.githubusercontent.com/3148302/136690711-d5765058-4f1e-4099-911c-8da269e56360.png)

this icon is from Breeze. surely there are packs that borrow such a badge from Breeze. but on all other standard packs such as Adwaita, Gnome, elementary Xfce, this icon has a bright color that may not always fit under the surrounding theme.

**Comment by alekksander** [comment]
graphics :)
