### ISSUE TITLE
keeps telling me my database is corrupt

### ISSUE THREAD

**Issue by bitesh** [Nicotine-Plus/nicotine-plus#1620]
Nicotine+ version:  
Operating System/Distribution: Ubuntu 20.04.3 LTS

### Describe the bug
Upon rescanning shares, he keeps telling me my database is corrupt. I've checked both disks where I have shares and found no problems. But sometimes he gives no such error.

### Expected behavior
That he gives no such error, ever.

### Steps to reproduce the bug
1. Menu
2. Rescan shares.
3. Look at log.

### Additional context
![Screenshot from 2021-10-14 16-38-14](https://user-images.githubusercontent.com/88059149/137350828-cf516737-3b9e-45f5-a3c8-db734b67b1cf.png)

**Comment by slook** [comment]
Please enable Menu > View > Show Debug Log Controls > `Transfers` + `Miscellaneous` logging categories, to see if any additional error messages can provide extra diagnostic details during the scanning operations @bitesh .

**Comment by mathiascode** [comment]
Could you send me your .db files (located in ~/.local/share/nicotine) to my email (see my profile)?
