### ISSUE TITLE
Serious error occurred while rescanning shares

### ISSUE THREAD

**Issue by therion23** [Nicotine-Plus/nicotine-plus#1625]
Nicotine+ version:  3.2.0-202110151310~ubuntu21.04.1
Operating System/Distribution: Debian bookworm
Python: 3.9.7

When scanning a particular folder, i get the below error. I have, of course, tried to delete *.db and upgrade to latest daily build (as you see above; problem began with 3.1.1). The end result is that nothing from that particular folder ever gets saved to the databases, and hence not shared either.

Enabling debug logging for transfers and miscellaneous gave me no further information.

Now, a shot in the dark would be that the scanner thread chokes on a potentially broken file. Is there any way of getting debug logging from that, so i can have a look?

```
2021-10-16 15:07:11 Serious error occurred while rescanning shares. If this problem persists, delete /home/t23/.nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pynicotine/shares.py", line 102, in run
    self.rescan_dirs(
  File "/usr/lib/python3/dist-packages/pynicotine/shares.py", line 187, in rescan_dirs
    newsharedfiles, newsharedfilesstreams = self.get_files_list(newmtimes, oldmtimes, oldfiles, oldstreams, rebuild)
  File "/usr/lib/python3/dist-packages/pynicotine/shares.py", line 338, in get_files_list
    streams[virtualdir] = self.get_dir_stream(files[virtualdir])
  File "/usr/lib/python3/dist-packages/pynicotine/shares.py", line 410, in get_dir_stream
    stream.extend(message.pack_file_info(fileinfo))
  File "/usr/lib/python3/dist-packages/pynicotine/slskmessages.py", line 2370, in pack_file_info
    msg.extend(self.pack_object(fileinfo[3] or 0))
  File "/usr/lib/python3/dist-packages/pynicotine/slskmessages.py", line 272, in pack_object
    return UINT_PACK(obj)
struct.error: argument out of range
```

**Comment by slook** [comment]
Thank you for this bug report @therion23 . 

> a particular folder

Is there anything unusual about the path name, such as extended Unicode characters, or perhaps something unusual with one of the file's properties or permissions attributes?

> Is there any way of getting debug logging from that, so i can have a look?

Agreeably some better error handling at this point in the shares scanner for more verbose logging would be helpful in this situation, but currently it only has this basic traceback handling. Ideally it would entirely avoid this error and leave a log of any files that had to be ignored.

**Comment by mathiascode** [comment]
You can send them to my email (see my profile).

**Comment by therion23** [comment]
Files sent. Let me know if i can help test anything.

**Comment by mathiascode** [comment]
> Thank you so much, both of you, for your help and time!

You're welcome!

Are the same files you previously sent me logged? In that case, I wonder what the issue with the metadata scanner could be...

**Comment by therion23** [comment]
Yes, all five show up in the log. The bitrate is -1 in one case, 0 for the other four, and duration is always a negative 7-8 digit integer.

I will start a full rescan with today's version and see if the new logger gives any hints. If it logs something that did not crash the previous scanner, maybe one of us can spot a pattern in it.

**Comment by therion23** [comment]
Okay, i noticed something. Here's the scan output from the five files i sent you, that crashed the previous scanner:
```
[Misc] Ignoring invalid metadata for file /mnt/Audio/file1.mp3: bitrate: 0, duration: -16329028 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/file2.mp3: bitrate: 0, duration: -19487596 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/file3.mp3: bitrate: -1, duration: -3930204 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/file4.mp3: bitrate: 0, duration: -19986804 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/file5.mp3: bitrate: 0, duration: -24839309 s
```
And here for some files that now get logged, but did not crash the scanner in the previous version:
```
[Misc] Ignoring invalid metadata for file /mnt/Audio/filea.mp3: bitrate: 0, duration: 47988587 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/fileb.mp3: bitrate: 0, duration: 44706402 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/filec.mp3: bitrate: 0, duration: 23437509 s
[Misc] Ignoring invalid metadata for file /mnt/Audio/filed.mp3: bitrate: 0, duration: 10965138 s
```
So it looks to me like a nonsensical positive duration would let the scanner continue, while a nonsensical negative duration would crash the scanner. I have no idea if Python has such a thing as unsigned integer variables, but it makes absolutely no sense that a duration would be a signed value.

Hope that helps any. Let me know if you need any of the second batch of files (the non crashing invalid duration ones).
