### ISSUE TITLE
Nicotine+ x64 3.2.0.dev1 fails to launch with "Failed to execute script nicotine" error

### ISSUE THREAD

**Issue by UnixNight** [nicotine-plus/nicotine-plus#1665]
Nicotine+ version:  3.2.0.dev1 (latest unstable)
Operating System/Distribution: Windows 10

### Describe the bug
When launching Nicotine+ x64, this error window appears
![image](https://user-images.githubusercontent.com/17035391/140329972-e3aa105a-49ac-449d-a018-c0a5bdba8137.png)
This occurs in both the portable and installer version. 

### Expected behavior
Launching Nicotine+ works correctly

### Steps to reproduce the bug
Download the latest build and try running N+

### Additional context
This only occurs on the 64 bit version. 32 bit can launch fine. 
Windows Defender hasn't removed anything related to PyInstaller or Nicotine+ as per https://github.com/nicotine-plus/nicotine-plus/issues/1417

**Comment by slook** [comment]
Related https://github.com/nicotine-plus/nicotine-plus/pull/1639 will hopefully address this issue.

**Comment by mathiascode** [comment]
This is fixed now.

**Comment by UnixNight** [comment]
Can confirm. Just installed the 64 bit unstable and it works fine
