### ISSUE TITLE
Move to Tray on Exit

### ISSUE THREAD

**Issue by CHJ85** [nicotine-plus/nicotine-plus#1694]
Hi there. In the settings menu, there's a way to enable "minimized to tray on startup", but I can't seem to figure out how I can exit to tray. This is not an extremely big deal as I can just minimize it to the taskbar. But it would be nice if I could minimize it to tray instead. Is there such option now? Because I sure can't find it, and I've been looking through all the settings.

**Comment by slook** [comment]
If you enable Preferences > User Interface > When closing Nicotine+: "Show confirmation dialog"

Then Quit > "Run in Background"

**Comment by mathiascode** [comment]
Alternatively, set "Run in Background" directly in Preferences > User Interface > When closing Nicotine+.

**Comment by CHJ85** [comment]
Ah. Thank you so much. I completely glanced over that setting.
I was looking under Tray and I couldn't find anything.

**Comment by mathiascode** [comment]
No problem. Nicotine+ 3.2.0 will have fewer settings categories to make it easier to find things.
