### ISSUE TITLE
warning if no files are shared

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#1698]
Sometimes, for whatever reason, I don't share files at startup. A share may be inaccessible, or the database may have become corrupted. And I don't notice until I download something from someone who has a leech plugin. I'd rather get a warning from nicotine+

Therefore I'd like to request showing a warning at start-up, if no files are shared.

**Comment by slook** [comment]
If this gets implemented as a "popup notification" then it must be off by default, because messages from Leech Detectors is already bad enough for nagging new users with fresh installs.

```
15:05:41 0 folders found after rescan
15:05:41 Finished rescanning shares 
```
It would be useful if these entries were the other way around, or combined into one line, so that it would stick on the Statusbar.

**Comment by hboetes** [comment]
Right, not a system-notification, nor a "pop-up", since both interrupt the work-flow and are annoying.

On the other hand, not sharing files is something important. For example, the N+ icon dot could go red.
![image](https://user-images.githubusercontent.com/2285225/141687999-929c97ae-f7d7-4c9c-bdf0-bff9dc590122.png)

**Comment by slook** [comment]
> the N+ icon dot could go red

The user is likely to wonder why it looks like they are disconnected when they are not.

I agree that Red is a suitable color for an error condition, but this already has the meaning of "Disconnected", so if we start using for displaying application status in addition to network status, then users will complain that it doesn't change colour during other sorts of error conditions that they might feel are equally as important to them, a failed transfer for example.

The tray icon mechanism is already problematic enough as it is, for example it doesn't work on MacOS, it incorrectly displays the red dot unless it was already enabled before startup, and the Quit mechanisms are non-nonsensical in several scenarios. This is something I have been working on recently, so I know that implementing something like this will be overly complex.

I think we should stick to improving the log system and what text is displayed on the Statusbar, these are areas where improvements are less prone to introducing strange application behaviour.

**Comment by hboetes** [comment]
Having a clear message in the status bar sounds like a good plan indeed.

**Comment by slook** [comment]
_Changed the log output of the scanner to this:_
![image](https://user-images.githubusercontent.com/88614182/142294684-d05da7e4-0607-4c50-8fc4-4e1bbc2d827c.png)

Perhaps we will append the number of errors encountered, but I don't think that information is counted at the moment.

**Comment by slook** [comment]
Startup performance is hindered by 'Scan on startup'. When launching from terminal, the initial stage of the scan process begins on the console before the GUI window is rendered. This creates a noticeable delay with the feature enabled vs disabled.

It makes me wonder if there should be an arbitrary few seconds delay to begin the scan process, this would both speed-up application launch and also ensure the "Rescan complete: nn" message is always last in sequence so it has a higher chance of sticking on the Statusbar.

Pending transfers should not be allowed to begin if there is a scan pending or in progress, because the file stats might not be accurate.

**Comment by hboetes** [comment]
Having a slowly pulsing "0 files shared" with a red background in the status bar(at the bottom right) sounds like a warning I'd like to receive. So the background would cycle between the normal bg and dark red in various shades, let's say 6 shades.

Like in this code:

```
while : ; do for i in {5..9} {9..5} ; do notify-send -t 500 -h 'string:bgcolor:#'$i$i'0000' -h 'string:fgcolor:#ffffff' 'battery at 10%';sleep 0.5; done; done
```

**Comment by slook** [comment]
That sounds pretty :) 

Perhaps the progress bar widget could be made to do something similar. In the case of 0 folders perhaps it could stay visible (the widget is under-used imo), and the "Scanning Shares" label be updated with the folder count, or the number of errors.

As a sidenote I have found that Scan at startup is done before login, which means stats don't get sent to the server.

**Comment by mathiascode** [comment]
It would probably make sense to only allow a rescan if all the main shared folders are accessible, to prevent this issue from happening in the first place. The best way to tell the user when this happens still needs to be explored.

**Comment by slook** [comment]
> It would probably make sense to only allow a rescan if all the main shared folders are accessible

I disagree, consider if a user may intentionally leave external drive(s) powered off or may routinely roam away from their home LAN/NAS, in which case it would be undesirable to entirely block rescanning of other locally available storage devices.

> the easiest route would be a message dialog that lists the folders that are inaccessible

The importance of the shared folder status might warrant a permanent status bar widget icon/counter, that could be the parent of a popover containing a listview of folders/filecounts/statuses.

**Comment by mathiascode** [comment]
> > It would probably make sense to only allow a rescan if all the main shared folders are accessible
> 
> I disagree, consider if a user may intentionally leave external drive(s) powered off or may routinely roam away from their home LAN/NAS, in which case it would be undesirable to entirely block rescanning of other locally available storage devices.

It's problematic in cases where the drive being unplugged wasn't intentional, or you forgot about it. The shares database is rewritten before you realize that the drive isn't mounted, requiring a rescan from scratch for all files in that folder.

**Comment by mathiascode** [comment]
> > > It would probably make sense to only allow a rescan if all the main shared folders are accessible
> > 
> > 
> > I disagree, consider if a user may intentionally leave external drive(s) powered off or may routinely roam away from their home LAN/NAS, in which case it would be undesirable to entirely block rescanning of other locally available storage devices.
> 
> It's problematic in cases where the drive being unplugged wasn't intentional, or you forgot about it. The shares database is rewritten before you realize that the drive isn't mounted, requiring a rescan from scratch for all files in that folder.

One option could also be to add a "force rescan" button in the dialog, in case the user still wants to rescan their shares.

**Comment by slook** [comment]
Are you saying to first check to verify the presence of each shared virtual folder path on disk, and then prompt with a dialog detailing the missing folders?

If so, the proposed "Force rescan" button might be ambiguous for a "Retry" or "Refresh" function that simply performs a presence check.

**Comment by hboetes** [comment]
> Of course there is only one database for all the shares.

Now that you mention it, perhaps create a DB per share? So in case a share is not online it doesn't get lost, it's just not available, just like the FS.

**Comment by slook** [comment]
That would be the most ideal solution in the long run, but unfortunately that is far beyond the scope of this issue.

**Comment by mathiascode** [comment]
> Are you saying to first check to verify the presence of each shared virtual folder path on disk, and then prompt with a dialog detailing the status of missing folders? This does sound like a good idea.

Exactly,. This should only require a os.access() call per virtual folder path, so it should be quite fast.

> Now that you mention it, perhaps create a DB per share?

This is something I've had in mind, but it requires a lot of work and rethinking how we do certain things.

**Comment by slook** [comment]
> It would probably make sense to only allow a rescan if all the main shared folders are accessible, to prevent this issue from happening in the first place.

This actually does make sense, but there still might be use cases for continuing with offline shares in certain scenarios. A function for Refresh/Retry is going to be needed as well as Force Rescan, to enable the user to mount their drive on the fly.

> The best way to tell the user when this happens still needs to be explored, but the easiest route would be a message dialog that lists the folders that are inaccessible.

In PR #2210 the missing folders are logged and also could be available for populating the content of a message box. Such a message dialog will be unavoidably obstructive, but it is a necessary step that will help us develop a better non-blocking solution.
