### ISSUE TITLE
Add "Group by folder" option to search results

### ISSUE THREAD

**Issue by bernd-wechner** [Nicotine-Plus/nicotine-plus#17]
I love the ideas of FOSS, and of Python and of Nicotine+ ... but after trying Nictine+ for a while I went back to SoulSeekQT, for one main reason. Namely this feature, which SoulSeekQT has, Nicotine+ lacks and that I find essential for navigating search results sensibly.

Michael Labouebe ( @gfarmerfr) suggested posting it as a bug and to include screenshots. So here it is as an issue to adddress and here is what the SoulSeekQT resutls look like for a sample search (on Led Zeppelin), grouped by folder:

![Image of SoulSeekQT Search results](http://i741.photobucket.com/albums/xx55/bwechner/SoulSeek/SoulSeekQT%20Search%20results.png)

and here is what Nicotine+ looks like:

![Image of Nicotine+ Search results](http://i741.photobucket.com/albums/xx55/bwechner/SoulSeek/Nicotine%20Search%20results.png)

Notice that Nicotine+ can group by user, but not by folder. Which alas for me is a fail :-(. Else I'd probably still be using Nicotine+ and potentially, given it's in Python, keeping the code on hand, and tweaking it if I ever felt the need, but the idea of implementing group by folder when SoulSeekQT already did it, didn't appeal to me I guess as I'd rather spend what little time I have on other projects.

**Comment by gfarmerfr** [comment]
Might be possible to do...
[Old Trac issue for reference](http://www.nicotine-plus.org/ticket/206)

There is even a beginning of code to it.

As soon as I fixed other pressing bugs i will get to it.

**Comment by throwaway217** [comment]
Soulseekqt is such a clusterfuck on linux that probably all linux users will migrate to nicotine+ after this lands.

**Comment by mathiascode** [comment]
Getting there ;)

![:)](https://user-images.githubusercontent.com/8754153/85755355-88c50c00-b716-11ea-88be-85b1bbea6f4d.png)

**Comment by hboetes** [comment]
@mathiascode the group by user option does not yet stick in searches.
Great feature BTW, thanks for implementing it.

**Comment by mathiascode** [comment]
Should be fairly stable now. Feel free to test:

`git clone -b searchgroup https://github.com/mathiascode/nicotine-plus`

**Comment by hboetes** [comment]
Oh yes! So much better!

**Comment by hboetes** [comment]
This looks a bid odd though: https://i.imgur.com/EmWMKTz.png

**Comment by mathiascode** [comment]
What in particular is odd in the screenshot?

**Comment by hboetes** [comment]
Never mind, I misunderstood what I saw. :-}

**Comment by mathiascode** [comment]
Performance of the search list has been improved a lot, both the classic and folder group modes should now be on par with each other.
