### ISSUE TITLE
OSError on Manjaro Linux

### ISSUE THREAD

**Issue by jxgx** [nicotine-plus/nicotine-plus#1703]
Nicotine+ version:  3.1.1 
Operating System/Distribution: Manjaro 5.14.10-1

Type: <class 'OSError'>
Value: [Errno 9] Bad file descriptor
Traceback:   File "/usr/lib/python3.9/site-packages/pynicotine/pynicotine.py", line 378, in network_event
    def network_event(self, msgs):
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2550, in on_quit
    self.save_state()
  File "/usr/lib/python3.9/site-packages/pynicotine/gtkgui/frame.py", line 2556, in save_state
    self.np.quit()
  File "/usr/lib/python3.9/site-packages/pynicotine/pynicotine.py", line 318, in quit
    self.closed_connection(server_conn, server_conn.getsockname())

### Expected behavior

Successfully quit Nicotine. 

### Steps to reproduce the bug

I was running Nicotine as normal, closed the lid and put the laptop to sleep, reopened and the bug report came to the screen when I tried to Ctrl-Q / quit the program. Now, I cannot quit the program without forcing it to quit.

**Comment by slook** [comment]
It would seem somehow that a config file is either corrupted, or the reference to it is. It would be good to find out what caused the original crash to happen, but I don't know if that event would have left any evidence in the (hidden) profile user `~/.nicotine/` folder. A `config.old` config file may be saved, you could try swapping to this to see if that resolves the issue.

Are all your preferences and settings remembered between sessions @jxgx ?

**Comment by mathiascode** [comment]
This doesn't look like a config file corruption. It looks like the previously stored server connection wasn't cleared when entering sleep mode, and caused issues when resuming.

**Comment by slook** [comment]
Detecting sleep mode is difficult, perhaps it would be more robust to check for the zombie connection(s) somehow and clear it/them, but it's tricky to know how to go about detecting this.
