### ISSUE TITLE
Cannot Use App or See App Windows

### ISSUE THREAD

**Issue by aaeefffhjnnoprt** [nicotine-plus/nicotine-plus#1709]
Nicotine+ version:  3.1.1
Operating System/Distribution: 2015 13" MBP running OS Monterey 12.0.1

### Describe the bug

Nicotine+ worked perfectly until about two weeks ago when I can no longer see any windows when I open the app.

### Expected behavior

I expect to open the app and be able to actually use it.

### Steps to reproduce the bug

- My status is ‘Connected’ according to the File menu
- When I click ‘Search Files’ under the Modes menu, nothing happens
- When I click ’Show All Windows’ from the dock, I just see an outline of the Nicotine+ app with nothing inside
- I’ve tried restarting my machine
- I’ve tried switching from two monitors to just my laptop
- The only thing I haven’t done is to uninstall and reinstall the app (let me know if that’s what you recommend)

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by Inso-m-niaC** [comment]
upgrading to gtk+3 3.24.30 rev. 1 might fix it

**Comment by aaeefffhjnnoprt** [comment]
If [this](https://www.linuxfromscratch.org/blfs/view/svn/x/gtk3.html) what you say I need, I don't use Linux.

**Comment by slook** [comment]
@aaeefffhjnnoprt This sounds like issue https://github.com/nicotine-plus/nicotine-plus/issues/1660 which is resolved in [latest Unstable](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos-catalina1015-and-newer) Nicotine 3.2.0.dev1

**Comment by Inso-m-niaC** [comment]
no, monterey on arm chips too

**Comment by slook** [comment]
I see, so does that mean running on brew is possible now then as per https://github.com/nicotine-plus/nicotine-plus/discussions/1675#discussioncomment-1598381 ?

> 2015 13" MBP

I'm guessing this is an Intel based machine @aaeefffhjnnoprt ?

**Comment by aaeefffhjnnoprt** [comment]
I downloaded the 3.2.0.dev1 update and it works perfectly -- thanks!

@slook Yeah, 2.7 GHz Dual-Core Intel Core i5

**Comment by Inso-m-niaC** [comment]
anyway, just to add. both gtk+3 and homebrew were patched to fix this very recently.

**Comment by mathiascode** [comment]
> anyway, just to add. both gtk+3 and homebrew were patched to fix this very recently.

Yes, the unstable Nicotine+ builds use GTK 3.24.30 rev. 1.

**Comment by Inso-m-niaC** [comment]
> I see, so does that mean running on brew might be possible now then as per #1675 (comment) ?
`brew update` should do it now for 3.1.1 users.
