### ISSUE TITLE
3.2.0.rc2 64-bit portable won't launch (Windows)

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1724]
Nicotine+ version: 3.2.0.rc2
Operating System/Distribution: Windows 11 Pro 22000.348

### Describe the bug
Downloaded the [64-bit unstable portable package](https://nightly.link/nicotine-plus/nicotine-plus/workflows/packaging/master/windows-x86_64-package.zip) and on first run, received these errors:
```
Nicotine+.exe - Entry Point Not Found
---------------------------
The procedure entry point FcWeightFromOpenTypeDouble could not be located in the dynamic link library C:\Users\m\Desktop\Nicotine+\libpangoft2-1.0-0.dll. 
```

```
Nicotine+.exe - Entry Point Not Found
---------------------------
The procedure entry point cairo_win32_surface_create_with_format could not be located in the dynamic link library C:\Users\m\Desktop\Nicotine+\libgdk-3-0.dll. 
```

```
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 15, in run
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 24, in <module>
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 246, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 62, in run_gui
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 45, in check_gui_dependencies
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/Gdk.py", line 83, in <module>
  File "D:/a/_temp/msys64/mingw64/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
AssertionError
```
On second run, only the third error appears. Program won't launch, same error each time.

### Additional context
May be worth noting in case it's related, but I backed up and then deleted my Nicotine+ appdata before attempting to run (just to be safe). Not sure why it's mentioning "D:/a/..." as I ran the software from my desktop ("C:/"). If I recall correctly, Nicotine+ bundles Python so it shouldn't be anything to do with my local Python install.

Haven't tried the installer version.

**Comment by mathiascode** [comment]
Same issue in the 32-bit build? I don't have a Windows 11 installation to test right now, but it seemed to work fine for someone else on Windows 11 earlier. Not sure what the problem is, since the required dlls are included.

**Comment by redactedscribe** [comment]
Just tested the 32-bit portable build and it launched with no problems.

Re-tested the 64-bit portable build and it still produces the same `cx_Freeze` error and doesn't launch.

I'll test the 64-bit installer version next, will update this post.

**Comment by mathiascode** [comment]
Did you try re-downloading the portable 64-bit build? I wonder if something went missing the first time, somehow.

**Comment by redactedscribe** [comment]
Yes, it was a re-download.

**Comment by mathiascode** [comment]
I have no idea what the issue could be right now. The 32-bit and 64-bit portable packages contain the same dlls, and both work fine on my Windows 10 installation.

**Comment by redactedscribe** [comment]
Downloaded it a third time to be sure and still the error.

I'm guessing Nicotine+ portable contains everything it needs to run, so it shouldn't be my system Python/Msys2/environment variables. I don't know what else to suggest, other than finding someone else / a way to test the package on another Windows 11 install.

**Comment by mathiascode** [comment]
This case is quite baffling. I upgraded my VM to Windows 11 Pro 22000.348, downloaded the latest unstable 64-bit portable, but everything works fine on my end...

**Comment by redactedscribe** [comment]
Good thing it's just my system I suppose. If I figure out what's happening I'll let you know.

**Comment by redactedscribe** [comment]
I'm not sure how useful that would be. It may tell us that it's limited to my user (if it runs), or it may still not work, meaning something globally misconfigured (assuming the issue isn't in the code). Either way I don't think it would get me much closer to determining the problem. I uninstalled my user-installed Python and Msys2 but it still doesn't run. It's more interesting to me why the 64-bit installer runs without issue, but the portable version does not.

**Comment by mathiascode** [comment]
There isn't much I can do unless I'm able to reproduce the issue somehow, but this is likely what I would do to start with:
- Narrow down the issue, determine if this issue is system-wide or just for the current user
- Download the latest 32-bit and 64-bit portable packages, ensure everything is identical, especially if the 32-bit version works (extract both to the same location, verify the included files, perhaps move the extracted folder to another location to see if anything changes)
- Create my own portable package in MinGW and check if it works (I realize I forgot to update the packaging instructions, but the commands are here: https://github.com/nicotine-plus/nicotine-plus/blob/6884ce3b73cf53ff72c59c297b038a4b95e4bc36/.github/workflows/packaging.yml#L89-L104)
- Probably something else that would come to my mind later.

The traceback doesn't say much unfortunately, only that GDK wasn't fully/correctly loaded for some reason.

**Comment by mathiascode** [comment]
I reverted a change exclusive to the portable packages, not sure if it changes anything: https://github.com/nicotine-plus/nicotine-plus/commit/b38da4815b9839c27613658aca791c4a0f5195ce

**Comment by redactedscribe** [comment]
I just re-downloaded windows-x86_64-package.zip and tried launching. It works! I don't know if it was specifically the commit you referenced (b38da48) that made the difference, or the commit after (325b8da) which was committed 9 minutes before re-downloading. I didn't do anything differently compared to before, same location for the extracted dir etc, so it should be whatever you did on your end.

**Comment by mathiascode** [comment]
Excellent! Can you verify that both the installer and portable package still work after the latest commit?

> I have one off-topic question however: are the current stable version's setting / data files supposed to worked fine with the upcoming 3.2.0?

Yes, that's supposed to work fine.

**Comment by redactedscribe** [comment]
> Can you verify that both the installer and portable package still work after the latest commit?

Looks like you've changed the directory structure. Tested both the 64-bit package and the installer and both worked great.

**Comment by mathiascode** [comment]
Thanks for confirming!
