### ISSUE TITLE
Support paths longer than 260 characters on Windows

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1728]
Nicotine+ version: 3.2.0.rc2
Operating System/Distribution: Windows 11

### Describe the bug
```
Error while scanning metadata for file C:\XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mp3: [Errno 2] No such file or directory: 'C:\\XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.mp3'
```
First path is 280 characters, and the second is 284 (due to escaped backslashes `\\` within the path (only the first is shown. the rest are censored)).

### Expected behavior
Scan paths longer than 260 characters.

### Additional context
I thought I had mentioned this somewhere before but I couldn't find the issue.

**Comment by mathiascode** [comment]
It was briefly mentioned in https://github.com/nicotine-plus/nicotine-plus/issues/1380

In order to have widespread support for long paths in Nicotine+, we have to start using the "\\?\" prefix for paths when necessary. This needs to be thoroughly tested though, since there are probably things that will break if the prefix is present.

You might be able to enable support for long paths on your own system by following these instructions (not tested): https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by redactedscribe** [comment]
Longer paths are already enabled on my system.

I only get errors for a handful of files in my shares, so it's not a big issue, but ideally I'd not have some files in a folder be unavailable to others due to this (I assume: no scan, no share).

**Comment by mathiascode** [comment]
In that case, the only workaround for now is to use shorter folder/file names. Why the long path registry key doesn't work here is a good question...

It's quite ridiculous that these kind of limitations still apply by default in an operating system today, but I guess that's the price you pay for supporting all kinds of legacy software.

**Comment by Efreak** [comment]
That doesn't help in the case of downloading a directory full of files that *already* have massive filenames

Currently I get around this with `subst m: "e:\downloads\soulseek\complete\username\some really long directory name"`, and use the __download *to*__ button but that doesn't help when the filenames are long too. Or when I want to download subdirectories, and those have long names, too.

**Comment by slook** [comment]
@redactedscribe @Efreak Please can you [test the latest master](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) 3.3.0dev1 to verify if the fix correctly resolves this issue for you?

If it works and doesn't lead to any regressions then it might be desirable to backport this fix into the next stable release of Nicotine+ 3.2.3

**Comment by redactedscribe** [comment]
I've long since removed any previously problematic paths from my shares so I haven't experienced any errors related to this since then (I just tested after adding a lengthy test path and 3.2.2 stable doesn't even complain with a scanning error in the logs any more). If I can get a buddy to download one of these test files, I'll report back with any findings for how _3.3.0dev1_ handles it.

**Comment by redactedscribe** [comment]
So I got someone to download the same file when I was using both 3.2.2 and 3.3.0dev1 and I got the same results:

```plaintext
[Upload] Upload started: user <user>, IP address ('<ip>', <port>), file Downloaded\pathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpath\xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz.jpg
[Upload] Upload finished: user <user>, IP address ('<ip>', <port>), file Downloaded\pathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpathpath\xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz.jpg
```

The file transferred fine. I'm not sure if 3.2.2 suffers from a long path issue.

**Comment by mathiascode** [comment]
> The file transferred fine. I'm not sure if 3.2.2 suffers from a long path issue.

It does if you don't enable the long path registry key.
