### ISSUE TITLE
Dowloads Requeueing

### ISSUE THREAD

**Issue by angrynerd** [nicotine-plus/nicotine-plus#1729]
Nicotine+ version:  
Operating System/Distribution:
Win 10 Home 64 bit

### Describe the bug
Downloads re-queue themselves after downloading around 60-70mb.

### Expected behavior
Each file finishes 1by 1.

### Steps to reproduce the bug
Download files over 70mb.

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://user-images.githubusercontent.com/24483958/144280839-79343bc5-4bad-4fc9-bbe4-a47816432c54.png)

**Comment by angrynerd** [comment]
I'm not entirely sure this is a bug, its just not the behavior I expected. I am new to this client so it may just be an operator error.

**Comment by angrynerd** [comment]
Downloads were progressing in regular intervals at about 400kbps and it would cycle back around in the queue and download another 60ishmb until the files were finished. 

This is the first folder I was downloading to test nicotine+ so I am not yet sure if it happens all the time. I will test a different user in a bit to see if that still happens.

I will also enable debug logs for the next test. If it does just happen to be this specific user.

**Comment by angrynerd** [comment]
Hmm I have just attempted to download another large folder, and this time it went perfectly. I guess it must just have been the user, but I didn't think that was even a setting you could do. For reference the username is inht, I don't think that there is any issue posting that here as its a public username.

**Comment by mathiascode** [comment]
Something strange is going on with that user. <60MB files are fine, but any files larger than that consistently abort around the 60MB mark. The user seems to be using Nicotine+ 3.1.1.

I'll see if I can reproduce the issue on a local installation somehow.

**Comment by mathiascode** [comment]
It seems like the user closes the connection after about 2 mins 30 seconds. I've tried to reproduce this behavior by uploading from a Linux machine to a Windows machine and vice versa, both on Nicotine+ 3.1.1 and the latest unstable version, but everything works as it should. There's nothing obvious in the Nicotine+ source code that could cause this either.

I'm going to assume something at the user's end closes connections after a certain time period, perhaps on a wider level outside Nicotine+.
