### ISSUE TITLE
Double-click on Interests items to trigger "Recommendations for Item"

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1730]
### Describe the solution you'd like
I think double-clicking on an item, either an item from the Likes list, or an item in the Recommendations like, should trigger the "Recommendations for Item" feature.

Not sure why "Recommendations for Item" option is missing for disliked items whilst "Search for Item" is present. If someone wouldn't be interested in recommendations for a Dislike, then they probably won't want to search for it either I'm guessing. I say either include both options, or remove both. If included, double-clicking could also check for recommendations for the given Dislike.

It'd also be nice to have the current term that the recommendations list is based off written at the top, after the refresh button next to the "Recommendations" word for example. There's no way to know what the list is in reference to, other than by knowing which term you searched for recommendations last.

### Additional context
Nicotine 3.2.0.rc2

**Comment by slook** [comment]
The Interests feature is massively improved from previous versions, at least it seems like something more meaningful than before, the server seems a bit mysterious as to how it spits out the recommendations but it's kind of intriguing. I wonder if Interest functions can be somehow integrated elsewhere within the application.

I agree about the mouse accessibility is not ideal, this would be the next thing to improve, see https://github.com/nicotine-plus/nicotine-plus/discussions/1526#discussioncomment-1283240:

> Interests tab Recommendations ListView needs a left-click function (in addition to right-click)
> 
> - Single-click to show context-menu (both left and right buttons).
> - Double-click on Recommendation could trigger default action "Recommendations for Item".
> - Drag and Drop would be ideal into Like/Dislike lists.

This is a non-urgent issue probably aim to do the above for 3.2.1
