### ISSUE TITLE
"[PRIVATE FILE/FOLDER]" items in 3.2.0.rc2

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1731]
I'm seeing a lot of files prepended with the string "[PRIVATE FILE]". When browsing a user, there'll also be "[PRIVATE FOLDER]"s.

Were these results/entries always visible in versions earlier than 3.2.0.rc2 but simply were not labelled? Or is this a new feature? And how do I make searches and exclude these private files which will not be able to be downloaded? Using the Excluded text filter won't work since the prefix isn't actually part of the file name/path etc.

Thanks.

**Comment by mathiascode** [comment]
Locked/private files are now displayed by default. They were opt-in in Nicotine+ 3.1.x, but I decided to show them by default like SoulseekQt due to users asking why Nicotine+ shows less search results. You can disable them for search results in the search preferences, if you want.

**Comment by slook** [comment]
Would it be appropriate for these items to be "greyed out" like the queued files?

**Comment by redactedscribe** [comment]
> You can disable them for search results in the search preferences, if you want.

Thanks.

> Would it be appropriate for these items to be "greyed out" like the queued files?

With all things considered, this probably makes sense because both queued items and private items aren't immediately downloadable (which is why queued items are grey if I'm not mistaken). Though something bothers me about them both sharing the same visual style, so it may be better if they'd _have they're own colour_, whilst still being dimmed like the grey entries.

The issue I'm thinking about now is: do private files/folders need to be indicated as such via colour, prefixed text (or icon), or both, and should the status be represented as prefixed text (as is currently), or as a sortable column instead?

Some thoughts and suggestions to consider:

- **Could it be better to indicate locked/private status using a lock icon: 🔒?**

  An emoji would be unreliable due to the font in use potentially not containing emoji glyphs, so an image icon (one of GTK's or from this [icon set](http://www.famfamfam.com/lab/icons/)) would be preferable.

  If sticking to plain text, "[PRIVATE FILE]" and "[PRIVATE FOLDER]" could be abbreviated to just "[PRIVATE]" or "[P]" (do we really need to know an item is a private FILE or FOLDER? Isn't this usually known based on the context?). The tooltip for "Show privately shared files in search results" already educates what the prefix means, so I see no reason to not make these prefixes less wordy, i.e. as shorter strings or icons. I find the current prefix to be visually noisy and wasteful of space.

- If a dimmed colour other than grey was used for private files, would the prefix be needed at all? No if the Browse Shares view would colour all private folders _and files_ the same way, then both Browse Shares and Search Files lists would share the same visual style.

Hopefully that's not been too confusing as I found it a challenge to figure out what I think would be ideal.

Regarding private files: Is it possible to mark one's own files/folders as private in Nicotine+? If not, a "Private" checkbox in the Shares preferences on a per-folder basis would be nice, especially if it considered the "Buddy-only" status of the share, and of course the "Limit buddy-only shares to trusted buddies" option too.

**Comment by mathiascode** [comment]
>     * **Could it be better to indicate locked/private status using a lock icon: lock?**

Yes, this is what SoulseekQt does, and it was also my original intention, but I had issues getting it working properly. I'll revisit this later, likely when rewriting treeview-related code, as the current code wasn't written with this kind of flexibility in mind.

> Regarding private files: Is it possible to mark one's own files/folders as private in Nicotine+? If not, a "Private" checkbox in the Shares preferences on a per-folder basis would be nice, especially if it considered the "Buddy-only" status of the share, and of course the "Limit buddy-only shares to trusted buddies" option too.

This is not currently possible without an overhaul of the way shared files are stored. https://github.com/nicotine-plus/nicotine-plus/issues/1595

**Comment by slook** [comment]
> I see no reason to not make these prefixes less wordy, i.e. as shorter strings or icons. I find the current prefix to be visually noisy and wasteful of space.

I very much agree. We cannot change the string right now because translations are frozen at the moment, we might as well leave it the way it is for now...

> an image icon... would be preferable.

I think we should aim for a sortable lock icon is_private column. Perhaps in future this could also be used for other attributes, such as is_buddy, is_ignored or is_blocked. Perhaps this would assist in the implementation of filtering based on those characteristics.

> a dimmed colour other than grey was used for private files

This would be good incase aforementioned lock icon column is hidden/not visible.

**Comment by rcz01** [comment]
Is it possible to hide all private files/folders in share browses too? There is only option for search results - or I'm just blind :P

**Comment by redactedscribe** [comment]
There doesn't appear to be. Sounds like a reasonable feature request, i.e. the ability to hide private folders from all views, not only search results.
