### ISSUE TITLE
Clicking in a result filter field scrolls the results list to the top

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1732]
Nicotine+ version: Nicotine 3.2.0.rc2
Operating System/Distribution: Windows 11

### Describe the bug
Clicking in a result filter field scroll the results list to the top. May or may not actually be current intended behaviour.

### Expected behavior
List should not move or scroll until the filter is applied.

### Steps to reproduce the bug
Make a search, scroll down the list, click in a result filter field.

### Additional context
If one wishes to include/exclude some text for example, they may be referencing a string present in the current results. With the view scrolling to the top upon clicking a field, it makes it so that you must memorise a string, or strings, as you write them into a field, assuming it has scrolled out of view.

**Comment by slook** [comment]
The bug is even worse, even clicking on a result in the Results TreeView causes the scroll to go to the top, if the focus was elsewhere, as detailed in related bug #1733 it seems the cause is the same.

**Comment by mathiascode** [comment]
Thanks for reporting this. I'm working on a fix.
