### ISSUE TITLE
UI hangs for seconds at a time in the Search Files view

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1734]
Nicotine+ version: 3.2.0.rc2
Operating System/Distribution: Windows 11

### Steps to reproduce the bug
1. Search for "test".
2. Sort a column, e.g. the User column.
3. Click in a filter field, e.g. Included text.

### Additional context
UI remains laggy for any further actions until program restart.
My number of results per search is set to 2000.

**Comment by redactedscribe** [comment]
Appears to be fixed by 2d87d71.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/5fa3da10ea26556576eae6a119cea8a4f7b9b751 improves this further.
