### ISSUE TITLE
Scrolling on a Preferences field changes the field's value

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1735]
This is generally undesirable behaviour for UIs, and considered bad UI design. We should be able to mouse-wheel the Preferences views without concern for accidentally changing field values. Currently, the only way to ensure this is to strictly use the scrollbar.

As for accessibility, this might be a downgrade for some users as I don't know if mouse-wheeling on a field is a common thing.

Nicotine+ 3.2.0.rc2

**Comment by mathiascode** [comment]
This has bothered me for a long time, but GTK doesn't provide an easy way of disabling scrolling on these UI elements. We'll have to come up with a workaround that works in both GTK 3 and GTK 4.
