### ISSUE TITLE
Direct Connection Fails

### ISSUE THREAD

**Issue by angrynerd** [nicotine-plus/nicotine-plus#1748]
Hello, I am looking through the connection logs and it appears that all of the direct connections are failing but the indirect ones succeed. I am unsure of what is cause this as upnp seems to be working correctly and the ports are showing as they are open. Is there something that could be blocking it?

**Comment by mathiascode** [comment]
If you're talking about the "Direct connection of type x to user y failed" messages, it means the user's port is closed. If indirect connections are working (the user can connect to your port instead), everything is set up properly.

**Comment by angrynerd** [comment]
Ah ok I guess I had the directions messed up. I though that it meant there was issues with people not being able to direct connect to me, or in other words and issue on my side, than one on theirs.
