### ISSUE TITLE
Split log file on certain file size threshold?

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1758]
Just curious if the log files, such as transfers.log, get split or overwritten at some point?

My log is 4 MB right now and at 20k lines, it's already a bit unwieldy to view in a text editor.

It'd be convenient if the file would split (preferable to being overwritten) at a sensible cut-off file size.

```
transfers.log
transfers1.log
transfers2.log
...
```

The downside becomes searchability with the lines across multiple files, but with the right tools this isn't much of an issue (e.g. VS Codes's "Find in files" feature).

**Comment by slook** [comment]
The Debian Linux log rotation naming schema is `transfers.log.1` `transfers.log.2` etc. Higher numbers are older, file 2 and up are gzipped.

Or maybe it would be simpler to prefix the file creation date as in `YYYY-MM-DD HH-MM-SS transfers.log`

As the exact size is not important, it only needs checking once each startup, if size > ~4096Kb then rotate/make new file, else open the most recent, unless it's more than a month old, in which case make new.

It's probably better performance when printing to smaller files.

**Comment by mathiascode** [comment]
How would per-session transfer log files sound, similar to debug log files?

Chat logs most likely won't be split, since the plan is to lazily load old messages in the GUI when scrolling to the top.

**Comment by slook** [comment]
> How would per-session transfer log files sound, similar to debug log files?

That would be fine, although a reverse-formatted timestamp would be preferable instead of seconds since the epoch like the debug.log is currently not very user friendly.
