### ISSUE TITLE
"Ban user" and "Block user's IP address"

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1762]
The options to ban or ignore a user are a bit confusing:

- Ban user
- Ignore user
- Block user's IP address
- Ignore user's IP address

Particularly confusing is the use of the terms _Ban_ and _Block_ when they both pertain to banning (at least, they both add to the Banned Users lists in the Preferences).

_Ban user_ sounds like it'd be the only switch you'd need to flip for a ban, but it's in fact only "Ban user's username", which may not be enough (i.e. username + IP for a full ban).

If my understanding is correct, I think it would be less ambiguous and mirror the Preferences better if grouped and worded as the following:

- Ban user by username
- Ban user by IP address
- Ignore user by username
- Ignore user by IP address

Ideally, nested (which is nice if right-clicking a user directly, but if right-clicking a file, it then requires _User > Ban user > By username_, which is getting deep, but possibly still acceptable):

- Ban user
  - By username
  - By IP address
- Ignore user
  - By username
  - By IP address

I haven't had to use these features so I don't know why it's important to have a ban or ignore split into two, by username and by IP, but possibly just the _Ban user_ and _Ignore user_ would be enough? I.e. both username and IP are added at once to the banned lists.

**Comment by slook** [comment]
Your suggestions seem to make more sense than the way it is now. We will look into this for 3.2.1

**Comment by redactedscribe** [comment]
Could someone explain to me what banning by username/ip does vs ignoring via username/ip?

Is banning about denying people to download from you, and ignoring is about chatting? So technically I could ban someone but still chat with them (if I don't ignore them)?

**Comment by mathiascode** [comment]
Exactly. I will add a short description to the `Ignore Users` preference page, similar to `Banned Users`, once the string freeze is lifted.

**Comment by bambury** [comment]
Related issue: is there a way to hide/remove users from _search results_? If not, I would appreciate it.

**Comment by mathiascode** [comment]
Not yet, but it's planned: https://github.com/nicotine-plus/nicotine-plus/issues/1676#issuecomment-962719969
