### ISSUE TITLE
Logs mention "privileged" users not "prioritized" users

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1764]
### Describe the bug
Somewhat minor, but the new terminology isn't reflected in the logs.

**Comment by mathiascode** [comment]
What log message?

**Comment by redactedscribe** [comment]
I meant the ones that appear in the UI, I don't know if they actually get logged.

E.g.: On connecting: `100 privileged users` , and `You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.`

**Comment by slook** [comment]
No that is the actual Soulseek privilege system... Menu > Soulseek Priviliages > Donate (1 month = $35)

https://www.slsknet.org/userlogin.php

Prioritize is a totally different function specific to the N+ buddy system.

**Comment by mathiascode** [comment]
> Prioritize is a totally different function specific to the N+ buddy system.

It is worth noting that prioritized buddies behave the same as users privileged on the Soulseek server (both will be able to download files before regular users), privileged buddies were just renamed to prioritized buddies to differentiate between the two systems.

**Comment by slook** [comment]
Indeed, the terminology was renamed just recently:

- old name... "Privileged" buddies in Nicotine+ 3.1.1 and below

- new name... "Prioritized" buddies in Nicotine+ 3.2.0 and above

The above feature never required a donation, it's simply a toggle setting in the Buddy List ("Buddies" tab).

If you wish to be globally Privileged on the entire Soulseek network for your own downloads, visit:
- https://www.slsknet.org/userlogin.php enter your username and click Donate.
