### ISSUE TITLE
Just crashed on Win 11 insider ring

### ISSUE THREAD

**Issue by ztauras** [nicotine-plus/nicotine-plus#1777]
Type: <class 'ValueError'>
Value: access: embedded null character in path
Traceback:   File "pynicotine/pynicotine.py", line 385, in network_event
  File "pynicotine/pynicotine.py", line 1823, in queue_upload
  File "pynicotine/transfers.py", line 666, in queue_upload
  File "pynicotine/shares.py", line 646, in file_is_shared

**Comment by mathiascode** [comment]
I assume this is on Nicotine+ 3.1.1? Do you share any files with names starting with "0 " (that would end up with a path similar to this: `something\0 - test file.mp3`)?

**Comment by mathiascode** [comment]
I tried downloading a file containing "\0 " in the path with Soulseek NS, SoulseekQt and Nicotine+, and all of them escape the path properly. Either some other Soulseek client out there is misbehaving, or someone is sending invalid file paths with malicious intent. In any case, I've pushed a commit that handles such file paths.
