### ISSUE TITLE
Unknown config option 'show_private_results'

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1779]
Nicotine+ version: 3.2.0
Operating System/Distribution: Win 11 Pro

### Describe the bug

> Unknown config option 'show_private_results' in section 'searches'

shows in the log when starting Nicotine+.

**Comment by mathiascode** [comment]
Have you started an old version of Nicotine+ recently, somehow? That config option only existed in a dev version between June 19 and July 1, 2021.

**Comment by redactedscribe** [comment]
Not intentionally, but it may have happened by mistake. I assume it's therefore fine to remove `show_private_results = False` from my Nicotine+ `config` file. Issue can be closed.

**Comment by mathiascode** [comment]
Yes, this is fine. Thanks.
