### ISSUE TITLE
Sort order time elapsed is off for uploads over an hour

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#1795]
As you can see, the sort order for time elapsed is off for uploads that took over an hour.

![image](https://user-images.githubusercontent.com/2285225/147890888-891340b4-992b-467b-96f0-f325f9b63c22.png)

**Comment by hboetes** [comment]
Of course this is a cosmetic bug.

**Comment by mathiascode** [comment]
We probably have to restore the hidden sort column that stores the value in seconds, especially if we're going to show text in the future. https://github.com/nicotine-plus/nicotine-plus/discussions/1533#discussioncomment-2011019

**Comment by hboetes** [comment]
thanks!
