### ISSUE TITLE
Question: No more charsets selection ?

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#180]
One of a thing nicotine was unique ...

Thank you for every improvement you ve done !!!

**Comment by eLvErDe** [comment]
If I remember correctly the old soulseek server was running ISO8859-1 and they switch to UTF-8 at some point.
So this charset stuff is probably remaining cruft from old times, can be safely dropped IMHO.

**Comment by mathiascode** [comment]
I removed it in https://github.com/Nicotine-Plus/nicotine-plus/pull/171, to simplify the whole encoding/decoding process. UTF-8 should work for everything nowadays.

**Comment by mathiascode** [comment]
Can we close this? Doesn't seem like any issues have popped up since.
