### ISSUE TITLE
my gtk3 theme gives checkbuttons looks bigger 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#181]
i thougth it was my "own" gtk+3.x theme wrong but i can't fix it so i m asking to you if there is something wrong with another users ? 
checkbuttons with menu looks oversized without padding only with nic+ 

screenshot with different view of how it should look vs how it looks with nic+

![Capture d’écran du 2020-05-24 11-39-21](https://user-images.githubusercontent.com/2409578/82751377-f6e47f00-9db6-11ea-8ec7-446da6c8d26b.png)

maybe you can help me with a good tip and how to fix it ?

thank you for your huge work !

**Comment by mathiascode** [comment]
Checkboxes don't even appear in the Yaru theme, so something must be wrong with the code. Investigating.

**Comment by zniavre** [comment]
i tried to understand via UI files but i m too dumb to understand what is wrong sorry ...

maybe it's because yaru and my own are using pixmap to draw checkbuttons ?

**Comment by mathiascode** [comment]
What do checkboxes look like when you right-click in something like gnome-terminal?

**Comment by zniavre** [comment]
as it should be .
![Capture d’écran du 2020-05-24 15-46-52](https://user-images.githubusercontent.com/2409578/82755868-cca2b980-9dd6-11ea-8ec4-af0be53ed6b1.png)
 it's gnome-terminal>  3states

**Comment by mathiascode** [comment]
Could you share your theme, or link to a theme with the same issue?

**Comment by zniavre** [comment]
[brdln.zip](https://github.com/Nicotine-Plus/nicotine-plus/files/4673731/brdln.zip)
