### ISSUE TITLE
when a filename is 255 characters long

### ISSUE THREAD

**Issue by holytrousers** [nicotine-plus/nicotine-plus#1825]
Nicotine+ version:  3.2.0
Operating System/Distribution:
Linux

### Describe the bug
when a filename is 255 chars long, nicotine prepends INCOMPLETE#HASH to the filename in the incomplete folder before it gets renamed back to the original filename, exceeding thus the 255 chars limit set by most filesystems (ext4, ntfs, btrfs ...)

### Expected behavior

- option to disable the temporary file ( ala transmission )

- incomplete filename contains only the hash, with filename-hash matches in a separate list

**Comment by AtticFinder65536** [comment]
I'm on 3.2.2, and it looks like the above commit [should be in this version](https://github.com/nicotine-plus/nicotine-plus/blob/cdab528b0f71391c74221098df6cf58acb7e6321/pynicotine/transfers.py#L1034). I still get an IO error when a filename is 255 chars long (or almost 255 char, what matters is the size of INCOMPLETE#HASH) and Nicotine+ writes INCOMPLETE#HASH$filename in the incomplete folder. Does that commit not work for anyone else??
