### ISSUE TITLE
Excessive memory usage when browsing large shares.

### ISSUE THREAD

**Issue by dddd66** [nicotine-plus/nicotine-plus#1826]
Nicotine+ version:  
Operating System/Distribution: Windows 10

### Describe the bug
Browsing large shares (1TB+) makes the application use a lot of RAM, and even after closing the share or have the application run in the background it doens't go away, it also makes the program very slow. When closing the large share and trying to browse it again the program just seems to behave unexpectedly, almost reaching the end and starting again while increasing it's RAM to crazy values like 1-2gb+.

### Expected behavior
Not have it use so much RAM even after closing the share, or have it use way less. / optimize the way this works.

### Steps to reproduce the bug
Browse a large share, close it, try browsing the same large share again.

### Additional context
Screenshots, logs, stacktraces or relevant information.
Uh, sorry if i'm being not so descriptive as i'm not acquainted with how the internals work as i'm not a programmer.

**Comment by hboetes** [comment]
I just checked by browsing my own  1 TB share, dropping it and reloading it and dropping it again. N+ loaded an additional 40 MB of cache, which make sense. I didn't see it claiming an extra GB of memory.

Using the latest version from git.

**Comment by slook** [comment]
Are you also on Windows @hboetes ?

@dddd66 If possible please could you verify whether or not the same issue occurs on your system with the [latest unstable testing branch of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) 3.2.1.rc1 for Windows, and also the questions in my previous post (above).

**Comment by hboetes** [comment]
> Are you also on Windows @hboetes ?

Nope.

**Comment by dddd66** [comment]
@slook 3.2.0 64 bits
I tested with the latest build and the unexpected behaviour stopped, but the memory keeps rising if you browse it again.

@hboetes the latter happened with a really large share e. g. 12tb ~


![Taskmgr_JIBeg0kvhp](https://user-images.githubusercontent.com/80369241/149501490-794274ac-e49f-40a5-aed7-074bcb2f7a27.png)
![Taskmgr_Cr9ANC0XMu](https://user-images.githubusercontent.com/80369241/149501494-935ffb7c-2509-4c96-b310-31943e7993e8.png)

**Comment by slook** [comment]
Thank you @dddd66 , I have a couple of questions... we need to identify if this is an issue with remote connections, or if this is an issue with local disk access.

- Does this occur at the point of loading the user's share, or after you browse into individual folders?

Please compare the difference of memory usage between:

- A) Browsing the user's share directly whilst online.
- B) Saving the 'Save shares list to disk' (button with floppy disk icon), then 'Open List' from disk whilst disconnected offline.

+ And what is the filesize of the Save List file (located in the 'Users~.\nicotine\usershares\' folder)?

**Comment by mathiascode** [comment]
The main issue is the GtkTreeView widget for the folder list. The memory usage remains reasonable while downloading the share from the user (considering it contains all the folders and files), but increases fast once the folder view starts generating. You can reproduce it by browsing some of the users with a lot of shared files in the nicotine room.

Browsing the user while online and loading their share from disk yields the same result.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/cf0e05ed3b80f38a7beb067fcb4b075318d154da helps release memory immediately when closing the tab (20 TB share, before the commit ~1 GB memory usage after closing the tab, after the commit ~100 MB).

**Comment by hboetes** [comment]
@dddd66 good that somebody tests stuff like that.

**Comment by slook** [comment]
Yes it was a good observation.

> I'm not sure if it's just Python being Python when the memory isn't released immediately

It's perhaps possible that something in the OS influences this behaviour on different systems, memory management and virtual disk swapping aren't known as being strong points of the Windows NT kernel.

@dddd66 Please download and install the latest unstable testing branch of Nicotine+ 3.2.1.rc1 for Windows, and see if this makes the expected improvement on your system?

**Comment by dddd66** [comment]
@slook the latest unstable build seems to fix this problem, after i close the share it gets to the normal memory levels again.

**Comment by mathiascode** [comment]
Thanks, I'll close this issue in that case.
