### ISSUE TITLE
Spaces at the end of directories are trimmed when creating

### ISSUE THREAD

**Issue by Efreak** [nicotine-plus/nicotine-plus#1835]
Nicotine+ version: 3.2.0.0
Operating System/Distribution: Windows 10 x64

### Describe the bug

When downloading a directory `.../Carter, Carlene /...`, The directory `/Carter, Carlene/...` was created, but then saving files in it failed, as it's looking for a directory `/Carter, Carlene /...`. 

### Expected behavior

Don't trim directory names. Users should know better than that, and if they do it, it might be intentional (While I wouldn't share files like this, I use spaces to get shortcuts without names on my desktop)

### Steps to reproduce the bug

Try to download a file in a folder that has a space in it.

### Additional context

`15:20:36 Couldn't move '...Soulseek\Incomplete\INCOMPLETE...' to '...Soulseek\Downloads\...\Carter, Carlene \...': [WinError 3] The system cannot find the path specified: '...Soulseek\\Downloads\\...\\Carter, Carlene \\...'`
Manually renaming the directory to have the space in it allowed it to continue (though it was a pain, since windows doesn't like spaces at the end of filenames, even in command prompt with command extensions enabled. I had to use WSL to do it. Next time I'll just change the download directory in nicotine...)

**Comment by mathiascode** [comment]
I don't think we're trimming any folder names. Downloading a folder containing a trailing space works fine for me in Linux, I'll have to investigate what's going on in Windows.

**Comment by mathiascode** [comment]
https://bugs.python.org/issue22744

**Comment by mathiascode** [comment]
@slook See the link to the Python bug tracker above. Windows silently trims trailing spaces on the OS level when creating a new folder (an unacceptable decision in my opinion), so we'll have to implement a workaround on our end.

**Comment by mathiascode** [comment]
Since we've already removed trailing periods for years, I've added spaces to the list: https://github.com/nicotine-plus/nicotine-plus/commit/2adfe08476d3bc50e363cc33a8e3dfba58be5125

**Comment by slook** [comment]
Problems appear to still exist see https://github.com/nicotine-plus/nicotine-plus/issues/2075
