### ISSUE TITLE
Connect to remote host? 

### ISSUE THREAD

**Issue by BEEFF** [nicotine-plus/nicotine-plus#1839]
Hi, I have Nicotine running on a server on my local network. Is there any way of routing the User Interface to connect to a different host  (not soulseek server) for downloads etc? Or forwarding some port on the local machine?

**Comment by BEEFF** [comment]
Other P2P clients such as transmission have a web interface that you could connect to from any host on the same network

**Comment by slook** [comment]
You can login to your server over SSH and run `nicotine --rescan` and `nicotine --headless`. There is no control over individual transfers so this is only useful as a sort of seed server, the log output is written to the stdout of your remote terminal session.

For your use case a more suitable client would be `slskd` is a modern client-server application for the Soulseek file sharing network: https://github.com/slskd/slskd

**Comment by mathiascode** [comment]
Closing, as this has been answered.
