### ISSUE TITLE
Question - Bug? - Log Window Issue

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#186]
1.4.3 in Linux, I noticed if I disable the Log Window, I still saw at the botton of Nictone+ when I started it that it said;

```You have no privileges left. They are not needed for Nicotine+ to function properly. You can acquire privileges by donating at```

Here's a screen shot of that; 
![nicotine_log](https://user-images.githubusercontent.com/36190223/82764897-5029ce00-9e0a-11ea-9f46-02ec47be555b.jpg)

I thought this info only appeared in the Log Window?

Also when I had the Log Window disabled, I then enabled the Log Window, and just disconnected and reconnected, this info didn't appear in the Log Window, only the URL appeared. This only happened once, so not sure why it was just empty with no message and only the URL to donate with/from...

Here's a screen shot how that apeared one time;

![nicotine_log_2](https://user-images.githubusercontent.com/36190223/82765080-8f0c5380-9e0b-11ea-942a-ee393d4f0dd7.jpg)

**Comment by mathiascode** [comment]
I remember the statusbar message being a thing in 1.4.1 too, but I'll see if I can make the presentation somewhat nicer.

There is an issue with the font color not updating properly in the log view at the moment.

**Comment by 0pLuS0** [comment]
I guess the idea here is to make a distinction between what should be ```Status Bar``` messages and what should be ```Log Messages```

IMHO, this ```no privileges left``` message should be a ```Log Message```

I think of the Status bar like; connected, disconnected, port connected to, etc...

THAHKS

**Comment by zniavre** [comment]
in the same place there is the priviliege days left number when you pay for it
