### ISSUE TITLE
Way to handle lots of small files on your upload queue

### ISSUE THREAD

**Issue by digitalnexus** [nicotine-plus/nicotine-plus#1865]
Firstly good job on Nicotine+, keep it up :)

Right now, it feels slow for people who have queued a large number of small files to download from you. In a round-robin configuration, they're grabbing a single file every few seconds, while if I manually right-click and Retry 30 files of, say, 100k each from their download queue, it all gets sent in five seconds, while it would otherwise take them closer to a minute, in my particular case. Your mileage may vary but the issue stays the same with small files.

A solution could be to bundle up a configurable amount of small files and send them in a single 'transaction', temporarily opening up additional simultaneous connections.

The configuration block would look like this:

- Allow bundling up to [30] of your files 
- under [100]k each

Maybe even:
- [10] minimum seconds between sending bundles

The latter option would help in not saturating your connectivity with continuous additional connections.

**Comment by slook** [comment]
Isn't this the purpose of the 'First-In, First-Out' (FIFO) queue configuration option?

Please specify what your settings are in Preferences > Uploads > Queue Limits > Each user may queue a maximum of X files

A screenshot of the Preferences > Uploads page might be useful to help replicate the behaviour you describe.

**Comment by mathiascode** [comment]
The "Retry" option incorrectly starts concurrent uploads in Nicotine+ 3.2.0, a bug that will be fixed in 3.2.1. The Soulseek protocol doesn't support concurrent uploads officially, and as long as the official client limits the number of active uploads per user to a one, it's off limits for us too.

**Comment by digitalnexus** [comment]
> Isn't this the purpose of the 'First-In, First-Out' (FIFO) queue configuration option?
> Please specify what your settings are in Preferences > Uploads > Queue Limits > Each user may queue a maximum of X files
> A screenshot of the Preferences > Uploads page might be useful to help replicate the behaviour you describe.

In the specific enhancement I was requesting, the total number of uploads doesn't matter nor is it an issue in my specific case.

Let's say User_A has queued 20 files totalling 2GB (100MB each) to download from me,
and User_B has queued 500 files totalling 125MB (250KB per file).

Let's assume I have one upload slot.

To my understanding, round-robin will be alternating between these people.
So the first iteration will give a single 100MB file to User_A, then a single 250KB file to User_B, then back to User_A's for their next 100MB file and so on. Right?

What I was proposing was: if, I had configured a maximum bundle of 20 files that are <= 250KB each, at the first iteration of the round-robin, User_A would receive a 100MB file then User_B would receive 20 of their eligible small files (250KB * 20 = 5MB but in one go, concurrently), since they fall well within the configured bundle threshold, then back to User_A's next 100MB file, and so on.

This way it wouldn't take User_B for ever to download their much smaller files. Even if, in this same example, I had two upload slots free and these two same users took over my two upload slots, it's a LOT slower to negotiate each one of those 250KB files serially instead of in parallel.

**Comment by slook** [comment]
Okay right I get the scenario now, that is not something which has been given any consideration for the round robin queue system.

The dynamic hybrid queue system you are suggesting sounds wonderful in operation but would be highly complex to implement cleanly. I agree that it would seem frustrating that very small files take a long time to download this could make the network feel slow for no apparent reason.

I still don't understand why it is that the FIFO queue system option isn't suitable for this use case, instead of using the round-robin system? If all those small files were queued at the same time, then they should all transfer at once when it is their turn.

**Comment by digitalnexus** [comment]
Well, a single perfect queue system for every use case has yet to be found and yes, implementation of my suggestion would be far trickier to pull than a post :)

I don't really like the FIFO system as, if they were queued at the same time, then User_C waiting down the line with only one large file queued, would have to wait for all of User_B's small files to be transferred (which in practice take a lot longer than their combined file size would suggest, due to transfer overhead).

Thanks for your answers.

**Comment by mathiascode** [comment]
> which in practice take a lot longer than their combined file size would suggest, due to transfer overhead

https://github.com/nicotine-plus/nicotine-plus/commit/9290815b21d3598be6e15db00ff0d4bd9d6f6fbf should cut down the wait time by about two seconds for certain uploads.

**Comment by slook** [comment]
@digitalnexus You can install the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) 3.2.1.rc3 to see if the issue with the indirect connections being delayed is improved.
