### ISSUE TITLE
Listening port range open on router, yet Check Port Status test fails

### ISSUE THREAD

**Issue by illusoryOne** [nicotine-plus/nicotine-plus#1868]
Nicotine+ version: 
- 3.2.0

Operating System/Distribution:
- Windows 10 Home
- Version 21H1
- OS build 19043.1466

### Describe the bug
After enabling port forwarding on my router for the listening ports in Nicotine+ (TCP/UDP 2234 - 2239), I'm still unable to pass the Check Port Status test.

### Additional context
I checked to make sure I got the port range correct on my router. I use SoulseekQt with different ports & have zero issues passing the Check Port Status test there, so was wondering if this is some issue specific to Nicotine+ or user error on my end.

Router settings:
![router-settings](https://user-images.githubusercontent.com/15148336/151897699-16ab6a58-95e8-4f26-a0b5-4908bac6a058.PNG)

Nicotine+ settings:
![nic-plus-settings](https://user-images.githubusercontent.com/15148336/151897713-24325911-1ff5-4458-aa64-0fd1952d3f30.PNG)

Check Port Status results:
![web-test-proof](https://user-images.githubusercontent.com/15148336/151898784-28ecfde5-d44a-4abc-a459-3599c3b74bbd.PNG)

**Comment by slook** [comment]
- Try some other ports somewhere in the 60000+ range.
- Try deleting the "soulseekqt" service from your router config.

**Comment by illusoryOne** [comment]
I deleted the "soulseekqt" service from my router config & afterwards tried out several ports in the 60000+ range for Nicotine+. No luck. I'm not sure if this is of help or not, but if I have SoulseekQt closed, Nicotine+ running, and assign Nicotine+ the same ports that SoulseekQt used to have, it still doesn't work.

**Comment by slook** [comment]
I know it sounds stupid but did you restart your router after changing the settings? Some routers seem to stick with a cached route and struggle with forwarding from 2 different local devices pointing to the same remote address.

It's also very possible that it is a software firewall issue in the OS, see if you can find any entries for Soulseek that exist, similar outbound rules will be needed for Nicotine+ since the configuration is not automatic with UPnP disabled.

**Comment by illusoryOne** [comment]
> did you power cycle your router after changing the settings?

Yes, but only once you suggested it. Nothing changed.

I made sure to mirror the inbound firewall rules from SoulseekQt to Nicotine+ as well. They were already the same.

### Solution
Likely a restart of the PC, which is a little embarrassing. For unrelated reasons, I installed a new antivirus after your last comment (migrated from Kaspersky Security Cloud Free to Bitdefender Total Security), which in turn required a restart. I'd not set any custom firewall rules in Kaspersky Security Cloud Free or Windows Defender Firewall previously, which lends me to believe it was a simple restart that was required.

Thank you for all the help you provided and some newfound troubleshooting knowledge I can walk away with. Feel free to mark the issue as closed, as it appeared to be an issue with my environment.
