### ISSUE TITLE
Just crashed on windows insider 11 slow ring

### ISSUE THREAD

**Issue by ztauras** [nicotine-plus/nicotine-plus#1875]
Nicotine+ version:  
Operating System/Distribution:

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
@ztauras Thank you for your bug report, however the content of your above post is empty.

Please edit your post to provide any logs or other information that could help to identify and fix the issue.

**Comment by mathiascode** [comment]
Is this on Nicotine+ 3.2.0, possibly the same issue as https://github.com/nicotine-plus/nicotine-plus/issues/1777?

**Comment by slook** [comment]
We can probably assume it is the same issue, in which case this has now been fixed in the [latest stable version](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#windows) of Nicotine+ 3.2.1 so unless @ztauras has anything further to add, this bug can be closed.

**Comment by mathiascode** [comment]
If you still experience this issue in Nicotine+ 3.2.1, feel free to open a new bug report.
