### ISSUE TITLE
Feedback: Nicotine Website Updated?

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#188]
Hello,

Just some food for thought, my feedback.

If you type into Google - Nicotine Plus you'll get back 3 URL results;

```Github```
https://github.com/Nicotine-Plus/nicotine-plus

```Sourceforge```
http://nicotine-plus.sourceforge.net/

```.Org```
https://www.nicotine-plus.org/

If you guys have access to sourceforge and the .org, it would be good to keep these updated, now that the development is back...

THANKS

P.S. Keep up the great work, it's greatly appreciated!

**Comment by kiplingw** [comment]
I don't know who has access to the old SourceForge page anymore, but I encourage whoever does to consider simply redirecting it to the latter link.

**Comment by eLvErDe** [comment]
Might have access to sourceforge but I don't think so. I'll try tomorrow

**Comment by mathiascode** [comment]
This can be closed now. Everything redirects to the same website.

**Comment by 0pLuS0** [comment]
The new site looks really nice!
