### ISSUE TITLE
Translations Bug when Autoconnect is off

### ISSUE THREAD

**Issue by o-c-s** [nicotine-plus/nicotine-plus#1884]
Nicotine+ version:  win x64 3.2.1
Operating System/Distribution:
Windows 11 Pro German Edition

### Describe the bug
German translation works only partially at app start if auto connect is off...

### Expected behavior
Works if connect at start is on...

### Steps to reproduce the bug
try to reproduce failed...
bug reproduce maybe @ win start...
### Additional context
Screenshots, logs, stacktraces or relevant information.
nope

**Comment by mathiascode** [comment]
What does partially mean in this case? Can you send a few screenshots of the UI in this state?

**Comment by o-c-s** [comment]
didn't manage to reproduce the bug...
does the bug not exist at all? ;-)
good work - keep going
