### ISSUE TITLE
Wishlist: take into account search filters

### ISSUE THREAD

**Issue by garylaski** [nicotine-plus/nicotine-plus#1887]
As far as I am aware, the wishlist only takes into account the search text, and executes searches with your default filters. It would be a great feature for the wishlist to be able to save an entire search configuration (filters).

**Comment by slook** [comment]
Yes you are correct, and without the extra filters or other means of discarding unwanted results there is limited value in the wishlist at the moment. There is a partial workaround to this, see https://github.com/nicotine-plus/nicotine-plus/discussions/1604#discussioncomment-1467766 

Before this feature is added, we should add the missing Length filter.

**Comment by mathiascode** [comment]
> missing Users filter

A "Discard repeated results" wishlist feature would essentially do this: https://www.slsknet.org/news/comment/2926#comment-2926

Requested in https://github.com/nicotine-plus/nicotine-plus/discussions/1604

**Comment by slook** [comment]
Interesting, that is quite rudimentary, but probably effective enough at discarding unwanted results. There have been several variations of this over the years, pyNicotine had "Close and Ignore" perhaps that worked in a similar fashion.

While we're at it we might as well store the entire `filters` set, alongside the Wishlist search term. The most accurate method of discarding search results might vary depending on the nature of the desired file.

Probably raw Bytes values would be the best method of differentiating between two files with the same filename.

**Comment by mathiascode** [comment]
> pyNicotine had "Close and Ignore" perhaps that worked in a similar fashion.

To clarify, old Nicotine+ versions had an option to reopen closed search tabs when new results arrived, and the ignore feature was mainly used with this option. Nowadays this doesn't make much sense, since search requests are distributed faster and results fill up instantly in most cases.

**Comment by slook** [comment]
Update: This issue is one step closer since #1727 has been closed with #1892

**Comment by mathiascode** [comment]
Closing in favor of #1604

**Comment by Bunny-Head** [comment]
Sorry for re-open this but, was the "repeated results" applied? If so, I can't find it out, can you point me where?

And btw, thank you so much for still developing and improving Nicotine+!

**Comment by slook** [comment]
No, `discard_repeated` it is not added yet but it is planned see https://github.com/nicotine-plus/nicotine-plus/discussions/1604#discussioncomment-4660210
