### ISSUE TITLE
Make "PRIVATE FILE" a translatable string

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#1893]
A forwarded request from `tagomago`, please make the following string translatable.
```
gtkgui/search.py
                name = "[PRIVATE FILE]  " + name
```

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/5eb9636b5ddaf3b43491c6877b7e65512910fc1a
