### ISSUE TITLE
wait a minute, only spellchecker is missing ?

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#190]
spending few hours on rooms and you can see how much we all need spellchecker comeback 
:o) 

hav a nice coding day ! tahnk uyo

**Comment by mathiascode** [comment]
Should be fairly easy to switch from Libsexy to GSpell for spell checking, but it's on the todo list.

**Comment by zniavre** [comment]
Thank you very much !
