### ISSUE TITLE
No working versions for Mac OS X 10.14 Mojave

### ISSUE THREAD

**Issue by godzfire** [nicotine-plus/nicotine-plus#1913]
This post is similar to a thread on here about 1.5-1 years ago (https://github.com/nicotine-plus/nicotine-plus/pull/722). Since so much time has elapsed, I thought it proper to create a new one.

I have Mac OS X 10.14 Mojave and can't update any further for 32bit application reasons.

I know that an actual prebuilt binary exists for 10.15, but nothing anymore for 10.14. I tried to use Homebrew as was suggested to create it, and everything runs and installs okay and it says that nicotine-plus installed (https://pastebin.com/raw/2b96gnuU), but there's no icon in my applications folder. I'm not sure what I'm doing wrong. I'm not sure if it's because according to the Homebrew page, 10.14 is no longer listed there either (https://formulae.brew.sh/formula/nicotine-plus).

It also sounds like if I compiled the program myself on my 10.14 system it would work, but I have absolutely no idea how to do that. I'm very sorry but it's like trying to understand another language to me.

Could I please get some assistance, or does someone have a built 10.14 version they'd be willing to share?

**Comment by godzfire** [comment]
Sorry, I accidently put the label to bug instead of other, but can't change it.

**Comment by slook** [comment]
If the application icon hasn't appeared then this is a Bug.

Have you tried running the `nicotine` command from the terminal?

**Comment by godzfire** [comment]
Running nicotine in terminal does indeed open the program, though the dock app shows as Python, not sure if that's expected behaviour or not.

How could I get an actual application icon created for it?

**Comment by mathiascode** [comment]
You can create your own .dmg package by running the following commands (with Homebrew installed):

```
python3 packaging/macos/dependencies_core.py
python3 packaging/macos/dependencies_packaging.py
pyinstaller packaging/macos/nicotine.spec
python3 packaging/macos/create_dmg.py
```

The .dmg file should then end up in the `dmg` folder.

I think I'll remove the instructions for installing Nicotine+ from Homebrew. It's CLI-focused (doesn't add an application launcher), and doesn't represent the experience we want to offer.

**Comment by godzfire** [comment]
This is what gets made:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2067820/155266592-54c58f02-9aed-4127-9d02-a7594f366850.png">

I move it into the application folder, double click the app, and for a split second you see something in the dock try to open but then disappear.
The only thing i see in console is: "Feb 22 23:38:27 GodzFire-MM com.apple.xpc.launchd[1] (org.nicotine_plus.Nicotine.48632[19730]): Service exited with abnormal code: 1"

Here's what the Nicotine+ folder contains:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/2067820/155267313-5eb2aec9-6e51-48bb-abc1-e377166dae40.png">

And here's the inside of the app:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/2067820/155267387-8305c5fc-b001-4a91-b90c-96c984df13f5.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/2067820/155267443-36554d10-29c9-46f5-84df-cc12b9c88803.png">
<img width="546" alt="image" src="https://user-images.githubusercontent.com/2067820/155267455-8b0e4400-8d53-45f6-9f16-afc3a0c30ddb.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/2067820/155267469-b21c48c0-df65-4720-959c-49c67cb76f67.png">
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/2067820/155267482-853f32a4-6918-4e4b-89d6-d633b75c052b.png">
<img width="773" alt="image" src="https://user-images.githubusercontent.com/2067820/155267491-d56575e9-6fbd-4902-94f7-bc5fbb83d13f.png">

**Comment by mathiascode** [comment]
> This is what gets made: <img alt="image" width="528" src="https://user-images.githubusercontent.com/2067820/155266592-54c58f02-9aed-4127-9d02-a7594f366850.png">

Something seems wrong here. I'll try the same steps on my macOS VM soon to see what happens.

**Comment by godzfire** [comment]
It would be really nice to just have a proper pre-built one made instead of all this homebrew stuff and what not.

**Comment by slook** [comment]
This subject has been tackled last year, at which point there are some not-too-old version builds that may work on Mojave 10.14 see https://github.com/nicotine-plus/nicotine-plus/issues/1366 i don't know if that thread is helpful or just creates more confusion at this point, it seems that none of this was properly packaged.

As to creating a current and ongoing build workflow, this is time consuming and requires considerable maintenance, so the best that can be hoped for is for us to identify and document a stable Nicotine+ version that legacy users can stick with.

**Comment by mathiascode** [comment]
> This subject has been tackled last year, at which point there are some not-too-old version builds that may work on Mojave 10.14 see #1366 i don't know if that thread is helpful or just creates more confusion at this point, it seems that the linked builds were not intended for stable release so are not properly packaged.

IIRC, the builds didn't work on Mojave in the end, and would've been too difficult to maintain.

I would provide official builds for Mojave if GitHub Actions still provided images for the OS version, but those were removed a long time ago. I don't have a VM running Mojave either, so I can't create builds for it myself (unfortunately you can't create builds for older macOS versions on a more recent version). I'll follow the build steps on my Catalina VM though and see if I can find any issues in the build process.

**Comment by godzfire** [comment]
Thank you very much, appreciate the time.

**Comment by mathiascode** [comment]
Could you try these steps? https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/PACKAGING.md#macos

I ended up with a build identical to the prebuilt ones when following the commands.

**Comment by godzfire** [comment]
Everything works fine for building, but as soon as I launch, it shows the dock icon for a split second, then disappears, like the above I posted.

Again, if I just run 'nicotine' from terminal, it opens up the GUI via Python okay.

Here's info from the console:
default	2022-03-14 13:42:07.606501 -0500	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- /Applications/Nicotine+.app/Contents, NSFilePath=/Applications/Nicotine+.app/Contents/PlugIns, NSUnderlyingError=0x7f87898ed0f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

info	2022-03-14 13:42:07.615262 -0500	Finder	LaunchApplication: appToLaunch={ "ApplicationType"="Foreground", "CFBundleExecutablePath"="/Applications/Nicotine+.app/Contents/MacOS/Nicotine+", "CFBundleExecutablePathDeviceID"=16777220, "CFBundleExecutablePathINode"=44570881, "CFBundleIdentifier"="org.nicotine_plus.Nicotine", "CFBundleName"="Nicotine+", "CFBundlePackageType"="APPL", "LSBundlePath"="/Applications/Nicotine+.app", "LSBundlePathDeviceID"=16777220, "LSBundlePathINode"=44570745, "LSExecutableFormat"="LSExecutableMachOFormat", "LSLaunchDLabel"="org.nicotine_plus.Nicotine.51476" } modifiers: { "AddPSNArgument"=true, "LSAdditionalEnvironmentVars"={  }, "LSLaunchAsync"=true, "LSLaunchStoppedTemporarily"=true } args=[ NULL ]

info	2022-03-14 13:42:07.616719 -0500	Finder	 Convert "/Applications/Nicotine+.app/Contents/MacOS/Nicotine+" = /Applications/Nicotine+.app/Contents/MacOS/Nicotine+

info	2022-03-14 13:42:07.620814 -0500	launchservicesd	NotifyAboutLaunchedApplication: {modifiers={LSLaunchAsync=true, LSAdditionalEnvironmentVars={}, LSFrontApplicationSeed=2351, LSLaunchStoppedTemporarily=true, LSLaunchProgressTimeout=30, LSUserActivityCount=0, AddPSNArgument=true, }, session=100009, exitstatusport=xpc object:<mach receive right: 0x7fc28233e5e0> { name = 0x1d53f, right = receive } , pid=38340U, asn=4178940U, command=600, info={ApplicationType="Foreground", CFBundleExecutablePathINode=44570881, CFBundleExecutablePathDeviceID=16777220, LSBundlePathDeviceID=16777220, LSExecutableFormat="LSExecutableMachOFormat", CFBundlePackageType="APPL", pid=38340, BundleIdentifierLowerCase="org.nicotine_plus.nicotine", LSWantsToComeForwardAtRegistrationTimeKey=true, LSASN={com.apple.coreservices.asn.hi=0U, com.apple.coreservices.asn=UUID:$c96172a0ce744d62, com.apple.coreservices.asn.lo=4178940U, }, CFBundleName="Nicotine+", LSLaunchTime=0118/01/25 16:18:33 , CFBundleExecutablePath="/Applications/Nicotine+.app/Contents/MacOS/Nicotine+", LSBundlePath="/Applications/Nicotine+.app", LSLa<…>

info	2022-03-14 13:42:07.621017 -0500	launchservicesd	-- Creating new LSApplication object for pending application (which we've gotten notified to expect), asn=[ 0x0/0x3fc3fc]  pid=38340 info={ "ApplicationType"="Foreground", "BundleIdentifierLowerCase"="org.nicotine_plus.nicotine", "CFBundleExecutablePath"="/Applications/Nicotine+.app/Contents/MacOS/Nicotine+", "CFBundleExecutablePathDeviceID"=16777220, "CFBundleExecutablePathINode"=44570881, "CFBundleIdentifier"="org.nicotine_plus.Nicotine", "CFBundleName"="Nicotine+", "CFBundlePackageType"="APPL", "LSASN"=ASN:0x0-0x3fc3fc:, "LSBundlePath"="/Applications/Nicotine+.app", "LSBundlePathDeviceID"=16777220, "LSBundlePathINode"=44570745, "LSDisplayName"="Nicotine+", "LSExecutableFormat"="LSExecutableMachOFormat", "LSLaunchDLabel"="org.nicotine_plus.Nicotine.51476", "LSLaunchedByLaunchServices"=true, "LSLaunchedWithLaunchD"=true, "LSLaunchEventRecordTime"=144447295872891, "LSLaunchTime"=now-ish 2022/03/14 13:42:07, "LSParentASN"=ASN:0x0-0x29c29c:, "LSWantsToComeForwardAtRegistrationTimeKey"=true, "pid"=38340 } portToReceiveExitStatusOn=0x1d53f:MACH_PORT_RIGHT_RECEIVE=1,

info	2022-03-14 13:42:07.621260 -0500	launchservicesd	Setting "CFBundleNameLowerCase" to "nicotine+"

info	2022-03-14 13:42:07.621760 -0500	launchservicesd	POLICY: Setting application App:"Nicotine+" asn:0x0-3fc3fc pid:38340 refs=2 @ 0x7fc282521dd0, pid=38340 to PRIO_DARWIN_ROLE_UI_NON_FOCAL

info	2022-03-14 13:42:07.622383 -0500	Finder	LaunchedApplication: "/Applications/Nicotine+.app/Contents/MacOS/Nicotine+", psn=[ 0x0/0x3fc3fc]

info	2022-03-14 13:42:07.622470 -0500	Finder	Application { "ApplicationType"="Foreground", "BundleIdentifierLowerCase"="org.nicotine_plus.nicotine", "CFBundleExecutablePath"="/Applications/Nicotine+.app/Contents/MacOS/Nicotine+", "CFBundleExecutablePathDeviceID"=16777220, "CFBundleExecutablePathINode"=44570881, "CFBundleIdentifier"="org.nicotine_plus.Nicotine", "CFBundleName"="Nicotine+", "CFBundlePackageType"="APPL", "LSASN"=ASN:0x0-0x3fc3fc:, "LSBundlePath"="/Applications/Nicotine+.app", "LSBundlePathDeviceID"=16777220, "LSBundlePathINode"=44570745, "LSDisplayName"="Nicotine+", "LSExecutableFormat"="LSExecutableMachOFormat", "LSLaunchDLabel"="org.nicotine_plus.Nicotine.51476", "LSLaunchedByLaunchServices"=true, "LSLaunchedWithLaunchD"=true, "LSLaunchEventRecordTime"=144447295872891, "LSLaunchTime"=now-ish 2022/03/14 13:42:07, "LSParentASN"=ASN:0x0-0x29c29c:, "LSWantsToComeForwardAtRegistrationTimeKey"=true, "pid"=38340 } launched temporarily-stopped, so this application must start it after returning from _LSLaunchApplication().
default	2022-03-14 13:42:07.622872 -0500	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Nicotine+, ready, updating active tracking timer
default	2022-03-14 13:42:07.622905 -0500	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Nicotine+
default	2022-03-14 13:42:07.623905 -0500	distnoted	register name: com.apple.sharedfilelist.change object: com.apple.LSSharedFileList.ApplicationRecentDocuments/org.nicotine_plus.nicotine token: f4754 pid: 289

info	2022-03-14 13:42:07.735494 -0500	launchservicesd	Got exit notification for application App:"Nicotine+" asn:0x0-3fc3fc pid:38340 refs=5 @ 0x7fc282521dd0, pid=38340, from port=0x1d53f:MACH_PORT_RIGHT_RECEIVE=1, fExitStatus=1.

info	2022-03-14 13:42:07.735681 -0500	launchservicesd	ADDING: App:"Nicotine+" asn:0x0-3fc3fc pid:38340 refs=4 @ 0x7fc282521dd0 exitStatus=1

info	2022-03-14 13:42:07.735729 -0500	launchservicesd	ADDING { "ApplicationType"="Foreground", "CFBundleExecutablePath"="/Applications/Nicotine+.app/Contents/MacOS/Nicotine+", "CFBundleIdentifier"="org.nicotine_plus.Nicotine", "DeathTime"=now-ish 2022/03/14 13:42:07, "LSBundlePath"="/Applications/Nicotine+.app", "LSDisplayName"="Nicotine+", "LSExitStatus"=1, "pid"=38340 } to sDeadApplicationInformation for 38340

default	2022-03-14 13:42:07.737521 -0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Nicotine+, _appTrackingState = 2

default	2022-03-14 13:42:07.737543 -0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Nicotine+, quit, updating active tracking timer

info	2022-03-14 13:42:07.739147 -0500	launchservicesd	virtual LSApplication::~LSApplication(), application [ 0x0/0x3fc3fc]  pid=38340 "Nicotine+" @ 0x7fc282521de0 being deleted, refs=1

**Comment by slook** [comment]
> Non-fatal error... "The file “PlugIns” couldn’t be opened because there is no such file."

Perhaps this leads to a runtime error, since the lowercase "plugins" name is somehow incorrect.

**Comment by godzfire** [comment]
Since I needed to get off Mojave anyway due to the rapid MacOS compatibility loss, I ripped off the bandaid and went to Monterey.

**Comment by slook** [comment]
It is good to know that legacy Mojave users can start `nicotine` from the terminal, even though this is not ideal it seems to be an acceptable workaround at this point.
