### ISSUE TITLE
Nicotine+ doesn't open: Value: 'int' object has no attribute 'split' error

### ISSUE THREAD

**Issue by lachlantula** [nicotine-plus/nicotine-plus#1917]
Nicotine+ version:  3.2.1
Operating System/Distribution: Arch (using kernel 5.6.10-arch1-1)

### Describe the bug

Nicotine+ crashes when I open it with the following error: 

```
Nicotine+ Version: 3.2.1
GTK Version: 3.24.31
Python Version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]

Type: <class 'AttributeError'>
Value: 'int' object has no attribute 'split'
Traceback:   File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/frame.py", line 1982, in do_activate
    NicotineFrame(
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/frame.py", line 200, in __init__
    connect_ready = network_processor.start(self, self.network_callback)
  File "/usr/lib/python3.10/site-packages/pynicotine/pynicotine.py", line 247, in start
    self.transfers.init_transfers()
  File "/usr/lib/python3.10/site-packages/pynicotine/transfers.py", line 133, in init_transfers
    self.downloadsview.init_transfers(self.downloads)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/transferlist.py", line 210, in init_transfers
    self.update(forceupdate=True)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/transferlist.py", line 311, in update
    self.update_specific(transfer_i)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/transferlist.py", line 498, in update_specific
    shortfn = filename.split("\\")[-1]
```

### Expected behavior

Nicotine+ will open successfully.

### Steps to reproduce the bug

Open Nicotine+ on my system.

### Additional context

I don't really have any good explanation for this error, but it also occurs when using the nicotine-plus-git package. If anyone has any pointers I'd be happy to provide some more information than I have.

**Comment by mathiascode** [comment]
Did this issue start occurring recently? If so, do you remember what you did? There seems to be an invalid file path value at the second index of one of the downloads, in ~/.local/share/nicotine/downloads.json. Could you post the problematic download here?

**Comment by lachlantula** [comment]
> Did this issue start occurring recently?

It's been a while since I first started having this error. I never really made the connection that a download could have caused the error, so I stopped using Nicotine for a while in case an update came around that fixed this error.

> Could you post the problematic download here?

My `downloads.json` looks like so:

`
[["imwinnin", 16, "", "Old", null, null, "16", "36:53"], ["ZywnOkwQ=", "@@xrknr\\music\\SHAWN KEMP\\[2015] Trick Dice\\AlbumArtSmall.jpg", "[2015] Trick Dice", "Old", 5559, null, "", ""], ["ZywnOkwQ=", "@@xrknr\\music\\SHAWN KEMP\\[2015] Trick Dice\\Folder.jpg", "[2015] Trick Dice", "Old", 23517, null, "", ""], ["104rog", "@@rwpjp\\[MUSIC DL]\\complete\\Big KRIT - 2010-Krit Wuz Here (Big K.R.I.T-\\albumart_{66252bcd-edc9-4b02-8a34-f8c7579d1baf}_large.jpg", "/home/lachie/Downloads/Big KRIT - 2010-Krit Wuz Here (Big K.R.I.T-", "Old", 20088, null, "", ""], ["104rog", "@@rwpjp\\[MUSIC DL]\\complete\\Big KRIT - 2010-Krit Wuz Here (Big K.R.I.T-\\albumart_{66252bcd-edc9-4b02-8a34-f8c7579d1baf}_small.jpg", "/home/lachie/Downloads/Big KRIT - 2010-Krit Wuz Here (Big K.R.I.T-", "Old", 3561, null, "", ""], ["Gashius Slay", "@@anhfv\\MUSIC\\F\\fly anakin & Koncept Jackson\\2017 - Chapel Drive CS\\folder.jpg", "/home/lachie/Downloads/2017 - Chapel Drive CS", "Old", 70710, null, "", ""], ["rancid88", "@@snalv\\Music\\Hip-hop\\Roc Marciano - Reloaded  (2012-album)\\thumbs.db", "/home/lachie/Downloads/Roc Marciano - Reloaded  (2012-album)", "Old", 39936, null, "", ""], ["boryaborya", "@@zsttx\\music\\The Weeknd\\After Hours\\albumart.jpg", "/home/lachie/Downloads/After Hours", "Old", 297215, null, "", ""], ["kartikt", "@@obxpy\\complete\\Pinata (2014)\\folder.jpg", "/home/lachie/Downloads/Pinata (2014)", "Old", 103845, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\10 Riverside Freestyle-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 2418227, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\11 Green Light-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 5117706, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\12 Homme-Angel Interlude-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 4993100, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\13 Life After Death-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 2688416, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\14 The Maury Show-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 4757221, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\15 Clicqout-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 3102959, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\16 Switch-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 4390767, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\17 Time Worth More Than Money-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 4636668, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\18 Hills Have Eyes (Bonus Track)-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 3959236, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\19 Ghost Ride feat. Yungmorpheus (Bonus Track)-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 7150394, null, "", ""], ["kellbc1", "@@yniem\\U.S.A\\2020's\\LPs, EPs 12s'' & Tapes\\YL [New York]\\[2020] Jesus Is My Homeboy\\20 Pray On It (Bonus Track)-HHB.mp3", "/home/lachie/Downloads/[2020] Jesus Is My Homeboy", "Old", 2996175, null, "", ""], ["matis_keynell", "@@mzrye\\msc_\\week 2021_12\\Mark Fell & Rian Treanor - Last exit to Chickenley (2021)\\01 - Last exit to Chickenley (Download Edit).mp3", "", "Paused", 83203457, 3604480, "320", "34:40"]]
`

**Comment by slook** [comment]
In the very first record... `16` that value is an integer, and not a string as it should be. Somehow the size is mixup with filename...

`["imwinnin", 16, "", "Old", null, null, "16", "36:53"],`

For you @lachlantula you can fix the error by deleting this record from the file (or deleting the entire file).

For us we should put the three missing sanity checks into add_stored_transfers for `user=i[0], filename=i[1], path=i[2]` here:

https://github.com/nicotine-plus/nicotine-plus/blob/701cc30acbfe5e189d6b073bfd8ce7db3c3e2dfe/pynicotine/transfers.py#L250

https://github.com/nicotine-plus/nicotine-plus/blob/701cc30acbfe5e189d6b073bfd8ce7db3c3e2dfe/pynicotine/transfers.py#L297

**Comment by mathiascode** [comment]
> In the very first record... `16` that value is an integer, and not a string as it should be. Somehow the size is mixup with filename...

That's the bitrate, the size is missing entirely.

It's possible that an old build extracted the incorrect values when queuing a download from a certain part of the program, at least I have vague memories of this. I've checked all parts of the code that provide a file path to Transfer objects, and everything seemed fine. Since nobody else has reported this issue, it probably happened a long time ago, and started causing issues after the critical error dialog was added.
 
> For us we should put the three missing sanity checks into add_stored_transfers for `user=i[0], filename=i[1], path=i[2]` here:
> 
> https://github.com/nicotine-plus/nicotine-plus/blob/701cc30acbfe5e189d6b073bfd8ce7db3c3e2dfe/pynicotine/transfers.py#L250
> 
> https://github.com/nicotine-plus/nicotine-plus/blob/701cc30acbfe5e189d6b073bfd8ce7db3c3e2dfe/pynicotine/transfers.py#L297

str(i[0]), str(i[1]) and str(i[2]) should do. We should also skip transfers that don't include these properties.

**Comment by slook** [comment]
> str(i[0]), str(i[1]) and str(i[2]) should do. 

No, this is insufficient, because `str()` will gladly convert an int value into a valid string, which then appears in the list.

`isinstance()` is required if we are to ensure that those values are not integers or some other data type that can be interpreted as a string.

**Comment by mathiascode** [comment]
> No, this is insufficient, because `str()` will gladly convert an int value into a valid string, which then appears in the list.

It depends on the situation, but yes, we should probably discard the download entirely here, since these strings are sent to other peers.

I find `isinstance()` ugly in general, but I guess we don't have another option here.

**Comment by slook** [comment]
We could use `isdigit()` or `is_integer()` to check `any()` of `map()` values contain only numerics in one go, maybe this will be faster or maybe not.
