### ISSUE TITLE
userlist for myself does not display files number

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#192]
in userlist and buddylist for myself it displays 0 file , i delete my old config file to make new configuration but it still does not display real number of my share files (it should display at least 6000 +/-)

thank you.

**Comment by zniavre** [comment]
i hav confirmation that a friend using slskQT can see my number of files in the user list and buddylist 

but here with last commit of nic+ it does not appear

**Comment by mathiascode** [comment]
Looks like the file count is incorrectly displayed under the directory count for some reason.
