### ISSUE TITLE
note editing no longer opens by double-clicking? 3.3.0.dev1

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1939]
Nicotine+ 3.3.0.dev1

note could be edited by clicking twice. now it is possible only after selecting in the context menu. it was more convenient.

**Comment by slook** [comment]
https://github.com/nicotine-plus/nicotine-plus/blob/e0db270d501a7cf06101abd003d1e158e88ee473/pynicotine/gtkgui/userlist.py#L114-L115

Confirm editing the cell is not possible GTK 3.22.11

**Comment by mathiascode** [comment]
Seems to be a regression in https://github.com/nicotine-plus/nicotine-plus/commit/f8b6cc4e5e4b7af68b04aa776fe3db2efc8cce2b.

**Comment by slook** [comment]
Must be `renderer.set_property` that overrides the explicit `render.connect`

**Comment by mathiascode** [comment]
> Perhaps it would not be a great loss to do away with the editable cells and instead divert the on_row_activated to the `on_add_note` dialog if column == 9

Implemented in https://github.com/nicotine-plus/nicotine-plus/commit/6f3e8dacb744c0dcaf5c50cdeb769279d399f8de

**Comment by slook** [comment]
> we need to implement support for two text entries in entry_dialog

I see what you mean, that is going to be ugly
