### ISSUE TITLE
Nicotine+ does not preserve the folder structure when downloading

### ISSUE THREAD

**Issue by aquila-XP** [nicotine-plus/nicotine-plus#1940]
Nicotine+ version:  3.2.1
Operating System: Windows 10 x64

**Describe the bug**

When choosing `Download Folder & Subfolder(s)` (or `Download Folder & Subfolder(s) To...`) from the right click menu, the subfolders are downloaded separated in the main folder.
I did not find an option to change this behavior. Downloading many subfolders and getting them messed up is very annoying.

Original structure of folders:
`Folder1\file7.ogg`
`Folder1\file8.ogg`
`Folder1\Folder2\Joys\file1.txt`
`Folder1\Folder3\Boys\file3.mp3`
`Folder1\Folder4\Goys\file2.flac`
`Folder1\Folder4\Goys\10\file4.flac`
`Folder1\Folder5\Joys\file1.txt`

Messed up structure of folders:
`Folder1\file7.ogg`
`Folder1\file8.ogg`
`Folder1\Joys\file1.txt`
`Folder1\Joys\file1.txt(1)`
`Folder1\Boys\file3.mp3`
`Folder1\Goys\file2.flac`
`Folder1\10\file4.flac`

Somehow all the folders between the first and the last are omitted from the path.
If the last subfolder have the same name with another from a different path and also the are files with similar name, these files are renamed as duplicates file1(1).mp3, file1(2).mp3, file1(3).mp3 and so on.

Please add some option to preserve the structure of all folders from the path.

**Comment by slook** [comment]
Thank you for raising this issue, this has been noticed before but has been forgotten about.

The code which handles the folder recursion needs to be more elaborate in order to stack the paths.

Currently we use get_folder_destination from the Transfers module, which is unsuitable for this use case in UserBrowse because it flattens down the last folder in the path, therefore it requires it's own recursion mechanism that is more similar to the implementation in the shares Scanner.

**Comment by slook** [comment]
@aquila-XP Please can you install the [latest unstable build](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) of Nicotine 3.3.0.dev1 and run some test downloads to let us know if subfolder downloading is working as expected now, or if anything else is needed.

**Comment by LightGameStudio42** [comment]
3.3.4, similiar issue. Unlike soulseek, it doesn't create subfolders for each set of files, so when I select not the whole folder, but some songs (maybe it happens even with the whole folder), it puts them in one directory /downloads, so I have to create folders and ambum names from dile properties.

**Comment by slook** [comment]
It is planned for being remedied in PR #3024
