### ISSUE TITLE
How to start nicotine and which ports should be open with Linux ? 

### ISSUE THREAD

**Issue by obriankevin11** [nicotine-plus/nicotine-plus#1941]
Hi,
Can't find any documentation regarding how to start nicotine in Linux. I have this:

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(nicotine:10363): Gdk-CRITICAL **: 18:03:21.595: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(nicotine:10363): Gdk-CRITICAL **: 18:03:21.595: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(nicotine:10363): Gdk-CRITICAL **: 18:03:21.595: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(nicotine:10363): Gtk-CRITICAL **: 18:03:21.595: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(nicotine:10363): Gtk-CRITICAL **: 18:03:21.610: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Unable to init server: Could not connect: Connection refused

(org.nicotine_plus.Nicotine:10363): Gtk-WARNING **: 18:03:21.644: cannot open display: ```

Could you help please?
Thank you

**Comment by slook** [comment]
Please can you provide which version of GTK is installed on your system, for example the version of the `libgtk-3.0` package?

**Comment by hboetes** [comment]
`cannot open display` is a typical error message if you log in to a server via for example ssh, and you are not connected to a local graphical session. Using `ssh -YC user@remotehost` might help.

If not, please describe in more detail how you are trying to start nicotine+.

**Comment by slook** [comment]
> a typical error message if you log in to a server via for example ssh

Good call, I can confirm that running `nicotine` over a `ssh` terminal session produces output identical to @obriankevin11 's OP.

> Using ssh -YC user@remotehost might help.

Starting the session with `ssh -YC` doesn't make any difference on Debian, not for nicotine nor any other GUI application.

However, running `nicotine --headless` does work as expected in an SSH session.

**Comment by slook** [comment]
In this scenario, simply checking for the presence of the Gtk module evidently isn't enough to verify that the user is actually able to start the display server in their runtime environment for drawing the application window:

https://github.com/nicotine-plus/nicotine-plus/blob/a001394ba4cedea09e9e5f2134c65c06bb1eb655/pynicotine/gtkgui/__init__.py#L44-L48

If anticipating or catching this error is trivial, then the out-of-box command line experience could be enhanced by offering a helpful error message and/or diverting run() into `--headless` mode to help users who are deprived of a graphical display.
