### ISSUE TITLE
Question: pytaglib required for 3.2.1?

### ISSUE THREAD

**Issue by 0pLuS0** [nicotine-plus/nicotine-plus#1952]
Hello,

It has been my understanding that for past versions pytaglib was a dependency.

Is this still a required dependency, or has it been dropped?

THANKS

**Comment by mathiascode** [comment]
Hi, welcome back!
pytaglib is no longer a dependency since Nicotine+ 2.2.0, released in late 2020. A list of dependencies can be found here: https://github.com/nicotine-plus/nicotine-plus/blob/3.2.1/doc/DEPENDENCIES.md#runtime

**Comment by 0pLuS0** [comment]
Welcome back, what you remember me? LOL

Ok thanks, I have the latest compiled and running...

Boy does the UI look really SLICK, I love it!

Keep up the great work, I hope the project lives long!

Take care... :)
