### ISSUE TITLE
Turn the ✉ blue, instead of adding a blue dot.

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#1954]
Wouldn't it be nice if the ✉ icon turns blue, instead of adding the blue dot, to indicate a message?
And of course the same for the other tabs.

Thanks for pondering on this idea.

**Comment by hboetes** [comment]
It certainly will look nice, but for colour-blind people it might be invisible.
I retract my request.

**Comment by mathiascode** [comment]
Additionally, there would likely be compatibility issues with various icon themes.

**Comment by hboetes** [comment]
Right, not all are transparent.

**Comment by mathiascode** [comment]
This became a thing when we added custom color support for status icons a while back.
