### ISSUE TITLE
Nicotine+ crashes or hangs after a few seconds after it's started

### ISSUE THREAD

**Issue by xGigaa** [nicotine-plus/nicotine-plus#1962]
Nicotine+ version:  3.2.2
Operating System/Distribution:  Arch Linux

### Describe the bug
I recently updated to version 3.2.2 and it seems like Nicotine+ will hang after a few seconds on my system and then crash after a few minutes.
The log has nothing of interest other than "Lost connection to Wayland compositor" before it crashes.

To rule out that it's not a wayland issue i tested it on X11 and headless aswell.

- X11 works but it takes about 5 minutes before the window becomes interactive and before activity starts.
- Headless seems to work immediately.

### Expected behavior
Being able to use it without crashing or hanging

### Steps to reproduce the bug
1. Be on 3.2.2 and start up Nicotine+
2. Wait 2-3 seconds.
3. Nicotine will hang then crash after a minute or two.

### Additional context
Screenshots, logs, stacktraces or relevant information.
```
[2022-03-20 06:37:19] Loading GTK 3.24.33
[2022-03-20 06:37:19] Loading Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
[2022-03-20 06:37:19] Loading Nicotine+ 3.2.2
[2022-03-20 06:37:19] Listening on port: 2235
[2022-03-20 06:37:19] Loading plugin system
[2022-03-20 06:37:19] Connecting to server.slsknet.org:2242
[2022-03-20 06:37:19] Connected to server server.slsknet.org:2242, logging in…
[2022-03-20 06:37:19] 1810 privileged users
[2022-03-20 06:37:19] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
Gdk-Message: 06:41:31.669: Lost connection to Wayland compositor.
```

**Comment by mathiascode** [comment]
To rule out any issues related to updated system components, can you do the following:

Run version 3.2.1 with GTK 3:

```
git clone -b 3.2.1 https://github.com/nicotine-plus/nicotine-plus
cd nicotine-plus
./nicotine
```

Run version 3.2.1 with GTK 4:

`NICOTINE_GTK_VERSION=4 ./nicotine`

Run version 3.2.2 with GTK 3:

```
git clone -b 3.2.2 https://github.com/nicotine-plus/nicotine-plus
cd nicotine-plus
./nicotine
```

Run version 3.2.2 with GTK 4:

`NICOTINE_GTK_VERSION=4 ./nicotine`

**Comment by xGigaa** [comment]
Okey, I went and tried all of them and 3.2.2 hanged a bunch then crashed but then it just started working again for no reason...
You can probably close this issue as it's working flawlessly now.
Thanks for the help :)

**Comment by slook** [comment]
It's a shame we couldn't identify the reason for the crashing, this needs further testing.

Please feel free to re-open the issue if there are any further problems.
