### ISSUE TITLE
Issue on macOS Monterey 12.2.1

### ISSUE THREAD

**Issue by pierreguan** [nicotine-plus/nicotine-plus#1969]
Nicotine+ version:  3.2.2
Operating System/Distribution: Macbook Pro 13' 2020 (macOS Monterey 12.2.1)

### Describe the bug
Error "impossible to open Nicotine+, the software must be updated..." when opening the app

### Additional context
<img width="374" alt="image" src="https://user-images.githubusercontent.com/9553761/159738233-34f4e746-b217-4e62-b240-4aa1398a09c5.png">

**Comment by mathiascode** [comment]
You have to follow these instructions the first time you open Nicotine+ (we can't afford signing the application): https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Let me know if it still doesn't work.
