### ISSUE TITLE
Downloading and user file browsing suddenly stops working after two successful downloads

### ISSUE THREAD

**Issue by varun-ramraj** [Nicotine-Plus/nicotine-plus#197]
If I try to browse a user's files after freshly starting up 1.4.3 unstable, I can browse them and try to download. After the first couple of files download (I've noticed that 2 files are always successful in my few test runs), the rest stay in "Connecting" state. I do not have the logs from the host's point of view, but I can confirm that once this happens, I can no longer browse a user's files (I don't see the little lightbulb next to "User browse", and I don't see any file lists. The log shows this:

```
19:04:25 <class 'pynicotine.slskmessages.OutConn'> {'conn': <socket.socket fd=37, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('x.x.x.x', 49236), raddr=('y.y.y.y', 15000)>, 'addr': ('y.y.y.y', 15000), 'init': None}
19:05:26 Connection closed by peer: {'addr': ('y.y.y.y', 15000), 'username': 'REMOVED', 'conn': <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>, 'msgs': [], 'token': None, 'init': <pynicotine.slskmessages.PeerInit object at 0x7f745c0fb0d0>, 'conntimer': None, 'tryaddr': None}
```

I've removed IP addresses for privacy, but all instances of "y.y.y.y" are the same IP address.
After restarting, I can browse for the files, but the downloads continue to stay in "Establishing connection" or "Connecting" states.

**Comment by varun-ramraj** [comment]
Just to add, I've checked the file transfer list again and one file has moved to "Cannot connect" state.

**Comment by zniavre** [comment]
can'tconfirm just trying downloading 188mo folder with 18files they were downloaded in one  'shot'
maybe user uploader is dieconnected ?

**Comment by varun-ramraj** [comment]
I've tried several scenarios, and yes, I asked the users to restart their clients. Randomly, a few files worked before choking up again and starting the same pattern over. I am not able to establish exactly when this behaviour occurs; is there anything I can do further with the logs to help?

**Comment by mathiascode** [comment]
Does the same happen on 1.4.1?

**Comment by varun-ramraj** [comment]
Sorry @mathiascode got caught up with work today. Will test it and report back shortly.

**Comment by varun-ramraj** [comment]
@mathiascode I am not able to replicate this reliably on either 1.4.1 or 1.4.3. I'll close this for now and open a new one if I can give you a more reliable replication protocol!
