### ISSUE TITLE
Gdk-CRITICAL messages related to tray icon

### ISSUE THREAD

**Issue by 0pLuS0** [nicotine-plus/nicotine-plus#1973]
Nicotine+ version:  
Operating System/Distribution:

Slackware 15.0, nicotine+ 3.2.2 compiled from source, python3-3.9.12

### Describe the bug

(org.nicotine_plus.Nicotine:23165): Gdk-CRITICAL **: 17:01:02.946: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

### Expected behavior

Not to see this message I assume...

### Steps to reproduce the bug

I ran nicotine from the terminal and noticed this message.

### Additional context
```
~ pts/0 foo ~ >nicotine
[2022-03-24 17:01:02] Loading GTK 3.24.31
[2022-03-24 17:01:02] Loading Python 3.9.12 (main, Mar 24 2022, 14:31:07) 
[GCC 11.2.0]
[2022-03-24 17:01:02] Loading Nicotine+ 3.2.2
[2022-03-24 17:01:02] Listening on port: 2234
[2022-03-24 17:01:02] Loading plugin system
[2022-03-24 17:01:02] Connecting to server.slsknet.org:2242
[2022-03-24 17:01:02] Rescanning shares…
[2022-03-24 17:01:02] 0 folders found before rescan, rebuilding…
[2022-03-24 17:01:02] Rescan complete: 0 folders found

(org.nicotine_plus.Nicotine:23165): Gdk-CRITICAL **: 17:01:02.946: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[2022-03-24 17:01:03] Connected to server server.slsknet.org:2242, logging in…
[2022-03-24 17:01:04] 1796 privileged users
[2022-03-24 17:01:04] You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
[2022-03-24 17:01:04] UPnP: Failed to forward external port 2234: UPnP is not available on this network
[2022-03-24 17:01:08] Quitting Nicotine+ 3.2.2, application closing…
[2022-03-24 17:01:08] Quit Nicotine+ 3.2.2, done!
```

**Comment by slook** [comment]
Please can you disable the Tray Icon (in Preferences > User Interface > 'Display tray icon' > Off) and let us know if the warning message is still there or not.

**Comment by 0pLuS0** [comment]
I disabled it, and that did the trick!

The OLE TRAY ICON! LOL :)

**Comment by slook** [comment]
This warning has existed for a long time, although the exact cause is not known the bug might belong to some versions of Gtk and is triggered by Xfce (and possibly other window managers). Out of interest, what WM runs on your environment?

The only negative effect seems to be that the middle-click function is impaired (show/hide window).

**Comment by 0pLuS0** [comment]
I run Openbox 3.6.1...

Sorry, are you saying, that for the tray icon, there are 3 buttons it responds to? Left - Right - Middle click?

By the way, I use tint2 as my panel in Openbox, and in the system tray, the nicotine+ icon, I can barely make it out sitting in the tray, the color is not bright enough.

I don't know if it changes colors when you do something, or it always just stays one color, but when I first open nicotine+, take a look at this screen shot, keepassxc is the one you see, and nicotine+ is on the left, barely visible.

THANKS

![nicotine+](https://user-images.githubusercontent.com/36190223/160259699-c2228324-5daf-4f02-b7a0-5cfe5f84cc4b.jpg)

**Comment by slook** [comment]
> are you saying, that for the tray icon, there are 3 buttons it responds to? Left - Right - Middle click?

Yes correct, Left or Right button is to show the popup menu, and Middle button is supposed to toggle Show Nicotine+ / Hide Nicotine+ (Hide is beyond normal minimize, even the taskbar item is hidden aswell ala minimize-to-tray).

On Xfce, the following error message is shown in the console upon press of middle-click (slightly different from the message displayed upon load) and the show/hide function only sometimes works unreliably in a glitchy manner:
```
(org.nicotine_plus.Nicotine:15284): Gtk-CRITICAL **: 23:52:43.588: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed
```

> I'd like them to show the Default icons instead.

I don't understand why your app tray icons are grey, the default icons are supposed to be bright orange with Red/Green/Blue indicators. Your panel has rendered them like symbolic for some reason.

> pick other iconsets to use besides the Default?

There is a "Classic" icon set included in the application package in the data folder, see link:
https://github.com/nicotine-plus/nicotine-plus/tree/master/data/icons/themes/classic#readme

To date, nobody has authored any other custom icon sets for Nicotine+

**Comment by 0pLuS0** [comment]
Middle Button does nothing here.

When I start nicotine+ I get this message;

(org.nicotine_plus.Nicotine:30903): Gdk-CRITICAL **: 16:57:40.175: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

When I left or right click the system tray icon I get this message, but not middle click.

(org.nicotine_plus.Nicotine:31138): Gtk-CRITICAL **: 16:59:25.806: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed

I said before, I am using an Iconset/Theme, and I change the icons with LXAppearace, so of course, if someone chooses to use different icons in Linux, the nicotine+ system tray icon is going to be different.

SO...

I was asking before, when someone uses an iconset, do you know how to easily have nicotine+ to use the default icons instead?

THANKS

**Comment by slook** [comment]
> if someone chooses to use different icons in Linux, the nicotine+ system tray icon is going to be different.

I could be wrong, but as far as I know no such Nicotine+ icon exists within system icon themes, and the Nicotine+ icon used for the system tray is bundled within the application package. Therefore, it should remain the same no matter your system's theme.

> do you know how to easily have nicotine+ use the default icons instead?

You are already using the default Nicotine+ icon, but judging by your screenshots above it looks like LXAppearance or something on your system is badly re-rendering the tray icon into a monochrome shade.

**Comment by mathiascode** [comment]
> You are already using the default Nicotine+ icon, but judging by your screenshots above it looks like LXAppearance or something on your system is badly re-rendering the tray icon into a monochrome shade.

No, Papirus ships its own Nicotine+ icons.

@0pLuS0 Setting this as your icon theme in the Nicotine+ preferences should give you the default tray icons: 
[default.zip](https://github.com/nicotine-plus/nicotine-plus/files/8357456/default.zip)

**Comment by slook** [comment]
Sweet, that fixes the missing notification icon when running from a local Git folder :)

On my system, for this to work I had to rename the 4 files `trayicon-` to `trayicon_` (replace `-` with `_` )

**Comment by 0pLuS0** [comment]
I had to rename them too underlined as well _

THANKS

**Comment by slook** [comment]
Glad you got the icon appearance fixed :)

As to the Gdk-CRITICAL warnings, something in the tray icon implementation (possibly middle-click connect) leads to these errors, but it is unknown how many systems are affected by it since most users don't see the console output so would never know any problem exists.

**Comment by 0pLuS0** [comment]
But as I mentioned before Middle Click does nothing here, only left/right...

**Comment by mathiascode** [comment]
I'll set up some VMs and look into the issue when I have time. It would be helpful if you (@slook or @0pLuS0, or anyone else) could compare the behavior of our tray icon to other GTK apps that implement one (e.g. Deluge, Transmission or Gajim), and see if similar issues occur there.

**Comment by 0pLuS0** [comment]
I have Transmission 3.00, what do you need?

**Comment by 0pLuS0** [comment]
When I enable the System Tray icon in Transmission 3.00 I get this message when I start it;

(transmission-gtk:20318): Gdk-CRITICAL **: 16:13:25.024: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

When I left/right click on the system tray icon I'll get this message;

(transmission-gtk:20318): Gtk-CRITICAL **: 16:14:05.944: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed

By the way, I use Redshift, and I use the redshift-gtk to have a system icon/menu and when it starts it gives me a similar message;

(redshift-gtk:20508): Gdk-CRITICAL **: 16:14:58.035: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

P.S. On a side note, if anyone uses Redshift 1.12, maybe you can help me get rid of this message, fix it for Redshift? I'm anal about all these messages, I like my logs squeaky clean... LOL

https://github.com/jonls/redshift

THANKS

**Comment by slook** [comment]
In Gajim on Xfce 4.12, Left-Click does show/hide, Right-Click does context menu, Middle-Click does nothing. There are no console errors.

**Comment by mathiascode** [comment]
As far as I can tell, there's nothing we can do here. The warning seems to appear when the AppIndicator icon is displayed, and delaying this makes no difference.

**Comment by slook** [comment]
@0pLuS0 The Gdk error is gone in Nicotine+ 3.2.6.dev1 and left-click action is changed to show/hide (middle-click does nothing).
