### ISSUE TITLE
Instant crash at startup since version 3.2.1

### ISSUE THREAD

**Issue by vctls** [nicotine-plus/nicotine-plus#1974]
Nicotine+ version:  3.2.1 or 3.2.2
Operating System/Distribution:
Windows 10 21H1 build 19043.1586

### Describe the bug
Nicotine+ crashes immediately upon launch.
And I mean _instantly_. It barely registers in the task manager.
Had to rollback from 3.2.1, and I was hoping 3.2.2 to work again, but nope.
Rolled back to 3.2.0 again, and it's working fine.

### Expected behavior
No crash.

### Steps to reproduce the bug
🤷‍♂️
Haven't found a way _not_ to produce it.

### Additional context
Main window doesn't even appear. Didn't find any relevant logs.
Are there supposed to be any crash logs? Where would I find them?
This looks a lot like my previous report #893 
But I just tried to switch languages again, and it didn't fix the problem.

**Comment by mathiascode** [comment]
Probably the same as #1963

**Comment by vctls** [comment]
Ah, yes. Didn't search well enough. I'll try the suggestions mentioned there, see if it matches.

**Comment by vctls** [comment]
Since the portable version works for me too, I think it's safe to say this issue is a duplicate.

**Comment by slook** [comment]
For anyone looking at this thread, the issue is caused by the installer format has changed since Nicotine+ 3.2.0. If you are upgrading from Nicotine+ 3.1.1 or earlier, please uninstall Nicotine+ first (this will not remove your existing settings).
