### ISSUE TITLE
UnicodeEncodeError when downloading file

### ISSUE THREAD

**Issue by peterlerousx** [nicotine-plus/nicotine-plus#1980]
Nicotine+ version:  
Operating System/Distribution:

### Additional context
Screenshots, logs, stacktraces or relevant information.

Nicotine+ Version: 3.2.2
GTK Version: 3.24.33
Python Version: 3.9.9 (main, Nov 10 2011, 15:00:00) 
[GCC 11.2.0]

Type: <class 'UnicodeEncodeError'>
Value: 'latin-1' codec can't encode character '\u2019' in position 74: ordinal not in range(256)
Traceback:   File "/app/lib/python3.9/site-packages/pynicotine/pynicotine.py", line 464, in network_event
    self.events[i.__class__](i)
  File "/app/lib/python3.9/site-packages/pynicotine/pynicotine.py", line 1208, in file_download_init
    self.transfers.file_download_init(msg)
  File "/app/lib/python3.9/site-packages/pynicotine/transfers.py", line 1037, in file_download_init
    file_handle = open(incomplete_name, 'ab+')

**Comment by slook** [comment]
Thank you for your bug report @peterlerousx Please provide:

- The path and filename of the file you attempted to download before the crash
- Your system language and locale

Also, if you can edit the title of this issue to something shorter that would be much appreciated :)

**Comment by slook** [comment]
character `\u2019` is a right-hand single quotation mark (non-standard character).

` 'latin-1' codec` it should be `utf-8` ? To avoid the error, suggest on line 1037:

`                    file_handle = open(incomplete_name.encode('utf-8'), 'ab+')`
