### ISSUE TITLE
UPnP is not available on this network

### ISSUE THREAD

**Issue by peacetwo** [nicotine-plus/nicotine-plus#1981]
Nicotine+ version:  
Operating System/Distribution:
Windows 10

### Describe the bug
Port forwarding is not working even though the port is open

> 2022-04-05 18:17:49 Loading GTK 3.24.33
> 2022-04-05 18:17:49 Loading Python 3.9.10 (main, Mar 14 2022, 18:37:07)  [GCC 11.2.0 64 bit (AMD64)]
> 2022-04-05 18:17:49 Loading Nicotine+ 3.2.2
> 2022-04-05 18:17:49 Listening on port: 62523
> 2022-04-05 18:17:49 Loading plugin system
> 2022-04-05 18:17:49 Connecting to server.slsknet.org:2242
> 2022-04-05 18:17:49 Rescanning shares…
> 2022-04-05 18:17:49 202 folders found before rescan, rebuilding…
> 2022-04-05 18:17:49 Rescan complete: 202 folders found
> 2022-04-05 18:17:50 Connected to server server.slsknet.org:2242, logging in…
> 2022-04-05 18:17:51 UPnP: Failed to forward external port 62523: UPnP is not available on this network

**Comment by slook** [comment]
Please enable the "[Debug] Miscellaneous" logging category (right click log history pane > Log Categories) and post the startup log again.

**Comment by peacetwo** [comment]
> 2022-04-06 04:16:26 [Misc] Using configuration: C:\Users\Regan\AppData\Roaming\nicotine\config\config
> 2022-04-06 04:16:26 Loading GTK 3.24.33
> 2022-04-06 04:16:26 [Misc] Saved configuration: C:\Users\Regan\AppData\Roaming\nicotine\config\config
> 2022-04-06 04:16:26 Loading Python 3.9.10 (main, Mar 14 2022, 18:37:07)  [GCC 11.2.0 64 bit (AMD64)]
> 2022-04-06 04:16:26 [Misc] Using Python executable: C:\Program Files\Nicotine+\Nicotine+.exe
> 2022-04-06 04:16:26 [Misc] Using Nicotine+ executable: C:\Program Files\Nicotine+\lib\pynicotine
> 2022-04-06 04:16:26 Loading Nicotine+ 3.2.2
> 2022-04-06 04:16:26 Listening on port: 62523
> 2022-04-06 04:16:26 [Misc] Maximum number of concurrent connections (sockets): 512
> 2022-04-06 04:16:26 [Misc] UPnP: Creating Port Mapping rule...
> 2022-04-06 04:16:26 [Misc] UPnP: Discovering... delay=2 seconds
> 2022-04-06 04:16:26 Loading plugin system
> 2022-04-06 04:16:26 [Misc] Enabled plugin(s): 
> 2022-04-06 04:16:26 Connecting to server.slsknet.org:2242
> 2022-04-06 04:16:26 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
> 2022-04-06 04:16:26 [Misc] UPnP: Sent M-SEARCH IP request 1
> 2022-04-06 04:16:26 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
> 2022-04-06 04:16:26 [Misc] UPnP: Sent M-SEARCH PPP request 1
> 2022-04-06 04:16:26 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
> 2022-04-06 04:16:26 [Misc] UPnP: Sent M-SEARCH IGD request 1
> 2022-04-06 04:16:26 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
> 2022-04-06 04:16:26 [Misc] UPnP: Sent M-SEARCH IP request 2
> 2022-04-06 04:16:26 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nMAN: "ssdp:discover"\r\nMX: 2\r\n\r\n'
> 2022-04-06 04:16:26 [Misc] UPnP: Sent M-SEARCH IGD request 2
> 2022-04-06 04:16:26 Rescanning shares…
> 2022-04-06 04:16:26 202 folders found before rescan, rebuilding…
> 2022-04-06 04:16:27 Rescan complete: 205 folders found
> 2022-04-06 04:16:27 Connected to server server.slsknet.org:2242, logging in…
> 2022-04-06 04:16:28 1798 privileged users
> 2022-04-06 04:16:28 You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.
> 2022-04-06 04:16:28 [Misc] UPnP: 0 device(s) detected
> 2022-04-06 04:16:28 UPnP: Failed to forward external port 62523: UPnP is not available on this network
> 2022-04-06 04:16:28 [Misc] Traceback (most recent call last):
>   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 366, in _update_port_mapping
> RuntimeError: UPnP is not available on this network

**Comment by peacetwo** [comment]
Hello can anyone help me with this

**Comment by slook** [comment]
Yes possibly, although it might take a while as these issues are tricky to identify and resolve, as the problems are often router specific and cannot be easily replicated in other network environments.

More details may be required such as router system logs. Perhaps @mathiascode can advise what else is required to diagnose the issue?

**Comment by mathiascode** [comment]
Judging by the debug output, UPnP doesn't seem to be enabled on your router. Does UPnP work in other applications, like torrent clients?

> even though the port is open

Have you manually forwarded the port before (it appears open in the Soulseek port checking tool)? If so, you don't need UPnP.

**Comment by peacetwo** [comment]
> Judging by the debug output, UPnP doesn't seem to be enabled on your router. Does UPnP work in other applications, like torrent clients?
> 
> > even though the port is open
> 
> Have you manually forwarded the port before (it appears open in the Soulseek port checking tool)? If so, you don't need UPnP.

Ok thanks that makes sense
