### ISSUE TITLE
nicotine+ always on dark mode regardless of my settings

### ISSUE THREAD

**Issue by DanBaur** [nicotine-plus/nicotine-plus#1983]
Nicotine+ version:  3.2.2
Operating System/Distribution:
Fedora Linux 35 KDE Plasma spin

### Describe the bug
Nicotine from the moment I installed it with dnf always stays on dark mode even though I unchecked the 'prefer dark mode' box in the user interface settings.

### Expected behavior
Dark mode should only be turned on when the 'prefer dark mode' box is checked and when the box is unchecked the interface should go back to light mode

### Steps to reproduce the bug
Fresh install of nicotine+ from the default fedora repos, use a wayland session under kde, attempt to manually toggle dark mode on and off

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://user-images.githubusercontent.com/55999131/162598894-860d43f0-8b5b-4e2f-bc23-96bf8788af1a.png)

**Comment by mathiascode** [comment]
Is your system theme dark? If so, this behavior is expected. We can only ask GTK to enable the dark theme, not force the light theme.

**Comment by slook** [comment]
The OP's "system theme" is only loosely related to the GTK theme set in KDE's "GTK Configuration" settings.

It is possible to set a separate GTK theme just for GTK apps like Nicotine+, but there's a conflicting setting in KDE's "Appearance" system settings which interfere with the coloring in an unpredictable way... It is almost as bad as MS Windows' GTK implementation.

**Comment by DanBaur** [comment]
> Is your system theme dark? If so, this behavior is expected. We can only ask GTK to enable the dark theme, not force the light theme.

my system theme was in light mode as usual

**Comment by DanBaur** [comment]
> The OP's "system theme" is only loosely related to the GTK theme set in KDE's "GTK Configuration" settings.
> 
> It is possible to set a separate GTK theme just for GTK apps like Nicotine+, but there's a conflicting setting in KDE's "Appearance" system settings which interfere with the coloring in an unpredictable way... It is almost as bad as MS Windows' GTK implementation in which there is no user facing option to change the default GTK theme at all.
> 
> Implementing the suggestion in #1882 (to provide an option to use a specific GTK theme in Nicotine+) would resolve this issue for users of the affected desktop environments.

other gtk based apps don't have this problem on my system

**Comment by mathiascode** [comment]
How do other GTK applications behave on your system? I don't recall doing anything special in Nicotine+ that could cause this issue.

**Comment by DanBaur** [comment]
I don't recall ever having GUI issues on other GTK programs on my system.

**Comment by mathiascode** [comment]
I tried a fresh installation of Fedora 35 KDE Plasma Desktop, and noticed several issues with GTK themes beyond our control. Applications tested are Nicotine+ and Transmission (GTK frontend).

Selecting the "Default" theme in System Settings -> Appearance -> Application Style -> GTK Application Style:
- GTK theme is unset
- Dark mode doesn't work (if you manually change the theme to Adwaita, dark mode works)

Selecting the "Breeze" theme:
- Dark mode works when set system wide, but requires a restart of the application
- Dark mode can't be toggled inside the application

Could you start Nicotine+ with the GTK inspector by running `GTK_DEBUG=interactive nicotine`, and tell which theme is selected under Visual -> GTK theme? Could you also do this with other GTK applications, such as Transmission, Deluge and Quod Libet, and see if there are any differences?

**Comment by mathiascode** [comment]
Likely fixed in https://github.com/nicotine-plus/nicotine-plus/commit/dedf20bd37fa6cdc74d688992cb240914490dc36

**Comment by mathiascode** [comment]
The fix will be included in 3.2.3: https://github.com/nicotine-plus/nicotine-plus/issues/1991
