### ISSUE TITLE
Add toggles for global upload/download speed limits to the status bar

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1987]
### Describe the solution you'd like
We currently have a button to toggle both the *alternative* upload and download speed limits from the status bar, but individual ones for the non-alternate up and down speed limits (which I'll call the global limits) could be useful too.

Here are some scenarios with example solutions:
- Want to download something quickly but not increase the upload speeds? Disable the alternate speeds if enabled and then disable the global down limit if set, leaving only the global up limit enabled.
- Want Nicotine+ to run in the background and have no perceptible effect on general internet usage? Enable the alternate speeds.
- Want to maximise Nicotine's up/down bandwidth but still be able to do basic internet activities such as read webpages? Disable the alternate speeds if enabled and then enable both the up and down global limits (which you've previously already set to, for example, a value 85% of your maximum).
- Want to upload and download at max speeds? Disable the alternate speeds if enabled and both global limits.

Three of these cases require using the Preferences, and specifically when dealing with the global down limit, it's required to memorise a value 85% of your download bandwidth so that you can temporarily set it to 0 (this is because the global down limit doesn't have a toggle checkbox unlike the global up limit for some reason, if it did, memorisation wouldn't be necessary). As a side note, it's not obvious to novice users that 0 = unlimited so the tooltips should explain this.

If the down and up speed readouts in the status bar had a toggle button next to each to control whether each is being globally limited, then the scenarios presented above could be easily handled via the main UI without needing to visit the preferences or memorising previous values.

So in total there'd be three toggles, two for the global up and down limits and one for toggling the alternate speeds. A nice touch would be to append the text "[### KiB/s]" to the up/down readouts when any limits are in effect to easily see how limited the bandwidth is.

Too over-engineered, or actually useful? I'm thinking the latter right now.

Thanks!

Nicotine+ 3.2.2

**Comment by mathiascode** [comment]
General note about the status bar: You should be really careful about adding new toggles, text in square brackets and whatnot. There's limited space available in the status bar, making it challenging to add widgets that the average user understands. We don't want a bunch of people toggling things by mistake, not understanding what happened, and leaving things toggled on.

**Comment by redactedscribe** [comment]
> add widgets that the average user understands

Totally agree, but in this case, if the default values Nicotine+ ships with for global limits are 0, then toggling the proposed buttons by mistake wouldn't have any effect.

> We don't want a bunch of people toggling things by mistake

True, but I'd also argue users would likely figure out what's going on if their connection seemed limited because they would've had to set a value other than 0 via the Preferences in the first place.

You have fair points though, maybe there's a better way, or maybe this is just a feature that complicates things too much. Depends on the computer literacy of the average Nicotine+ user. I do think more upfront control over the bandwidth would be appreciated in a sharing client, but I could be biased after years of torrent client use which is arguably more complex software on average.

**Comment by slook** [comment]
The button widgets which display the speeds currently do not have very useful click actions (on click they simply open the 'Downloads' or 'Uploads' preferences pages).

A better use for them might well be to individually toggle the alternative speeds, provided that clear visual feedback somehow indicates their state (perhaps by using different/additional icons and/or bold colorization of widget background and/or text).

> We don't want a bunch of people ... leaving things toggled on.

Good point, to avoid this issue perhaps the state of the alternative speed limiters doesn't and shouldn't be remembered across sessions, such that upon each application startup the normal speed limits are in effect by default.

**Comment by mathiascode** [comment]
What do you think about this? It's in the preferences dialog, but could also be added to a popover that shows when pressing the download/upload status buttons in the status bar.

![](https://user-images.githubusercontent.com/8754153/204617445-3538984c-8a02-4c3a-a01b-f68473ddd0b0.png)

**Comment by mathiascode** [comment]
A popover would look like this:

![](https://user-images.githubusercontent.com/8754153/204620311-287da2a4-a77b-4a9b-8f7e-7e0a6a85356c.png)

**Comment by slook** [comment]
+1 Really nice.

That does remove the need for the `<<` button as well.

Also the similar popover idea can be used for the result counter button "Limit number of results per search:" setting.
