### ISSUE TITLE
Some users unable to access my files and they are seeing the "Remote File Not Shared" message

### ISSUE THREAD

**Issue by Earthbound1** [nicotine-plus/nicotine-plus#1988]
Nicotine+ version:  
Operating System/Distribution:
MacOs Monterey 12.2.1
Nicotine+ 3.2.2

### Describe the bug
Some users report that they are unable to access my files and are seeing the  "Remote File Not Shared" message. However I have not unshared my files with anybody and many users are still able to download from me.
### Expected behavior
Users should have no trouble downloading from em because I have not unshared my files 

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Most likely the same as https://github.com/nicotine-plus/nicotine-plus/issues/1827#issuecomment-1013546287

Could you enable transfer logging (Right-click the log pane -> Log Categories -> Enable "Transfers"), and verify if this is the case?

**Comment by Earthbound1** [comment]
My MacBook Pro is being repaired right now. I will do as you suggest just
as soon as I have it back and let you know what I find out.
Thanks for responding to my post.

**Comment by Earthbound1** [comment]
I got my Macbook Pro back from the repair shop and added "Transfers" to the
log categories as you suggested. But now I have another much worse problem.
I am able to search and download from others but no one is able to download
from me.
My HD was repartitioned so I had to reinstall Nicotine+. Now the previous
Port Forward settings (which used to work) no longer work.

Now I get the message:

Failed to forward external port 50000: Failed to map the external WAN port:
Error code 718: ConflictInMappingEntry

This makes no sense to me because it's the same laptop on the same network
with the same Port Forward settings as before (which used to work) and now
it no longer works and I have no idea how to fix it.

**Comment by slook** [comment]
@Earthbound1 are you still using Nicotine+ on your MacBook? If so we'd appreciate some testing on a recent version. You can install the [stable version](https://nicotine-plus.org/doc/DOWNLOADS.html#macos) or the [latest testing build](https://nicotine-plus.org/doc/TESTING.html#macos). Please let us know if everything is working as it should.
