### ISSUE TITLE
TODO-list for version 3.2.3

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#1991]
Prepare a minor release 3.2.3 while work continues on 3.3.0. The release date for 3.2.3 will likely be in May.

Things to include:
- Fix for issue where theme is always dark on newer distros with Freedesktop color scheme support: dedf20bd37fa6cdc74d688992cb240914490dc36
- Proper file attribute parsing for protocol messages
- Only display images in image chooser
- Various minor GUI-related bug fixes
- Nicotine+ icon tweaks
- Minor documentation updates
- Apply minor translation fixes (but no new languages)
- Anything else?

**Comment by slook** [comment]
+ Fix issue #2004 to finish off https://github.com/nicotine-plus/nicotine-plus/commit/b64dc6e97427c38a699676ba9e9d135f561bbe3b

**Comment by mathiascode** [comment]
I believe this is ready now. We just need release notes and perhaps a few more days of testing the 3.2.x branch.

**Comment by hboetes** [comment]
I've added a note to https://hosted.weblate.org/projects/nicotine-plus/nicotine-plus/ , so our translators have the chance to fix the latest translation changes.

**Comment by mathiascode** [comment]
@M0Rf30 @uniss2209 There's time until May 31 to complete the Italian and Ukrainian translations for 3.2.3, if you are interested.

**Comment by M0Rf30** [comment]
OK, got it. I'll submit in these days

**Comment by uniss2209** [comment]
Done

**Comment by hboetes** [comment]
Thanks for all your hard work. I'm so happy we've got **11** completely translated languages for our project.

**Comment by mathiascode** [comment]
Anything I forgot, or are we ready to ship?
