### ISSUE TITLE
Connect without UPnP or port forwarding - is this possible?

### ISSUE THREAD

**Issue by ctp9** [nicotine-plus/nicotine-plus#1996]
As the title states - is there any way to make Nicotine+ work without opening ports and/or using UPnP? SoulseekQt works that way - no open ports required, UPnP disabled... and it still connects, returns search results, is able to download and upload files without any issues...

The reason for not opening ports and not using UPnP is due to security concerns. I'm on a network where such actions are restricted, and as a result, Nicotine+ is rendered useless.

**Comment by mathiascode** [comment]
What is your operating system? Connections to users with open ports should still work, so you should be able to connect to approximately half of the users on the network. Nicotine+ handles connections the same way as SoulseekQt, so something seems to be wrong on your end. Can you enable debug logging, capture some logs from trying to perform searches etc, and send the logs to my email (see my GitHub  profile)?

To enable debug logging: Menu -> View -> Show Log Pane, then right click the log pane -> Log Categories -> Enable "Connections" "Messages" and "Transfers"

**Comment by ctp9** [comment]
Update:

It seems to be working now as intended. Perhaps the socket or port was still in use when I exited SoulseekQt right before launching Nicotine+ yesterday for the first time.

Today I opened it again (Soulseek wasn't running prior) - and voila - it works. (I have to migrate some of my settings now between the two clients.)

Thanks for your suggestions.
