### ISSUE TITLE
Log says port 2234 is successfully forwarded to local IP address. "Check Port Status" says port 2234 is closed.

### ISSUE THREAD

**Issue by Earthbound1** [nicotine-plus/nicotine-plus#1999]
Nicotine+ version:  
Operating System/Distribution:
MacOS Monterey 12.3.1
Nicotine+ 3.2.2  •  GTK 3.24.33

### Describe the bug
Log says port 2234 is successfully forwarded to local IP address. "Check Port Status" says port 2234 is closed.

### Expected behavior
Log and Port Status should say the same thing.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Have you successfully forwarded other ports in the past? If not, it could be the case that your public IP address is shared with others, and your ISP doesn't forward ports (CGNAT). Some ISPs may provide a static IP address for an additional fee, but if you're on e.g. mobile broadband, a VPN is the only good option.

**Comment by Earthbound1** [comment]
Yes. I have successfully forwarded other ports in the past. In fact yesterday I successfully forwarded ports and this was confirmed by both the log and Port Status. But today, although, I have made no changes, Port Status says port 2234 is closed.

**Comment by slook** [comment]
It's likely this is some firewall issue.

There is a security feature of some routers that have a stored route for a particular machine, that if something significant about that machine changes (such as a new OS install or hardware upgrade for example), then your router can get scared and think the network adapter is being cloned or something like that.

To remedy such an issue, it is often necessary to completely remove the stored port forwarding settings and clear all DNS caches, fully-restart all network adapters (several times), then create the rule from fresh.

**Comment by Earthbound1** [comment]
What happened was that my HD was reformatted. After that my old port forward settings no longer worked and I had to, as you said, remove the stored port forward settings and use different ports. That worked for a day. I don't know how to clear DNS caches. I have some research to do.

**Comment by Earthbound1** [comment]
Looks like the DNS caches are on the Macbook's HD. Which means it was already cleared when the HD was reformatted a few days ago.

Also I just opened Nicotine+ and checked the Port Status. It says:

"Port: 2234/tcp open. Your router and Soulseek client is configured correctly."

Not sure what to make of it.

**Comment by Earthbound1** [comment]
I think (I hope) I found the problem. My Macbook was automatically joining another wifi network. I did not know about (until now).

Thank you for your help.
