### ISSUE TITLE
[nightly] can't connect

### ISSUE THREAD

**Issue by dchmelik** [nicotine-plus/nicotine-plus#2002]
Nicotine+ version: nicotine+-20220426-201163d-x86_64-1_SBo (manually increased SlackBuild version)
Operating System/Distribution: Slackware64 15.1-current

### Describe the bug
Cannot connect to server server.slsknet.org:2242: Timed out.

### Expected behavior
Connect.

### Steps to reproduce the bug
Switch from regular SoulSeek or stable Nicotine+ (both connect fine) to nightly Nicotine+.

### Additional context
Keeps increasing wait to reconnect; never connects (left on 1+hrs)

**Comment by dchmelik** [comment]
Apparently it does eventually connect, just takes much longer than regular SoulSeek and stable Nicotine+.

**Comment by mathiascode** [comment]
Might have been a temporary ban from the server. Nothing has changed in the networking code since the latest stable release.
