### ISSUE TITLE
chat rooms go out of order and names disappear and walls seem inacessible

### ISSUE THREAD

**Issue by dchmelik** [nicotine-plus/nicotine-plus#2003]
Nicotine+ version: nicotine+-20220426-201163d-x86_64-1_SBo (manually increased SlackBuild version)
Operating System/Distribution: Slackware64 15.1-current GNU/Linux

### Describe the bug
When I join more rooms than fit screen and move through list, some room names disappear in their tabs and tabs get moved out of the order I put them in.  Also in regular SoulSeek chat rooms have a second area called wall--permanent message screen.

### Expected behavior
Redraw names and save user's order.

### Steps to reproduce the bug
Join more rooms than fit on page and move through.

**Comment by mathiascode** [comment]
Is this what you're seeing? I can reproduce an issue with misplaced tab labels, but only when the tab bar is vertical and I scroll up. The tab order doesn't seem to change on my end.

![](https://user-images.githubusercontent.com/8754153/165509288-ca22226c-ae61-4c19-953a-310efdb2ead8.png)

**Comment by mathiascode** [comment]
Seems to have disappeared this time after scrolling down.

![](https://user-images.githubusercontent.com/8754153/165510391-4bd455ac-d28e-49ec-a927-fb4a371631ab.png)

**Comment by dchmelik** [comment]
No; my rooms are horizontal but I want them vertical (I can probably find the setting) but I guess you found that of the two issues...

**Comment by mathiascode** [comment]
The bug seems worse in GTK 4 than GTK 3. In GTK 3, a tab occasionally moves out of order when alternating between presses on the left and right scroll button, but it seems to happen on every press in GTK 4.

I'll check if this is something we can work around, or if it requires a fix in GTK.

**Comment by mathiascode** [comment]
This bug needs to be fixed in GTK, but I've implemented mouse wheel scrolling on the tab bar, which should be more convenient: https://github.com/nicotine-plus/nicotine-plus/commit/70260a763d0a2eeab7b40b3145f23935962cc0a0

There's a button for the room wall next to the text entry.

**Comment by slook** [comment]
> walls seem inacessible

Agreed, many users do not seem to know about the feature until somebody explains it.

> There's a button for the room wall next to the text entry.

Suggest moving into the Users container and giving it a label, also Alt+W key mnemonic:

![image](https://user-images.githubusercontent.com/88614182/166616084-48914d0d-9918-473f-b3a9-bf8ff47b8b1a.png)
