### ISSUE TITLE
crash on connecting 

### ISSUE THREAD

**Issue by AradiaIsStupid** [nicotine-plus/nicotine-plus#2006]
Nicotine+ version:  3.3.0.dev1
Operating System/Distribution:
Arch Linux 

### Describe the bug
crash on connecting, same happened with the pip and the official repo and AUR versions 
### Additional context
Screenshots, logs, stacktraces or relevant information.
```py
Type: <class 'TypeError'>
Value: could not get a reference to type class
Traceback:   File "/home/aradia/gitshit/nicotine-plus/pynicotine/pynicotine.py", line 458, in network_event
    self.events[i.__class__](i)
  File "/home/aradia/gitshit/nicotine-plus/pynicotine/pynicotine.py", line 683, in join_room
    self.chatrooms.join_room(msg)
  File "/home/aradia/gitshit/nicotine-plus/pynicotine/chatrooms.py", line 173, in join_room
    self.ui_callback.join_room(msg)
  File "/home/aradia/gitshit/nicotine-plus/pynicotine/gtkgui/chatrooms.py", line 173, in join_room
    self.pages[msg.room] = tab = ChatRoom(self, msg.room, msg.users)
  File "/home/aradia/gitshit/nicotine-plus/pynicotine/gtkgui/chatrooms.py", line 414, in __init__
    ChatEntry(self.frame, self.chat_entry, chatrooms.completion, room, slskmessages.SayChatroom,
  File "/home/aradia/gitshit/nicotine-plus/pynicotine/gtkgui/widgets/textentry.py", line 66, in __init__
    self.frame.init_spell_checker()
  File "/home/aradia/gitshit/nicotine-plus/pynicotine/gtkgui/frame.py", line 436, in init_spell_checker
    self.spell_checker = Gspell.Checker()
```
on the verbose log when opened using the terminal it shows

```bash
** (org.nicotine_plus.Nicotine:11718): WARNING **: 06:25:07.789: Failed to load shared library 'libgspell-1.so.2' referenced by the typelib: libicuuc.so.71: cannot open shared object file: No such file or directory
/home/aradia/gitshit/nicotine-plus/pynicotine/gtkgui/frame.py:436: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.spell_checker = Gspell.Checker()
```

**Comment by mathiascode** [comment]
`Failed to load shared library 'libgspell-1.so.2' referenced by the typelib: libicuuc.so.71: cannot open shared object file: No such file or directory`

Looks like someone recently updated the `gspell` Arch package to version 1.10.0, but forgot to specify a new dependency. You need to install the `icu` package in order to make `gspell` work again.

**Comment by mathiascode** [comment]
Reported downstream: https://bugs.archlinux.org/task/74619

**Comment by Scimmia22** [comment]
@AradiaIsStupid, if this is actually Arch, partial updates are not supported. There's almost no way you'd have gtk3 without icu, so you must be doing partial updates.

**Comment by mathiascode** [comment]
@Scimmia22 Thanks, that's more likely to be the case.

Since there's nothing to do on our end, I'll close this issue. @AradiaIsStupid let us know if the issue still occurs after updating all your packages.
