### ISSUE TITLE
Nicotine+ not running in background

### ISSUE THREAD

**Issue by Earthbound1** [nicotine-plus/nicotine-plus#2008]
Nicotine+ version:  3.2.2  •  GTK 3.24.33

Operating System/Distribution: macOS Monterey 12.3.1

### Describe the bug 

If I am not actively using Nicotine+, after an hour or so downloads and uploads cease completely.

At first I thought it was related to the setting "Use UPnP to forward listening port (interval in hours)" because network inactivity seemed to happen at about the same time the message "failed to forward port" appeared. So I changed that setting from 4 hours to 0 hours. I no longer see the "failed to forward port message" but uploads and downloads still stop after a period of time if I am not actively using Nicotine+.
I also tried setting "Toggle away status after minutes of inactivity" to 10000, but the problem continues to happen.

### Expected behavior

Network activity should continue when Nicotine+ is (supposed to be) running in the background)

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Maybe related to #1997

- Do connections to other users still work (requesting user info, browsing shares etc)?
- Which status are the transfers stuck on? If you attempt to resume the transfer, does the status change at all (e.g. to "Getting status", "Cannot connect" or similar)?
- Can you enable debug logging, attempt to connect to users and pause/resume transfers, and send the log to my email (show the log pane Ctrl+L -> right-click it -> log categories -> enable "downloads", "uploads", "connections", "messages" and "transfers")?

Related to the "failed to forward port" message, I thought you found the cause in your previous bug report? Was this not the case after all? https://github.com/nicotine-plus/nicotine-plus/issues/1999#issuecomment-1109119669

**Comment by Earthbound1** [comment]
I have never tried to request user info or browse shares while Nicotine+ appears to be inactive so I have no answer to your first question. 

Transfers are stuck on either "Cannot connect" or "transferring" (with no movement).

I have emailed the log as you requested. 

Yes. If I put a number in "Use UpNP to forward listening port (interval in hours)" I will see the message "failed to forward port". But when I check ports they are still open and configured correctly.

**Comment by Earthbound1** [comment]
A couple of days ago I changed the setting "Turn Display Off After . . ." to "Never". Since then activity on Nicotine+ has been uninterrupted. Problem solved.
