### ISSUE TITLE
Nicotine+ window maximized blocks the start bar

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2009]
Nicotine+ version:  3.3.0.dev1  •  GTK 4.6.2
Operating System/Distribution: Windows 11

### Describe the bug
When Nicotine+ window is maximized I cannot access my hidden start bar

### Expected behavior
When moving cursor to the bottom of the screen start bar should pop up

### Steps to reproduce the bug
Maximize Nicotine+ window and move cursor to the bottom of the screen

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Thanks for the report @woollarding , please can you verify whether or not the same behaviour occurs with other apps using GTK4 on Windows, that is if you know of any?

**Comment by woollarding** [comment]
I don't know any.. but of another window like a web browser is in front and
nicotine is still behind, the start bar still won't pop up.. sorry I can't
be more of a help

**Comment by slook** [comment]
That's okay I don't know of any either!

It is likely this bug belongs to GTK upstream and needs reporting to them, or otherwise we require some sort of hack.

Pressing the 'Windows Logo' key should work around the issue for now.

**Comment by woollarding** [comment]
It does

**Comment by mathiascode** [comment]
I'm pretty sure we're one of the first larger applications testing GTK 4 on Windows.

I've seen a GTK issue where the window shadow acts like a clickable part of the window, and my guess is that it's obstructing the area that triggers the taskbar. I'll see if I can reproduce it when I have time.

**Comment by woollarding** [comment]
Cool, thanks!

**Comment by mathiascode** [comment]
Closing in favor of #2014
