### ISSUE TITLE
Add support for >2GB downloads

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#201]
Support for large files was added to SoulseekQt in 2015, but parsing a TransferRequest response in Nicotine+ only returns 0 as the filesize for large files. Investigate what the official client does different.

Edit: Should also check if Museek+ supports large downloads.

**Comment by mathiascode** [comment]
It is worth noting that large uploads seem to work just fine (tested with 16GB file).

**Comment by mathiascode** [comment]
The only work left to do is to is to figure out why large downloads from SoulseekQt clients return a file size of 0. >2GB file transfers between Nicotine+ clients and uploads to SoulseekQt clients will work fine when Nicotine+ 2.0.0 is released.

**Comment by mathiascode** [comment]
Fully supported in https://github.com/Nicotine-Plus/nicotine-plus/pull/328, we just ignore the invalid file size sent by SoulseekQt.

**Comment by kiplingw** [comment]
My guess is it probably involves a primitive whose width is too small to represent the value.

**Comment by mathiascode** [comment]
What's also curious is that Nicotine+ correctly shows the size of >2GB files in search results, while SoulseekQt shows no size. SoulseekQt shows the correct size if you browse a user share though. :P

**Comment by mathiascode** [comment]
Heh, now I realized that someone already came up with the same workaround in Museekd. https://github.com/eLvErDe/museek-plus/commit/fd12d21fab814345660dcd35b62945c40cd5e1eb
