### ISSUE TITLE
Flashing Window

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2010]
Nicotine+ version:  3.3.0.dev1  •  GTK 4.6.2
Operating System/Distribution: Windows 11

### Describe the bug
When clicking tabs or right clicking on the Nicotine+ window the screen flashes. also when right clicking in the debug window the pop up menu is out of place 

### Expected behavior
Not flashing. Right click menu in debug in the location where the right click took place

### Steps to reproduce the bug
Right click

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Does the same behaviour occur when CSD (Client Side Decorations) are disabled in Menu > View > Use Header Bar > Off ?

**Comment by woollarding** [comment]
Yes I don't use the header bar

**Comment by slook** [comment]
Perhaps the window flashing is caused here:

https://github.com/nicotine-plus/nicotine-plus/blob/70260a763d0a2eeab7b40b3145f23935962cc0a0/pynicotine/gtkgui/frame.py#L1278-L1281

Maybe it makes more sense to `show` _then_ `hide`, or perhaps this optimization is not possible if platform is Windows with GTK4.

**Comment by mathiascode** [comment]
Unlikely to be an issue in Nicotine+, since GTK 3 worked fine. Probably another GTK 4 regression on Windows that I'll have to look into.

**Comment by woollarding** [comment]
Ok, thanks.

**Comment by mathiascode** [comment]
I can reproduce the issue with the misaligned context menu, but not the flashing. Could you get a screen recording that captures the flashing? What's your graphics card?

**Comment by woollarding** [comment]
moving house,, ill see what i can do next week

**Comment by slook** [comment]
Clearly GTK 4 support on Windows requires further testing.

@woollarding I hope your house move went okay :) When you have the time further [testing of latest master](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) would be appreciated. Please note that currently, GTK 3 is the default, to force GTK 4 run with:

`./NICOTINE_GTK_VERSION=4 nicotine`

**Comment by slook** [comment]
Closing in favour of #2014.

Please feel free to re-open if the visual glitching still persists in the latest master and you are able to test this further.

**Comment by mathiascode** [comment]
> also when right clicking in the debug window the pop up menu is out of place

Fixed in 44ca03d21985d66308813a31f6a2381645a825c0
