### ISSUE TITLE
Copy and Paste acting weird 

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2011]
Nicotine+ version:  3.3.0.dev1  •  GTK 4.6.2
Operating System/Distribution: Windows 11

### Describe the bug
After pasting copied text into a dialog box and hitting enter, text doesn't post, its like the selection moves to right one and pops up menu 

### Expected behavior
Posting text when pasting and hitting enter

### Steps to reproduce the bug
paste into a dialog and hit enter

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Which dialog box, do you mean something like "Upload Files To User" or "Add User Note"?

**Comment by woollarding** [comment]
Chat, either where type to send a message or enter username and a few
others but now that I'm trying to recreate that it's not happening hah I'll
keep an eye on it

**Comment by slook** [comment]
Ah cool, you mean the "TextEntry" widgets, and not "dialog box", thanks for clarifying.

Do the Result Filters text entry boxes filter the search results when pressing Enter?

**Comment by woollarding** [comment]
Yes the filters seem to work

**Comment by slook** [comment]
Check your Keyboard Accessibility settings, maybe it's possible you had inadvertently enables Sticky Keys (by pressing Shift 5 times or something stupid like that). You can disable those shortcuts in the Windows Control Panel.

**Comment by mathiascode** [comment]
Likely a GTK 4 regression on Windows.

**Comment by woollarding** [comment]
Hmm ok it just didi it again, when I pasted in a chat it popped up the
private chat command help window ... I have not really been using my. Linux
laptop much but I'll try it on there soon

**Comment by mathiascode** [comment]
Sorry, I didn't read your issue correctly last time. This also seems to happen on Linux, the widget focus moves to the next widget in the chain for some reason.

**Comment by mathiascode** [comment]
Closing in favor of #2014

**Comment by woollarding** [comment]
Sticky was off
