### ISSUE TITLE
List of GTK-related issues and deprecations

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#2014]
Note: Upstream reports need minimal reproducers, e.g. instructions for reproducing the issue in gtk-demo/gtk-widget-factory, or a small .ui file or Python application

### GTK 4

- No support for spell checking
  - Affected platforms: Linux
  - Upstream report: https://gitlab.gnome.org/GNOME/gtk/-/issues/3814
  - Support is planned in GTK 4, but will probably not be implemented soon
  - Gspell has a WIP GTK 4 port, but we need support for GtkEntry: https://gitlab.gnome.org/GNOME/gspell/-/merge_requests/8

## Deprecations

- [x] Gtk.Assistant -> Gtk.Window 
- [x] Gtk.FileChooserNative -> Gtk.FileDialog
- [x] Gtk.Dialog -> Gtk.Window
- [x] Gtk.Widget.show/hide() -> Gtk.Widget.set_visible()
- [x] Gtk.StyleContext
- [x] Gtk.ColorButton -> Gtk.ColorDialogButton
- [x] Gtk.FontButton -> Gtk.FontDialogButton
- [x] Gtk.CssProvider.load_from_data() -> Gtk.CssProvider.load_from_bytes()
- [x] Gtk.ComboBox -> Gtk.Entry + Gtk.DropDown
- [x] Gtk.InfoBar -> Gtk.Box
- [x] Gtk.MessageDialog -> Gtk.Window
- [ ] Gtk.TreeView -> Gtk.ColumnView
- [ ] Gtk.EntryCompletion -> ?

### Uncertain Future

- Gtk.Notebook

**Comment by mathiascode** [comment]
Most of the Windows-exclusive issues should be fixed once https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4252 is merged.

**Comment by AtticFinder65536** [comment]
When I press enter to enter a search query in someone's share list when using GTK 4.6.5 (from Arch 1:4.6.5-1) (libadwaita or not), the tree view does not jump to the folder. Instead, it just jumps down the page a little bit like when you press space on a long web page. Then if you do it enough times the behaviour is a little bit weird in a way I can't describe well. Otherwise, it works well but I had to switch back because of this. Also, I needed to check "Prefer Dark Mode" to get a dark mode in libadwaita (I have Adwaita-dark set as my GTK theme), that might just be the expected behaviour and the theming system might be a little different in libadwaita, I didn't look into it.

**Comment by mathiascode** [comment]
> When I press enter to enter a search query in someone's share list when using GTK 4.6.5 (from Arch 1:4.6.5-1) (libadwaita or not), the tree view does not jump to the folder. Instead, it just jumps down the page a little bit like when you press space on a long web page. Then if you do it enough times the behaviour is a little bit weird in a way I can't describe well.

I believe there was an issue report related to this for GTK 4. I'll have to check if there's a workaround, but the long-term solution is to stop using the unmaintained GtkTreeView widget in favor of GtkColumnView.



> Also, I needed to check "Prefer Dark Mode" to get a dark mode in libadwaita (I have Adwaita-dark set as my GTK theme), that might just be the expected behaviour and the theming system might be a little different in libadwaita, I didn't look into it.

Libadwaita uses a new Freedesktop color scheme spec, which is only available in recent GNOME and KDE releases afaik.

**Comment by mathiascode** [comment]
@AtticFinder65536 I came up with a workaround for the scrolling issue in 92f985984b873a552814e644f72a7203dd9da414

**Comment by mathiascode** [comment]
> @AtticFinder65536 I came up with a workaround for the scrolling issue in [92f9859](https://github.com/nicotine-plus/nicotine-plus/commit/92f985984b873a552814e644f72a7203dd9da414)

Upstream fix submitted in https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4940

**Comment by mathiascode** [comment]
The new tray icon implementation compatible with GTK 4 is done. I've also done some work in the past two months to fix a few bugs in GTK 4, and we've almost reached parity with GTK 3!

Things left to do before we can consider making the GTK 4 version of Nicotine+ the default:
- Reintroduce tray icon support on Windows (StatusNotifierItem does not exist there)
- Fix broken window decorations on Windows: https://gitlab.gnome.org/GNOME/gtk/-/issues/5142

**Comment by slook** [comment]
> No support for tray icons
> 
> - Affected GTK versions: 4
> - Find an alternative to GtkStatusIcon? (use Windows API directly?)

Interacting with the Windows API poses complicated security implications that increase the attack surface of the program, a direct implementation from the core would not be justifiable for a non-essential feature in my opinion.

I believe it is (was?) best practice for Windows applications to package a separate tray icon applet executable which runs as a separate process. Often these serve(d) as a launcher type arrangement which is capable of nothing more than spawning/activating the main process and allowing only a limited subset of defined signals from it, in order to avoid having the main process be the host for the applet.

**Comment by mathiascode** [comment]
> Interacting with the Windows API poses complicated security implications that increase the attack surface of the program, a direct implementation from the core would not be justifiable for a non-essential feature in my opinion.

Do you have any concrete examples? I don't see how a tray icon with a simple menu and a few callbacks could cause many issues.

In any case, the notification bubbles currently depend on the tray icon, so it will probably have to remain in the core: https://github.com/nicotine-plus/nicotine-plus/blob/e98a3a51255d05caf0010650c4c46ad1ab1bb895/pynicotine/gtkgui/widgets/notifications.py#L133-L208

I haven't explored alternatives for implementing a tray icon on Windows yet, though, so it's all up in the air right now.

**Comment by slook** [comment]
> Do you have any concrete examples?

Nothing specific. Reading any of the Windows security updates KB's gives an idea of the scale of the problem.

- [ClamAV for Windows](https://clamwin.com/) (I've not tried it) seems to have a tray module:
https://github.com/clamwin/clamwin/blob/master/py/ClamTray.py
https://github.com/clamwin/clamwin/blob/master/py/Utils.py#L84

**Comment by critkitten** [comment]
Is the following error related to `Popover cannot be closed after opening a child popover`? 


```
Nicotine+ Version: 3.3.0.dev5
GTK Version: 4.10.4
Python Version: 3.11.3 (linux)

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'get_focusable'
Traceback:   File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/widgets/window.py", line 96, in on_popover_closed
    if focus_widget.get_focusable():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by slook** [comment]
If the action which leads to the error is as described in #2539 , then yes.

**Comment by mathiascode** [comment]
@critkitten What did you do to get the error?

**Comment by mathiascode** [comment]
For lack of a better place to write this, I plan on supporting GTK 3 for about two more years, possibly three depending on how much demand there is once we reach that point.

**Comment by mathiascode** [comment]
Ubuntu 22.04 (LTS) is finally upgrading from GTK 4.6.6 to 4.6.9, so I'm going to support GTK 4.6.9 in Nicotine+ once again (assuming we don't run into major issues that require 4.8).

**Comment by mathiascode** [comment]
Once https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6052 is merged and a new GTK release is tagged, our GTK 4 Windows builds should be on par with GTK 3 (i.e. no longer blocking a Nicotine+ 3.3.0 release).

macOS has not been tested to the same extent yet, I need to reserve time for that.

**Comment by clawth0rne** [comment]
Regarding the spell checking, you can use libspelling as an alternative to gspell.

https://gitlab.gnome.org/chergert/libspelling

**Comment by mathiascode** [comment]
A bunch of issues were recently fixed in GTK (and Nicotine+ 3.3.3rc2 as a result):
- Cannot click taskbar icon to minimize application
- Missing Super+M shortcut to minimize window
- Nicotine+ window popping up unexpectedly when opening other programs

https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7072

**Comment by DeathStalker77** [comment]
@mathiascode @slook - Been away for a while, just wondering how things are progressing with the GTK4 TreeView issues?  Thanks for all the work you do!  🥇 

--- DS

**Comment by mathiascode** [comment]
Work on porting to Gtk.ColumnView hasn't started yet. Right now we're only doing bug fixes for Nicotine+ 3.3.x to get it in great shape, development on 3.4.x will start sometime later this year.

**Comment by francisuk1989** [comment]
@mathiascode 

Do you know if there issue with KDE Plasma 6 with GTK 4.14.4?

In alpine linux, i get theses errors

nicotine
```
05/27/24 23:43:15] Loading Python 3.12.3
[05/27/24 23:43:15] Loading Nicotine+ 3.3.4
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
[05/27/24 23:43:15] Loading GTK 4.14.4

(org.nicotine_plus.Nicotine:2950): Gtk-WARNING **: 23:43:15.537: Unknown key gtk-modules in /home/francis/.config/gtk-4.0/settings.ini
[05/27/24 23:43:15] Loading plugin system
[05/27/24 23:43:15] Loaded plugin Nicotine+ Commands
[05/27/24 23:43:15] You need to specify a username and password before connecting…
Couldn't open libGLESv2.so.2: Error loading shared library libGLESv2.so.2: No such file or directory
Fatal Python error: Aborted

Thread 0x00007f7c61c10b38 (most recent call first):
  File "/usr/lib/python3.12/site-packages/pynicotine/shares.py", line 1003 in process_scanner_messages
  File "/usr/lib/python3.12/site-packages/pynicotine/shares.py", line 1083 in _process_scanner
  File "/usr/lib/python3.12/threading.py", line 1010 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x00007f7c61f5cb38 (most recent call first):
  File "/usr/lib/python3.12/site-packages/pynicotine/slskproto.py", line 2697 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x00007f7c62162b38 (most recent call first):
  File "/usr/lib/python3.12/site-packages/pynicotine/cli.py", line 54 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x00007f7c74c3fb38 (most recent call first):
  File "/usr/lib/python3.12/site-packages/pynicotine/events.py", line 330 in _run_scheduler
  File "/usr/lib/python3.12/threading.py", line 1010 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Current thread 0x00007f7c75c76b28 (most recent call first):
  File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/widgets/window.py", line 78 in present
  File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/application.py", line 1008 in on_activate
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 42 in run
  File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/application.py", line 112 in run
  File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/__init__.py", line 156 in run
  File "/usr/lib/python3.12/site-packages/pynicotine/__init__.py", line 224 in run
  File "/usr/bin/nicotine", line 35 in load_module
  File "/usr/bin/nicotine", line 39 in <module>
Extension modules: gi._gi (total: 1)
Aborted
```

**Comment by mathiascode** [comment]
> Couldn't open libGLESv2.so.2: Error loading shared library libGLESv2.so.2: No such file or directory

Perhaps try installing the `mesa-gles` package.

**Comment by francisuk1989** [comment]
> mesa-gles

Works nicely, The GUI opens up however there is a warning.

`(org.nicotine_plus.Nicotine:3176): Gtk-WARNING **: 17:55:38.223: Unknown key gtk-modules in /home/kittydoodoo/.config/gtk-4.0/settings.ini`

~ $ nicotine
```
[05/28/24 17:55:37] Loading Python 3.12.3
[05/28/24 17:55:37] Loading Nicotine+ 3.3.4
libEGL warning: DRI2: failed to authenticate MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
[05/28/24 17:55:38] Loading GTK 4.14.4

(org.nicotine_plus.Nicotine:3176): Gtk-WARNING **: 17:55:38.223: Unknown key gtk-modules in /home/francis/.config/gtk-4.0/settings.ini
[05/28/24 17:55:38] Loading plugin system
[05/28/24 17:55:38] Loaded plugin Nicotine+ Commands
[05/28/24 17:55:38] You need to specify a username and password before connecting…
[05/28/24 17:55:57] Quitting Nicotine+ 3.3.4, application closing…
[05/28/24 17:55:57] Quit Nicotine+ 3.3.4!
```

**Comment by mathiascode** [comment]
There isn't much point in keeping this issue open anymore. The remaining deprecations will be taken care of in Nicotine+ 3.4.0.
