### ISSUE TITLE
Russian translation [updated]

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2016]
Hello! Just updated Russian translation of Nicotine+: https://hosted.weblate.org/translate/nicotine-plus/nicotine-plus/ru/

Please, could you update it in your next version? Thank you!

**Comment by mathiascode** [comment]
I will add any translations to 3.2.3 that are compatible with the source strings in 3.2.x.
3.3.0 (to be released in a few months) will contain translations for new strings.
