### ISSUE TITLE
Time Left for folder and user same as for currently active file

### ISSUE THREAD

**Issue by nikohug** [nicotine-plus/nicotine-plus#2018]
Nicotine+ version:  3.3.0.dev1
Operating System/Distribution: Ubuntu 22.04 LTS

### Describe the bug
"Time Left" shows the same value for the file being downloaded/uploaded, for the folder and for the user, regardless if there are more files/folders to be downloaded

### Expected behavior
"Time left" for the folder and user should show an estimation of time remaining for the folder, resp. all users' DL and UL, based on size and current speed.

### Steps to reproduce the bug
Download/Upload a folder

### Additional context
The bug was already ocurring on Ubuntu 20.04 and Nicotine+ 3.2.2
![image](https://user-images.githubusercontent.com/75673584/167708969-04d4eca6-4109-4143-a350-837ba5624aaf.png)

**Comment by slook** [comment]
Obvious now you point it out, yes indeed this is an oversight. 

For the Time Left calculation to be correct, all of the transfers in each folder with the status of "Queued" should be included in the sum of the total Size, but clearly only transfers with the status of "Transferring" are currently included, which is wrong.
