### ISSUE TITLE
Time Left column regression

### ISSUE THREAD

**Issue by rcz01** [nicotine-plus/nicotine-plus#2020]
**Nicotine+ version**: 3.2.0, GTK 3.24.33
**Operating System/Distribution**: Ubuntu 22.04

**Describe the bug**
In Uploads tab "Time Left" column on user level user shows time left for current file (or nothing if no files are being uploaded to user), not ETA for all files queued. In previous versions it used to show ETA for all files queued by user.

**Expected behavior**
Time left on user level to show ETA for all queued files for this user

**Steps to reproduce the bug**
Works for all uploads
![image](https://user-images.githubusercontent.com/96410914/167915889-1e2175b3-5e67-4e3f-9194-d3033a69baef.png)

**Comment by mathiascode** [comment]
Thanks, this was fixed yesterday: https://github.com/nicotine-plus/nicotine-plus/issues/2018

I'll include the fix in the upcoming 3.2.3 release.
