### ISSUE TITLE
Debian PPA

### ISSUE THREAD

**Issue by ovitus** [nicotine-plus/nicotine-plus#2069]
There's an Ubuntu PPA for Nicotine+

https://launchpad.net/~nicotine-team/+archive/ubuntu/stable

Is there one specifically for Debian?

**Comment by slook** [comment]
If you prefer to install a .deb package directly, you can [download one here](http://ppa.launchpad.net/nicotine-team/stable/ubuntu/pool/main/n/nicotine/).

Nicotine+ will be available from the offical Debian repo in the future see #1448

**Comment by slook** [comment]
Hopefully your question is answered and you are up and running now @ovitus ?

**Comment by slook** [comment]
You're welcome. Please let us know if you have any further questions issues installing/upgrading Nicotine+.
