### ISSUE TITLE
Nicotine+ failed to compile (arch repo)

### ISSUE THREAD

**Issue by ahloiscreamo** [nicotine-plus/nicotine-plus#2073]
Nicotine+ version:  nicotine-plus-git 3.3.0.dev1.r7195.6af10d29-1
Operating System/Distribution: artix linux

Nicotine+ failed to compile (arch repo)

relevant output -
`================= 54 passed, 2 deselected in 15.97s ==================
data/org.nicotine_plus.Nicotine.metainfo.xml: data/org.nicotine_plus.Nicotine.metainfo.xml could not be read: Failed to open file “data/org.nicotine_plus.Nicotine.metainfo.xml”: No such file or directory
==> ERROR: A failure occurred in check().
    Aborting...
checking dependencies...
`

**Comment by ahloiscreamo** [comment]
Update-

i manually placed the file _org.nicotine_plus.Nicotine.metainfo.xml_  into _~/.cache/yay/nicotine-plus-git/src/nicotine-plus/data master*_  and compile successfully. I will close the issue.

**Comment by mathiascode** [comment]
@yochananmarqos The AUR package probably needs an update to take 59f8b2a23b7e5df07d981e38fe63be1ac188a1a4 into account.

**Comment by slook** [comment]
Why can't we just symlink them?

**Comment by mathiascode** [comment]
> Why can't we just symlink them?

1. Nobody else does that
2. It makes no sense, since we switched to an older naming scheme that is supported everywhere

**Comment by slook** [comment]
This change was made was obviously for a good reason then, please explain:

- Quick reason why the the naming scheme has been changed?
- What is "appstream"?
- Are there benefits to dropping the appstream compile-time dependency? Can it be optional?
- Is this a breaking change for international users on Arch based systems? Is app re-install required?

**Comment by yochananmarqos** [comment]
@mathiascode [Fixed](https://aur.archlinux.org/cgit/aur.git/commit/?h=nicotine-plus-git&id=cf5072c6a93b0b7904aa7a2451e019ec4bfbc9a4)
