### ISSUE TITLE
Make log history font configurable

### ISSUE THREAD

**Issue by AtticFinder65536** [nicotine-plus/nicotine-plus#2074]
### Describe the solution you'd like
I would like to make the font of the messages in the log history configurable, like you can with the chat font, transfers font, browse shares font etc. I like GUIs to use sans-serif but still chat and logs to use monospace.

### Additional context
I tried adding the feature by copy pasting in a [branch](https://github.com/AtticFinder65536/nicotine-plus/tree/log-history-font-configurable) in my fork but I couldn't get it to work. The log history font always uses globalfont. I tried setting the font option to 'chatfont' to rule out any error in the new option but it kept using the global font. I tried a bunch of things but couldn't make it work and I couldn't do it on 3.2.2 as well.

**Comment by mathiascode** [comment]
This should probably be a generic text view font option that covers user info descriptions as well.

**Comment by AtticFinder65536** [comment]
If that's the only other thing I think it would be better to have a separate option rather than grouping log history + user info description + any other textview screens. Other than user info descriptions and log history I can't think of any other area that would be remotely useful to have a separate font option rather than inherit the global font.

Does anyone know if I'm just missing something really obvious in https://github.com/AtticFinder65536/nicotine-plus/commit/89ca01a0968c5b9b778bf8608b98efe1e9b73693 that is preventing the log history from using the log history font option?

**Comment by slook** [comment]
Since `TextView()` is invoked during `frame.__init__` thereafter `TextView.font` would always contain the initial value.

**Comment by slook** [comment]
> something really obvious in https://github.com/AtticFinder65536/nicotine-plus/commit/89ca01a0968c5b9b778bf8608b98efe1e9b73693 that is preventing the log history from using the log history font option?

If you can get this working I'd be happy to review a PR.
