### ISSUE TITLE
Directories with trailing spaces cannot be created on NTFS

### ISSUE THREAD

**Issue by hejops** [nicotine-plus/nicotine-plus#2075]
Nicotine+ version:  3.2.0
Operating System/Distribution: 5.10.117-1-MANJARO

### Describe the bug
Trailing whitespace is allowed on ext4 systems (and similar), but not on NTFS. Downloads from a user using ext4 will thus fail as the directory cannot be created on NTFS.

### Expected behavior
Trailing whitespace in directory names should be stripped before attempting to create directory.

### Steps to reproduce the bug
1. Find a shared directory with trailing whitespace (search for "slsk descent maelstrom", for example)
2. "Download Folder(s) To..." [some NTFS location]

**Comment by slook** [comment]
I believe this should have been resolved now see https://github.com/nicotine-plus/nicotine-plus/issues/1835

@hejops Please update to [the latest stable version](https://nicotine-plus.org/doc/DOWNLOADS) (Nicotine+ 3.2.2) to verify if any related issues still exist or not, and re-open this issue if there is still a problem.
