### ISSUE TITLE
Feature: Provide a list of all open chat and chat room tabs

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#2079]
### Describe the solution you'd like
Currently when one is joined to many chat room or chat message tabs, the only way to see them all (or at least, more at once) is to wait for any given tab to receive a new message, then right-click on the notification icon that appears at the end of the tab row (which shows only tabs with new messages). When this icon is right-clicked, _all_ tabs are shown in a list, making it more convenient to jump to a given one, or simply to see an overview of what is open, compared to having to scroll through them all to discover at where a specific tab you're looking for actually is.

The improvement here would be to provide an area/icon to click even when no new message has arrived so that tabs can be browsed in list format at any time.

Nicotine+ 3.2.2

**Comment by slook** [comment]
The open chat tabs should be added to the Autocomplete list of the frame's TextEntry.

The Chat History popover should ideally feature all the open chats regardless if a log file exists or not.

**Comment by mathiascode** [comment]
Right-click empty space or a close button in the tab bar to get a list.

**Comment by redactedscribe** [comment]
Where do you see close buttons? Ah, seems I've had those disabled via the Preferences for a while (like my browser's tabs, it's annoying when I accidentally click them). With close buttons disabled and no blank space to click, there is no way to see a list. Preferably this wouldn't be a choice and it'd be possible in both cases.

**Comment by mathiascode** [comment]
I agree it should be easier to open the list, but for now, you should be able to press anywhere between the tabs (where text isn't present) to open the list, even with close buttons disabled.

**Comment by mathiascode** [comment]
Alternatively, right-click any buttons on the tab pages.

**Comment by redactedscribe** [comment]
It's actually still possible to show a list of tabs _without_ the close buttons enabled: right-click the blue highlight that lines the bottom of the tab (under the username) and it'll show. That of course isn't the greatest or most intuitive.

**Comment by slook** [comment]
In public chat you can also right-click in the empty area of the Users header, or in the space below the list.

In private chat when the tabs are on the right hand edge and the window is maximized then the context menu can be opened by right-clicking on the far right hand edge of the screen (last pixel).
