### ISSUE TITLE
Clear Finished also clears uploads/downloads with "User logged off" status

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#2081]
Nicotine+ version: 3.2.2
Operating System/Distribution: Windows 11

### Describe the bug
Clicking Clear Finished in the Uploads/Downloads tabs also clears any entries that have the "User logged off" status. Downloads which are even partially downloaded with this status are also cleared.

### Expected behavior
Not sure if this is expected, but it doesn't seem quite right.

### Additional context
Are these transfers really "finished"?

**Comment by slook** [comment]
I suppose they should be considered as "Failed" instead.

**Comment by mathiascode** [comment]
This shouldn't be the case for downloads? For uploads, the "Clear Finished" button covers both finished and aborted uploads.

**Comment by redactedscribe** [comment]
> This shouldn't be the case for downloads? The "User logged off" status isn't anywhere in the code at least:

Right, I must've mistakenly assumed this. However, last night I pressed Clear Finished and it did clear uploads with status "User logged off".

**Comment by mathiascode** [comment]
Here are the status combinations for uploads: https://github.com/nicotine-plus/nicotine-plus/blob/e70921a15442858744c3c1e7062fa05d6be4dbdf/pynicotine/gtkgui/uploads.py#L153-L164

I guess the main question is, do these combinations make sense? What would you expect here? The "Clear Finished" button currently calls `on_clear_finished_aborted`, should it only clear the `Finished` status, or would this do too little for a quick-access button?

**Comment by slook** [comment]
If the remote user logs off then it is probably not their intention to abort, as they will resume in progress transfers upon logging back in.

Additionally, if the Clear Finished button is pressed whilst we are disconnected, then all the statusus are User logged off, so of course we do not want to clear those transfers unless they are Finished at 100%.

However, I do not personally use this button, so there could be other opinions about this.

**Comment by redactedscribe** [comment]
My basic assumption is that "User logged off" doesn't really imply any specific transfer status, they've simply logged off.

When we clear these uploads, I assume it's just on our end and those uploads aren't cancelled for the downloader, and so the remaining uploads that were marked as "User logged off" which we clear will reappear in our uploads list when they log back in. If that's the case, I guess the issue doesn't matter that much, however, we now don't know that someone may be waiting to download something from us when they re-login, which could influence our actions to not move/delete some files.

If uploads marked as "User logged off" had an expiration time to their status, then they could be kept around for e.g. 7 days, and once they're older, be marked as Aborted get cleared on "Clear Finished".

Or, if "User logged off" uploads were not treated as "Finished", then an additional entry "User logged off" could be added under "Clear All..." to treat is separately. This is the least complex and makes the most sense to me.

On an slightly off-topic note, why do both "Clear Finished" and "Finished" under "Clear All..." exist? Maybe the latter could be removed if it performs the same function.

**Comment by mathiascode** [comment]
> When we clear these uploads, I assume it's just on our end and those uploads aren't cancelled for the downloader

Yes.

> Or, if "User logged off" uploads were not treated as "Finished", then an additional entry "User logged off" could be added under "Clear All..." to treat is separately. This is the least complex and makes the most sense to me.

Sounds the most reasonable to me.

> On an slightly off-topic note, why do both "Clear Finished" and "Finished" under "Clear All..." exist? Maybe the latter could be removed if it performs the same function.

Mainly for the shared "Clear All" submenu in the transfer list context menu.
