### ISSUE TITLE
Please show completed transfer speeds in the upload tab.

### ISSUE THREAD

**Issue by magnog0** [nicotine-plus/nicotine-plus#2082]
Please show completed transfer speeds in the upload tab, official Slsk app does this if you could please implement it that would be great. 

Another thing, how come the upload speeds aren't consistent in nicotine? for example it takes a second or two for the upload speed to refresh, doesn't seem to be instantaneous, also goes from like 100kb/s to 500kb/s then to 20kb/s, then goes to like 2mb/s it always varies. yes my ports are open and working correctly.

**Comment by mathiascode** [comment]
Are you on Nicotine+ 3.2.2?

**Comment by mathiascode** [comment]
The issue with inconsistent transfer speeds in the GUI should be fixed in 56c758c733edc41023012db72e55dd6968647076 and c0605a0acd962b5bded2cbb466ebb42c03cea984.

**Comment by magnog0** [comment]
> The issue with inconsistent transfer speeds in the GUI should be fixed in [56c758c](https://github.com/nicotine-plus/nicotine-plus/commit/56c758c733edc41023012db72e55dd6968647076) and [c0605a0](https://github.com/nicotine-plus/nicotine-plus/commit/c0605a0acd962b5bded2cbb466ebb42c03cea984).

Sorry yes 3.2.2, when is the new update coming with the fix ?

**Comment by slook** [comment]
The fix is in 3.2.3rc2 (Release Candidate 2), so you can test the [latest unstable build](https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md) to verify if this fixes the issue for you @magnog0

**Comment by mathiascode** [comment]
The fix helps in some cases, mainly downloads, but it likely won't affect your case much, considering how much the speeds vary.

**Comment by magnog0** [comment]
@mathiascode How do i add that to my nicotine now?

**Comment by mathiascode** [comment]
Download the pre-release version or wait for the next release. https://nicotine-plus.org/doc/TESTING.html
