### ISSUE TITLE
add basic literary unicode: bold, italic, underline

### ISSUE THREAD

**Issue by dchmelik** [nicotine-plus/nicotine-plus#2085]
### Describe the solution you'd like
Major Internet Relay Chat (IRC, dating to 1988) clients like HexChat have been able to do unicode for years/decades including selecting/entering special characters to make subsequent text bold, italic, and/or underline, and to change back to normal text... but when I tried to paste those characters into Nicotine+ they were incorrectly changed to newlines. and/or ignored.. Nicotine+ should handle them correctly and/or add menu & keystroke options for such text styles.

**Comment by mathiascode** [comment]
The official Soulseek client doesn't support text formatting as far as I know.

**Comment by slook** [comment]
Would it necessarily matter if the the official client doesn't support formatting? since any special forwarding characters would just be ignored by it?

**Comment by mathiascode** [comment]
I don't personally want to put effort into features that don't work for all users on the network (slsk links for example, which don't work in the official clients).

**Comment by slook** [comment]
It is a shame, but for that reason adding the suggested feature would be a bad idea.

**Comment by mathiascode** [comment]
Closing as won't fix for now.
