### ISSUE TITLE
Portforwarding error

### ISSUE THREAD

**Issue by LittleIggy18** [nicotine-plus/nicotine-plus#2088]
Nicotine+ version:  3.2.2
Operating System/Distribution: Windows 10

### Describe the bug
Unable to upload any files. My ports are open, however nothing is going through. 
Error message: "UPnP: Failed to forward external port 2234: Failed to map the external WAN port: Error code 501: ActionFailed" displays. I asked around and they said it was because I wasn't forwarding using the correct IP. I double checked and I do appear to have the port forwarding to the correct IP. Looking into it I found that many linksys routers have the same issue with port forwarding. 

### Expected behavior
Unable for other users to download, upload, or view your files.

### Steps to reproduce the bug
Own a linksys router, direct your open port to your device IP.

### Additional context
Screenshots, logs, stacktraces or relevant information.
Attached images are soulseek saying my ports are opened, and my portforward configuration. The text is the string of errors shown when an error message decides to appear.
![image](https://user-images.githubusercontent.com/107805876/174490062-447b109d-e3f0-4476-87d6-5d2854934d37.png)
![image](https://user-images.githubusercontent.com/107805876/174490071-c4e85220-ea6e-44b0-811f-052474eef69a.png)

11:57:16 [Misc] UPnP: Trying to redirect external WAN port 2234 TCP => 192.168.0.104 port 2234 TCP
11:57:16 [Misc] UPnP: Adding port mapping (192.168.0.104 2234/TCP, urn:schemas-upnp-org:service:WANIPConnection:2) at url '192.168.0.116:5555/ctl/IPConn'
11:57:16 [Misc] UPnP: Add port mapping request headers: {'Host': '192.168.0.116:5555', 'Content-Type': 'text/xml; charset=utf-8', 'SOAPACTION': '"urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"'}
11:57:16 [Misc] UPnP: Add port mapping request contents: b'<?xml version="1.0"?>\r\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"><NewRemoteHost></NewRemoteHost><NewExternalPort>2234</NewExternalPort><NewProtocol>TCP</NewProtocol><NewInternalPort>2234</NewInternalPort><NewInternalClient>192.168.0.104</NewInternalClient><NewEnabled>1</NewEnabled><NewPortMappingDescription>NicotinePlus</NewPortMappingDescription><NewLeaseDuration>86400</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>\r\n'
11:57:16 [Misc] UPnP: Add port mapping response: b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>501</errorCode><errorDescription>ActionFailed</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>'
11:57:16 UPnP: Failed to forward external port 2234: Failed to map the external WAN port: Error code 501: ActionFailed
11:57:16 [Misc] Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 376, in _update_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 297, in _request_port_mapping
Exception: Error code 501: ActionFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/upnp.py", line 387, in _update_port_mapping
RuntimeError: Failed to map the external WAN port: Error code 501: ActionFailed

**Comment by LittleIggy18** [comment]
update: I can download and upload files and users can browse my files after restarting nicotine but the error still shows up. I have no idea what the error means or what it would be preventing from working but it doesn't appear to be doing anything.

**Comment by slook** [comment]
Thank you for your bug report. Resolving these types of issues can be complex and time consuming, but is worthwhile to support as many routers as possible.

Further information such as system logs might be required from you in due course.

**Comment by mathiascode** [comment]
Since you forwarded the port manually, UPnP is likely conflicting with the port mapping. Either remove the manual port forward and let UPnP do the job, or disable UPnP in the Nicotine+ preferences.

**Comment by mathiascode** [comment]
Closing, since an answer was given.
