### ISSUE TITLE
Column headings overlapping in the downloads tab

### ISSUE THREAD

**Issue by Sciencentistguy** [nicotine-plus/nicotine-plus#2090]
Nicotine+ version: `Nicotine+ 3.2.1`
Operating System/Distribution: `NixOS, 22.11 (Raccoon), 22.11.20220618.e0a4226`

### Describe the bug
In the downloads tab, the "Queue Position" and "Percent" column titles overlap when Nicotine is first opened:

![image](https://user-images.githubusercontent.com/4983935/175044465-a3ae756c-fab2-4f1c-97c0-4bfc0fbf61d6.png)

### Expected behavior
Not that:

![image](https://user-images.githubusercontent.com/4983935/175044667-6a4100e8-5cce-4e6f-a283-260e012984ea.png)

### Steps to reproduce the bug
1. Open nicotine
2. Look at the column titles

**Comment by Sciencentistguy** [comment]
I'm using this theme: https://github.com/nana-4/materia-theme.

Yes, the issue still occurs with Adwaita:
![image](https://user-images.githubusercontent.com/4983935/175074216-a9d87bd0-8e5e-4f3f-991b-6d7f06f51a16.png)

**Comment by mathiascode** [comment]
> Yes, the issue still occurs with Adwaita: ![image](https://user-images.githubusercontent.com/4983935/175074216-a9d87bd0-8e5e-4f3f-991b-6d7f06f51a16.png)

This looks as intended, i.e. the column header has a background that covers any overlapping text.

Depending on the font and translation, you will never get a perfect result for these narrow columns, but I could bump the default width slightly to make it less likely to occur.
