### ISSUE TITLE
Granular control over shares with trusted buddies (+ custom buddy shares?)

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#2093]
### Describe the solution you'd like
Currently, shares can be individually limited to buddies only or not, with an additional option _Limit buddy-only shares to trusted buddies_ which is applied globally to all shares. A nice feature, however it's an all-or-nothing situation. I'd like to see this feature refined so that the augmenting trusted buddies option is no longer global, but instead settable on a per-share basis (the same way you can limit a particular share to be buddy-only or not).

The limit to trusted buddies option was original introduced as a way to let Nicotine+ user's have buddies on their buddy list without them also having access their private shares as this isn't always desired. With the suggested improvement, we could not only have private shares for the average buddy, but also a subset of those shares limited to buddies which are marked as trusted.

The idea here is that each type of share in the table assumes the same level of trust as the type above it:

Share type | Examples
-|-
Public share | A user's Downloads folder; lossy music; unsorted music
Buddy-only share | Lossless music; sorted music
Trusted buddies share | Hi-res lossless music; personally ripped music
Custom buddies share | Music library folder; misc. personal files

Taking it a step further (as seen in the last row of the table), perhaps a share could also be limited to a list of specific buddy usernames and/or IPs? E.g. one adds a buddy the share's custom list, then chooses whether the limitation is username-based, or IP-based, or both.

Should these ideas ever be implemented, the _Limit buddy-only shares to trusted buddies_ option could either be retired, or kept as a global switch, overriding any per-share trusted settings.

However for now, being able to set individual shares to public, buddy-only, or trusted buddies would be ideal (if this would be able to make it into the upcoming release, that would be perfect).

Leave a comment if further control of who has access to what shares is something you see any benefit in.

Thanks.

**Comment by mathiascode** [comment]
> However for now, being able to set individual shares to public, buddy-only, or trusted buddies would be ideal (if this would be able to make it into the upcoming release, that would be perfect).

This, including the other share-related requests like private shares and excluding files/folders, will likely require a complete overhaul of the way shares are stored in Nicotine+. Shares are currently divided into two databases, public and buddy shares, which provide very little flexibility when it comes to individual folders.

Unfortunately, I have too many other things on my Nicotine+ TODO list right now, so I won't be able to work on this anytime soon.

**Comment by redactedscribe** [comment]
> This, including the other share-related requests like private shares and excluding files/folders, will likely require a complete overhaul of the way shares are stored in Nicotine+. Shares are currently divided into two databases, public and buddy shares, which provide very little flexibility when it comes to individual folders.

I was hoping that since individual folders can be marked as buddy-only, an additional requirement of those buddies being trusted too wouldn't have been too much to put together, but that doesn't sound like it's the case sadly.

> Unfortunately, I have too many other things on my Nicotine+ TODO list right now, so I won't be able to work on this anytime soon. 3.2.3 is feature-frozen and will be released next week.

That's understandable. Good news on 3.2.3's release coming soon though. It's been a while. Thanks to you and the other code committers for your efforts.

**Comment by slook** [comment]
The new `/share` and `/unshare` commands proposed in https://github.com/nicotine-plus/nicotine-plus/pull/2313 are designed to easily support multiple share groups, because the share databases are referenced by index instead of name, as such:

- 0 = "public" _== False == 0_
- 1 = "buddy" _== True == 1_ 
- 2 = "trusted" _== 2_

The boolean "Buddy-only" CheckButtons in the Shares Preferences could be converted to numeric index in the config for the implementation of inline drop-down ComboBoxes in the column, with renamed header "Group".

**Comment by mathiascode** [comment]
> could be converted to numeric index in the config

Please never add any new index-based options to the config. They are unreadable, and always come back to haunt you in one way or another. Due to someone going the lazy route of storing column visibilities/widths in a list, the columns could never be reordered or removed again, and the whole system had to be scrapped.

If we ever add share groups, I would instead either use a random ID, or if the groups can be named, a normalized variant of the name.

**Comment by mathiascode** [comment]
I've added a trusted buddy shares group in https://github.com/nicotine-plus/nicotine-plus/pull/2662, which should resolve this feature request. I don't plan on offering more granularity than this.

**Comment by mathiascode** [comment]
Check https://github.com/nicotine-plus/nicotine-plus/issues/1870 for up-to-date builds for testing.

**Comment by mathiascode** [comment]
If everything works well, this will likely be the final build before the PR is merged into master: https://nightly.link/mathiascode/nicotine-plus/actions/runs/6423191481

Note that this build will migrate the global "Limit buddy-only shares to trusted buddies" option that existed before. If you had enabled this option, buddy shares will be changed to trusted shares, but you can change them back afterwards.

**Comment by redactedscribe** [comment]
> If everything works well, this will likely be the final build before the PR is merged into master: https://nightly.link/mathiascode/nicotine-plus/actions/runs/6423191481

Unfortunately I've not had much time so I haven't been able to test it. I'll give it a quick try tomorrow.

**Comment by redactedscribe** [comment]
> Note that this build will migrate the global "Limit buddy-only shares to trusted buddies" option that existed before. If you had enabled this option, buddy shares will be changed to trusted shares, but you can change them back afterwards.

I had _Limit buddy-only shares to trusted buddies_ enabled on Stable Nicotine+ and upon running the dev version from your link, the only item checked under Preferences > Shares was _Rescan shares on startup_, not either of the other two. Doesn't look like migration is occurring.
