### ISSUE TITLE
Banned and ignored users indicators

### ISSUE THREAD

**Issue by ghost** [nicotine-plus/nicotine-plus#2100]
A visual indicator like forbidden sign symbol and muted audio symbol next to the name. Something that makes it easier to see than having to go to preferences and looking at the list.

**Comment by slook** [comment]
Adding icon columns into TreeView is something that going to be considered at the point where the TreeView widget will be overhauled as discussed in https://github.com/nicotine-plus/nicotine-plus/issues/1731 :

_"I think we should aim for a sortable lock icon is_private column. Perhaps in future this could also be used for other attributes, such as _is_buddy_, _is_ignored_ or _is_blocked_. Perhaps this would assist in the implementation of filtering based on those characteristics."_

> Something that makes it easier to see than having to go to preferences and looking at the list.

For now an easier way you can open the Right-click > User(s) menu to see the checked menu-items if a user is banned or ignored.

**Comment by mathiascode** [comment]
This request is blocked until we've ported the chat room user list to the new TreeView object.

**Comment by mathiascode** [comment]
To clarify, where would you like to see these indicators? Only chat rooms, or somewhere else?

**Comment by JediMaster25** [comment]
To be honest I haven't found the need for this since then and I don't remember on what context I thought this would be helpful. I'll write the specifics if I recall it at some point.

**Comment by slook** [comment]
In the chat room users list, it might be logical to apply the greyed-out style to ignored user rows.

**Comment by mathiascode** [comment]
@slook That's what I had in mind as well.
