### ISSUE TITLE
Save leechers persistently

### ISSUE THREAD

**Issue by ghost** [nicotine-plus/nicotine-plus#2105]
### Describe the solution you'd like
Save a list of leechers messaged by the Leech Detector plugin to avoid messaging them more than once.

I would actually use this list to check users at regular intervals, like once a day, or at startup, to check the number of files and remove the ban from them, since I've set the plugin to ban instead of messaging.

**Comment by slook** [comment]
Yes indeed this required functionality is missing. Persistence would help with the forever ongoing issue https://github.com/nicotine-plus/nicotine-plus/issues/1565:

> "... it was suggested to me that it would be a very good idea to persistently store known leechers in a JSON file, because that would stop users being repeatedly plagued by spam complaints each time the plugin is restarted, which I think could be the more major issue that causes the bugging."

Suggest those user data be stored as _'plugins/leech_detector/leechers.json'_ for this purpose (there is already a mechanism for creating .json files like _'downloads.json'_).

It might be useful to expose a couple of related helper functions in _'pluginsystem.py'_ as there may be other purposes that plugin developers could have for storing persistent user data that is unrelated to _'config'_ settings.
