### ISSUE TITLE
Easier way to remove ban from a user

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2111]
### Describe the solution you'd like
When a user is banned the ban button should say unban instead, and remove him from the ban list when clicked.

The leech detector plugin has banned many people and I'm finding it tedious to remove the ban when they share enough files, because I have to find a name between many manually everytime.

**Comment by mathiascode** [comment]
> When a user is banned the ban button should say unban instead, and remove him from the ban list when clicked.

This is a good idea. Until it's implemented, you can right click the user info tab and unban from there.

**Comment by slook** [comment]
Also the "Ban User" and "Ignore User" buttons in the User Info view should ideally behave in the same manor as suggested here.
