### ISSUE TITLE
Tray icon has dissapeared in the latest version

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2113]
Nicotine+ version:  Nicotine+ 3.3.0.dev1
Operating System/Distribution: Manjaro Linux

### Describe the bug
After upgrading to the latest version I don't see the tray icon. I have `run in background` set. I used to see the tray icon always even when the program was maximized and closed to tray.

**Comment by JediMaster25** [comment]
GTK 4.6.5

pamac-gtk through the AUR package

**Comment by mathiascode** [comment]
Does the tray icon appear in the GTK 3 version?

**Comment by JediMaster25** [comment]
A couple of days ago it appeared, now I'm using 3.3.0 so I don't know.

**Comment by mathiascode** [comment]
Closing, since GTK 4 tray icon support is tracked in #2014.
