### ISSUE TITLE
Don't scan everything after removing a folder or allow stopping a rescan

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2117]
### Describe the solution you'd like
I did a rescan overnight and this morning I removed a folder with 1 file and it has started rescanning again. I don't want it to be scanning while I'm on the computer so I've had to close the program.

**Comment by mathiascode** [comment]
Nicotine+ only rescans on startup (can be disabled in preferences -> shares), and when you manually trigger a rescan.

**Comment by slook** [comment]
Closing in favour of #2115
