### ISSUE TITLE
Lists of shared files not human-readable

### ISSUE THREAD

**Issue by hejops** [nicotine-plus/nicotine-plus#2118]
Nicotine+ version:  3.2.0

### Describe the bug
Saving a user's list of shares produces a single-line text file that is of next to no use for the average user. The file is often too large (several MB) and complex to be read in any meaningful way.

### Expected behavior
Shares should simply be saved as a newline-delimited list of files (or similar):
```
# Shares from USER
/path/to/directory
/path/to/directory/file
...
```

As a workaround, you can currently obtain a list of (most?) directories (no files) by running:
```
< FILE grep -Po '@[^"]+' > OUT
```

### Steps to reproduce the bug
1. Browse any user's shares
1. "Save shares list to disk" (icon)
1. `cat $HOME/.local/share/nicotine/usershares/USER`

**Comment by mathiascode** [comment]
The list is a medium to restore the shares into the GUI later, using the "Open List" button.

**Comment by slook** [comment]
What is the reason why our json files are unable to contain line breaks?

**Comment by hejops** [comment]
> The list is a medium to restore the shares into the GUI later, metadata (bitrate, length) and all, using the "Open List" button. It's stored in json to allow for manipulation by determined users, but it's not the goal.

Fair enough; it didn't occur to me that the lists were in json, and parsing with `jq` turned out to be _much_ faster. I suggest that, at the very least, such lists be saved with a `.json` extension so that people know what tools they can use.

> What is the reason why our json files do not contain line breaks?

They don't even have an end-of-line!

**Comment by slook** [comment]
> I suggest that, at the very least, such lists be saved with a .json extension

This cannot be changed without breaking backwards compatibility.

> Presumably to save space? They don't even have an end-of-line!

The difference of disk space isn't so large that it would be of concern. It probably is possible to add line breaks that the json parser library can handle without breaking compatibility, because my understanding is that any whitespace is ignored.

**Comment by mathiascode** [comment]
Line breaks would probably be fine. I tried indentation, but that quickly blows up the file size.
