### ISSUE TITLE
i cant log in for some reason even though my existing account credentials are right. If i log in as a new user it works again

### ISSUE THREAD

**Issue by TestForFunOrSo** [nicotine-plus/nicotine-plus#2121]
Nicotine+ version:  
Operating System/Distribution: Windows 11

### Describe the bug 
I cannot log into the soulseek servers with my main account. The Log stated The Error code is 403

### Expected behavior
not succesfully connecting to the soulseek network

### Steps to reproduce the bug
log in

### Additional context
Screenshots, logs, stacktraces or relevant information.
If you log in with the Original Soulseek Client it works flawlessly and is accepting my Account name and pass however it is not for Nicotine+ for some reason u can log in as a different User and the error is not present.

**Comment by slook** [comment]
For some reason the server error 403 is "Forbidden", maybe it doesn't like you logging in from 2 clients/machines or something.

Try waiting for 30 minutes or so before logging in.

**Comment by slook** [comment]
I think the UPnP 403 error is unrelated to your login problem.

**Comment by TestForFunOrSo** [comment]
sorry forgot my name has a capital i will close the issue
