### ISSUE TITLE
Exception thrown when highlighting several uploads & selecting "Clear"

### ISSUE THREAD

**Issue by ursasenior** [nicotine-plus/nicotine-plus#2124]
Nicotine+ version:  `3.3.0.dev1` (latest up to commit `9d0836b87709ace4a380fc1035277480925726b1`)
Operating System/Distribution:
```
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.63-v7+
      Architecture: arm
```

### Describe the bug
I noticed a couple of users I had been uploading to for several days had stalled. It would exhibit the behaviour of uploading as per normal for 1-2 seconds before stopping, and the users were simply redownloading the same chunk of file and never progressing.
I shift-selected everything in my Uploads window (including users & singular file uploads) and Right-clicked before selecting Clear.
The exception below was shown, and the Upload entries were not removed.

### Expected behavior
Selected upload entries should be cleared from the window.

### Steps to reproduce the bug
- Wait until Uploads to other users are started
- Expand all entries, so that User + Folder + Single files view is shown
- Select all entries
- Right click -> Clear

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://user-images.githubusercontent.com/1014472/178172663-6525fbc6-f02c-47ee-b6ea-d56c19744bd4.png)

```
Nicotine+ Version: 3.3.0.dev1
GTK Version: 3.24.5
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]

Type: <class 'ValueError'>
Value: deque.remove(x): x not in deque
Traceback:   File "/home/pi/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 908, in on_clear_transfer
    self.abort_transfers(clear=True)
  File "/home/pi/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 659, in abort_transfers
    self.remove_specific(transfer, update_parent=False)
  File "/home/pi/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 679, in remove_specific
    self.transfer_list.remove(transfer)
```

**Comment by ursasenior** [comment]
Additional: This exception also occurs when clearing Downloads using the same steps for selecting entries

**Comment by slook** [comment]
Please can you verify if the crash is also present in Nicotine+ 3.2.3rc3 https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md

**Comment by ursasenior** [comment]
> Thank you for your detailed bug report.
> 
> Please can you verify if the crash is also present in Nicotine+ 3.2.3rc3 https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md

Confirmed via Downloads window (for ease of replication)
- Queued downloads
- Selected User + Folder + Files
- Right Click > Clear
- Error is thrown

![image](https://user-images.githubusercontent.com/1014472/178269678-11b0c848-f810-40f5-9cac-99a120e05709.png)

```

Nicotine+ Version: 3.2.3rc3
GTK Version: 3.24.5
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]

Type: <class 'ValueError'>
Value: deque.remove(x): x not in deque
Traceback:   File "/home/pi/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 908, in on_clear_transfer
    self.abort_transfers(clear=True)
  File "/home/pi/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 659, in abort_transfers
    self.remove_specific(transfer, update_parent=False)
  File "/home/pi/nicotine-plus/pynicotine/gtkgui/transferlist.py", line 679, in remove_specific
    self.transfer_list.remove(transfer)

```

**Comment by mathiascode** [comment]
Unfortunately I won't have access to a computer for a few days, but it sounds like the dummy transfer objects used by the user/folder rows are unintentionally selected now for some reason.

**Comment by ursasenior** [comment]
Looks good on both `master` and `3.2.x` repeating the same steps I posted earlier for uploads, downloads & search selection.

**Comment by slook** [comment]
Thank you for your help @ursasenior :)

Please stick with the `3.2.x` branch until Nicotine+ 3.2.3 is released and be sure to post a bug report if you get any other critical errors or important issues.
