### ISSUE TITLE
Later versions not diplaying the count and types of files downloaded 

### ISSUE THREAD

**Issue by Blinkot** [nicotine-plus/nicotine-plus#2129]
just upgraded from an earlier build to 3.2.2 and now the file type and count is no longer displayed on the "filename" category of folders
![image](https://user-images.githubusercontent.com/80516370/180571885-061e7b74-54d0-47ea-aebd-12149485cb30.png)
![image](https://user-images.githubusercontent.com/80516370/180571291-d97dfa07-f91e-4980-977e-5f30bdf93922.png)
I did not find any setting that could alter this behaviour in the newer build so I assume it isn't meant to act like that.

**Comment by slook** [comment]
There has been an unpopular feature regression, see #1174.

As far as I know the old implementation of the file count had performance issues so it had to be removed for now, but the total counts will be added again in a future version soon.

**Comment by slook** [comment]
There has been an unpopular feature regression, see #1174.

As far as I know the old implementation of the file count had performance issues so it had to be removed for now, but the total counts will be added again in a future version soon.

**Comment by mathiascode** [comment]
Closing as duplicate.
