### ISSUE TITLE
Option to choose language in Nicotine+

### ISSUE THREAD

**Issue by MasterSuggester** [nicotine-plus/nicotine-plus#2134]
### Describe the solution you'd like
There should be an option to choose your language, as many users may be using a Windows in another country or maybe just prefer the original English version (and also to be able to send logs in English).

### Additional context
N/A

**Comment by hboetes** [comment]
Not that I agree or disagree with the feature request, but… you can switch languages pretty easily like described over here:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TRANSLATIONS.md#testing-different-languages

Hope that helps for now.

**Comment by VsevolodGolovanov** [comment]
> https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TRANSLATIONS.md#testing-different-languages

This seems to be source oriented, for developers. Users, who have a Nicotine+ release installed, should create a batch file (with the `.bat` extension) and put the following in it:
```
set LANGUAGE=en_US.UTF-8
"C:\Program Files\Nicotine+\Nicotine+"
```
And launch it via this file.
Change the path if you have Nicotine+ installed in a non-default folder.
