### ISSUE TITLE
Different speed limit for buddies

### ISSUE THREAD

**Issue by ghost** [nicotine-plus/nicotine-plus#2139]
I would like to choose a different speed limit for buddies and normal users.

**Comment by slook** [comment]
It also might be desirable to choose different max files limit for buddies.

**Comment by mathiascode** [comment]
This isn't something I want to add right now, since it encourages people to set low limits for everyone except a few buddies, and there are a lot of questions about how it would fit in with the current speed limits (per transfer/total transfers).
