### ISSUE TITLE
Bitrate filter does not work as expected

### ISSUE THREAD

**Issue by defaultxr** [nicotine-plus/nicotine-plus#2141]
Nicotine+ version:  3.2.2
Operating System/Distribution: Arch Linux

### Describe the bug

The "Bitrate" results filter does not seem to work as expected:

- I would expect that typing `<320` and pressing enter should hide all results with bitrates of 320 or above. But 320kbps mp3s are still visible.
- Typing `>192` and pressing enter should hide all results with bitrates of 192 or below. They are still visible though.
- Typing `>192 <320` and pressing enter should show only results with bitrates above 192 and below 320. Again, this is not what happens.

It seems that Nicotine+ is interpreting `>` as `>=` and `<` as `<=`, since `<319` seems to hide 320kbps results as expected; `>193` also seems to hide 192kbps.

However, then I would expect a query like `>193 <319` to hide 320kbps and 192kbps results. Instead, I still see them. Is it possible to filter to a specific range?

Maybe I am misunderstanding how this filter works; if so, a more informative tooltip may be helpful. I could've sworn previous versions had a better tooltip but in 3.2.2 it just says "Bitrate" when I hover my mouse over the input field.

Either way, the bitrate field has always felt a bit buggy.

### Expected behavior

- `>` and `<` operate as greater then/less than, rather than greater than or equals/less than or equals.
- Multiple (space-separated) entries in the Bitrate field should be `AND`-ed together like they are in the other filters.
- A better tooltip with bitrate filtering syntax and examples of bitrate filtering.

### Steps to reproduce the bug

1. Do a search.
2. Open "Result filters".
3. Try any of the above examples.

### Additional context

Let me know if you need any other information.

**Comment by slook** [comment]
The bitrate filter has already been revised in 3.3.0dev1, please can you review the behaviour in the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) and we can go from there.

**Comment by defaultxr** [comment]
> Yes, multiple conditions are possible to specify a range now with the | (OR) operator syntax in the latest build.

Hmm. But "AND" is not supported for bitrates? I tried with `&` but it seems to exclude all results. For example, even though there are plenty of 256kbps files in the results, a bitrate filter like `>192&<320` doesn't show them (or any results, in fact).

> Please can you review the behaviour in the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) and we can go from there.

Sure. I tried the flatpak linked in TESTING.md and am seeing the same behavior. `<320` still shows files with 320kbps bitrates, etc.

> Whilst this would make sense for the integer values of Bitrate, it would not work for the Size and Duration filters because applying the same logic there (and indeed the same logic is actually used for all three filters) would wrongly exclude files that are infact only a decimal fraction more/less than the input specified.

So you're saying that an input like `<3MB` or similar would exclude files that are 3.01MB, for example? What's wrong with that? I think most people would say that's correct. I would think if a user wants files less than 3.01MB they would input something like `<3.01MB` instead.

**Comment by slook** [comment]
In the context of the filter functions AND is OR so the seperator used is the `|` (pipe) character, since a single file object cannot be both 192Kbps and 320Kbps at the same time.

Admittedly more characters other than `|` would make specifying multiple conditions much more intuitive as you have highlighted, and really it is reasonable for an end user to consider the filters apply to a group of result objects rather than a single object, so `&` should be considered as a valid operator regardless of the actual operation done in the filtering function.

For the sizes I made it so that values which are converted from Bytes into MiB are approximated to with 0.125 of a unit, because otherwise getting any results with the `=` (equal) operator was practically impossible.

For the duration I suppose one would consider for example `<3:01` to show files that are 3:01.9 (almost 3:), because milliseconds are not displayed in the interface, nor supported in the filters.

The issue is that only 1 character is expected for the operator symbol, but I suppose 2 character operators could be supported aswell without too much trouble.

**Comment by slook** [comment]
@defaultxr Are you able to clone [this development branch](https://github.com/slook/nicotine-plus/tree/filter-operator-sep) for testing? If possible, your feedback on this would be most welcome before it is considered for merging into master.

```
git clone https://github.com/slook/nicotine-plus.git --branch filter-operator-sep --depth 1
cd nicotine-plus
./nicotine
```

**Comment by defaultxr** [comment]
Sure. Testing as per your instructions and the bitrate filter definitely looks like it's working how I expected it to. Makes it a lot easier to find V0 mp3 in search results and such. I would be very pleased if this behavior became the new standard behavior in the master branch.

**Comment by slook** [comment]
Thanks @defaultxr that's good to hear.

I have further refined the syntax to enable any amount of spaces, ampersands or pipes can be entered between multiple filter conditions without breaking the field or creating duplicate history entries with different ||| spacing as it was doing before. Also, now one space after an operator can be entered before the digit without it being orphaned, allowing for a much more flexible syntax.

To test, update the development branch with:

```
cd nicotine-plus
git pull
./nicotine
```

**Comment by defaultxr** [comment]
That seems to work as well; `< 320 > 192` works as expected. I also tried `< 320 | > 192` and similar. Though I'm not sure if it's expected behavior or not but `|` doesn't seem to work as an `or` operator like I was expecting; for example, `> 320 | < 192` doesn't show any results, even though there are plenty of files with > 320 bitrate in the non-filtered results, as well as plenty that are < 192. If `|` isn't meant to be an `or` then that's fine with me, I would still be happy with the behavior as it is in the `filter-operator-sep` branch right now as finding V0 mp3s more easily was my primary use-case (and I can't really imagine why someone would want to search "greater than 320 or less than 192" in reality).

**Comment by slook** [comment]
>`|` doesn't seem to work as an OR operator

No, that's right. This behaviour has not changed since the numeric filters have had ability to concatonate multiple conditions together, the `<` and `>` have not been able to exclude a range, only to include a range.

> I can't really imagine why someone would want to search "greater than 320 or less than 192" in reality

Agreed, while there might be a valid reason for doing so in some edge case scenario, it would require somebody much smarter than myself to work on this, and I don't think the extra complexity that would be needed is warranted.

**Comment by defaultxr** [comment]
Makes sense. Then I would say the current behavior on this branch definitely seems good to me.

**Comment by slook** [comment]
@defaultxr The development branch is just updated again, perhaps it will be the final testing before merging it into master.

**Comment by defaultxr** [comment]
Tested, and it looks good to me! :+1: Looking forward to the official release with it :)

**Comment by slook** [comment]
@defaultxr After review discussion in https://github.com/nicotine-plus/nicotine-plus/pull/2238 it is changed slightly again, update with `git pull` to test.

+ Changed: Exclude non-audio files (with zero duration or bitrate) when using digit based filter (unless exact match of zero)

**Comment by defaultxr** [comment]
Pulled and tested, and the bitrate filter still seems to work as expected. I also tested filtering by length and it looks like that is working for me as well.

**Comment by slook** [comment]
What do you think of the factory presets in the combobox?

**Comment by mathiascode** [comment]
My intention was to have a filter for lossless files, hence `>320`.

**Comment by mathiascode** [comment]
I would assume people either want lossless or not, depending on if they care about quality or disk space. For a high quality filter containing both lossy and lossless files, >=320 isn't that good today, when you have newer audio formats with equivalent quality at a lower bitrate.

**Comment by slook** [comment]
That is true, however on the other hand since recent versions of LAME encoding, when used for electronic genres which are popular with our users such as house and techno, then 320Kbps MP3 files are considered to be indistinguishable from lossless, even on high end sound systems.

**Comment by defaultxr** [comment]
> What do you think of the factory presets in the combobox?

If you're asking me, I think having one for mp3 V0 files would be nice. I usually search `>192 <320` for that. `192 <=320` isn't quite the same since it finds a lot more CBR files than `>192 <320` does, as 192kbps is a pretty common CBR bitrate.

Otherwise, I pulled again and checked and everything still seems to be working fine for me.

**Comment by slook** [comment]
`        "filterbr": ("!0", "128 <=192", ">192 <320", "=320", ">320"),`

**Comment by mathiascode** [comment]
@slook This works for me.

> I am concerned that if any users have >320 set as a default filter, then they will suddenly see less results than was previously expected as a result of recent changes to the math used in the bitrate filter.

I don't think this will be a large issue, considering `320` was a preset before. We are probably breaking behavior in some other cases anyway, and we'll have to mention this in the release notes and bump the version accordingly.
