### ISSUE TITLE
Cancelled transfers re-added as fresh after share rescan finishes

### ISSUE THREAD

**Issue by Mentalist** [nicotine-plus/nicotine-plus#2144]
Nicotine+ version:  3.3.0.dev1/3.2.4  •  GTK 4.6.6
Operating System/Distribution: Arch Linux (5.18.16-arch1-1)

### Describe the bug
A set of users, to be exact, three have initiated transfers but cancelled them at either halfway or three-quarters done. When a rescan of my shares finishes (manually or on startup), those cancelled transfers get re-added, and N+ will loop over all the files going from '**Getting Status**' to '**Transferring**' to '**Cancelled**'.

I can't seem to be able to remove these cancelled transfers permanently; note, it's only doing this for three specific users; for others (with comparable (cancelled) transfers), it doesn't show the same behaviour.

### Expected behaviour
Cancelled transfers don't get re-added when a rescan of the shares finishes.

### Steps to reproduce the bug
_No idea_

### Additional context
_None_

**Comment by slook** [comment]
It is probable that the erroneous transfers are being initiated from the remote peer's legacy clients which have the buggy behaviour.

**Comment by mathiascode** [comment]
The transfers are added right after the rescan finishes because Nicotine+ pauses file download requests while shares are rescanning.

Since the transfer status changes to 'Transferring' before the transfer is cancelled, and the user keeps requesting the file again, it's probably some I/O issue on the user's end, maybe low on disk space or similar.

**Comment by mathiascode** [comment]
If you send me some debug logs, I could check if anything odd shows up. Follow these steps:

1. Preferences -> Logging -> Debug log to file
2. Menu -> View -> Show log pane
3. Right-click the log pane -> log categories -> enable "Messages", "Uploads", "Transfers" and "Connections"
4. Once you've captured the transfers being re-added in the log, send it to my e-mail on my Github profile. The log is located at ~/.local/share/nicotine/logs/debug

**Comment by Mentalist** [comment]
Thanks to both for replying; the explanations make sense. I will send you debug-logs mathiascode, as soon as I re-encounter the issue; it seems to be that all three affected users have gone offline, which logically prevents it from happening—closing for now.
