### ISSUE TITLE
Certain methods of minimizing a Nicotine+ window will result in the Nicotine+ window popping up unexpectedly when opening other programs.

### ISSUE THREAD

**Issue by hypercube42** [nicotine-plus/nicotine-plus#2149]
Nicotine+ version:  3.2.4
Operating System/Distribution: Windows 10

### Describe the bug
Certain methods of minimizing a Nicotine+ window will result in the Nicotine+ window popping up unexpectedly when opening other programs. I just updated Nicotine to the current version, but I have had this issue since starting to use Nicotine about a year ago.

### Expected behavior
Nicotine+ window will stay minimized to the taskbar no matter the method used to minimize it

### Steps to reproduce the bug
1. Open nicotine as either maximized or windowed
2. Open another program
3. Minimize all the open programs simultaneously with either Win+D or the Windows desktop icon (small sliver in the the very bottom right corner in Windows 10)
4. Click on any minimized program (besides Ncotine) in the taskbar, and the desired program pops up, but Nicotine also pops up in the background.

### Additional context
Steps to prevent bug:
1. Open nicotine in either maximized or windowed
2. Open another program
3. Minimize Nicotine by either clicking the "minimize" button at the top right of the window or by clicking the icon in the system tray
4. click on any minimized program (besides Nicotine) in the taskbar, and only the desired program pops up

**Comment by slook** [comment]
Please specify your GTK version (displayed in the About Nicotine+ dialog)?

**Comment by mathiascode** [comment]
This is a GTK issue on Windows.

**Comment by hypercube42** [comment]
> 

GTK 3.24.34

**Comment by hypercube42** [comment]
> Please specify your GTK version (displayed in the About Nicotine+ dialog)?

GTK 3.24.34

**Comment by mathiascode** [comment]
Closing in favor of #2014

**Comment by mathiascode** [comment]
Fixed in Nicotine+ 3.3.3rc2.
