### ISSUE TITLE
Speed up program startup times

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#215]
The startup time of Nicotine+ is pretty slow, which mainly stems from the fact that a lot of objects are initialized at startup, even if they're not needed yet or disabled (e.g. settings window, tray icon, plugin system). We should initialize things on-demand, which speeds up startup times a lot.

**Comment by kiplingw** [comment]
I'm fine with the proposal. Although I'm only seeing it take about three seconds to load on my machine that's running Focal. Or did you test on Windows?

**Comment by mathiascode** [comment]
Takes 2-3 seconds on my main system, somewhat slower in Windows for some reason. SoulseekQt starts in about half a second or less.

What seemed to be the main culprit is the settings window, not sure yet if something there in particular slows it down, or if it's just the sheer amount of settings and pages that hogs it.
