### ISSUE TITLE
Arch linux no buttons to apply in menus

### ISSUE THREAD

**Issue by 3k2** [nicotine-plus/nicotine-plus#2156]
Hey,

I noticed in [Arch linux package](https://archlinux.org/packages/community/any/nicotine+/) there's no option to apply settings in the menus.

![image](https://user-images.githubusercontent.com/11908261/185607350-fcadc7b2-4b26-456f-8b8a-ad471bf163c8.png)

I am using KDE on my linux system.

Also I'd like to know how to do port forwarding I am using vpn and port forwarding is enabled but whenever I set the correct port at launch it says following.
`
The range you specified for client connection ports was 61533-61533, but none of these were usable. Increase and/or move the range and restart Nicotine+.`

if I add 61534 it automatically connects to that port which isn't open.

**Comment by 3k2** [comment]
> What about in the Setup Assistant dialog (from the Help menu), do the buttons show in there?
> 
> Is it a problem with a particular OS window manager theme maybe? Does changing the theme make any difference?

I tried to switch to completely new theme in window manager but didn't have any effect.  in setup assistant dialog the button on the first page was showing up but after going to the port forwarding section there wasn't any buttons to continue.

![image](https://user-images.githubusercontent.com/11908261/185627747-4120e314-e468-4569-b4fa-45d417d701a0.png)

I even tried KDE's official themes to see if it would get it fixed but seems it doesn't. I did notice when I try to setup profile picture and such none of those settings will stick it's like I never touched them.

**Comment by mathiascode** [comment]
The buttons are supposed to appear in the title/headerbar (client side decorations), but I guess something on your system is overriding it with server side decorations? Does the main window have buttons in the headerbar?

**Comment by 3k2** [comment]
> The buttons are supposed to appear in the title/headerbar (client side decorations), but I guess something on your system is overriding it with server side decorations? Does the main window have buttons in the headerbar?

I'm not sure what you mean exactly but there is buttons for the settings and hamburger menu. Not sure what else there is suppose to be.

**Comment by slook** [comment]
Minimize; Maximize/Unmaximize; Close buttons?

**Comment by 3k2** [comment]
> Minimize; Maximize/Unmaximize; Close buttons?
> 
> ![image](https://user-images.githubusercontent.com/88614182/185717357-94e83107-17e0-43e7-8d93-e256b4152d33.png)

Yeah they are showing in all of the pictures.

![image](https://user-images.githubusercontent.com/11908261/185732187-18784b03-d9cd-44f1-8e38-4e2b97b903e5.png)

**Comment by slook** [comment]
Can you try Menu -> View -> Use Header Bar -> Off.

**Comment by 3k2** [comment]
![image](https://user-images.githubusercontent.com/11908261/185733910-5feace92-34af-4017-8f9d-7cf567b2f41f.png)

Header Bar off didn't work.

**Comment by slook** [comment]
We need to determine if this problem is exclusive to the community Arch package or not.

Are you able to [install Nicotine+ using another installation method](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#other-distributions) or perhaps [run from a local Git folder](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#git)?

**Comment by 3k2** [comment]
I ran nicotine from local git folder but the results are still the same.

```
nicotine-plus on  master
➜ ./nicotine
[2022-08-20 11:22:55] Loading GTK 3.24.34
[2022-08-20 11:22:55] Loading Python 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
[2022-08-20 11:22:55] Loading Nicotine+ 3.3.0.dev2
[2022-08-20 11:22:55] Loading plugin system

(org.nicotine_plus.Nicotine:2095): Gtk-WARNING **: 11:22:55.421: Theme directory  of theme Antu-icons has no size field

[2022-08-20 11:22:55] The range you specified for client connection ports was 60533-60533, but none of these were usable. Increase and/or move the range and restart Nicotine+.
[2022-08-20 11:22:57] Rescanning shares…
[2022-08-20 11:22:57] 45136 folders found before rescan, rebuilding…
```

![image](https://user-images.githubusercontent.com/11908261/185736228-63a831cb-1d1f-420d-86f7-760a6401b9c4.png)

I also yet again changed KDE theme but no effect.. what theme you are using slook (just curious)

**Comment by slook** [comment]
I'm using XFCE on Debian with some standard theme that comes with the MX Linux distro. Apparently KDE on MX does not have this same problem as you are having on your system, so it is something specific to your Arch distro.

**Comment by 3k2** [comment]
> I'm using XFCE on Debian with some standard theme that comes with the MX Linux distro. Apparently KDE on MX does not have this same problem as you are having on your system, so it is something specific to your Arch distro.
> 
> I remember from another issue before that changing the GTK theme in Arch with the Breeze theme required extra packages, since the Gtk theme is totally separate from the main Qt window manager theme.
> 
> What's this about? `(org.nicotine_plus.Nicotine:2095): Gtk-WARNING **: 11:22:55.421: Theme directory of theme Antu-icons has no size field`

I did some research from the GTK warning it seems to be nothing major to worry about.

> I just wanted to share with you guys the solution to this warning in the title I was getting lately in terminal window whenever I was using the Update Manager in Linux Mint 18.2 and 18.3. I've read in a post in the Arch Linux community forum that the warning is just that, a warning, that some size fields are missing in a theme's "index.theme" file, so nothing really to worry about.

I installed Nicotine+ from AUR it comes with Nicotine+ GTK 4 version and there menus are working correctly.

![image](https://user-images.githubusercontent.com/11908261/185746850-10b23a53-8c8d-472a-a046-7d61aff12876.png)

tho it seems like there isn't button to close the window only cancel is that normal?


> I remember from another issue before that changing the GTK theme in Arch with the Breeze theme required extra packages, since the Gtk theme is totally separate from the main Qt window manager theme.


Yes in KDE you need to set GTK theme separely but I have installed both themes as KDE and GTK versions so they should match.

**Comment by mathiascode** [comment]
> tho it seems like there isn't button to close the window only cancel is that normal?

It's normal.

> ![image](https://user-images.githubusercontent.com/11908261/185732187-18784b03-d9cd-44f1-8e38-4e2b97b903e5.png)

That doesn't look completely right, something is disabling client-side decorations. Do you have gtk3-nocsd or similar installed on your system?

> Header Bar off didn't work.

You need to restart Nicotine+ for the change to take effect on dialogs that were already opened before.

**Comment by 3k2** [comment]
> > tho it seems like there isn't button to close the window only cancel is that normal?
> 
> It's normal.
> 
> > ![image](https://user-images.githubusercontent.com/11908261/185732187-18784b03-d9cd-44f1-8e38-4e2b97b903e5.png)
> 
> That doesn't look completely right, something is disabling client-side decorations. Do you have gtk3-nocsd or similar installed on your system?
> 
> > Header Bar off didn't work.
> 
> You need to restart Nicotine+ for the change to take effect on dialogs that were already opened before.

![image](https://user-images.githubusercontent.com/11908261/185948940-09f2e06a-4191-4330-b2b7-0a67c130a387.png)

I deleted gtk3-nocsd package and it was at least in arch linux package section said to install gtk3-classic package. 

[link where it was suggested to remove it](https://aur.archlinux.org/packages/gtk3-nocsd-git)

but now it seems to be working correctly at least in my opinion!

cheers

**Comment by slook** [comment]
Closing since gtk3-nocsd seems to be deprecated anyway there isn't any need for Nicotine+ to support it.
