### ISSUE TITLE
Chat emoji scaling issue

### ISSUE THREAD

**Issue by Forever-A-Hermit** [nicotine-plus/nicotine-plus#2169]
Nicotine+ version:
3.2.5

Operating System/Distribution:
Windows 10 

### Describe the bug
Chat emojis used to appear correctly in Nicotine+ 3.2.4, but are now stretched/scaled incorrectly in 3.2.5 .

### Additional context
Windows scaling on my PC is set to 125%. Everything other than the emojis look fine. Issue persists even after changing Windows scaling to 100%.

![3 2 4](https://user-images.githubusercontent.com/15148336/188020374-43e6af4c-1e78-46c4-8091-90a34670d558.PNG)
![3 2 5](https://user-images.githubusercontent.com/15148336/188020393-f13ca33d-7f56-4ec7-805d-a048d5b4ea39.PNG)

**Comment by slook** [comment]
This is a known issue that is due to the downgraded version of Cairo used to mitigate https://github.com/nicotine-plus/nicotine-plus/issues/2150.

**Comment by mathiascode** [comment]
Closing in favor of #2014
