### ISSUE TITLE
Remember last sorted column for each tab (Downloads, Uploads, Search Files, etc)

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#2170]
### Describe the solution you'd like
When I user the Search Files tab in particular, each time I perform a search I manually sort the results by the Speed column (which takes two clicks: first slowest to fastest, then the more logical fastest to slowest). Would it be possible for each subsequent search to then be automatically sorted by the Speed column and fastest to slowest?

I guess this isn't already being done because new results are always being appended to the bottom as they come in. Maybe results could be continually sorted by the actively sorted column? This however would have the effect of the list jumping around as new searches come in and are, for example, inserted above the point at which you are currently scrolled to, but maybe there is a way to mitigate this?

Other tabs may also benefit from this feature, and I think the sorted columns should persist across sessions.

Any thoughts?

Nicotine 3.2.5

**Comment by mathiascode** [comment]
See https://github.com/nicotine-plus/nicotine-plus/issues/373#issuecomment-696910528

It's been a while since I last looked at the issue, so I may revisit it at some point.

**Comment by slook** [comment]
This idea would work for the Downloads and Uploads tab, but the method of identifying the user's sort order preference for the Search Files and Browse Shares tabs is more complex because of the multiple page tabbed interface.

It might feel like a strange UX to select a sort order in one tab but then switch to another tab, then it might be expected that the remembered sort order would be that which was last viewed, but infact that would not necessarily be the case as the tabs are often switched after performing a sort operation.

Therefore, it might be a more consistent UX to have options in the Preferences for the user to explicitly define the default sort order for the views which have multiple tabs (Shared Files, Browse Shares), and then it would seem logical to have all the default sort options in there as well.

Thus, with explicit options in the Preferences any ad-hoc column sorting operations would be treated as temporary, in order to allow the user to retain their preferred sorting views across sessions without fear of permanently messing things up.

**Comment by redactedscribe** [comment]
It's been so long that I found myself rewriting the same issue. I think it's more well thought out than my original issue.

---

When clicking the _Speed_ column header (or any other numerical column) on the _Search Files_ tab, it sorts from smallest to largest on the first click, and then the opposite way on the second click.

In almost all cases, one has to click twice to get the typically desired sort order: Largest to smallest (i.e. fastest to slowest speed). You could argue the same is desirable for the columns _Size_, _Bitrate_, and possibly _Length_. Where this doesn't make sense is for the _In Queue_ column and arguably the _ID_ column.

**Perhaps the column sorting logic could be adjusted?**

- One option is to invert the default sort order for all numerical columns for the sake of the first set of columns I mentioned (which I think are probably used more often). Though I'd be likely happy enough with this, the quality of the solution isn't great in my opinion.
- The more sound option is to **make it so that the last sort order of a column is remembered, either per session, or across them (which would be ideal):** Currently, if we click on the _Speed_ header (sorted slowest to fastest) and then on any other, e.g. _Folder_, and then back on _Speed_, _Speed_ gets re-sorted (now fastest to slowest). **Instead, when going from any other column back to _Speed_ for example, if the _Speed_ column was sorted _as it was previously_, requiring an additional click to then invert the sorting, this could solve the issue.** How? Every time I click on _Speed_, it'll be the sorted by the order that I usually prefer. This would apply to other columns, e.g. the _ID_ column (smallest to largest; the inverse sort order of _Speed_).

**Comment by slook** [comment]
@redactedscribe Your feature request has been added to the next release candidate. It would be very helpful if you could test the latest build and report back if everything is working as expected for you:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by redactedscribe** [comment]
Other than the PR settling for remembering the sort order for columns in only some of the tabs (i.e. not Search, unfortunate in my opinion), the column which the list is sorted by, and its sort order, do appear to be remembered across sessions correctly. A welcome addition, thanks 👍

---

The somewhat minor issue remains with having to click some columns twice (as I have already attempted to describe above, possibly poorly):

**_All_ columns are sorted in an ascending order (so: 0-9/A-Z) by default.**

**A)** If you look at for example Microsoft's File Explorer, each column has its own default sort order (the sort order for its initial click). Clicking *Name* will sort A-Z (assuming not already sorted by Name), but clicking Size will sort 9-0 (descending). Nicotine+ sorts _every_ column in an ascending order which just means requiring an extra click to sort (most) numerical columns in the typically desirable, descending 9-0 order ("most", because for example in the case of the _In Queue_ column, 0-9 could arguably make more sense). This is what I tried to describe in my first bullet point in my previous comment.

**B)** I failed to explain myself well in my second bullet point: You could go further than simply defining how Nicotine+ should sort the initial clicks of currently unsorted columns: If columns each remembered their sort order (per session), then when they are clicked again (after having sorted the list by a different column), sort the column by the last remembered order. An example: Sort _Note_ column on the _Buddies_ tab by Z-A, then sort by e.g. the _Speed_ column, then sort by _Note_ again: Its order would still be Z-A, not always reverting to the default of A-Z.

So there's a few options for how I see these two ideas being applied:

1. **A + B:** Devs take the time to define what the individual default sort orders for each column should be (potentially laborious), and columns remember their last sort order per session. A new session uses the default sort order for the initial click.
2. **A only:** No remembering of last sort orders. Just friendlier defaults defined.
3. **B only (per session):** No need to define any defaults, all columns all sort in an ascending order as they do currently. For each session, once the user has sorted a column, remember its last order so that when they sort by that column again, it sorts by the last sort, rather than always defaulting to ascending. This means the initial clicks per session may not be ideal (ascending), but once the user has inverted the sort, if they want to sort by that column again, it's in the order they'd likely prefer.
4. **B only (across sessions):** Remembering the last sort orders of each column across sessions would mean clicking on a column is typically always in the order you expect (excluding the very first time you ever click a column since no state has yet been saved for its last sort order).

As mentioned, it's minor, but it does remain a little clunky having to click certain columns twice to sort by what seems the logical order. Based on what I wrote, I'm thinking **B only (across sessions)** would work best: Users define the "default" column sort orders through general use of the software. Perhaps with a "Reset all column sort orders" under Preferences > User Interface.

Thanks.

**Comment by mathiascode** [comment]
If we're going to implement this, I'm leaning towards A only, but Gtk.TreeView doesn't support changing the default order when clicking a column header. We would have to hack around it somehow.

**Comment by mathiascode** [comment]
Columns with numerical sort values are now sorted in descending order on the first click. Please try the latest build and let me know how it works for you.

As you mentioned, there are a few exceptions where this new behavior doesn't make sense (e.g. In Queue). Please list all of them, and I'll see if I can add overrides for these columns.

**Comment by redactedscribe** [comment]
Firstly, I can't test the columns on the _Uploads_ tab: I have no uploads, and no columns are visible in that state.

I think it's probably best to keep the numerical columns without exceptions (other than in the most obvious of cases such as _In Queue_, and _Queue_ on the _Downloads_ and _Uploads_(?) tab). I say this because it could end up feeling to a user like there is no rhyme or reason behind a numerical column's default sorting choice if the default is too subjective, and then clicking between different numerical columns would become a matter of clicking once on some and twice on others if defaults don't align with expectations; **it should be expected that numerical columns sort descending (with rare exception), and alphanumerical columns ascending.**

**The only other numerical column which could have an exception is the _Duration_ column** since File Explorer (and likely other file managers), as well as media players, often have shortest to longest as the default sort for "Length".

It may not be easily possible, but when sorting _Last Seen_ (on the _Buddies_ tab) in a descending order (its default, i.e. most recently seen to least), buddies with no last-seen value (blank) are listed above the most recent buddies. These blank last-seen buddies should be at the very bottom (after "Never seen" I presume). I suggest this because when ordering a list of files by, for example, _Quality_, all audio files with a quality value are listed first, then files with no value (blank) at the bottom (e.g. jpg, log).

The above blanks-before-values probably manifests in other columns too, e.g. _Note_ on the _Buddies_ tab. My expectation is that if I click this column, it'd be ascending (which it is), with buddies with no note value at the bottom. If this was remedied with a broad fix, I'm not sure of the side effects on other columns. Maybe leave this as-is.

Other than that, I don't have any further suggestions. Numerical columns in all tabs appear to sort 9-0 by default, which feels like a small QoL win.

**Comment by mathiascode** [comment]
> It may not be easily possible, but when sorting _Last Seen_ (on the _Buddies_ tab) in a descending order (its default, i.e. most recently seen to least), buddies with no last-seen value (blank) are listed above the most recent buddies. These blank last-seen buddies should be at the very bottom (after "Never seen" I presume). I suggest this because when ordering a list of files by, for example, _Quality_, all audio files with a quality value are listed first, then files with no value (blank) at the bottom (e.g. jpg, log).

This one is subjective in my opinion. Does it make more sense to show the most recently seen (i.e. online) users first, or after the least recently seen ones?

> The above blanks-before-values probably manifests in other columns too, e.g. _Note_ on the _Buddies_ tab. My expectation is that if I click this column, it'd be ascending (which it is), with buddies with no note value at the bottom. If this was remedied with a broad fix, I'm not sure of the side effects on other columns. Maybe leave this as-is.

Not sure if this behavior can be changed easily.

> Other than that, I don't have any further suggestions. Numerical columns in all tabs appear to sort 9-0 by default, which feels like a small QoL win.

Good to hear.

**Comment by redactedscribe** [comment]
> This one is subjective in my opinion. Does it make more sense to show the most recently seen (i.e. online) users first, or after the least recently seen ones?

Right. I guess I didn't ask myself why they're blank. They're online, right? In that case I agree with you. Online first, then most recently seen.
