### ISSUE TITLE
Scanning taking many hours

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#2173]
Nicotine+ version:  3.2.5
Operating System/Distribution: macOS Monterey 12.5.1

### Describe the bug
After updating to 3.2.5, rescanning of my shared folders consistently takes at least 6 hours to complete for over 500,000 files on external drives. Problem persists after uninstalling completely and reinstalling 3.2.4 and then 3.2.5.

### Expected behavior
In the past, a rescan of these files would complete in 5 minutes or less.

**Comment by slook** [comment]
Are you saying that downgrading to 3.2.4 does not resolve the problem?

Does downgrading to 3.2.2 solve the problem?

**Comment by thep50** [comment]
When downgrading to 3.2.2 it just shows a black window, doesn't load properly.

I've tried resetting my mac's PRAM and SMC, checked the drives for errors, still slow scanning when I try to share my entire library. When sharing just a small number of folders from the external drives it scans them quickly enough.

**Comment by slook** [comment]
After the first scan any future scans should be much quicker, is it faster the next time?

Are any errors related to scanning logged?

**Comment by thep50** [comment]
I got through two full 6 hour initial scans so far from an empty library, and the second scan each time has lasted at least an hour without completing, but I haven't gone longer than that yet. I have a second scan still going now and will see how long it goes.

Each time it's completed a scan it gives this error:

> 2022-09-03 17:33:01 Can't save files.db: [Errno 35] Resource temporarily unavailable: '/Users/thep/.local/share/nicotine/files.db'

**Comment by slook** [comment]
That error seems to be the main culprit here. Please also enable the 'Debug Miscellaneous' log category (Log Pane > right-click > Log Categories menu) and report any other related errors.

Please can you determine if [Errno 35] happens also with a small library, of say 10 folders, or if it only happens with a library over a certain size? (if the error appears in all cases then you might as well perform your testing with a small library to save your time).

Does manually deleting all the *.db files before launching Nicotine+ remedy the problem at least for the first scan?

**Comment by thep50** [comment]
Alright, I tried just deleting files.db and fileindex.db and scanned my library in two halves, which took a combined 6 hours again, but it didn't give the error this time. After scanning everything a second time it took only 5 minutes. So all seems good now. Thanks for the help!

**Comment by slook** [comment]
I'm glad you have resolved the issue on your system, thank you for your bug report it is useful to know that you encountered this problem. There must have been some problem with the permissions of the *.db files that already existed from having a previous version of Nicotine+ installed.

It is curious that the error [Errno 35] was encountered after upgrading from Nicotine+ 3.2.4 to 3.2.5, @mathiascode do you have any ideas as to why this scenario had come about for the macOS user?

Given the considerable effort required to perform a rebuild on a large dataset of shares, perhaps this problem could be avoided with a sledge-hammer approach of removing the files from the filesystem before undertaking a full rebuild, such as by means similar to `Shares.load_shares(reset_shares=True)`, or alternatively performing a reset_shares (remove/rmdir) operation if error.startwith("[Errno 35]") to enable retry with the same rebuild source data upon Exception here:

https://github.com/nicotine-plus/nicotine-plus/blob/737d7a4aa7fae1f9ac7ad7b4c0a24aa6c89966b4/pynicotine/shares.py#L172-L175

**Comment by mathiascode** [comment]
@slook That error typically means the shelve file (.db) is already open for writing somewhere else when attempting to open it. https://docs.python.org/3/library/shelve.html#restrictions

**Comment by slook** [comment]
What happens if the close() fails silently, then open() on the next line will also fail:

https://github.com/nicotine-plus/nicotine-plus/blob/737d7a4aa7fae1f9ac7ad7b4c0a24aa6c89966b4/pynicotine/shares.py#L165-L169
It would help to separate these Exceptions, and do something else if we cannot close the old handle.

If it was close() that caused the error, then the error message is misleading and seems unnecessary, we should try again or resort to removing the shelve files from the filesystem to allow a write instead of an overwrite.

The error presents when share_version is None which causes the full_rebuild, upon which an opportunity is missed to somehow remedy the situation that could be done here:
https://github.com/nicotine-plus/nicotine-plus/blob/737d7a4aa7fae1f9ac7ad7b4c0a24aa6c89966b4/pynicotine/shares.py#L209-L211

**Comment by mathiascode** [comment]
I think the recent changes in `shares.py` should largely fix this.

**Comment by slook** [comment]
@thep50 Update to the [current stable version of Nicotine+](https://nicotine-plus.org/doc/DOWNLOADS.html#macos) 3.2.6 to verify that shares scanning continues to operate correctly on your system. Please always feel free to open an issue if you encounter any further problems. Thank you for your bug report.
