### ISSUE TITLE
Offline messages not popping up a tab

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2174]
3.2.5  •  GTK 3.24.34
windows 11

When a user sends a message to me and i am offline, usually it pops up in a message when i login, now i can only see it in the debug box/log... ill wait for more later or tomorrow to verify it is persistent 

as always anything i can do to help test it let me know

EDIT: so the user has not come back and i cannot verify that i didn't have the ip ignored,, so disregard for now sorry

**Comment by slook** [comment]
Thank you for your bug report @woollarding please leave this issue open until you have verified for sure that a bug doesn't exist, and feel free to suggest a course of action if the behaviour of offline message notifications needs to be improved in some way.

**Comment by mathiascode** [comment]
> EDIT: so the user has not come back and i cannot verify that i didn't have the ip ignored,, so disregard for now sorry

I can't reproduce this issue at least.

**Comment by mathiascode** [comment]
Feel free to reopen the issue if you encounter it again.
