### ISSUE TITLE
Users can't connect to me after upgrade to 3.2.5 (transfers don't work) on OpenBSD

### ISSUE THREAD

**Issue by heavytrip** [nicotine-plus/nicotine-plus#2175]
Nicotine+ version: 3.2.5
Operating System/Distribution: OpenBSD 7.1
Python version: 3.9.13

### Describe the bug
Users can't connect and download from me after upgrade to 3.2.5, everything works when downgrade to 3.2.4

### Steps to reproduce the bug
1. Run 3.2.4, wait for several users to connect in uploads tab, transfers are OK, then close the program
2. Upgrade to 3.2.5 (with pip), run the program, transfer list is completly empty in uploads tab and nothing happens there for several minutes, nothing shows up, close the program
3. Downgrade to 3.2.4, run the program, previous users are connecting again immediately, transfers are OK

**Comment by heavytrip** [comment]
config path is the same between versions:
[Misc] Using configuration: /home/<user>/.config/nicotine/config

/home/<user>/.local/share/nicotine/uploads.json is always empty, with "[]" inside and 2 bytes
there is also the same uploads.json.old with "[]" inside, 2 bytes in size
the content and size of these files always remains the same, regardless of whether nicotine is currently running or not, only the modification time of the file is changing also while program is running every minute or so

My shared folders appear as they are supposed to in 3.2.5

**Comment by slook** [comment]
Are you saying that when you switch back to 3.2.4 that previous Uploads history is visible but it is not in 3.2.5?

Does searching, downloading and chat work okay in 3.2.5?

**Comment by heavytrip** [comment]
When I switch back to 3.2.4 the file transfers are starting to users that are online, I usually have a few users downloading from me at any time..

When some user goes offline his queue usually disappears from my Uploads tab after some time, I am not sure if this is expected.

I have enabled Autoclear finished / canceled uploads from transfer list in settings.

Searching and downloading of files works on 3.2.5, but it seems I can't upload to anyone.

**Comment by slook** [comment]
If you have autoclear enabled then it would be expected that items disappear for offline users who are considered to be cancelled transfers.

> it seems I can't upload to anyone

Is this is based on your own observations of the Uploads activity, or has another user directly reported to you that this is actually the case?

You might try looking for unusual errors in the "Connections" log category, perhaps comparing the pattern of behaviour between versions to spot a clue as to what is going on here.

**Comment by heavytrip** [comment]
I'm running git master now testing specific commits and uploads breaks on this commit: https://github.com/nicotine-plus/nicotine-plus/commit/0d5efbea6af5705a10cf6efa17608dff9681fb6b

on previous one, ie. https://github.com/nicotine-plus/nicotine-plus/commit/0271797aa040c935483aee892dc18883fc45ed6c uploads works fine

**Comment by slook** [comment]
Nice work!

From what I remember @mathiascode applied https://github.com/nicotine-plus/nicotine-plus/commit/0d5efbea6af5705a10cf6efa17608dff9681fb6b in the process of troubleshooting and mitigate issue #2154 (in progress).

It is interesting that there is/was a mysterious OpenBSD specific workaround mentioned in that commit.

**Comment by mathiascode** [comment]
@heavytrip Can you check if this branch changes anything?

`git clone -b slskproto-test --depth 1 https://github.com/mathiascode/nicotine-plus.git`

> It is interesting that there is/was a mysterious OpenBSD specific workaround mentioned in that commit.

Yes, there was an issue with the selectors module in the past, and I think that module is causing the issues again.

**Comment by heavytrip** [comment]
> Can you check if this branch changes anything?
no, uploads does not work with this branch

**Comment by mathiascode** [comment]
Can you try the latest commit in the same slskproto-test branch (`git pull --rebase`)?

**Comment by heavytrip** [comment]
I can't connect to slsk server at all with latest commit in slskproto-test branch

2022-09-08 00:45:50 Connecting to server.slsknet.org:2242
2022-09-08 00:46:30 Cannot connect to server server.slsknet.org:2242: [Errno -5] no address associated with name

**Comment by slook** [comment]
The slskproto-test does seem to work fine here on MX Linux Debian.

**Comment by heavytrip** [comment]
Issue with connection to server.slsknet.org yesterday was only temporary.

This commit https://github.com/mathiascode/nicotine-plus/commit/1d9eb444694825a99063617cedc0379df00c04e9
seems to solve the problem, inbound connections are established now.

I will do some longer tests and report back later.

**Comment by mathiascode** [comment]
I've backported the fix to the `3.2.x` branch. Could you verify that it works? Thanks!

`git clone -b 3.2.x --depth 1 https://github.com/nicotine-plus/nicotine-plus.git`

**Comment by heavytrip** [comment]
works OK now on 3.2.x branch
