### ISSUE TITLE
Window resizing glitchy on MacOS 12.1

### ISSUE THREAD

**Issue by rpmindroid** [nicotine-plus/nicotine-plus#2178]
Nicotine+ version:  3.2.5
Operating System/Distribution: MacOS 12.1

### Describe the bug
Choppy resizing of window, with black areas appearing.

### Expected behavior
Fluid like other MacOs apps.

### Steps to reproduce the bug
Open nicotine, resize / zoom / full screen window.

### Additional context
I have a screen recording I could send by WeTransfer or something.

**Comment by slook** [comment]
Please specify your systems GTK version displayed in the About Nicotine+ dialog?

You can attach a small video file in standard formats MP4 or MOV etc by drag n drop into a GitHub comment here.

**Comment by mathiascode** [comment]
I don't think there's anything that can be done for GTK 3 anymore. Could you check if the GTK 4 version works better? https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos

**Comment by rpmindroid** [comment]
Hey all.
I didn't attach my screen recording cause it was 250+ Mb.
My versions were Nicotine 3.2 / GTK 3.24.34, and indeed Nicotine 3.3 / GTK 4.6.7 works fine.
Now waiting for the new stable release.
Thanks a lot! :)

**Comment by slook** [comment]
Thanks for your report @rpmindroid you might as well stick with the master testing branch on Nicotine+ 3.3.0 with GTK 4 (now 4 is the default) and be sure to let us know if any issues arise on your installation, macOS testers are rare so your help is very valuable to us and the community.

The next stable release will be Nicotine+ 3.2.6 you may want to test the 3.2.x branch [here](https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md#macos) that would also be helpful if you report any issues :)
