### ISSUE TITLE
Someone try to hack my Nicotine+ app or possible a bug?

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2183]
Nicotine+ version:  3.2.2
Operating System/Distribution: Windows 10 LTSB 2016 x64

19:17:51 Peer message type 925775114 size 74 contents bytearray(b'.27-log\x00@m\x03\x00J\x0b%5toaR\x00\xff\xf7\x08\x02\x00\xff\x81\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00K**a7\x0fPaY\x0cb\t\x00mysql_native_password\x00') unknown, from user: robertasergio, 187.15.5.35:32601
19:19:40 Peer message type 925775114 size 74 contents bytearray(b'.27-log\x00zn\x03\x00%Ma\x1d\x16F4\x0c\x00\xff\xf7\x08\x02\x00\xff\x81\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18%nM)t5X*\x17\x1f \x00mysql_native_password\x00') unknown, from user: robertasergio, 187.15.5.35:32601
20:09:43 Peer message type 925775114 size 74 contents bytearray(b'.27-log\x00\x17\x85\x03\x00\x04gM,i\x03w`\x00\xff\xf7\x08\x02\x00\xff\x81\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00^<\x05aCtr]{--q\x00mysql_native_password\x00') unknown, from user: robertasergio, 187.15.5.35:32601
20:11:28 UPnP: внешний порт 2234 успешно переброшен на локальный IP-адрес 192.168.1.147 порт 2234
20:37:44 Peer message type 925775114 size 74 contents bytearray(b'.27-log\x00\xda\x89\x03\x00ft;4Gd_\x0f\x00\xff\xf7\x08\x02\x00\xff\x81\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00fK\x1b;C:\x012\x1fE@-\x00mysql_native_password\x00') unknown, from user: robertasergio, 187.15.5.35:32601
20:44:50 Peer message type 925775114 size 74 contents bytearray(b'.27-log\x00{\x8c\x03\x00%*\\\x1fC\x06@3\x00\xff\xf7\x08\x02\x00\xff\x81\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00J\x0b\x1d[ \x1b,<fxHC\x00mysql_native_password\x00') unknown, from user: robertasergio, 187.15.5.35:32601
21:11:28 UPnP: внешний порт 2234 успешно переброшен на локальный IP-адрес 192.168.1.147 порт 2234
22:09:28 Peer message type 925775114 size 74 contents bytearray(b'.27-log\x00Q\x90\x03\x0085\x19\x1e\x14gj&\x00\xff\xf7\x08\x02\x00\xff\x81\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00B0\x1caL\x0bz\x0c6x.\x06\x00mysql_native_password\x00') unknown, from user: robertasergio, 187.15.5.35:32601
22:11:28 UPnP: внешний порт 2234 успешно переброшен на локальный IP-адрес 192.168.1.147 порт 2234

Screenshot:

![2022-09-15_22-10-31](https://user-images.githubusercontent.com/31162059/190441352-69d67196-b9c0-48f9-8940-f62e239aeb7d.png)

**Comment by mathiascode** [comment]
My guess is that something on that user's system is hijacking all connections to send that message. Since it's not a Soulseek protocol message, it doesn't cause any harm to us at least.

Those kind of log messages were moved to the `Miscellaneous` debug log category recently to avoid spam.

**Comment by SnIPeRSnIPeR** [comment]
Ok, thanks!
