### ISSUE TITLE
Search Files: Keyboard shortcut to focus search bar

### ISSUE THREAD

**Issue by hejops** [nicotine-plus/nicotine-plus#2186]
### Describe the solution you'd like
In the "Search Files" window, the ability to focus the search bar with a keyboard shortcut, e.g. `/`, to make repeated searches faster.

### Additional context
Focus is lost after a search is performed, and a mouse click (or multiple `TAB` presses) is required to regain focus.

**Comment by mathiascode** [comment]
We should probably add a F6 shortcut (similar to browsers) to switch between the search entry and main view.

**Comment by mathiascode** [comment]
There are two new shortcuts, similar to web browsers:
- Alt+D: focus the main text entry
- F6: change focus between the main text entry and content

**Comment by hboetes** [comment]
Would ctrl-L, just like in browsers make sense?
