### ISSUE TITLE
REOPENING ISSUE: Offline messages not popping up in tabs

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2189]
Nicotine+ version:  3.2.5  •  GTK 3.24.34
Operating System/Distribution: Windows 11

### Describe the bug
When offline, some messages are not being sent to PM and only show up in the debug box

### Expected behavior
for all messages to pop up tabs weather sent offline or not

### Steps to reproduce the bug
not 100% sure, just something i have noticed since the last update

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Do the messages show up in the history if you manually open private chat tabs for the users?

**Comment by woollarding** [comment]
no the message does not show up in the chat history when i manually open tab for user
