### ISSUE TITLE
Cannot find GTK+ 2.24.X, please install it.

### ISSUE THREAD

**Issue by fsouzamoraes** [Nicotine-Plus/nicotine-plus#219]
even with all versions of gtk installed, still got the error message. i am using slackware-current

**Comment by mathiascode** [comment]
Is this on version 1.4.1? I suggest testing the master branch (1.4.3) if you haven't, it's the in-development GTK3/Python3 port which will be released as version 2.0.0 in the near future. It should be quite stable at this point, but bug reports are welcome.

**Comment by 0pLuS0** [comment]
@fsouzamoraes 

As mathiascode pointed out, make sure you are cloning from the Master branch, to get 1.4.3;

```git clone https://github.com/Nicotine-Plus/nicotine-plus.git```

I'm using the Master branch in Slack 14.2.

I also have a ```nicotine-plus.SlackBuild``` I've attached. I removed the locale translations, you can always remove that line, if you want them.

[nicotine-plus.SlackBuild.zip](https://github.com/Nicotine-Plus/nicotine-plus/files/4732820/nicotine-plus.SlackBuild.zip)

**Comment by mathiascode** [comment]
@kiplingw Close?
