### ISSUE TITLE
Downloading a file that contains ñ character crashes the app

### ISSUE THREAD

**Issue by psociety** [nicotine-plus/nicotine-plus#2191]
Nicotine+ version:  Latest? (https://bitbucket.org/freddywullockx/nicotineplus/)
Operating System/Distribution: Linux - Docker container

### Describe the bug
Downloading a file that contains ñ character crashes the app

### Expected behavior
Shouldn't crash

### Steps to reproduce the bug
1. Search `coño`
2. Try to download any song containing that word

### Additional context
![image](https://user-images.githubusercontent.com/29523682/191314292-a7e3a278-ee2e-410d-96a5-c27063faea37.png)

**Comment by mathiascode** [comment]
That looks like Nicotine+ 3.0.6, which is quite old. The issue should be fixed in recent Nicotine+ versions.

I see Nicotine+ is installed from our stable PPA in the Dockerfile, so I assume it should be fairly easy to get the newest version.

**Comment by psociety** [comment]
oh, i apologize, i downloaded the container today and i thought it would be up to date.
