### ISSUE TITLE
The flatpak version of Nicotine+ is using the wrong language

### ISSUE THREAD

**Issue by johnnada** [nicotine-plus/nicotine-plus#2194]
Nicotine+ version:  3.2.5 
Operating System/Distribution: Debian Testing

### **Describe the bug**

Hello, my operating system is set to the french (fr_FR) locale but Nicotine+ is using the english language.

### **Additional context**

The 3.2.5 debian packaged version of Nicotine+ is using the french language.

Other flatpak applications installed on my system are using the french language.

Thank you for this wonderful application 🙂

**Comment by mathiascode** [comment]
Fixed in 5d6f0008b4410fc43ebeeb5d90536dd0097a605a

> Thank you for this wonderful application

Glad you like it. :)

**Comment by slook** [comment]
Thank you for your bug report @johnnada please install the [latest unstable Flatpak build of Nicotine+](https://nicotine-plus.org/doc/TESTING.html#flatpak) 3.2.6.rc1 to verify if the translations are now working as expected?

**Comment by johnnada** [comment]
The translation works as expected now, thanks a lot !
