### ISSUE TITLE
Paste from clipboard in search section makes crash

### ISSUE THREAD

**Issue by lxegs** [nicotine-plus/nicotine-plus#2195]
Nicotine+ version:  3.3.0 dev 2 // 3.3.0 dev 3
Operating System/Distribution: Windows 11 22H2

### Describe the bug
when pasting text content from clipboard in the search section, nicotine+ instantly crashed

### Expected behavior
text pasted in search field

### Steps to reproduce the bug
launch nicotine+
copy text in clipboard from notepad
paste in search field

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
I can't seem to reproduce this issue on my system. What's your system language and keyboard layout?

**Comment by hboetes** [comment]
Can you add the stack trace output of the crash? The funny messages you get to see after the crash.

**Comment by lxegs** [comment]
system language and keyboard layout are in french, windows is in french version (provided at install not by adding additional language pack)

nothing in debug log , file is created in filesystem but nothing inside

**Comment by mathiascode** [comment]
I thought it could be related to the system language, but that doesn't seem to be the case either.

A few questions:
- Do you have any clipboard manager or similar software installed?
- Does the crash happen when pasting any text from any location?
- Does the crash only happen in the search text entry, or any text entry/view in the program?

**Comment by lxegs** [comment]
Do you have any clipboard manager or similar software installed? --> nop, just basic windows clipboard manager

Does the crash happen when pasting any text from any location? yes, tried from copying from notepad, chrome, word ....

Does the crash only happen in the search text entry, or any text entry/view in the program? i can reproduce in the search entry from the "share browsing" panel

Does it make any difference if you paste with the keyboard shortcut (ctrl-v) or context menu item? --> no

I have observed that it crashes only when i try to parse at the moment where in the search box, the cursor is not blinking but static / always on ; if blinking, it works --> going to another panel makes cursor blinking again

**Comment by mathiascode** [comment]
I believe it's this issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/5207

Which was fixed about 3 days ago: https://github.com/msys2/MINGW-packages/pull/13269

Could you download the latest unstable build of Nicotine+ and confirm if the issue is fixed?

**Comment by lxegs** [comment]
I have downloaded the latest unstable version and i cannot reproduce the bug

issue is fixed

thanks

**Comment by mathiascode** [comment]
Thanks for confirming!
