### ISSUE TITLE
Uploads partly broken

### ISSUE THREAD

**Issue by EhotPotaskun** [nicotine-plus/nicotine-plus#2197]
Nicotine+ version:  Nicotine+ 3.2.5 (builded from latest stable tarball)
Operating System/Distribution: RaspberryPi OS

Linux 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
GTK 3.24.24
Python 3.9.2 (default, Feb 28 2021, 17:03:44)

### Describe the bug
Right after Nicotine++ starts there's a couple of the uploads from the same couple of users popped up which always staying on 0% in "Transfering/User logged off" status (mostly album's Cover.jpg files). They returning after some time even when i tap "Clear Finished". It's status keeps rotating like "Transfering -> User logged off -> Cancelled -> Transfering..." etc. I have necessary ports opened on my ISP hardware so i could check them up with internal Nicotine++ link/any other tool so i guess them working well. In other hand some users have no visible troubles, uploading just starts and stops when it should without looping. I also tried to rescan my shares and clear both .local/nicotine/ and .config/nicotine/ directories but no luck.

### Expected behavior
No repeated upload's attempts, successful uploads, finished/broken uploads should go after "Clear Finished" button is pressed

### Steps to reproduce the bug
???

### Additional context
Screenshots, logs, stacktraces or relevant information.
Providing some debug logs i made, one for successful upload's attempt of couple flac files (success_flacs.txt), one for failed (fail_flacs.txt) and two for looped jpg's uploads (fail_jpg1.txt and fail_jpg2.txt). I filtered out only problematic "user/ip address/upload attempt" parts and purge some sensitive data from logs. Feel free to ask for more complete logs and any additional info. Thanks!

[fail_flacs.txt](https://github.com/nicotine-plus/nicotine-plus/files/9722291/fail_flacs.txt)
[fail_jpg1.txt](https://github.com/nicotine-plus/nicotine-plus/files/9722292/fail_jpg1.txt)
[fail_jpg2.txt](https://github.com/nicotine-plus/nicotine-plus/files/9722294/fail_jpg2.txt)
[success_flacs.txt](https://github.com/nicotine-plus/nicotine-plus/files/9722295/success_flacs.txt)

**Comment by slook** [comment]
This sounds like it might be similar to #1933 which was recently fixed in https://github.com/nicotine-plus/nicotine-plus/commit/cf5fefb914adfdfb29b579d6187277ddff99668c

@EhotPotaskun Please install the [latest unstable build of Nicotine+](https://nicotine-plus.org/doc/TESTING.html) 3.2.6.rc2 and verify that uploads are working as expected?

**Comment by mathiascode** [comment]
The behavior observed in fail_flacs.txt was fixed in cf5fefb914adfdfb29b579d6187277ddff99668c. The jpg issue is a different one, it seems like the user never responds to the upload request, but still re-queues the files as expected when Nicotine+ sends a UploadFailed message.

**Comment by slook** [comment]
Could it be related to the peer's download exclusion filters?

**Comment by mathiascode** [comment]
> Could it be related to the peer's download exclusion filters?

Not as far as I know. Soulseek NS should reject the download with a "Disallowed extension" message, and SoulseekQt/Nicotine+ shouldn't send a download request at all.

I could perform some tests to verify this though.

**Comment by mathiascode** [comment]
I've added some more logging in 27dd5df2f604fa948a94aa85cdac3132e08c8256 to hopefully aid in debugging this issue.

**Comment by slook** [comment]
@EhotPotaskun Please update to the [latest unstable build of Nicotine+](https://nicotine-plus.org/doc/TESTING.html) 3.2.6.rc2 and post another debug log showing the issue in more detail.

**Comment by EhotPotaskun** [comment]
@slook Should i pin complete log or filtering out only problematic users should be okay?

**Comment by slook** [comment]
Just change all the usernames/ip's with some_string, but keep them all unique such as 'user1' 'ip1', 'user2' 'ip2', etc. It is also a good idea to change filenames if they refer to the title of copyrighted works.

Alternatively you can send unfiltered log privately to the email address on [mathiascode](https://github.com/mathiascode)'s GitHub profile, with the title of this issue as subject.

**Comment by EhotPotaskun** [comment]
@mathiascode I just sent you a complete log via email

**Comment by mathiascode** [comment]
Thanks, I see where the bug happens now. For some reason, these users are sending a file offset (at what point in the file they want to continue downloading from) that's the same as the file size, and we're not correctly marking these uploads as finished.

**Comment by mathiascode** [comment]
Regression in https://github.com/nicotine-plus/nicotine-plus/commit/6aa46d697ac47c39e953aaefc4c6b0a839e6ddb6#diff-9809d81eb6dc9a7beabdb30bd797cf82b81019ebb1a7bf26ffab80af335e2cbb

**Comment by slook** [comment]
@EhotPotaskun Please update to the [latest unstable build of Nicotine+](https://nicotine-plus.org/doc/TESTING.html) 3.2.6.rc2 to verify the bug is fixed?

**Comment by EhotPotaskun** [comment]
@slook I guess it is only partly fixed because uploading slots still returning on every Nicotine's startup. @mathiascode I send you some new logs via email

**Comment by mathiascode** [comment]
If the user keeps requesting the file, there's probably an issue moving the file to the download folder on their end. Not much we can do in this case.
