### ISSUE TITLE
Specific error message when closing Nicotine client

### ISSUE THREAD

**Issue by Subject43** [nicotine-plus/nicotine-plus#2212]
Nicotine+ Version: 3.2.2
GTK Version: 3.24.33
Python Version: 3.9.10 (main, Mar 14 2022, 18:37:07)  [GCC 11.2.0 64 bit (AMD64)]
Operating System/Distribution: Windows 7 (64-Bit)

### Description:
Yesterday, while closing Nicotine, I received this error message:

Type: <class 'KeyError'>
Value: <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/pynicotine.py", line 288, in quit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 670, in abort
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 608, in server_disconnect
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1071, in close_connection
  
  The client also directed me to this web page. I couldn't find this issue anywhere already, so I hereby submit it.. hope this helps!

### Expected behavior
Closing.

### Steps to reproduce the bug
Not sure, this was the only time it happened. The client was still transferring some files though, but that usually doesn't give any problems.

**Comment by mathiascode** [comment]
Thanks for the bug report. This is fixed in the latest version of Nicotine+ (3.2.5).

Since you're using Windows 7, could you test Nicotine+ 3.2.6rc3 and verify that it works well? Would be much appreciated, since we don't have any Windows 7 testers anymore. You will be able to upgrade to stable 3.2.6 normally once it's released.

https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by Subject43** [comment]
Hi, thanks for the quick reply.

Sure, no problem.. happy to help out! I've installed the release candidate.

**Comment by slook** [comment]
Thanks for testing it out, please feel free to open an issue if anything needs fixing @Subject43 :)
