### ISSUE TITLE
Nicotine+ Crashes with this error message on launch

### ISSUE THREAD

**Issue by roland-tb303** [nicotine-plus/nicotine-plus#2213]
Nicotine+ version:  3.3.0.dev3
GTK Version: 4.8.1
Python Version: 3.10.8 (main, Oct 11 2022, 20:04:56) [GCC 12.2.0]
Operating System/Distribution: Arch Linux

### Describe the bug
I haven't launched Nicotine in a while, and i have done some updates in that time, one of which was probably a GTK update of some sort (and maybe a python update). I launched Nicotine earlier to refresh some folders, and I got said error message which provided below. I installed Nicotine+ through the AUR, its package is called nicotine-plus-git.
Could be just specific to my system but if any one else is having the problem you can state your versions.

### Expected behavior
Nicotine to launch normally.

### Additional context
[nicotinebug.txt](https://github.com/nicotine-plus/nicotine-plus/files/9790068/nicotinebug.txt)

**Comment by mathiascode** [comment]
Was there another error message before the one you attached?

**Comment by slook** [comment]
@roland-tb303 if there are cascading errors sometimes the Critical Error dialogs get stacked ontop of each other, usually the first one is most relevant as to the actual cause of the crash, and the rest are related to failures to properly shutdown due to the error.

Alternatively you may invoke Nicotine+ with the ./`nicotine` command to get the console output in the terminal window.

**Comment by roland-tb303** [comment]
Just started Nicotine again after some updates and the bug apparently solved itself, Nicotine opens normally.

i do recall there being an error message something along the lines of "Nicotine has crashed and will need to close", but nothing more than that.

tbh that crash was kinda weird, and idk what the cause of it was.

**Comment by slook** [comment]
Great news! Thanks for keeping us posted.

Please do let us know if anything strange happens again, there are some big changes under the hood coming up soon, so your time is much appreciated testing it :)
