### ISSUE TITLE
Notifications for wish list results

### ISSUE THREAD

**Issue by NightProgramming** [nicotine-plus/nicotine-plus#2221]
SoulseekQt by default displays a flashing icon in the task bar, when the wish list feature finds some tracks. So there is no chance to miss it even if the window is minimized and even if the user was away from the computer and then returns to it later.

It would be nice if Nicotine+ had the option to show a notification or do the taskbar icon flashing thing (obviously not helpful when minimized to tray) or/and play a sound when wish list search results appear. I think right now it just silently opens a tab under "Search files" and the blue circle icon appears.

Tags:
wishlist

**Comment by mathiascode** [comment]
I think a notification bubble and category in Preferences -> User Interface -> Notifications would be feasible. That would also play a sound if they're enabled.
