### ISSUE TITLE
Unknown config option 'filterlength' in section 'searches'

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2228]
On Manjaro Linux I get the following message when I option the program.
```
Unknown config option 'filterlength' in section 'searches'
Loading GTK 3.24.34
Loading Python 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0]
Loading Nicotine+ 3.2.6
```
I've just updated to 3.2.6 and I don't recall seeing this message before the update.

**Comment by slook** [comment]
It might be a good idea to move this log entry into the debug log, since it is not really an important enough problem for it to be in the standard log.
