### ISSUE TITLE
Show users with similar files

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2239]
Count the number of files that are the same as our files for all users and show a list of users sorted by the ratio of same files over total files. This could be a tab on the similar users list that is available right now. I think this would be more helpful than that feature to discover new files we might like.

I don't know if nicotine uses some kind of hash to keep track of the files, but this will probably only be possible if that's the case.

**Comment by slook** [comment]
> This could be a tab on the similar users list that is available right now. I think this would be more helpful than that feature to discover new files we might like.

Whilst the OP's proposal is not viable, I do agree that the existing Interests features could be somehow better implemented, no idea exactly how, maybe some sort of integration with other parts of the interface such as a visual indicator in the search and/or chats as to if a peer is known to be a similar user.

**Comment by JediMaster25** [comment]
I've yet to see a similar user with files that I want, so I don't think expanding on that is necessary.

**Comment by slook** [comment]
You are probably correct really the Interests feature provides nothing more than novelty value.
