### ISSUE TITLE
Save wishlists automatically after closing the corresponding window

### ISSUE THREAD

**Issue by paveloom** [nicotine-plus/nicotine-plus#2249]
### Describe the solution you'd like
I would like wishlists to be saved automatically after closing the corresponding window.

### Additional context
Frequent crashes of the application result in loss of the changes made to wishlists.

**Comment by mathiascode** [comment]
This can be done, but if they are any crashes other than #2250, they should be reported and fixed.

**Comment by Paveloom** [comment]
Yup, on a lookout for those.

**Comment by mathiascode** [comment]
Have you experienced any crashes recently?

**Comment by paveloom** [comment]
No. I'm on the latest stable version, though.
