### ISSUE TITLE
In the downloads tab, filter by filename

### ISSUE THREAD

**Issue by ra-om** [nicotine-plus/nicotine-plus#2251]
Hi, I'm using nicotine 3.2.6 from pip, and as far as I can tell, the filter only works for usernames instead of folder or filenames. Is there a setting somewhere I'm overlooking?

**Comment by slook** [comment]
Good spot @ra-om, quick-search has been expanded to all text columns in latest master, if you would like to test it then [install Nicotine+ 3.3.0.dev3](https://nicotine-plus.org/doc/TESTING.html#pip). Please do let us know if you spot anything else that isn't quite right.

**Comment by ra-om** [comment]
Amazing, TYVM!

A shortcut or button to highlight next match would be nice also

**Comment by mathiascode** [comment]
> A shortcut or button to highlight next match would be nice also

Press the up/down arrow keys when the search field is visible.

**Comment by slook** [comment]
It is unexpected that the enter key activates the selected row when the search field is active.

Would it be feasible to implement `F3` and `Shift+F3` shortcut accelerators keys here?

**Comment by mathiascode** [comment]
The treeview search entry is private in GTK, so no.
