### ISSUE TITLE
Nicotine+ not connecting on mac

### ISSUE THREAD

**Issue by idonttalkmachine** [nicotine-plus/nicotine-plus#2283]
Nicotine+ version:  3.2.7
Operating System/Distribution: macOS Big Sur 11.7.2

### Describe the bug
Everytime I try to connect to nicotine+ on my mac it shows the following error: 

2022-12-15 19:58:30 Loading GTK 3.24.34
2022-12-15 19:58:30 Loading Python 3.10.8 (main, Oct 13 2022, 10:19:13) [Clang 12.0.0 (clang-1200.0.32.29)]
2022-12-15 19:58:30 Loading Nicotine+ 3.2.7
2022-12-15 19:58:30 Listening on port: 2234
2022-12-15 19:58:30 Loading plugin system
**2022-12-15 19:58:31 UPnP: Failed to forward external port 2234: Error code 606: Action not authorized**
2022-12-15 19:58:31 Connecting to server.slsknet.org:2242
2022-12-15 19:58:33 Cannot connect to server server.slsknet.org:2242: Timed out

The annoying part is that I have nicotine on my Windows, and it works perfectly fine there, so I don't think it's a connection issue. Also I can use SoulSeekQT on my mac, and it's working just fine too.

There is something that I noticed, and it's that on Windows, nicotine actually shows my IP on the Network Settings, meanwhile on mac it doesn't appear, as if it couldn't connect to my computer somehow? I really don't know.

### Additional context
<img width="767" alt="image" src="https://user-images.githubusercontent.com/120674780/207948792-283fe855-723e-4954-8390-7e769f9752dd.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/120674780/207948901-542bc9f8-97bf-4338-89dc-afb788d9ca71.png">

It's been days already trying to deal with this problem! I'd really appreciate some help.

Thank you in advance.

**Comment by mathiascode** [comment]
> There is something that I noticed, and it's that on Windows, nicotine actually shows my IP on the Network Settings, meanwhile on mac it doesn't appear, as if it couldn't connect to my computer somehow? I really don't know.

The public IP is only set once you've connected to the server and it has sent your IP.

A few questions:
- Do you use any VPN, firewall (e.g. Little Snitch) or similar on the macOS machine?
- Is the network the exact same on your Windows and macOS machines?
- Have you specified a network interface in Preferences -> Network. If this is the case, try leaving the text entry blank. If not, could you test the available network interfaces one by one to see if any of them work? (note that you need to restart Nicotine+ after selecting an interface)

**Comment by idonttalkmachine** [comment]
oH MY god i feel terribly stupid... it worked when i changed the network interface T_T
THANK YOU A LOT!

**Comment by mathiascode** [comment]
Glad it works!

> Though i keep getting this error but i dont think its too important?

Have you forwarded the listening port manually? In that case, UPnP won't be able to do it, and will complain about a port forwarding already being present.

If you haven't forwarded the port manually, I think the error should go away after about 24 hours.

**Comment by mathiascode** [comment]
Closing, since this issue is resolved.
