### ISSUE TITLE
Nicotine+ split-tunneling connection to server issue

### ISSUE THREAD

**Issue by bresso07** [nicotine-plus/nicotine-plus#2285]
Nicotine+ version:  3.2.7
Operating System/Distribution: Windows 64 bit

### Describe the bug
Connection time-out when using Nicotine+ behind a VPN (Private Internet Access' split-tunneling). HOWEVER, no such issues with SoulseekQT. (Cannot connect to server [server.slsknet.org:2242](https://server.slsknet.org:2242/): Timed out - The server seems to be down or not responding, retrying in X seconds).)

### Expected behavior
Nicotine+ to connect to the network without timing out, like SoulseekQT

### Steps to reproduce the bug
Install Nicotine+, install PIA, create split-tuneling rule to force Nicotine+ to connect only through the VPN

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by bresso07** [comment]
Temp workaround seems to be to connect without any VPN whatsoever, wait for successful soulseek server connection, activate split tunneling, connect to VPN, disconnect from soulseek server and reconnect. Not ideal, haha.

**Comment by mathiascode** [comment]
Can you confirm if the issue also exists in the development version of Nicotine+? https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by bresso07** [comment]
Thanks for the quick reply!!   I tested with the nightly build (3.3), and it was the same.

HOWEVER, I found out what is causing the issue. It's a setting within PIA. It only affects Nicotine+'s ability to connect (SoulseekQT can still connect no matter what option is selected (it's about the nameserver routing through VPN or following the app rules). Here's an image to hopefully make it clearer: https://ibb.co/sF1C8d1

**Comment by slook** [comment]
![image](https://user-images.githubusercontent.com/88614182/208321526-8c818518-ba73-4abe-b820-ba5bfab7f1c3.png)

**Comment by bresso07** [comment]
Yes, you have to set the nameservers item to VPN DNS only for Nicotine+ to connect.

**Comment by francisuk1989** [comment]
Another idea is to set the network interface under nicotine+ so you don't need to worry about Split Tunneling

1)
Connect the VPN with Split Tunneling for temporary, Go to Settings/Preferences > Network > Network Interface and then select the VPN interface and then apply and exit,
2)
Switch off split tunneling for N+ and reload N+ and you see that it will stay on the VPN interface you choice.

**Comment by mathiascode** [comment]
Binding to network interfaces is not yet implemented on Windows: https://github.com/nicotine-plus/nicotine-plus/issues/871#issuecomment-1422417767

I currently don't have a VPN with split-tunneling functionality, so I haven't been able to debug this issue so far.

**Comment by slook** [comment]
Blocked until #871 is implemented on Windows, then the OP can test it [as suggested above](https://github.com/nicotine-plus/nicotine-plus/issues/2285#issuecomment-1436041892).

**Comment by francisuk1989** [comment]
> Binding to network interfaces is not yet implemented on Windows: [#871 (comment)](https://github.com/nicotine-plus/nicotine-plus/issues/871#issuecomment-1422417767)
> 
> I currently don't have a VPN with split-tunneling functionality, so I haven't been able to debug this issue so far.

Douh, i forgot about WIndows users, my bad.

**Comment by mathiascode** [comment]
This behavior doesn't make much sense to me. According to PIA's help center, "Follow App Rules" will use the default DNS for apps that don't have VPN enabled, and PIA's DNS for apps that have enabled it. In Nicotine+'s case, "Follow App Rules" should (ideally) not be any different from "VPN DNS Only", since Nicotine+ should always use the VPN DNS anyway.

Are you able to connect to the IP address of the server (208.76.170.59:2242)?

**Comment by slook** [comment]
@bresso07 please [update to latest unstable master](https://nicotine-plus.org/doc/TESTING.html#windows) and then follow the [previously suggested steps for binding](https://github.com/nicotine-plus/nicotine-plus/issues/2285#issuecomment-1436041892) to see if that helps to resolve your issue or if something further is required?

**Comment by mathiascode** [comment]
There have been a bunch of changes to the networking code, and an option to set a specific network interface has been added on Windows. I'll assume the issue is fixed, but let me know if the latest unstable build still doesn't work properly.

**Comment by francisuk1989** [comment]
@mathiascode
