### ISSUE TITLE
Error launching

### ISSUE THREAD

**Issue by perfect7gentleman** [nicotine-plus/nicotine-plus#2290]
Nicotine+ version:  3.2.7
Operating System/Distribution: Gentoo/GNU Linux

### Describe the bug
```
Nicotine+ Version: 3.2.7
GTK Version: 
Python Version: 3.11.1 (main, Dec  7 2022, 18:42:18) [GCC 12.2.1 20221203]

Type: <class 'TypeError'>
Value: constructor returned NULL
Traceback:   File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/application.py", line 109, in on_activate
    self.frame = NicotineFrame(self.instance, self.core, self.tray_icon, self.start_hidden, self.ci_mode)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/frame.py", line 242, in __init__
    self.log_view = TextView(self.log_view, auto_scroll=True, parse_urls=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/widgets/textview.py", line 77, in __init__
    self.pointer_cursor = Gdk.Cursor.new_from_name(textview.get_display(), "pointer")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
### Expected behavior
To run in GUI-mode

### Steps to reproduce the bug
No

### Additional context
```
/usr/lib/python3.11/site-packages/pynicotine/gtkgui/widgets/dialogs.py:229: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed self.dialog.present()
```

**Comment by mathiascode** [comment]
Something seems to be wrong with your cursor theme. What cursor theme are you using?

**Comment by perfect7gentleman** [comment]
It worked before. It works with git-version - Nicotine+ 3.3.0.dev4.

**Comment by mathiascode** [comment]
> It works with git-version - Nicotine+ 3.3.0.dev4.

I've applied a commit from master in the 3.2.x branch. Could you check if it fixes the issue in 3.2.8.dev1?
https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md

**Comment by mathiascode** [comment]
Any change?

**Comment by perfect7gentleman** [comment]
```


Nicotine+ Version: 3.2.8.dev1
GTK Version: 
Python Version: 3.11.1 (main, Dec  7 2022, 18:42:18) [GCC 12.2.1 20221203]

Type: <class 'TypeError'>
Value: constructor returned NULL
Traceback:   File "/home/MZ7WD240HAFV/Temporary/nicotine-plus/pynicotine/gtkgui/application.py", line 107, in on_activate
    from pynicotine.gtkgui.frame import NicotineFrame
  File "/home/MZ7WD240HAFV/Temporary/nicotine-plus/pynicotine/gtkgui/frame.py", line 36, in <module>
    from pynicotine.gtkgui.chatrooms import ChatRooms
  File "/home/MZ7WD240HAFV/Temporary/nicotine-plus/pynicotine/gtkgui/chatrooms.py", line 41, in <module>
    from pynicotine.gtkgui.popovers.roomwall import RoomWall
  File "/home/MZ7WD240HAFV/Temporary/nicotine-plus/pynicotine/gtkgui/popovers/roomwall.py", line 23, in <module>
    from pynicotine.gtkgui.widgets.textview import TextView
  File "/home/MZ7WD240HAFV/Temporary/nicotine-plus/pynicotine/gtkgui/widgets/textview.py", line 36, in <module>
    class TextView:
  File "/home/MZ7WD240HAFV/Temporary/nicotine-plus/pynicotine/gtkgui/widgets/textview.py", line 42, in TextView
    POINTER_CURSOR = Gdk.Cursor.new_from_name(Gdk.Display.get_default(), "pointer")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by slook** [comment]
> `GTK Version: `

Why has the empty GTK version not thrown an incompatible version or missing Gtk install error?

**Comment by perfect7gentleman** [comment]
I don't know.
```
3.3.0.dev4   •   Python 3.11.1   •   GTK 4.8.3
```
Works well.

**Comment by mathiascode** [comment]
> > `GTK Version: `
> 
> Why has the empty GTK version not thrown an incompatible version or missing Gtk install error?

`config.gtk_version` is set too late: https://github.com/nicotine-plus/nicotine-plus/blob/d5b6344a1f946e0d0c5d8276b8d65a630a5918b0/pynicotine/gtkgui/frame.py#L251

A textview is created a few lines above: https://github.com/nicotine-plus/nicotine-plus/blob/d5b6344a1f946e0d0c5d8276b8d65a630a5918b0/pynicotine/gtkgui/frame.py#L242

@perfect7gentleman Right, it's using GTK 4. If you start Nicotine+ 3.3.0.dev4 with GTK 3, does the error show up?

The command is:
`NICOTINE_GTK_VERSION=3 nicotine`

**Comment by perfect7gentleman** [comment]
```
Nicotine+ Version: 3.3.0.dev4
GTK Version: 3.24.35
Python Version: 3.11.1 (linux)

Type: <class 'TypeError'>
Value: constructor returned NULL
Traceback:   File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/application.py", line 869, in on_activate
    from pynicotine.gtkgui.mainwindow import MainWindow
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/mainwindow.py", line 35, in <module>
    from pynicotine.gtkgui.chatrooms import ChatRooms
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/chatrooms.py", line 42, in <module>
    from pynicotine.gtkgui.popovers.roomwall import RoomWall
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/popovers/roomwall.py", line 24, in <module>
    from pynicotine.gtkgui.widgets.textview import TextView
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/widgets/textview.py", line 35, in <module>
    class TextView:
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/widgets/textview.py", line 41, in TextView
    POINTER_CURSOR = Gdk.Cursor.new_from_name(Gdk.Display.get_default(), "pointer")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mathiascode** [comment]
It's something related to the cursor theme, but I'm not sure why the behavior is different in GTK 3 and GTK 4.

Some questions:
- What's the name of the cursor theme you're using on your system?
- When using Nicotine+ 3.3.0.dev4 with GTK 4, join a room, send a link as a chat message, and hover over the link. Does the cursor change to a pointer/hand cursor? Can you send a screenshot of the cursor?

**Comment by perfect7gentleman** [comment]
Yep, you are right. It's the cursot theme. I used custom theme, then I switched to built-in one, and voila!

**Comment by slook** [comment]
> I used custom theme

When you are designing your cursor theme, consider that it is recommended to include at least the standard cursor names as specified in the standard CSS specification, see link:
https://docs.gtk.org/gdk3/ctor.Cursor.new_from_name.html#description

**Comment by perfect7gentleman** [comment]
It was not my theme, I downloaded it from kde-look.org

**Comment by slook** [comment]
Such themes are often thrown together by amateurs and community contributors. In fairness, the cursor naming specification is not well documented, the design conventions are loose and not well defined, so it is very easy to break things in this way.

**Comment by mathiascode** [comment]
Handled in https://github.com/nicotine-plus/nicotine-plus/commit/107f7396e119fc151e5c3500ac18ac0d01b21a08, since there was someone else with a broken cursor theme.

**Comment by slook** [comment]
Similar error has shown up again in issue #2943
