### ISSUE TITLE
stuck on 'Unable to check for updates' after one offline startup

### ISSUE THREAD

**Issue by rpmindroid** [nicotine-plus/nicotine-plus#2295]
Hey. Just read that old, last message on [this thread](https://github.com/nicotine-plus/nicotine-plus/issues/2178) and the encouragement to report macOS issues, so there you go. :)

(Also, just to understand, is 3.2 still getting upgrades while 3.3 is also being developed?)

Ok, about the bug:

Nicotine+ version:  3.3.0.dev4
Operating System/Distribution: macOS 12.1

### Describe the bug
After launching Nicotine while offline once, later back-online start ups only yield the same error message pop-up.

### Expected behavior
The pop-up window would not appear on startup after going online, and Nicotine would start.

### Steps to reproduce the bug
- open Nicotine offline. The 'Unable to check for updates - Make sure you are connected to the internet.' pop-up appears.
- click 'Done'.
- connect to the internet
- start up Nicotine again
> the 'Unable' pop-up appears again, and nothing else. Clicking Done just closes the window, nothing else happens. Nicotine doesn't start.

<img width="1323" alt="Screenshot 2023-01-01 at 16 43 34" src="https://user-images.githubusercontent.com/93481982/210176692-fbef5406-d617-4aca-88bf-4f778e5ebebc.png">

Thx,
Paul

**Comment by slook** [comment]
That popup is generated by your OS.

There is nothing in the nicotine startup script that checks for updates, it must be something to do with your package manager.

Does this problem completely prevent you from starting Nicotine+ thereafter?

**Comment by rpmindroid** [comment]
Hey. Thanks for your explanations. :) Yes, as far as I know, I couldn't get Nicotine to start anymore afterwards. Now I reinstalled it and it's fine, but I have to give Apple a call tomorrow about something else so I'll ask about that too.

**Comment by rpmindroid** [comment]
(I guess I'll close that since it's not a Nicotine issue.)

**Comment by slook** [comment]
Agreed, although it would be useful to understand what OS configuration issue regarding System Update that leads up to this scenario, and if any workaround exists for the problem.

I have a feeling that this is one of those situations where the proprietary OS vendor is deliberately sand-bagging support for third-party unsigned apps.
