### ISSUE TITLE
Add sortable audio properties/quality column

### ISSUE THREAD

**Issue by mathiascode** [nicotine-plus/nicotine-plus#2296]
### Describe the solution you'd like
The bitrate column isn't very useful for lossless audio files, but it can be sorted to show higher quality files first.

SoulseekQt has an `Attributes` column that shows bit depth and sample rate for lossless files, and bitrate for lossy files. Unfortunately, the column isn't sortable.

I want the best of both worlds, where the bitrate is always used as the internal sort value, but the value shown in the GUI is similar to SoulseekQt. This allows us to keep displaying high quality files first.

### Additional context
![](https://user-images.githubusercontent.com/8754153/210179208-ba342a2a-4c96-44cf-ba4f-78dd9da53d26.png)
![](https://user-images.githubusercontent.com/8754153/210179209-cb553a8d-9bbf-4906-8cad-205baf5fce79.png)

**Comment by mathiascode** [comment]
The bitrate result filter requires some thought. It could probably be turned into a "quality" filter somehow, where you can enter bitrates, bit depths and sample rates.

**Comment by slook** [comment]
Sample Rate data is not displayed anywhere at the moment, for lossless files if it is listed could probably add it to the file properties dialog.

> a "quality" filter somehow, where you can enter bitrates, bit depths and sample rates.

Suppose having suffixes such as "k", "bits", "khz", etc, albeit the structure of syntax and documentation would be rather complex. 

Perhaps if the numbers are within certain ranges, then this could reliably infer the desired unit, such as <=32 would infer "bits", <~20000 would infer "bitrate" and >~20000 would infer sample rate is the intended unit.
