### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by asmitir** [nicotine-plus/nicotine-plus#2309]
Nicotine+ Version: 3.2.8
GTK Version: 3.24.36
Python Version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]

Type: <class 'FileNotFoundError'>
Value: [Errno 2] Arquivo ou diretório inexistente: b'/usr/lib/python3.10/site-packages/pynicotine/gtkgui/ui/popovers/roomlist.ui'
Traceback:   File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/application.py", line 109, in on_activate
    self.frame = NicotineFrame(self.instance, self.core, self.tray_icon, self.start_hidden, self.ci_mode)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/frame.py", line 277, in __init__
    self.chatrooms = ChatRooms(self, core)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/chatrooms.py", line 84, in __init__
    self.roomlist = RoomList(frame, core)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/popovers/roomlist.py", line 37, in __init__
    UserInterface.__init__(self, "ui/popovers/roomlist.ui")
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/widgets/ui.py", line 39, in __init__
    with open(encode_path(os.path.join(GTK_GUI_DIR, filename)), encoding="utf-8") as file_handle:

**Comment by slook** [comment]
Thank you for your bug report @asmitir 

What did you do to make the error happen? Does it happen every time?

**Comment by mathiascode** [comment]
Also, what operating system are you using, and how did you install Nicotine+?

**Comment by asmitir** [comment]
> Thank you for your bug report @asmitir
> 
> What did you do to make the error happen? Does it happen every time?

hello, it started after an abrubtly system shut down. many things started to not work properly and later i found out i was having problems with core dumps and stuff like that, so i tried to fix the issue. i reckon it was happening because my system couldnt alocate memory to python or something like so, maybe some nicotine dependency. im still with the issues in some applications that i could not fix, but i fixed it simply by re-installing nicotine+. idk how it worked but it did, i can now open and use it normally as i would before the issue.




> Also, what operating system are you using, and how did you install Nicotine+?

im using arch, installed it trough the aur

**Comment by mathiascode** [comment]
Seems like the abrupt shutdown resulted in some files going missing, and reinstalling Nicotine+ brought them back. I'm guessing you probably have other missing or corrupted files that are causing issues elsewhere on your system.

**Comment by slook** [comment]
Closing, since there is no evidence here that Nicotine+ caused the initial core dump, and the critical error message produced by the exception handler correctly caught the problem and crashed gracefully considering the circumstances.

@asmitir Please re-open this issue or create a new bug report if you encounter any further errors on your system (either OS core dumps or errors within Nicotine+) whilst Nicotine+ is running.

I hope you are able to recover your system and that any important data on your disk is okay.
