### ISSUE TITLE
I have gtk3 but I get "Cannot find GTK 3, please install it."

### ISSUE THREAD

**Issue by tari3x** [nicotine-plus/nicotine-plus#2310]
Nicotine+ version:  Nicotine+ 3.2.8

Operating System/Distribution:
NAME="openSUSE Leap"
VERSION="15.4"

### Describe the bug
```
$ rpm -qa | grep libgtk
libgtkmm-3_0-1-3.24.5-150400.1.10.x86_64
libgtk-2_0-0-2.24.33-150400.2.11.x86_64
libgtk-4-1-4.6.0-150400.3.3.1.x86_64
libgtk-3-0-3.24.34-150400.3.3.1.x86_64

$ ~/.local/bin/nicotine 
[2023-01-08 16:38:16] Cannot find GTK 3, please install it.
```

**Comment by mathiascode** [comment]
I believe you need this package on openSUSE: https://software.opensuse.org/package/typelib-1_0-Gtk-3_0

**Comment by tari3x** [comment]
Indeed! It started now, thanks a lot!

How could I have figured it out myself?

**Comment by mathiascode** [comment]
It would be nice if someone packaged Nicotine+ for openSUSE. Since every distro has slightly different dependencies, I think the best I can do is add openSUSE-specific commands for installing the dependencies to https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEPENDENCIES.md.

**Comment by tari3x** [comment]
There's already a packman package actually: http://packman.links2linux.com/package/nicotine-plus/1004616

I guess it's just missing a dependency?

**Comment by slook** [comment]
Please alert your distro's package maintainer to this issue.

**Comment by mathiascode** [comment]
> There's already a packman package actually: http://packman.links2linux.com/package/nicotine-plus/1004616
> 
> I guess it's just missing a dependency?

I can't test this package right now, but if it doesn't work, there seems to be a link to contact the Packman Team on that page. Perhaps you could try doing that.
