### ISSUE TITLE
Behaviour of tabs horizontal scroll

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2315]
Nicotine+ version:  3.2.8
Operating System/Distribution: -

I find confusing the behaviour of the horizontal scroll of tabs when a number of them exceed the visible window area, and the [<] [>] buttons are available.
Using those buttons, moves the current selected tab to the next ont one to the left or right contiguous one.
IMO, what i'd expect from those buttons is to scroll the tab headers, to show the availabe tabs that weren't previously visible, without changing the current active/selected one.
That is the standard behaviour of those type of buttons, for example, in a tabbed browser like firefox, or a spreadsheet like excel.

**Comment by slook** [comment]
> to scroll the tab headers, to show the availabe tabs that weren't previously visible

Changing from Bug to Enhancement, as this is not a feature included by default in the standard GtkNotebook widget.

**Comment by mathiascode** [comment]
I don't think we can change the behavior of the arrow buttons, but I've implemented https://github.com/nicotine-plus/nicotine-plus/issues/2079 to hopefully make it easier to find tabs.

**Comment by mathiascode** [comment]
Closing, as this isn't something that can be changed in the current GtkNotebook widget.
