### ISSUE TITLE
"Add to Buddy List" button in User Info should be greyed/disabled out if already on Buddy List

### ISSUE THREAD

**Issue by palmerito0** [nicotine-plus/nicotine-plus#2325]
### Describe the solution you'd like
Currently, the "Add to Buddy List" is clickable regardless of whether or not you have clicked on it. Would likely improve UX to indicate that the user is already on buddy list.

### Additional context
Want to get involved with the repo and thought like this was a good first small task to take on!

**Comment by mathiascode** [comment]
Hello! Thank you for the feature request.

This request has already been implemented in https://github.com/nicotine-plus/nicotine-plus/commit/5f6bb8116095aa29eae6b74864c47fc4478af40d.

I'm afraid there aren't many easy tasks left to work on. However, we've recently switched to GTK 4 and are currently refactoring things in the master branch. Any testing on the various available operating systems out there is greatly appreciated, especially in the long run.

- Development builds: https://nicotine-plus.org/doc/TESTING.html
- General information about the project: https://nicotine-plus.org/doc/DEVELOPING.html
- Planned changes for Nicotine+ 3.3.0: https://github.com/nicotine-plus/nicotine-plus/issues/2260

**Comment by palmerito0** [comment]
Ah, gotcha. Would still love to try and contribute, recently stumbled across Soulseek and have really enjoyed it so far :)

**Comment by mathiascode** [comment]
I think one area that could always be improved is the default Nicotine+ plugins. It would be nice to have more plugins shipped by default, if you have any ideas that could benefit a lot of users, or perhaps some new features or improvements for the existing ones.

https://github.com/nicotine-plus/nicotine-plus/tree/master/pynicotine/plugins
