### ISSUE TITLE
Messages are wonky 

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2329]
Nicotine+ version:  
3.2.8  •  GTK 3.24.36

Operating System/Distribution: 
Windows 11

### Describe the bug
Sometimes when a user sends a message it only shows up in the debug, ive been playing around and when i checked users ip, all the messages popped up.. 

### Expected behavior
PM shows up in the users chat tab

### Steps to reproduce the bug
it seems to be random .. i am not sure

### Additional context
Screenshots, logs, stacktraces or relevant information.
I do have screen shots if needed

**Comment by mathiascode** [comment]
That would be https://github.com/nicotine-plus/nicotine-plus/commit/aa7f4caa2de8979f61c4d6a0ac60cdc5fb3fa95f. I'll see if I can backport it to Nicotine+ 3.2.x.

**Comment by slook** [comment]
Backported to 3.2.9.dev1 in https://github.com/nicotine-plus/nicotine-plus/commit/697bb9dc5f946d26d12097ade573528472169d85

The Windows testing packages won't be available for a few days because GH Actions are broken at the moment.

**Comment by mathiascode** [comment]
@woollarding 3.2.9.dev1 should be available for testing now. Can you verify that the issue is fixed on your end?
https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md#windows

**Comment by woollarding** [comment]
Yep, out of town but should be able to check that tomorrow. Thanks

**Comment by woollarding** [comment]
so far i have not noticed the issue with the dev version i'm running, will
continue to monitor

**Comment by slook** [comment]
Thank you, please re-open if issue re-appears.

Good spot on this one btw :)
