### ISSUE TITLE
search bar doesn't work

### ISSUE THREAD

**Issue by bobombolo** [nicotine-plus/nicotine-plus#2335]
Nicotine+ version:  
Operating System/Distribution:
linux mint

### Describe the bug
the search bar doesn't activate. you can't type in it

### Expected behavior
being able to search

### Steps to reproduce the bug
just installed nicotine following the download instructions for debian

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
The search bar is disabled if not connected.
