### ISSUE TITLE
Unusual CPU usage

### ISSUE THREAD

**Issue by karolyi** [nicotine-plus/nicotine-plus#2361]
Nicotine+ version:  
Operating System/Distribution:
FreeBSD 13.1

### Describe the bug
Hey,
with using the latest master branch, nicotine started churning the CPU. I can't tell what exactly is doing it, but once nicotine loads, it starts constantly using about 25% CPU.

### Expected behavior
This didn't happen about 3-4 days ago.

### Steps to reproduce the bug
Just run a the process and look at its CPU usage.

### Additional context
Screenshots, logs, stacktraces or relevant information.
```
  PID   JID USERNAME    PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
32452  1078 karolyi      40    0   155M    81M select   7   0:07  24.60% python3: nicotine (python3.9){python3.9}
```

**Comment by slook** [comment]
Do you have a discrete GPU?

Does you os use X11 or Wayland?

**Comment by karolyi** [comment]
Thanks, it seems to have stabilized now.
