### ISSUE TITLE
Unable to share files on google drive after update to monterey

### ISSUE THREAD

**Issue by artrelated** [nicotine-plus/nicotine-plus#2362]
Nicotine+ version:  3.2.8
Operating System/Distribution:
Mac OS monterey

Monterey changed the location of the google drive and they way it is accessed on the OS.
I used to share my music folder which was inside the drive but now nicotine can no longer access the file. I have given nictoine full disk access but I get Errno 13 Permission denied: path to folder

Any Idea how to solve this?

**Comment by slook** [comment]
You may need to create a new `mount` point with the same read permissions as the user account running Nicotine+.

**Comment by artrelated** [comment]
This is what I was able to find: https://support.google.com/drive/answer/12178485?visit_id=638108597324964262-833022013&p=file_provider&rd=1#fileprovider&zippy=%2Cwhere-do-i-find-my-streaming-files-now%2Chow-does-this-functionality-differ-from-what-i-had-before
I'll try to create a mount point.

**Comment by slook** [comment]
A mount point might not be needed...

> - "For advanced use cases (e.g. Terminal), you can find your files under `~/Library/CloudStorage`. "
> 
> - "If you have configured applications to explicitly use file paths referencing Drive for desktop’s streaming drive, you will need to manually change these paths to continue accessing them as you did previously. "

**Comment by artrelated** [comment]
Setting the share folder as Users/[username]/Library/CloudStorage/Google Drive/ seems to work.
However there is an issue with downloads, which in my case are also inside the drive.
Nicotine fails to create a download folder (as I download a whole folder). Also it fails to rename incomplete files or move them from the incomplete folder. This results in downloads failing at 100% and the files remain in incomplete folder with incomplete name. I get the 'Download folder error' in Status.

**Comment by slook** [comment]
Good news that the Uploads are sorted.

What is your "Incomplete downloads" and "Finished downloads" folder locations in Preferences > Downloads?

**Comment by artrelated** [comment]
In which way do you mean that?
They are folders on the Google Drive, but I have to browse to select them. Due to the nature of the menu, I can't type in the folder path as with the shares.

**Comment by slook** [comment]
The real path is displayed in a tooltip, before you click to open the folder select dialog.

You may be able to browse the explicit path using the "Other locations" item in the dialog.

**Comment by artrelated** [comment]
The path is Users/[username]/Library/CloudStorage/GoogleDrive-[my email address]/[path to folder]

**Comment by slook** [comment]
Can you enable the "[Debug] Transfers" logging catagory (View > Log Pane > Right-click > Log Categories > [Debug] Transfers), and capture some log lines that show the exact error.

My guess is that it will be a filesystem permissions related issue. Obviously Nicotine+ needs direct write permissions to the folder.

**Comment by artrelated** [comment]
2023-02-01 17:19:25 Couldn't move '/Users/[username]/Library/CloudStorage/GoogleDrive-[my email address]/Shared drives/[username]/Music/incomplete/INCOMPLETEa03a2b23eb66f2747b2276e7ad1b295fCover.jpg' to '/Volumes/GoogleDrive/Shared drives/[username]/Music/2022/First Light/Cover.jpg': [Errno 13] Permission denied: b'/Volumes/GoogleDrive'

For some reason it still wants to move to /Volumes/GoogleDrive which is the old location of the drive

**Comment by slook** [comment]
Well, there you go. The fact that N+ can write the incomplete file into the G drive proves that it must be possible for this to work.

Try making a new Finished Downloads folder in the G drive, perhaps that will bump the change needed in the config.

**Comment by artrelated** [comment]
I tried making a new folder in Gdrive, but no change. Also tried setting the folder outside of the drive but it still tries to save at /Volumes/GoogleDrive and since it doesn't exist it fails.

**Comment by slook** [comment]
The already downloaded item has already decided its destination. Try it with a new download.

**Comment by artrelated** [comment]
yes, that was it. new downloads are working fine. thanks for your help!
