### ISSUE TITLE
Download I/O error: [Errno 36] File name too long

### ISSUE THREAD

**Issue by shdw** [nicotine-plus/nicotine-plus#2375]
Nicotine+ version:  3.2.6
Operating System/Distribution: Linux / Calculate Linux 23
FS: ext4 on LVM

### Describe the bug
Getting "Download I/O error: [Errno 36] File name too long: <filepath here>" for some failing downloads where the file name is too long for the filesystem being used (might be due to incomplete files named with prefixes before download completes).

### Expected behavior
handle the error gracefully which would allow the download to occur ; suggestions : an option in the settings to autorename / autotruncate the filename / offer a rename prompt or something similar

### Steps to reproduce the bug
Find & try to download this file : "25 the end of the beginning of contraction (involutional speed up _ preperation for the big runch).flac"

### Additional context
error entry from log :
2023-02-06 13:06:03 Download I/O error: [Errno 36] File name too long: b'/home/shdw/Downloads/nicotine-downloads/incomplete/INCOMPLETE1f136be8f41c4915b1b2d2086407124625 the end of the beginning of contraction (involutional speed up _ preperation for the big runch).flac'

**Comment by mathiascode** [comment]
@slook That's not the issue. 722e43d6511992f1a15b67efc7ed24bfdb51a26b needs to be backported to 3.2.x.

**Comment by mathiascode** [comment]
@shdw I've backported the fix to Nicotine+ 3.2.9.dev1. Could you test it and verify that it fixes your issue? https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md

**Comment by mathiascode** [comment]
I'll assume this is fixed.

**Comment by shdw** [comment]
> @shdw I've backported the fix to Nicotine+ 3.2.9.dev1. Could you test it and verify that it fixes your issue? https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md

Thanks for your patience, I confirm your fix works for me. Very appreciated!

Regards
