### ISSUE TITLE
[Linux][Flatpak]Nicotine+ Doesn't Switch To Dark Mode

### ISSUE THREAD

**Issue by WasteOfO2** [nicotine-plus/nicotine-plus#2379]
Nicotine+ version:  
Operating System/Distribution:
Arch Linux, Nicotine+ Flatpak version 3.2.8

WM: Hyprland (Might be useful)

### Describe the bug
I have set the User Inteferace --> Prefer Dark Mode to true, but it fails to actually load in the theme

I recently got rid of KDE, before which it respected the dark theme. Now that I have removed it, it no longer respects the option

I have tried `flatpak install Adwaita-dark` runtime but to no avail.

### Expected behavior
Nicotine sets itself to dark theme

### Steps to reproduce the bug
1. Have no prominent DEs installed (needs verification)
2. Set Nicotine to dark mode

### Additional context
Screenshots, logs, stacktraces or relevant information.

Pastebin to the terminal output of `flatpak run org.nicotine_plus.Nicotine` is [here](https://pastebin.pl/view/0ae990d4l)

Screenshot of the window is [here](https://files.catbox.moe/jjhr7l.png)

**Comment by mathiascode** [comment]
What's your system GTK theme? I suspect an empty GTK theme name is set in Nicotine+, which makes it fall back to the default light Adwaita theme.

Could you run Nicotine+ with `GTK_DEBUG=interactive flatpak run org.nicotine_plus.Nicotine`, and check which GTK theme is set in the inspector?

**Comment by WasteOfO2** [comment]
Hello! Thank you for ur response

Here is a [screenshot](https://files.catbox.moe/isv7f6.png) help you out

The dropdown for "GTK+ Theme" also shows the following options
1.  Adwaita
2.  Adwaita-dark
3.  Breeze
4.  HighContrast
5.  HighContrastInverse
6.  win32

It seems to not apply any of them by default

**Comment by mathiascode** [comment]
Does anything change if you set the system theme to Adwaita? It should be this command:
`gsettings set org.gnome.desktop.interface gtk-theme Adwaita`

**Comment by WasteOfO2** [comment]
I don't use gnome as previously stated in the issue. I use a WM

Alternatively, I could try to run N+ with environment variables in Flatseal

For now, I have applied the environment variable as `GTK_THEME=Adwaita`.

This did not fix the issue.

I just now tried setting the environment variable to `GTK_THEME=Adwaita-dark` and that DID fix the issue. Turns out only installing the runtime isn't the way to fix it :P

**Comment by mathiascode** [comment]
The GTK_THEME environment variable shouldn't be necessary if everything is working correctly.

I remember having this issue when testing the Flatpak in elementary OS a while back, but I don't quite remember how I fixed it. Might be worth using `lxappearance` or `nwg-look` as suggested here, and verify that the GTK theme, icon theme, cursor theme and other GTK settings are correct: https://wiki.hyprland.org/hyprland-wiki/pages/Getting-Started/Master-Tutorial/#themes

If that doesn't help, I don't think there's anything else we can do.

**Comment by WasteOfO2** [comment]
Right, I didn't know that u can install `lxappearance` and `nwg-look` to make things more comprehensive system-wide, thx.

Although I still found it weird that even after checking the "Prefer Dark Mode" option it didnt switch to it.

I think I can now close this issue, thank you so much for your insight and help!
