### ISSUE TITLE
Errors with downloading\complete\received folders

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2390]
Nicotine+ version:  3.2.8
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

Hello, I see errors when I try to download files.

![2023-02-14_22-58-40](https://user-images.githubusercontent.com/31162059/218790590-00b81799-5d1d-4445-895e-a64008a2eef2.png)

![2023-02-14_22-50-54](https://user-images.githubusercontent.com/31162059/218789891-d12e7079-2ce8-454e-9af9-3b147d776c7a.png)

![2023-02-14_03-47-44](https://user-images.githubusercontent.com/31162059/218789938-a59cb411-6d11-41b7-8017-d843adf7e51f.png)

Upd 1.: I changed all 3 folders (downloading\complete\received) to "C:\!" and also got an error (with Z:\ drive, but I don't have it right now):

![2023-02-14_23-07-45](https://user-images.githubusercontent.com/31162059/218793030-5a7a9ef7-641b-4be2-b877-b87e7a65f8ba.png)

![2023-02-14_23-09-21](https://user-images.githubusercontent.com/31162059/218793332-f1bc4937-1dd8-4372-b6b9-5876a1a44eba.png)

![2023-02-14_23-12-09](https://user-images.githubusercontent.com/31162059/218794010-7290269a-ba7a-4056-b099-67b08e99fc9e.png)

Please, fix this :)

Upd 2.: Change some drive letter to Z:\, after that changed all folders (downloading\complete\received) to "E:\Музыка_SOULSEEK\complete\", "E:\Музыка_SOULSEEK\downloading\", "E:\Музыка_SOULSEEK\received\". All works fine now. Very strange bug...

![2023-02-15_12-44-39](https://user-images.githubusercontent.com/31162059/218943070-63449f48-5f79-4e44-8c09-4d8499479ab2.png)

**Comment by slook** [comment]
There is more than one problem happening here with no clear course of action.

Are the 2 issues in your bug report related?

**Comment by SnIPeRSnIPeR** [comment]
> There is more than one problem happening here with no clear course of action.
> 
> Are the 2 issues in your bug report related?

Hmm I don't know...

A bug with a filename like this "05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌.flac" confirmed:

![2023-02-15_10-54-44](https://user-images.githubusercontent.com/31162059/218925241-4f815a59-1941-4065-a6c6-fa67b734490d.png)

**Comment by slook** [comment]
> I changed all 3 folders (downloading\complete\received) to "C:!"

"C:\!" is not a valid path. Really they all should be separate to avoid any risk of conflict.

**Comment by SnIPeRSnIPeR** [comment]
> > I changed all 3 folders (downloading\complete\received) to "C:!"
> 
> "`C:\!`" is not a valid path. Really they all should be separate to avoid any risk of conflict.

The main problem is that for some reason I could not change the location of the files after changing the drive letter.

**Comment by slook** [comment]
Files that were already downloading/downloaded before you change the setting will already have the destination decided, so the new setting will not have any effect on them.

It is necessary to restart the download again from scratch for saving into the new folder.

**Comment by SnIPeRSnIPeR** [comment]
> Files that were already downloading/downloaded before you change the setting will already have the destination decided, so the new setting will not have any effect on them.
> 
> It is necessary to remove and then restart the download again from scratch for saving into the new folder.

I did everything exactly as you wrote, but it didn't help. Steps were helped: 1) changing the drive letter to the old one (Z:/) 2) then changing the location of the downloaded files. It helped in that order.

**Comment by slook** [comment]
Is the problem specific to the handling of root `\` drives?

**Comment by slook** [comment]
Closing, as the OP did workaround the issue by changing the settings to alternate folder locations, and there is not enough information to identify what the problem was.
