### ISSUE TITLE
Download errors with strange file names

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2392]
Nicotine+ version: 3.2.8
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

A person can't download a file from me with this name: "E:\Музыка\Flume\Mixtapes\2019 - Hi This Is Flume (Web)\05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌.flac". Status - Cancelled. Status - Cancelled. Again and again.

![2023-02-14_03-47-44](https://user-images.githubusercontent.com/31162059/218942446-70c20ac1-c104-434e-8e22-5e0c6c20f034.png)

P.S. A bug with a filename like this "05 - ╜Φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌.flac" confirmed by downloader:

![2023-02-15_10-54-44](https://user-images.githubusercontent.com/31162059/218942543-c38bb5d4-662e-46f5-922b-6661b37646ce.png)

Please, fix this bug :)

**Comment by mathiascode** [comment]
Could you ask what Soulseek client and OS they're using? I've tried to download files with that name from multiple users, and also tried sharing it with Nicotine+ on Linux and Windows, without issues so far.

**Comment by SnIPeRSnIPeR** [comment]
> Could you ask what Soulseek client (version) and OS they're using? I've tried to download files with that name from multiple users, and also tried sharing it with Nicotine+ on Linux and Windows, without issues so far.

I already asked, but this user didn't message me back yet...

**Comment by slook** [comment]
Closing. It's probably an issue with a older client on the peer's machine.

Keep us posted if you ever  find out more information about this.
