### ISSUE TITLE
Upnp Port does not close upon exit of nicotine+

### ISSUE THREAD

**Issue by Sakooooo** [nicotine-plus/nicotine-plus#2393]
Nicotine+ version:  
Operating System/Distribution:
Windows 10 21H2

### Describe the bug
When exiting Nicotine+ and then going into my router's upnp page it says that nicotine+ is still opening the port

### Expected behavior
Upnp should say the port is closed and should open again on next launch

### Steps to reproduce the bug
1. Open Nicotine+ with UPNP port forwarding
2. Open router UPNP homepage
3. Close Nicotine+
4. Port should say it is still open

### Small Workaround until it is fixed
1. Turn off Upnp
2. Turn it on again

# This also happens with the original SoulSeek Client

**Comment by mathiascode** [comment]
The port mapping expires after 24 hours, but I suppose we could also remove it when closing Nicotine+.

**Comment by Sakooooo** [comment]
I think it would just be better to just add it as an option in that case

**Comment by Sakooooo** [comment]
woohoo awesome :D thanks man
