### ISSUE TITLE
Scanner to skip files basing on metadata/tags

### ISSUE THREAD

**Issue by kryger** [nicotine-plus/nicotine-plus#2410]
### Describe the solution you'd like
Allow configuring a regex-based keyword (or list of keywords) that should make the resource scanner skip the file from being added to the shares. It should be a matter of checking the fields read by TinyTag and skipping the file if it matches the criteria.

### Additional context
Use case: bypass files with "bandcamp" in the comment field to exclude albums I bought on Bandcamp from sharing, but it could be potentially used for other purposes.

**Comment by slook** [comment]
Blocked because this would require the filters code to be moved from the search module into it's own class.
