### ISSUE TITLE
Nicotine+ opens VSCode instead of default file manager

### ISSUE THREAD

**Issue by ForeskinJim** [nicotine-plus/nicotine-plus#2411]
Nicotine+ version:  3.2.8/Flatpak
Operating System/Distribution: OpenSUSE Tumbleweed 

### Describe the bug
When you right click a file/folder in the downloads tab and click "Open in File Manager" the application opens VSCode instead of Dolphin/PCmanFM.

### Expected behavior
VSCode not opening as my file manager

### Steps to reproduce the bug
See above

### Additional context
VSCode is not set as my default for anything. I had found a similar bug on VSCode's github [https://github.com/Microsoft/vscode/issues/65885](url) and there it was said that it was an issue with WebKit and the issue should be passed on to you. Well, here I am. This is the only application I use that seems to have this behavior. I even installed chromium just to download something and see if it opened Dolphin when I clicked on "View in folder". It did.

**Comment by slook** [comment]
Unless you specify a custom file handler (in Preferences > URL Handlers > "File manager command"), by default the file is launched by Gtk using a URI with the handler `"file:///"`...

https://github.com/nicotine-plus/nicotine-plus/blob/2c20feeef140fd458fcfeb09e9e92d4c5227733f/pynicotine/utils.py#L360

https://github.com/nicotine-plus/nicotine-plus/blob/2c20feeef140fd458fcfeb09e9e92d4c5227733f/pynicotine/utils.py#L316

https://docs.gtk.org/gio/type_func.AppInfo.launch_default_for_uri.html
https://docs.gtk.org/gio/type_func.AppInfo.get_default_for_uri_scheme.html

As you can see Nicotine+ doesn't try to do anything non-standard here.

For some reason VSCode has decided to register itself as the default handler for that URI scheme, which seems to be incorrect as you have highlighted in https://github.com/Microsoft/vscode/issues/65885 and as such would be a problem with that software's shell integration features.

> This is the only application I use that seems to have this behavior

It should affect all applications using GTK in the same way that have an equivalent function, for example Opera browser - can you download Opera to test if its Open Download function has the same problem?

In Nicotine+ you can work around the issue by setting a custom handler in Preferences > URL Handlers > "File manager command".

**Comment by mathiascode** [comment]
> It should affect all applications using GTK in the same way that have an equivalent function, for example Opera browser - can you download Opera to test if its Open Download function has the same problem?

I'm not sure if Opera is a good application to test, since it's just another Chromium-based browser today.

Perhaps try Transmission. I haven't looked at their code, but it's probably the closes you'll get to Nicotine+.

**Comment by slook** [comment]
It doesn't look like this is a bug in Nicotine+.
