### ISSUE TITLE
Visit my own user profile

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2412]
Right now when I want to open my user profile, I search for myself on the chat. There should be a more straightforward way of doing this. I think a button next to the `Update Info` one in the `User Info` tab would be a good option.

There's probably another way I just haven't heard about. Is there documentation?

**Comment by slook** [comment]
> I think a button next to the Update Info one in the User Info tab would be a good option

Those widgets have been renamed to `Update Profile` and `User Profiles` in latest master.

What do you think would be a good label string for your proposed button?

**Comment by JediMaster25** [comment]
Maybe `See Profile` or just `Profile`.

**Comment by mathiascode** [comment]
I think we could replace the `Update Profile` button with one that takes you to your own profile. The profile page could then contain buttons to edit it:

![](https://user-images.githubusercontent.com/8754153/221008327-c5c76c34-0589-4fe4-8988-1b1f36a20feb.png)

When you've edited your profile, it could refresh automatically.
