### ISSUE TITLE
Request: Modes Tab Placement?

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#242]
Hello,

In Linux using the latest 1.4.3 master branch, I noticed I could move the Modes Tabs left or right, to change the placement, but when I restarted Nicotine, they went back to their original location.

I'd personally rather have the ```Search files```  on the left of Downloads, it makes more sense to me, to have Search before Downloads.

I'm assuming since I can arrange the tabs, they should stick, but they're not.

![Modes Tabs](https://user-images.githubusercontent.com/36190223/83811491-715fa980-a6a9-11ea-871a-056f5e2ce521.jpg)

**Comment by mathiascode** [comment]
Thanks for the report. This was working fine before, but must've broken recently.

**Comment by 0pLuS0** [comment]
THANKS it appears working now in the latest Master!
