### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ivovegter** [nicotine-plus/nicotine-plus#2439]
Nicotine+ crashes on startup with the following error:

```
Nicotine+ Version: 3.3.0.dev4
GTK Version: 4.10.0
Python Version: 3.10.9 (linux)

Type: <class 'TypeError'>
Value: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
Traceback:   File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/application.py", line 878, in on_activate
    self.window = MainWindow(self)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/mainwindow.py", line 288, in __init__
    set_global_style()
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/widgets/theme.py", line 291, in set_global_style
    set_global_css()
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/widgets/theme.py", line 274, in set_global_css
    global_css_provider.load_from_data(css)
```

**Comment by slook** [comment]
Has this started happening after a recent update, or is this your first time run on this system?

**Comment by ivovegter** [comment]
After a recent update. In particular, the update to 3.3.0.dev4.r8630. The previous version I had installed, ...r8613, worked fine.

**Comment by slook** [comment]
Gtk version 4 is now the default if it is available on the system.

It looks a workaround has already been added for this crash:

https://github.com/nicotine-plus/nicotine-plus/blob/da6a8e87996abe4941fe50aea2e0785dad13dfae/pynicotine/gtkgui/widgets/theme.py#L284-L286

Please update to the [latest master](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#gnulinux).

**Comment by ivovegter** [comment]
That fix works, thank you.

**Comment by slook** [comment]
You're welcome, thank you for your bug report... Please do post any further crashes or issues you may encounter in future.
