### ISSUE TITLE
Uploads erroneously getting listed as complete, actually "aborted" at 99%

### ISSUE THREAD

**Issue by exodustx0** [nicotine-plus/nicotine-plus#2447]
Nicotine+ version:  3.2.8/3.2.9
Operating System/Distribution: Windows 10 (22H2)

### Describe the bug

I'm getting reports from numerous people that their downloads from me get aborted at 99% completion, which I surely did not initiate myself. Worse, on my end, the uploads are listed as 100% complete. Since updating to 3.2.8 (_maybe_ 3.2.7 but I believe not) I _have_ been seeing strange activity in my uploads tab on about two-thirds of all my uploads, which I think could be related in some way; I don't know if it is, as I've never happened to see this behaviour and then gotten a message about the same upload, but I'll explain in the case that it's related.

For about two-thirds of the uploads that get queued, on my end I'll instantly see the first queued upload get set to 100%, yet it'll still take a while to move on (doing the actual upload, one would assume). Occasionally, these same uploads get set back to 0% and get requeued.

I will add that, though I've seen this behaviour as of updating to version 3.2.8, I've only been receiving messages for the failing uploads as of yesterday, a week after updating to version 3.2.9. On my end, nothing appears to have changed.

### Expected behavior

Uploads that are listed as 100% complete to be listed as 100% complete rather than 99% aborted on the downloader's end.

### Steps to reproduce the bug

Haven't the foggiest, sorry. Could try downloading from me but I'm not online 24/7, and it would only provide the downloader perspective.

### Additional context

N/A

**Comment by mathiascode** [comment]
I don't think there's been any substantial changes related to transfers or peer connections since 3.2.6 or 3.2.7.

Could you enable debug logging (Messages, Connections, Transfers), capture the behavior in the log, and send the log to my e-mail address (on my GitHub profile)? https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging

**Comment by exodustx0** [comment]
I've e-mailed you the requested log file. Let me know if I need to provide any further data.

**Comment by mathiascode** [comment]
I need to look closer at the logs when I'm back home, bit I did notice that some users send a file byte offset the same size as the file, which would result in the upload showing up as 100% complete on your end.

I believe this can happen when a client isn't able to move a download to the completed download folder. SoulseekQt only shows a generic "Aborted" error in this case, IIRC.

Another more uncommon reason could be that the file size changed after a SoulseekQt user queued a download. Have you made any changes to your shared files recently, e.g. modified metadata?

**Comment by exodustx0** [comment]
> As for the delay, it's up to the downloading user to close the file transfer connection, unless it times out after 60 seconds.
> 
> I believe this can happen when a client isn't able to move a download to the completed download folder. SoulseekQt only shows a generic "Aborted" error in this case, IIRC.

Does this suggest that this could be buggy behaviour on the downloader-side, then? 

> Another more uncommon reason could be that the file size changed after a SoulseekQt user queued a download. Have you made any changes to your shared files recently, e.g. modified metadata?

I did trim the padding in almost all my FLAC files 3 weeks ago (I'd estimate about half my library got its padding trimmed). I'm pretty sure this issue existed for me before then. Other than that, only a few cover arts (maybe 1-2% of my library) have been replaced, nothing more.

**Comment by mathiascode** [comment]
> Does this suggest that this could be buggy behaviour on the downloader-side, then?

In some cases, but I don't think the download folder is the main reason.

> I did trim the padding in almost all my FLAC files 3 weeks ago (I'd estimate about half my library got its padding trimmed). I'm pretty sure this issue existed for me before then. Other than that, only a few cover arts (maybe 1-2% of my library) have been replaced, nothing more.

Is it always the same uploads that have this issue on startup? Unfortunately, SoulseekQt clients ignore size updates for downloads, so whatever total size a download had when it was added to the download list is the one that will remain until the download is removed. Trimming files could explain why the progress is stuck on 99%, since the user is waiting for a part of the file that no longer exists.

**Comment by exodustx0** [comment]
> Is it always the same uploads that have this issue on startup?

There are definitely a few uploads that I recognise from a while back, but I don't know if all of them are the same; I feel like there's some newer ones, but I don't think I have a way of checking this.

> Trimming files could explain why the progress is stuck on 99%, since the user is waiting for a part of the file that no longer exists.

Right, that makes sense to me. I realise I'm being unhelpful with this, as I again can't check this I don't think, but I really thought that this weird behaviour started before I trimmed those files.

---

So I just checked some, and in browsing my own files (both through Nicotine+ and through SoulseekQt as another user) I have found at least one file that I know that was trimmed, which is listed on both with a file size higher than the actual file; I created the SoulseekQt user just now, tried downloading the file, got aborted at 23% while Nicotine+ says the upload (eventually) 100% finished. Took a while on both sides, but their statuses got set to that simultaneously.

**Comment by mathiascode** [comment]
> So I just checked some, and in browsing my own files (both through Nicotine+ and through SoulseekQt as another user) I have found at least one file that I know that was trimmed, which is listed on both with a file size higher than the actual file; I created the SoulseekQt user just now, tried downloading the file, got aborted at 23% while Nicotine+ says the upload (eventually) 100% finished. Took a while on both sides, but their statuses got set to that simultaneously.
> 
> I checked the file in the `downloading` directory, and it's identical to the actual file, so it did actually succeed, SoulseekQt just doesn't realise it.

Thanks for checking, that explains it.

A rescan should update the sizes. Is this not the case on your end?

**Comment by exodustx0** [comment]
Rescanning does not update the sizes on these files.

I've taken a look at `shares.py`. Based on what I could gather from it, Nicotine+ doesn't reread a file's stats if its containing directory's mtime hasn't changed. My script doesn't do anything with those.

I'm not sure whether this behaviour from Nicotine+ (assuming I got it right) is flawed or not. I certainly had never even considered doing work on the _directories_ of files that my scripts are made to modify. I can look into that so I can at least get a functioning rescan going, but that's a short-term solution.

**Comment by mathiascode** [comment]
You're right, the mtime doesn't update in this case. That's unfortunate, since Nicotine+ has been checking the folder mtimes for 20 years now...

I'll have to check how/if SoulseekQt takes care of the issue. Calling stat() for every file on each rescan is just too slow.

**Comment by exodustx0** [comment]
As an attempt at explaining why this hasn't been an issue in the past, I assume that most (if not all) metadata editing applications create temp files for writing the edited file contents to, then delete the old file and rename the temp file; the ones I use do at least. Nicotine+'s behaviour _depends_ on this being the case. My script just overwrites and truncates; I can only assume that this is a bad practice I didn't know about, but regardless, if my assumption is correct, it's enough of a niche case that it makes sense to me that it hasn't come up before.

I'm very curious to hear about how SoulseekQt handles this once you've checked it.

**Comment by mathiascode** [comment]
@exodustx0 Can you try this branch? https://github.com/mathiascode/nicotine-plus/tree/db-format-new

There is no way to avoid the issue when using folder modification times, so I've opted to use file modification times instead so we at least don't have to read the audio tags every time.

The branch also contains a new share database format that should be a little bit faster than before.

Let me know how the changes work and perform on your end.

**Comment by exodustx0** [comment]
I'll gladly try it out, but I lack any relevant experience with Python. Do you have instructions for how to build/run this?

For the record, since it's been 6 months, I can report that I'm still getting people who keep re-downloading my shares, even though I've _long_ since made sure to update directory mtimes. It's just very unfortunate that SoulseekQt doesn't handle filesize changes. None of the perhaps 40 users who keep re-downloading from me have reacted to my plea to remove and retry their download, to force SoulseekQt to get the correct filesize, so I've resorted to banning them to prevent significant wasteful bandwidth. I appreciate that this itself isn't on Nicotine+, but I'm not sure where else my lamentation would be better suited.

**Comment by mathiascode** [comment]
Sorry, forgot to post the link to the downloads: https://nightly.link/mathiascode/nicotine-plus/actions/runs/6280664636

**Comment by mathiascode** [comment]
> For the record, since it's been 6 months, I can report that I'm still getting people who keep re-downloading my shares, even though I've _long_ since made sure to update directory mtimes. It's just very unfortunate that SoulseekQt doesn't handle filesize changes. None of the perhaps 40 users who keep re-downloading from me have reacted to my plea to remove and retry their download, to force SoulseekQt to get the correct filesize, so I've had to resort to banning them to prevent significant wasteful bandwidth. I appreciate that this itself isn't on Nicotine+, but I'm not sure where else my lamentation would be better suited.

There are plans to add automatic rescanning when someone requests a file that exists in your share, but isn't found on disk anymore, but other than that I can't do much unless SoulseekQt makes changed (I've reported the issue to the SoulseekQt developer a while back, but it's unlikely that anything will happen).

**Comment by exodustx0** [comment]
> There are plans to add automatic rescanning when someone requests a file that exists in your share, but isn't found on disk anymore, but it doesn't help much in this case. I can't do much unless SoulseekQt makes changed (I've reported the issue to the SoulseekQt developer a while back, but it's unlikely that anything will happen).

I appreciate your effort! I don't hold out much hope, but who knows. The automated rescanning sounds like a great idea though.

I'll try to test the new build sometime in the coming days.

**Comment by mathiascode** [comment]
Check https://github.com/nicotine-plus/nicotine-plus/issues/1870 for up-to-date builds for testing.

**Comment by mathiascode** [comment]
If everything works well, this will likely be the final build before the branch is merged into master: https://nightly.link/mathiascode/nicotine-plus/actions/runs/6423191481

Note that this build will migrate the global "Limit buddy-only shares to trusted buddies" option that existed before. If you had enabled this option, buddy shares will be changed to trusted shares, but you can change them back afterwards.
