### ISSUE TITLE
Reduce number of function calls

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#245]
There are some excessive function calls here and there that should be looked into.

**Comment by kiplingw** [comment]
Thanks Mat. Could you be more specific?

**Comment by mathiascode** [comment]
Actually, this issue might not be as large as I originally thought. The only thing that looks suspicious to me is 20k calls in the ticker sorting code when joining a chat room, might have to look into if something abnormal is going on there later.

(Checked with cProfile: `python -m cProfile nicotine`)
