### ISSUE TITLE
Uploads Restart Indefinetly

### ISSUE THREAD

**Issue by Climbatiz** [nicotine-plus/nicotine-plus#2472]
Nicotine+ version:  3.2.9 + .3.2.7
Operating System/Distribution: Windows 10 Home

this appears to be happening only to me, it started about a week ago for no apparent reason, i hadn't changed versions or any system settings, i run 3.2.7 on another system and it's not happening there, i also tried deleting all the data from my Nicotine's folder in AppData and installing it again from scratch but still have bug happen

### Describe the bug
For some users who download from me, after completion, after awhile the download restarts from that user and hangs saying "Transferring" for about a minute or so while also saying it's 100% taking 0:00s, this is happening with so many users that it takes up alot upload slots

i haven't seen this happen for files other than music, not movie files

![Untitled](https://user-images.githubusercontent.com/39280509/229772709-0212cc14-62d4-4510-8630-ddf61b1938a8.png)

**Comment by mathiascode** [comment]
Have you made any changes to your files recently, e.g. metadata or trimming (see https://github.com/nicotine-plus/nicotine-plus/issues/2447)?

**Comment by Climbatiz** [comment]
you're right about that, that's what they all have in common, i recently updated the ID3/APEv2 tags on all those files

**Comment by mathiascode** [comment]
> edit, i renamed the virtual dirs for those files, i assume that's a temporary fix

File sizes not updating after rescanning in some cases might be fixable on our end, but SoulseekQt clients that queued downloads before the file size changed is not. It would require changes in SoulseekQt to stop ignoring updated file sizes sent when initiating a transfer.

**Comment by Climbatiz** [comment]
yeah, renaming the virtual dirs worked as a temporary fix incase it happens to somebody else, i guess i can rename it back once every1 who was downloading from me has finished their files

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/2447
