### ISSUE TITLE
weird behaviour - "corrupted directory" and closing unexpectedly

### ISSUE THREAD

**Issue by cyberhardt** [nicotine-plus/nicotine-plus#2477]
Nicotine+ version:  3.2.9
Operating System/Distribution: win10

### Describe the bug
It's actually more than one. Out of the blue, nicotine started reporting "Couldn't move X to X,  [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: b'\\\\?\\D:\\'"
for every download. at first, it would download "normally", the downloaded files had "INCOMPLETE" before their names but would play without issues. Now it doesn't even want to download, and, when I try to change the download folder, it closes unexpectedly. This has never happened to me before.

### Expected behavior
To download without issues

### Steps to reproduce the bug
Try to download something

### Additional context
The log was already posted up there. I thought that maybe it could be path too long but even when I put it on the root folder it won't stop giving me those errors. I'll try reinstalling nicotine and see what happens.

**Comment by cyberhardt** [comment]
ps: reinstalling didnt solve it

**Comment by slook** [comment]
Even across re-installing, if the downloads are already added, then the destination path won't change until the download item is removed (Clear), and then added again from scratch.

Regards to the original error, is there any system errors or warnings logged in the Windows Event Viewer?

**Comment by cyberhardt** [comment]
ps: uploads happen as intended 

no critical error dialog displayed - it just shuts down

errors in event viewer are unrelated - some 4 DNS ones and 1 ModernDeployment-DiagnosticsProvider

clearing the downloads and then downloading something else "works" - the errors are still displayed and the files are still "INCOMPLETE-filename".

hm...the error seems related to the change on the drive letter assigned to the drive where the songs are located - which is weird, because after the change I did set up my shares again, and even downloaded more stuff without issues. I'll try a full reinstall, this time erasing all traces of nicotine on my system.

**Comment by slook** [comment]
The relevant file is called `config` in the User \ Application Data hidden folder. It can be renamed or deleted to run Nicotine+ with a new configuration.

Alternatively, you may use the `--config` command line argument, for example `nicotine --config new`

**Comment by cyberhardt** [comment]
Deleting the config folder under appdata>roaming>nicotine>config solved the problem

**Comment by slook** [comment]
I'm glad the problem is sorted and you are back up and running.

If the problem recurs again, please save a copy of the corrupted config folder as it might be possible to debug the issue and prevent it from occurring again, or at least improve the handling of the error.

As you say, it is plausible that an active drive letter change might have led to some kind of error state.
