### ISSUE TITLE
Sorting by "length" does not work

### ISSUE THREAD

**Issue by thenormal** [nicotine-plus/nicotine-plus#2485]
Nicotine+ version:  3.2.9
Operating System/Distribution: Windows 10 19045.2846

### Describe the bug

When I search for a song by a given artist, I am provided with a list of matches in the Search tab. Trying to sort the song by Length does not work. The program does nothing, and the list of matches is not organized accordingly.

### Expected behavior

The program should sort by length, either by longer length or by shorter length

### Steps to reproduce the bug

Search for a song by a given artist. Try to sort by Length.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by redactedscribe** [comment]
I think what you may be experiencing is that you've got Nicotine+ set to use a grouping mode. I believe _Group by Folder_ is the default. Set it to _Ungrouped_ to be able to sort the results by time without any grouping in effect:

![Nicotine+_2023-04-25_18-11-29](https://user-images.githubusercontent.com/25013746/234322628-1b5f4166-056b-489e-88f7-4f3638485b8f.png)

**Comment by redactedscribe** [comment]
No problem. You can close the issue if there's nothing else.
