### ISSUE TITLE
Cannot find pygobject

### ISSUE THREAD

**Issue by sonofevil** [nicotine-plus/nicotine-plus#2486]
Nicotine+ version:  3.2.9-1

Operating System/Distribution: Arch

### Describe the bug
Nicotine+ fails to start with the following error:
`Cannot find pygobject >= 3.18.0, please install it.`
python-gobject 3.44.1-1 is installed. There is no "pygobject" package.

### Expected behavior
Nicotine+ starts normally

### Steps to reproduce the bug
Run `nicotine`

**Comment by mathiascode** [comment]
How did you install Nicotine+? Is both Nicotine+ (nicotine) and PyGObject (gi) present in /usr/lib/python3.10/site-packages/?

**Comment by sonofevil** [comment]
> How did you install Nicotine+? Is both Nicotine+ (nicotine) and PyGObject (gi) present in /usr/lib/python3.10/site-packages/?

`2023-04-28 19:00:53 [EndeavourOS] 
 ~ $ ls /usr/lib/python3.10/site-packages/ | grep PyGObject
PyGObject-3.44.1.egg-info
2023-04-28 19:01:07 [EndeavourOS] 
 ~ $ ls /usr/lib/python3.10/site-packages/ | grep nicotine
nicotine_plus-3.2.9.dist-info
pynicotine
`

**Comment by mathiascode** [comment]
Any difference if you run Nicotine+ from Git? https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md#git

What's the error message if you replace

https://github.com/nicotine-plus/nicotine-plus/blob/93b070cc269bb7add84760e7762ffe4081e1c76e/pynicotine/gtkgui/__init__.py#L44-L49

with

```
    import gi
    gi.check_version(pygobject_version)
```
?

**Comment by sonofevil** [comment]
Same error when I run from git. After changing the file:
```

 nicotine-plus $ ./nicotine
Traceback (most recent call last):
  File "/home/lutra/nicotine-plus/./nicotine", line 38, in <module>
    sys.exit(load_module())
  File "/home/lutra/nicotine-plus/./nicotine", line 34, in load_module
    return run()
  File "/home/lutra/nicotine-plus/pynicotine/__init__.py", line 194, in run
    exit_code = run_gui(core, trayicon, hidden, bindip, port, ci_mode, multi_instance)
  File "/home/lutra/nicotine-plus/pynicotine/gtkgui/__init__.py", line 106, in run_gui
    error = check_gui_dependencies()
  File "/home/lutra/nicotine-plus/pynicotine/gtkgui/__init__.py", line 45, in check_gui_dependencies
    import gi
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgirepository-1.0.so.1: undefined symbol: g_string_free_and_steal

```

**Comment by mathiascode** [comment]
Have you held back any package updates? It seems like the gobject-introspection package was upgraded, but the glib2 version on your system is too old. The latest version is 2.76.1. Could you upgrade/reinstall glib2 and see if it fixes the issue?

**Comment by sonofevil** [comment]
Yes, thank you, it works now. Sorry about my system packages being such a mess.
