### ISSUE TITLE
rejoin rooms in order

### ISSUE THREAD

**Issue by dchmelik** [nicotine-plus/nicotine-plus#2490]
### Describe the solution you'd like
Save order rooms are in and optionally (probably default) on restart rejoin in that order, not the order they were last joined.

### Additional context
I accidentally left some rooms, and joined new ones, and it'd be nice if they were joined in order instead of me parting all 40+ and having to be exact enough to join all in order (might take several/many tries).

**Comment by mathiascode** [comment]
Rooms are always auto-joined according to the previous tab order now. Let me know if this is what you wanted, or if something else should be done.
