### ISSUE TITLE
Examplar plugin broken

### ISSUE THREAD

**Issue by DeathWired** [nicotine-plus/nicotine-plus#2506]
Nicotine+ version:  3.2.9
Operating System/Distribution: Windows 11

### Describe the bug
When trying to use the port_checker plugin the command is not recognized

### Expected behavior
using the command ```/port [user]``` and see if they have their port open

### Steps to reproduce the bug
copy port_checker from pynicotine to the nicotine plugins folder (on my computer AppData\Roaming\nicotine\plugins\) enable the plugin and do /port

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/37221707/a9baa073-5020-489f-a5c0-706b36b70e55)
![image](https://github.com/nicotine-plus/nicotine-plus/assets/37221707/64f8bbdb-2233-490a-9b26-63eab613a64b)

**Comment by slook** [comment]
The port_checker plugin in the master branch uses the new command system in 3.3.0+.

You can either:
- install the [latest unstable version of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) 3.3.0.dev5, or;
- use an [older version of the port_checker plugin from the 3.2.x branch](https://github.com/nicotine-plus/nicotine-plus/tree/3.2.x/pynicotine/plugins/examplars/port_checker).

**Comment by DeathWired** [comment]
Sorry for my misunderstanding, the solution worked. Thank you!

**Comment by slook** [comment]
You're welcome!

If you decided to install latest master 3.3.0.dev5 then please note there are currently improvements to the plugin system that may bring in breaking changes until everything is ratified, such as when PR https://github.com/nicotine-plus/nicotine-plus/pull/2504 is merged you will need to again update the plugin.
