### ISSUE TITLE
Turn off display of automatic chat messages

### ISSUE THREAD

**Issue by DarkVoyage** [nicotine-plus/nicotine-plus#2510]
While you keep chat with user open you will end up seeing something like this after some hours-days. I've imitated this by just connecting-disconnecting. Anyway it makes chat unreadable filling with useless technical info. Good that these messages are not logged to file. I want to turnoff display of these and similar messages completely.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/95372fd4-efc6-42f3-b7c7-51dbf16d16a5)

**Comment by slook** [comment]
The other problem was that "---reconnected---" was misleadingly printed even if the user was offline.
