### ISSUE TITLE
text in log aera in chat rooms lag to display from entry 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#253]
Sometime i type text in the entry-box chat rooms then enter, text does not appear fast in log window.
i hav the feeling it's when the log is full window from top to bottom looks like the log aera does not refresh ? im logged into nicotine and private room only but it does not happen in private chat where i usually hav less than 10lines.
is that possible ? or  misinterpreting something 

the two rooms (nicotine and my private room) are also logged at least 10000 lines maybe it causes lag to display new text ? 

do not hesitate to delete this issue if you consider i am wrong 

thank you ! 

sorry for my english im doing my best but i really know it is not correct .

**Comment by zniavre** [comment]
[simplescreenrecorder-2020-06-07_15.58.33.zip](https://github.com/Nicotine-Plus/nicotine-plus/files/4742192/simplescreenrecorder-2020-06-07_15.58.33.zip)
that not easy to catch without seeing my keyboard but after last word "arf" i need to use arrow up ans down to make text in log .

**Comment by mathiascode** [comment]
I can reproduce in chat rooms, no issues in private chat.

**Comment by mathiascode** [comment]
As far as I can tell, your own messages appear after the server has received and processed them, so it may take a short while.

**Comment by zniavre** [comment]
was not sure in private cause i never fill the entire log window
it happens randomly ( in screencast you can see my first test displayed normaly ( first arf) and second try was buggy
hope im not only one who got this ...  :o( 

thank you :o)

**Comment by mathiascode** [comment]
Can you check if this branch solves the issue?
`git clone -b logread https://github.com/mathiascode/nicotine-plus`

**Comment by mathiascode** [comment]
Alright, should be fixed now. Try cloning the branch above again.

**Comment by zniavre** [comment]
at this point it looks fixed ...    :1st_place_medal:
