### ISSUE TITLE
Some Personal Feature Suggestions

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [nicotine-plus/nicotine-plus#2530]
### Describe the solution you'd like
1. Warning pop-up when closing the app while someone's downloading from your library, or there's unfinished downloads;
2. Show a message when someone starts downloading from you (it's really a proud thing!)
3. Select the far right corner to close / minimise (currently the × button is slightly off)

### Additional context
Semi-bug / GUI engine related issue: font weights are not handled properly. Nicotine+ stable version seems to straight out not support font weight. For example, San Francisco font family look all the same no matter what weight you pick.

On Nicotine+ 3.3.0.dev5, somehow the system tray icon won't show.

**Comment by slook** [comment]
1. Already suggested https://github.com/nicotine-plus/nicotine-plus/issues/885
2. For every file, or only for peers who have never been seen before?
3. Theme dependent, try a different GTK theme or workaround with View -> Use Header Bar > Off

What is your OS?
What GTK version displayed in Help -> about Nicotine+?

**Comment by DarkVoyage** [comment]
> Show a message when someone starts downloading from you (it's really a proud thing!)

Is it not enough that you see whole upload list? There's a notification in status bar, when someone browses you. Especially it looks cool, when you start downloading form someone and he checks your list. Maybe they check, do you deserve downloading?

It won't be entertaining for too long...

**Comment by mathiascode** [comment]
> 2. Show a message when someone starts downloading from you (it's really a proud thing!)

Enable the "Uploads" log category (right-click the log view pane -> Categories -> Uploads).

> Semi-bug / GUI engine related issue: font weights are not handled properly. Nicotine+ stable version seems to straight out not support font weight. For example, San Francisco font family look all the same no matter what weight you pick.

If you're talking about the global font, this should be fixed in Nicotine+ 3.3.0.dev5.

> On Nicotine+ 3.3.0.dev5, somehow the system tray icon won't show.

It needs to be reimplemented, see https://github.com/nicotine-plus/nicotine-plus/issues/2260.

**Comment by mathiascode** [comment]
Closing, since everything asked here either exists or is tracked elsewhere.
