### ISSUE TITLE
Removing previously searched terms from the Search box

### ISSUE THREAD

**Issue by thenormal** [nicotine-plus/nicotine-plus#2535]
### Describe the solution you'd like
A feature that I would like to see is the possibility to remove previously searched terms from the list which appears when clicking on the down arrow next to the search box.

### Additional context
Let's say there are 20 items on that list, and I feel like I want to eliminate the first three because those where just a once-in-a-lifetime thing I was looking for. It would be nice to right click on each on those items and select something like "Eliminate from search list". This feature is especially useful when the search list is clogged with plenty of items, most of which the user will not search for again.

**Comment by mathiascode** [comment]
There's the option to remove the whole search history in Preferences -> Searches. I'm not sure how technically feasible it is to allow removing individual items, at least from within the search history dropdown.

**Comment by slook** [comment]
Closing, unfortunately Gtk doesn't provide a dropdown list widget that has delete buttons built in, and a custom widget such as in a web browser would be far too heavy to consider for such a limited use case.

If you absolutely need to remove a specific term from your history without clearing the entire history then you can manually edit the `history` setting in the `[searches]` category in your `config` file.
