### ISSUE TITLE
Room wall stuck after copy.

### ISSUE THREAD

**Issue by tomato-fred** [nicotine-plus/nicotine-plus#2539]
Nicotine+ version:  3.3.0.dev5
Operating System/Distribution:
linux

### Describe the bug
Room wall popup will only close with the ESC key after some text has been selected and copied.

### Expected behavior
Room wall popup to behave as normally.

### Steps to reproduce the bug
Open room wall, select and copy some text (via the context dialog), now the popup is stuck and will even transfer over other programs/workspaces.

**Comment by slook** [comment]
Cannot replicate. Please specify GTK version displayed in Help -> About Nicotine+

**Comment by tomato-fred** [comment]
GTK is 4.10.3

**Comment by mathiascode** [comment]
It's a known GTK 4 issue (https://gitlab.gnome.org/GNOME/gtk/-/issues/4529), but I forgot to add it to https://github.com/nicotine-plus/nicotine-plus/issues/2014.

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/2014
