### ISSUE TITLE
Add Password Protect option

### ISSUE THREAD

**Issue by toineenzo** [nicotine-plus/nicotine-plus#2548]
### Describe the solution you'd like
For me Nicotine+ is the best client to use for SLSK. I'm running it right now in a docker container on my NAS to always have it available. I also would like to connect to it from outside my network. I could secure it via Cloudflare, but it would be much easier if there was an option in the N+ settings to password protect the app/ui. I could use [slskd ](https://github.com/slskd/slskd) but it doesn't have an easy (settings) UI

### Additional context
n/a

**Comment by mathiascode** [comment]
I'm not sure this belongs in Nicotine+. Perhaps HTTP authentication support should be added to the Docker image instead?

**Comment by toineenzo** [comment]
@mathiascode Then I will close this issue in favor of #2312 and add a comment for the password protection feature
