### ISSUE TITLE
Wishlist results - sound alert and flashing icon when minimized

### ISSUE THREAD

**Issue by ghaarth** [nicotine-plus/nicotine-plus#2551]
**Wishlist results - sound alert and flashing icon when minimized to tray**

Nicotine+ does this when a user online alert is set up, so why not offer this for wishlist search results also? I missed a painful amount of rare matches due to the user going offline before I have a chance to act.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/issues/2221 should take care of this.

**Comment by slook** [comment]
No, afaik #2231 which closed #2221 only implemented popup bubbles, it did not implement taskbar urgency hints.

**Comment by mathiascode** [comment]
We don't seem to have explicit urgency hints for online alerts either, unless the notifications do this implicitly somehow?

**Comment by slook** [comment]
That's right, it does not. I think the OP meant alerts do appear for an online user who has sent a new message in chat.

It is not needed to call `show_urgency_hint` to notify about a buddy who comes online, because that event is not interesting enough to warrant it.

**Comment by ghaarth** [comment]
Sorry for the late response. 
What I meant is: With the "Notify" checkbox activated in the "Buddies" tab, Nicotine+ makes lots of noise and visual flashes to let me know that the selected user appeared online. When minimized to tray. 

Would be nice to have this for wishlist search results too. I pray to the Nicotine+ gods every day to see this happening. for years. 


> That's right, it does not. I think the OP meant alerts do appear for an online `highlight_user()` who has sent a new message in chat.
> 
> It is not needed to call `show_urgency_hint()` to notify about a buddy who comes online, because that event is not important.

**Comment by slook** [comment]
We could trigger `show_urgency_hint()` from `update_title()` for any notification that `is_important` or `high_priority`, see https://github.com/nicotine-plus/nicotine-plus/discussions/2145#discussioncomment-6336995
