### ISSUE TITLE
Different colors in highlighted tabs and status icons

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2554]
Nicotine+ version:  3.3.0.dev5  Python 3.10.6  GTK 3.24.33
Operating System/Distribution: ubuntu 22.04. [image](https://hub.docker.com/r/cproensa/nicotine-docker/tags)

This is a difference i notice in the nightly build against the latest stable release

This is as seen in 3.2.9
![nic1](https://github.com/nicotine-plus/nicotine-plus/assets/14123811/7ffa2a89-5603-4630-9abd-de7ba45c47f7)

This is on nightly, as yesterday's package:
![nic2](https://github.com/nicotine-plus/nicotine-plus/assets/14123811/ab79d1ca-8863-4771-a11b-4f7fe025b0db)

Notice two things:
- Tab highlited is different: full colored text (with red and blue, bold text), instead of the single blue dot
- Online status icon is black, but should be green. Other colors are also slightly different hues.

Maybe, the colored text is part of a future change? but for sure, black online icon is not an expected feature.

### Steps to reproduce the bug
I swith between my two docker images, which are only different in the .deb package release used to install nicotine.

**Comment by mathiascode** [comment]
Icons are colored according to the colors set in Preferences -> User Interface in 3.3.0. Your installation has colors from a very old version of Nicotine+, press the reset icon next to the text entries in preferences to reset the colors.

**Comment by cproensa** [comment]
> Your installation has colors from a very old version of Nicotine+, 

cant be that old, it's been ~6 months since i started with this profile.

> press the reset icon next to the text entries in preferences to reset the colors.

right, reset all and that fixed to correct defaults. Now the coulors are reasonable.

Seems like that redefinition of preferences resurfaced some odd config i had (which must have been the defaults at the time, because i dont remember changing any of those). May this also happen to others users when they upgrade to some future version?

anyway, solved. Thanks!

**Comment by slook** [comment]
> May this also happen to others users when they upgrade to some future version?

If you have encountered the bug on default settings, then it is likely.

We need to identify what series of events causes the migration problem, before 3.3.0 is released.

**Comment by mathiascode** [comment]
The default colors changed in Nicotine+ 3.0.0, so anyone who started on an older version than this will have the old colors (as shown in your second screenshot).

**Comment by cproensa** [comment]
Right. I had in my config: `useronline = BLACK`
I think probably i did change that at some point becasue i didn't like seeing green text in the chat for an online user.

So, if i understand correctly:
- In version 2.x, the coulored dots (status circle icons) are fixed?
- In version 3, those dots now follow the settings in `useronline`, `useraway`, `useroffline`

That explains why i was seeing black dots for online users.
In retrospect, i should have used the check to disable "colored usernames" instead.

Still i'm not sure that the colours in the dots should follow the settings for the text. They have a different scope, as this example: i'm ok with the standard semaphore icons, but prefer a diffrent text colour cheme for readability purpose.
Without a thorough analysis... i'd rather leave the old status colors only for text, and leave the icons as is, or separately configurable on their own.
It's the same with the tab highlight text + icon. I may prefer a flashy colored icon, but not applied to the text label (or the other way around)
...But i understand the aim of reducing the numbers of options. That UI config is already huge.

**Comment by slook** [comment]
> In version 3, those dots now follow the settings in `useronline`, `useraway`, `useroffline`

That is what happens now yes, that does seem desirable, except for the visual accessibility issue you have highlighted.

**Comment by cproensa** [comment]
Thank you all for your comments.
Closing this

**Comment by mathiascode** [comment]
Dynamic status icon colors were mainly added because GTK provided the functionality, and it seemed like a good idea to apply preferred colors everywhere in the UI, for easier customization according to personal needs (e.g. color blindness). Status icons and text share the same colors by default, but I would be interested to hear if more users have issues with this, or simply prefer separate colors.

For now, you can achieve the previous behavior as follows (or replace the icons entirely if you wish), both steps done in Preferences -> User Interface:
- Unset tab colors by leaving the text fields empty
- Download the example icon theme (https://github.com/nicotine-plus/nicotine-plus/tree/master/data/icons/themes/example) and enable it
