### ISSUE TITLE
Downloads appearing in the "received" folder

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2568]
Nicotine+ version:   3.3.0.dev5   •   Python 3.10.6   •   GTK 3.24.33
Operating System/Distribution: ubuntu 22.04

### Describe the bug
Sometimes i find a pattern where:
- Having some queued files as regular downloads
- Removing those downloads from my queue
- Those files later appear as downloads into the "received" folder

Seems like the activation of the queued items on the remote side, after deleting them on local side, triggers them as "uploads"

**Comment by mathiascode** [comment]
This is one of the downsides of the upload system, and there isn't much that can be done. I recommend restricting the `Preferences -> Downloads -> Allow users to send you any files` option as much as possible to prevent this from happening (we should probably change it from buddies to trusted buddies or disable it by default).

**Comment by slook** [comment]
"Trusted Buddies" would be a better default.

**Comment by cproensa** [comment]
> "Trusted Buddies" would be a better default.

+1

so.. it's in the protocol that is not possible to differentiate this situation, from a proper "upload" initiated by the remote user?

**Comment by slook** [comment]
That's right, I suspect the remote client decides to retry because it disregards the local "Cancelled" deny reason, or misinterprets this reason as a failure rather than a user Abort request.

**Comment by mathiascode** [comment]
> so.. it's in the protocol that is not possible to differentiate this situation, from a proper "upload" initiated by the remote user?

Yes. There are protocol messages to abort transfers from the uploader's end (when e.g. banning), but not in the other direction. When a user cancels their download, it stays enqueued on the uploader's end until they attempt to upload it. If their upload attempt is rejected, they mark the file as cancelled.

**Comment by mathiascode** [comment]
> "Trusted Buddies" would be a better default, because buddies are not trusted unless done so explicitly and thus, it would effectively be disabled yet still relatively easy to figure out how to make remoteuploads work.

I think disabling the checkbox by default, effectively making the feature opt-in (in case someone overlooks the option), and setting a sane "Trusted Buddies" default if it's enabled is the way to go. There aren't many times this feature will be used anyway.
