### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Adthrawn** [nicotine-plus/nicotine-plus#2569]
Nicotine+ version:  3.2.9
Operating System/Distribution: Ubuntu 18.04.6 LTS (Bionic Beaver)

I am getting the below exception, seems to be caused when trying to download a folder

```
UnicodeEncodeError: 'ascii' codec can't encode character '\xff' in position 18: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/application.py", line 95, in on_process_network_msgs
    self.core.process_network_msgs()
  File "/usr/lib/python3/dist-packages/pynicotine/pynicotine.py", line 444, in process_network_msgs
    self.events[msg.__class__](msg)
  File "/usr/lib/python3/dist-packages/pynicotine/pynicotine.py", line 636, in get_user_status
    self.transfers.get_user_status(msg)
  File "/usr/lib/python3/dist-packages/pynicotine/transfers.py", line 592, in get_user_status
    self.get_file(username, download.filename, path=download.path, transfer=download, ui_callback=False)
  File "/usr/lib/python3/dist-packages/pynicotine/transfers.py", line 1610, in get_file
    download_path = self.get_existing_download_path(user, filename, path, size)
  File "/usr/lib/python3/dist-packages/pynicotine/transfers.py", line 1853, in get_existing_download_path
    folder_path, basename = self.get_download_destination(user, virtual_path, target_path)
  File "/usr/lib/python3/dist-packages/pynicotine/transfers.py", line 1838, in get_download_destination
    max_bytes = self.get_basename_byte_limit(folder_path)
  File "/usr/lib/python3/dist-packages/pynicotine/transfers.py", line 1827, in get_basename_byte_limit
    max_bytes = os.statvfs(folder_path).f_namemax
UnicodeEncodeError: 'ascii' codec can't encode character '\xff' in position 18: ordinal not in range(128)
```

I'm not able to determine which file/folder is causing this issue as Nicotine is crashing as soon as I open the application, but I'm willing to pull any logs to try and get rid of this. Or at least if there is a way to get rid of these queued downloads 

![image](https://github.com/nicotine-plus/nicotine-plus/assets/13037489/6e9b6ef0-ee83-4f0f-8cd2-806d3de96a4f)

**Comment by slook** [comment]
> I'm willing to pull any logs to try and get rid of this

Please locate the `downloads.json` file from the hidden `.nicotine` user data directory, and email it to the email address on @mathiascode 's gh profile page with the title of this issue in the subject line (don't publicly post logs containing personal data on here).

> Or at least if there is a way to get rid of these queued downloads

Firstly, try [the latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) 3.3.0.dev5 to see if the bug is already fixed or not.

Renaming or moving the aforementioned file will cause your download queue to be forgotten and thus avoid the error. Please keep a copy of it for debugging purposes.

**Comment by Adthrawn** [comment]
> Please locate the `downloads.json` file from the hidden `.nicotine` user data directory, and email it to the email address on @mathiascode 's gh profile page with the title of this issue in the subject line (don't publicly post logs containing personal data on here).

Done

> Firstly, try [the latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) 3.3.0.dev5 to see if the bug is already fixed or not.

Tested this, still crashing on launch

> In that case, search for the relevant text in the `downloads.json` file and delete that line (but save a copy of the original for debugging purposes).

Sorry I mis-typed my message, I am **not** able to determine which file is causing the issue

**Comment by Adthrawn** [comment]
Just got the new package, seem to be working now. Thanks for the help
