### ISSUE TITLE
crash (maybe before network reconnect, not sure)

### ISSUE THREAD

**Issue by starenka** [nicotine-plus/nicotine-plus#2573]
### Additional context
```
starenka /opt/nicotine-plus master at 5922d97f5? % git log | head                                                    
commit 5922d97f595a3c5b7b8914887790c62e20b79c68
Author: Mat <mail@mathias.is>
Date:   Mon Jul 3 05:13:34 2023 +0300

    events.py: make scheduler additions/removals thread-safe
    
    Fixes #2566

commit 273137c10382f60fcc5cf19520e1c280979dea05
Author: Mat <mail@mathias.is>

Nicotine+ Version: 3.3.0.dev5
GTK Version: 3.24.37
Python Version: 3.11.4 (linux)

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'NAME'
Traceback:   File "/opt/nicotine-plus/pynicotine/gtkgui/application.py", line 622, in raise_exception
    raise exc_value
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/nicotine-plus/pynicotine/portmapper.py", line 555, in _add_port_mapping
    "protocol": self._active_implementation.NAME,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by slook** [comment]
Annoyingly that crash is within the error handler itself so the proper traceback isn't included in the Critical Error message. I don't see why `_active_implementation` gets reverted to `None`, and I cannot replicate the crash.

Please can you [enable the "Miscellaneous" logging category](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEVELOPING.md#debug-logging) and try to capture messages about PortMapper UPnP before the crash occurs. If you are starting `./nicotine` from the terminal then the debug log messages will be printed in the console.

**Comment by starenka** [comment]
ok, updated to latest master and capturing the logs... will get back as soon as it crashes. cheers

**Comment by mathiascode** [comment]
Doesn't seem to be fixed yet, I just encountered this while resuming from sleep. Not sure why it happens yet, but my guess is that the networking thread and main thread try to forward the port at the same time.
