### ISSUE TITLE
Windows 10 taskbar doesn't auto-unhide when Nicotine+ is maximized

### ISSUE THREAD

**Issue by nerdsalot** [nicotine-plus/nicotine-plus#2585]
Nicotine+ version:  3.2.9 portable
Operating System/Distribution: Windows 10 Home 22H2 19045.3208 - laptop monitor

### Describe the bug
My taskbar is set to auto-hide, so it auto-unhides when hovering the mouse over the bottom of the screen. Works with every other program maximized window but Nicotine's.

### Expected behavior
Show (unhide) the taskbar when hovering the mouse over the bottom of the screen.

### Steps to reproduce the bug
Set Windows 10 taskbar to auto-hide. Open Nicotine+, set its window to maximized. Hover mouse over bottom of screen.

**Comment by slook** [comment]
It is mentioned in #2014:

> - Window overlaps autohide task bar in Windows 11
> 
>     - Affected GTK versions: 3, 4 (CSD)
>     - Upstream bug report: https://gitlab.gnome.org/GNOME/gtk/-/issues/2785

A workaround is Menu -> View -> "Use Header Bar" -> Off

**Comment by nerdsalot** [comment]
Thanks for the workaround, it works! Much cooler with the header bar though.

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/2014
