### ISSUE TITLE
Its not possible to set download folders when they are already set to invalid drive

### ISSUE THREAD

**Issue by majkinetor** [nicotine-plus/nicotine-plus#2586]
Nicotine+ version:  3.2.9
Operating System/Distribution: Windows 11

### Describe the bug

The drive S on the picture doesn't exist any more:

![image](https://github.com/nicotine-plus/nicotine-plus/assets/85767/becd4864-bff3-4be8-80c6-92919aace516)

I can't set a new folder without app crashing. 
Also, app is frozen for a long time when I click on it the folder field. The standard Windows browser for folders appears, and after folder is selected the app crashes. 

There is no way currently to change those settings making the app unusable.

### Expected behavior

If drive is not found, either remove it, but certainly do not crash. 

### Steps to reproduce the bug

1. Map the external drive in Windows as drive letter (S in above case)
2. Use that drive to setup Nicotine++ download folder
3. Remove the drive
4. Start the Nicotine++ again and try to change the settings.

**Comment by slook** [comment]
>> I've not been able to reproduce this issue

> the downloads folders which is on its own external drive S

What kind of device is drive S? For example is it a USB caddy or a NAS box connected via Ethernet or other such?

**Comment by majkinetor** [comment]
Just external drive connected via USB. Both M and S are [this one](https://www.amazon.com/Seagate-Expansion-18TB-External-Drive/dp/B08XKL3GF9)

**Comment by mathiascode** [comment]
> Regarding download folders I was able to change them now and I get this popup

That popup comes from GTK's file chooser. Not sure why there's such a large delay. I'll have to look into it once I'm home.

**Comment by majkinetor** [comment]
Maybe its Windows specific - many tools get completelly blocked when network drive is not present, some more then others. Seems that Explorer handles it tho....

**Comment by actual-kwarter** [comment]
I had a similar issue: I had my downloads folder set to an external HDD (E:) and I later removed the drive. Even after changing the downloads folder, it's still trying to download to the old E: location.

**Comment by slook** [comment]
That is because previously added/in progress downloads still have the previous setting.

**Comment by slook** [comment]
>> Could you also try the development version and see if the issue exists there? https://nicotine-plus.org/doc/TESTING.html

> It seems to work with this version. On start I am given Shares not available 

Please reopen this issue if similar problems persist.
