### ISSUE TITLE
Nicotine+ Low FPS/Stuttering on Mac OS

### ISSUE THREAD

**Issue by WesCurry** [nicotine-plus/nicotine-plus#2589]
Nicotine+ version:  
Operating System/Distribution: 3.2.9 Mac OS X

### Describe the bug

Nicotine+ Lag On Mac Issue

Been dealing with this ever since I switched from SSQT on my Mac I've had the issue of graphical lag. Updating to 3.3.0 beta resolved the issue but now Dev5 doesn't work on mac, so had to downgrade. Has anyone got a fix for this issue? It's like I'm using N+ in 15fps

### Expected behavior

For N+ to run at or close to 60fps

### Steps to reproduce the bug
Dong need any?

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
There's no other solution than using the dev builds, which use GTK 4 instead of GTK 3. I'll look into why they stopped working.

**Comment by WesCurry** [comment]
> There's no other solution than using the dev builds, which use GTK 4 instead of GTK 3. I'll look into why they stopped working.

I’ve seen someone else comment about it, the issue is the Nicotine app opens and then shuts down straight away, like it pops up in my system tray and then closes instantly.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/1dba0a1710c4b2115e15c91cb5d97efc8b2e29da should fix the dev build issue.

Can you download the latest development build and see if it works?

**Comment by WesCurry** [comment]
> https://github.com/nicotine-plus/nicotine-plus/commit/1dba0a1710c4b2115e15c91cb5d97efc8b2e29da should fix the dev build issue.
> 
> 
> 
> Can you download the latest development build and see if it works?

Aye it’s working again, thanks man

**Comment by mathiascode** [comment]
> Hi Mate, now in the dev build my shares are not working, they are working when I downgrade to 3.2.9 however.

Are you referring to rescanning shares (Menu -> Rescan Shares)? Any error messages?

**Comment by WesCurry** [comment]
> > Hi Mate, now in the dev build my shares are not working, they are working when I downgrade to 3.2.9 however.
> 
> Are you referring to rescanning shares (Menu -> Rescan Shares)? Any error messages?

When I try browse my shares in 3.3.0 it says that I am not sharing any files or i am privately, this doesnt happen in 3.2.9

**Comment by mathiascode** [comment]
Can you try the latest dev build, rescan shares (Menu -> Rescan Shares), and see if the issue is fixed? There was a similar issue on Windows that's fixed at least.

**Comment by WesCurry** [comment]
> Can you try the latest dev build, rescan shares (Menu -> Rescan Shares), and see if the issue is fixed? There was a similar issue on Windows that's fixed at least.

Aye yeah it works now thanks again!
