### ISSUE TITLE
Download does not seem to work

### ISSUE THREAD

**Issue by deafwired** [nicotine-plus/nicotine-plus#2595]
Nicotine+ version:  3.3.0.dev5
Operating System/Distribution: Windows 11

### Describe the bug
When trying to download a file from someone, it loops between getting status and transferring

### Expected behavior
download the song from user

### Steps to reproduce the bug
search for song, right click to download

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/37221707/a8a06dfd-9f39-4bde-9a94-fd11116d7872)
no errors in the console

**Comment by slook** [comment]
I am also experiencing stuck on "Transferring" at 0% on dev5 (linux).
