### ISSUE TITLE
Make proper release

### ISSUE THREAD

**Issue by zx2c4** [Nicotine-Plus/nicotine-plus#26]
Hey -- glad to see this project is still alive.

Per this bug, https://bugs.gentoo.org/show_bug.cgi?id=593622 , do you think you could release a real version for downstreams?

Thanks,
Jason

**Comment by Geyup** [comment]
Did you look at the TODO list?

https://github.com/eLvErDe/nicotine-plus/blob/master/doc/TODO.md

There seems to be quite a bit for gfarmerfr to do before releasing a version.

And I'm just as anxious as anyone to see it happen, when it happens.

**Comment by gfarmerfr** [comment]
Hi everyone,

Sorry for the late response, I've been very busy lately with a new job.

As Geyup pointed out : there is still some blocking bugs needed to be solved and some very old dependencies needed to be refreshed to have nicotine+ in a state where I'm comfortable to do a proper release.
I'll do a release before the end of this year with whatever I managed to do until then.

**Comment by Geyup** [comment]
It's to bad you haven't been able to get some help.

Keep up the great work!

And don't worry when a release comes, let it happen when it happens, don't kill yourself! LOL

**Comment by Geyup** [comment]
@gfarmerfr Hello, how are you and Happy New Year!

I see you are still going at it, this is great!

So how is progress coming, any idea on a release date?

By the way I see you want to switch to Python 3, I hope you can just stick with Python 2 for now, I run Slackware and it doesn't come with 3, of course I can install it, but I'd rather not mess with it if I don't have to for something like this.

Hopefully Python2 can be made to do what you need... hmm

**Comment by gfarmerfr** [comment]
Happy new year to you @Geyup :)

@kiplingw and @Mutnick have been helping me :)

I was an vacation last week and I was able to almost cross one major stuff from the TODO list : getting rid of glade and switch to GtkBuilder. Maybe I'll be able to finish the port this weekend.
I think I was too optimistic on the short terms goals roadmap: my new job is very time consuming.

The only thing that i can't really postpone to futures releases is refreshing the windows installer. So if everything falls together I think I can release something around the end of January / beginning of February.

With @kiplingw help (which is taking care of our ppa) we've decided on a versioning scheme similar do what gnome does: odd number for unstable release (so we can bump version number and trigger a deb package build) and even for stable release. So our next release will be 1.4.0.

We still have long standing bugs (pre 1.2.16) not being solved:
- A too generic search will eat your CPU and freeze the UI: but at least now I know why and maybe can put together a plan :)
- Some download/upload are hanging and a n+ restart solve the problem: will look into that when I have some time.

Don't worry we still have a long road until we can switch to python3: it requires GTK3.
The roadmap of upgrades for the code is:
- python2 + PyGTK (GTK2) + glade: almost finish to get rid of glade
- python2 + PyGTK (GTK2) + GtkBuilder: almost ready
- python2 + PyGObject (GTK3) + GtkBuilder : to be done
- python3 + PyGObject (GTK3) + GtkBuilder : to be done

**Comment by Geyup** [comment]
Sounds great, keep up the great work, you know us kiddies just can't sit still! LOL... :)

THANKS!

**Comment by gfarmerfr** [comment]
Hi guys 1.4.0 is out :)

I'll build and attach the windows installer to the release page tomorrow night.
I'll also update the N+ wiki.

@kiplingw will trigger his ppa build soon for ubuntu.

For other distros we have to hope that downstream packagers notice it and maybe give them a head's up.

**Comment by Geyup** [comment]
Ahhh over six and a half years since Life!

AWESOME this is great gfarmerfr!

I'll compile it and let you know how it goes!

THANK YOU VERY MUCH! :)
