### ISSUE TITLE
Disconnected from server loop

### ISSUE THREAD

**Issue by ctp9** [nicotine-plus/nicotine-plus#2613]
Nicotine+ version: **3.2.9**
Operating System/Distribution: **Windows 11 Pro (Version 10.0.22621, Build 22621)**

### Describe the bug
Two weeks ago my client started disconnecting and failing to reconnect. Nothing out of the ordinary was changed in my OS or network configuration - this just started occurring on its own. Here is the log:

`2023-08-07 22:56:58 Connecting to server.slsknet.org:2242`
`2023-08-07 22:57:00 Cannot connect to server server.slsknet.org:2242: Timed out`
`2023-08-07 22:57:00 The server seems to be down or not responding, retrying in 240 seconds`
`2023-08-07 23:01:00 Connecting to server.slsknet.org:2242`
`2023-08-07 23:01:00 Connected to server server.slsknet.org:2242, logging in…`
`2023-08-07 23:01:00 1948 privileged users`
`2023-08-07 23:01:01 You have no privileges. Privileges are not required, but allow your downloads to be queued ahead of non-privileged users.`
`2023-08-07 23:03:12 Disconnected from server server.slsknet.org:2242`
`2023-08-07 23:03:12 The server seems to be down or not responding, retrying in 15 seconds`
`2023-08-07 23:03:27 Connecting to server.slsknet.org:2242`
`2023-08-07 23:03:29 Cannot connect to server server.slsknet.org:2242: Timed out`
`2023-08-07 23:03:29 The server seems to be down or not responding, retrying in 30 seconds`
`2023-08-07 23:03:59 Connecting to server.slsknet.org:2242`
`2023-08-07 23:04:01 Cannot connect to server server.slsknet.org:2242: Timed out`
`2023-08-07 23:04:01 The server seems to be down or not responding, retrying in 60 seconds`
`2023-08-07 23:05:01 Connecting to server.slsknet.org:2242`
`2023-08-07 23:05:03 Cannot connect to server server.slsknet.org:2242: Timed out`
`2023-08-07 23:05:03 The server seems to be down or not responding, retrying in 120 seconds`
`2023-08-07 23:07:03 Connecting to server.slsknet.org:2242`
`2023-08-07 23:07:06 Cannot connect to server server.slsknet.org:2242: Timed out`
`2023-08-07 23:07:06 The server seems to be down or not responding, retrying in 240 seconds`

### Steps to reproduce the bug
Simply open the app and it immediately fails to connect, with the exception of occasionally connecting and then shortly disconnecting again.

### Additional context
What could be going on? As I mentioned, nothing was changed in the OS or network by me... so perhaps a recent Windows Update and/or a router firmware upgrade botched something?

**Comment by mathiascode** [comment]
Anything in particular to note about your network setup? Are you using a VPN? Could you try SoulseekQt and see if it has similar issues?

**Comment by ctp9** [comment]
> Anything in particular to note about your network setup? Are you using a VPN? Could you try SoulseekQt and see if it has similar issues?

No VPN but DNS encryption w/ECS, yes (always had this).

SoulseekQt connects without any issues, whereas Nicotine became problematic since 2 weeks ago.

**Comment by DarkVoyage** [comment]
I use TOR for Soulseek server and it doesn't connect with many exit peers. Also it disconnects, if I use VPN from Japan or South Korea. I don't know which side doesn't like which, but peer connections are fine either way, but you need a stable connection to this server. No matter SoulseekQt or Nicotine, it is problem with that server.

**Comment by ctp9** [comment]
I found the problem:

Threat detection on my hardware firewall suddenly decided to blacklist the server. Whitelisted it - and the problem is solved.

**Comment by slook** [comment]
Thank you for keeping the issue updated with a conclusion, it's great to have found the solution to the problem.

If the application's handling of network traffic seems prone to triggering your firewall's threat detection repeatedly, please open an issue for it with details about your router/firewall hardware so that problem can be investigated if needed.
