### ISSUE TITLE
Nicotine+ App won't open

### ISSUE THREAD

**Issue by WesCurry** [nicotine-plus/nicotine-plus#2638]
Nicotine+ version:  3.3.0dev5
Operating System/Distribution:

### Describe the bug
macos says the application is damaged and to move it to the trash. it isnt working

### Expected behavior
for the app to open

### Steps to reproduce the bug
N/A

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/commit/05ca333584f503cb424e9175f97c48855b8b2065 should hopefully fix this. Can you try the latest build?

**Comment by WesCurry** [comment]
> [05ca333](https://github.com/nicotine-plus/nicotine-plus/commit/05ca333584f503cb424e9175f97c48855b8b2065) should hopefully fix this. Can you try the latest build?

Downloading latest from website seems to incurr the same issue :(

**Comment by mathiascode** [comment]
Any difference with this build? https://nightly.link/mathiascode/nicotine-plus/actions/runs/6139135455

**Comment by WesCurry** [comment]
> Any difference with this build? https://nightly.link/mathiascode/nicotine-plus/actions/runs/6139135455

<img width="953" alt="Screenshot 2023-09-12 at 10 29 01 am" src="https://github.com/nicotine-plus/nicotine-plus/assets/140483298/ae02a68c-180e-4973-ad0c-79e85eeb0a1b">


Nope same issue, here is a screenshot of what comes up.

**Comment by mathiascode** [comment]
Any change with these two builds?
https://nightly.link/mathiascode/nicotine-plus/actions/runs/6131639814
https://nightly.link/mathiascode/nicotine-plus/actions/runs/6154529638

**Comment by WesCurry** [comment]
> Any change with these two builds? https://nightly.link/mathiascode/nicotine-plus/actions/runs/6131639814 https://nightly.link/mathiascode/nicotine-plus/actions/runs/6154529638

The first one works but not the second one

**Comment by mathiascode** [comment]
Thanks for testing. Can you confirm the latest development build on the main website works (will be ready in about 5 minutes)?

**Comment by mathiascode** [comment]
Any update?

**Comment by WesCurry** [comment]
> Any update?

sorry for the delay, can confirm the testing build on website is working!

**Comment by mathiascode** [comment]
Thanks!

Are you on macOS Ventura 13.5 or 13.6? In that case, could you confirm if https://github.com/nicotine-plus/nicotine-plus/issues/2617 works or not?

**Comment by WesCurry** [comment]
> Thanks!
> 
> Are you on macOS Ventura 13.5 or 13.6? In that case, could you confirm if #2617 works or not?

ayo I'm on Sonoma/Sonoma PB
