### ISSUE TITLE
"Remote file error" when trying to download from users on Nicotine+

### ISSUE THREAD

**Issue by rikafuruda** [nicotine-plus/nicotine-plus#2644]
Nicotine+ version:  3.2.9 
Operating System/Distribution: Windows 10 IoT LTSC 2019

### Describe the bug
When using Nicotine+ a lot of the time I cannot download from anyone. Trying to download results in a short "Getting Status" before "Remote file error" is shown. This renders me unable to download from anyone on Soulseek.

### Expected behavior
Download should simply say "Transferring" and download like normal.

### Steps to reproduce the bug
I'm not sure, but It seems to happen some of the time while other times it works without issue.

### Additional context
Screenshots, logs, stacktraces or relevant information.
I use a VPN (AirVPN) in order to use Port forwarding since I have yet been able to get port forwarding to work without it.

**Comment by mathiascode** [comment]
Can you enable debug logging, leave it enabled for some time while the issue happens, and send the logs to my email (on my GitHub profile? https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging

**Comment by rikafuruda** [comment]
Sorry for the late reply; It solved itself a few hours after and then happened again for another few hours, I haven't gotten it since, I will send a debug log when I am able to reproduce it.

**Comment by rikafuruda** [comment]
Sorry for the late reply; It solved itself a few hours after and then happened again for another few hours, I haven't gotten it since, I will send a debug log when I am able to reproduce it.

**Comment by mathiascode** [comment]
Sounds like some kind of temporary connectivity issue anyway, where connections either don't go through, or are interrupted shortly after they are established.

**Comment by slook** [comment]
This error may also be encountered if the remote peer has moved or deleted a file from the filesystem without doing a rescan.

If the remote peer is a Nicotine+ user (idk about Qt as well?), they would not be alerted to such failures, so are therefore unlikely to take any remedial action...

_https://github.com/nicotine-plus/nicotine-plus/issues/2260#issuecomment-1712757101:_

> I just noticed someone downloading all the boring accompanying files of a dir, but not the rest of it, and then it struck me: I had just retagged/renamed the files in that folder but not yet rescanned the shares, but I didn't get an error message.
> 
> We should examine that.

Some kind of "Rescan Required" flag label/icon widget might be displayed near the Rescanning shares progress bar widget.

**Comment by mathiascode** [comment]
I don't think this has anything to do with files, although the error misleadingly says so. We use the "Local file error" status when we receive a UploadFailed message twice in a row. Soulseek NS can send this message when it's not able to read a file, but all other clients only send it when a connection was closed unexpectedly.

We should probably use a different status message, but I need to check what SoulseekQt does. I would guess it probably uses a vague "Aborted" status though, like it does in most cases.

**Comment by mathiascode** [comment]
https://github.com/nicotine-plus/nicotine-plus/pull/2658

**Comment by rikafuruda** [comment]
Hello, I'm getting the error again, I don't think its simply due to someone rearranging their files, it seems to happen with every single user I try to download from, not just one or two people. I will send the logs to your email, Mathias.

**Comment by mathiascode** [comment]
I'm now using AirVPN myself, and haven't noticed the issue yet.

Can you try the latest development version of Nicotine+? There have been various changes to transfers: https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by rikafuruda** [comment]
> I'm now using AirVPN myself, and haven't noticed the issue yet.
> 
> Can you try the latest development version of Nicotine+? There have been various changes to transfers: https://nicotine-plus.org/doc/TESTING.html#windows

I figured out what I believe was causing the remote file errors; I was using qbittorrent on the same port as Nicotine+ which caused it to be blocked.
I have qbittorrent on its own port now, Everything has been fine so far.
I really do appreciate the help though!
Thank you :)
