### ISSUE TITLE
Option to transfer SoulSeek QT data to Nicotine+

### ISSUE THREAD

**Issue by LukaTV939** [nicotine-plus/nicotine-plus#2650]
### Basically what the title says
I want to transfer downloads, chat history, search history, options, and other data that is stored in SoulSeek QT client

I heard that there are differences between qt and n+ from [this Reddit post](https://www.reddit.com/r/Soulseek/comments/nb1mmq/nicotine_question/) and that's about it. I don't really know if it's actually possible so that's why I'm making this request

**Comment by mathiascode** [comment]
Closing in favor of #1685

There's no easy way to import data from another Soulseek client currently.
