### ISSUE TITLE
Download folder for remote user keeps appearing

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2667]
Nicotine+ version:   3.3.0.dev5   •   Python 3.10.12   •   GTK 3.24.33
Operating System/Distribution:  Ubuntu 22.04.3 LTS

### Describe the bug
In the downloads directory, for the folders created for each user, ther is one that is regularly being created empty without any interaction from my side. This folder is empty.
This specific folder has the name of one user, and keeps appearing on a regular basis, once every other week.

I notice that when i queue some files, these user's folders are created as soon as the files are put in the download queue, even before any actual trasnfer happens. This may be happening also for a remote upload initiated by that user.
For this specific user, i have him blocked, ignored, non trusted, and my upload settings for "allow users to send you files" to "only trusted buddies".

A possible explaination is that this user is starting an upload, or restarting a stale download from me that he still has in his outgoing queue (but i doubt it, becasue its been happening for months already). I dont think its anything malicious, only some kind of glitch

### Expected behavior

The point is, i would expect that if i have this user totally blocked and there is no way i can accept remotely initiated transfers, these folders should not be created in the first place.

### Steps to reproduce the bug

I can't reproduce this locally. I tried with a different soulseek client to test different upload use cases, but being all clients within the same NAT home network, it's difficult to make then behave normally...

**Comment by cproensa** [comment]
if i understand correctly, that fix: https://github.com/nicotine-plus/nicotine-plus/commit/b44ca23e7c68eadb823ae20ee33ff514bc3250b9
would avoid creating any empty username folder before its actually needed?

I still wonder, in these examples:
- the remote user is banned
- user is not trusted and thus (according to config) not allowed to upload to me 
...that code path is even reached. Should it be checked earlier and stop the operation right away?

**Comment by mathiascode** [comment]
> if i understand correctly, that fix: [b44ca23](https://github.com/nicotine-plus/nicotine-plus/commit/b44ca23e7c68eadb823ae20ee33ff514bc3250b9) would avoid creating any empty username folder before its actually needed?

Yes.
 
> I still wonder, in these examples:
> 
> * the remote user is banned
> * user is not trusted and thus (according to config) not allowed to upload to me
> 
> ...that code path is even reached. Should it be checked earlier and stop the operation right away?

The folder was created here:
https://github.com/nicotine-plus/nicotine-plus/blob/3b251cd19c5f3d14432fb3542a812c1f897ccaf0/pynicotine/downloads.py#L348-L351

but we should probably check if the user is allowed to upload first.
