### ISSUE TITLE
Crashing when uploading folders to user

### ISSUE THREAD

**Issue by TheKfcBandit** [Nicotine-Plus/nicotine-plus#2690]
Nicotine+ version: 3.3.0.dev6
GTK Version: 4.12.3
Python Version: 3.11.6 (win32)

Operating System/Distribution Windows 11 22H2 (OS Build 22621.2428)

### Describe the bug
can't send folders containing files to another user

### Expected behavior
sends folder & contents to said user

### Steps to reproduce the bug
1. browse own shares
2. find something to upload
3. click "Upload Folder..." OR "Upload Folder & Subfolders..."
4. select a user to upload to
5. click "Upload"
6. cry

### Additional context
Screenshots, logs, stacktraces or relevant information.

```
Type: <class 'KeyError'>
Value: ''
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/dialogs.py", line 408, in _on_button_pressed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/userbrowse.py", line 852, in on_upload_folder_to_response
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/userbrowse.py", line 277, in upload_folder
```

**Comment by slook** [comment]
Cannot reproduce (on linux). Is there some other condition required to reproduce the circumstance that leads to the reported crash?

**Comment by mathiascode** [comment]
Looks like a blunder in https://github.com/nicotine-plus/nicotine-plus/commit/664914cd4c03910570b03f16d47f014bd707395a#diff-eead057c42104f1ff09cceb62e2d6934e0f40efa9913e1e6430aa368d5e80b86R270.

We're trying to get the shares of the user we want to upload to, instead of our own.

**Comment by slook** [comment]
Thanks for your bug report! Please update to latest and try to encourage more Windows users to test if you know any :)

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows
