### ISSUE TITLE
Remove "Send To Player" from main right-click menu

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2705]
### Describe the solution you'd like
This option can easily be placed elsewhere

### Additional context
This is not an often used function - I do not know many people ("Buddies" aside) who want to either send a file to someone or have them send a file to them - putting it as the 1st function is simply a bad idea and a waste of valuable space.

At the very least, implement an option where users can select what options they want where on the right-click menu.

IMHO, most users will either want to SEND A MESSAGE or BROWSE USER'S FILES as their primary function from right-clicking a User Name.

**Comment by DeathStalker77** [comment]
Ok, yes, there is no way I would have interpreted that to mean "open the file" - but again, just my opinion, but I don't think that would be the primary function someone would be looking for at the top of the list. :-)

**Comment by slook** [comment]
I use it all the time, at least for every download in fact.

**Comment by mathiascode** [comment]
> IMHO, most users will either want to SEND A MESSAGE or BROWSE USER'S FILES as their primary function from right-clicking a User Name.

How does a quick access `View User Profile` item next to the existing `Browse Folder` item sound, similar to search results? The idea is that you would read e.g. guidelines the user has put in their description, and use buttons such as `Send Message` on the profile page if further action is required.

**Comment by DeathStalker77** [comment]
I think that would certainly be worth a try - it sounds like a logical User Map.  I only recently started using the **View User Profile** (& Search) and noticed that all those options are also there.

One small issue though, I think that the description of what a User can/should put IN their profile should be a bit clearer.  Initially, to me, it looked like a place just to put an Avatar/Pic.

Personally, I don't use BROWSE FOLDER that much, because they way some people have their folders/files structured, just doing that would NOT get you all of the files you would want that might be associated with that folder - such as separate Art, multiple discs, etc, so I select to view the whole SHARES and then search for what I was looking for - that also o9ften results in finding MORE from that user than just what I had initially been searching for.

**Comment by mathiascode** [comment]
> Personally, I don't use BROWSE FOLDER that much, because they way some people have their folders/files structured, just doing that would NOT get you all of the files you would want that might be associated with that folder - such as separate Art, multiple discs, etc, so I select to view the whole SHARES and then search for what I was looking for - that also o9ften results in finding MORE from that user than just what I had initially been searching for.

`Browse Folder` is supposed to expand any parent folders, so you can see related folders such as art. Is that not the case? If there are folder structures out there that currently don't work well with this approach, we could probably make improvements, if you can provide a generic example.

**Comment by mathiascode** [comment]
Renamed `Send to Player` -> `Open File`. Feel free to continue responding even though the issue is closed.
