### ISSUE TITLE
Browsing Folders Only Provides "Upload Folder/s / File/s"

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2712]
Nicotine+ version:  3.3.0.dev6    Python 3.11.6   GTK 4.12.3  26-OCT Build
Operating System/Distribution:  Win10 x64 Ent 22H2  19045.3570  Feature Experience Pack 1000.19052.1000.0

### Describe the bug
As the title says.  In SEARCH the correct DOWNLOAD options are available, but not in BROWSE SHARES

### Expected behavior
The same (previously existing) right-click menu options - four (4) in total - are available

### Steps to reproduce the bug
Install version, Search, Browse folder or shares

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
If you are running PR https://github.com/nicotine-plus/nicotine-plus/pull/2709#discussion_r1372756242 branch, presumably this change was made to provide a method of queuing files from self for testing a scenario.

**Comment by DeathStalker77** [comment]
Ok, hard to tell (for me, being a non-coder) which build goes with which thread :-(  I'm noticing that the current 27-OCT build does not perform as well as the 26-OCT build, but it does have the rt-clk menu back.

**Comment by slook** [comment]
The branches have now been merged into master, so the latest build for testing is at the normal location, link:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows
