### ISSUE TITLE
nicotine crashing

### ISSUE THREAD

**Issue by TheKfcBandit** [nicotine-plus/nicotine-plus#2713]
Nicotine+ version: 3.3.0.dev6
GTK Version: 4.12.3
Python Version: 3.11.6 (win32)
Operating System/Distribution: Windows 11 Version 22h2 build 22621.2506

### Describe the bug
crashing randomly after some amount of time

### Expected behavior
works

### Steps to reproduce the bug
1. run the app
2. wait

### Additional context
```
Type: <class 'KeyError'>
Value: 'knowanF' <----- someone's username with an F on the end
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 702, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 287, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/core.py", line 363, in _thread_callback
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 521, in _check_indirect_connection_timeouts
```

**Comment by DeathStalker77** [comment]
Not experiencing that issue with the 26-OCT x64 build.

**Comment by DeathStalker77** [comment]
Nicotine+ Version: 3.3.0.dev6
GTK Version: 4.12.3
Python Version: 3.11.6 (win32)

Type: <class 'AttributeError'>
Value: 'str' object has no attribute 'status'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/downloads.py", line 204, in on_clear_finished_filtered
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/downloads.py", line 1125, in clear_downloads

This was with the 26-OCT build when I click the CLEAR FINISHED button for DOWNLOADS.  There was (at least) a single finished file that did not automatically clear.  I will be installing the current 27-OCT build.

**Comment by slook** [comment]
@DeathStalker77 crash report is not from the master branch, afaik you were testing [performance-improvements-downloads](https://github.com/mathiascode/nicotine-plus/tree/performance-improvements-downloads) in PR #2709 please post the trace in there.

**Comment by mathiascode** [comment]
> I will be installing the current 27-OCT build.

Please don't do that yet, unless you want to go back to Nicotine+ hanging.

**Comment by slook** [comment]
@DeathStalker77 the branches have now been merged into master, so the latest build for testing is at the normal location, link:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

**Comment by DeathStalker77** [comment]
> > I will be installing the current 27-OCT build.
> 
> Please don't do that yet, unless you want to go back to Nicotine+ hanging.

Yes, so I found :-D  Fortunately, the hanging was not quite as bad as it was previously, but I **definitely** look forward to this new build :-)  Cheers to the both of you for all this work! (and to all others who helped but aren't named).  Things are currently transferring with the 27-OCT build pretty well, so I don't want to interrupt them, but will do so when more users go offline, and update the status of things as soon as possible.
