### ISSUE TITLE
Right click with control click doesn't work on mac with trackpad

### ISSUE THREAD

**Issue by ewof** [nicotine-plus/nicotine-plus#2724]
Nicotine+ version: 3.2.9
Operating System/Distribution: macOS Sonoma 14.1

### Describe the bug
right clicking on mac with trackpad is done with control + click but it doesn't work in nicotine in the browser shares menu and i need to connect a mouse in order to right click

### Expected behavior
control + click right clicks

### Steps to reproduce the bug
use nicotine on a mac with a trackpad
open a users folders in browser shares tab
control click one of their folders

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Unfortunately the 3.2.x branch will not be getting any more bug fixes now. Development is happening in 3.3.x wherein the issue you reported may already be fixed. Please install Nicotine+ 3.3.0.dev6 to verify if the problem still exists or not, link:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos

**Comment by slook** [comment]
Please can you try some Keyboard Shortcuts (press F1 for a list) that involve the Control/Command key and verify that they work?

**Comment by ewof** [comment]
seams to be related to tabs, things like `cmd + h` for away and `shift + cmd + d/c` for disconnecting/connecting work but things like `cmd + a` or `cmd + f` in downloads tab don't

**Comment by mathiascode** [comment]
> I suspect that the cmd key modifier or mouse button keyval is being consumed by the Accelerator() class module.

The problem is that the treeview shortcuts are provided by GTK, which no longer translates ctrl -> cmd in GTK 4.

We need to add the shortcuts like this (should probably override them in the TreeView class): https://github.com/nicotine-plus/nicotine-plus/blob/45bae5fdff57d447e07fd67b9719848ad5012b0d/pynicotine/gtkgui/application.py#L255-L271

@ewof I'm not sure if GTK supports control click. Could you try e.g. Gaphor, and see if it has the same issue? https://gaphor.org/en/

Does macOS support pressing the trackpad with two fingers to show context menus?

**Comment by ewof** [comment]
> Does macOS support pressing the trackpad with two fingers to show context menus?

i don't think so, got the laptop like 2 weeks ago it's my first mac, i'm not able to use two fingers to show context menus

same issue on graphor yea, control click with trackpad doesn't work but right click with mouse works

**Comment by mathiascode** [comment]
> i don't think so, got the laptop like 2 weeks ago it's my first mac, i'm not able to use two fingers to show context menus

You can change this behavior in the macOS touchpad settings.

As for adding control click to Nicotine+, should be fairly straightforward with our own context menus.

**Comment by mathiascode** [comment]
In any case, not a blocker for Nicotine+ 3.3.0, since there's a workaround.

**Comment by slook** [comment]
This seems like it would be ideal to fix it upstream and add it to https://github.com/nicotine-plus/nicotine-plus/issues/2014.

**Comment by mathiascode** [comment]
Looks like GTK 3 supported this, but it was lost in GTK 4. I have a workaround ready for Nicotine+, but I'll report this issue upstream too.

**Comment by mathiascode** [comment]
Reported upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/6724
