### ISSUE TITLE
Add Indicator To Show When Messages Are Read

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2744]
### Describe the solution you'd like
Each PM should have an indicator showing when they were read, so that the sender knows they have been read and not just ignored.

**Comment by slook** [comment]
Sadly the protocol doesn't support message read receipts.

The best that could possibly be achieved is a plugin to somehow indicate this, but it would only work between certain Nicotine+ users who have such a plugin installed, so even that would still not achieve the objective of knowing if messages were ignored.
