### ISSUE TITLE
Allow Manual Refresh Of Shares Without Restarting Client

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2754]
### Describe the solution you'd like
As a user, I need to be able to refresh my SHARES after I have made any changes - without having to go through the trouble of restarting the client - so that my shares are always current (which also makes it more convenient and user-friendly for other users)

### Additional context
N/A

**Comment by mathiascode** [comment]
Menu -> Rescan Shares, or Ctrl+Shift+R.

**Comment by DeathStalker77** [comment]
AH!  Sorry, I was looking in the PREFERENCES for that :-)
