### ISSUE TITLE
Ability to set default Buddies tab list sort

### ISSUE THREAD

**Issue by metaisfacil** [nicotine-plus/nicotine-plus#2758]
### Describe the solution you'd like
Whenever I start Nicotine+, the sort on the list in the Buddies tab resets to User. I would either like the ability to set a default sort method for the Buddies tab list, or for it to sort by Online by default.

### Additional context
Running this actions build on Windows 10 x64:
https://github.com/nicotine-plus/nicotine-plus/actions/runs/6445347862

**Comment by slook** [comment]
@metaisfacil Your feature request has been added to the next release candidate. It would be very helpful if you could test the latest build and report back if everything is working as expected for you:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md
