### ISSUE TITLE
Radical departure from established UI confuses user

### ISSUE THREAD

**Issue by sysdbugfactory** [nicotine-plus/nicotine-plus#2759]
Nicotine+ version:  3.2.2 GTK 3.24.38
Operating System/Distribution: Debian 12.2 bookworm / KDE

### Describe the bug

Just launched nicotine after not using it for a while and the whole UI paradigm has radically departed from the usual interfaces.

### Expected behavior

I expect the UI of the software to match long established practices and fit coherentlw with the other UI

### Steps to reproduce the bug

install nicotine, launch nicotine. Be lost in a nightmarish UI.

**Comment by slook** [comment]
Please provide a screenshot of how it looks in your desktop environment.

**Comment by mathiascode** [comment]
If you're talking about the removal of the menu bar in 3.0.0, then you can bring it back by toggling Menu -> View -> Use Header Bar.

**Comment by slook** [comment]
Closing, it's too late to go back to the old way now, since most users like the new UI design.
