### ISSUE TITLE
window control button close to invisible

### ISSUE THREAD

**Issue by sysdbugfactory** [nicotine-plus/nicotine-plus#2760]
Nicotine+ version:  3.2.2
Operating System/Distribution: debian 12.2 / kde

### Describe the bug

buttons to control the window (minimize, maximize, close) are white on light grey background making them virtually invisible.
I literally spent 5 minutes searching for a way to maximize the window and had to resort to kde contexual menu from the application bar to do it.

### Expected behavior

have sufficient contrast so these buttons are visible. like the rest of the text in the app which is all written in shade of black of dark grey.

### Steps to reproduce the bug

launch nicotine. using breeze dark theme.

**Comment by slook** [comment]
Perhaps the experience of GTK is not so good on your Qt based desktop environment.

You can try setting `Menu > View > "Use Header Bar" > Off` to disable Client Side Decorations, maybe that will be better for you?

**Comment by mathiascode** [comment]
Theming is not our responsibility. If there's a problem with the Breeze GTK theme, please report it to the KDE developers.

**Comment by slook** [comment]
From memory I recall that there is a setting buried somewhere in the KDE control panels which tries to match the colours from the active Breeze theme onto it's GTK theme, but it doesn't work properly in all cases.
