### ISSUE TITLE
UI/UX improvement: move the buddies only option out of the edit subwindow to the share window

### ISSUE THREAD

**Issue by sysdbugfactory** [nicotine-plus/nicotine-plus#2763]
Nicotine+ version:  3.2.2
Operating System/Distribution: debian 12.2 / kde

### Describe the bug

The shares configuration window does not display which shares are buddies only, you have to go through each share one by one and go into the edit sub window to find out which shares are public or buddies only.
This is quite inconvenient to bury this information and setting behind several click when it could and should be exposed right away. 

### Expected behavior

adding a column besides the existing "virtual folder" and "folder" to both provide the relevant information right away and ability to set/unset it. A checkbox would be good enough, but an explicit public/buddies only would probably be better; a click on this would toggle the setting to the other state.

having a button to set everything to public or buddies only may be useful.

### Steps to reproduce the bug

Open the configure shares prefrences window.

**Comment by slook** [comment]
In [the latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md) 3.3.0.dev6 it is now changed to a dropdown list chooser to change the share group for each share.
