### ISSUE TITLE
UI/UX improvement: button to rescan shares from the configure shares windows

### ISSUE THREAD

**Issue by sysdbugfactory** [nicotine-plus/nicotine-plus#2764]
Nicotine+ version:  3.2.2
Operating System/Distribution:

### Describe the bug

One would expect the configure shares preferences window to be the place to find action about shares such as rescaning the shares. But the option to rescan shares is oddly absent from this obvious place one expect to find it.

One has to close the configure share window, reopen the menu, click rescan shares, then browse shares and then reopen the configure shares to be able to make further changes.

### Expected behavior

all option dealing with shares should be in the configure shares preferences. rescanning shares and browing shares are part of the process of configuring shares, having access to all in one place would streamline the process.

**Comment by mathiascode** [comment]
Rescanning is supposed to happen when you press OK after making changes to the shares, but judging by your other bug report, it doesn't seem to be working for you in 3.2.2. Please try 3.2.9 and let us know if it improves things.

**Comment by slook** [comment]
> when you press OK

Or "Apply", which keeps the Preferences dialog open.

**Comment by mathiascode** [comment]
Closing, as rescanning should be automatic when closing the preferences dialog.

**Comment by DrSakuu** [comment]
Closing the preferences dialog does not rescan shares in version 3.3.4. I would like a dedicated button for it to make sure it happens, or shares should be scanned for changes constantly in the background like in foobar2000.

**Comment by mathiascode** [comment]
> Closing the preferences dialog does not rescan shares in version 3.3.4. I would like a dedicated button for it to make sure it happens, or shares should be scanned for changes constantly in the background like in foobar2000.

Closing the preferences dialog only starts a rescan if shared folders have been added/removed/renamed in the list. If you just want to rescan without making changes, use Menu -> Rescan Shares.

Scheduled scans have been requested here: https://github.com/nicotine-plus/nicotine-plus/issues/2900
