### ISSUE TITLE
"Invisible Border" Around Program?

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2768]
Nicotine+ version:  
Win10 Ent
3.3.0.dev6 
Python 3.11.6  
GTK 4.12.3

### Describe the bug
I noticed that there seems to be an "invisible border" around the program (in Dark Mode), where you cannot access anything other than the program.

I cannot tell you exactly how far this "border" extends other than on a 34" Ultra wide, it is approx 1" around the visible border.  I am only using this in Dark Mode, so I cannot tell you if it is present in any other.

### Expected behavior
The visible edge of the program (in any mode/theme) should be the edge of the program.

### Steps to reproduce the bug
Just run it and try to click to another program running behind it.

### Additional context
N/A

**Comment by slook** [comment]
Can you illustrate the problem in a screenshot?

**Comment by DeathStalker77** [comment]
There is no way to capture it in a screenshot - you would have to run Windows with the app in Dark Mode and other applications running behind it - then try to click on one of them close to the edge of the N+ border and see if it switches to that program.

**Comment by mathiascode** [comment]
This is probably caused by the window shadow (known GTK bug on Windows). I could try making the shadow smaller to make it less obstructive.

**Comment by DeathStalker77** [comment]
Could you maybe try to make it more visible?  (FWIW, it's the first time I've heard of a "windows shadow").  Learning more about these issues will help me with my devs & discussions at work :-)  I have also not previously heard of GTK - or dealt with it on any of my projects.  Most of them have been Angular or full Java-based.  However, I am also getting more into low/no coding software as well.

**Comment by slook** [comment]
GTK has bindings and wrappers to work with the language of your choice see https://www.gtk.org/

**Comment by mathiascode** [comment]
> it's the first time I've heard of a "windows shadow"

The shadow around the window border/frame.

> I have also not previously heard of GTK - or dealt with it on any of my projects.

No surprise really, it's mainly used on Linux. The only somewhat popular programs using GTK on Windows are GIMP and Inkscape.

I made the shadow smaller, so it's less likely to obstruct background windows you're trying to click. Please try the latest development build once it's ready (in about 15 minutes), and let me know if it feels fine, or if I should tweak it further.

**Comment by DeathStalker77** [comment]
I'll install it in just a bit or in the morning :-)  Thanks!

**Comment by DeathStalker77** [comment]
@mathiascode - fwiw, it's better, about 1/2 of what it was, but still noticeable.  If you are able to make it semi-transparent, I think that would help the most.  I'm not sure I understand why there needs to be a "shadow" to begin with.

**Comment by mathiascode** [comment]
> If you are able to make it semi-transparent, I think that would help the most.

That needs to be fixed in GTK, but it won't happen anytime soon.

In the meantime, I made the shadow even smaller. Should take up about the same area as the resize cursor does.

> I'm not sure I understand why there needs to be a "shadow" to begin with.

That's how most operating systems style windows by default nowadays.

**Comment by DeathStalker77** [comment]
I'll let you know how it is on the next build - though I am more concerned about the freezing I noted on the other bug.
