### ISSUE TITLE
network connectivity lost until a server reconnect

### ISSUE THREAD

**Issue by stefantalpalaru** [nicotine-plus/nicotine-plus#2778]
Nicotine+ version:  Git HEAD
Operating System/Distribution: Linux

### Describe the bug

Both download and upload stop working, after a few minutes/hours. Restarting the software, or manually disconnecting and connecting again to the Soulseek server gets both working again.

The download status, in this non-working state, is "connection timeout".

### Additional context

Nothing in the debug logs.

**Comment by mathiascode** [comment]
Thanks for reporting. Just to confirm, this didn't happen in 3.2.9, right?

Could you verify that the listening port is still open when this starts happening (https://github.com/nicotine-plus/nicotine-plus/issues/2223)?

If that's the case, could you enable the "Messages" and "Connections" debug log categories, and send the logs to my email address on my GitHub profile once the issue has started happening. I'll take a closer look.

**Comment by stefantalpalaru** [comment]
> this didn't happen in 3.2.9, right?

No, I never noticed that.

> Could you verify that the listening port is still open when this starts happening (https://github.com/nicotine-plus/nicotine-plus/issues/2223)?

Good catch! The UPnP port redirection has disappeared. After manually disconnecting and reconnecting to the server, the port redirect appears again.

It has a lease time of 120, which is weird. I think it's the default value, when no lease time is specified, but this piece of code is explicitly using `PortMapper.LEASE_DURATION` which is 43200: https://github.com/nicotine-plus/nicotine-plus/blob/b821131b007f804d963e609d50a14efc54897510/pynicotine/portmapper.py#L577

After a cursory glance at the code, it also seems that port redirection is done only once, after server login. When I implemented this in some other software, I renewed it every hour - not only because of expiring lease times, but because most residential users get dynamic public IPs from their ISPs and the two are usually handled together.

> could you enable the "Messages" and "Connections" debug log categories

Sorry, I forgot that right click "log category" selection. This is why I was not seeing any debug messages.

Will do.

---

Unrelated, but maybe interesting: I see a file with the status "Finished" even though I have it configured to autoclear finished/filtered downloads.

**Comment by stefantalpalaru** [comment]
I now see that there's `PortMapper._start_timer()` that renews the port mapping every 4 hours. Not soon enough for my router that thinks the port redirection has a lease time of 120 seconds.

**Comment by stefantalpalaru** [comment]
The 120s lease time displayed by `upnpc -l` might be a red herring: https://github.com/miniupnp/miniupnp/issues/222

**Comment by stefantalpalaru** [comment]
I caught it in the act again, and it looks like a silent failure in `UPnP._request_port_mapping()`. It's probably a router issue, and checking if the port was redirected through UPnP is not reliable across manufacturers.

What we can do is lower the port mapping interval (`PortMapper.RENEWAL_INTERVAL`) from the current 4 hours to something like an hour, to limit the time we're offline.

**Comment by mathiascode** [comment]
> I caught it in the act again, and it looks like a silent failure in `UPnP._request_port_mapping()`. It's probably a router issue, and checking if the port was redirected through UPnP is not reliable across manufacturers.
> 
> 
> 
> What we can do is lower the port mapping interval (`PortMapper.RENEWAL_INTERVAL`) from the current 4 hours to something like an hour, to limit the time we're offline.

Lowering the interval is probably the best solution. The lease used to be 24 hours in Nicotine+ 3.2.9 instead of 12 hours, which might explain why the issue went unnoticed.

Regarding the "Finished" issue, I'll look into it at the beginning of next week.

**Comment by mathiascode** [comment]
The interval is now 2 hours. If you happen to run into this issue again, e.g. when connecting to the server, please enable "Miscellaneous" debug logging and check if there are any relevant logs.

I also fixed the issue where certain finished downloads were not cleared.
