### ISSUE TITLE
lower on an int?

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#278]
Whilst doing searches for example: `Oh Brother Where Art Thou``` I got a lot of errors like this one:

```
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/search.py", line 1154, in check_filter
    if filters[0] and not filters[0].search(row[12].lower()):
AttributeError: 'int' object has no attribute 'lower'
```

This is the code in question.

```python
        # "Included text"-filter, check full file path (located at index 11 in row)                                                                                           
        if filters[0] and not filters[0].search(row[12].lower()):                                                                                                             
            return False                                                                                                                                                      
```

And I think there are more of those lower() on integers.

**Comment by mathiascode** [comment]
Can you test this branch?

`git clone -b searchrow https://github.com/mathiascode/nicotine-plus`

**Comment by hboetes** [comment]
Does that include the fixes from your `simplelen` branch? :-)

**Comment by mathiascode** [comment]
Yup

**Comment by hboetes** [comment]
Yay! I can search again!

**Comment by mathiascode** [comment]
Nice! I suppose the "Row index 12" output in the terminal is now the file path, as it's supposed to be?

**Comment by hboetes** [comment]
I can't confirm nor deny that. But it works now. :-)

**Comment by mathiascode** [comment]
Can you clone a fresh copy of the master branch, just to ensure that no more issues exist there?

**Comment by hboetes** [comment]
I just did and both the search bug and the database bug are still gone.
awesome! :-)

**Comment by mathiascode** [comment]
Thanks! :)
