### ISSUE TITLE
Dark mode: different color for messages sent by me in private chats

### ISSUE THREAD

**Issue by karolyi** [nicotine-plus/nicotine-plus#2786]
### Describe the solution you'd like
Hey,

this is more like a usability issue, so not a bug, basically, a low-hanging-fruit to get done imo.

When in dark mode, the messages sent by me in private chats are shown with a dark-blue color. Not only is it very hard to read (dark blue on a dark background), but almost impossible when you use a color adjuster for the nighttime that removes/dims the blue component in everything. Depending on how much blue suppression you set the tool, reading dark blue might be outright impossible as it'll appear with the same color as the background.

I always have to select the text that inverts it (white on a lighter blue background) to make it readable at those times.

So my request would be to change the color to another (non-blue based) and less dark, at least in dark mode :)

An example: ![image](https://github.com/nicotine-plus/nicotine-plus/assets/987055/3b1d4b9c-abc3-4cde-a6bc-5e5b644b5515)

Appreciate your work.

**Comment by mathiascode** [comment]
The default colors were updated a while back. If you have a config file from a few years ago, you need to reset the colors in Preferences -> User Interface (the arrow icons next to the color codes).
