### ISSUE TITLE
Invasive permissions recently added to the flatpak build

### ISSUE THREAD

**Issue by nekolifestyle** [nicotine-plus/nicotine-plus#2794]
Nicotine+ version:  
Operating System/Distribution:
Linux

Home folder read/write access
Can read and write all data in your home folder

System folder media
Can read and write all data in the directory

System folder mnt
Can read and write all data in the directory

System folder run/media
Can read and write all data in the directory

User runtime subfolder gvfs
Can read and write all data in the directory

**Comment by nekolifestyle** [comment]
This goes against the flatpak container philosophy and should be considered an anti-feature

**Comment by mathiascode** [comment]
At some point in the future, I want to get rid of the permissions in favor of only using portals, but you can use Flatseal or similar to do this on your own system for now.

**Comment by mathiascode** [comment]
Closing due to comments above.
