### ISSUE TITLE
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

### ISSUE THREAD

**Issue by Zidenett** [nicotine-plus/nicotine-plus#2806]
![image](https://github.com/nicotine-plus/nicotine-plus/assets/132226452/f264eff4-2fc9-4f77-9609-01a3b745e673)

Trying to put an image cover to an mp3

idk why the indenting on the def part doesnt work...

`
def set_cover():
    # filepath
    # image.jpeg
    audio_path = filepath
    picture_path = 'image.jpeg'

    try:
        audio = MP3(audio_path, ID3=ID3)
        audio.add_tags()
    except error:
        pass

    audio.tags.add(APIC(mime='image/jpeg', type=3, desc=u'Cover', data=open(picture_path, 'rb').read()))

    audio.save()
`

**Comment by mathiascode** [comment]
I think you meant to open this issue at https://github.com/quodlibet/mutagen/issues?
