### ISSUE TITLE
Right clicking into the search bar or ctrl+v copy paste causes application to crash

### ISSUE THREAD

**Issue by tenzlugz** [nicotine-plus/nicotine-plus#2809]
Nicotine+ version:  
Operating System/Distribution:

As the title suggests, attempting to copy paste anything into the search bar causes an immediate crash, same with simply right clicking into the search bar.

Happens every time no matter what unless I wait some arbitrary amount of time or it just happens to randomly not do it.

Have uninstalled and reinstalled, nothing has solved this issue on my end, not sure what to make of it.

**Comment by mathiascode** [comment]
Which operating system and Nicotine+ version are you using?

**Comment by tenzlugz** [comment]
Windows 10 and latest 3.2.9

**Comment by mathiascode** [comment]
Can you verify that you don't have an old installation of Nicotine+ <=3.1.1 present on your system (Control Panel -> Programs -> Programs and Features. It would appear as a duplicate Nicotine+ entry)?

If not, can you try Nicotine+ 3.3.0rc2 and see if it still crashes? https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by tenzlugz** [comment]
It appears I did have 3.1.1 leftover files, which I just now uninstalled. Uninstalled and reinstalled 3.2.9 and the issue still persists. Will try 3.3.0rc2.

**Comment by DeathStalker77** [comment]
The prior 13-31 build would NOT paste from the clipboard, it seems to have "locked" only what was copied from N+!

Installing the new 01-03 Build.

--- DS

**Comment by mathiascode** [comment]
> The prior 13-31 build would NOT paste from the clipboard, it seems to have "locked" only what was copied from N+!
> 
> Installing the new 01-03 Build.
> 
> --- DS

https://github.com/nicotine-plus/nicotine-plus/issues/2815

**Comment by tenzlugz** [comment]
Update,  Nicotine+ 3.3.0rc2 functions well so far. Issue not here either.
