### ISSUE TITLE
Some event causes text copied to clipboard outside Nicotine+ to be ignored

### ISSUE THREAD

**Issue by metaisfacil** [nicotine-plus/nicotine-plus#2815]
Nicotine+ version: https://github.com/nicotine-plus/nicotine-plus/actions/runs/7174673532
Operating System/Distribution:
Windows 10

### Describe the bug
There is some circumstance that causes Nicotine+ to start ignoring external changes to the clipboard. In this state, text copied inside of Nicotine+ can still be pasted outside the application, but not the other way around.

### Expected behavior
Nicotine+'s clipboard functionality should mirror the clipboard functionality everywhere else on the system.

### Steps to reproduce the bug
I'm having trouble figuring that out. If I figure that out I'll post details here. I don't think it's a byproduct of long term usage, I've had it start happening a few minutes after launching.

### Additional context
![nicotine clipboard bug](https://github.com/nicotine-plus/nicotine-plus/assets/93785302/c44fa8ac-67e9-4422-be8b-b36a6efd7487)

**Comment by mathiascode** [comment]
I think this is the same issue as https://discourse.gnome.org/t/gtk4-win32-debug-clipboard-issue/17950, fixed in https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6560. We need to wait for a GTK 4.12.5 release.

**Comment by mathiascode** [comment]
Should be fixed in the latest build. https://nicotine-plus.org/doc/TESTING.html#windows

Let me know if you still run into this issue or other issues.
