### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [nicotine-plus/nicotine-plus#2817]
### Describe the solution you'd like
It would be nice if the app's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by mathiascode** [comment]
Thanks for opening an issue. There are many cases where I wouldn't use Microsoft's products, but currently I don't want to go through the effort of migrating all issues, discussions, CI runners, and updating outdated links. We use GitHub Actions extensively for testing and packaging on different OSes, and as long as the service is still provided for free, I don't have a compelling reason to  migrate.

The code is currently mirrored at https://code.launchpad.net/nicotine+, in case that's a concern.
