### ISSUE TITLE
Change search share behavior to classic Soulseek

### ISSUE THREAD

**Issue by DarkVoyage** [nicotine-plus/nicotine-plus#2819]
When you search share in classic Soulseek, you actually don't search anything in list but filter list to match only your string and so you see only matching branches. Search in Nicotine+ work similar to web search and go through results. This is not comfortable behavior, especially if you have a lot of matches and you need to skip every track that contains that string (artist or partial name, label, etc). Original client behavior was much better. Add additional field that works as dynamic filter.

**Comment by mathiascode** [comment]
The plan is to bring the search result filters to the Browse Shares tabs, replacing the current search text entry.

**Comment by mathiascode** [comment]
Advanced filters are not present yet, but irrelevant folders are now filtered from the tree view. Please try the latest release candidate and let me know how it works for you: https://nicotine-plus.org/doc/TESTING.html

**Comment by DarkVoyage** [comment]
It crashes right away.

![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/3526fd7d-4b8b-4b5a-a644-672a257a632f)

**Comment by mathiascode** [comment]
Should've been fixed in https://github.com/nicotine-plus/nicotine-plus/commit/79fe92da55da2eade864be422ef6581a06b2d762. Can you try the latest build again?

**Comment by DarkVoyage** [comment]
It works great now! But the need to completely rehash share is a pain...

**Comment by slook** [comment]
The share database format has changed, so unfortunately a full rescan is unavoidable when upgrading to this release.
