### ISSUE TITLE
Windows Installer Still Remains Running

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2821]
Nicotine+ version:  01-03 Build
Operating System/Distribution: Win10 Enterprise

### Describe the bug
**msiexec.exe** still remains running after the installation completes.

### Expected behavior
The exe should terminate upon completion of the installation.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
It is fairly typical to see that running process, it is used by various mechanisms including Windows Update etc.

Can you be certain that the running instance of msiexec belongs to the Nicotine+ installer?

**Comment by slook** [comment]
Closing, it's not a critical problem. We don't have enough information to investigate this issue.
