### ISSUE TITLE
Failure to launch GUI on Linux

### ISSUE THREAD

**Issue by gsandhucode** [nicotine-plus/nicotine-plus#2824]
Nicotine+ version:  3.3.0rc2
Operating System/Distribution: Arch Linux x86_64 

### Describe the bug
Error upon launching:
```
Nicotine+ Version: 3.2.9
GTK Version: 
Python Version: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]

Type: <class 'ModuleNotFoundError'>
Value: No module named 'pynicotine.gtkgui.frame'
Traceback:   File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/application.py", line 107, in on_activate
    def add_action(self, action):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Expected behavior
Launching as normal

### Steps to reproduce the bug
Execute through `/usr/bin/nicotine` or through desktop file.

### Additional context

```nicotine -n``` works as normal.
```nicotine --version``` and the version in the error message differ.
GTK version is 4.12.4 in console output
Tested on Wayland.

**Comment by mathiascode** [comment]
How did you install Nicotine+? It seems like there's a mix of files from 3.2.9 and 3.3.0rc2 (`pynicotine.gtkgui.frame` no longer exists in 3.3.0rc2).

**Comment by slook** [comment]
Two factors need to be understood here...
1. Which installation method did you use to install Nicotine+ 3.2.9?
2. Which installation method did you use to install Nicotine+ 3.3.0.rc2?

**Comment by gsandhucode** [comment]
I installed them both with pacman.

**Comment by mathiascode** [comment]
That error looks like https://github.com/nicotine-plus/nicotine-plus/issues/2290 (issue with the cursor theme).

What are the exact commands you used to install 3.2.9 and 3.3.0rc2?

The only thing I can suggest right now is to completely uninstall Nicotine+, ensure no files remain in `/usr/lib/python3.11/site-packages/pynicotine`, and try 3.3.0rc2 again.

**Comment by slook** [comment]
> completely uninstall Nicotine+, ensure no files remain in /usr/lib/python3.11/site-packages/pynicotine

Is that something the setup script can be made to do automatically?

**Comment by mathiascode** [comment]
Actually, looking at the traceback again, I don't think it's a problem with conflicting files. Perhaps an old instance of Nicotine+ was still running in the background after the update?

**Comment by slook** [comment]
@gsandhucode [Nicotine+ 3.3.0](https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.3.0) is released.

Suggest exit the application before upgrading. Please let us know if you encounter any problem or not. Thanks.,

**Comment by gsandhucode** [comment]
Looks like it works now! Thank you!

**Comment by slook** [comment]
Similar error has shown up again in issue #2943
