### ISSUE TITLE
Classic Soulseek re-enter search function

### ISSUE THREAD

**Issue by DarkVoyage** [nicotine-plus/nicotine-plus#2826]
![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/809b94b1-2e33-434e-9fea-267e5d0e2ac0)

Nicotine has copy search function, which uses clipboard. It should be kept, but I'd like to have classic Soulseek copy to search bar function without use of clipboard. It can be added to this menu.

![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/08b9dbf6-6e84-4cf7-ac5b-0aa0b5912fef)

**Comment by DarkVoyage** [comment]
Not going to add another topic. Found uncomfortable behavior in new Nicotine 3.3.0rc that new search is added on the left instead of right.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/c7f0f1ac-6ba3-409f-8172-ceba3461df67)

**Comment by mathiascode** [comment]
> Not going to add another topic. Found uncomfortable behavior in new Nicotine 3.3.0rc that new search is added on the left instead of right. This should be changed back.

Is this only an issue for you when it comes to searches? The behavior was mainly intended for private chats, to avoid showing old chats first, but it could be reverted for other tabs.

**Comment by DarkVoyage** [comment]
>Is this only an issue for you when it comes to searches?

You already know something that I should know? :)
Some things look different, but I'm not sure if it is worse/better or "who cares".

Country flag in separate column is a bad idea, can be added before name. Who needs sorting by flag?
At least if you put that column before name - it adds tree view arrows there and it looks bad...

**Comment by hboetes** [comment]
The magical things ChatGPT can do with your communication.  🤓

> Hello! I hope you're doing well. I've noticed a few things that I believe could be improved upon:
> 
>     Regarding the country flag, I was wondering if it might be possible to move it to be displayed before the user's name. I think this change could enhance the visual appeal. What are your thoughts on this?
> 
>     I was thinking about the sorting feature related to the flag column. Would it be alright to consider placing the flag column before the name column? This adjustment could avoid the addition of tree view arrows, which might improve the overall appearance.
> 
>     I've observed that the user name and flag are repeated on every line, and I was wondering if there's a possibility of having them displayed only once, perhaps without repetition. SoulseekQt takes a different approach by creating more space between users. Could we explore a similar option or perhaps differentiate the colors of user blocks to better highlight results from each user?
> 
> I appreciate your time and consideration in addressing these suggestions. Thank you!

**Comment by mathiascode** [comment]
> Country flag in separate column is a bad idea, can be added before name.

You could make this argument about any column.

> At least if you put that column before name - it adds tree view arrows there and it looks bad... Any column that is put first includes list arrows. They should always be inside User column, because you logically browse that user's results.

Probably true.

> I don't like that user name (and flag) is repeated on every line (this was before too). SoulseekQt doesn't do that, instead it makes more space between users. You can differentiate colors of user blocks to better highlight results from each user.

Boils down to technical reasons, will be revisited once treeviews have been ported to the new Gtk.ColumnView widget.

In any case, the original feature request was resolved.

**Comment by mathiascode** [comment]
> Country flag in separate column is a bad idea, can be added before name. Who needs sorting by flag? At least if you put that column before name - it adds tree view arrows there and it looks bad... Any column that is put first includes list arrows. They should always be inside User column, because you logically browse that user's results.

Slight improvement: expander arrows can no longer end up inside an icon column. If they should always be inside the user column (and what to do if the user column is hidden) can be revisited once we've looked into the Gtk.ColumnView replacement widget.
