### ISSUE TITLE
N+ 3.3.0 transfers not working

### ISSUE THREAD

**Issue by DarkVoyage** [nicotine-plus/nicotine-plus#2827]
I updated to unstable build. Currently it is rehashing my share, but I can't download anything. All online downloads are in Queued status and nothing happens. Search works.

I saw that new network interface option appeared, but it doesn't affect transfers no matter what I choose there or leave empty. But looks like it works, if you choose interface without internet, it will show this error:
Cannot listen on port xxx. Ensure no other application uses it, or choose a different port. Error: [WinError 10049] The requested address is not valid in its context

It is written that this option requires restart, but looks like it needs only server reconnection.

**Comment by mathiascode** [comment]
Transfers only start once shares have been scanned once, to prevent private messages about not sharing files. The database format changed in 3.3.0, which is why it takes a while the first time you launch it. Should be instant after shares have been scanned once.

> It is written that this option requires restart, but looks like it needs only server reconnection.

We will probably auto-reconnect at some point in the future, but until then, the "requires restart" part remains, even though it's not required if you know how to reconnect.

**Comment by DarkVoyage** [comment]
You wrote sooner than I finished rehashing large share. But this is very unexpected behavior. At least you should somehow inform user about this. But better not think for user and allow downloading or at least make it as an option with addition (not recommended).

**Comment by mathiascode** [comment]
Actually, looking closer at the code again, it's not working as intended. Loading share databases on startup is supposed to delay transfers, but not rescanning. I'll fix this.

**Comment by slook** [comment]
Surely only uploads should be postponed while rescanning is in progress, but downloads shouldn't need to be blocked.

**Comment by mathiascode** [comment]
> Surely only uploads should be postponed while rescanning is in progress, but downloads shouldn't need to pend.

Uploads are postponed while rescanning is in progress.

Downloads are postponed until the share dbs are ready and the share messages have been generated (so we have something to send when SoulseekQt's leech detector requests our share). This should at most take a few seconds with large shares.
