### ISSUE TITLE
"Browse Files" doesn't always work on the first try

### ISSUE THREAD

**Issue by metaisfacil** [Nicotine-Plus/nicotine-plus#2829]
Nicotine+ version: https://github.com/nicotine-plus/nicotine-plus/actions/runs/7521643549
Operating System/Distribution:
Windows 10 x64

### Describe the bug
When I right-click a user from search results or the "Upload" tab and do "User Actions" > "Browse Files", the user share will often fail to load the first time, whether that's by getting stuck on the loading animation or outright showing a "unable to request shared files from user". This also impacts the "Auto-browse shares" plugin, in that some users shares will never load before they log back off. If I try to load the share, then close the tab, then try to load the share right away, it will work 90% of the time. If I try to load the share, wait for it to fail, then try to load the share again, it only works about half the time by my observation.

### Expected behavior
The share should load the first time the share is requested.

### Steps to reproduce the bug
I don't know the mechanisms behind the problem so I can't provide reproduction steps.

### Additional context
![nicotine autobrowse share never loads](https://github.com/nicotine-plus/nicotine-plus/assets/93785302/22e9fbc7-6484-496d-8e5e-3228d9f153c1)
![image](https://github.com/nicotine-plus/nicotine-plus/assets/93785302/8c770490-c04c-408a-a6c5-30f9f28a0130)

**Comment by mathiascode** [comment]
Could you send the following to my email address (on my GitHub profile)?

- Debug log that captures the issue (see https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging for instructions, enable all categories). Note that debug logging can be slow when searching for popular things.
- A list of some users that didn't load properly

**Comment by mathiascode** [comment]
I've made a few improvements. Please try the latest build and let me know how it works.

There are some users running a buggy client that tries to send the response on the wrong connection. If you still run into users that fail, send me the names, and I'll look into them.

**Comment by mathiascode** [comment]
> I've actually been trying it for the past 30 minutes already but still experiencing the issue it seems. I'll email you the name of a user who's share I specifically cannot access without refetching after canceling.

There are at least two different issues with similar symptoms, but this specific user seems to show the same buggy behavior I mentioned earlier. Looks like they are still using SoulseekQt, would you happen to know which version?

**Comment by mathiascode** [comment]
Could you try the latest build and see if you still find users with connection issues?

**Comment by mathiascode** [comment]
Have you noticed this issue since, or can it be closed?

**Comment by Babbzzz** [comment]
I have the same issue. I am a new user. But cannot view shares from another user. They can see mine, I can see their profile, private message them, download files, search for files and see their files, but cannot browse their shares. 

MacOS. ProtonVPN manually port forwarded using Wireguard. Ports are open.

**Comment by mathiascode** [comment]
> I am using 3.3.4. I have the same issue. I am a new user. But cannot view shares from another user. They can see mine, I can see their profile, private message them, download files, search for files and see their files, but cannot browse their shares.
> 
> MacOS. ProtonVPN manually port forwarded using Wireguard. Ports are open.

What happens when you try to browse the user? Does it load for a while, and time out eventually?

If you send the username to my email address (on my GitHub profile), I could try to reproduce the issue on my end.
