### ISSUE TITLE
Disable sorting in search

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2830]
I see that after this change:  e5f70bdb738508e5aae5ede86c36ace00b21256f

>For now, this is only done for downloads, uploads, buddies and
chat room users. Remembering the sort order of searches and user
shares is too intrusive, always sort search results by speed instead.

...now the search results are always ordered by some column:
- Either a column selected explicitly
- Or sorted by speed, which always gets enabled by default after unselecting any other column

And seemingly, the chosen ordering is remembered for new searches (good)

For me it's confusing seeing the results moving around during the time that they are loading. Problem is, now i can't unset an ordering, to get them displayed by order or arrival...

I'd suggest enabling the speed column to be also in the tri-state form (asc/desc/unsorted). With this setting now being remembered, it would remain to a user choice again to disable any explicit ordering for search results.

**Comment by mathiascode** [comment]
Without substantial changes, the options are the following:
- Unset the default sort column, don't remember the last sort column from the previous search tab
- Unset the default sort column, but remember the last sort column from the previous search tab

Which one would you rather have?

**Comment by cproensa** [comment]
I'm fine with remembering "the last sort column from the previous search tab", it's a desirable behaviour i think
That's why i suggest: to be able to unset the sort by speed, which now is not possible to do.

i guess, it means: `**Allow to** Unset the default sort column, but remember the last sort column from the previous search tab`  (emphasis mine)

**Comment by cproensa** [comment]
Sorry, i misunderstood: `Remembering the sort order of searches and user
shares is too intrusive, always sort search results by speed instead.`
So, remembering sorting is search is no currently implmeneted
I'm not pushing for that, if you think it's not satisfactory.

However, the initial issue is still:  provide some way to not force a sorted search resultset

**Comment by mathiascode** [comment]
> So, remembering sorting in search is not currently implmeneted I'm not pushing for that, if you think it's not satisfactory.

Doesn't matter to me, but someone else wanted it, so might as well try.
