### ISSUE TITLE
OR operator for searches

### ISSUE THREAD

**Issue by brutalbombs** [nicotine-plus/nicotine-plus#2835]
Hello!

I'm longing for a "OR"-operator for when I'm searching - instead of saving up 4-5 different searches for my wishlist. For instance, when I'm looking for a edit of a song with a special name or with special characters the name could differ, especially if it is old. I want to be able to make a search that would look like this: "Song Name _Club-Dub/"club dub"/clubdub_" where i've separated three different phrases with a slash. I want this search to return all hits on Song Name + Club-dub, Song Name + club dub and song name + clubdub.

Additional question - is it a function in nicotine to add quotation marks around a phrase to search for the specific order of words/letters?

**Comment by mathiascode** [comment]
This is not possible without making changes to all Soulseek clients out there, but you could perhaps get creative with wildcard terms and quotation marks (recently added in 3.3.0), e.g. "song name" *ub

Note that a wildcard character before a complete term, e.g. *dub, will not work with most clients like SoulseekQt.

**Comment by brutalbombs** [comment]
That's a good tip, thanks for coming back to me on this, @mathiascode, and explaining it to me.

**Comment by slook** [comment]
Closing as the suggested feature would require a protocol wide implementation that is not possible.
