### ISSUE TITLE
crash when storage reached out of space

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#284]
1.4.3-20200613030

crashed when disk reached of of space with downloads going on. if started again it doesn't crash.
luckily no data was corrupted

**Comment by mathiascode** [comment]
Do you have a stacktrace/log? In my case, the program doesn't crash, the downloads just stop.

**Comment by alekksander** [comment]
sorry i don't + unable to reproduce. it migh have been search related after all, cause it crashed when i disabled filtering in search result. i will try to narrow this one down. if i get anything will re–open.
