### ISSUE TITLE
SVG icons not shown

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2841]
Nicotine+ version:   3.3.0rc3  GTK 3.24.33   •   Python 3.10.12
Operating System/Distribution:  Ubuntu + docker

Running the latest testing deb package in [this image.](https://hub.docker.com/layers/cproensa/nicotine-docker/latest/images/sha256-b09102b08f353e46004e0be0cb0ec750e75166ac408965c36060e78ec4254851?context=explore)

### Describe the bug

After updating this weekend i have found again the same issue as described here:
https://github.com/nicotine-plus/nicotine-plus/discussions/2312#discussioncomment-6246490

Where the icons and flags are not shown correctly.
At that time, the culprit was that `librsvg2-common` was not installed (not listed as dependency of the debian package).
However, this is not the case now, as this library is still installed.

Do yo have any idea of what may have changed in the last days that may explain this issue?
I think, the last time i refreshed my running image was around 20/21 Jan, so if anything, the regression has been introduced this past week?
On my side, the image is rebuilt unattended (only change is the daily deb pkg), haven't changed the dockerfile for months...

**Comment by slook** [comment]
Guessing the regression occured at https://github.com/nicotine-plus/nicotine-plus/commit/be4c9229480e2fad12a84fd403b993ae5bb82f67 in PR #2838

**Comment by cproensa** [comment]
Thank you... ! This is now fixed
