### ISSUE TITLE
Styling of contextual menu in higlighted tabs

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2845]
Nicotine+ version:   3.3.0rc3  GTK 3.24.33   •   Python 3.10.12
Operating System/Distribution: Linux

### Describe the bug

The contextual menu in a highlighted tab is not style consistent, as it inherits the bold font style.

![imagen](https://github.com/nicotine-plus/nicotine-plus/assets/14123811/828f9927-bbed-42b3-a0ac-984aa0a0b758)

![imagen](https://github.com/nicotine-plus/nicotine-plus/assets/14123811/0e51b3e6-593c-4955-b04d-a22dfaa2f86f)

### Expected behavior

I guess, the style in this menu does not need to be different.

**Comment by mathiascode** [comment]
Ah yes, looks like an old bug wanted to say hello again. :)
