### ISSUE TITLE
Implement server code 160

### ISSUE THREAD

**Issue by JurgenR** [nicotine-plus/nicotine-plus#2854]
### Describe the solution you'd like

Server code 160 contains a list of search terms that should be blocked by the client, and seems to have been added recently (it is sent post-logon). When being queried, search results matching these strings should be filtered out.

### Additional context

Discussion on Reddit here: https://www.reddit.com/r/Soulseek/comments/19czgxk/is_this_legit/

**Comment by mathiascode** [comment]
I did notice the message appearing the other day, but SoulseekQt doesn't use it yet to my knowledge. I'll wait until there's an official update.

> When being queried, search results matching these strings should be filtered out.

I don't think this is true, because there's already a server-side blacklist for searches. It would make more sense for these strings to be checked when rescanning shares, but again, I'll wait until the message is used in the official client.

**Comment by JurgenR** [comment]
It is already used in the latest build (2024.2.1), most stuff is already filtered on the server side however it seems to be less strict for user search. The message is there too, easiest way to reproduce is share a file with the banned name in the filename (eg.: "bryan adams - something") then perform a user search for "something". Under Diagnostics > Searches you will see a message : "Discarding result <filename> due to filter bryan adams" (something along those lines)

**Comment by mathiascode** [comment]
I see, so it's a stricter filter to prevent banned files from being sent in search responses, no matter what search query was used. I'll check how it can be implemented in Nicotine+ without sacrificing performance too much.

**Comment by mathiascode** [comment]
For posterity, these are the exact requirements provided by Soulseek's administrators:

> Basically the only thing the client needs to do is make sure that search results that contain any of the strings in message 160 in either their folder or file name aren't returned to other users.
