### ISSUE TITLE
add mbid tag support 

### ISSUE THREAD

**Issue by petitminion** [nicotine-plus/nicotine-plus#2858]
Idk how the tags (bitrate, size, length) are parsed. Could it be possible to add support for musicbrainz id tag ? Idk where is the db or how content discovery work but to save space having a boolean field mbid would be enough to know if the files are tagged using musicbrainz.

**Comment by slook** [comment]
It's not possible to transmit tags other than bitrate, size, length between clients due to limitations of the protocol. See:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md#file-attribute-types

**Comment by mathiascode** [comment]
Only integer-based file attributes are possible in the Soulseek protocol, and I don't want to extend it unless the official client does so.
