### ISSUE TITLE
search result not appearing with filters enabled by default

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#286]
1.4.3-20200613030 / KDE neon (Ubuntu 18.04 LTS)

search result are not appearing with filters enabled by default:
![image](https://user-images.githubusercontent.com/3148302/84569987-9ed3e380-ad8a-11ea-9ef4-463a7b2fcdab.png)

to get result displayed it's necessary to press enter in one of filter inputs:
![image](https://user-images.githubusercontent.com/3148302/84570096-333e4600-ad8b-11ea-8379-fb08523d6b4b.png)
⎆
![image](https://user-images.githubusercontent.com/3148302/84570065-09851f00-ad8b-11ea-8487-1b1a1634e980.png)

**Comment by mathiascode** [comment]
Did this start happening recently?

**Comment by mathiascode** [comment]
Can you test this branch?
`git clone -b filterfixes https://github.com/mathiascode/nicotine-plus`

**Comment by alekksander** [comment]
it didn't start happening recently. i'd say a month, but is fixed now. thanks!
