### ISSUE TITLE
"Open in File Manager" not working on Windows

### ISSUE THREAD

**Issue by matterharz** [nicotine-plus/nicotine-plus#2860]
Nicotine+ version:  v3.3.0
Operating System/Distribution: Windows 10

### Describe the bug
The context menu item "Open in File Manager" (or similar, I'm using the German interface) does nothing. 

### Expected behavior
It should open the file manager in the respective folder.

### Steps to reproduce the bug
1. Download something (or have something downloaded).
2. Right-click on a file, select "Open in File Manager".
3. Nothing.

Just saw someone else complain about it here: https://www.reddit.com/r/Soulseek/comments/1ahg6ry/comment/kos7fh9/

Btw, thanks for the excellent release!

**Comment by mathiascode** [comment]
> Btw, thanks for the excellent release!

Thanks!

I think the issue is that the change to run scripts without a visible window is too broad, and also affects custom file manager and audio player commands.

You can unset the file manager in Preferences -> URL Handlers for now, to make the file manager window visible.

**Comment by mathiascode** [comment]
Please try 3.3.1.dev1 and see if it works fine for you: https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by matterharz** [comment]
Works fine! One thing, however, that's unusual (but I don't know if it's new) is that when you perform that action on a file that was moved or deleted, the folder that's being opened is the "incomplete" folder. I'm not sure that's to be expected.

**Comment by slook** [comment]
Great! Thanks for your bug report.

> action on a file that was moved or deleted, the folder that's being opened is the "incomplete" folder. I'm not sure that's to be expected.

What sort of other event would you expect?

**Comment by matterharz** [comment]
Hmm, maybe a hint that the file(s) in question are no longer in place, along with the option to clear all these files, now that we have this new feature that does exactly that.

Alternatively, just open the default Soulseek download folder. It's the "incomplete" that I take issue with, since those downloads were, in fact, complete.

**Comment by AurelFR** [comment]
> Nicotine+ version: v3.3.0 Operating System/Distribution: Windows 10
> ### Describe the bug
> 
> The context menu item "Open in File Manager" (or similar, I'm using the German interface) does nothing.
> ### Expected behavior
> 
> It should open the file manager in the respective folder.
> ### Steps to reproduce the bug
> 
>     1. Download something (or have something downloaded).
> 
>     2. Right-click on a file, select "Open in File Manager".
> 
>     3. Nothing.
> 
> 
> Just saw someone else complain about it here: https://www.reddit.com/r/Soulseek/comments/1ahg6ry/comment/kos7fh9/
> 
> Btw, thanks for the excellent release!

Latest version on debian side .The same problem -right click on -open in filemanager does nothing .Debian 12
