### ISSUE TITLE
3.3.0: does not connect to server via tun0 (vpn)

### ISSUE THREAD

**Issue by rexendevar** [nicotine-plus/nicotine-plus#2861]
Nicotine+ version:  3.3.0
Operating System/Distribution: Pop OS 22.04

### Describe the bug
Since updating yesterday, Nicotine will no longer connect to the server when it is configured to connect via `tun0`. It will repeatedly throw timeout errors instead.

### Expected behavior
Nicotine should work just as well with the VPN as it does without it (aside from inevitable decrease in throughput).

### Steps to reproduce the bug
Set up and run the OpenVPN service on your operating system (`sudo service openvpn start`). I use Mullvad for the VPN but it shouldn't matter. 
Open Nicotine+ and go to the network settings. Set the network interface to `tun0` (the vpn) and keep the soulseek server at default configuration (`server.slsknet.org:2242`). Restart Nicotine and attempt to connect.

### Additional context
I'm on a college network and have no control over which ports are open on the internet. I don't think this affects things but I mention it just in case.

**Comment by mathiascode** [comment]
If you enable "Miscellaneous" [debug logging](https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging), the local IP address should be included in the logs (`Local IP address: x.x.x.x`). Does it look correct?

**Comment by rigrig** [comment]
Same problem here (except with a different VPN) 

The debug log shows
`[Misc] Local IP address: <IP-address of the VPN interface>`

Version 3.2.9 works fine, but doesn't seem to log the IP.

**Comment by mathiascode** [comment]
Can you try starting Nicotine+ 3.2.9 with the following command, using the IP logged in 3.3.0, and see if the issue happens there too?

`nicotine --bindip <IP>`

This should be the same way of binding to an interface that Nicotine+ 3.3.0 uses.

**Comment by rigrig** [comment]
Yes, running Nicotine+ 3.2.9 with that argument also fails to connect.   
(I checked the VPN interface still has that same IP)

**Comment by mathiascode** [comment]
Strange. In 3.3.0, if you unset the network interface while the VPN is active, does Nicotine+ connect? Does the IP address remain the same?

**Comment by rigrig** [comment]
It did connect, the IP address changed to that of the default interface (`enp5s0` / `192.168.2.2`)

After selecting either `enp5s0` or my Wi-Fi interface it still connects, so the problem is only with the VPN interface.

**Comment by mathiascode** [comment]
> Edit: I should probably note that my VPN is setup to only provide the interface, not route all traffic over it by default.

Thanks for this information. After doing some research, it seems like socket.bind() isn't enough on Linux in this case.

**Comment by slook** [comment]
@dochdoch @felipehw 
PR #2925 might cause a regression to the fix which was implemented prior in fix to this issue. Latest master 3.3.3dev1 needs to be tested in the wild to verify that fallback doesn't happen in the case of any sort of network outage or other error, link:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md
