### ISSUE TITLE
Issue selecting text on macOS Monterey

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#2862]
Nicotine+ version:  3.3.1.dev1
Operating System/Distribution: macOS Monterey 12.7.3

### Describe the bug
When editable text anywhere on the app is selected (search tab, browse tab, private chat, user info, everywhere else you can enter/edit text), the Command and Option keys no longer work as expected. Holding either of them and pressing any arrow keys to jump the text cursor no longer has any effect and there is no movement of the cursor. The arrow keys only move the cursor when pressed on their own, as well as while holding shift.

**Comment by mathiascode** [comment]
Should be working now. Please try the latest development build: https://nicotine-plus.org/doc/TESTING.html#macos

**Comment by thep50** [comment]
Yep, works now. Thanks!
