### ISSUE TITLE
Retry on uploads no longer works

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#2864]
Nicotine+ version:  3.3.0
Operating System/Distribution: Windows 10

### Describe the bug
I used to be able to highlight a users upload and click the 'R'(right-click + retry) key to get it going without setting an extra slot to be open, now nothing happens

### Expected behavior
Start a transfer without having to open an extra slot

### Steps to reproduce the bug
Highlight upload, click 'R' or right click + retry

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
Thank you as always for your bug reports @woollarding . A fix is implemented in 3.3.1dev1 please do switch to the master branch to verify that everything is working as expected?...
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by mathiascode** [comment]
Unfortunately, Windows builds broke today, so there are no new builds yet. Trying to fix it.

**Comment by woollarding** [comment]
I am assuming there is still no fix as the 3.3.1.dev1 is still not allowing
the forcing of uploads, I'll check back soon.
thanks again for all your hard work guys, this application
is definitely heading in the right direction
I should also report a noticeable improvement so far (3.3.0 as well) in
overall performance... no major lagging/locking

**Comment by mathiascode** [comment]
You're welcome. The Windows builds are working again, so the fix should be available in 3.3.1.dev1 now.
