### ISSUE TITLE
Crash after clearing download folder with 1 file in it

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#2869]
Nicotine+ version:  3.3.1.dev1
Operating System/Distribution: macOS Monterey 12.7.3

I've gotten this crash twice now since updating to the latest version. It happens when clearing a folder in the downloads tab which has only 1 file in it. And I believe both times it was a file that wasn't completed. It doesn't happen every single time though. 

> Nicotine+ Version: 3.3.1.dev1
GTK Version: 4.12.5
Python Version: 3.11.7 (darwin)
>
>Type: <class 'KeyError'>
Value: 'BABYBLUEMUSICA STRANIERA   S - Z\\T\\T-CONNECTION\\FLAC - T-Connection - 1977 - Magic\\04 - Got to See My Lady.flac'
Traceback:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 1081, in on_clear_transfer
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/downloads.py", line 114, in clear_selected_transfers
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/downloads.py", line 841, in clear_downloads
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/downloads.py", line 522, in _clear_transfer

**Comment by mathiascode** [comment]
Is "Autoclear finished/filtered downloads from transfer list" enabled in Preferences -> Downloads?

**Comment by thep50** [comment]
No

**Comment by mathiascode** [comment]
What method did you use to clear the download (button in the bottom bar, context menu, or keyboard shortcut)? Was there any previous moment you tried to remove a download, but nothing happened?

**Comment by thep50** [comment]
Context menu, and no

**Comment by mathiascode** [comment]
Could you keep debug logging enabled for some time, in case the bug happens again? https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging

Please enable the following categories: downloads, connections, messages, transfers, miscellaneous

**Comment by slook** [comment]
Issue https://github.com/nicotine-plus/nicotine-plus/issues/2882 seems to confirm this bug is still happening.

**Comment by mathiascode** [comment]
> Possible suggestion, perhaps a difference in path separators?

I tried experimenting with different separators, but it doesn't seem to be the issue.

I've read through the code many times, but haven't been able to locate the bug or reproduce it on my end. An error message will be logged instead of crashing in 3.3.1.
