### ISSUE TITLE
Program closes after inactivity

### ISSUE THREAD

**Issue by freebass311** [nicotine-plus/nicotine-plus#2875]
Nicotine+ version:  3.3.0  
GTK 4.12.5
Python 3.11.7
 
Operating System/Distribution: Windows 10 Pro: Version 10.0.19045 Build 19045
 
### Describe the bug
The program closes on it's own after a period of inactivity on the server. Or it will close when I try to open it from the system tray after a period of inactivity

### Expected behavior
To stay running regardless of activity

### Steps to reproduce the bug
The server is running headless and I use RDP to connect. Since installing the current version a week ago, everytime I come home from work the program is either closed or closes when I click on the icon in the system tray. 

### Additional context
Screenshots, logs, stacktraces or relevant information.

![image](https://github.com/nicotine-plus/nicotine-plus/assets/159853454/59d63ed2-e53c-4e25-9969-fa03595ebb93)

At the top of the context menu it will show "default" instead of "Hide/Show Nicotine+" as in the image. 

I have debug turned on but there are no logs.

**Comment by mathiascode** [comment]
> At the top of the context menu it will show "default" instead of "Hide/Show Nicotine+" as in the image.

When exactly does it start saying "default"? That's the text the menu item is initialized with, but it shouldn't be possible to revert to it after the window has initialized.

I suspect Nicotine+ crashes somewhere outside of Python. Could you try the [following build](https://github.com/mathiascode/nicotine-plus/actions/runs/7879804004) (scroll down for download links), open a console window, and run Nicotine+.exe inside it? It should show log output, including crashes in GTK.

**Comment by freebass311** [comment]
I installed the build you linked this past weekend and it didn't repeat the behavior. It has stayed running all day yesterday through today. I have attached a text file from the console from the 17th (the day I installed it) which has some GTK crashes. 
[Nic+ console.txt](https://github.com/nicotine-plus/nicotine-plus/files/14337485/Nic%2B.console.txt)

**Comment by mathiascode** [comment]
Nicotine+ 3.3.1 has been released. Please try it and see if you run into the issue.

**Comment by freebass311** [comment]
> Nicotine+ 3.3.1 has been released. Please try it and see if you run into the issue.

I just installed it, and will report back any issues. Thanks!

**Comment by slook** [comment]
Closing as resolved, re-open bug if you run into the issue again.
