### ISSUE TITLE
key error ?? NIcotine kills again on linux with Bob

### ISSUE THREAD

**Issue by Ham23010** [nicotine-plus/nicotine-plus#2882]
Nicotine+ Version: 3.3.1.dev1
GTK Version: 3.24.33
Python Version: 3.10.12 (linux)

Type: <class 'KeyError'>
Value: 'staiic@@zsttx\\Soulseek Shared Folder\\music\\Bob Marley & The Wailers\\Uprising (1980)\\Bob Marley & The Wailers - Uprising - 02 - Real Situation (FLAC 811 kbps).flac'
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/transfers.py", line 1104, in on_clear_transfer
    self.clear_selected_transfers()
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/downloads.py", line 114, in clear_selected_transfers
    core.downloads.clear_downloads(downloads=self.selected_transfers)
  File "/usr/lib/python3/dist-packages/pynicotine/downloads.py", line 837, in clear_downloads
    self._clear_transfer(download, update_parent=False)
  File "/usr/lib/python3/dist-packages/pynicotine/downloads.py", line 521, in _clear_transfer
    del self.transfers[transfer.username + transfer.virtual_path]

![afbeelding](https://github.com/nicotine-plus/nicotine-plus/assets/160082541/5ebd6eb3-8a24-4b4f-9900-342062563014)

**Comment by slook** [comment]
Are you up to date with latest master? https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by mathiascode** [comment]
I see that the screenshot only contains four files, but the counter says five. Did you download one or two files from the second user?

**Comment by Ham23010** [comment]
Yes I Have update found on github last time around here.

deep thanx


Op vr 16 feb 2024 om 03:34 schreef slook ***@***.***>:
