### ISSUE TITLE
add a "hide private files" options to the shares settings; show files as private

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#2886]
an additional options to select whether all surrounding files for friends and trusted shares marked "PRIVATE" can be seen. hide private files

![hide private files](https://github.com/nicotine-plus/nicotine-plus/assets/15121782/5973546f-30ba-420b-9e80-3d0376e0f1e6)

This option will replace the current state of affairs where files for friends are no longer visible to anyone except friends. If the checkbox is not checked, then files for friends in the general search are marked as private.

I know examples and I am sure that many people do not use Nicotine due to the search display features that force them to switch to the official client... personally, I have many times thought that most of my files are hidden from public view for the reason that I I have limited access to them for leeches who do not share anything and would like to limit only access but not hide them from the search.
I think I know that its absence in Nicotine is justified by the fact that people should not trade through this application. but there will be hucksters anyway, whether we like it or not, this inconvenience is also felt by those users who are not involved in sales but simply want more functionality.

**Comment by mathiascode** [comment]
I'm not sure I fully understand what you're asking for.

When checked, the "Visible to everyone" option will show buddy shares, trusted shares, or both, to users who are not on those lists (similar to SoulseekQt). I.e. they will show up with the [PRIVATE] prefix in both search results and when someone browses your shares.

Is this the behavior you want? If the option isn't working as described on your end, there's a bug somewhere.

**Comment by 82d** [comment]
You can do that. but it is better to display private files by default with the [PRIVATE] mark. And hide it from everyone as an option. I understand that at the moment Nicotine does not show private files to other users? I tested this on a second client under a different user and the private files were not showing up.

**Comment by slook** [comment]
> it is better to display private files by default

What are is the reason why you think this would be better?

**Comment by mathiascode** [comment]
> I understand that at the moment Nicotine does not show private files to other users? I tested this on a second client under a different user and the private files were not showing up.

Not by default, but you have the option to show them in Nicotine+ 3.3.0. Showing them should be a conscious action, otherwise search results will be polluted with files that people didn't intend to share or provide access to in the first place.

**Comment by 82d** [comment]
Perhaps so.  So, you need to make the option **"show hidden files in search"**
But personally, I have a bunch of friends with whom I wouldn't want to share valuable files. There are a lot of people on their list that I just wish I could remember. In the list of friends there are banned accounts. the list of people I share valuable music with is "Trusted shares" and these are the tracks I would like to show in the search.

**Comment by 82d** [comment]
There is also a disadvantage that not only hidden tracks, but also a small number of gigabytes of songs are indicated in the information.

**Comment by 82d** [comment]
> What is the reason why you think this would be better?

I think it depends on the implementation of the settings.  for example, you can make an additional choice when setting up a catalog.
- Public
- Buddies
- Trusted Buddies
- Buddies (Privat)
- Trusted Buddies (Privat)
- Privat only    (in this case, the files are accessible only to me, to implement a general search.  but hidden to everyone around)

**Comment by 82d** [comment]
![hide private files3](https://github.com/nicotine-plus/nicotine-plus/assets/15121782/7ceb0444-1da3-49ae-b222-32da90e0b785)

![hide private files2](https://github.com/nicotine-plus/nicotine-plus/assets/15121782/373b9319-919e-486d-9ee1-41fb75145da7)

**Comment by mathiascode** [comment]
> the list of people I share valuable music with is "Trusted shares" and these are the tracks I would like to show in the search.

Then checking `Visible to everyone -> Trusted shares`, while leaving `Buddy shares` unchecked, will do the job.

I'm not adding more share categories. You have two "private" ones, buddies and trusted buddies, and the option to make them visible when sending search results and when someone browses your shares. If this isn't enough, there are clients like SoulseekQt and slskd with more fine-grained user group systems.
