### ISSUE TITLE
Cannot save file error

### ISSUE THREAD

**Issue by jimmybreeze** [nicotine-plus/nicotine-plus#2888]
Nicotine+ version:  3.3.0
Operating System/Distribution: Windows 11 64-bit 23H2

I am getting this in the log

`2024-02-19 18:56:41 Cannot save file in C:\Users\myname\AppData\Roaming\nicotine\incomplete: [Errno 22] Invalid argument: b'\\\\?\\C:\\Users\\myanme\\AppData\\Roaming\\nicotine\\incomplete\\INCOMPLETE80003573ef0ae75eb95a7e2d3df76db8Icon\r'`

Every 15 minutes.

Everything is working as normal.

**Comment by mathiascode** [comment]
It seems like a file isn't downloading properly, due to some issue with the file name. What's the full file name?

**Comment by jimmybreeze** [comment]
Oddly, I do not have that file in AppData\Roaming\nicotine\incomplete

I have no pending downloads so I can delete that folder if that will help.

**Comment by jimmybreeze** [comment]
Just noticed it actually stopped last night, so guess it resolved itself?

**Comment by mathiascode** [comment]
It seems like the file Nicotine+ tried to download contains a carriage return character (`\r`) in the file name, which isn't allowed on Windows. We need to filter out such characters.

**Comment by slook** [comment]
It's possible that the illegal character might arise from the `username`, or that the `virtual_path` is not encoded:

https://github.com/nicotine-plus/nicotine-plus/blob/405f9c53b11b03aaa2f4231e0cf07c6eabddc132/pynicotine/downloads.py#L704
