### ISSUE TITLE
Search results navigation missing

### ISSUE THREAD

**Issue by mrror** [nicotine-plus/nicotine-plus#2920]
Prior to version 3.3, I was able to right-click in the header of a search tab to show a list of all tabs, including the ones not visible on screen.
This was particularly useful to know which tabs had new results and to open them directly (with the left/right arrows, you couldn't know which tabs had new results)
This can't be done anymore with the new look.
(Windows 11, Nicotine+ 3.3)

### Describe the solution you'd like

Is there something I'm missing, or could your bring this feature back?

### Additional context

![2024-03-03](https://github.com/nicotine-plus/nicotine-plus/assets/6650443/d3b6cf82-3844-4aab-b2ae-03202fafa1b2)

**Comment by slook** [comment]
That menu is now handled within the "All Tabs" widget (!) button widget to the right-hand side, which is out of context with the search toolbar so it is not available from there anymore, but the functionality does still exist...

![image](https://github.com/nicotine-plus/nicotine-plus/assets/88614182/125bcea7-dac5-4054-9dff-b182b1ebd52e)

To indicate pages with new results, the highlighter icons have been removed in favour of an * astisk character. I think this had to be done for GTK compatibility reasons, so it's not currently possible to bring the old menu back like the way it was before.
