### ISSUE TITLE
Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'>on attempt to browse folder from search results

### ISSUE THREAD

**Issue by 501NotImplemented** [nicotine-plus/nicotine-plus#2921]
Nicotine+ version:  Nicotine+ 3.3.3.dev1
Operating System/Distribution:
Windows 11 Pro
Version	23H2
OS build	22631.3235
Experience Windows Feature Experience Pack 1000.22687.1000.0

### Describe the bug
Unable to browse user shares found in the search on first attempt, an exception occurs from the log.

### Expected behavior
User shares should be loaded successfully

### Steps to reproduce the bug
1. Enter a search term in the Search tab
2. Right click on the found results
3. Select 'Browse folder'
4. Go to 'Browse shares' tab

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/61db1738-c393-4d7f-a79c-ff570a611718)
Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 1371147 contents <memory at 0x0000020e7161d540>: unsupported operand type(s) for +: 'memoryview' and 'int'

If I click the Retry button - the user shares are loaded successfully.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/f85d9d23-602b-4bce-8793-f0957181ed6d)

**Comment by slook** [comment]
If your session is still active can you scroll up the log to copy and paste the entire stack trace that has line ending with
`TypeError: 'builtin_function_or_method' object does not support the context manager protocol`
30 or so lines just before 18:54:52.

**Comment by 501NotImplemented** [comment]
@slook the log above is related to scan reshares (I assume issue #2907 )

Full log attached.
[debug_log.txt](https://github.com/nicotine-plus/nicotine-plus/files/14474159/debug_log.txt)

**Comment by slook** [comment]
```
03.03.2024 18:42:02 Rescanning shares…
03.03.2024 18:42:08 Serious error occurred while rescanning shares. If this problem persists, delete C:\Users\************\AppData\Roaming\nicotine/*.dbn and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 281, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 458, in rescan_dirs
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 409, in set_shares
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 216, in update
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/shares.py", line 198, in __setitem__
TypeError: 'builtin_function_or_method' object does not support the context manager protocol
03.03.2024 18:54:52 [Misc] Saved configuration: C:\Users\************\AppData\Roaming\nicotine\config\config
03.03.2024 18:55:00 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 1371147 contents <memory at 0x0000020e7161d540>: unsupported operand type(s) for +: 'memoryview' and 'int'
```

**Comment by 501NotImplemented** [comment]
@slook no, I've just reproduced this issue without sharing the corrupted FLAC files.

> 03.03.2024 22:20:22 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 1593267 contents <memory at 0x0000025dfa765840>: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by slook** [comment]
To clarify, then afterwards it is successful upon the second attempt at browsing yourself, without any error?

**Comment by mathiascode** [comment]
There are two different issues here: one related to rescanning, one related to browsing shares of other users.

@501NotImplemented Can you browse the shares of a few more users, see if you get the SharedFileListResponse error, and send the affected usernames to my email? Preferably also retry browsing these users a few times to see if the issue happens consistently.

**Comment by slook** [comment]
The reported error occurs when browsing self.

**Comment by 501NotImplemented** [comment]
@slook the issue is related to browsing **_other_** user files.

@mathiascode sure, I will do that.

**Comment by 501NotImplemented** [comment]
@mathiascode please check your email. I was able to reproduce the issue 2 times while attempting to browse shares from users in my buddy list.
Each time the exception message was a bit different, but still.

User shares 328128 files
> 03.03.2024 22:39:40 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 7484013 contents <memory at 0x0000025dfa8304c0>: unsupported operand type(s) for +: 'memoryview' and 'int'

User shares 1089730 files
> 03.03.2024 22:41:55 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 26180845 contents <memory at 0x0000025dfa830400>: can only concatenate str (not "int") to str

**Comment by 501NotImplemented** [comment]
Another update: this morning I tried to browse user files from the buddy list (same user as reported above), there were no exceptions logged, and the blue progress spinner loaded in the Browse Shares tab, but after that app froze a couple of times, and was unresponsive, until closed by Windows. The third time it just crashed. Nothing logged.

**Comment by slook** [comment]
Has your shares database sorted itself out now?

Do you still encounter the spurious errors from the Python 3.11.8 interpreter upon first attempt at browsing another user's shares?

**Comment by 501NotImplemented** [comment]
@slook after the upgrade to Nicotine+ 3.3.3.dev2 the app correctly displays the number of my shared files.
As for browsing other user shares - I'll test it and keep you updated with results.

**Comment by 501NotImplemented** [comment]
On first attempt:
![image](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/286c0c65-c66b-44c2-a32a-d2b1277602cd)
`06.03.2024 0:00:46 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 3670405 contents <memory at 0x000001f5ac842440>: can only concatenate str (not "int") to str`

After clicking retry - the shared list was loaded successfully.

Nicotine+ 3.3.3.dev2

**Comment by 501NotImplemented** [comment]
For now - it seems that Nicotine+ 3.3.3.dev2 is a bit more stable on browsing the files, at least it's not freezing.

![06 03 2024_00 33 57_REC](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/4d6d4a5f-e559-4439-8b15-3efca1293593)
![06 03 2024_00 36 53_REC](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/c6dc7385-a00c-40d0-beaf-44c09a2a8818)

`06.03.2024 0:34:40 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 21689477 contents <memory at 0x000001f5af4ad000>: can only concatenate str (not "int") to str`

**Comment by slook** [comment]
Thank you. Please can you enable the "[Debug] Connections" and "[Debug] Messages" as well as the [Misc] log catagory and capture all the relevant log lines preceeding the parsing error. With the usernames and addresses censored out of course.

**Comment by mathiascode** [comment]
I might have to take a closer look at the Windows builds. So far I haven't been able to reproduce the issue on Linux.

**Comment by 501NotImplemented** [comment]
The app has frozen again in an attempt to browse files. Nicotine+ 3.3.3.dev2

**Preconditions**:
The user to browse files is online
Transfers to this user are present in the Downloads tab

**Steps:**

1. Select finished transfer from the user
2. Right click on the transfer
3. Select browse folder

Actual result: Browse shares tab is opened. The progress bar starts to load, but after the app is frozen and unresponsive.
Expected result: The share list should be successfully loaded.

_Note:_ GetUserStatus message on 10:44:46 is sent to other user than selected for share

`06.03.2024 10:44:34 [Misc] Unable to parse peer message type <class 'pynicotine.slskmessages.SharedFileListResponse'> size 5445234 contents <memory at 0x0000024d5a4a6500>: can only concatenate str (not "int") to str
06.03.2024 10:44:46 [Msg] IN: <S - GetUserStatus> {'user': '****', 'status': 1, 'privileged': True}
06.03.2024 10:45:06 [Conn] Shutting down socket <socket.socket fd=2424, family=2, type=1, proto=0, laddr=('**********', 59116), raddr=('**********', *****)>
06.03.2024 10:45:06 [Conn] Closing socket <socket.socket fd=2424, family=2, type=1, proto=0, laddr=('**********', 59116), raddr=('**********', *****)>
06.03.2024 10:45:06 [Conn] Removed connection of type P to user ********** ('**********', *****)
06.03.2024 10:45:06 [Conn] Removing PeerInit message of type P for user ********** ('**********', *****)
06.03.2024 10:45:06 [Msg] OUT: <P - SharedFileListRequest> {}
06.03.2024 10:45:06 [Conn] Sending message of type <class 'pynicotine.slskmessages.SharedFileListRequest'> to user **********
06.03.2024 10:45:06 [Conn] Attempting direct connection of type P to user ********** ('**********', *****)
06.03.2024 10:45:06 [Msg] OUT: <S - ConnectToPeer> {'token': 28, 'user': '**********', 'conn_type': 'P', 'ip_address': None, 'port': None, 'privileged': None, 'unknown': None, 'obfuscated_port': None}
06.03.2024 10:45:06 [Conn] Attempting indirect connection to user ********** with token 28
06.03.2024 10:45:06 [Conn] Established outgoing connection of type P with user **********. List of outgoing messages: [<pynicotine.slskmessages.SharedFileListRequest object at 0x0000024d59cd82c0>]
06.03.2024 10:45:06 [Conn] Sending PeerInit message of type P to user **********
06.03.2024 10:45:06 [Msg] OUT: <I - PeerInit> {'sock': <socket.socket fd=2424, family=2, type=1, proto=0, laddr=('**********', 59271), raddr=('**********', *****)>, 'init_user': '**********', 'target_user': '**********', 'conn_type': 'P', 'indirect': False, 'token': 28, 'outgoing_msgs': [<pynicotine.slskmessages.SharedFileListRequest object at 0x0000024d59cd82c0>]}
06.03.2024 10:45:06 [Msg] OUT: <P - SharedFileListRequest> {}`

**Comment by mathiascode** [comment]
Since the errors are different every time, make no sense, and nobody else has encountered these issues so far, I wonder if there's some kind of memory corruption going on. Perhaps faulty RAM? Could you run some of the memory diagnostic tools provided by Windows?

**Comment by 501NotImplemented** [comment]
@mathiascode as for the RAM - I just had a chance to run Windows Memory Diagnostic about a month ago, took a while, but it reported no issues. Will try again if I'll have some free time. It was very slow, took a couple of hours to finish.

**Comment by mathiascode** [comment]
In the meantime, I suppose you could downgrade to Nicotine+ 3.2.9, and see if you encounter any similar errors.

**Comment by slook** [comment]
@501NotImplemented were to able to downgrade to 3.2.9 to test this further?
