### ISSUE TITLE
Nicotine+ 3.3.3.dev1 critical error on background wishlist search with excluded terms

### ISSUE THREAD

**Issue by 501NotImplemented** [nicotine-plus/nicotine-plus#2924]
### Describe the bug
Nicotine+ Version: 3.3.3.dev1
GTK Version: 4.12.5
Python Version: 3.11.8 (win32)

Type: <class 'TypeError'>
Value: endswith first arg must be str or a tuple of str, not Search
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 961, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 290, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 435, in _file_search_request_distributed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 681, in _process_search_request
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 563, in _create_search_result_list

### Expected behavior
The app should continue working

### Steps to reproduce the bug
No particular, I was away from PC, and when I returned - the app crashed. From the logs, I assume it was a background wishlist search.

### Additional context
![image](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/51fca3b8-26ee-4155-9057-12b6f8c07f94)

> 04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\00.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\01 На Заре(millenium version).flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\01.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\02 День освобождения.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\02.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\03 Смерти нет.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\03.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\04 Фальстарт.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\04.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\05 Падение-взлет.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\05.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\06 Падение-взлет.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\06.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\07 День вечного сна.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\07.jpg from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\08 На восток.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\09 Дайте огня.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\10 Вальс.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\11 Встаньте, братья.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\12 Гражданские войны.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\13 В Петропавловске-Камчатском полночь.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\14 Порабощенные трудом.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\15 Тува-1.flac from user **** for search term "alians flac -zare"
04.03.2024 11:55:36 [Misc] Filtered out excluded search result @@ypfoy\Music\complete\complete\Alians - Na Zare (2001) Flac\Alians - Na Zare.log from user **** for search term "alians flac -zare"

**Comment by slook** [comment]
> I assume it was a background wishlist search

No, it is unrelated to your wishlist, it is an incoming search from another peer (that may or may not be manually searching).

**Comment by 501NotImplemented** [comment]
@slook strange, because this term is added to my wishlist as well.

**Comment by mathiascode** [comment]
> Value: endswith first arg must be str or a tuple of str, not Search

I misread this error message, it's one of the search term words that is the wrong type.

`self` is Search, so it's possible that we end up using it somehow, though I'm not sure how. I changed the variable names so they don't share the same name at least: https://github.com/nicotine-plus/nicotine-plus/commit/6f2996c2e6fc3ef3f2ee2041840be63014519d90

**Comment by mathiascode** [comment]
The crash happened when someone used a partial word in a search query, e.g. *lac (for flac).

Can you try the following?
1. Search Tab -> Change "Global" search to "User"
2. Leave username entry blank (searches your own files)
3. Search for something you know exists in your shares, and include a partial word in your search query (e.g. `music *lac`)

Does the crash happen then?

**Comment by mathiascode** [comment]
> `self` is Search, so it's possible that we end up using it somehow, though I'm not sure how. I changed the variable names so they don't share the same name at least: [6f2996c](https://github.com/nicotine-plus/nicotine-plus/commit/6f2996c2e6fc3ef3f2ee2041840be63014519d90)

If I change `partial_word` to `self` on [this line](https://github.com/nicotine-plus/nicotine-plus/blob/c39868a1e713a89a56100ea9083a16a7500a0657/pynicotine/search.py#L563), I get the same error message as originally reported:
```
Type: <class 'TypeError'>
Value: endswith first arg must be str or a tuple of str, not Search
```

How `self` ended up there in the first place is a mystery, of course...

**Comment by 501NotImplemented** [comment]
@mathiascode just tried with the partial search term - the search results are returned correctly, and the app is running, no new logs added.

**Comment by slook** [comment]
Please upgrade to Nicotine+ 3.3.3dev2 for ongoing testing:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

**Comment by 501NotImplemented** [comment]
A quick update: I've faced the same issue a couple of times in 3.3.3.dev2 version. I don't have additional logs or steps as of now.

**Comment by mathiascode** [comment]
Could you downgrade to Nicotine+ 3.2.9 and see if any errors appear there?

**Comment by 501NotImplemented** [comment]
@mathiascode, could you please share where I can download version 3.2.9? The latest stable version https://nicotine-plus.org/doc/DOWNLOADS.html#windows is 3.3.2, and I have already switched to it for now.

**Comment by mathiascode** [comment]
Downloads are at the bottom of this page: https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.2.9
