### ISSUE TITLE
No icon in taskbar when running in background

### ISSUE THREAD

**Issue by hyppyp** [nicotine-plus/nicotine-plus#2928]
Nicotine+ version:  nicotine_3.3.2-202402251923~ubuntu22.04.1_all.deb
Operating System/Distribution: Raspberry Pi 4b 8gb with Pi OS Bookworm 64bit

### Describe the bug
When trying to run nicotine in the background no icon is shown in the taskbar. Program does run.
Worked with nicotine_3.2.9-202303052115~ubuntu22.04.1_all.deb before and this problem did not occur

**Comment by slook** [comment]
What is the GTK version displayed in Menu -> Help -> About Nicotine+ ?

Which window manager desktop environment does Pi OS use?

**Comment by hyppyp** [comment]
GTK 3.24.38

From Wikipedia:
Raspberry Pi OS has a desktop environment, PIXEL (short for *P*i *I*mproved
*X*windows *E*nvironment, *L*ightweight),[10]
<https://en.m.wikipedia.org/wiki/Raspberry_Pi_OS#cite_note-10> based on LXDE
<https://en.m.wikipedia.org/wiki/LXDE>,[11]
<https://en.m.wikipedia.org/wiki/Raspberry_Pi_OS#cite_note-11> which looks
similar to many common desktops, such as macOS
<https://en.m.wikipedia.org/wiki/MacOS> and Microsoft Windows
<https://en.m.wikipedia.org/wiki/Microsoft_Windows>.

Verzonden vanaf mijn mobiele... huh dinges

Op ma 4 mrt. 2024 23:59 schreef slook ***@***.***>:

**Comment by slook** [comment]
This issue might take a while to investigate. It's depends how easy it is to emulate.

https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/

_There is still a taskbar at the top of the screen that allows you to launch applications and see the status of various systems, but this is a totally new application. Under Bullseye, this was an application called lxpanel, but this has now been replaced with wf-panel-pi (short for “wayfire panel for Raspberry Pi”)._

_This was based on wf-shell, the example panel application from the authors of Wayfire, but we have extensively modified it to look and work like lxpanel. The largest part of this work was to port all the existing lxpanel plugins — the icons which control volume, network, Bluetooth, etc — so that they now all work with wf-panel-pi._

- The system tray — _the area on the taskbar where applications can put their own icons — has to use a completely new mechanism to work with Wayland’s security model. This means that some applications may need to be updated in order for their icons to appear there._

https://github.com/raspberrypi-ui/wf-panel-pi

**Comment by mathiascode** [comment]
There seem to be two desktop environments: an older one based on LXDE, and a newer, Wayfire-based one. Is there any system information that gives more details about which one is used?

The Wayfire-based one seems to implement the StatusNotifier spec at least, so our tray icon should work with it: https://github.com/raspberrypi-ui/wf-panel-pi/blob/fbfa317be0e11bd8f331fe303c7091ca37c4a3c1/src/panel/widgets/tray/watcher.cpp

**Comment by hyppyp** [comment]
I’m using X11, the ‘old’ variant. Wayland is not 100% supported in Pi OS Bookworm (yet). As already stated, the former 2023 version of Nicotine does not have this issue, while using the exact same environment.

 

 

Van: Mat ***@***.*** 
Verzonden: dinsdag 5 maart 2024 15:22
Aan: nicotine-plus/nicotine-plus
CC: hyppyp; Author
Onderwerp: Re: [nicotine-plus/nicotine-plus] No icon in taskbar when running in background (Issue #2928)

 

There seem to be two desktop environments: an older one based on LXDE, and a newer, Wayfire-based one. Is there any system information that gives more details about which one is used?

The Wayfire-based one seems to implement the StatusNotifier spec at least, so our tray icon should work with it: https://github.com/raspberrypi-ui/wf-panel-pi/blob/fbfa317be0e11bd8f331fe303c7091ca37c4a3c1/src/panel/widgets/tray/watcher.cpp

**Comment by mathiascode** [comment]
> I’m using X11, the ‘old’ variant. Wayland is not 100% supported in Windows OS Bookworm (yet). As already stated, the former 2023 version of Nicotine does not have this issue, while using the exact same environment.

Nicotine+ 3.3.0 removed the old X11-specific tray icon implementation in favor of the [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) spec (known as AppIndicator on the Ubuntu side). Most desktop environments should support it by now, but it's possible that LXDE doesn't. I'll look into it and see if that's the case or not.

**Comment by hyppyp** [comment]
Sorry to inform you that despite version 3.3.3. solved the icon issue initially, since a couple of days the issue has reappeared over here. Same old routine, no tray icon at all... I'm working on a Raspberry Pi 5 with Pi OS Bookworm (X11). Don't know if I need to open an issue, starting here.

**Comment by mathiascode** [comment]
3.3.3 hasn't been released yet, can you check that you're running 3.3.3rc2? The tray icon code hasn't been changed since this issue was closed.

**Comment by hyppyp** [comment]
Hi Mat,

 

Yes, 3.3.3.dev2. Worked like a charm, but that changed a few days ago. Reinstalled it, to no avail. Must have to do with some Bookworm updates because there are a few tiny changes in the look of the program.

To make it even stranger, this issue seems to affect the Pi5 only. I use a Pi4 which has an identical Bookworm installation and the same updates had no negative outcome there. Please have a look at the screenshots, the icons are slightly different.

 

I am very sorry to bother you with this, if you can sort this one out you are a magician in my eyes…. ;)

 

Henri

 

Van: Mat ***@***.*** 
Verzonden: woensdag 1 mei 2024 23:59
Aan: nicotine-plus/nicotine-plus
CC: hyppyp; Author
Onderwerp: Re: [nicotine-plus/nicotine-plus] No icon in taskbar when running in background (Issue #2928)

 

3.3.3 hasn't been released yet, can you check that you're running 3.3.3rc2? The tray icon code hasn't been changed since this issue was closed.

**Comment by hyppyp** [comment]
Hi mathiascode, you are quite right, the Pi4 GTK version is 3.24.38, the Pi5 GTK version is 4.8.3..
So the icon issue has to do with GTK 4 I guess. Can this be resolved in the program?
And if not, how do I start Nicotine with GTK 3 instead of 4? (googled it, can not find)

hyppyp

**Comment by mathiascode** [comment]
The X11 tray icon implementation was only available in GTK 3 (removed in GTK 4), and it doesn't seem worth reimplementing it, when most desktop environments now support the newer tray icon standard.

Try adding this line to your `~/.bashrc` file. Nicotine+ should use GTK 3 after that.
`export NICOTINE_GTK_VERSION="3"`

**Comment by hyppyp** [comment]
Thanks for the explanation, I can understand not supporting GTK anymore. However, the issue is that Wayland is not yet fully supported in Pi OS Bookworm, X11 is still recommended.

Adding export NICOTINE_GTK_VERSION="3" in .bashrc works, but only when Nicotine is started from a command line in a terminal. It would be nice to have that option working when starting the program from the menu.

Anyway, thanks for the help and I still love Nicotine+!

hyppyp

**Comment by mathiascode** [comment]
Sorry, I believe it needs to go into `~/.bash_profile` instead to affect the whole session. You also need to restart, of course.

**Comment by hyppyp** [comment]
Created _.bash_profile_, added _export NICOTINE_GTK_VERSION="3"_ 
Saved, restarted. Not the solution I fear, still GTK4 :(

**Comment by mathiascode** [comment]
Perhaps try `~/.profile` instead.

**Comment by hyppyp** [comment]
Bingo! You da man, thanks!!

hyppyp


Op do 2 mei 2024 23:28 schreef Mat ***@***.***>:
