### ISSUE TITLE
Refresh Files button not working

### ISSUE THREAD

**Issue by KaelanMikla** [nicotine-plus/nicotine-plus#2937]
Nicotine+ version:  3.2.2
Operating System/Distribution: Nobara Linux 39

### Describe the bug

After upgrading to version 3.3.2, the files displayed in the profile are not visually updated when closing and opening the program, nor when pressing the update button. The upload speed and the number of folders are also not updated, while the upload slots and queues are updated.

Clarification:
It is important to mention that there is no real problem with uploading files. They are uploaded correctly if you browse the folders manually. The problem is that the information is not updated in the profile and friends list.

### Expected behavior

Normally, I have a tab open with my profile to see the queues and also to visualize if the files are added correctly after adding them by hitting the refresh button

![Captura de pantalla_20240312_221022](https://github.com/nicotine-plus/nicotine-plus/assets/37126796/82bac776-d9fb-4fef-ad16-c1d1dd495d7a)

**Comment by slook** [comment]
Fixed in https://github.com/nicotine-plus/nicotine-plus/commit/89a19f04b5a8310eed4da6cf9902c1627cc619cd in 3.3.3.dev2 https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md
