### ISSUE TITLE
Crash on Windows 10 when attempting to open path via double click that has already been moved 

### ISSUE THREAD

**Issue by ali-imad** [nicotine-plus/nicotine-plus#2938]
Nicotine+ version:  3.2.9
Operating System/Distribution:
Windows 10

### Describe the bug
If you attempt to open a folder which has been moved from the download folder but is still present in the Nicotine+ "Downloads" tab, Nicotine+ will hang and subsequently crash to desktop

### Expected behavior
A warning message and the path for the download to be cleared

### Steps to reproduce the bug
Download a folder, move the folder from the download directory, then try to open a file from the folder. Nicotine+ will hang and subsequently crash to desktop.

**Comment by mathiascode** [comment]
Is this still an issue in Nicotine+ 3.3.2?

**Comment by slook** [comment]
Is this the same as resolved issue https://github.com/nicotine-plus/nicotine-plus/issues/2961 ?

**Comment by mathiascode** [comment]
Seems to be fixed in 3.3.x. I get an error message in the status bar when a path doesn't exist anymore, as expected.
