### ISSUE TITLE
Ability to automatically retry the transfers with 'Connection timeout' status

### ISSUE THREAD

**Issue by 501NotImplemented** [nicotine-plus/nicotine-plus#2939]
### Describe the solution you'd like
As a user, I would like to have the ability to enable the automatic retry transfers that have '**Connection timeout**' status, to automatically resume them in case the initial connection attempt failed, but the upcoming connection might succeed.

### Additional context
As for now, the transfers from some users fail with '**Connection timeout**', but can successfully continue or start if I manually right-click on them and select '**Resume**'. I would like to get this feature enabled _**by default**_, instead of **manually** monitoring the downloads status.
This feature could reuse the exponential retries or something or be limited to a specific number of retries before failing.

**Comment by mathiascode** [comment]
This is already done every three minutes.

**Comment by mathiascode** [comment]
> Maybe it's also worth specifying it somewhere, e.g. in a status tooltip in a downloads grid?

It's something we can revisit, but it will probably not happen now.
