### ISSUE TITLE
Cannot show East Asian Characters like Chinese, Japanese and Korean

### ISSUE THREAD

**Issue by dnet890** [nicotine-plus/nicotine-plus#2949]
Nicotine+ version:  3.3.2
Operating System/Distribution: Kubuntu

### Describe the bug
when I typed East Asian characters. it just show garbled word 

### Expected behavior
it should shows the font properly

### Steps to reproduce the bug
type east asian characters on search bar and it shows garbled words

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/29157187/81986b77-e523-4cbe-a060-b34c69985a62)

**Comment by mathiascode** [comment]
Likely missing the required fonts on your system. Do other GTK apps have the same issue?

**Comment by dtantono** [comment]
I have a qalculate GTK and they can rendered East Asian font properly. What do you think?
<img width="493" alt="2024-03-21_09-53_2" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/5e35ecb1-04b1-40ed-986d-62fcb1555392">
<img width="401" alt="2024-03-21_09-53_1" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/53bddc63-8b84-438f-8b85-b32e6892bbab">
<img width="410" alt="2024-03-21_09-53" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/ca8cc2f5-4186-4b07-9c7f-67160769c5e5">

The issue is for Nicotine Flatpak app

**Comment by cproensa** [comment]
in case it helps: in my image i add `fonts-noto-cjk` to show japanese characters.
I don't know how does it works in the flatpak...

**Comment by slook** [comment]
> The issue is for Nicotine Flatpak app

Did you try another install method as well to confirm that the problem doesn't exist in the ppa or deb package install method?

**Comment by mathiascode** [comment]
It could be an issue with the font cache. Could you rename `/home/<user>/.var/app/org.nicotine_plus.Nicotine/cache/fontconfig` to e.g. `fontconfig.old`, and see if that changes anything?

**Comment by dtantono** [comment]
<img width="881" alt="2024-03-21_22-52" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/8b828fb6-72eb-4575-90f6-997d15b58a2f">
<img width="946" alt="2024-03-21_22-51" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/555c88cb-8cd5-4ac3-9c6d-5f0220c406bf">
Do you mean these empty folders right? it does not worked

**Comment by mathiascode** [comment]
@dtantono Are you using Kubuntu 23.10? Perhaps it's this issue: https://www.reddit.com/r/kde/comments/1am8qye/broken_fonts_in_flatpak_gtk_apps/

You could try this suggested solution: https://www.reddit.com/r/kde/comments/1am8qye/comment/kpk731b/

**Comment by dtantono** [comment]
I use Kubuntu 22.04 LTS which is lower than that and I tried to type that command. But, the output is:
<img width="793" alt="2024-03-28_09-21" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/77ee6150-2fac-4ef9-b30f-31a8e5dcec53">

**Comment by mathiascode** [comment]
Is this still an issue in the latest update?

**Comment by dtantono** [comment]
yes for flathub version

**Comment by mathiascode** [comment]
I've tried the Nicotine+ Flatpak on a fresh installation of Kubuntu 22.04, but all characters appear without issues.

Could you install another GTK 4 Flatpak, e.g. GNOME Calculator, and see if it has the same issue? If so, there probably isn't much we can do in Nicotine+ itself.

`flatpak install org.gnome.Calculator`

**Comment by dtantono** [comment]
I tried to install the related app and it shows related issue. What do you think?　
<img width="227" alt="2024-06-27_11-15" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/d1717a9d-8399-494a-b6f5-1ebcece1db8c">

<img width="876" alt="2024-06-27_11-10" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/5e73a96a-d550-4b4c-a18e-4d42d0f25dce">

https://github.com/nicotine-plus/nicotine-plus/assets/29157187/4a421298-24e8-4b3e-94e6-850e6ce3bb14

**Comment by slook** [comment]
That shows it's definitely not a bug in Nicotine+ then. Suggest you should report the problem to a maintainer of your distro.

Are installation methods other than Flatpak also affected, such as from the PPA, .deb or pip?

**Comment by dtantono** [comment]
So, Flatpak is not officially maintained by Nicotine?

**Comment by mathiascode** [comment]
> to a maintainer of the Flatpak

That would be me.

@dtantono Hard to say what's going on, since the Flatpak works in a fresh installation on Kubuntu. Could you try the following things?

- Try changing the global font in Nicotine+ Preferences -> User Interface. Do fonts appear correctly in the list there?
- Add a new local user on your computer with default settings, and try the Flatpak there

**Comment by dtantono** [comment]
@mathiascode you are right by go to this Setting and change the font manually solved the issue and this behavior quite different from the PPA (the PPA can detect it automatically). Is it possible for the next update it can detect the CJK font automatically like the current PPA version?
<img width="563" alt="2024-07-01_13-27" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/74249fbc-bfd9-4cc0-8c1e-2a14f0cea2c2">

<img width="780" alt="2024-07-01_13-27_1" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/3757bc31-05db-42f7-ac84-de1627b7135c">

**Comment by mathiascode** [comment]
Thanks, looks like it's at least detecting the fonts, but not applying them automatically for whatever reason.

> Is it possible for the next update it can detect the CJK font automatically like the current PPA version?

That's how it's supposed to work, but something is wrong with Flatpak or a dependency it interacts with on your system.

Can you try the two other steps I mentioned, and see if there's any difference?

**Comment by dtantono** [comment]
I tried these solutions:
1. Add a new local user on your computer with default settings, and run the new Flatpak instance there
2. Install Flatseal, and set the NICOTINE_GTK_VERSION=3 environment variable for Nicotine+
So, only change the font settings manually works within the app.
What do you think?
<img width="958" alt="2024-07-01_14-28" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/31aa29fc-54f5-4407-a0c9-cf56e18a8c5d">
<img width="728" alt="2024-07-01_14-27" src="https://github.com/nicotine-plus/nicotine-plus/assets/29157187/8af9db02-b215-44d9-a94c-55abcaa03872">

**Comment by mathiascode** [comment]
I'll do some more research and see if I can find a way to debug this issue better.

**Comment by mathiascode** [comment]
I've tested the Flatpak package on fresh installations of both Kubuntu 22.04 and 24.04, and these characters show up correctly there. Since we're not doing anything special with fonts in Nicotine+ or the Flatpak package, there's nothing we can do on our end.
