### ISSUE TITLE
Help -> Report a Bug broken

### ISSUE THREAD

**Issue by kiplingw** [nicotine-plus/nicotine-plus#2954]
Nicotine+ version:  3.3.3.dev2
Operating System/Distribution: Ubuntu Mantic

Clicking Help -> Report a Bug is broken on my system. It looks as though Nicotine+ has `mozilla(1) ` hardcoded into it. If the binary doesn't exist, it doesn't work.

I recommend using `xdg-open` instead, which on Debian based systems this is found in the `xdg-utils` package.

**Comment by mathiascode** [comment]
I believe you either have a very old config, or you set a URL handler at some point. The default URL handler used to be `mozilla` in Nicotine+ <=1.2.4, changed to `firefox` in 1.2.5 (18 years ago), and finally changed to an empty string in 1.2.12 (15 years ago).

If you remove the URL handler for `http` and `https` in Preferences -> URL Handlers, you will get the default behavior, i.e. equivalent to `xdg-open`.

**Comment by slook** [comment]
> If the binary doesn't exist, it doesn't work.

Then should this scenario be handled by Nicotine+, for example by falling back to a popup message box with a copyable hyperlink?

**Comment by kiplingw** [comment]
Thanks @mathiascode. That fixed it for me.

**Comment by mathiascode** [comment]
> > If the binary doesn't exist, it doesn't work.
> 
> Then should this scenario be handled by Nicotine+, for example by falling back to a popup message box with a copyable hyperlink?

The error message in the status bar should be enough.
