### ISSUE TITLE
0 Shares on Profile

### ISSUE THREAD

**Issue by hydratioNx99** [nicotine-plus/nicotine-plus#2956]
Nicotine+ version:  3.3.2
Operating System/Distribution:
Windows 11 Pro

### Describe the bug
even though I have shared plenty of folders and other user can and have downloaded from me, it still show 0 Shared Files and Folders on my Profile...
But my shares do show up on "Browse Shares" and "Search Files" (not in Global though for some reason)

### Expected behavior
Show shared files and folders on my profile

### Steps to reproduce the bug
idk be me?

### Additional context
![image](https://github.com/nicotine-plus/nicotine-plus/assets/29978081/af32d7a2-610c-451c-9d4d-bd4360a943dc)
![image](https://github.com/nicotine-plus/nicotine-plus/assets/29978081/797855bf-2288-4a15-8823-3f05b1eef114)
![image](https://github.com/nicotine-plus/nicotine-plus/assets/29978081/dc78c1a2-d350-45fa-bbe7-7a94cffd26d5)

**Comment by hydratioNx99** [comment]
it crashed, I had to login again and now it works

**Comment by slook** [comment]
This issue is fixed since PR #2915 merged in 3.3.3.dev1 please try it:
https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md#windows
