### ISSUE TITLE
connection timeout 

### ISSUE THREAD

**Issue by VehementHam** [nicotine-plus/nicotine-plus#2958]
Nicotine+ version: Nicotine+ 3.3.2
Operating System/Distribution: Alpine Linux

### Describe the bug
When attempting to download from any user, I receive the error `Connection timeout` after the `Queued` status.

### Expected behavior 
The files download.

### Steps to reproduce the bug
Reproduction may not be possbile. The operating system is Alpine Linux.

### Additional context
Screenshots, logs, stacktraces or relevant information.
I have treid disabling shares. I have tried changing the port. I have checked the network.

**Comment by slook** [comment]
Does the same behaviour also occur in 3.3.3.dev1?
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by VehementHam** [comment]
Yes, I tested on that one too.
 
![image](https://github.com/nicotine-plus/nicotine-plus/assets/75701545/f017d496-0a76-494b-8f04-10e702240284)

```
./nicotine --version
Nicotine+ 3.3.3.dev2
```

**Comment by mathiascode** [comment]
Does this only happen when downloading files? Can you browse profiles and shares of users without issues?

Please enable debug logging (all categories), capture a few of these timeouts, and send the logs to the email address on my GitHub profile. https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging

**Comment by VehementHam** [comment]
Where is the log file?

**Comment by slook** [comment]
You can either just copy the text from the Log Pane or enable 'Log to file' in Preferences -> Logging.

**Comment by VehementHam** [comment]
It magically works now
