### ISSUE TITLE
1 download file at a time

### ISSUE THREAD

**Issue by Vladimir-russian** [nicotine-plus/nicotine-plus#2966]
Nicotine+ 3.3.2

When I have few thousands file, it is downloading only 1 file at a time. Is there any option where we can set the no of files it can download in parallal/at a time ?

Also if that one file is stuck in queue, nothing happens to other file e.g they are not changed from queue to downloading so I have to wait for that file or I remove that file from downloading

**Comment by rlaphoenix** [comment]
> Not more than 1 file can be transferring to each user at a time.

Is this the case even for transfers to/from private trusted buddies with all settings set to prioritize buddies/unlimited, etc? When transferring folders with a lot of small files, its quite restrictive, especially when each individual transfer is relatively slow even when unlimited.
