### ISSUE TITLE
This option is doesn't work on Nicotine+ 3.3.3 rc2

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2969]
Nicotine+ version: 3.3.3 rc2
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

This option is doesn't work on Nicotine+ 3.3.3 rc2:
![2024-04-07_18-55-29](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/e2d239a1-8abc-4677-a4ee-5835078aefba)

Columns are always opened:
![2024-04-07_18-55-35](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/6a7bfedf-19ff-4480-a6ae-4b4b7240e672)

**Comment by SnIPeRSnIPeR** [comment]
Doesn't work again on 3.3.4 rc1

**Comment by mathiascode** [comment]
Works on my end. Can you show in detail what issue you're experiencing in 3.3.4?

**Comment by SnIPeRSnIPeR** [comment]
New things appears in this sections are opened when I use option not to open it by default
![2024-05-08_00-51-28](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/4ada6b44-d6b3-4bb1-85ce-d1bbe5fb2a5f)

![2024-05-08_00-53-53](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/4a924e5f-5347-4685-9aec-4d87e87b8812)

**Comment by mathiascode** [comment]
Folder grouping mode was fixed in 3.3.3, but I didn't test user grouping mode well enough.

@SnIPeRSnIPeR Could you test 3.3.5.dev1 and verify that the issue is fixed? https://nicotine-plus.org/doc/TESTING.html

**Comment by SnIPeRSnIPeR** [comment]
> Folder grouping mode was fixed in 3.3.3, but I didn't test user grouping mode well enough.
> 
> @SnIPeRSnIPeR Could you test 3.3.5.dev1 and verify that the issue is fixed? https://nicotine-plus.org/doc/TESTING.html

Works fine on 3.3.5 dev1
