### ISSUE TITLE
right-clicking file that user 2 downloads points to user 1

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#297]
I sometimes check if people really share a nice collection or just a few dirs. So today two guys were downloading something. I right-clicked the username and checked his collection. After that I right-clicked on a file the second guy was downloading and in the menu I saw the name of Mr. 1. I had to click the username and then I got the right user.

**Comment by mathiascode** [comment]
The general issue is that items aren't selected automatically when right-clicking them, right?

**Comment by hboetes** [comment]
Yes, that's an accurate description of what I encountered. You have to left click something first before right clicking it.

**Comment by mathiascode** [comment]
Can you test this branch?
`git clone -b selection https://github.com/mathiascode/nicotine-plus`

**Comment by hboetes** [comment]
I'm testing the branch, how would you describe the change? I'm not sure what I should notice.

**Comment by mathiascode** [comment]
The behavior is modified in the search view, download list and upload list. If you right-click a row, it is now selected, and the popup menu appears. You can still select multiple rows by selecting an initial row, holding down shift, and selecting another one. If you then right-click a new row outside the selected ones, the previous rows will be unselected, and the new row will be selected instead.

**Comment by mathiascode** [comment]
Make sure that these changes are in your local copy: https://github.com/mathiascode/nicotine-plus/commit/a2b20623bd9acf52e01ff9173d6f4c850f07a0bb

**Comment by hboetes** [comment]
Oh my, for some reason the branch did not get installed. Now it's working. Yes, much better! Thanks!

**Comment by mathiascode** [comment]
Sweet, thanks for confirming!
