### ISSUE TITLE
Nicotine+ 3.3.0 and newer do not start on Windows 10

### ISSUE THREAD

**Issue by sbstn87** [nicotine-plus/nicotine-plus#2972]
Nicotine+ version:  3.3.0, 3.3.1 and 3.3.2
Operating System/Distribution: Windows 10

### Describe the bug
Nicotine does not start, attached screenshots of error messages. Nicotine+ 3.2.9 works fine.
![2024-04-10_18-58](https://github.com/nicotine-plus/nicotine-plus/assets/37237675/5ae36df9-8057-4866-82f2-41127ab69a40)

![2024-04-10_18-56](https://github.com/nicotine-plus/nicotine-plus/assets/37237675/f0b22aa4-c04d-44a7-b204-8281f27cd714)

![2024-04-10_18-56_1](https://github.com/nicotine-plus/nicotine-plus/assets/37237675/e16cc843-0f6c-4da4-89a4-eaedd1a1cb55)

**Comment by slook** [comment]
Is it still a problem in 3.3.3rc2 ? https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

**Comment by sbstn87** [comment]
Yes, I get exactly the same error messages.

**Comment by mathiascode** [comment]
Could you
- try the standalone executable download of Nicotine+ (below the installer link on the download page)?
- ensure that an old, pre-3.2.0 installation of Nicotine+ isn't present on your system? It would show up as a duplicate entry in Control Panel -> Programs -> Programs and Features.

**Comment by sbstn87** [comment]
Ok, so the standalone executable works fine with Nicotine+ 3.2.9 installed.

I uninstalled Nicotine+ 3.2.9, and the standalone version still worked fine with my old settings. 

I then tried installing 3.3.2 and 3.3.3 versions, but they both don't work - the same error appears when trying to launch them.

There are no duplicates in the program list,

**Comment by mathiascode** [comment]
Can you uninstall Nicotine+ completely, and verify that no old files remain in `C:\Program Files\Nicotine+`?

**Comment by sbstn87** [comment]
After uninstalling Nicotine+ 3.2.9 there was a bunch of .dll files left in the install folder. I have deleted them manually and installed Nicotine 3.3.3RC2 as suggested - now everything works fine for me.

Thank you.

**Comment by mathiascode** [comment]
Good to hear that solved the issue. I suspect those were pre-3.2.0 files that the old uninstaller failed to remove for some reason. Not much we can do about it in any case.
