### ISSUE TITLE
Can you update Russian translation for the future Nicotine 3.3.3

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2975]
Can you update Russian translation for the future Nicotine 3.3.3?

https://hosted.weblate.org/projects/nicotine-plus/nicotine-plus/ru/

Thanks.

**Comment by mathiascode** [comment]
Done in 0f01949f6e348554b63ddf5730f8ff38ba52bb6e
