### ISSUE TITLE
Num lock state is inverted

### ISSUE THREAD

**Issue by DarkVoyage** [nicotine-plus/nicotine-plus#2977]
Nicotine+ version:  3.3.3rc2
Operating System/Distribution: Windows 11 x64

If you need to enter special character with Alt+0000, it works with Num Lock OFF instead of commonly ON.
N+ understands Alt with numpad arrow keys as moving between tabs when Num Lock ON.
At same time numpad works correctly without Alt: ON for numbers, OFF for arrows and functions.

**Comment by mathiascode** [comment]
I wonder how we should handle this. Maybe we could disable Alt+1-9 shortcuts for tab switching while num lock is enabled on Windows?
