### ISSUE TITLE
Allow N+ To SKIP Files Identified As NOT SHARED And Continue With Other Files Queued

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2984]
### Describe the solution you'd like
As it is now, when N+ encounters a file identified as FILE NOT SHARED, ALL downloads from that user STOP.  The program _should_ just SKIP any such files (or ANY "error") and move on to the next queued files from the user.

### Additional context
N/A

**Comment by mathiascode** [comment]
It's the uploader's responsibility to initiate upload attempts, we don't control that when downloading files. Perhaps this is the same issue as https://groups.google.com/g/soulseek-discussion/c/wUB0-AqfIhs in SoulseekQt?
