### ISSUE TITLE
Private Chat tab does not get notified on receiving a message

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#299]
Someone sent me a PM and I noticed only much later because the Private Chat tab didn't get a notification message. So no blue bird on the Private chat tab.

**Comment by mathiascode** [comment]
Can you reproduce this, or did it only happen once? A light bulb icon should appear on the private chat tab if you get a new message.

**Comment by hboetes** [comment]
It happened multiple times. I'll send you my username via the mail, so we can test it.

The lightbulb appeared on the user tab in private chat, but not on the private chat tab

**Comment by mathiascode** [comment]
I tested sending messages with three different clients, and I consistently got a notification icon on the tab.

**Comment by zniavre** [comment]
same here on individual tabsit's ok but the "private chat" tab did not

**Comment by hboetes** [comment]
Well that's odd. This time it worked. Next time I'll pay close attention to the circumstances and ask the messenger for details.

Please don't close this bug yet.

**Comment by zniavre** [comment]
i guess if nic+ is focused it works but if you leave it in background it does not

**Comment by hboetes** [comment]
@zniavre I couldn't reproduce that. Are you running the latest git version?

**Comment by hboetes** [comment]
The leech plugin does send a message, I can understand this does not trigger a notice in the private chat tab, it would be nice though.

I recall clicking on the private chat tab, noticing a message was sent to a user not sharing files, the user replied saying he was rescanning. Both events did not trigger a notice on the private chat tab.
If someone is willing to try to reproduce this problem, please find me in the nicotine-dev channel.

**Comment by mathiascode** [comment]
There's no special filtering for leech messages though, it's just a normal message that is supposed to trigger a notification as usual.

**Comment by hboetes** [comment]
I just had someone who didn't share who replied to the auto-message and I got notified of that. Closing.
