### ISSUE TITLE
Can you incorporate the autoban feature into the Leech Detector from this other (abandoned) Leech plugin?

### ISSUE THREAD

**Issue by Tenome** [nicotine-plus/nicotine-plus#2993]
https://github.com/thisisbbc/nicotine-plus-leech-nomore

This fork of the Leech plugin has a feature to autoban anyone who isn't sharing any music at all who tries to leech, but it's no longer in development. Can that be incorporated here? As it stands, I have to go through all the leechers who got PM'd and see who still hasn't shared any music so they don't try to download my entire library again.

**Comment by mathiascode** [comment]
Sorry, I can't accept this into the client officially. It's not supported by the original Soulseek client, and the feature is controversial. You can fork the current leech detector plugin, add the required changes, and use it as a third-party plugin.
