### ISSUE TITLE
Ability to see user's client & version in PROFILE

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2995]
### Describe the solution you'd like
It would be VERY helpful to know what client & version a user is using - that way we can also communicate all the new features of N+! :-)

### Additional context
N/A

**Comment by mathiascode** [comment]
It's only possible to know the client and version of Nicotine+ users, when running the `/ctcpversion` command in a private chat with them. The Soulseek protocol doesn't have a way to request a client's name or version.
