### ISSUE TITLE
Scrolling performance suddenly abysmal (again)

### ISSUE THREAD

**Issue by matterharz** [nicotine-plus/nicotine-plus#3000]
Nicotine+ version: 3.3.3
Operating System/Distribution: Windows 10

### Describe the bug
Scrolling performance when browsing search results, user files, downloads, uploads is horrible, maybe 2-3 fps. Was excellent in v3.3.2. Settings/Preferences seems only slightly worse, still tolerable. Launching/quitting seems a bit faster than before (?).
Seems like this bug/regression is back on the menu: https://github.com/nicotine-plus/nicotine-plus/issues/2150 (I didn't comment back then but I observed it, too.)

### Expected behavior
--

### Steps to reproduce the bug
--

### Additional context
--

**Comment by SnIPeRSnIPeR** [comment]
Hey, I have the same problem on 3.3.3 (final) right now. Scrolling FPS is so slow when I use vertical scrolling...

**Comment by mathiascode** [comment]
https://nicotine-plus.org/doc/TESTING.html#windows

Can you check if it's fixed there?

**Comment by SnIPeRSnIPeR** [comment]
> https://nicotine-plus.org/doc/TESTING.html#windows
> 
> Can you check if it's fixed there?

Ok, will check later today

**Comment by mathiascode** [comment]
Fixed on my end. Let me know if you're still experiencing the issue.

**Comment by matterharz** [comment]
Works fine. Thanks!

**Comment by SnIPeRSnIPeR** [comment]
> Works fine. Thanks!

Me too on 3.3.4 rc1
