### ISSUE TITLE
Sometimes, Nicotine+ (3.3.3) window doesn't open on top when other windows already opened full screen on the desktop.

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#3002]
Nicotine+ version: 3.3.4 rc1
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

Nicotine+ window doesn't open on top when other windows already opened full screen on the desktop. Under Chrome or other programs, like Total Commander.

**Comment by mathiascode** [comment]
Did this happen in 3.3.2? Can you check if it happens in 3.3.4rc1?

**Comment by SnIPeRSnIPeR** [comment]
Just checked on 3.3.4 rc1. Problem is still here. If I minimize the program by clicking on the taskbar, then by clicking in the tray the program opens under all other opened windows in full screen. You can expand Nicotine+ only by clicking on the taskbar or minimizing all currently open windows. Why after 3.2.9 the program is so buggy?

**Comment by mathiascode** [comment]
> Why after 3.2.9 the program is so buggy?

Because it was ported from GTK 3 to GTK 4, which resulted in a few regressions (and improvements), and Windows support was never a priority.

**Comment by SnIPeRSnIPeR** [comment]
> > Why after 3.2.9 the program is so buggy?
> 
> Because it was ported from GTK 3 to GTK 4, which resulted in a few regressions (and improvements), and Windows support was never a priority.

What percentage of users uses Windows version of Nicotine+?

**Comment by mathiascode** [comment]
> > > Why after 3.2.9 the program is so buggy?
> 
> > 
> 
> > Because it was ported from GTK 3 to GTK 4, which resulted in a few regressions (and improvements), and Windows support was never a priority.
> 
> 
> 
> What percentage of users uses Windows version of Nicotine+?

I don't know, but I know it's unfortunately too large. I don't use Windows myself except for testing Nicotine+ occasionally, and I'm tired of that operating system and its issues.

**Comment by mathiascode** [comment]
Anyway, let me know if this issue is fixed in 3.3.4 or not.

**Comment by SnIPeRSnIPeR** [comment]
Ok. Will do.

Also, I found a new problem with Nicotine enviroment (3.3.4 rc1). If you open this list or other, you can't collapse it by clicking in this place how I can do in all other Windows programs:
![2024-05-08_00-56-11](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/4e2964e4-b4e6-45fe-be9d-3010ed0454d2)

**Comment by mathiascode** [comment]
> Nicotine+ should collapse to the tray when a user clicking icon in task bar.

This isn't default behavior in qBittorrent. Seems to be optional (Options -> Behavior > Minimize qBittorrent to notification area).
