### ISSUE TITLE
Nicotine won't connect

### ISSUE THREAD

**Issue by ralphydobbs** [nicotine-plus/nicotine-plus#3007]
Nicotine+ version:  3.3.4
Operating System/Distribution: Windows 11 64bit

### Additional context
Screenshots, logs, stacktraces or relevant information: I think all was covered in expected behavior.

**Comment by ralphydobbs** [comment]
Soulseek also appears down, is this related?

**Comment by mathiascode** [comment]
> Soulseek also appears down, is this related?

Yes, if https://slsknet.org is down, you can't connect using Nicotine+ either.

Some Australian ISP blocked Soulseek the other day, but other than that, there aren't any known issues.

**Comment by ralphydobbs** [comment]
Thanks! In trying to fix the issue, I saw that I need to ensure my ports are forwarded, whatever that means. I discovered in the process that perhaps it is my router that is failing. Although it allows me access to the internet, I don't have the option to open a port so I have a tech coming out to repair. Hopefully, I can close this issue today. I certainly never expected the router to be my problem with the internet working.

**Comment by ralphydobbs** [comment]
Thanks all! The problem indeed turned out to be my router wasn't apparently configured correctly. Why I was able to use Soulseek and Nicotine + previously, I'm not sure, but once my router was correctly configured to port forward to my desktop, everything works great again.
