### ISSUE TITLE
Autoclear finished/filtered downloads from transfer list option doesn't work

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#3009]
Nicotine+ version: 3.3.4 and 3.3.5 dev1
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

Autoclear finished/filtered downloads from transfer list option doesn't work:
![2024-05-11_20-51-26](https://github.com/nicotine-plus/nicotine-plus/assets/31162059/db106eb6-3da7-4d9b-9fb2-5999a9616e94)

**Comment by mathiascode** [comment]
Was the option enabled before, or did you just enable it? It only applies to downloads that finished after the option was enabled (but maybe it should also clear the previous list then toggled, not sure).

You screenshot also shows the uploads tab, not downloads.

**Comment by SnIPeRSnIPeR** [comment]
> Was the option enabled before, or did you just enable it? It only applies to downloads that finished after the option was enabled (but maybe it should also clear the previous list then toggled, not sure).
> 
> You screenshot also shows the uploads tab, not downloads.

My bad. That's "downloads" tab in settings, not uploads :)
