### ISSUE TITLE
unable to download to created folder

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#301]
1.4.3-20200615224 / KDE neon (Ubuntu 18.04 LTS)

search result → download containing folder(s) to… → create folder → unable to press „open” (greyed out)

![image](https://user-images.githubusercontent.com/3148302/84771389-a210de80-afd9-11ea-9ebd-9366c20dd329.png)

**Comment by mathiascode** [comment]
Huh, looks like the whole feature is broken. Investigating...
