### ISSUE TITLE
Nicotine+ refuses to start after installing latest version; "bad magic number"

### ISSUE THREAD

**Issue by Setup2134** [nicotine-plus/nicotine-plus#3010]
Nicotine+ version:  3.3.4
Operating System/Distribution: Windows 10

### Describe the bug
Installing the latest version of Nicotine+ causes a python traceback error to appear relating to a "bad magic number"

### Expected behavior
Nicotine+ successfully installs and starts up

### Steps to reproduce the bug
Install Nicotine+ 3.3.4 with the .msi installer

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://github.com/nicotine-plus/nicotine-plus/assets/138363522/f24c1637-6665-46e5-bcfe-ecbbbaf08da5)

**Comment by mathiascode** [comment]
Can you uninstall Nicotine+, ensure there are no files remaining in `C:\Program Files\Nicotine+`, and reinstall Nicotine+?
