### ISSUE TITLE
Add timestamp columns to Uploads and Downloads views

### ISSUE THREAD

**Issue by dakka** [nicotine-plus/nicotine-plus#3013]
### For both Uploads and Downloads views add timestamp *started*, another timestamp for *last data received*

This will allow user to 
- see when an upload or download was started (not possible atm)
- without looking at the calculated rates and elapsed times, get a wall clock idea of speeds

**Comment by slook** [comment]
Closing in favour of duplicate #2171 please add your comments in support of that issue and join in with the discussion therein.
