### ISSUE TITLE
Cant connect to server?

### ISSUE THREAD

**Issue by WesCurry** [nicotine-plus/nicotine-plus#3015]
Nicotine+ version:  3.3.4
Operating System/Distribution: 

### Describe the bug
I cant get online on Nicotine+, is it down at the moment?

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment]
No, the server is up. There must be a problem at your end.

**Comment by mathiascode** [comment]
The server was down earlier today: https://www.reddit.com/r/Soulseek/comments/1cvm7pd/soulseek_down/
