### ISSUE TITLE
Crash on Mac OS Monterey 12.7.5 (Intel) - Nicotine+ Version: 3.3.5.dev1

### ISSUE THREAD

**Issue by iioniis** [nicotine-plus/nicotine-plus#3016]
Nicotine+ Version: 3.3.5.dev1
GTK Version: 4.14.4
Python Version: 3.12.3 (darwin)

Type: <class 'OSError'>
Value: [Errno 22] Invalid argument
Traceback:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 886, in _raise_exception
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2732, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2497, in _process_ready_sockets
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2400, in _process_ready_input_socket
Operating System/Distribution:

I wasn't active at the computer when it happened.  I just came back to this report.

**Comment by slook** [comment]
Regression since https://github.com/nicotine-plus/nicotine-plus/commit/e181f50e785ce3f8bec9eff2eb2932426b910c6e

https://github.com/nicotine-plus/nicotine-plus/blob/77bc46da957b1dc8caa50f0edfa24c9b57632f84/pynicotine/slskproto.py#L2400

**Comment by mathiascode** [comment]
Maybe an incoming connection died while accepting it? Are you able to perform file searches without issues?

**Comment by iioniis** [comment]
> Maybe an incoming connection died while accepting it? Are you able to perform file searches without issues?

mathiascode, yes I am.  Search seams to work fine.  It's only happened when I'm not actively using it and uploads are going.  Uploads are usually happening anyway and it doesn't crash all the time.

**Comment by slook** [comment]
It is bizarre that this argument is available on the system (otherwise the program wouldn't even be able to start), yet for some reason it went away in the middle of a session. I suppose the interface could have gone down for sleep or something like that.

**Comment by mathiascode** [comment]
I'll have to verify how macOS behaves myself, but the fix will most likely be to move the setsockopt calls inside the try block.

**Comment by mathiascode** [comment]
I haven't been able to reproduce this issue on macOS. All incoming connections are working fine.

I don't know what the exact issue is, but it's an edge case. I'll catch the exception and remove such connections.
