### ISSUE TITLE
Crash on load, Nicotine+ 3.3.4 mingw x86_64 (Fixed)

### ISSUE THREAD

**Issue by Climbatiz** [nicotine-plus/nicotine-plus#3017]
Nicotine+ version:  3.3.4-mingw_x86_64
Operating System/Distribution: Windows 10 Home

### Describe the bug
was upgrading from 3.2.9, used the standard installer and when i try to load the application i crash immedietly with this error:
![Untitled](https://github.com/nicotine-plus/nicotine-plus/assets/39280509/6cd89368-87da-4fda-a86b-6e967ef11571)

**Comment by Climbatiz** [comment]
seems i ran into that old version bug, still i was upgrading from 2.2.9

**Comment by mathiascode** [comment]
Looks like https://github.com/nicotine-plus/nicotine-plus/issues/3010. Try reinstalling and see if that fixes the issue.

**Comment by Climbatiz** [comment]
yeahl removing old version fixed it, installation was fine, however i am running into known bug about program exiting fullscreen on open

**Comment by slook** [comment]
Which known bug... do you have an issue number?

Does the problem prevent the application window from being visible whatsoever, or is it only the size not being correctly remembered upon launch?

**Comment by Climbatiz** [comment]
oh i thought  i had read in change/release notes about such a bug having been fixed, but anyway, when i load app and the screen is maximized and then minimize to tray, when i open the app again it isn't maximized anymore even though it says it is

**Comment by mathiascode** [comment]
> oh i thought i had read in change/release notes about such a bug having been fixed, but anyway, when i load app and the screen is maximized and then minimize to tray, when i open the app again it isn't maximized anymore even though it says it is

I think I've seen this one occasionally before. Could you open a new bug report with a screenshot?

I'll close this issue, since it's resolved.
