### ISSUE TITLE
"Ok" on Network Closes Port

### ISSUE THREAD

**Issue by LennyPhoenix** [nicotine-plus/nicotine-plus#3020]
Nicotine+ version:  Nicotine+ 3.3.4
Operating System/Distribution: Arch (Bedrock) Linux

### Describe the bug

Pressing "ok" at any time in the network page of preferences will close the listening port, even if the port field was not adjusted. I consider this a bug, as it is not intuitive and led to some confusion with the port closing seemingly randomly.

### Expected behavior

Port to only be closed when the listening port field is changed. (Or not at all, surely this should only take effect on restart?)

### Steps to reproduce the bug

- Ensure port is open
- Open network tab of preferences
- Press "Ok" to close the network tab
- Refresh port checker, port is now closed

### Additional context

I am using UPnP

**Comment by mathiascode** [comment]
Thanks for reporting. The intention was to only remove the port mapping when disabling UPnP, but the code wasn't strict enough.
