### ISSUE TITLE
Python Memory Error

### ISSUE THREAD

**Issue by Rik93** [nicotine-plus/nicotine-plus#3022]
Nicotine+ version:  3.3.4
Operating System/Distribution: Windows 11 Pro 23H2

### Describe the bug
When I leave Nicotine+ open for a few hours, I get the following error pop-up.

### Expected behavior
I expected to Nic+ to stay minimized and running in the background.
But then after a hour I get the following error message.

### Steps to reproduce the bug
Just opening Nic+ and leave it running for a few hours I get the message again.

### Additional context
Screenshots, logs, stacktraces or relevant information.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/vkHLVB9/Screenshot-2024-06-01-232458.png" alt="Screenshot-2024-06-01-232458" border="0"></a>

Nicotine+ Version: 3.3.4
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'MemoryError'>
Value: 
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 884, in _raise_exception
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2725, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2492, in _process_ready_sockets
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2433, in _process_ready_input_socket
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2606, in _read_data

**Comment by mathiascode** [comment]
A MemoryError happens when the program runs out of memory. What does the memory usage of Nicotine+ and the rest of the OS look like?

**Comment by Rik93** [comment]
> A MemoryError happens when the program runs out of memory. What does the memory usage of Nicotine+ and the rest of the OS look like?

Well my Virtual Memory was indeed very high, before Nic+ crashed.
What can I do to prevent these errors?

And I'll try to reproduce the error, and I'll show you the memory usage of my computer.

**Comment by slook** [comment]
> Well my Virtual Memory was indeed very high, before Nic+ crashed.

It would be interesting to know what proportion of memory was used by N+ verses other applications, and also if N+ memory consumption was exceptionally large such as many Gigabytes?

**Comment by Rik93** [comment]
I have it running for a few hours now, nowhere as long as the erroneous one, but trying to recreate the error.
I don't have other data than the one in the OP, unfortunately.
So when I get the same error again, I will let you guys know.

**Comment by slook** [comment]
Thanks, also it would be useful if you could try to see roughly how many connections are active at the time of the crash, and if they were mainly from uploads, downloads or other peer activity such as responding to search queries or chats.

You can use the [log pane](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEVELOPING.md#debug-logging) to view in more detail what the client is doing.

**Comment by Rik93** [comment]
Got the error reproduced.
I was searching an album, just one search query open.
It used/hogged up all my Virtual Memory, up to at least 16Gb of it.
My virtual memory is system organized, and has a total of 71,9Gb, so at least 25% was used by Nicotine+ before it crashed.
It also crashed my screen, in the way of giving me a black screen for a few seconds, and then back to usual, and all the virtual memory was free right after the crash.

For the amount of connections, there were 3, and no up/download traffic as seen in the lower right of the screen.

Can I do something, say increasing my virtual memory manual (although I think 72 Gb is already a lot)?
Or is there something else I can do?

**Comment by slook** [comment]
Did it crash in the same place (line 2606, in _read_data) or was the stack trace in the Critical Error message slightly different?

Increasing your virtual memory won't help, something is going bezerk and getting stuck in a loop.

**Comment by Rik93** [comment]
> Increasing your virtual memory won't help, something is going bezerk and getting stuck in a loop.
> 
> Did it crash in the same place (line 2606, in _read_data) or was the stack trace in the Critical Error message slightly different?

As far as I know it crashed at the same place.
I cannot recall it 100% because I already closed Nic+ and restarted the application.

**Comment by mathiascode** [comment]
I've looked at the code, but I'm struggling to find anything that could possibly eat 16 GB of memory. We clear the incoming/outgoing buffer when closing connections.

@Rik93 How many files are you sharing? How large are your download/upload lists? Any wishlist searches?

Could you try the following?

- Disconnect from the server (Menu -> Disconnect), and leave it disconnected for a while. Does memory usage change?
- Try a fresh config, where you only log in and do nothing else (back up/rename the `C:\Users\USERNAME\AppData\Roaming\nicotine` folder).

**Comment by Rik93** [comment]
@mathiascode, Thanks for looking at my problem.
But I cannot try anything of that sort because when my Nicotine+ crashes, I only can shut it down, nothing is possible then.
I already don't use it anymore on Windows, but on docker on my NAS (unRAID, docker).
And that is working flawlessly, so in fact, I totally abandoned N+ on Windows, too bad but I had to look at other possibilities.

Thanks again.

Kind regards,
Rik93

**Comment by mathiascode** [comment]
If you're still able to run Nicotine+ on Windows, you could do the steps at startup, before Nicotine+ starts running out of memory. I'm mainly curious what specific part of the application is causing the issues.

**Comment by Rik93** [comment]
@mathiascode maybe I will look at it on Windows again, has it to be running on the same PC, preferrably?
Or can I also try a fresh install on my laptop?

**Comment by mathiascode** [comment]
Preferably on the same PC that had the issue, but you could see if the issue happens on your laptop too.

**Comment by DarkVoyage** [comment]
I can give you a good heavy load picture.
Windows 11
N+ 3.3.5dev1
RAM 64GB
Working set: 1.7GB
Private bytes: 1.3GB
Share is over 30TB
Connections 30-50 all the time (not only uploads, but search replies)

Of course it may be hardware based problem, but generally N+ feels great during heavy load and multiple dl/ul jobs. RAM is more than normal. qBt eats much more GBs for torrents. SoulseekQt would be useless under such load.
