### ISSUE TITLE
Manually "lock" specific queued downloads from being accidentally cleared

### ISSUE THREAD

**Issue by metaisfacil** [nicotine-plus/nicotine-plus#3025]
### Describe the solution you'd like
I have queued downloads from a number of users who are rarely on, or only appear for short periods before logging back off. I'd like a way to "lock" or "freeze" queued downloads (per-user or per-folder/file, either is fine) so they can't be cleared from the queue by an accidental mispress of the "Delete" key or etc.

To be clear, I'm aware I can re-queue files from offline users using saved shares - I already do that - but I don't always remember exactly what I had queued, or in what order.

### Additional context
N/A

**Comment by slook** [comment]
> accidental mispress of the "Delete" key

Perhaps it might be helpful if the `<Shift>` modifier key was required for this shortcut.

**Comment by mathiascode** [comment]
Closing in favor of #2922.
