### ISSUE TITLE
Libadwaita theme not applying

### ISSUE THREAD

**Issue by nathanielevan** [nicotine-plus/nicotine-plus#3035]
Nicotine+ version: Latest master
Operating System/Distribution: Arch Linux

### Describe the bug
As described on title -- nicotine lists libadwaita as its [dependency](https://nicotine-plus.org/doc/DEPENDENCIES.html) but my libadwaita theme doesn't seem to be applied. It works on other libadwaita apps though.

### Expected behavior
The libadwaita theme applies and the customised colours are displayed

**Comment by mathiascode** [comment]
Are you using GNOME Shell? The libadwaita theme only applies there by default, otherwise you have to start Nicotine+ with the `NICOTINE_LIBADWAITA=1` environment variable.

**Comment by nathanielevan** [comment]
Ah no, thanks for telling me about the environment variable! Is this documented in the docs somewhere? Anyway, using the `NICOTINE_LIBADWAITA` environment variable does do the job, thank you!

**Comment by nathanielevan** [comment]
Closing this issue -- in hindsight I should've asked in Discussions first before opening an issue. Sorry!

**Comment by nathanielevan** [comment]
Closing this issue -- in hindsight I should've asked in Discussions first before opening an issue. Sorry!

**Comment by mathiascode** [comment]
It's not documented currently, not sure where it would fit. Maybe the man page?

**Comment by nathanielevan** [comment]
That works, yeah. I think environment variables specific to Nicotine+ can fit in the man page
