### ISSUE TITLE
nowplaying - other should decode bytes

### ISSUE THREAD

**Issue by mayli** [nicotine-plus/nicotine-plus#3039]
Nicotine+ version:  latest
Operating System/Distribution:

### Describe the bug
nowplaying is returning b'xxxxx' when after executing external commands

### Expected behavior
show output without the `b''`

### Steps to reproduce the bug
use custom command in the nowplaying settings, click test

### Additional context
Screenshots, logs, stacktraces or relevant information.

https://github.com/nicotine-plus/nicotine-plus/blob/master/pynicotine/utils.py#L476
Is returing bytes by default, we need to add a `.decode('utf-8')` there.

**Comment by slook** [comment]
Please create a PR (pull request) with the exact edit of the code required to fix the issue.
