### ISSUE TITLE
Newly started downloads will open a collapsed thread?

### ISSUE THREAD

**Issue by Climbatiz** [nicotine-plus/nicotine-plus#3044]
Nicotine+ version:  3.3.4
Operating System/Distribution: Windows 10 Home

### Describe the bug
This didn't happen in earlier versions, but in latest if you uncollapse a download and the person downloads a new file it'll open that window/download again that you have collapsed, this is especially irritating when you collapse a user and he is opening new downloads all the time cuz he fails a download and his client queues another file, like i said this didn't happen in earlier versions of Nicotine

**Comment by mathiascode** [comment]
Should be fixed now. Please try the [development build](https://nicotine-plus.org/doc/TESTING.html#windows) to verify that it works as expected.
