### ISSUE TITLE
Crash on MBP Ventura 13.6.7

### ISSUE THREAD

**Issue by winy98** [nicotine-plus/nicotine-plus#3045]
Nicotine+ version:  
Operating System/Distribution: Macos Ventura 13.6.7 (MBP 2017)

### Describe the bug
The app crashes when I try to search anything.

**Comment by mathiascode** [comment]
Any error message or crash report?

**Comment by mathiascode** [comment]
Is your system region set to Spain? It might be the same issue as https://github.com/nicotine-plus/nicotine-plus/commit/a704546980d2fc8bcf261de9da4f47846a2c3eb4.

Please try the [development version](https://nicotine-plus.org/doc/TESTING.html#macos) and see if it fixes the issue.

**Comment by mathiascode** [comment]
I'm assuming it's the same issue that commit fixed. If Nicotine+ is still crashing, feel free to reopen the issue.
