### ISSUE TITLE
twice downloaded same folder, aborted duplicate files, remove aborted does not remove

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#305]
And then you just try things for the fun of it.

So I downloaded a whole folder from a user, downloaded it again, check the downloads list and noticed those duplicate entries have the same download id. Selected the duplicate ones and aborted them. Hit remove duplicate/aborted and...

They're still there.

What I'd hope for is that the duplicate tracks would not have been added to the download list at all.

**Comment by mathiascode** [comment]
No bugs allowed. :P

**Comment by hboetes** [comment]
Thanks! Amazing!
