### ISSUE TITLE
Sorting order of files is broken because of characters not in current codepage

### ISSUE THREAD

**Issue by DarkVoyage** [nicotine-plus/nicotine-plus#3052]
Everything is obvious here

![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/7424bb61-dcf4-44dd-b929-7c43e427444e)

![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/ee779765-eb4b-4b88-9a48-a8550940147a)

Same thing happens in wishlist. If string contains any special characters (umlauts), it goes to the end of the wishlist after "Z".
Sometimes it is good to find out that there's are zero spaces in title. Also a recommendation - make filter of forbidden characters in wishlist and in other places. Would be very grateful if you add zero-width space indication that will notify, if it is found in any of shared files. It brings a lot of troubles and it doesn't filter easily and goes to filenames, folder names, to the internet - like a plague... Zero-width space and other null length invisible characters should be forbidden from use.

**Comment by mathiascode** [comment]
What's your system locale set to?

**Comment by DarkVoyage** [comment]
Russia.

**Comment by mathiascode** [comment]
I haven't been able to reproduce the issue. Can you check if the latest [development build](https://nicotine-plus.org/doc/TESTING.html#windows) is any different?

What's also strange in the screenshot is the direction the arrow is pointing in. It should be pointing down when files are sorted 0-9, not up. What does sorting look like when no numbers are included in the file names?

Could you also send a screenshot of the settings in Windows Settings -> Time & language -> Language & region?

**Comment by DarkVoyage** [comment]
> Can you check if the latest [development build](https://nicotine-plus.org/doc/TESTING.html#windows) is any different?

No change.



> It should be pointing down when files are sorted 0-9, not up.

I've checked several apps with list view - arrow up is always forward order. It is not really arrow, but sign "from least to most".


![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/0bbaee6c-4927-437d-9a95-e2911966ab09)
![image](https://github.com/nicotine-plus/nicotine-plus/assets/31579340/8f860015-8b52-462c-a409-6c89762c8622)

**Comment by DarkVoyage** [comment]
> I haven't been able to reproduce the issue.

I've tried to use some other symbols and found out that none of them are possible to be printed.
Does Nicotine support UTF?

**Comment by DarkVoyage** [comment]
This build crashes a lot. Now right after launch.

`Nicotine+ Version: 3.3.5.dev1
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'name'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 979, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 295, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 251, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/downloads.py", line 912, in _user_status
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/downloads.py", line 301, in _enqueue_transfer
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/downloads.py", line 449, in _finish_transfer`

**Comment by slook** [comment]
Are you sure that was the only traceback from the crash, perhaps another Critical Error dialog was hidden behind the one you posted above?

**Comment by DarkVoyage** [comment]
I don't know. Just copied from crash dialog on front. I've downgraded to stable, because it was impossible to work further, it just crashed after connection to server on launch many times.

**Comment by slook** [comment]
Was your Downloads history list also corrupted?

**Comment by mathiascode** [comment]
> I've checked several apps with list view - arrow up is always forward order. It is not really arrow, but sign "from least to most".

It's a little confusing, I think there was some GTK issue about the direction being wrong compared to other apps. I'll see if I can find it again.

> ![image](https://private-user-images.githubusercontent.com/31579340/346319363-8f860015-8b52-462c-a409-6c89762c8622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTkwNzQsIm5iZiI6MTcyMDQ1ODc3NCwicGF0aCI6Ii8zMTU3OTM0MC8zNDYzMTkzNjMtOGY4NjAwMTUtOGI1Mi00NjJjLWE0MDktNmM4OTc2MmM4NjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE3MTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNGU4NjI3NWQ0YWY0OTUxYmYxYzMzNjBiMGQ1YmZjZDY1N2U2ZDVhMjFmZDFhM2ExYTMwZTAzZWNjMzMzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7KCK_KTNtMiJBc2Lf_3Mbyr-FW1CGlXZlMO4SgsiBhI)

Does "Beta: Use Unicode UTF-8 for worldwide language support" change anything in this case? Maybe we could just force UTF-8 in Nicotine+ itself regardless...

The crash should be fixed in the latest development build in a few minutes.

**Comment by DarkVoyage** [comment]
I need to upgrade to 3.3.5, because some problems that were resolved - returned... Thanks for update.



> Does "Beta: Use Unicode UTF-8 for worldwide language support" change anything in this case?

I don't want to turn this on, because it breaks interface of some old tools that don't support UTF8. I really don't know how they planned to force UTF support for apps that can't even work with UTF8 path.

**Comment by mathiascode** [comment]
Should be fixed in the latest development build. Can you confirm?

**Comment by DarkVoyage** [comment]
Yes, fixed everywhere! You're great!
