### ISSUE TITLE
"Add..." button in Shares section does not work

### ISSUE THREAD

**Issue by mvster1** [nicotine-plus/nicotine-plus#3055]
Nicotine+ version:  3.3.4
Operating System/Distribution: Fedora 40

### Describe the bug
"Add..." button in Shares section doesn't do anything
https://github.com/nicotine-plus/nicotine-plus/assets/146800336/432dda6e-87b6-434c-8c0c-2794f31f29e2

### Expected behavior
"Add..." button should open a file manager window for selecting the folders for sharing

### Steps to reproduce the bug
Settings > Shares > Add...

### Additional context
Clicking on the button does absolutely nothing, launching the application from the command line returns no error message relating to the problem

**Comment by slook** [comment]
GTK should spawn a dialog box titled "Add a Shared Folder", perhaps it appeared behind the main window?

Are any other dialogs in Nicotine+ also affected?

Please report your GTK version as displayed in the "About Nicotine+" dialog (that is, if it can be opened!) from the Help menu.

**Comment by mathiascode** [comment]
Which edition of Fedora 40 are you using? Which desktop environment?

**Comment by mathiascode** [comment]
If you're using a custom setup, my guess is that you're missing some portal-related packages used by the file chooser nowadays. Try installing `xdg-desktop-portal-gtk`.

**Comment by mvster1** [comment]
> Which edition of Fedora 40 are you using? Which desktop environment?

Fedora 40 Server + bspwm, very minimal installation indeed.

> Try installing `xdg-desktop-portal-gtk`.

I have that package installed.

> Are any other dialogs in Nicotine+ also affected?

Appears to be just this one. Everything else relating to opening file manager works normally e.g. "Show in folder", etc.

> Please report your GTK version as displayed in the "About Nicotine+" dialog (that is, if it can be opened!) from the Help menu.
Dialog opens normally. Version shows GTK 4.14.4

**Comment by mathiascode** [comment]
Any difference if you start Nicotine+ with `GDK_DEBUG=no-portals`?

**Comment by mvster1** [comment]
Launching it with `GDK_DEBUG=no-portals` seems to have worked. `xdg-desktop-portal` is running and I have `xdg-desktop-portal-gtk` installed but not running and I can't start it from terminal. I guess this issue is partly fixed now?

**Comment by mathiascode** [comment]
Finding out why `xdg-desktop-portal-gtk` crashes on your system would be the next step. Alternatively, you could just use the workaround to disable portals, but it would be a good idea to get them working again as more apps start porting to GTK 4. Any output in the terminal when running `xdg-desktop-portal-gtk`?

Closing the issue in any case, since there's nothing we can do about it in Nicotine+ itself.

**Comment by mvster1** [comment]
`xdg-desktop-portal-gtk` on terminal returns `command not found`. I'll look into getting it fixed and, sure, just close it. I really appreciate the help!
