### ISSUE TITLE
Adding SMB share on linux results in critical error 

### ISSUE THREAD

**Issue by litemotiv** [nicotine-plus/nicotine-plus#3056]
Nicotine+ Version: 3.3.4
GTK Version: 4.14.4
Python Version: 3.12.4 (linux)

```
Type: <class 'TypeError'>
Value: _path_normpath: path should be string, bytes or os.PathLike, not NoneType
Traceback:   File "/usr/lib/python3.12/site-packages/pynicotine/gtkgui/widgets/filechooser.py", line 109, in on_finish
    selected = [os.path.normpath(i.get_path()) for i in selected_result]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This occurs when adding a network Samba share as a shared folder. This is perhaps not intended usage (?), i've used Nicotine+ on Win11 before and am currently trying it out on Fedora 40 (rpm version). 

Please advise if it is possible to use Samba shares in N+, and how they could be added.

**Comment by litemotiv** [comment]
I looked into it a bit further and i think it's mostly a skill issue on my side. The Samba share on Fedora is a transient one so it's probably not suitable as a shared drive. I'll have to look into permanently mounting the share instead.

Perhaps the error above could be caught to prevent Nicotine+ from crashing. ;-)

**Comment by mathiascode** [comment]
> I looked into it a bit further and i think it's mostly a skill issue on my side. The Samba share on Fedora is a transient one so it's probably not suitable as a shared drive. I'll have to look into permanently mounting the share instead.

Looks like it doesn't return a path, so we're indeed not able to use it. Since nobody else seems to have run into this before, I've only done enough to prevent the crash.
