### ISSUE TITLE
"end" key works incorrectly at the "uploads" tab.

### ISSUE THREAD

**Issue by emoxam** [nicotine-plus/nicotine-plus#3068]
Nicotine+ version:  Nicotine+ 3.3.4 (SNAP)
Operating System/Distribution:
Ubuntu 22.04.4 LTS/Kubuntu

### Describe the bug
1. Open the "uploads" tab
2. press "end" key
3. see cursor moves to the end but focus is not.
4. press home, end then end one more time. see focus changed to the end of the list
5. now end and home works correctly

### Expected behavior
Both keys works fully from the very first time

### Steps to reproduce the bug
described above.

### Additional context
Screenshots, logs, stacktraces or relevant information.
Tell me if you need something.

**Comment by mathiascode** [comment]
Looks like only some lists are affected, for whatever reason. Last time it worked properly was in Nicotine+ 3.2.9.

**Comment by emoxam** [comment]
Forget to mention - added to the main post - my "Nicotine+ 3.3.4 (SNAP)".
