### ISSUE TITLE
Cannot see user profile / file list when expected

### ISSUE THREAD

**Issue by AyeTSG** [nicotine-plus/nicotine-plus#3078]
Nicotine+ version:  3.3.4
Operating System/Distribution: Microsoft Windows 11

### Describe the bug
When trying to view an online user's profile / file list or attempting to upload a file to said user, Nicotine+ refuses to make a connection when a connection should be expected. As a result, the profile / file list do not show, and file uploads time out. This seems to happen sometimes, and not at all at other times.

### Expected behavior
The profile / file list should be fully viewable, and uploads should not time out.

### Steps to reproduce the bug
???
I truly cannot reproduce this issue. Sometimes it happens, sometimes it does not.

### Additional context
Applicable debug connection logs
```
8/8/2024 11:21:41 AM [Conn] Sending message of type <class 'pynicotine.slskmessages.UserInfoRequest'> to user [REDACTED] on existing connection
8/8/2024 11:21:50 AM [Conn] Cannot read data from connection ('[REDACTED]', [REDACTED]), closing connection. Error: [WinError 10054] An existing connection was forcibly closed by the remote host
8/8/2024 11:21:50 AM [Conn] Shutting down socket <socket.socket fd=7884, family=2, type=1, proto=0, laddr=('10.2.0.2', 56392), raddr=('[REDACTED]', [REDACTED])>
8/8/2024 11:21:50 AM [Conn] Closing socket <socket.socket fd=7884, family=2, type=1, proto=0, laddr=('10.2.0.2', 56392), raddr=('[REDACTED]', [REDACTED])>
8/8/2024 11:21:50 AM [Conn] Removed connection of type P to user [REDACTED] ('[REDACTED]', [REDACTED])
8/8/2024 11:21:50 AM [Conn] Removing PeerInit message of type P for user [REDACTED] ('[REDACTED]', [REDACTED])
8/8/2024 11:21:50 AM [Conn] Cannot remove PeerInit message, since an indirect connection attempt is still in progress
8/8/2024 11:21:54 AM [Conn] Indirect connect request of type P to user [REDACTED] with token 41 expired
```

**Comment by mathiascode** [comment]
Any difference with 3.3.5.dev3? There were some changes made to peer connections. https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by AyeTSG** [comment]
> Any difference with 3.3.5.dev3? There were some changes made to peer connections. https://nicotine-plus.org/doc/TESTING.html#windows

Apologies, just now saw this reply. I'll use 3.3.5.dev3 for a bit and let you know if the issue persists.

**Comment by AyeTSG** [comment]
Been using it for almost a week now, and I'm not sure it's made any difference? I still experience these strange "dropouts" in functionality every so often and I can't discern why

**Comment by slook** [comment]
> `[Conn] Cannot read data` ... `[WinError 10054] An existing connection was forcibly closed by the remote host`

This logged error message is the best effort Nicotine+ can do to handle the situation, since the problem appears to originate from the other end, there is nothing actionable here.
