### ISSUE TITLE
right click user implicitly selects all files downloading from that user.

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#308]
Currently, if you want to say retry all files from the same user, for instance if he has a download limit. You have to select all those files. It would be very intuitive if you could simply right click the user and then all his files selected, I guess implicitly would be the nicest, so without actively highlighting them all. But that may be a matter of taste.

**Comment by mathiascode** [comment]
There's a (somewhat unintuitive) way to do this currently. Right-click transfer -> User(s) -> Username -> Select user's transfers.

I'm not sure if selecting everything on right-click is good (or expected) behavior, but I think opening the user menu when right-clicking the username could work as a slight shortcut.

**Comment by mathiascode** [comment]
Alternatively there could be another button in the bottom bar for the purpose.

**Comment by hboetes** [comment]
Yes, let's think this one through a bit before making changes.

**Comment by mathiascode** [comment]
This will not be included in 2.0.0.

**Comment by mathiascode** [comment]
I could make it so that selecting a user or folder in grouping mode performs an action on all child files.

**Comment by hboetes** [comment]
I think that would be awesome.
