### ISSUE TITLE
Client closes after PC waking from sleep

### ISSUE THREAD

**Issue by LightGameStudio42** [nicotine-plus/nicotine-plus#3082]
Nicotine+ version:  3.3.4
Operating System/Distribution: Win10

### Describe the bug
My PC goes sleep with opened client. After waking up the app dissapears from the taskbar, when i click tray, it freezes for a second and dissapears

### Expected behavior
Client doesn't close

### Steps to reproduce the bug
1. Sleep PC
2. Wake it

### Additional context
-

**Comment by slook** [comment]
Is this still a problem in Nicotine+ 3.3.5.dev3 https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by mathiascode** [comment]
When Nicotine+ crashes, can you check if the Event Viewer contains any crash logs? https://superuser.com/a/495511

**Comment by slook** [comment]
@LightGameStudio42 do you want to investigate the cause of the sleep problem or shall we close the issue?

**Comment by LightGameStudio42** [comment]
> @LightGameStudio42 do you want to investigate the cause of the sleep problem or shall we close the issue?

Sure. Should I just check crash logs?

**Comment by slook** [comment]
Please can you confirm that "C:\Program Files\Nicotine+\lib\libcairo-2.dll" does exist?

**Comment by mathiascode** [comment]
I can't reproduce the issue on my Windows machine. Some questions:

- How many monitors do you have? (there was an issue a while back where multiple monitors could crash Nicotine+ on Windows)
- Can you try the latest 3.3.5rc1 build? It upgraded to GTK 4.16.0 the other day. https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by slook** [comment]
Does the crash also occur if one of your monitors suddenly disappears (by that I mean, literally ripping out the display cable)?

**Comment by LightGameStudio42** [comment]
> Does the crash also occur if one of your monitors suddenly disappears (by that I mean, literally ripping out the display cable)?

No. It doesn't happening anymore.
