### ISSUE TITLE
Files are not shared

### ISSUE THREAD

**Issue by LightGameStudio42** [nicotine-plus/nicotine-plus#3083]
Nicotine+ version:  3.3.4
Operating System/Distribution: Win10

### Describe the bug
I use default settings (as for Soulseek) and totally have no uploads.

### Expected behavior
There's uploads, my file are available

### Additional context
Default port is closed as well as the one of Soulseek, but soulseek shares files.
Minutes of inactivity is 0
![image](https://github.com/user-attachments/assets/cacd9a10-684e-4334-bb9e-e06afa3cd363)
![image](https://github.com/user-attachments/assets/d57de18f-c34a-4385-b7f5-0cc7540790b6)

**Comment by slook** [comment]
Is the Soulseek client also running on the same machine? If so, is each client configured to use a different port from each other?

**Comment by LightGameStudio42** [comment]
> Is the Soulseek client also running on the same machine?
Yes
> If so, is each client configured to use a different port from each other?
Yes

**Comment by slook** [comment]
The server is supposed to permit up to 5 users per each IP address, but running multiple clients isn't widely tested.

Does Nicotine+ serve results as expected when it is the only running client?

**Comment by LightGameStudio42** [comment]
> Does Nicotine+ serve results as expected when it is the only running client?

No. I tried it for about 5 days and noticed there were no totally downloads, so started two clients at the same time

> In the Search Files tab, set the search scope to User, leave the username field empty (searches your own files), and try to search for a file/folder in your shares.

I didn't understand, so searching by user with my username was successfull

> Also check if your shares look fine in Menu -> Browse shares

It also reveals all my files...

But searching throught Soulseek gives no results

**Comment by slook** [comment]
> But searching throught Soulseek

You cannot search yourself from the same machine nor another machine on the same local area network, it has to be from a different location over the internet.

**Comment by mathiascode** [comment]
If you want to, you could send your Soulseek username to my email address (on my GitHub profile), and I could check if I'm able to download your files.

**Comment by mathiascode** [comment]
Any update? Were you able to get things working?

**Comment by ngs428** [comment]
> Any update? Were you able to get things working?

I'm not the OP, but I seem to be having issues sharing files too.  Answers to some questions show above...

Is the Soulseek client also running on the same machine? If so, is each client configured to use a different port from each other?
_I have QT and Nicotine+ running on the same machine, but I only use one program at a time. I am switching over to Nicotine.  Or at least trying to as I work through this._  

If you're using a different username, your upload speed might still be unknown to the server, which pushes your search results to the bottom in the official client.
_Possibly happening, I recently switched my username, but this issues was happening before I switched._  

In the Search Files tab, set the search scope to User, leave the username field empty (searches your own files), and try to search for a file/folder in your shares. 
_I don't get any results, but I see @slook mentioned above "You cannot search yourself from the same machine nor another machine on the same local area network, it has to be from a different location over the internet."  So if that is the case, correct, I don't see anything._  

Also check if your shares look fine in Menu -> Browse shares.
_If I go to Menu > Browse Shares > Browse Public Shares I can see all my shares no issue.  I have 7,428 folders and 636 GiB._  

If you want to, you could send your Soulseek username to my email address (on my GitHub profile), and I could check if I'm able to download your files.
I'll send you that.  I had someone else who could download from me.  I am curious if even if you can connect to my username and download, is it possible that my results won't show in your search results?  Maybe they get pushed low.  My connection speed should be good.  I have a 1gig fiber connection.  I'll send that over and see what you can see.  

I had QT open for 15 mins this AM and I got about 30 uploads, I have had Nicotine+ open the last 2 hours and not a single one.  Could be coincidence, but I had Nicotine open all day yesterday and no uploads at all, very odd.

**Comment by slook** [comment]
I can browse your shares and download from you, but alas, you are invisible in search.

**Comment by ngs428** [comment]
> I can browse your shares and download from you, but alas, you are invisible in search.
> 
> You need to delete the third image in your above post (click ... Edit), because ident handles and artist names are not supposed to be posted on this forum.

Image has been corrected.  

Any thoughts on the reason I am visible in search in QT, but invisible in Nicotine?  It has me stumped.

**Comment by mathiascode** [comment]
Two things:
- Are you using the same username in SoulseekQt and Nicotine+? If not, can you try your SoulseekQt username in Nicotine+?
- Can you try rebuilding your shares, to see if it's an issue with the search index database? Run `/rescan rebuild` in a private chat window.

**Comment by ngs428** [comment]
> Two things:
> 
> * Are you using the same username in SoulseekQt and Nicotine+? If not, can you try your SoulseekQt username in Nicotine+?
> * Can you try rebuilding your shares, to see if it's an issue with the search index database? Run `/rescan rebuild` in a private chat window.

I am using the same username in both.

I just did the `/rescan rebuild` .  Please see if it worked.

**Comment by slook** [comment]
Still nothing.

Can you enable the Log Catagory -> "Search" to show in the log pane, on average there should be approx a received search query every couple of seconds or so.

Shall we see happens if you use a different username in Nicotine+?

**Comment by ngs428** [comment]
> Can you enable the Log Catagory -> "Search" to show in the log pane, on average there should be approx a received search query every couple of seconds or so. If there are none being relayed to your client, then it is some kind of server-side issue.

Not sure where to set this.  If you could assist that would be great.  Thank you for the continued help.

**Comment by ngs428** [comment]
Here are the .dbn files.  Please see attached .7z file.
Nic

**Comment by ngs428** [comment]
> > Shall we see happens if you use a different username in Nicotine+?
> 
> Yes, try this. Sometimes users can be excluded from search results due to DMCA complaints. It shouldn't be the case if searches work fine in SoulseekQt, but it's still a good idea to make sure.
> 
> Can you also:
> 
> * enable debug logging (Messages category), restart, let Nicotine+ run for a few minutes, and send the logs to my email? https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging
> * send all the .dbn files to my email (stored in `C:\Users\<USERNAME>\AppData\Roaming\nicotine` on Windows)?

OK, I randomly picked "Greyhound1359" as a new username.  ngs428 I just created yesterday and like I/you mentioned it works to share in QT.  

OK, changed to debug logging and will let this run for a few mins and email you the file.  Yes, I am on Windows.  

Files emailed.  Please review.  And yes, thank you for the continued support.

**Comment by slook** [comment]
> Sometimes users can be excluded from search results

It is possible that what may be happening is the server detecting something fishy going on at the address because of different client versions being used successively with the same username. Perhaps doing this creates a pattern of behavior like what a network of bots would make.

**Comment by ngs428** [comment]
I'll be away from the PC, but I opened Nicotine now and Greyhound1359 will be available for the day today. Please do any checking if you can.  

@mathiascode if you see anything in the .dbn files, please let me know. 

I do randomly get this error on startup, maybe 50% of the time.  That directory does exist, but I get this message: "Plugin upload_stats failed with error <class 'FileNotFoundError'>: [Errno 2] No such file or directory: "

Also, what does the number of connections shown at the bottom of the screen mean?  I usually have 3 at minimum.

**Comment by slook** [comment]
>> your upload speed might still be unknown to the server

> "Plugin upload_stats failed with error..."

Even after you have successfully upload a file, the server still does not report your upload speed for some reason...

![image](https://github.com/user-attachments/assets/76702909-2df0-485e-91f7-6fa27802df53)

It is possible that your broken upload_stats plugin is blocking the reporting of the upload speed, that is normally sent to the server after every successful upload.

If the server can't get a speed, then perhaps it will assume your client is dead and therefore won't relay any search requests to it.

**Comment by ngs428** [comment]
> If the server can't get a speed, then perhaps it will assume your client is dead and therefore won't relay any search requests to it.

Interesting theory.  I will remove it and see what happens.  This won't happen for about 10 hours though since I am off at work now,.  Thanks for the idea.  

Is there a proper way to remove a plugin?  I assume files are stored in a few locations..

**Comment by mathiascode** [comment]
> I'll be away from the PC, but I opened Nicotine now and Greyhound1359 will be available for the day today. Please do any checking if you can.

Same problem still.

> @mathiascode if you see anything in the .dbn files, please let me know.

I think you sent the email to this GitHub issue thread by mistake, so I can't see the files. Please send them to my email.

> Also, what does the number of connections shown at the bottom of the screen mean? I usually have 3 at minimum.

It's mainly a way to see how much P2P activity is going on. If you perform a search, for example, this number will jump quite high.

> Even after you have successfully upload a file, the server still does not report your upload speed for some reason...

That's normal, it takes a couple of uploads (don't remember the exact number) for the server to start sending a speed.

**Comment by mathiascode** [comment]
One thing I forgot to ask: In Preferences -> Searches, are the settings for network searches correct?

![searches](https://github.com/user-attachments/assets/f74f8873-64b5-4bb7-ac25-e0c351e06bd1)

**Comment by ngs428** [comment]
> > I'll be away from the PC, but I opened Nicotine now and Greyhound1359 will be available for the day today. Please do any checking if you can.
> 
> Same problem still.
> 
> > @mathiascode if you see anything in the .dbn files, please let me know.
> 
> I think you sent the email to this GitHub issue thread by mistake, so I can't see the files. Please send them to my email.
> 
> > Also, what does the number of connections shown at the bottom of the screen mean? I usually have 3 at minimum.
> 
> It's mainly a way to see how much P2P activity is going on. If you perform a search, for example, this number will jump quite high.
> 
> > Even after you have successfully upload a file, the server still does not report your upload speed for some reason...
> 
> That's normal, it takes a couple of uploads (don't remember the exact number) for the server to start sending a speed.

I'll send to the correct address later today.  Not sure how I did that, but I see the post now...  I'll verify the settings later too.  Thanks!

**Comment by ngs428** [comment]
> One thing I forgot to ask: In Preferences -> Searches, are the settings for network searches correct?
> 
> ![searches](https://private-user-images.githubusercontent.com/8754153/364072825-f74f8873-64b5-4bb7-ac25-e0c351e06bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MDQ4MTgsIm5iZiI6MTcyNTQwNDUxOCwicGF0aCI6Ii84NzU0MTUzLzM2NDA3MjgyNS1mNzRmODg3My02NGI1LTRiYjctYWMyNS1lMGMzNTFlMDZiZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMjMwMTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNmMWY1MmU3MWMxZTY2NThlNTMxOTNlZGQzYzg4NjQzNjU1NTgxMjFkMWE2Yjk2OTIzOTdmMzk2NjM4NzM0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Kzb_c1W5R2gTihIiknPyo1mB5Qb-lJUaWow8LjVn3Q)

Well, I did have the "Respond to over requests from network users" tuned off.  Turned it on and now i am seeing search requests in the log window.  I have a feeling that was my issue...  Not sure if that is off by default or I clicked it (I must have) but I will monitor and see what happens...

**Comment by slook** [comment]
Yes confirm your results are now visible from here!

**Comment by ngs428** [comment]
> Yes confirm your results are now visible from here!
> 
> Such misconfiguration could be made more obvious such as by logging a warning message about certain important settings being turned off.

Well, I can’t believe it was something that simple!  

I do agree, a warning message would have helped.  

I appreciate the help!!
