### ISSUE TITLE
App window not showing up with Wayland

### ISSUE THREAD

**Issue by ESRSAN2** [nicotine-plus/nicotine-plus#3105]
Nicotine+ version:  3.34
Operating System/Distribution: Ubuntu 22.04.4

### Describe the bug
App window not showing up with Wayland graphics. Running upon 6.8.0_40 kernel and nvidia driver 470 version

### Expected behavior
App window popping up

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Most likely an issue with the NVIDIA driver and GTK 4's GPU renderer. You could try launching Nicotine+ with the `GSK_RENDERER=cairo` env variable instead.

**Comment by ESRSAN2** [comment]
> Most likely an issue with the NVIDIA driver and GTK 4's GPU renderer. You could try launching Nicotine+ with the `GSK_RENDERER=cairo` env variable instead.

I am closing the issue and opening it in another thread, as this user is linked to a company email. I'll give it a try meanwhile and come back to you! And thanks!

**Comment by ESRSAN2** [comment]
Closing the issue and opening it in another thread, as this user is linked to a company email
