### ISSUE TITLE
Input history scroll

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#3106]
Nicotine+ 3.3.5rc1
FBSD 13.3
GTK 4.14.4   •   Python 3.9.18

The global input string is broken when searching. At first, everything works after launching, but after some use, the input history stops scrolling if you scroll up and down arrows. The problem appeared with the latest update.

**Comment by mathiascode** [comment]
Do you mean the search history dropdown, accessed by pressing the arrow button next to the search entry?

Not sure how to reproduce this issue. Is there still a scrollbar in the dropdown when scrolling stops working?

**Comment by 82d** [comment]
UPD
By selecting the mouse, it is not possible to select the newest entry when hanging occurs.

**Comment by mathiascode** [comment]
Which version of Nicotine+ did you upgrade from? If a development version, do you remember roughly when you installed it? Any other package updates at the same time, or only Nicotine+?

**Comment by 82d** [comment]
> Which version of Nicotine+ did you upgrade from? If a development version, do you remember roughly when you installed it? Any other package updates at the same time, or only Nicotine+?

I delete the old version and move new with the git clone command instead.

**Comment by 82d** [comment]
After a new entry, it does not select the history either with the buttons or with the mouse, but after selecting any other line after the first one with the mouse, it begins to be selected. So it repeats all the time. That is, the buttons do not work only because the last line for some reason jams.

**Comment by 82d** [comment]
now it works!
