### ISSUE TITLE
Files get downloaded twice

### ISSUE THREAD

**Issue by yogapotato** [nicotine-plus/nicotine-plus#3107]
Nicotine+ version:  3.3.4
Operating System/Distribution: win10 21h2

### Describe the bug
Some files get downloaded twice despite only appearing once in download queue.

### Expected behavior
Files are not downloaded multiple times when queued once.

### Steps to reproduce the bug
1. Select "Download Folder(s)" for a shared folder.

**Comment by mathiascode** [comment]
Twice in the same folder? Is `(1)` appended to the file name of the second file?

Please check if this is still happening in Nicotine+ 3.3.5rc1: https://nicotine-plus.org/doc/TESTING.html#windows
