### ISSUE TITLE
App window not showing up with Wayland

### ISSUE THREAD

**Issue by raulhsj** [nicotine-plus/nicotine-plus#3108]
Nicotine+ version:  3.34
Operating System/Distribution: Ubuntu 22.04.4

### Describe the bug
App window not showing up with Wayland graphics. Running upon 6.8.0_40 kernel and nvidia driver 470 version. `GSK_RENDERER=cairo` env was suggested, I need to test it.

### Expected behavior
App window popping up

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by raulhsj** [comment]
@mathiascode the env property did the trick. Closing ticket and many thanks!

**Comment by emoxam** [comment]
> [@mathiascode](https://github.com/mathiascode) the env property did the trick. Closing ticket and many thanks!

What env propetry?

**Comment by raulhsj** [comment]
`GSK_RENDERER=cairo` passed as argument. Nonetheless, at least with 6.8.0-52 kernel, the argument is not needed any more.
