### ISSUE TITLE
downloading folder from user browse doesn't work

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#311]
1.4.3-20200617224 / KDE neon (Ubuntu 18.04 LTS)

if folder contains only folders in it (and not files) nicotine refuses to download

![image](https://user-images.githubusercontent.com/3148302/85121484-2014f580-b225-11ea-8597-6355094f99f8.png)

**Comment by mathiascode** [comment]
Doesn't "Download recursive" work?

**Comment by alekksander** [comment]
is expected behavior of recursive to download (in this case) Jazz folder?

**Comment by mathiascode** [comment]
I think it's supposed to download every folder inside the selected one.
