### ISSUE TITLE
Leave "Wishlist" windows open/active after initiating a search & Easier method to initiate search

### ISSUE THREAD

**Issue by ngs428** [nicotine-plus/nicotine-plus#3114]
When I run searches via the Wishlist, I typically run a few in a row, say 10 of them.  Each time I initiate a search by right clicking on a item and selecting "search for Item" the window will disappear.  Desire is to keep this window open/active after each search.

Also, adding a "Search" button to each Wishlist search term row would make it easier to initiate a search. Rather than the right click and and selecting "search for item".  You could click the search button on each row.

Obviously one can't initiate too many searches in too short of time, that would be an issue.  But the user will already be notified of that now by the server if they do that.

**Comment by mathiascode** [comment]
I'm hesitant to implement something like this, because the wishlist isn't supposed to be used for mass searches. The server will ban you temporarily if you perform too many searches in a short period of time.

The most I would be willing to do is keep the wishlist dialog open. You would still have to right-click every individual item you want to search.

**Comment by ngs428** [comment]
> I'm hesitant to implement something like this, because the wishlist isn't supposed to be used for mass searches. The server will ban you temporarily if you perform too many searches in a short period of time.
> 
> The most I would be willing to do is keep the wishlist dialog open. You would still have to right-click every individual item you want to search.

I hear ya.  If the window could at least stay open, I’d love to have that.  Still would take a bit to do each search, but that will help slow down and avoid band.  

If you are able to keep that window open, that would be great!

**Comment by ngs428** [comment]
Works great in 3.3.5.  Thanks!
