### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#312]
Lately I'm noticing whilst downloading multiple files 1 or 2 get a "cannot connect" message. The downloads continue with the rest of files, I can retry those downloads to no avail. Restarting doesn't help either. The user didn't ban me, since I can still download other files from them. All I can do is remove the missing file completely and download it again from the same user.

How can I debug this?

**Comment by hboetes** [comment]
So the workaround:

- Keep the search window open
- Don't clear finished files
- As soon as files are in 'cannot connect' mode, abort & remove them
- Go back to the search window and download from the same user again.

**Comment by hboetes** [comment]
Which also brings me to another nit: N+ does not check if the target file already exists.
So: download file, clear output, download again and it only figures out the problem very late in the process.

**Comment by alekksander** [comment]
i experienced this too, but only twice. don't know how to reproduce.

**Comment by legionxvx** [comment]
I'm having this issue for every download I attempt. I tried @hboetes workaround, and it did not work for me

**Comment by hboetes** [comment]
Before I get `cannot connect` the file is in `getting address` for about a minute and then times out. Really odd since other files work fine.

**Comment by hboetes** [comment]
What's also interesting: normally if you download a complete folder the files are downloaded in order. When there is a `cannot connect` a file or two from somewhere in the download list is tried and gets stuck at `getting address`.

**Comment by mathiascode** [comment]
Could you enable debug logs in the log window, and post the logs from this incident?

**Comment by hboetes** [comment]
I have `warnings`, `connections` and `transfers` enabled in the debug window. Anything else?

For anybody else who can't find debugging: `view` → `debug mode`

**Comment by mathiascode** [comment]
That should be enough.

**Comment by legionxvx** [comment]
Same symptoms for my issue. I see "Getting Address" and then it fails.

I'll check the logs when I have time to do so.

**Comment by Spongman** [comment]
0b7221dcf870ef96ead09dac712165d627ec83d5 broke it
