### ISSUE TITLE
Toggle in Searches Preferences Screen to Turn on/off Wishlist searching

### ISSUE THREAD

**Issue by ngs428** [nicotine-plus/nicotine-plus#3120]
I would like to leave my Wishlist in tact, but have the option to disable automatic searching.  The searches in my wishlist return the same results time and time again, so not searching for an amount of time would be nice, Fewer search tabs to sort through between what I am manually searching vs what came in with the Wishlist (I know they are labeled) :)

**Comment by mathiascode** [comment]
I think what you're actually asking for is an option to ignore duplicate results? In that case, https://github.com/nicotine-plus/nicotine-plus/discussions/1604.

**Comment by ngs428** [comment]
Kind of, but not specifically.  I used that ignore duplicate results in QT and I was never quite sure it actually worked.  

I am just looking for the option to disable wishlist searches.  If it truly ignored duplicate results, then that may be ok, but I don’t think it ever worked right in QT.  Personally, I just manually search my wishlist when I have time.  I know that may not be thought of the wishlist, but right now I just keep getting searches with the same old results and it would just be nice to disable the searches.

**Comment by ngs428** [comment]
> I think what you're actually asking for is an option to ignore duplicate results? In that case, #1604.

I read through that one a bit more. I do see some comments in there about the wishlist results being a bit annoying at times.  Since duplicates are not removed, it is the same files over and over.

My thought here is to preserve the wishlist items and just have a simple toggle to turn automatic searching off.  When I jump on my PC after Nicotine has been running for a while, I don’t have time to dig through the 20 new tabs which are probably just all repeats anyway.  Just toggle it off, if you could please.  🙏
