### ISSUE TITLE
Wishlist result notification is emitted even when disabled

### ISSUE THREAD

**Issue by Firepal** [nicotine-plus/nicotine-plus#3123]
Nicotine+ version: 3.3.4 (stable)
Operating System/Distribution: Windows 10 x64

### Describe the bug
In Settings > User Interface > "Show notifications for:", the "Wishlist results found" checkbox seems to not do anything. The program will continue to notify me of wishlist items regardless, despite clicking "Apply" and restarting the program.

### Expected behavior
The "Wishlist results found" checkbox in the "Show notifications for" section should be respected

### Steps to reproduce the bug
Just add something to your wishlist susceptible to be found during an auto-search, then untick the "Wishlist results found" checkbox mentioned above, click "Apply" and minimize Nicotine+. 

### Additional context
N/A

**Comment by slook** [comment]
Please can you check if this problem still occurs in Nicotine+ 3.3.5.rc1 https://nicotine-plus.org/doc/TESTING.html ?

**Comment by Firepal** [comment]
@slook Just tried it, I can confirm that the issue also appears in 3.3.5rc1.

**Comment by mathiascode** [comment]
Are we talking about notification popups/bubbles or tab highlights? The setting only affects notification bubbles.

**Comment by slook** [comment]
> and minimize Nicotine+.

The OP must be talking about popups here.

**Comment by Firepal** [comment]
Okay I initially provided way too little information, sry.

I'm talking about when Nicotine+ is _minimized_ (on the taskbar next to other running windowed programs) and the icon is highlighted in green. I've seen the green highlight happen with private messages, which I want, and wishlist search hits, which I don't.

Honestly it's unclear what Nicotine+ means when it comes to "notifications". Windows 10 has "notifications" but I've never seen _those_ from Nicotine+. Are notifications the highlighted tabs when the window is up? The special "blue circle" system tray icon? The highlighted taskbar icon? 

Just received a wishlist search result with the "Wishlist results found" checkbox off:
the system tray icon didn't change, but I got the green highlighted taskbar icon.
![image](https://github.com/user-attachments/assets/fe335b33-f29c-4fc8-948e-8882bfd9193f)

It would be nice if it was somewhat consistent.

**Comment by slook** [comment]
The window title bar text does change for some events such as new messages and found wishlist results, regardless of the notification setting. ~Perhaps this causes Windows to create the green highlight by itself.~ Edit: orange icon highlight (the green dot is of course made by N+)

**Comment by mathiascode** [comment]
I haven't looked at the code in a while, but we do set taskbar urgency hints (the orange highlight) in some cases. Tying these to the notification checkboxes seems like something we could do (unless I'm forgetting some reason why they currently aren't)?

**Comment by slook** [comment]
@Firepal Please test the latest build of 3.3.5.rc1 https://nicotine-plus.org/doc/TESTING.html#windows to verify that notifications behave in the way that you rightfully expect?

**Comment by Firepal** [comment]
I can confirm wishlist results don't produce the orange taskbar highlight in the release candidate, and this behavior meets my expectations. I wonder if anyone actually expects wishlist results to be high-priority, time will tell... Thanks for the quick fix =)
