### ISSUE TITLE
two cds saved in the same folder

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#313]
I just downloaded 2 2-CD albums from the same user, and they ended up in the same folders, `Disc 1` and `Disc 2`.  Of course my tagger was able to make sense of it. So this is no biggy.

But I'd still like to mention it so people can have a look at it and come up with a creative solution.

**Comment by mathiascode** [comment]
Found this suggestion while browsing the Soulseek group: https://groups.google.com/forum/#!topic/soulseek-discussion/Ney98CQg874

**Comment by hboetes** [comment]
Cheers guys. That's awesome. :-)
