### ISSUE TITLE
Wrong hotkeys on mac. Should be Cmd instead of Ctrl

### ISSUE THREAD

**Issue by n-smits** [nicotine-plus/nicotine-plus#3139]
Nicotine+ version: 3.3.4
Operating System/Distribution: macOs 14.6.1

### Description

Hotkey for "Hide" is `Ctrl + H`. Likewise, for "Hide Others" it is `Ctrl + Opt + H`.

### Expected Behavior

Instead of `Ctrl`, it should be `Cmd` (Command). Ie. `Cmd + H` and `Cmd + Opt + H`, respectively.

### Note

This is rather annoying since Hide is the basic window management control on mac. Additionally, hotkey remapping via mac System Settings doesn't work, so fixing this in the user land is impossible without additional programs.

**Comment by n-smits** [comment]
I am guessing line `("app.hide", ["<Primary>h"]),` needs to be added here

https://github.com/nicotine-plus/nicotine-plus/blob/62b55b25016e08b1c0ce2ca9b59a5e2a55c27938/pynicotine/gtkgui/application.py#L219

to resolve the immediate problem.

**Comment by mathiascode** [comment]
Should be fixed in 3.3.5rc2: https://nicotine-plus.org/doc/TESTING.html#macos
