### ISSUE TITLE
In download page, pressing Delete key removes 2 files instead of 1

### ISSUE THREAD

**Issue by zebulon-1st** [Nicotine-Plus/nicotine-plus#314]
Nicotine+ version:  1.4.3
branch master
downloaded from a "git clone"
always "git pull"ed before a new run.

Operating System/Distribution:
Debian GNU/Linux 9 (stretch) x86-64
Kernel: Linux 4.9.0-12-amd64

### Describe the bug
In the download page, if I remove (by pressing Delete key) a file (finished or not), it is well removed. But the next file in list is removed too from the list.

Note : it does the same (2 files removed instead of 1) if I start from the very last file in list : the file before it is removed too.

**Comment by mathiascode** [comment]
Does this happen consistently? I tested Nicotine+ on Debian 9, but couldn't reproduce the issue.

**Comment by zebulon-1st** [comment]
>Does this happen consistently?

It seems yes. It happened each times I would delete a file in the download list.

**Comment by mathiascode** [comment]
Could you check if this branch solves the issue?

`git clone -b deletekey https://github.com/mathiascode/nicotine-plus`

**Comment by zebulon-1st** [comment]
Yes, absolutely. It seems solved.
I tried selecting the very first file only, and only the first file has been deleted.
I tried selecting the very last file only, and only the last file has been deleted.

But, another strange thing happens when I use CTRL to select here and there.
Select a file, then CTRL to select another one, and the selection changes to the very last file in list.

And, globally, this version lags on GUI.

**Comment by mathiascode** [comment]
Can you elaborate on the GUI lag issue? When exactly did it start happening? What kind of lag is it? Do you have many transfers in your download list (https://github.com/Nicotine-Plus/nicotine-plus/issues/34)?

**Comment by zebulon-1st** [comment]
It is perceptible as soon as this version of Nicotine+ (the test branch) is launched. The graphical interface is slower to respond than with the version of the master branch.
Clicking on a tab (the search or downloads tab, for example) N+ takes a while before switching to it. Searching, downloading files from the search, ... In fact, any operation performed is slow to respond.
Otherwise, I have no other download in progress at the moment. There are only those (just a few audio files, about 10-15) chosen to test the problem with the Delete key.

**Comment by mathiascode** [comment]
Probably just a fluke, the changes in the deletekey branch shouldn't affect GUI performance. Mind trying the master branch again?

**Comment by zebulon-1st** [comment]
I retried with branch master (git pull'ed before, of course).
The issue seems to be fixed.
I tried deleting 1 file from the top, only the file selected removed.
I tried deleting 1 file from the bottom, only the file selected removed.
I tried selecting here and there, with CTRL key, selection unchanged, and only selection removed.
