### ISSUE TITLE
'Open in File Manager' does not work on 3.3.5 in macOS Monterey

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#3143]
Nicotine+ version:  3.3.5
Operating System/Distribution: macOS Monterey 12.7.6

After updating to the latest version just now, 'Open in File Manager' does nothing in either the download or upload tabs. Finder does not open.

**Comment by hboetes** [comment]
Please run Nicotine+ from a terminal, reproduce the issue, and paste the generated log messages in this ticket.

**Comment by thep50** [comment]
ok, I did that and it just brings up this line:

> (org.nicotine_plus.Nicotine:7889): GLib-GIO-CRITICAL **: 15:02:48.973: g_osx_app_info_launch_internal: assertion 'uris == NULL' failed

**Comment by mathiascode** [comment]
Reported upstream: https://gitlab.gnome.org/GNOME/glib/-/issues/3484

I'll add a workaround until it's fixed.

**Comment by mathiascode** [comment]
Please try 3.3.6.dev1 and verify that everything works as expected: https://nicotine-plus.org/doc/TESTING.html#macos

Let us know if you run into any other issues. Nicotine+ 3.3.6 will possibly be the last version to support macOS 12, depending on when GitHub removes the macOS 12 images.

**Comment by thep50** [comment]
> Please try 3.3.6.dev1 and verify that everything works as expected: https://nicotine-plus.org/doc/TESTING.html#macos

Alright great, both the file manager issue and text selection issue are fixed now.

> Let us know if you run into any other issues. Nicotine+ 3.3.6 will possibly be the last version to support macOS 12, depending on when GitHub removes the macOS 12 images.

Ok, thanks for the heads up. I hopefully will get a newer mac soon that can run the latest macOS.

**Comment by thep50** [comment]
I just noticed another issue. When the search bar at the top is selected, the up and down arrow keys no longer browse through the last searches. It's the same for all tabs.

**Comment by mathiascode** [comment]
> I just noticed another issue. When the search bar at the top is selected, the up and down arrow keys no longer browse through the last searches. It's the same for all tabs.

Thanks, I'll take a look.

**Comment by mathiascode** [comment]
@thep50 Should be fixed in https://github.com/nicotine-plus/nicotine-plus/commit/cdeb6b08e4bc0155d5fe2686bf3bde75bca8d35f.

**Comment by thep50** [comment]
> @thep50 Should be fixed in [cdeb6b0](https://github.com/nicotine-plus/nicotine-plus/commit/cdeb6b08e4bc0155d5fe2686bf3bde75bca8d35f).

Yep, fixed now. Thanks.
