### ISSUE TITLE
Issues with selecting text on 3.3.5 in macOS Monterey

### ISSUE THREAD

**Issue by thep50** [nicotine-plus/nicotine-plus#3144]
Nicotine+ version:  3.3.5
Operating System/Distribution: macOS Monterey 12.7.6

Right after updating to 3.3.5, I noticed an issue selecting text - holding Command and hitting any arrow keys no longer moves the selection. The arrow keys work on their own, as well as when holding Shift or Option. In fact, it seems like Option is doing the function that Command should be doing.

**Comment by hboetes** [comment]
Please run Nicotine+ from a terminal, reproduce the issue, and paste the generated log messages in this ticket.

**Comment by thep50** [comment]
I did this but it doesn't produce any logs when I hit command and/or any arrow keys.

**Comment by mathiascode** [comment]
Looks like a bug in GTK. These shortcuts use the Option key by mistake, when they should actually use Cmd: https://github.com/GNOME/gtk/blob/d3c166d5115ae8c6519a35fec847332f99c949c2/gtk/gtktext.c#L1447-L1457

Until we've fixed it upstream, I'll restore the missing shortcuts in Nicotine+.

**Comment by mathiascode** [comment]
If you find any other missing keyboard shortcuts, let us know.
