### ISSUE TITLE
Incorrect processing of passwords with special characters

### ISSUE THREAD

**Issue by 56th** [nicotine-plus/nicotine-plus#3156]
Nicotine+ version:  3.2.9
Operating System/Distribution: Ubuntu 24.04.1 LTS

### Describe the bug

When application is started for the first time, one enters username and password. All works fine during the first run. 
At the second run (after restarting the application), the application fails to read the password from configs properly, prompting a window to enter "correct" credentials again.

### Steps to reproduce the bug

Come up with a username and use `@dRtif8r%?8Ea8O!3jW%"p\#5` as the password.

Most likely the application fails to read `#` (interpreting it as a comment):

```
$ head ~/.config/nicotine/config
[server]
server = ('server.slsknet.org', 2242)
login = someusername
passw = @dRtif8r%?8Ea8O!3jW%"p\#5
interface = 
ctcpmsgs = False
autosearch = []
autoreply = 
portrange = (2234, 2239)
upnp = True
```

**Comment by mathiascode** [comment]
I can't reproduce this issue in Nicotine+ 3.2.9 nor 3.3.5. The password is stored and read properly on each restart.

Config values should be read no matter what characters are present in them. You could put that password in the username field or another text entry in the preferences, such as Network Interface, restart, and verify if the GUI reads it properly.

**Comment by 56th** [comment]
> I can't reproduce this issue in Nicotine+ 3.2.9 nor 3.3.5. The password is stored and read properly on each restart.
> 
> 
> 
> Config values should be read no matter what characters are present in them. You could put that password in the username field or another text entry in the preferences, such as Network Interface, restart, and verify if the GUI reads it properly.

Will try this tomorrow and report back. Thanks!

**Comment by 56th** [comment]
@mathiascode ok, I was able to find out the actual problem and reproduce it. It comes from copying and pasting text from terminal after double-clicking on the text (note the white part on the screenshot below): 

![Screenshot from 2024-10-17 07-03-59](https://github.com/user-attachments/assets/10ff5560-40ed-454c-a68a-1122a3db5788)

If one pastes it e.g. in a text editor, one can see that there is a line break in the end.
If one pastes such a password during the config set up in GUI in the password field (after deleting / moving somewhere `~/.config/nicotine/config/*`), a new user will be created successfully. During the second run, however, the application will fail to parse it from configs:

![Screenshot from 2024-10-17 06-54-40](https://github.com/user-attachments/assets/3572481d-37c9-4c53-a6d3-dea65fc08ae5)

**Comment by slook** [comment]
The problem occurs because the server allows trailing newline characters in the password string, but the `config` file doesn't.

It works the first time because the string is obtained verbatim directly from the text entry widget, but fails after restart because any end-trailing newline characters are striped upon parsing the value from the `config` file upon startup.

To resolve this, we could take any one of the following actions:
- `rstrip("\n")` trailing newline characters from the entry
- Reject the entry, ideally with an error message or hint icon indicating the reason for rejecting the input
- Storing the `passw` value elsewhere such as by implementing https://github.com/nicotine-plus/nicotine-plus/issues/2834

Any action may of course lead to somebody else being unable to login or change their password.

**Comment by 56th** [comment]
> `rstrip("\n")` trailing newline characters from the entry

Does their server accept whitespaces anywhere in the password string? If so, rstripping may not be enough for the `config` parser to work properly. 
I may check it once I am by the laptop. 

This approach shall fix the usecase I described though, and seems to be the easiest and the least intrusive to implement. I do not think it shall affect existing users, because if they have trailing line break in the password, they already face this issue with GUI.

**Comment by slook** [comment]
> Does their server accept whitespaces anywhere in the password string?

Yes, it appears to accept any string, including whitespaces/newlines anywhere, at the start, in the middle or at the end.

The config parser supports spaces anywhere, but newlines are not allowed at the end, only at the start or in the middle.

**Comment by 56th** [comment]
> The problem occurs because the server allows trailing newline characters in the password string, but the config file doesn't.

Another way may be storing the value in `~/.config/nicotine/config/passwd`, and just reading it from this text file as is, leveraging all the validation to the server. 

I think that adding a sentence to the register/login GUI window that clarifies that the password is stored in plain text locally would be nice, too.

**Comment by slook** [comment]
> Another way may be storing the value in `~/.config/nicotine/config/passwd`, and just reading it from this text file as is

> adding a sentence to the register/login GUI window that clarifies that the password is stored in plain text locally

Anything else more elaborate can be dealt with in Issue #2834 please do chime in with any suggestions you have about that there.

**Comment by 56th** [comment]
> Even though the server allows such strings, I think it's safer to assume it isn't the user's intention to include a newline character at the end of their password.

I agree (and this would actually apply for my case as well). Thanks for the merge request.

**Comment by mathiascode** [comment]
Leading and trailing spaces, as well as spaces before and after a newline character, are affected as well. Maybe we should just remove newline characters from the password entirely? Surely nobody would actually want them in a password?

**Comment by slook** [comment]
> Maybe we should just remove newline characters from the password entirely?

The problem with the client altering the password in any way is that it could cause difficulties for a user who wishes to login using another client, or if they created their account with a different client.

> Surely nobody would actually want them in a password?

It is a valid use case for a user to copy the entire contents of an arbitrary file or page of a document used to store their secure key that may well contain line breaks (as well as spaces, tabs, etc) within it.

**Comment by mathiascode** [comment]
Are you suggesting https://docs.gtk.org/gtk4/property.Entry.truncate-multiline.html then?

**Comment by mathiascode** [comment]
> The problem with the client altering the password in any way is that it could cause difficulties for a user who wishes to login using another client, or if they created their account with a different client.

It's true that we should avoid modifying passwords, but we don't have many options with the current setup. I don't want to introduce drastic changes that somehow end up wiping or corrupting all passwords when upgrading to 3.3.7, and I don't have time to deal with such fallouts either.

Considering seemingly nobody has run into this issue in the past two decades, enabling the truncate-multiline property and stripping spaces at the beginning and end of the password is probably fine, at least for now.

**Comment by slook** [comment]
> Are you suggesting https://docs.gtk.org/gtk4/property.Entry.truncate-multiline.html then?

Yes. It doesn't make sense to allow entering multiple lines into a single-line entry via pasting, since it can't be done by typing manually. The way it is at the moment is obscure in this regard, and this property will make the entry behave as intended.

> stripping spaces at the beginning and end

That's a separate issue. It doesn't feel like a good idea to make any more changes to the behaviour of the password entry widgets than what is absolutely needed to resolve the issue at hand.

**Comment by mathiascode** [comment]
> > Leading and trailing spaces, as well as spaces before and after a newline character, are affected as well
> 
> When I tested this I found that that leading and trailing spaces, provided there are no newline characters, can be stored in the config and are accepted by the server.

Hm, there's something strange going on with loading config values. Leading/trailing whitespace, even trailing newlines, are properly stored in the config, but disappear when loaded on the next run.

**Comment by slook** [comment]
https://github.com/nicotine-plus/nicotine-plus/blob/6da7ea1d26e71459b581255bdc174f6d1b369359/pynicotine/config.py#L704

https://docs.python.org/3/library/ast.html#ast.literal_eval

> Changed in version 3.10: For string inputs, leading spaces and tabs are now stripped.

**Comment by mathiascode** [comment]
literal_eval isn't used on string values. It's happening in the configparser module, presumably here: https://github.com/python/cpython/blob/23468acac4f682f079abc09e93492990d61e56c2/Lib/configparser.py#L1154

In any case, not much that can be done about that. I'll merge the PR.
