### ISSUE TITLE
3.3.5 has same bug latest Test clients have about upload showing wrong upload

### ISSUE THREAD

**Issue by Climbatiz** [nicotine-plus/nicotine-plus#3162]
Nicotine+ version:  3.3.5
Operating System/Distribution: Windows

I went from latest test clients to Stable to avoid this bug but after going to newer builds it started happening again, possibly related to "Upload I/O error: Remote client does not support large file transfers: cannot fit 'int' into an offset-sized integer" bug

but my total upload data in Statistics went from some normal TB value to 60 EiB however much that is, i really don't want this bug to be messing up my upload stats

i don't see it fixed in new 3.3.6 release notes

### Additional context
![Untitled](https://github.com/user-attachments/assets/0a8c320f-29e9-4a37-83c6-dd054bed0633)

**Comment by mathiascode** [comment]
> I went from latest test clients to Stable to avoid this bug

Please report bugs if you encounter them again. Nobody else reported this again, so it was assumed to be fixed.

**Comment by Climbatiz** [comment]
i rarely encounter the bug though in current 3.3.5 stable, i can have client running 1-2 weeks without problems, seems to be something very specifc

**Comment by slook** [comment]
64 EiB = 68,719,476,736 GiB (73,786,976,294,838,206,464 Bytes)

**Comment by slook** [comment]
If the "cannot fit 'int' into an offset-sized integer" bug or another error is thrown here then there an opportunity exists for the progress, and thereby the statistics, to be updated with erroneous values because that's called before the exception handler...

https://github.com/nicotine-plus/nicotine-plus/blob/70b2bc72bdba768d21449fd392aad64137def246/pynicotine/slskproto.py#L1903-L1921

Suggest emitting the "file-upload-progress" event after the exception handler instead of before it.

**Comment by Climbatiz** [comment]
i got that same error 2 days ago (client has been running for 4 days) but my upload stats did not bug out

**Comment by slook** [comment]
What version are you running at the moment?

**Comment by Climbatiz** [comment]
3.3.5

**Comment by mathiascode** [comment]
Right, I understand what's happening now:
1. A Soulseek NS client starts downloading a large file
2. They cancel the download after they've downloaded more than 2GB
3. `last_byte_offset` remains at the offset they cancelled at
4. They resume the download
5. Resuming fails, as they send a -1 offset (interpreted as the maximum unit64 value on our end)
6. `last_byte_offset` is subtracted from the new offset: https://github.com/nicotine-plus/nicotine-plus/blob/70b2bc72bdba768d21449fd392aad64137def246/pynicotine/transfers.py#L443
7. ...and the remaining value is added to the stats, blowing them up: https://github.com/nicotine-plus/nicotine-plus/blob/70b2bc72bdba768d21449fd392aad64137def246/pynicotine/transfers.py#L448

**Comment by Climbatiz** [comment]
well... i'll goto latest TEST version then. will report if it happens again
