### ISSUE TITLE
Cannot update nicotine+

### ISSUE THREAD

**Issue by Setup2134** [nicotine-plus/nicotine-plus#3167]
Nicotine+ version:  3.3.6
Operating System/Distribution: Windows 10 21H2

### Describe the bug
Updating to the latest nicotine+ version results in various python errors. they persist even after fully wiping nicotine+ from my system and now I'm worried I've lost my userlist (Though hopefully not, i'm not sure how it works but i have a backup but it has this same error)

### Expected behavior
Nicotine+ updates with 0 issue

### Steps to reproduce the bug
1. download nicotine+ installer
2. Install
3. Try and run Nicotine+

### Additional context
Screenshots, logs, stacktraces or relevant information.
![image](https://github.com/user-attachments/assets/8bed1ce8-875a-4fc2-83b3-e9518146a00d)
![image](https://github.com/user-attachments/assets/6df1d1c8-eaf2-4808-ab36-1048c8dad169)

**Comment by slook** [comment]
What installation method did you use (msi installer, standalone package, chocolaty, etc)?

**Comment by Setup2134** [comment]
> What installation method did you use (msi installer, standalone package, chocolaty, etc)?

I tried the installer first, and then when that didn't work I tried standalone. Same error.

**Comment by mathiascode** [comment]
Installing 3.3.5 again works?

**Comment by Setup2134** [comment]
> Installing 3.3.5 again works? The standalone package was extracted to an empty directory?

I was on 3.3.4 before but installing 3.3.5 works fine. I was installing 3.3.6 to an empty directory, too. Still brought up the same error message
I remember having this error on an older version of Nicotine+ (or something similar to it, i believe I made an issue about it) but i'm thinking that might've been something else. No matter what I try this time i can't get it to work.
Is there any difference between the 3.3.6 installer on the nicotine+ website and the one on this git repo?

**Comment by slook** [comment]
>  Is there any difference between the 3.3.6 installer on the nicotine+ website and the one on this git repo?

No, the repo serves the content on the website.

> I was on 3.3.4 before but installing 3.3.5 works fine

You're better off sticking with 3.3.4 for now because 3.3.5 had a serious bug in it.

**Comment by mathiascode** [comment]
@Setup2134 Can you try the following builds, and mention which ones that work (if any), and which ones that don't?

- https://github.com/nicotine-plus/nicotine-plus/actions/runs/11545716424
- https://github.com/mathiascode/nicotine-plus/actions/runs/11545486808
- https://github.com/mathiascode/nicotine-plus/actions/runs/11545492029

Scroll down on the pages for download links.

**Comment by Setup2134** [comment]
> @Setup2134 Can you try the following builds, and mention which ones that work (if any), and which ones that don't?
> 
>     * https://github.com/nicotine-plus/nicotine-plus/actions/runs/11545716424
> 
>     * https://github.com/mathiascode/nicotine-plus/actions/runs/11545486808
> 
>     * https://github.com/mathiascode/nicotine-plus/actions/runs/11545492029
> 
> 
> Scroll down on the pages for download links.

Firstt two bring up the same error. The last one (that seems to be built on ucrt, rather than clang) starts up fine and seems to work properly. I have a feeling it might be related to that.

**Comment by mathiascode** [comment]
Thanks for testing. It doesn't seem to be a widespread issue (I would've expected at least another bug report by now), but clearly something is flaky with the Clang builds. I'm changing the builds to use UCRT for now.
