### ISSUE TITLE
Opening the uploads window or trying to check how much I have uploaded freezes Nicotine+

### ISSUE THREAD

**Issue by Setup2134** [nicotine-plus/nicotine-plus#3169]
Nicotine+ version:  v3.3.4
Operating System/Distribution: Windows 10 21H2

### Describe the bug
After opening Nicotine+, Whenever I try and go to the uploads tab or click the users button at the top of the window the program stops responding and freezes, forcing me to restart. I am unable to clear my uploads either because of this.

### Expected behavior
I am able to check my uploads list and the users button.

### Steps to reproduce the bug
1. Open nicotine+
2. Go to the uploads tab
3. See error

### Additional context
Screenshots, logs, stacktraces or relevant information.
None, I don't get any traceback messages and if there are I don't know how to view them.

**Comment by mathiascode** [comment]
Please try the latest dev build and see if the uploads tab loads there (there were some larger performance improvements in 3.3.5): https://nicotine-plus.org/doc/TESTING.html#windows

How large is your uploads.json file (in C:\Users\<USERNAME>\AppData\Roaming\nicotine)?

**Comment by Setup2134** [comment]
It seems that when i tried your 3.3.7 test build the issue was fixed. 3.3.5 was still having these issues however.
