### ISSUE TITLE
Failing test `pynicotine.tests.integration.test_startup.StartupTest testMethod=test_gui_startup` on Void Linux CI build

### ISSUE THREAD

**Issue by MIvanchev** [nicotine-plus/nicotine-plus#3171]
Nicotine+ version:  3.3.6
Operating System/Distribution: Void Linux

### Describe the bug

Failing test 

### Expected behavior

The test runs

### Steps to reproduce the bug

See the [build log](https://github.com/void-linux/void-packages/actions/runs/11550346147/job/32145147057?pr=52806)

### Additional context

I got a failing test while updating Nicotine+ from 3.3.4 to 3.3.6. Maybe someone has more insights as to what is going on.

**Comment by mathiascode** [comment]
We had this issue with some of our CI jobs recently, due to no fonts being installed: https://github.com/nicotine-plus/nicotine-plus/commit/5160aba182282d8471fc1d7289792b8ec2819c39

**Comment by MIvanchev** [comment]
Thanks @mathiascode that did it, is dejavu required to run Nicotine+ now?
