### ISSUE TITLE
Nothing shows up on uploads list even when people download from me

### ISSUE THREAD

**Issue by Setup2134** [nicotine-plus/nicotine-plus#3177]
Nicotine+ version:  3.3.7.dev1
Operating System/Distribution: Windows 10 21H2

### Describe the bug
My uploads list remains empty even when the button turns blue meaning there are people downloading from me. I cannot interact with any of these users either (e.g cancelling, banning users, restarting uploads etc.)

### Expected behavior
Uploaded files will show up on the uploads list

### Steps to reproduce the bug
1. Open Nicotine+
2. Go to uploads tab
3. See Error

### Additional context
Screenshots, logs, stacktraces or relevant information.
On 3.3.4 which i upgraded from. My uploads list would crash nicotine+ entirely. I wonder if that might be related. #3169

**Comment by mathiascode** [comment]
Is `Preferences -> Uploads -> Autoclear finished/cancelled uploads from transfer list` enabled?

**Comment by Setup2134** [comment]
> Is `Preferences -> Uploads -> Autoclear finished/cancelled uploads from transfer list` enabled?

Yes it was. I must've enabled it at some point by accident.
