### ISSUE TITLE
A lot of dump files (gdbus )

### ISSUE THREAD

**Issue by LightGameStudio42** [nicotine-plus/nicotine-plus#3181]
Nicotine+ version:  3.3.5rc1
Operating System/Distribution: Windows 10

Every time I quit the app cmd appears and writes dump file to C;/dump related to C+ and gdbus (reltaed to N+)
![image](https://github.com/user-attachments/assets/4b9fa888-4db2-4670-ba6d-2faff881bbb5)

**Comment by slook** [comment]
Try 3.3.6 https://nicotine-plus.org/doc/DOWNLOADS.html#windows

**Comment by mathiascode** [comment]
Might be a better idea to try 3.3.7.dev1, since we changed the environment from Clang to UCRT: https://nicotine-plus.org/doc/TESTING.html#windows

If it still happens 3.3.7.dev1, we can start looking into why Nicotine+ and gdbus crash on exit.

**Comment by slook** [comment]
@LightGameStudio42 Please can you test 3.3.7rc1 to verify it works on your system without errors, link:
https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by LightGameStudio42** [comment]
> @LightGameStudio42 Please can you test 3.3.7rc1 to verify it works on your system without errors, link: https://nicotine-plus.org/doc/TESTING.html#windows

Hello, it doesn't happen it 3.3.7rc1
