### ISSUE TITLE
Windows Nightly builds libgcc_s_seh-1.dll is missing

### ISSUE THREAD

**Issue by Inso-m-niaC** [nicotine-plus/nicotine-plus#3183]
The libgcc_s_seh-1.dll is present in the lib directory, but says it is missing when attempting to launch nicotine+.

**Comment by mathiascode** [comment]
Looks like a regression in the latest cx_Freeze release: https://github.com/marcelotduarte/cx_Freeze/issues/2671

**Comment by Inso-m-niaC** [comment]
I ran this latest, and the problem persists. Is it likely to do with the he switch from clang to the current thing?

**Comment by mathiascode** [comment]
The latest build works on my end now.

**Comment by Inso-m-niaC** [comment]
Okay. I tested it, and it launches.
But, now the plugin is throwing a FileNotFound error:

 Plugin big_text failed with error <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '${NICOTINE_DATA_HOME}\\plugins\\big_text\\fonts\\not_as_big_text.txt'.
Trace:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/pluginsystem.py", line 891, in _trigger_command

**Comment by mathiascode** [comment]
Fixed in https://github.com/nicotine-plus/nicotine-plus/commit/f29988a4da194446b635c1b11a01eb69289b10df
