### ISSUE TITLE
[Bug]: Transfer Statistics Total Uploaded Size jumps to 32 EiB

### ISSUE THREAD

**Issue by minicoz** [nicotine-plus/nicotine-plus#3185]
Nicotine+ version:  
Operating System/Distribution:
Linux, 3.36

### Describe the bug
My Total Uploaded Size was near 5 TiB when all of a sudden it jumped to 16 EiB and now its at 32 EiB. 

### Expected behavior
Not jump to 32 EiB but instead correctly go up to 6 TiB

### Steps to reproduce the bug
Upload a lot of P*rn

### Additional context
Screenshots, logs, stacktraces or relevant information.

![Capture](https://github.com/user-attachments/assets/48ebb396-b7bd-42fa-85ea-37163877b002)

**Comment by minicoz** [comment]
ahh i just found 
https://github.com/nicotine-plus/nicotine-plus/issues/3162

This bug might not be fixed yet

**Comment by mathiascode** [comment]
What version of Nicotine+ are you using? The fix has not been released yet, but will be available in 3.3.7.

**Comment by minicoz** [comment]
gotcha 3.36, i have autoupdates so when 3.3.7 is out i should get the fix
