### ISSUE TITLE
Picking an emoji clears text in chat entry, rather than being appended to it

### ISSUE THREAD

**Issue by Inso-m-niaC** [nicotine-plus/nicotine-plus#3197]
Nicotine+ version:  Nicotine+ 3.3.7rc1

Describe the bug:

Picking an emoji clears text in chat entry, rather than being appended to it.
As a result, only one emoji can be present in the chat entry at any one time.

Steps to reproduce the bug:

1) Type anything in the chat entry and then pick an emoji
2) Pick an emoji, the pick a subsequent emoji.

**Comment by slook** [comment]
OS platform and GTK version?

**Comment by Inso-m-niaC** [comment]
GTK 4.16.5 & win10

**Comment by mathiascode** [comment]
Regression in GTK 4.16, will be fixed in GTK 4.16.6.

**Comment by mathiascode** [comment]
I forgot our x86_64 macOS builds are stuck on GTK 4.16.2, so I'll have to come up with a workaround anyway.

**Comment by mathiascode** [comment]
Managed to cobble something together. Please try the latest dev build and verify that everything works fine.

**Comment by Inso-m-niaC** [comment]
The effort is appreciated. Thanks.

And i can confirm that it works perfectly well.
