### ISSUE TITLE
Folder/Files names starting with dots '.' not showing up in the file list

### ISSUE THREAD

**Issue by 4163** [nicotine-plus/nicotine-plus#3204]
Nicotine+ version:  Nicotine+ 3.3.6
Operating System/Distribution: Windows 10

### Describe the bug
Folder names or files starting with dots '.' does not show up in the file list

### Expected behavior
Names starting with dots '.' should show up in the file list. Or at least the user should be able to specify that the folders they are sharing starts with dots '.'. I understand that directories that start with dots are usually hidden in a various applications and even system files. But this prevents people on windows (me, not sure how frequent people use folder naming structure like this) from being able to share my files without having to change the way I structure my folders.

### Steps to reproduce the bug
Share either a folder or files with the naming convention of having a dot at the start of the name '.'.
Example:
Folder: .J-Pop
File: .Track-1.flac

### Additional context
![directory](https://github.com/user-attachments/assets/b6877401-21f5-4186-b200-afd2d5e097d2)
![filelist](https://github.com/user-attachments/assets/5631dff5-99b5-477f-be08-cf3969c1c750)

In this case folders, .Anime, .Contributions, .Other Sources, .PVs, .TV-Music, .YouTube and file .IMG_20151208_0001.jpg, does not appear on the Nicotine+ client.

**Comment by slook** [comment]
This is intended behaviour for dotfiles which are hidden on most other filesystems.

For sorting purposes it is more conventional to use something like an underscore `_` for items you want listed at the top.
