### ISSUE TITLE
Deleted folder downloads return after deletion, 1 by 1

### ISSUE THREAD

**Issue by majkinetor** [nicotine-plus/nicotine-plus#3208]
Nicotine+ version:  3.3.6
Operating System/Distribution: Windows10

### Describe the bug

I start download of some folder with music. I delete downloads. Then folder comes back, 1 file at a time. As soon as I delete it, the next one from that folder appears. Restarting the app doesn't help. This bug happens in multiple versions

![image](https://github.com/user-attachments/assets/c6117061-de8c-446f-ac48-f3541d8d525a)

![image](https://github.com/user-attachments/assets/d64d6e77-ca42-4390-84e1-24ff84ef1987)

**Comment by slook** [comment]
Does it occur with only this particular user, or may it also happen with others too?

**Comment by majkinetor** [comment]
Any user.

**Comment by majkinetor** [comment]
Notice that I delete downloads while they are still being downloaded. Otherwise, if fully downloaded, they don't come back.

**Comment by slook** [comment]
What about deleting after being paused.

**Comment by mathiascode** [comment]
In Preferences -> Downloads, either disable the "Allow users to send you any files" option, or restrict it to a smaller group of users.

**Comment by slook** [comment]
I notice that no `status` is set when clearing a download...

https://github.com/nicotine-plus/nicotine-plus/blob/892e7c4dbbeb74d5cdf5316b95d8f9c4a5dff053/pynicotine/transfers.py#L483-L484

Perhaps it should be set to something like `TransferStatus.CANCELLED` or maybe aborting `TransferStatus.PAUSED` before clearing might help to avoid this problem.

**Comment by majkinetor** [comment]
> In Preferences -> Downloads, either disable the "Allow users to send you any files" option, or restrict it to a smaller group of users.

I did this, so now we will see. However, I am pretty certain people are not sending me files in this amount. Especially as it can happen seconds after I start and remove downloads

**Comment by slook** [comment]
It is not a manual request by them to send you files, but their automatically client falls back by default to pushing the files to you via this method in case the normal way was interrupted for any reason (unfortunately including if you cancelled it on purpose).

**Comment by slook** [comment]
Duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2568

**Comment by majkinetor** [comment]
> It is not a manual request by them to send you files, but their automatically client falls back by default to pushing the files to you via this method in case the normal way was interrupted for any re

The option doesn't make sense as its named "Allow users to send you any files" so it implies direct action.

**Comment by majkinetor** [comment]
Also, files appear 1 by 1. So if I deleted 10 files, it will return 1 of them, download it, then the next one will appear. In automatic case would expect all files to appear ASAP.

**Comment by slook** [comment]
The feature is intended to allow a remote user to manually push file(s) to you. However, due to fundamental design flaw in the protocol it is unintentionally triggered from the uploader's Upload queue (hence, why the files re-appear 1 by 1).

For this reason the feature was apparently removed from the official client. In Nicotine+, it is now disabled by default, and if enabled it is set to "Trusted Buddies" in order to limit the effect of the problem.

Proper mitigation for the issue would require an elaborate mechanism to track deleted downloads in order to send rejections to abort at the moment when the uploader actually begins each transfer.

**Comment by majkinetor** [comment]
OK, thanks a lot for detailed explanation.
