### ISSUE TITLE
Nicotine+ not working on Windows 10 since v3.3.6

### ISSUE THREAD

**Issue by dingeling** [nicotine-plus/nicotine-plus#3210]
Nicotine+ version:  3.3.6 + latest testing
Operating System/Distribution: Windows 10 Pro, 22H2, 19045.5011

### Describe the bug
Nicotine+ fails to start with errors. Failure came with v3.3.6 and still exists in latest testing.
v3.3.5 runs fine.

### Expected behavior
Starting.

### Steps to reproduce the bug
Start Nicotine+.

### Additional context
![Screenshot 2024-12-02 104116](https://github.com/user-attachments/assets/087bc5f3-fe88-4f21-8ef7-d46c11a026fd)
![Screenshot 2024-12-02 104126](https://github.com/user-attachments/assets/2a837b57-124c-4004-a6f9-6501c22bdace)

**Comment by slook** [comment]
Until this is fixed, don't use 3.3.5 because it has a severe bug in it, use [3.3.4](https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.3.4) instead.

**Comment by dingeling** [comment]
The screenshots were made from an installed latest testing. I cannot find a specific 3.3.7rc1 version. But latest testing installs 3.3.7rc1:
![Screenshot 2024-12-02 115513](https://github.com/user-attachments/assets/efe8244f-6cc6-40df-9e23-dc09e25334f4)

**Comment by slook** [comment]
Does the "libgtk-4-1.dll" file exist with the "lib" folder, or can it be found somewhere else or named slightly differently?

**Comment by dingeling** [comment]
The file exists and it's the only one on this system. So i think it's the one which gets loaded by Nicotine+:

![Screenshot 2024-12-02 120528](https://github.com/user-attachments/assets/6ed362e8-902e-45e8-bc62-4320dedbac07)

**Comment by slook** [comment]
Similar to fixed issue #3167

**Comment by slook** [comment]
@dingeling Please try the latest build of 3.3.7rc1, is the error is gone or different?

**Comment by dingeling** [comment]
Just tried. The only difference is the line number changed in `pynicotine/gtkgui/__init__.py` from 140 to 141. The missing procedure call is the same:

![Screenshot 2024-12-03 082548](https://github.com/user-attachments/assets/e07d470c-ed31-40f1-81a3-0a10e0176045)

**Comment by mathiascode** [comment]
Any luck with any of these builds?
https://github.com/mathiascode/nicotine-plus/actions/runs/12146988749
https://github.com/mathiascode/nicotine-plus/actions/runs/12147015316

Scroll to the bottom for download links.

**Comment by dingeling** [comment]
The second one is running!

This is the trace from the first one:

![Screenshot 2024-12-04 082827](https://github.com/user-attachments/assets/a303b8be-7ae6-48b5-97b6-fdc7fbda5dcb)

**Comment by mathiascode** [comment]
@dingeling Can you verify that the latest build here still works (I bumped the GTK version to the last one that should work)? https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by dingeling** [comment]
it's working! thanks.

**Comment by mathiascode** [comment]
@dingeling Does the following build work on your system (download links at the bottom of the page)? https://github.com/mathiascode/nicotine-plus/actions/runs/12456075171

I'm trying to see if I can fix the issue for good without resorting to downgrading GTK.

**Comment by dingeling** [comment]
It's still working.

**Comment by mathiascode** [comment]
Please also try this build: https://github.com/mathiascode/nicotine-plus/actions/runs/12469556521

**Comment by dingeling** [comment]
https://github.com/mathiascode/nicotine-plus/actions/runs/12469556521 isn't working:

![image](https://github.com/user-attachments/assets/b70c175b-379f-494e-a471-6dbfae90b157)
![image](https://github.com/user-attachments/assets/89167ec1-f298-41e6-8156-bd328c876e9e)

**Comment by dingeling** [comment]
https://github.com/mathiascode/nicotine-plus/actions/runs/12469110722

works!
