### ISSUE TITLE
Nicotine+ UPnP Error

### ISSUE THREAD

**Issue by popcorn2024ok** [nicotine-plus/nicotine-plus#3213]
![IMG_0135](https://github.com/user-attachments/assets/2d15168f-e7ff-4ff8-93af-d5dd6331d816)

I get this problem Nicotine+ is there a solution to this error and problem I have version 3.3.6 of Nicotine+ UPnP Error

**Comment by toineenzo** [comment]
Do you have any UPnP devices in your network? If not, this error shouldn't be a problem.
