### ISSUE TITLE
Investigate "broken" user share

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#323]
Nicotine+ doesn't like the shared files of user "kytsyk".
```
Peer message type 2068977581 size -319834151 contents 
b'' unknown
```

**Comment by hboetes** [comment]
I can't reproduce this.

**Comment by mathiascode** [comment]
Hm, so you're able to browse the shares of this user just fine? Maybe some kind of block...

**Comment by hboetes** [comment]
I just downloaded some files from him. Looks like a pretty normal share to me.

**Comment by hboetes** [comment]
Although I did get this mysterious message in the log.

```
20:22:54 Peer message type 2068977581 size -319834151 contents 
b'' unknown, from user: kytsyk, unknown:unknown
```

**Comment by hboetes** [comment]
Mind you, that message appeared about an hour after I downloaded files from him.

**Comment by hboetes** [comment]
And there's another one:

```
19:42:29 Rescanning finished
20:09:39 Peer message type 2068977581 size -319834151 contents 
b'' unknown, from user: kytsyk, unknown:unknown
```

**Comment by kiplingw** [comment]
Maybe it's just an NOP ping.

**Comment by mathiascode** [comment]
Looks like this is unrelated to the user share, just my firewalled connection that didn't allow me to browse it. Not sure if we can do anything about these messages, but at least they don't affect functionality.
