### ISSUE TITLE
"Cannot find the pynicotine module" error message

### ISSUE THREAD

**Issue by dmitrykvasnikov** [nicotine-plus/nicotine-plus#3234]
Nicotine+ version:  
Operating System/Distribution:
Arch (vanilla), 6.12.6-1

### Describe the bug
Nicotine doesn't launch, error message in console:
**_Cannot find the pynicotine module.
Perhaps it is installed in a folder which is not in Python's module search
path. There could be a version mismatch between the Python version that was
used to build the application binary package and the version you try to run
the application with._**

### Expected behavior
Start of the program

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Did you install the nicotine+ Arch package? Is the system up to date?

**Comment by dmitrykvasnikov** [comment]
> Did you install the nicotine+ Arch package? Is the system up to date?

I installed nicotine+, it replaced prevously installed (and worked till today) nicotin-git-plus, and everything is working now. Thank!!!
