### ISSUE TITLE
Connection issues after search

### ISSUE THREAD

**Issue by zalloy** [Nicotine-Plus/nicotine-plus#329]
Nicotine+ version:  1.4.3 unstable branch
Operating System/Distribution: Kubuntu 20.04 (Focal)

Description: After searching for files and adding to my Download queue, the log window at the bottom is spammed with messages, and any downloads in progress change to "Cannot Connect". Clicking "Retry" for these failed downloads gives the same result. Downloads continue after restarting Nicotine+, as long as the user is still online.

Expected Behavior: After searching for files and adding them to the Download queue, files in the queue should be downloaded without messages being spammed to the log window. Retrying failed downloads should result in the files being downloaded unless the user is offline or files are no longer shared. 

Steps to Reproduce: 

1. Open Nicotine+ and connect to the network.
2. Search for an album or artist in the Search tab.
3. Choose some files to download, and select a download location.
4. Go to the Downloads tab. You will see that any downloads you had in progress are now showing "Cannot Connect" and you will see messages spamming in the log window, at the bottom. Clicking "Retry" for those downloads shows an attempt at reconnecting, but the status will return to "Cannot Connect".
5. Restart Nicotine+. You will then see the failed downloads resume as normal.

Additional Context:
[Screenshot](https://www.dropbox.com/s/h261obsjhzwp5cu/Selection_570.png?dl=0)

**Comment by mathiascode** [comment]
I have no idea why certain users send messages of type 12547, as I've found no documentation about it. This message has been in the ignore list for Nicotine+ since at least 2006, but I briefly removed it when I thought it was unused. It is added back in https://github.com/Nicotine-Plus/nicotine-plus/pull/327.

**Comment by mathiascode** [comment]
Can you test the latest changes in the master branch?

**Comment by zalloy** [comment]
I think that did the trick. No longer seeing those messages, and downloads are working fine now.
