### ISSUE TITLE
Window decorator close button doesn't work

### ISSUE THREAD

**Issue by kiplingw** [Nicotine-Plus/nicotine-plus#330]
I am using git HEAD. When I first open Nicotine+ it opens maximized. If I click the window decorator's close button it disappears to my system tray as expected. If I click on the system tray icon and select Hide / Show Nicotine+ once nothing happens. If I do this again it appears maximized. But when I then click the close button on the window decorator nothing happens. I can, however, minimize to tray by using the tray icon's menu again.

**Comment by mathiascode** [comment]
I can reproduce the issue, will check what's going on.
