### ISSUE TITLE
Question: group by folders vs group by users 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#335]
the new feature is nice but instead of replacement can we hav the choice to use this one ? 
im much acclimated to group by users display
maybe this new feature is not mature enough to be the only way displaying list ? 

sorry it's not a real complain but a kind a feature request

**Comment by mathiascode** [comment]
I'll check if it's feasible to add the old feature back.

**Comment by zniavre** [comment]
some information to not be considered negative guy : 
1/ it missing on empty line general information > 
![Capture d’écran du 2020-06-29 11-47-38](https://user-images.githubusercontent.com/2409578/86262787-a126a200-bbc0-11ea-8455-507e7030641f.png)

2/ with upload tabs im experiencing strange behavior please let me  show you with 4 screenshots 
![Capture d’écran du 2020-07-01 17-28-21](https://user-images.githubusercontent.com/2409578/86262981-da5f1200-bbc0-11ea-9066-fc9225637e4f.png)
![Capture d’écran du 2020-07-01 17-28-30](https://user-images.githubusercontent.com/2409578/86262987-dc28d580-bbc0-11ea-8a5e-6da2797ebe9d.png)
![Capture d’écran du 2020-07-01 17-28-41](https://user-images.githubusercontent.com/2409578/86262993-dd5a0280-bbc0-11ea-92f9-2aaf884b6cd3.png)
![Capture d’écran du 2020-07-01 17-28-55](https://user-images.githubusercontent.com/2409578/86263000-dfbc5c80-bbc0-11ea-8551-72ad7688ea52.png)

2 users but only one grouping ( you can see how better are screenshot than my explaination)  

hav a nice day; be good and well 

><((((*>

**Comment by mathiascode** [comment]
Regarding the second issue (wrong user grouping), it was fixed in https://github.com/Nicotine-Plus/nicotine-plus/pull/339.

As for the first issue, I left the user rows empty due to performance reasons, but there is probably some reasonable way the row info can be brought back.

**Comment by mathiascode** [comment]
The user row info issue is resolved in PR https://github.com/Nicotine-Plus/nicotine-plus/pull/337

**Comment by zniavre** [comment]
Thank you !! well done

**Comment by mathiascode** [comment]
You're welcome! :)
