### ISSUE TITLE
Downloads tab hanging when adding a lot of files

### ISSUE THREAD

**Issue by gfarmerfr** [Nicotine-Plus/nicotine-plus#34]
Extracted from https://github.com/Nicotine-Plus/nicotine-plus/issues/32

When you have a lot (about 3000 or more) files added to download, the program hangs for several seconds when doing anything, if the Downloads tab is visible. I suspect that it is trying to sort every item each tick of the GUI main loop.

**Comment by mathiascode** [comment]
In addition to already added downloads, adding a lot of new downloads also lags the program hard, since the transfers file is opened and closed for every new transfer.

**Comment by mathiascode** [comment]
I almost have a solution ready for this issue.

**Comment by mathiascode** [comment]
There was a quite severe bug in the current code. When asking the server for a user's IP address, we did this for every download in the transfer list instead of once, resulting in some nasty connection spam.
