### ISSUE TITLE
Exception during parsing FolderContentsResponse: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#342]
Whilst trying to download a folder from a certain user I got this message: `10:23:43 Exception during parsing FolderContentsResponse: unpack requires a buffer of 4 bytes`

Repeated attempts to get the folder gave the same result.

Found with user: `fidtheforce`  whilst searching for `Jay-Z The Blueprint`

**Comment by hboetes** [comment]
Oh, that also triggered this message from the user:

`[Automatic Message] Please try browsing me if you get 'File not shared' errors. You don't have to reply to this message.`

I'll ask him how he did that.

**Comment by zniavre** [comment]
it is not the away mode auto-reply ? i guess i got this message too

**Comment by hboetes** [comment]
Hmmm but how did he set it so that I have to browse his files before being able to download them?

**Comment by lene** [comment]
I think you misunderstand it. I've been getting this message all the time, for years, and I hardly ever need to browse the users' files, they usually download without problems. I interpret that message as "My client is buggy, it sometimes shows File not shared, and you can get around this bug by browsing my files".

**Comment by hboetes** [comment]
OK, that makes perfect sense.

**Comment by mathiascode** [comment]
After some light digging, the FolderContentsResponse from the user seemed incorrect somehow.

**Comment by mathiascode** [comment]
Probably someone using Nicotine+ 1.2.16. If only that version had died out by now... https://github.com/Nicotine-Plus/nicotine-plus/commit/557822dc5bd241be0612d799805372d486ccc56a
