### ISSUE TITLE
expand/collapse all missing in upload tab 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#354]
in upload tab the expand/collapse all (list)  button is missing maybe it's normal causes by coding details or maybe you forgot it ( wich is also normal causes by number of code line you did until now .

hav a nice day

**Comment by mathiascode** [comment]
Oops, looks like the logic was swapped there. Thanks for noticing!

**Comment by dchmelik** [comment]
This should be a permanent option in the download & upload tabs.

**Comment by slook** [comment]
In the latest unstable 3.3.0.dev the button toggle does seem to be remembered. Please do try it @dchmelik see link:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by dchmelik** [comment]
Good to know, but after much bad experience, I generally avoid development/testing/unstable over long-term/stable/user versions, because often some 'commit' introduced bugs critically worse than minor ones people said 'upgrade' to fix.  If I could know if testing v3.3.0.dev won't break my configuration/profile to not work with 3.2.9, I'll test v3.3.0.dev.

**Comment by mathiascode** [comment]
@dchmelik The behavior should be the same in 3.2.9, see my comment: https://github.com/nicotine-plus/nicotine-plus/issues/981#issuecomment-1860572457

If the current behavior is not enough, can you explain how you would like it to be?

**Comment by slook** [comment]
> If I could know if testing v3.3.0.dev won't break my configuration/profile to not work with 3.2.9, I'll test v3.3.0.dev.

There are currently no known backwards-compatibility issues. A lot of care does go into avoiding config breakages before any PRs are merged or commits are pushed to master.

**Comment by dchmelik** [comment]
Oh, I see; it's already there: had no idea an arrow stood for collapse/expand (doesn't seem that clear like some text buttons).
