### ISSUE TITLE
remove filtered files when autoremoving

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#374]
I noticed when having auto-remove enabled the filtered files have to be removed manually.

Could you add filtered files to the auto-removed files? I guess after all other files have been downloaded would be best.

**Comment by mathiascode** [comment]
Would it be fine if they're removed immediately? Keeping track of when an album has downloaded would probably add needless complexity.

**Comment by hboetes** [comment]
Sure, it's your call. I'm just giving my 2 cents.
