### ISSUE TITLE
Where can I find the previous version?

### ISSUE THREAD

**Issue by CHJ85** [Nicotine-Plus/nicotine-plus#382]
Hi there. Everything worked until I upgraded to the latest version 1.4.3.
On this new version, I get very few search results and the tabs (speed, size, filename etc) are all messed up.
So do you happen to have the deb file for 20.04 still? That's be great.
Looked in the unstable PPA and the stable one. The stable PPA doesn't have the latest Ubuntu for some reason, so no luck there either.

**Comment by mathiascode** [comment]
What version did you upgrade from (approximately when did you install it)? The only version we've provided for Ubuntu 20.04 so far is an unstable development version (always 1.4.3) which will soon become 2.0.0. Does resetting the config file make any difference?

**Comment by mathiascode** [comment]
I attempted to upgrade from 1.4.1 and an early May build of 1.4.3 to the latest unstable PPA version, and everything still looked and worked fine. Are you sure that the few search results are not a result of the new folder grouping feature (can be disabled on the search page)? The number of visible search results was bumped from 500 to 1000 as a result, but this won't apply automatically if you're using an old config file. It can be changed in Settings -> Misc -> Searches.

**Comment by hboetes** [comment]
@CHJ85 a shipload of improvements have been applied. Please try and bite the bullet, take some drastic steps to fix your issues and enjoy the new version. How much work would it be to start from scratch? Consider moving your `.config/nicotine` and `.local/share/nicotine` out of the way and run the new version.

**Comment by kiplingw** [comment]
That actually reminds me. We should make sure migration from whatever distro stable is out there to our 2.0.0 series is painless. There will likely be problems otherwise with pickle DBs and such.

**Comment by mathiascode** [comment]
1.4.1 to 2.0.0 is fine, pickle DBs use different file names and will be regenerated in any case. Migrating them is not worth it.

1.2.16 to 2.0.0 is something I haven't tested yet. Fun 10 year gap there.

**Comment by kiplingw** [comment]
Yeah if the share pickle DBs need to be regenerated, that's trivial. Main issue is really just user config settings. If that's fine then we don't have any problem.

**Comment by mathiascode** [comment]
The config migrates fine from 1.4.1 to 2.0.0, and judging by previous config migration code, a jump from 1.2.16 should probably be fine too. Just need to confirm this before release.

**Comment by CHJ85** [comment]
Not sure what the previous version was.
Installed and upgraded from the unstable PPA.
And I should mention, I removed the config files and started from scratch already.
@hboetes you're right. I appreciate all you guys' hard work. It's just that certain things don't work as they used to. For instance, I can no longer sort by file size and there's a tree view from download speed now. Would be nice if I could disable that feature.

**Comment by mathiascode** [comment]
The old view, as well as grouping by user, is available under the "Group by folder" dropdown.
![ss](https://user-images.githubusercontent.com/8754153/87113242-7bf7fa80-c276-11ea-9b7c-1217499a82ff.png)

**Comment by CHJ85** [comment]
Thanks @mathiascode. Is there a way I can get rid of that tree view thing with the spaces in between the files and get it to look exactly like the old view?
I still prefer the previous version though if someone has the DEB package still.
Because like I said, I'm not getting as many results now and sort by size doesn't work.

**Comment by mathiascode** [comment]
Setting the dropdown shown in the screenshot to "No grouping" is supposed to get rid of the treeview and bring back the old list style, where sorting by size works. Doesn't this work on your end?

**Comment by CHJ85** [comment]
@mathiascode It did. Thank you.

**Comment by mathiascode** [comment]
:)

Are there still issues with fewer results, or can this issue be closed?

**Comment by CHJ85** [comment]
Yea I believe this issue can be closed now.
Again. Thanks for all your help. 😀

**Comment by Rahinebezzy** [comment]
> Yea I believe this issue can be closed now.
> Again. Thanks for all your help. 😀

hey iv been looking for you can i get a link to animax asia iptv or japan or both
