### ISSUE TITLE
Please put whole search string after/before "results: x/y"

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#383]
The first chars of a search string are on top of the tab, but often I wonder what I actually searched for and how I should improve the search, but I don't remember the exact search string since I can't see it any more.

Wouldn't it be nice if the complete original search string was behind, or before the "results: x/y" string?

Thanks for taking my request into consideration.

**Comment by mathiascode** [comment]
The full search string is visible when hovering over the tab, but the window title could probably be utilized to show the whole string too. My largest concern with the old string placement is that the minimum window width becomes too large if the string is long. The button area is already a bit too crowded.

**Comment by hboetes** [comment]
Thanks for the tip. I never thought of that. Let's give it some thought, what would be a nice way to display it nicely.
