### ISSUE TITLE
Search log window case insensitive.

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#384]
Hello!

Would you consider making the search in the log window case-insensitive? Thanks.

Cheers!

**Comment by mathiascode** [comment]
Thanks, I wasn't aware it was case-sensitive. Should be a trivial change.

**Comment by hboetes** [comment]
I just stumbled upon it when trying to find something. Pure luck.

**Comment by hboetes** [comment]
Works as expected! Thanks.
