### ISSUE TITLE
replace log search function with search/filter thingybob, send logs to logfile.

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#387]
This is for after 2.0.0

- Please replace the search function in the log window with a search/filter. This would make inspecting the logs a lot easier.
- Perhaps consider sending the (debug)logs to a logfile.

**Comment by mathiascode** [comment]
Can you link some screenshots or examples of ideal implementations?

**Comment by hboetes** [comment]
Ideal... That's hard to obtain. :-)

```
debug output: Warnings ☑ Search Results ☑ Connections ☑ Messages ☑ Transfers ☑ Statistics ☑ Log ☑ Filter [                    ]

Something like that?
