### ISSUE TITLE
Configure - Directories Page 4 of 5

### ISSUE THREAD

**Issue by Geyup** [Nicotine-Plus/nicotine-plus#39]
I'm using Slackware 14.2 x86_64 with python-2.7.13.

This issue is with 1.4.0

When I start Nicotine for the first time with the configure window, under the ```Directories Page 4 of 5``` section, ```Share the following directories``` when I clicked ```Add``` it then gave me another popup window asking to type a name of the vitual directory, but I could not type anything in it, and then when I tried to close it, clicking the ok or cancel button nothing happened.

So then I closed nicotine, reopened it and then this time to get the ```Forward``` button to appear I just clicked ```Remove```, now the ```Forward``` appeared...

So for now can't add a directory to share... hmm

Please see the attached screen shot of this section that won't let me type anything, and can't close either.

![nic-plus](https://cloud.githubusercontent.com/assets/13072581/22495041/bf473c26-e834-11e6-8a12-878a7a9b75fb.jpg)

**Comment by gfarmerfr** [comment]
Hi @Geyup,

Good catch I overlooked this one.
I've fixed it in my develop branch of my own repo.

I'll pill up a few more fixes for your other gh issues before releasing 1.4.1 as a stable branch fix.

**Comment by Geyup** [comment]
Sounds good...

Thanks
