### ISSUE TITLE
upnp does not seem to work 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#396]
Nicotine+ version:  2.0.0
Operating System/Distribution:ubuntu 20.04

### Describe the bug
test port closed , before it was working well but without changing anything now it's closed
no output even with terminal sorry 
i do not know how to give you information

**Comment by zniavre** [comment]
i just saw the closed bug for gentoo upnp i tried the command you gives to debug it maybe it will be usefull for you 


'zniavre@zniavre:~/Desktop$  upnpc -l
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
Connection Type : IP_Routed
Status : Connected, uptime=668431s, LastConnectionError : ERROR_NONE
  Time started : Tue Jul  7 14:51:41 2020
MaxBitRateDown : 25000000 bps (25.0 Mbps)   MaxBitRateUp 1000000 bps (1.0 Mbps)
ExternalIPAddress = 91.161.69.196
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
 0 TCP 15000->192.168.0.9:2234  'Nicotine+' '' 0
 1 TCP 15001->192.168.0.9:15000 'Nicotine+' '' 0
GetGenericPortMappingEntry() returned 713 (SpecifiedArrayIndexInvalid)
zniavre@zniavre:~/Desktop$ upnpc -e Nicotine+ -a 127.0.0.1 2416 15000 TCP
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
ExternalIPAddress = 91.161.69.196
AddPortMapping(15000, 2416, 127.0.0.1) failed with code 402 (Invalid Args)
zniavre@zniavre:~/Desktop$  upnpc -e Nicotine+ -a 127.0.0.1 2416 2416 TCP
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
ExternalIPAddress = 91.161.69.196
AddPortMapping(2416, 2416, 127.0.0.1) failed with code 402 (Invalid Args)
zniavre@zniavre:~/Desktop$  upnpc -e Nicotine+ -r 2416 15000 TCP
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
ExternalIPAddress = 91.161.69.196
InternalIP:Port = 192.168.0.9:2416
external 91.161.69.196:15000 TCP is redirected to internal 192.168.0.9:2416 (duration=0)
zniavre@zniavre:~/Desktop$ upnpc -N 0 15000 tcp
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
UPNP_DeletePortMappingRange() failed with code : 401
zniavre@zniavre:~/Desktop$ upnpc -e Nicotine+ -a 192.168.1.109 2416 15000 TCP
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
ExternalIPAddress = 91.161.69.196
AddPortMapping(15000, 2416, 192.168.1.109) failed with code 402 (Invalid Args)
zniavre@zniavre:~/Desktop$ upnpc -e Nicotine+ -a 192.168.1.109 2416 15000 TCP
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.0.9
ExternalIPAddress = 91.161.69.196
AddPortMapping(15000, 2416, 192.168.1.109) failed with code 402 (Invalid Args)
zniavre@zniavre:~/Desktop$ 
`

**Comment by mathiascode** [comment]
Any output in the log window? UPnP now forwards the same port as the main listening port, instead of 15000.

If nothing else works, could you try removing existing port mappings with `upnpc -N 0 15001 tcp`, and open Nicotine+ again?

**Comment by zniavre** [comment]
same my port stays closed ... i ll try to set via router, but later, kids first .
thank you answering fast

**Comment by mathiascode** [comment]
I suppose it's because external port 15000 didn't point to the corresponding internal port anymore, but I'm not entirely sure. Let's hope this is an isolated case.
