### ISSUE TITLE
Configure - Username

### ISSUE THREAD

**Issue by Geyup** [Nicotine-Plus/nicotine-plus#40]
I'm using Slackware 14.2 x86_64 with python-2.7.13.

This issue is with 1.4.0

I use KeePassX to create nice long mixed character passwords, so I type in the username, but I copy and paste a password, and I noticed if I copy and paste the password, I have to backspace to remove one character in order for the ```Forward``` button to appear...

The only way this is working is if I copy and paste in the password first, then type in the username, or if I just typed in a password...

If I type in a username and then copy and paste the password the ```Forward``` button is greyed out...

Hmm odd

**Comment by bernd-wechner** [comment]
I've had a similar problem in other contexts, and I'd suspect KeePassX here. Try pasting the password into a simple text editor in which you can see or check for spaces easily. You might find it's pasted your password and one extra space. I've certainly found similar in various contexts with password copy/pasting alas. Never spent the time to diagnose fully in any context, but my first suspect is the source, if that is what's happening.

**Comment by Geyup** [comment]
No this is not the problem, I open up KeepPassX and go to the section I have for nicotine and open it, then I view the password and copy and paste it with the keyboard keys ctrl c & ctrl v

I can also just copy out the password and put it in a text file, open it, then copy from there and paste into nicotine and the same thing...

This is a bug in the configure setup...

**Comment by bernd-wechner** [comment]
Insufficient evidence alas. IN my case it most definitely has been a space at end and it would have passed those tests. Views fine. CTRL+C and CTRL+V into text file looks fine, CTRL+C and CTRL+V from theere to elsewhere all fine etc. But login rejected. 

Not saying that is the problem, just that you haven't provided enough evidence to conclude it isn't, that's all. As I said, paste into an empty text file in an editor you trust and can see or test for spaces in, and then physically check if a space is being copied at end of password. That is how to gain evidence that this is the problem or not.

Could be something else altogether of course, just saying how you can really check whether or not this is the problem.  But I may have misunderstood, maybe you did check for a space at end of the copied text in an editor you trust and know how to use to see or find spaces.

**Comment by Geyup** [comment]
I said before that if I copy and paste the password first, then add in the username it works.

So this makes no sense by changing the order it works, but since I'm assuming LOL, we all read from left to right, the logic is to put in the user first then the password,. and in this order it does not work...

This seems like a bug to me, works one way and doesn't the other...

**Comment by bernd-wechner** [comment]
Sorry if I misunderstood. Clearly is off if order is the only variable that makes a difference and suggests some esoteric feature, er bug, pending I guess reproducibility by a dev.

**Comment by Geyup** [comment]
Hey no problems thanks for the help, much appreciated...

It's a small thing, but I thought to report it anyways...

Cheers

**Comment by gfarmerfr** [comment]
Hi @Geyup @bernd-wechner,

It was a little tricky to understand what was going on but I think I fixed it in my own repo develop branch.
I'll test it further tomorrow.

**Comment by Geyup** [comment]
Sounds good...

thanks
