### ISSUE TITLE
proxy settings

### ISSUE THREAD

**Issue by danrobi11** [nicotine-plus/nicotine-plus#400]
Hello 
Running new 2.0.0 flatpak version
Why theres no proxy settings?
This is a file-sharing app, it needs proxy settings!

**Comment by mathiascode** [comment]
I don't think this is something we want to support inside Nicotine+ itself, since (to my knowledge) SOCKS5 does not support port forwarding. A VPN that supports port forwarding is recommended: https://www.reddit.com/r/VPNTorrents/comments/oqnnrq/list_of_vpns_that_allow_portforwarding_2021/
