### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by MitraMai** [Nicotine-Plus/nicotine-plus#401]
No bug, just want to say THANK YOU SO MUCH for the work you have put into crushing bugs and improving Nicotine+ !!! Today when I updated my system I got so happy to see the new version, ported to GTK3 and all!

So, again, thank you so much!

**Comment by mathiascode** [comment]
Thank you for your kind words, it means a lot!

**Comment by zniavre** [comment]
adding my THANK YOU !!! congrats for 2.0.0, a small step for user a huge gap for humanity ( or not)  anyway that is really nice.hav a good day best regards all of you devs  :o)

**Comment by hboetes** [comment]
I'm also very grateful. I've reported quite a few bugs and feature requests, and they were all fixed and applied in a very short time. It was an amazing experience.

**Comment by haggletonpie** [comment]
hear hear. i actually said 'oh my god' out loud when I saw the release notes/change log.

huge thanks for a huge contribution.

(fatgas)

**Comment by pizzadude** [comment]
Thanks for the flatpak version!

**Comment by zniavre** [comment]
leave this one open please !  i know you do not like ticket number but this one is special no ?

**Comment by misterhat** [comment]
I thought the project was almost dead, updated from 1.4.1 to 2.0.1 and was also really surprised. Great job on this!

**Comment by gahag** [comment]
Great job on the GTK3 update!

**Comment by daks** [comment]
One more to thank you for the job recently done :) I recently upgraded and even if it emptied my download list I'm happy to see this software been worked on.

**Comment by mathiascode** [comment]
I think this issue has served its purpose. Thank you everyone!
