### ISSUE TITLE
1.4.0 Text Off Set Under Columns

### ISSUE THREAD

**Issue by Geyup** [Nicotine-Plus/nicotine-plus#41]
I'm using Slackware 14.2 x86_64 with python-2.7.13.

I noticed under the ```Search``` and ```Downloads``` sections text is offset, meaning, for the given section text is not appearing directly underneath the section aligned under the first letter as some of the sections are.

```Size``` under the ```Search Files``` the text is located more to the right, and right next to the text for ```Speed```. The numbers should appear under the S, appearing as an example like below;

Size
9.5MB

```In queue```  under the ```Search Files``` the text is also located more to the right, and right next to the text for ```Immediate Download```

Same thing, text, the numbers for ```In queue``` don't appear lined up under the letter ```I``` as they should like below;

In queue
20

```Length``` section the numbers are off set to the right and not appearing under, the letter ```L``` lined up like below as example;

Length
3:59

Please see the attached screen shot for what I mean.

It would be nice to have separation of the text, like how the other sections all appear. Not sure why these sections are like this, hmm...

![nic](https://cloud.githubusercontent.com/assets/13072581/22495699/e95ad0da-e83a-11e6-975d-ff6c1b4e3b57.jpg)

Thanks

**Comment by Geyup** [comment]
Forgot to add in, for the ```Downloads``` section the ```Queue Position``` and ```Size``` are what appear off for me...

Thanks

**Comment by gfarmerfr** [comment]
Hi @Geyup,

Yes I think setting every columns "left align" should result in a more consistent UI.
It should not be too difficult to do (don't quote me on that :D) and I'll try to see how it looks and report back.

**Comment by gfarmerfr** [comment]
I've pushed this tweaking in the develop branch of my own repo: https://github.com/gfarmerfr/nicotine-plus/tree/develop.
Could you check it out to see how it looks like ?
I think it's a little bit better, but taste and colours... :)

**Comment by Geyup** [comment]
YEAH it's working nice, everything aligned to the left... :)

Can fonts or themes have an effect on this, I would think not, but I can test if you like?

THANKS gfarmerfr keep up the great work!

**Comment by gfarmerfr** [comment]
Yes I would appreciate if you found out if themes would influence this. I don't this they would mess with gtk cell alignment but we never know. At least on the 2-3 themes I have on Gnome 3 I don't see any difference.

**Comment by Geyup** [comment]
Ok will let know...

thanks
