### ISSUE TITLE
"Fatal error detected" when trying to run Nicotine on Windows 10

### ISSUE THREAD

**Issue by sbstn87** [Nicotine-Plus/nicotine-plus#413]
Nicotine+ version:  2.0.1
Operating System/Distribution: Windows 10

### Describe the bug
Nicotine does not start, the dialog window appears: Fatal error detected. Failed to execute script nicotine.

### Expected behavior
The error above should not appear.

### Steps to reproduce the bug
Just install and run Nicotine 2.0.1 on Windows 10.

### Additional context
![Nicotine+_2020-07-20_16-39-37](https://user-images.githubusercontent.com/37237675/87950790-45508a00-ca97-11ea-9c64-ca983df03bc6.png)

**Comment by mathiascode** [comment]
Can you try the updated installers? They should fix the issue. https://github.com/Nicotine-Plus/nicotine-plus/releases

**Comment by sbstn87** [comment]
The updated installer has fixed the issue. Thanks!
