### ISSUE TITLE
RAM usage 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#416]
Nicotine+ version:  2.0.1
Operating System/Distribution: 20.04

### Describe the bug
after 5 days nicotine runing, RAM is at 544mo 

### Expected behavior
less usage 

### Steps to reproduce the bug
running 7/7 

### Additional context
Screenshots 
![Capture d’écran du 2020-07-21 23-54-51](https://user-images.githubusercontent.com/2409578/88111267-e6c9ff80-cbad-11ea-95e9-163271e23000.png)

**Comment by mathiascode** [comment]
What was the average memory usage on the Python 2 version of Nicotine+?

**Comment by zniavre** [comment]
for long time it was like around 75/100mo

**Comment by toofar** [comment]
Are you opposed to turning the "Autoclear finished/aborted" option on? If you just want to get stats about what you've been uploading you can turn on logging of transfers under Chat > Logging in the settings.
The uploads tab used to have terrible performance when it had man uploads (even finished ones). That improved drastically recently but I wouldn't be surprised if it were contributing.
Actually does just hitting "Clear Finished / Failed" and waiting a while for a GC run help?

**Comment by zniavre** [comment]
@toofar i can try for sure 
rendez vous in 5 days ...  !

**Comment by mathiascode** [comment]
If my understanding is correct, Python doesn't necessarily release memory back to the OS unless necessary, but reuses it when possible. Still, porting Nicotine+ to GTK 3 and Python 3 alone seems to have increased the memory usage after startup and in general, would be interesting to know exactly what uses it.

**Comment by mathiascode** [comment]
There seems to be a memory leak related to self.peerconns in pynicotine.py, connections don't seem to be removed from the list.

**Comment by mathiascode** [comment]
Less memory should now be used for actions related to file shares.

**Comment by mathiascode** [comment]
Incoming search requests should use a bit less memory now.

**Comment by mathiascode** [comment]
@zniavre Did things improve?

**Comment by zniavre** [comment]
for my previous wrong bug report an user told me to close the report.... i was thinking to do same for this one after you commented 11hours ago ... i just installed this morning last code im waiting next week to check ram usage
