### ISSUE TITLE
if no close button on tabs it's not possible to close User search file notebook

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#428]
title clear enough i think 
in contrario of  user browse tab there is a "close this tab" menu

**Comment by mathiascode** [comment]
What do you mean with "user search file notebook"? All notebook tabs I've found have a popup menu item to close them (except for the buddy list, but that's a different case handled in view -> buddylist hidden).

**Comment by zniavre** [comment]
sorry ( not sorry ) after a new update it does not happen anymore
maybe i updated too early in the night

sorry for that one ...   :o(

**Comment by mathiascode** [comment]
Reopen if it happens again.
