### ISSUE TITLE
notify sharelist is empty

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#434]
I sometimes notice after a few hours, usually because nobody downloads anything my shares are empty.

I don't know what caused that. That's interesting to know as well.

Would it be an idea to add the number of files and folders shared, perhaps in the bottom bar or a pop-up at start? Perhaps with a bright colour if it's 0?

Something like that?

**Comment by mathiascode** [comment]
What do you do once the shares disappear? Does a rescan repair Nicotine+?

**Comment by hboetes** [comment]
Yes, both a rescan and a rebuild(what's the difference?) work.

**Comment by mathiascode** [comment]
https://github.com/Nicotine-Plus/nicotine-plus/issues/430#issuecomment-663632509

**Comment by mathiascode** [comment]
The next time this happens, can you check what the file count/size is on your user info page, and perhaps check the size of the shares db file?

**Comment by hboetes** [comment]
Sure, will do.

**Comment by mathiascode** [comment]
Once https://github.com/Nicotine-Plus/nicotine-plus/pull/455 is merged, it would be interesting to see if this still happens.

**Comment by hboetes** [comment]
Make sense indeed.

**Comment by mathiascode** [comment]
Any news regarding this issue?

**Comment by hboetes** [comment]
I've been looking for this problem to reappear, but it stubbornly doesn't. How annoying! Let's close it for now and if it does reappear, I'll let you know.
