### ISSUE TITLE
double click is received on selection despite being performed on blank space

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#437]
Nicotine+ version:  2.0.2-20200725221
Operating System/Distribution: KDE neon (Ubuntu 18.04 LTS)

### Describe the bug
if file is selected on download/upload list double clicking at empty space doesn't deselect it. double clicking empty place acts as if the file is clicked twice

### Expected behavior
selection vanishing

**Comment by mathiascode** [comment]
Is this standard behavior in any other program? Most programs I've used (including SoulseekQt) don't behave like this.

**Comment by alekksander** [comment]
no, it's only in nicotine. it wasn't an issue few updates back (don't know how many, i wasn't using, but was updating daily)

**Comment by mathiascode** [comment]
Hm, I tried replicating this behavior in 1.4.1, but it is the same as in 2.0.2.dev1 on my end.

**Comment by alekksander** [comment]
okay, it might be my setup as i'm experiencing some gtk bugs last few days. i'm closing for now and if this lasts after my environment is fixed will re–open.

**Comment by alekksander** [comment]
bug still present in 2.1.0-202009021733~ubuntu20.04.1

**Comment by mathiascode** [comment]
That version doesn't contain the changes yet. Generating a new daily build now.
