### ISSUE TITLE
align columns text to left, right or center

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#438]
### Describe the solution you'd like
we can already show/hide preferred columns, but we are unable to align their content to left, right or center it. that would be very useful for long path names – if we are interested more on the last directories instead of beginning of the path

### Additional context
as it shows more we narrow the column then lesser important information remains visible – aligning this column text to right edge will make last directories visible. right align filename column however could clear up visibility a bit, so text doesn't look merged together as one line of information
![image](https://user-images.githubusercontent.com/3148302/88724392-0f647300-d133-11ea-8fd5-392924979246.png)

**Comment by mathiascode** [comment]
SoulseekQt seems to display a reverse file path to mitigate the issue.

**Comment by alekksander** [comment]
i think „align to” would match with how customizable nicotine is, but both solutions are okay i guess

**Comment by mathiascode** [comment]
Could be worth exploring both options, but I'd prefer to avoid adding new options whenever possible. There are already too many things to keep track of.

**Comment by hboetes** [comment]
Another possibility: mc cuts out the middle so 

`Coronation Music For King James II - 01 - John Blow - God Spake Sometime in Visions.flac`

is displayed as:

`Coronation Music For King James~ Spake Sometime in Visions.flac`

**Comment by alekksander** [comment]
![Screenshot_2020 08 06_12:24:59](https://user-images.githubusercontent.com/3148302/89521482-42b89900-d7e8-11ea-82b8-01299427e94b.png)
was this the intention? it's even less readable in my setup

**Comment by mathiascode** [comment]
It's not supposed to be cut off at the beginning
