### ISSUE TITLE
Font worrie > 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#458]
Nicotine+ version:  2.1.0.dev1
Operating System/Distribution:20.04

### Describe the bug
i set font to Sans Regular 12 to Ubuntu Regular 11 but nic+ does not stuck this setup.

### Expected behavior
keeping setting all restart 

### Steps to reproduce the bug
start/restart

**Comment by hboetes** [comment]
Changing the font settings does make weird things happen indeed. It's hard to describe but I bet it's easy to reproduce.
