### ISSUE TITLE
Question : how to auto-join a room ? 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#464]
good morning since you deleted the "auto-join room" how to do it for new room we enter. One user created nicotine-dev room i tried to be in an after a nic+ restart it did not open as expected ...

for now only my private room and nicotine room are open at startup ( how to deactivate nicotine for example?)

**Comment by mathiascode** [comment]
![auto-join](https://user-images.githubusercontent.com/8754153/89269990-5e366f00-d643-11ea-8c86-544d0454147b.png)

The option should appear there.

**Comment by zniavre** [comment]
ok i see it but i usually alt+e to not showing list toggle etc... and this way the auto join check button is not displayed ...

**Comment by mathiascode** [comment]
Thanks for reporting, the checkbox should definitely not be a part of alt+e.
