### ISSUE TITLE
Tree view expand/collapse is not respected on new transfer

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#473]
Nicotine+ version: 2.1.0-20200805010
Operating System/Distribution: KDE neon (Ubuntu 18.04 LTS)

### Describe the bug
New transfers don't respect expand/collapse setting and are expanded by default. This happens on both downloads and uploads view.

### Additional context

![Screenshot_20200805_132507](https://user-images.githubusercontent.com/3148302/89407543-aa5adf80-d727-11ea-9b3b-6b70a54066dd.png)

**Comment by mathiascode** [comment]
I tried to reproduce this several times, but wasn't able to. Can you test this branch?
`git clone -b transferlist https://github.com/mathiascode/nicotine-plus`

**Comment by alekksander** [comment]
perfect – i'm using daily pre–built .deb packages. will check the behavior as soon as i manage to do an update.

**Comment by alekksander** [comment]
i sadly report that the issue persist with 2.1.0-20200806021

**Comment by alekksander** [comment]
i fiddled with settings and despite eventually everything is way it used to be, the issue is gone.
