### ISSUE TITLE
don't repeat user name in tree view

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#475]
### Describe the solution you'd like
for now in the tree view user name is repeated in each and every line. is there a reason for that? i think it would be better to have it only in top position, resulting less cluttered view.

### Additional context
![Screenshot_2020 08 05_13:50:46](https://user-images.githubusercontent.com/3148302/89409800-4cc89200-d72b-11ea-869c-f0ffea06d947.png)

**Comment by mathiascode** [comment]
I repeated them intentionally in the search view at least, since I got tired of constantly having to scroll up in SoulseekQt just to remember who the uploader is, if there were many folders under a user.

**Comment by mathiascode** [comment]
Marking this as wontfix for now. If there's more demand from other users, I may reconsider.
