### ISSUE TITLE
Completed downloads are re-Queued

### ISSUE THREAD

**Issue by poutine-dejeuner** [Nicotine-Plus/nicotine-plus#477]
Nicotine+ version:  1.2.16
Operating System/Distribution: Ubuntu 18.04.4LTS

### Describe the bug
when downoads are queued 2 will be transfered but then will be queued again instead of being marked as Finished and the 2 will then alternate between Queued, Requesting file and Transfering. The console displays the messages 
_Retrying failed download:
Failed download:
 Download started:_ 

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Please try the latest version of Nicotine+ (2.0.1) from the stable PPA: https://github.com/Nicotine-Plus/nicotine-plus#ubuntu-ppa-stable

Version 1.2.16 is around 10 years old at this point, and a ton of fixes have been added since.

**Comment by poutine-dejeuner** [comment]
weird! i was sure i was using the latest...
