### ISSUE TITLE
search tab "close thistab" missing if 3 tabs are open 

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#481]
Nicotine+ version:  2.1.0.dev1
Operating System/Distribution:20.04 

### Describe the bug
try to open 3 searchs the tab between two others does not hav "close this tab" option but listing of the search tabs 

### Expected behavior
open this tab each tabs 

Sorry for this one it's second time ...   :o(

**Comment by mathiascode** [comment]
Can't reproduce. Are you sure it's not the hitbox that is bad (outer edges of the tab usually don't work)?

**Comment by zniavre** [comment]
like last time i m quite sure it became.... trying to search a new way to reproduce and for the moment it works nicely  :o)

sorry for wrong report 
mea culpa maxima

**Comment by alekksander** [comment]
![Screenshot_2020 08 06_01:06:40](https://user-images.githubusercontent.com/3148302/89472644-934cd980-d789-11ea-924f-24bfc790406f.png)

looks okay here too. @zniavre  please close if You cannot reproduce anymore – or perhaps there were some specific conditions?

**Comment by mathiascode** [comment]
This happens when a search request is ignored, and consistently when max search results are reached on the latest master.
