### ISSUE TITLE
close button in About Nicotine+ doesn't work

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#485]
Nicotine+ version:  2.1.0-20200805010
Operating System/Distribution: KDE neon (Ubuntu 18.04 LTS)

### Describe the bug
after viewing „About Nicotine+” user can't close the dialog with „Close”

### Additional context
![Screenshot_2020 08 06_00:48:50](https://user-images.githubusercontent.com/3148302/89471593-3d773200-d787-11ea-86ce-548a5f37e714.png)

**Comment by mathiascode** [comment]
Most likely a bug in GTK, looking for a workaround.

**Comment by alekksander** [comment]
sorry for such a minor report by the way, and thanks for responding
