### ISSUE TITLE
Wishlist has issues with chinese characters

### ISSUE THREAD

**Issue by CypherNL** [Nicotine-Plus/nicotine-plus#498]
Nicotine+ version:  2.0.1
Operating System/Distribution: Windows 10 2004 Education

### Describe the bug
When adding a wishlist search with chinese characters, the wishlist setting don't save these wishlist searches and everything underneath. So when restarting these wishlist searches are gone. When adding this manually in the config file, the application closes immediately after loading the wishlist.

### Expected behavior
The wishlist searches with chinese characters should have been retained after reboot and the special characters should be shown properly.

### Steps to reproduce the bug
For the chinese character bug:
1. Go to the wishlist search window
2. Add "霜冻前夜" to the list
3. Add something underneath "霜冻前夜"
4. Restart the application and go back to the wishlist search window.
5. The wishlist search "霜冻前夜" is gone as the searches beneath it.
6. Quit the application and add the wishlist search "霜冻前夜" in the config file (for windows: C:\Users\<user>\AppData\Roaming\nicotine\config\config) at autosearch and save it.
7. Open the application and you will see it won't show up when it should.
8. Remove "霜冻前夜" from the config file and open the application
9. The application should now open correctly

**Comment by mathiascode** [comment]
There are issues with non-Latin characters in Nicotine+ 2.0.1 on Windows. It will be fixed in 2.1.0.
