### ISSUE TITLE
add country flags to uploaders and the option to geoban said country

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#506]
I don't have a particular reason to like or dislike people from any country and I don't look up uploaders country of origin. But I can imagine I might discover a pattern if it was easy to get the info.

Would it be possible to add a country flag to uploaders? Would it be possible to add a menu-option to ban the country from that country?

I mean, those people from Antarctica are really just leechers! I never knew!

**Comment by mathiascode** [comment]
Targeting this for a future version of Nicotine+. We will probably have to rewrite the column width/visibility config code, since it's too inflexible for adding new columns.

**Comment by hboetes** [comment]
Same here. Let's close this issue. It's just a bad work around.
