### ISSUE TITLE
Download Folder function doesn't work from search when uploader is offline

### ISSUE THREAD

**Issue by CypherNL** [Nicotine-Plus/nicotine-plus#511]
Nicotine+ version:  2.1.0.dev1 (around 5387c97)
Operating System/Distribution: Windows 10 2004 Education

### Describe the bug
When right-clicking a folder of an offline user at the search results and clicking on the option Download folder(s), it does nothing. The option Download folder(s) to... and selecting the download might work sometimes. Downloading the files inside the folder does work 100% of the time so does the Download file(s) to... Function.

### Expected behavior
The whole folder should added to the download list with the status "User logged off".

### Steps to reproduce the bug
1. Search something or let the wishlist function search something for you. Be sure the download list is grouped by folder.
2. Wait when an user with their folders and files becomes **red** (offline).
3. Right-click on the **folder** or **one of the files inside that folder**.
4. Click on _Download folder(s)_.
5. Check the _Downloads_ list. You will see the folder doesn't add to the download list.
6. Try again but with the _Download folder(s) to..._ option and select a different folder to download that folder
7. Check the _Downloads_ list again. The folder might have been added this time. Or may be not...
8. Go back to the _Search files_ list and **select all the files in the folder** and right-click on the selection
9. Click on _Download file(s)_.
10. Check the Downloads list and the files are being added with the "User logged off" status.

**Comment by mathiascode** [comment]
Not sure if there's much that can be done here. When downloading individual files, we can just grab all the cached data from the search results, but when downloading a folder, we request the user to send us all the files of the folder.

**Comment by mathiascode** [comment]
Perhaps we could add the all the files visible in the search results to mitigate the issue slightly.

**Comment by CypherNL** [comment]
> 
> 
> Perhaps we could add the all the files visible in the search results to mitigate the issue slightly.

That's also what i thought. If the user is offline, download all the files in the folder shown in the search list.
