### ISSUE TITLE
Disable SourceForge downloads

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#513]
@eLvErDe Can we disable downloads on the Nicotine+ SourceForge page? Seems like there are still people downloading 1.2.16 every week, and it would be better if we could discourage the usage of old, broken versions as much as possible. The GitHub releases seem to include old installers from SourceForge in any case.

**Comment by hboetes** [comment]
Since @eLvErDe is not responding:
Via https://sourceforge.net/support you can file a support request to sfnet_ops@slashdotmedia.com and ask them to take down the downloads, or maybe even take down the whole project.

**Comment by mathiascode** [comment]
I got a response from SourceForge. @eLvErDe or another admin (daelstorm) are the only people who are able do something.

I suggest marking the project as moved, as there seems to be a SF feature for that, and disabling/removing the downloads.

**Comment by hboetes** [comment]
Wow, the completely passive attitude of SF is very disappointing.
