### ISSUE TITLE
Show network drives when adding a shared directory.

### ISSUE THREAD

**Issue by Pelllicer** [Nicotine-Plus/nicotine-plus#52]
Currently only main drives are listed. Would be cool to have access to network drives too. If anyone knows a workaround to share a network share let me know.

**Comment by bernd-wechner** [comment]
Only guessing, but probably useful to know what OS you're on and what you're expecting as they all handle network drives, and mapping them onto the filesystem proper a little differently. I'm on Linux for example and my NAS drives are just mounted seamlessly on to the root filesystem. Windows generally offers two options, mapping network drives to drive letters or using a UNC path name (browsing in the latter case is likely to need specific support).

**Comment by Pelllicer** [comment]
Yes windows here. They don't show as drive letters instead they are folders shared under a network drop down so I guess it uses an UNC path name.

**Comment by gfarmerfr** [comment]
Hi @Pelllicer 

I never tested N+ with network drives on Windows.
As far as i know we rely on a gtkfilechooser dialog to select a directory to share.
I'll look into it to see how this part works and report back.

**Comment by gfarmerfr** [comment]
I've just tested on Win7 to share a directory on the network, then map it to a network drive.
It seems to work as you can see with the following screenshots.
Is this what you're trying to do ?

![screenshot1](https://cloud.githubusercontent.com/assets/20270839/23378032/3cce7bca-fd32-11e6-8f70-45c4c74e47c6.png)
![screenshot2](https://cloud.githubusercontent.com/assets/20270839/23378033/3cd022b8-fd32-11e6-89d8-600801394680.png)

**Comment by mathiascode** [comment]
I haven't tested if sharing actually works properly yet, but I can add folders from servers without issues in GNOME 3.36.2 (Manjaro). Downloading files to a server folder also works. I don't have a Windows installation to test on, but it seems evident that it's working when looking at the screenshots above.

**Comment by mathiascode** [comment]
Working as intended.

@kiplingw close
