### ISSUE TITLE
Certain searches don't stop even after closing the tab, restarting the program, and/or disconnecting and reconnecting to Soulseek

### ISSUE THREAD

**Issue by CypherNL** [Nicotine-Plus/nicotine-plus#520]
Nicotine+ version:  2.1.0dev1-d16417c
Operating System/Distribution: Windows 10 2004 Education

### Describe the bug
When searching a very common phrase like "test" and then closing the tab to stop searching, it still tries to get results for "test" and it doesn't stop when reconnecting to Soulseek, restart the program and even research the term and click on "ignore" according to the "Messages" debug output.

This means the downloads could be hang to "Getting address" or something else when downloading and probably uploading nothing.

### Expected behavior
After closing the tab, it should stop searching and displaying results even in the debug log.

### Steps to reproduce the bug

1. Enable "Messages" at debug output.
2. Go to search files
3. Search for the term "test"
4. Close the tab
5. The FileSearchResult messages keeps spamming the debut output and you can download/upload nothing
6. Restart the program.
7. After connecting to Soulseek, the FileSearchResult messages continue with results for "test"
8. It does stop after a while, but it may outputs FileSearchResult messages with results for "test" occasionally.

### Additional context
In settings, i have a max search results and stored results of 10000 which may prolong this issue.

**Comment by mathiascode** [comment]
Thanks for the report! Stopping search requests is something I previously wanted to look into as an optimization when reaching maximum stored results, but I wasn't aware that results are sent even after a disconnect from the server.

**Comment by CypherNL** [comment]
I have also a log of it: https://gist.github.com/CypherNL/9ebdfe3654b25494d075db8ce3ef6f1f

I do have removed download and upload file information but otherwise you see the issue. This is taken after restarting the program post test term search. It includes A LOT of WinError 10054 for some reason and i don't know if it's actually just an user or something else causing this.

**Comment by CypherNL** [comment]
I also get some search request results i had searched before i upgraded to the latest dev version that's not on my wish list. So it isn't only build d16417c that has this issuel.

**Comment by mathiascode** [comment]
SoulseekQt seems to be able to stop search requests. I see this in the log: `Stopping search for test at 10197 results.`

I'll dig a bit to see how it's done. Possibly some unknown server message.

**Comment by mathiascode** [comment]
As far as I can tell, there is no way of stopping search requests. While analyzing traffic in SoulseekQt, incoming connections didn't seem to stop after the search result limit was reached.

I've made a few changes such as https://github.com/Nicotine-Plus/nicotine-plus/pull/543 to hopefully improve the situation a bit.

**Comment by CypherNL** [comment]
I've installed the newest NIcotine_ (48ae3b7) and it does still this even clicking on "Ignore". SoulseekQT seem to does it too so I'm okay with that. But there's an issue with huge search like test where after a half a minute pressing on ignore the client becomes very unresponsive it eats ram without stopping. I saw it rise to 6GB of RAM before i quit the client manually. This is with only Messages debug output being turned on.

**Comment by mathiascode** [comment]
Sounds like an issue that could be exclusive to the Windows version. I'll investigate.

**Comment by mathiascode** [comment]
Some good news: I've finally identified the cause for the high memory usage, and a fix is coming soon.

**Comment by mathiascode** [comment]
@CypherNL Can you try the latest unstable build to confirm that the memory issue is gone?

**Comment by CypherNL** [comment]
I've updated my Nicotine install but it doesn't boot. I try to do a clean reinstall before i can confirm if it's a new issue.

**Comment by CypherNL** [comment]
Removed and re-installed the latest build of Nicotine+ (9b99572) here: https://github.com/Nicotine-Plus/nicotine-plus/actions/runs/229329562

I still can't start the program after opening it. I'm not sure how to debug this since the exe file doesn't respond to -d, --debug, -h and --help flags. There does not seem to be a log file either.

**Comment by mathiascode** [comment]
There's something wrong with the builds generated by Github Actions. I'll investigate.

**Comment by mathiascode** [comment]
Latest unstable build should be working.

**Comment by CypherNL** [comment]
I can boot now. Currently setting up Nicotine+ again... I will let you know if the issue still persist.

**Comment by CypherNL** [comment]
Just tested the "Test" search result and the memory leak and the huge freeze is gone! So far, so good!

**Comment by mathiascode** [comment]
Excellent! If you notice any freeze issues when downloading some folders, this should take care of the issue: https://github.com/Nicotine-Plus/nicotine-plus/pull/614
