### ISSUE TITLE
debian packages

### ISSUE THREAD

**Issue by starenka** [Nicotine-Plus/nicotine-plus#530]
Could anyone please look into debian packages? The flatpak dist is kinda clumsy and PITA to use. Using nicotine from source also does not shine too much (because of missing reqs in setup.py/requirements file). I suppose it won't be too much hassle as there are Ubuntu pkgs already. Thank you a big thank you to you all for making this happen (2.x).

**Comment by hboetes** [comment]
I've already made a request for maintainer ship and a request for somebody to become a maintainer for the Debian packages and I have no reaction to either request.
Feel free to try the same.
The `/debian` folder makes building packages for Debian a breeze.

**Comment by kiplingw** [comment]
@starenka, try the PPA and see how it fares under Debian. Most, if not all, of the dependencies I would think should be satisfiable.

**Comment by starenka** [comment]
> The `/debian` folder makes building packages for Debian a breeze.

Cheers! Will try. Can you please navigate me to a term i need to google out to get me started?

**Comment by hboetes** [comment]
Sure, just google for:
```
git clone https://github.com/Nicotine-Plus/nicotine-plus.git
sudo apt install devscripts build-essential:native
tar czf nicotine_2.1.0.orig.tar.gz nicotine-plus
cd nicotine-plus
sudo mk-build-deps -i
dpkg-buildpackage
ls -lrt
```

**Comment by kiplingw** [comment]
Instructions in the README.
