### ISSUE TITLE
running from source - missing reqs

### ISSUE THREAD

**Issue by starenka** [Nicotine-Plus/nicotine-plus#531]
Can we please state required python libs to run from source? They're not stated in setup.py/requirement file. I run it now on using current pygobject & mutagen

```
mutagen~=1.45.1
PyGObject~=3.36.1
```
Is there a reason why the reqs are not in setup.py and therefore would be installed when doing `python setup.py install`?

**Comment by mathiascode** [comment]
Main reasons: the native package manager of the OS is recommended for deps, nobody has asked for a requirements.txt file previously, and it's one less dependency list to keep up to date.

https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/DEPENDENCIES.md
https://github.com/Nicotine-Plus/nicotine-plus/blob/2.0.1/doc/DEPENDENCIES.md

**Comment by starenka** [comment]
I don't think encouraging people to `sudo python install` and using global site-packages is good idea (in general). The virtualenv approach should be suggested and thus you need those requirements to install in virtualenv. I don't know how packaging python app works (for linux/macos etc), but stating those reqs in setup.py/requirements.txt is standard python way to make these reqs installed in the env.

**Comment by mathiascode** [comment]
Thanks for the heads up about virtualenv, sounds like a good approach. I'll look into it closer at some point.

**Comment by starenka** [comment]
it basically boils down to:

```
git clone https://github.com/Nicotine-Plus/nicotine-plus.git /tmp/nicotine-plus
cd /tmp/nicotine-plus
python3 -m venv .env
# (now either use `source .env/bin/activate` which will allow you to run python and pip without the full path or use full paths for pip and python - will show you the latter one as it is more universal)
/tmp/nicotine-plus/.env/bin/pip install -r requirements.txt #if requiements not in setup.py
/tmp/nicotine-plus/.env/bin/python setup.py install
```

to run just: `/tmp/nicotine-plus/.env/bin/python tmp/nicotine-plus/nicotine`
to update, just pull from the repo and redo all steps from the `git clone`

**Comment by starenka** [comment]
Nice! Cheers!
