### ISSUE TITLE
CPU usage spikes and remains high after period of usage

### ISSUE THREAD

**Issue by sunox1** [Nicotine-Plus/nicotine-plus#54]
Hi @gfarmerfr 

I am using the master version 1.4.1 on Debian Stretch with kernel 4.9.0-2.

If I leave N+ open and seeding, after a variable period of time (between let's say 6 and 24 hours) its CPU usage will spike very high, and remain high thereafter. If I run htop during this high CPU usage phase I see two PIDs associated with nicotine with very high usage (~150% and ~85%). Restarting nicotine temporarily fixes the problem. 

Please let me know if there is any other information I can provide.

Thanks.

**Comment by sunox1** [comment]
This seems to be tied to certain problematic users. 

In the past few weeks I have noticed some strange attempted transfers. A few times in the past few weeks I have encountered situations where a user queues up some transfers, and it stalls for seemingly no reason, sometimes after transferring a little bit of a file. Many times (maybe all of the time), not long after it stalls, the queued files start disappearing one by one until all queued transfers for that user are cleared from my Uploads tab.

I had a suspicion that these were related to the CPU spikes, so I started taking down the name and IP for users who were giving me this issue, and banning them. Sometimes I could only find out the name and IP by restarting nicotine and getting their info before they disappeared. I thought it seemed to help reduce instances of the cpu spikes, but wasn't sure, so I didn't mention it in the above post. 

A few minutes ago, I think I have found a confirmation that these strange stalling-then-disappearing users are is indeed related to the cause of the issue. This time the issue was persisting through many restarts, and sure enough there was a stalled user sitting in my Uploads. As soon as I banned the user my CPU usage immediately returned to normal.

Is it possible that people are trying to high-jack my cpu? Or do you think it's relatively innocent?

Thanks as always!

**Comment by gfarmerfr** [comment]
Hi @sunox1,

I don't think anyone is trying to hijack you but I could be wrong. It might just be a defective client cancelling its requests or something similar.

**Comment by sunox1** [comment]
Ok, well that's reassuring. I just thought I would bring it to your attention in case it was helpful in some way. It could be an issue with soulseek in general - I haven't bothered to do a comparison with QT. 

Thanks as always.

**Comment by df0ecc** [comment]
Was experiencing this recently. Since disabling the auto-join of 'Nicotine' chatroom it seems to have stopped. Also, I am not joined in any other rooms.

**Comment by addfrustration** [comment]
I am using Nicotine + 1.4.1 on Debian 9.0.4 Linux 4.9.0-3. amd 64. intel dual core  at 3066mhz 4gb ram.
I also have a cpu spike issue.
I have managed to copy and paste debug information to a text file, but I have difficulty opening a text file of 68 mb. 
When my cpu spikes it also uses more than a gig of swap file. Normally my system does not use swap file.
It seems to occur when someone makes a BrowseShares request.
It does not happen every time a BrowseShares request is made.
Similar to sunox1, I thought it was certain problematic users, but after going through debug info I have formed the opinion that it is a bug with BrowseShares requests. Possibly in conjunction with search results, and my download request from the user making a BrowseShares request.
Once the cpu spikes, I have to quit Nicotine and restart, as my cpu temp also hits the roof.
It is very difficult to retrieve debug information as it completely freezes my system.
The only way I can retrieve debug info is to use Task manager to kill enough processes to stabilize my system and copy and paste to a text file, which is difficult to open as it too freezes my system.
I will attach the debug info in the hope that it is useful in determining what is at the root of the problem.
The debug info is for a session that was approx. 1 hour duration.
Well I tried to upload my text file but it is too big.
Let me know if you would like to receive the file by some other method.

Thanks,
addfrustration

**Comment by fawngarden** [comment]
I can't seem to figure out any of the free software bug bounty sites because I am not very smart, but if anyone is willing to put this issue on Issuehunt, Gitcoin, or etc., I will contribute some money. It's been a persistent issue for a long time, and I'm a daily user.

**Comment by abdulocracy** [comment]
> I am using Nicotine + 1.4.1 on Debian 9.0.4 Linux 4.9.0-3. amd 64. intel dual core at 3066mhz 4gb ram.
> I also have a cpu spike issue.
> I have managed to copy and paste debug information to a text file, but I have difficulty opening a text file of 68 mb.
> When my cpu spikes it also uses more than a gig of swap file. Normally my system does not use swap file.
> It seems to occur when someone makes a BrowseShares request.
> It does not happen every time a BrowseShares request is made.
> Similar to sunox1, I thought it was certain problematic users, but after going through debug info I have formed the opinion that it is a bug with BrowseShares requests. Possibly in conjunction with search results, and my download request from the user making a BrowseShares request.
> Once the cpu spikes, I have to quit Nicotine and restart, as my cpu temp also hits the roof.
> It is very difficult to retrieve debug information as it completely freezes my system.
> The only way I can retrieve debug info is to use Task manager to kill enough processes to stabilize my system and copy and paste to a text file, which is difficult to open as it too freezes my system.
> I will attach the debug info in the hope that it is useful in determining what is at the root of the problem.
> The debug info is for a session that was approx. 1 hour duration.
> Well I tried to upload my text file but it is too big.
> Let me know if you would like to receive the file by some other method.
> 
> Thanks,
> addfrustration

Hey, do you happen to still have that debug log around? We could find a way to get it here.

**Comment by mathiascode** [comment]
@addfrustration If you're still around, some debug info would be really useful. Some CPU usage should be expected when compressing the filelist before sending it, but there's definitely some bug here. How many files are you sharing?

**Comment by mathiascode** [comment]
Haven't seen any new reports about this, and a lot of changes have been made to the codebase since this issue was reported. Open a new issue if you still experience this.
