### ISSUE TITLE
filter out unspecific searches

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#551]
Because of another issues with master I looked quite a bit at the search results floating by:

```user foo is searching for m, returning 50 results```

Would it be helpful to have a filter that only searches for requests that contain at least 5 chars?

**Comment by hboetes** [comment]
oops, wrong label.

**Comment by toofar** [comment]
Not sure about 5 chars, then you couldn't search for ABBA!

**Comment by hboetes** [comment]
It's not about searching, it's about returning search results on unspecific searches.
Personally I never search for less than 3 words because I'm looking for specific bands and albums. So I'd search for:
```abba Gold Greatest Hits flac``` which will give useful results.

I hope you can agree that searching for a single char is pointless, and so is 2 and 3. 4 and 5 is really on the edge.

**Comment by hboetes** [comment]
I just found the setting under "searches" "Send out a max of $x results per search request. Which I decreased to 10. I bet that helps.
