### ISSUE TITLE
Mouse cursor does not indicate draggable borders

### ISSUE THREAD

**Issue by leopwinters** [Nicotine-Plus/nicotine-plus#552]
Nicotine+ version:  2.1.0dev1
Operating System/Distribution: Gnu/Linux Pop!_OS 20.04 (a distribution based on Ubuntu 20.04)

### Current behaviour

When I hover over a draggable border, the mouse cursor does not indicate that the border can be dragged:

![actual](https://user-images.githubusercontent.com/69720042/90313026-5d39f300-df09-11ea-8078-a5e764f4f607.gif)

### Expected behaviour

I expect the mouse cursor to change to indicate that the border can be dragged, like this (the irony of it being the Spotify client, also note the lag :):

![expected](https://user-images.githubusercontent.com/69720042/90313028-60cd7a00-df09-11ea-85b6-628409a18168.gif)

### Additional context
I use bspwm as my window manager.

**Comment by zniavre** [comment]
it should be your mouse theme or DE who don't handle something it works here

![simplescreenrecorder-2020-08-15_15 41 10](https://user-images.githubusercontent.com/2409578/90313592-0b479c00-df0e-11ea-9cb9-7bf3e1a9316f.gif)

**Comment by mathiascode** [comment]
Have you tested if any other GTK3 applications have this issue on your system?

**Comment by leopwinters** [comment]
> Have you tested if any other GTK3 applications have this issue on your system?

I just noticed that other GTK applications also have this, indeed. For example GNOME Files (nautilus) has the exact same behaviour. Which is weird, as it works fine with applications that do not use GTK, such as Firefox and the Spotify client.

So it is probably an issue with my window manager, other configuration, or GTK.

**Comment by mathiascode** [comment]
I hope you get the issue resolved somehow.
