### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by ibrokemypie** [Nicotine-Plus/nicotine-plus#56]
https://www.nicotine-plus.org/ is reported to be using an expired ssl certificate, according to Chromium.
The message is as follows:
This server could not prove that it is www.nicotine-plus.org; its security certificate expired 69 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Thursday, 13 April 2017. Does that look right? If not, you should correct your system's clock and then refresh this page. Find out more.

**Comment by Mutnick** [comment]
It looks like there's a fresh certificate, so closing this.
