### ISSUE TITLE
Segfault When Getting User Info

### ISSUE THREAD

**Issue by ibrokemypie** [Nicotine-Plus/nicotine-plus#57]
zsh: segmentation fault  nicotine
no other error is reported.

**Comment by tinglycraniumplacidly** [comment]
Hi, what version of Nicotine+ are you running? I'm not able to reproduce with v 1.4.2

**Comment by mathiascode** [comment]
Is this still happening in the master branch?

**Comment by mathiascode** [comment]
No response since 2019, and likely fixed in the wave of Python3 changes. @kiplingw Close?
