### ISSUE TITLE
Search -> Right Click -> Download folder(s) does nothing

### ISSUE THREAD

**Issue by jasonsmedvik** [Nicotine-Plus/nicotine-plus#574]
Nicotine+ version:  2.0.1
Operating System/Distribution: Fedora Core 32

### Describe the bug
I run a search for a particular album/song, and results are displayed. Upon right-clicking on any result and selecting "Download folder(s)" nothing happens. I check the Downloads tab and the requested folder is not downloading, in fact nothing at all has apparently happened.
However, selecting another result in Searches and right-clicking and selecting Download folder(s) results in the folder downloading correctly

### Expected behavior
Item shows up in downloads and downloads

### Steps to reproduce the bug
See above

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by jasonsmedvik** [comment]
Glad that I am not alone

However, highlighting/selecting all in the folder for Download Folder has the same result for me - sometime it works, most times it does not, with no apparent pattern.

**Comment by alekksander** [comment]
same here

**Comment by gmarthews** [comment]
Same here

**Comment by mathiascode** [comment]
For some reason users don't always respond when asking for the folder contents. Might have to implement https://github.com/Nicotine-Plus/nicotine-plus/issues/511 to solve/mitigate this issue.

**Comment by mathiascode** [comment]
I found the issue, coming up with a solution now.
