### ISSUE TITLE
Some weird characters prevents download of file

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#578]
![image](https://user-images.githubusercontent.com/2285225/90984091-34ea6e00-e573-11ea-91b4-2b4c61fe0582.png)

This file refused to get downloaded even after a few retries. I suspect the file was named with a funny encoding.

Feel free to close the bug if this is not a N+ problem, which is very well possible.

**Comment by mathiascode** [comment]
Nothing we can do on our side. I suggest giving the user a heads up about fixing their file names.
