### ISSUE TITLE
Brew OSX Install

### ISSUE THREAD

**Issue by ibrokemypie** [Nicotine-Plus/nicotine-plus#58]
I have created a pull request on homebrew core to include nictotineplus. It builds and runs, however I think it needs some polish as well as perhaps reverting at least some of https://github.com/Nicotine-Plus/nicotine-plus/commit/c4f1435ac057afeff522d447cc1122530454f619
PR is here https://github.com/Homebrew/homebrew-core/pull/12400

**Comment by mathiascode** [comment]
@ibrokemypie Are you still interested? I think Homebrew dropped Nicotine+ due to Python 2 being EOL, but a Nicotine+ 2.0.0 release with Python 3 support is planned in the near future.

**Comment by mathiascode** [comment]
Closing due to lack of interest. Unstable macOS packages are now available outside Homebrew, testers would be appreciated: https://github.com/Nicotine-Plus/nicotine-plus#macos

**Comment by EricFromCanada** [comment]
I've submitted an updated Homebrew formula in https://github.com/Homebrew/homebrew-core/pull/62820.

**Comment by mathiascode** [comment]
Thanks!
