### ISSUE TITLE
some margin lines are missing (possible qt/gtk issue)

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#593]
Nicotine+ version:  
2.1.0-202008251623~ubuntu20.04.1

Operating System/Distribution:
KDE Plasma on KDE neon (Ubuntu 20.04 LTS)

### Describe the bug
Margin lines are not drawn fully in some places.

### Additional context
![margins](https://user-images.githubusercontent.com/3148302/91305831-51c1b400-e7b4-11ea-8003-f16f82974041.png)

**Comment by mathiascode** [comment]
Seems like an issue in the Breeze theme, not much that can be done.
