### ISSUE TITLE
Failed to map the external WAN port: Invalid Args

### ISSUE THREAD

**Issue by frddbbbl** [Nicotine-Plus/nicotine-plus#597]
I have just changed my isp and have set up my router with upnp enabled however i get this error that i previously did not have on the other router.Not sure exactly what information is usefull to you but the router is a Zyxel brand.

UPnP exception: Failed to map the external WAN port: Invalid Args
Failed to automate the creation of UPnP Port Mapping rule.

**Comment by mathiascode** [comment]
Not sure if it's relevant in your case, but https://github.com/miniupnp/miniupnp/issues/92

What's the output of `upnpc -l`?

**Comment by frddbbbl** [comment]
the output is :
---
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:5555/DeviceDescription.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:5555/UD/?3
Local LAN ip address : 192.168.1.7
Connection Type : IP_Routed
Status : Connected, uptime=68279s, LastConnectionError : ERROR_UNKNOWN
  Time started : Thu Aug 27 19:13:29 2020
MaxBitRateDown : 20410000 bps (20.4 Mbps)   MaxBitRateUp 1020000 bps (1.0 Mbps)
ExternalIPAddress = 89.168.123.186
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
 0 TCP  6881->192.168.1.4:6881  'libtorrent/1.2.2.0' '' 0
 1 UDP  6881->192.168.1.4:6881  'libtorrent/1.2.2.0' '' 0
 2 TCP 62190->192.168.1.4:62190 'SoulseekQT' '' 0
 3 TCP 62191->192.168.1.4:62191 'SoulseekQT' '' 0
GetGenericPortMappingEntry() returned 501 (Action Failed)
---

also my mates windows computer with slsk client on the same network appears to work so i dont think it is inately to do with the router

**Comment by mathiascode** [comment]
Does manually adding a port forwarding entry work?
`upnpc -e Nicotine+ -a 192.168.1.7 <client port> <client port> TCP`

Client port should be whatever port you've specified in Nicotine+.

**Comment by hboetes** [comment]
@frddbbbl as you can see your log output is rendered wrong. Could you be so kind to edit your post and put three backticks before and three backticks after the log output? See https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks for the details.
Thanks

**Comment by mathiascode** [comment]
Closing this, since UPnP functionality was rewritten in https://github.com/Nicotine-Plus/nicotine-plus/pull/820. If the original issue still occurs, feel free to open a new issue with additional information.
