### ISSUE TITLE
Segmentation fault on Ubuntu Gnome 17.04

### ISSUE THREAD

**Issue by zalloy** [Nicotine-Plus/nicotine-plus#60]
Nicotine used to work on this machine. However, since this afternoon, every time I try to start it it closes as soon as it tries to scan/rebuild my share directory.

I tried starting it from Terminal, and all that shows is `Segmentation fault (core dumped)`

Any idea how I can get this working again? It's a real drag having to use SoulseekQT, because that client doesn't even save my settings on exit, so I then have to go back and try to download anything that hadn't completed again manually, which is a pain in the ass.

Any help would be greatly appreciated. 

Thanks!

**Comment by mathiascode** [comment]
Most likely not happening in the master branch anymore.

**Comment by kiplingw** [comment]
Unfortunately the PPA doesn't build for Zesty anymore. I'm sure more than one of our dependencies are not available for it. @zalloy, can you let us know if you are still having this issue on eoan, focal, or groovy?

**Comment by zalloy** [comment]
@kiplingw No longer seeing this issue (currently running focal). However, I now have an entirely different problem, so will open a new issue for that if one doesn't already exist. Going to close this out.
