### ISSUE TITLE
Nicotine Freezes With Too Many Transfers

### ISSUE THREAD

**Issue by jasonsmedvik** [Nicotine-Plus/nicotine-plus#609]
Nicotine+ version:  2.1.0.dev1
Operating System/Distribution: Fedora Core 32

I apologize if this has been covered or there is an obvious way to prevent this issue.

I'm currently stuck and unsure what to do to recover and still keep my current Downloads

### Describe the bug
Downloading 10+ different folders and Nicotine suddenly froze when I tried to switch to the Downloads Tab 

After closing program and opening again, Nicotine continues to freeze each time it opens... sometimes it manages to load the current Downloads, sometimes not. 

Currently stuck in a situation where I can no longer use Nicotine since it freezes immediately upon opening

### Expected behavior
For this to not happen, or at least for it gracefully recover.

### Steps to reproduce the bug
Download 10 or so folders, switch back and forth between Search and Downloads tabs... eventually it will freeze.

### Additional context
Freezes on Downloads tab with all downloads saying "Getting status"
Only way out is to kill program

**Comment by mathiascode** [comment]
I assume you're on the latest master commit?

**Comment by jasonsmedvik** [comment]
Yes, latest commit.

**Comment by jasonsmedvik** [comment]
Is there a way I could enable detailed logging/tracing to help diagnose the problem?

In .niocotine/config it has debug = True and has a logsdir specified but the directory seems to be empty

**Comment by mathiascode** [comment]
Debug logs aren't currently saved to file. https://github.com/Nicotine-Plus/nicotine-plus/issues/387

Could you try the py-spy profiler? It should give you a hint of which part of the code is causing freezes. `py-spy top nicotine`

**Comment by mathiascode** [comment]
Also try the latest master commit, it might help a bit.

**Comment by jasonsmedvik** [comment]
OK latest master commit - seems to have no effect based on several runs (same results each time)

py-spy gives the following output

``````

` 30.00%  30.00%    6.90s     6.90s   update_parent_row (pynicotine/gtkgui/transferlist.py:327)
 47.00%  47.00%    6.86s     6.86s   update_parent_row (pynicotine/gtkgui/transferlist.py:332)
  5.00%   5.00%    1.00s     1.00s   update_parent_row (pynicotine/gtkgui/transferlist.py:333)
  8.00%   8.00%   0.940s    0.940s   update_parent_row (pynicotine/gtkgui/transferlist.py:338)
  5.00%   5.00%   0.520s    0.520s   update_parent_row (pynicotine/gtkgui/transferlist.py:335)
  3.00%   3.00%   0.280s    0.280s   update_parent_row (pynicotine/gtkgui/transferlist.py:329)
  0.00%   0.00%   0.210s    0.210s   update_parent_row (pynicotine/gtkgui/transferlist.py:336)
  1.00%   1.00%   0.120s    0.120s   update_parent_row (pynicotine/gtkgui/transferlist.py:325)
  1.00%   1.00%   0.110s    0.110s   update_parent_row (pynicotine/gtkgui/transferlist.py:342)
  0.00%   0.00%   0.020s    0.020s   __init__ (selectors.py:349)
  0.00%   0.00%   0.010s    0.010s   update_parent_row (pynicotine/gtkgui/transferlist.py:337)
  0.00%   0.00%   0.010s    0.010s   register (selectors.py:359)
  0.00% 100.00%   0.000s    16.95s   <module> (nicotine:248)
  0.00% 100.00%   0.000s    16.95s   Login (pynicotine/pynicotine.py:636)
  0.00% 100.00%   0.000s    16.95s   update_parent_rows (pynicotine/gtkgui/transferlist.py:292)
  0.00% 100.00%   0.000s    16.95s   run (nicotine:241)
  0.00% 100.00%   0.000s    16.95s   run (gi/overrides/Gio.py:44)
  0.00% 100.00%   0.000s    16.95s   OnNetworkEvent (pynicotine/gtkgui/frame.py:652)
  0.00%   0.00%   0.000s    0.030s   _bootstrap_inner (threading.py:932)
  0.00%   0.00%   0.000s    0.010s   run (pynicotine/slskproto.py:1155)
  0.00% 100.00%   0.000s    16.95s   InitInterface (pynicotine/gtkgui/frame.py:569)
  0.00%   0.00%   0.000s    0.020s   run (pynicotine/slskproto.py:1131)
  0.00% 100.00%   0.000s    16.95s   InitInterface (pynicotine/gtkgui/transferlist.py:159)
  0.00%   0.00%   0.000s    0.030s   _bootstrap (threading.py:890)
  0.00% 100.00%   0.000s    16.95s   update (pynicotine/gtkgui/transferlist.py:282)
```

````

**Comment by mathiascode** [comment]
Do you think you could send your transfers.pickle file somehow (in .local/share/nicotine), perhaps to the email address on my GitHub profile? I'm not sure why updating the download list UI is so resource intensive in your case.
