### ISSUE TITLE
filenames with ? in them get stuck on uploads list

### ISSUE THREAD

**Issue by mozai1** [Nicotine-Plus/nicotine-plus#61]
I'm running arch linux.
Great work on the upgrade!

**Comment by mathiascode** [comment]
This is now resolved, as long as the uploader is using Nicotine+ 1.4.3, and the downloader is using Nicotine+ 1.4.3 or the official Soulseek client.

@kiplingw close

**Comment by mathiascode** [comment]
Sharing files with special character file names will not work if the downloader is using the old Soulseek NS client, but there's nothing we can do about it. Happens if SoulseekQt is sharing too.
