### ISSUE TITLE
Nicotine+ 1.4.1, windows 8.1 (64-bit) errors when using UPNP

### ISSUE THREAD

**Issue by neiljt** [Nicotine-Plus/nicotine-plus#63]
13:58:43 UPnP exception: UPnPPortMapping instance has no attribute 'externalipaddress'
13:58:43 Failed to automate the creation of UPnP Port Mapping rule.

**Comment by TomJansen** [comment]
I have this too on Arch linux. Is this an Nicotine+ issue or miniupnp issue?

**Comment by TomJansen** [comment]
Ah oops it was a router issue
