### ISSUE TITLE
Minor issues to fix for 2.1.1

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#659]
Due to personal time constraints, the next release(s) of Nicotine+ will be very small, unless there are contributions by other people. Here's a list of minor issues to fix for 2.1.1:

- [ ] Ctrl+C no longer working in debug log window
- [x] In Settings -> Interface -> Icons, icon labels have the wrong order
- [x] Dev versions should not display "up to date" message in update checker

More issues will be added in due time.

**Comment by zniavre** [comment]
i hav made change in setting window ui file to reorganize icon name>image how to send you this file please

not huge mode but at least i can "contribute" to nic+ after 17 years i will love to be one week contributor

**Comment by mathiascode** [comment]
Thanks! Since you've only changed one file, you can get away with editing the file in the web UI by pressing the pencil icon here: https://github.com/Nicotine-Plus/nicotine-plus/blob/master/pynicotine/gtkgui/ui/settings/icons.ui

This will create a fork with the changed file. GitHub should then display a button for creating a pull request with the change.

If you plan on doing larger contributions that start touching the code, I recommend installing git and learning the basics. There should be multiple tutorials online.
