### ISSUE TITLE
Import and export scd1 config files.

### ISSUE THREAD

**Issue by Goldmaster** [Nicotine-Plus/nicotine-plus#673]
### Describe the solution you'd like
During setup maybe the last part, there should be an option to import a .scd1 Soulseek backup file, so that any chats, uploads, and any other settings are imported into nicotine plus.

### Additional context
The idea also would that once a Soulseek backup file is imported, that when the program is closed or at a certain schedule of the users choice, nicotine plus can automatically backup the configurations, chats, download ques etc, to a .scd1 file in a particular location of the users choice. maybe that could be again in the settings and at the end of the configuration setup.

**Comment by mathiascode** [comment]
These scd1 files seem to be in some custom, non-readable format with zero documentation. I'm afraid this request is out of scope for the foreseeable future, as Nicotine+ is already lacking manpower as-is.

**Comment by mathiascode** [comment]
Closing as won't fix for now.
