### ISSUE TITLE
Can't share directories

### ISSUE THREAD

**Issue by zalloy** [Nicotine-Plus/nicotine-plus#68]
I just updated Nicotine+ from the Ubuntu PPA, and as I was setting it up I found that I wasn't able to share my ~/Music directory. I was getting an error message about not sharing my home directory. So, to get around that, I made a copy of that directory on another drive and tried to share that, but still getting that same error message.

Why isn't it allowing me to share the copy that's on another drive? Because of this, I can't share anything and can't use the app. :angry: 

Any suggestions on how I can fix this, so I can share the copy and use the app normally? Thanks in advance. 

L

**Comment by mathiascode** [comment]
Is this still an issue on the master branch?

**Comment by zalloy** [comment]
Not that I'm aware of. Closing this out. @mathiascode
