### ISSUE TITLE
Uploads randomly freeze

### ISSUE THREAD

**Issue by pirate1337** [Nicotine-Plus/nicotine-plus#686]
When somebody tries to download a file from me, sometimes (not all the time) it flat out will not upload until i restart the client.

**Comment by mathiascode** [comment]
- What is your Nicotine+ version?
- In settings -> general -> server, is "I can receive direct connections" checked or not? Are your ports open?
- What status message are the uploads stuck on?

**Comment by mathiascode** [comment]
Closing until more information is provided.
