### ISSUE TITLE
Too Many Files issue.

### ISSUE THREAD

**Issue by gandhicandy** [Nicotine-Plus/nicotine-plus#725]
Nicotine+ version:  
Operating System/Distribution:

### Describe the bug
![image](https://user-images.githubusercontent.com/67538664/95668877-6d97d400-0b2e-11eb-8572-ef018aa6ecb4.png)
When downloading a full album, which has 20+ songs, I get an error stating "Too many files" 

### Expected behavior
Should be able to download all files in the downloading tab.

### Steps to reproduce the bug
Search, and download albums with more than 20 songs. 

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
This is not a bug, the uploader has set their client to not allow users to queue more than 20 files. Either queue less files at once, or ask the uploader if they could set a more generous limit.
