### ISSUE TITLE
Follow X Session Management Protocol

### ISSUE THREAD

**Issue by alekksander** [Nicotine-Plus/nicotine-plus#729]
Could we please have nicotine+ compatible with X session protocol? ( https://www.x.org/releases/X11R7.7/doc/libSM/xsmp.html ) this would allow nicotine to be brought back with session restore on linux.

**Comment by mathiascode** [comment]
Any reason for closing this?

**Comment by alekksander** [comment]
i'm not sure how it works exactly, but for some reason my system (plasma 5.20) restores nicotine on startup now. before that i thought it's x11 related.
