### ISSUE TITLE
Question: Is Development Dead?

### ISSUE THREAD

**Issue by sla0101** [Nicotine-Plus/nicotine-plus#73]
One thing I noticed when gfarmerfr took over the project, it seemed like at that point in time it was really being worked on, now almost a year since the last release there hasn't been anything, and there are still a lot of things to be worked out.

The ```Columns Position Not Being Maintained```, I agree, this really turns me off over using nicotine-plus, constantly having to move everything around, and I too have really hope since that report was made it would of been completed by now;

https://github.com/Nicotine-Plus/nicotine-plus/issues/8

Anyhow I hope all is ok with gfarmerfr, and development will begin again soon...

Thanks

**Comment by Mutnick** [comment]
Hi @sla0101, indeed @gfarmerfr  put in a commendable amount of work on the project and he appears to be on hiatus. It's great when someone puts in a lot of effort like that but realistically, that's not something we are entitled to, it's just great when it happens.

The main point is anyone should feel free to contribute to development here. I'll probably put more dev time into the project myself this year, but for sure have been reviewing and merging any pull requests in a timely manner.

So as far as answering your question I know it can be frustrating when particular issues aren't resolved, but really we're in the same boat as most open-source projects.

Thanks.

**Comment by sla0101** [comment]
Hi,

Well gfarmerfr was certainly going at it, and the last it seemed like he was going to keep this alive, and working on new releases, so not sure what happened...

Anyhow, in regards to the Columns Position Not Being Maintained, is this something you can do?

I personally don't have any issues using this, other then the columns not being maintained, which is a real negative for me, always having to mess with them to see...

Thanks for the reply...

**Comment by Mutnick** [comment]
Closing this, as issue already exists - https://github.com/Nicotine-Plus/nicotine-plus/issues/8

**Comment by sla0101** [comment]
@Mutnick are you able to work on the Columns Positions?

Thanks
