### ISSUE TITLE
"No module named pynicotine" on Debian 10

### ISSUE THREAD

**Issue by iaeiou** [Nicotine-Plus/nicotine-plus#732]
Nicotine+ version:  2.1.1-202009270058~ubuntu20.10.1
Operating System/Distribution: Debian 10, fresh install

### Describe the bug

I followed [the documentation](https://github.com/Nicotine-Plus/nicotine-plus#ubuntu-ppadebian-stable), everything was fine:
```
$ sudo apt install software-properties-common
$ sudo add-apt-repository ppa:nicotine-team/stable
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6CEB6050A30E5769
$ sudo apt update
$ sudo apt install nicotine
```
But when I try to start `nicotine` from the terminal I just get an error:

```
$ nicotine 
Traceback (most recent call last):
  File "/usr/bin/nicotine", line 33, in <module>
    from pynicotine.utils import ApplyTranslation
ModuleNotFoundError: No module named 'pynicotine'
```

Any hint?

**Comment by mathiascode** [comment]
This will be fixed once Nicotine+ 2.1.2 is released later today.
