### ISSUE TITLE
improve dark/light theme settings

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#736]
This is a cosmetic problem and has low priority.

- Have a double set of colours, one for the dark theme and one for the light theme, since both themes require completely different text colours. Both should have sane defaults.
- Changing the URL colour only takes effect after restarting N+

**Comment by gits68** [comment]
first of all, thanks for the dark theme 👍 

for ex., color set for dark theme:

dark_mode = True
chatme = #4E9A06
chatlocal = #729FCF
chathilite = #AD7FA8
urlcolor = #3465A4
useronline = #4E9A06
useraway = #F57900
useroffline = #AA0000
searchq = #888A85
tab_default = #BABDB6
tab_hilite = #AD7FA8
tab_changed = #729FCF

would be interresting to have the default color value greyed in the ui for the empty ones:

chatremote = 
textbg = 
search = 
inputcolor =
