### ISSUE TITLE
sometimes, nicotine eats all memory

### ISSUE THREAD

**Issue by gits68** [Nicotine-Plus/nicotine-plus#750]
Nicotine+ version:  2.0.1
Operating System/Distribution: Windows 10 2004

### Describe the bug
sometimes, nicotine will eat all memory

### Expected behavior
limit the max used memory

a possible solution would be to add 2 parameters, virtual & physical memory limits, 0 for no limit by default.
https://stackoverflow.com/questions/54949110/limit-python-script-ram-usage-in-windows

### Steps to reproduce the bug
none

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Thanks for the report! Please upgrade to Nicotine+ 2.1.2. There were memory leaks in 2.0.1 that have since been fixed.

**Comment by gits68** [comment]
not seen the new version, update done, will see, thanks.
PS : it was a long standing bug I have since v1., then v2.x
for instance, I limit the memory usage using https://github.com/lowleveldesign/process-governor (--install)
I've disabled it to see if the problem subsist...

**Comment by mathiascode** [comment]
How is it looking so far?

**Comment by gits68** [comment]
well, humm... still here :-(

![2020-10-18 13_29_03-Gestionnaire des tâches](https://user-images.githubusercontent.com/7086920/97009144-09204000-1544-11eb-946b-5fd4c718b44d.png)

**Comment by mathiascode** [comment]
Bummer. A couple of questions:
- Does the memory usage suddenly grow, or does it happen gradually?
- Are you uploading a lot of files? If so, how many users do you have in your buddy list?
- Is there anything else you do in Nicotine+ (e.g. browse a lot of shares without closing them)?

**Comment by gits68** [comment]
Hi, a couple of answers :

- apparently, the memory usage suddenly grow and the nicotine window doesn't answer, there is nothing to do except to kill the process.
- for instance, I didn't download anything, and I don't know if there are many uploads since the window doesn't answer. I have no users in the buddy list, but 2990 in the ban list...
- possibly since I automatically browse shares through a plugin (slsk://gits2k/autoban-leechers), but I close them on a regular basis.

hope this help ;^)

Regards.

**Comment by mathiascode** [comment]
Sounds exactly like two Windows-related issues that were fixed in 2.1.0 (suddenly growing memory usage). Perhaps there's a third one still lurking somewhere. Are you on version 2.1.2 for sure (just confirming for my own sanity, since there have been previous cases where users were on the wrong version)?

**Comment by gits68** [comment]
for sure, I'm on version 2.1.2.
the next time, maybe I could take a [SysInternal's ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) ?
something like : procdump64 -h Nicotine+.exe NicotineHung.dmp
don't know if I should use the -r and/or -k options ?

**Comment by gits68** [comment]
hi, did you received the private email to mail(at)mathias.is about minidumps ?

**Comment by mathiascode** [comment]
I don't think the email arrived for some reason. Can you try sending it again?

**Comment by gits68** [comment]
done

**Comment by gits68** [comment]
> hi, did you received the private email to mail(at)mathias.is about minidumps ?

ping ;-)

**Comment by mathiascode** [comment]
I received your email, but didn't find anything suspicious in the dumps. Sadly, I haven't come up with a good way to debug this issue on Windows yet due to poor availability of tools there, but I'll let you know if I figure something out.

A lot of subpar code related to connectivity has been refactored recently, to hopefully improve the situation too. I'll get the unstable Windows builds working in a moment, so you can test them.

**Comment by gits68** [comment]
not seen the unstable windows builds before, installed the last one, will see, thanks.

**Comment by gits68** [comment]
still crashing, but don't know yet if it's still a memory problem ?
i'm still on latest 2.2.0-dev1 12/11/2020

**Comment by mathiascode** [comment]
Crashing or hanging?

**Comment by gits68** [comment]
Hi, a crash last week, but don't know why, it was just no more there... for instance, no more hang.
I'm still on the same instance for a week now, while before I had a hang almost every day.
I think you may close this ticket for now, will see, thanks for your help, regards

**Comment by mathiascode** [comment]
Thanks, let's close this for now.
