### ISSUE TITLE
Feature request: USR signals controls?

### ISSUE THREAD

**Issue by teledyn** [Nicotine-Plus/nicotine-plus#76]
would it be possible to signal nicotine to do a connect/disconnect? for example, to use kill -USR1 to toggle the disconnect/connect controls.  This would enable scheduling via cron :)

**Comment by Mutnick** [comment]
Hi @teledyn I'd say this isn't needed as new feature as you likely can send keypresses to the nicotine+ process, alt-c for connect and alt-d for disconnect. 

Examples for linux/x11 using xdotool:

disconnect
xdotool windowactivate $(xdotool search --name "Nicotine\+") key alt+d


connect
xdotool windowactivate $(xdotool search --name "Nicotine\+") key alt+c

Adjust as appropriate, what utility and parameters you use to send keypress will depend on your system and use case but this more generalized solution should already be possible.  Hope this helps.
