### ISSUE TITLE
some users aren't browsable

### ISSUE THREAD

**Issue by gits68** [Nicotine-Plus/nicotine-plus#766]
Nicotine+ version:  2.1.2
Operating System/Distribution: Windows 10 2004

### Describe the bug
Use informations say that some user have files & directories,
but trying to browse that user returns nothing !

### Expected behavior
the ability to browse files for such users

### Steps to reproduce the bug
try on users elmatana (slow), Greenlyph (fast) and suture (not connected right now) 

### Additional context
Screenshots, logs, stacktraces or relevant information.

User Informations :
![2020-10-24 04_28_53-Nicotine+ 2 1 2](https://user-images.githubusercontent.com/7086920/97065968-8766fb80-15b1-11eb-941b-b9d37afaa948.png)

Shared Files :

**slow**
![2020-10-24 04_31_04-Nicotine+ 2 1 2](https://user-images.githubusercontent.com/7086920/97065992-c432f280-15b1-11eb-8152-82730a3e911b.png)

**fast**
![2020-10-24 04_55_59-Nicotine+ 2 1 2](https://user-images.githubusercontent.com/7086920/97066372-3f49d800-15b5-11eb-9bd2-07661124ff29.png)

**Comment by mathiascode** [comment]
I checked on SoulseekQt, same results there. Seems like this can happen when someone shares files privately. I suppose we could add an info message on the user browse page if it's empty, to reduce confusion.

**Comment by gits68** [comment]
well, same result with Nicotine 1.4.1...
As I remember, for example, I download files from suture through the search files while I can't browse it !
I'll try other tests, to give you another test case...

**Comment by mathiascode** [comment]
I'll check what's up with suture once the user is online again, but ultimately we can't do much in Nicotine+ if users don't send us correct data.

**Comment by gits68** [comment]
humm, elmatana was browsable today !

![2020-10-28 04_58_40-Nicotine+ 2 1 2](https://user-images.githubusercontent.com/7086920/97389333-569d0400-18da-11eb-8e4e-b1e96858a309.png)

Greenlyph too !!

![2020-10-28 05_01_27-Nicotine+ 2 1 2](https://user-images.githubusercontent.com/7086920/97389509-c01d1280-18da-11eb-82ee-694c87d69c14.png)
