### ISSUE TITLE
tray icon problem

### ISSUE THREAD

**Issue by starenka** [Nicotine-Plus/nicotine-plus#767]
Nicotine+ version:  7a4297745424e337e2f08de49bb69bca2f897d3f (current master)
Operating System/Distribution: Debian testing, sddm & awesome

Hi folks, ever since I switched to npp 2.0+ (running from source) my tray icon is just this "page with missing stuff" (see screenshot, right next to slack icon). Any ideas, how to get "normal icon"?

```
(.env) starenka /opt/nicotine-plus master at 7a429774 % pip freeze
backcall==0.2.0
decorator==4.4.2
ipdb==0.13.3
ipython==7.18.1
ipython-genutils==0.2.0
jedi==0.17.2
miniupnpc==2.0.2
mutagen==1.45.1
nicotine==2.1.3.dev1
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.7
ptyprocess==0.6.0
pycairo==1.19.1
Pygments==2.6.1
PyGObject==3.38.0
pytaglib==1.4.6
six==1.15.0
traitlets==4.3.3
wcwidth==0.2.5
```

![Screenshot_20201024_152413](https://user-images.githubusercontent.com/228248/97082921-54eaec00-160d-11eb-956d-f9197587d1a9.png)

**Comment by mathiascode** [comment]
Looks like we have to come up with some clever hack to get the correct icon path in Python virtual environments (relevant code location here: https://github.com/Nicotine-Plus/nicotine-plus/blob/master/pynicotine/gtkgui/tray.py#L202), unless there's a better way I'm not aware of. Until then, you'd have to copy the tray icons to `/usr/share/icons/hicolor/32x32/apps`, create a custom icon theme, or install a Nicotine+ package system-wide.

**Comment by starenka** [comment]
Oh, detecting venv was about comparing sys.real_prefix and sys.base_prefix.
If they don't match, you're in venv. Keep it with a grain of salt, i have
very vague memory about this and don't have a computer around right now.

---
aknerats[::-1]

**Comment by starenka** [comment]
maybe this would be a way to detect env?

```
starenka /tmp % python3 /tmp/env_check.py
starenka /tmp % 
starenka /tmp % 
starenka /tmp % python3 /tmp/env_check.py
inside venv: False
starenka /tmp % mktmpenv -ppython3       
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
/usr/local/lib/python2.7/dist-packages/virtualenv.py:1039: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /data/.envs/tmp-5e9404fa30f33b90/bin/python3
Also creating executable in /data/.envs/tmp-5e9404fa30f33b90/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /data/.envs/tmp-5e9404fa30f33b90/bin/predeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-5e9404fa30f33b90/bin/postdeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-5e9404fa30f33b90/bin/preactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-5e9404fa30f33b90/bin/postactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-5e9404fa30f33b90/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-5e9404fa30f33b90) starenka /data/.envs/tmp-5e9404fa30f33b90 % python3 /tmp/env_check.py
inside venv: True
(tmp-5e9404fa30f33b90) starenka /data/.envs/tmp-5e9404fa30f33b90 % cat /tmp/env_check.py 
# coding=utf-8

import sys


def inside_virtualenv():
    return hasattr(sys, 'real_prefix') or sys.base_prefix != sys.prefix


if __name__ == '__main__':
    print('inside venv: %s' % inside_virtualenv())
```

**Comment by starenka** [comment]
i'm on current master, still the icon does NOT work....

**Comment by starenka** [comment]
cheers!
