### ISSUE TITLE
Development Dead: Can Someone Please Pick Up The Project?

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#78]
Hello,

If anyone reads/sees this, can someone please pick up this project and bring it into active ongoing development?

I personally don't get why an application like this would ever die, because what really is the alternative here that can match this? I personally am not aware of any such application, where you can find the same level of quaility music online through another P2P app like Nicotine/Soulseek...

I hope somene with the coding talent can please pick the project up!

THANKS

**Comment by Mutnick** [comment]
Closing this as it's best to keep general grievances out of an area intended for actual code issues and ideas. Thanks for your understanding, @0pLuS0.
