### ISSUE TITLE
Uploads Cancelled

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#784]
Nicotine+ version:  2.1.2
Operating System/Distribution:Linux Mint 20

### Describe the bug
random uploads have status 'cancelled', the users that are downloading from me say they are not doing it so i am guessing its something with my client

### Expected behavior
uploads to keep uploading

### Steps to reproduce the bug
it seems to be random

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Thanks for the report! Looks like we might be too aggressive with upload cancellation, as this can happen when a connection is flaky or otherwise closes.

**Comment by mathiascode** [comment]
We still want to cancel a transferring file if a connection problem occurs, to avoid uploads getting stuck, but the linked PR stops Nicotine+ from immediately cancelling all queued files for the user.
