### ISSUE TITLE
Can't scan any songs

### ISSUE THREAD

**Issue by normanck** [Nicotine-Plus/nicotine-plus#798]
Nicotine+ version:  2.1.2
Operating System/Distribution: OpenBSD

### Describe the bug
It's been a while since I last used nicotine+, pymutagen used to throw lots of errors so my shared library was always incomplete. I decided to try this new version but every time I get an error when adding a folder, no matter what files are in there. Browsing to my own shares shows every folder correctly, but no files in any of them.

### Expected behavior
It should scan the files found in the folder allowing me to share those files.

### Steps to reproduce the bug
Add a new folder to your shares and let it scan every file in there.

### Additional context
Here's a small excerpt from nicotine's logs: 
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Bringer Of Light.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Commercial Whore.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Flesh And Blood.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Godless.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Good Gloomy Night.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - I Saw You.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Inner Exile.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Last Breath.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Parasites.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Stachel Im Herz.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Stuprum Violentum.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - Valediction.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/x-Fusion/X-Fusion - Vast Abysm (2CD 2008)/X-Fusion - When The Curtain Falls.mp3: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(11) [Nina Simone] Do What You Gotta Do.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(01) [Nina Simone] In The Morning.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(02) [Nina Simone] Sunday In Savannah.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(03) [Nina Simone] The Backlash Blues.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(04) [Nina Simone] Please Read Me.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(05) [Nina Simone] Gin House Blues.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(06) [Nina Simone] Why- (The King of Love Is Dead).flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(07) [Nina Simone] Peace Of Mind.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(08) [Nina Simone] Ain't Got No - I Got Life.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(09) [Nina Simone] I Loves You Porgy.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(10) [Nina Simone] Take My Hand Prescious Lord.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(12) [Nina Simone] Mississippi Goddam - Bonus Track.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(13) [Nina Simone] Don't Let Me Be Misunderstood - Bonus Track.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(14) [Nina Simone] Come Ye - Bonus Track.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(15) [Nina Simone] Ain't Got No - I Got Life (Single) - Bonus Track.flac: This class cannot be instantiated from Python
16:45:08 Error while scanning file /home/music/(1968) Nina Simone - 'Nuff Said!/(16) [Nina Simone] Peace Of Mind (Single) - Bonus Track.flac: This class cannot be instantiated from Python
16:45:08 22 folders found after rescan
16:45:08 Rescanning finished

**Comment by mathiascode** [comment]
Seems like something is up with your pytaglib installation. Which version of pytaglib do you have, and how did you install it?

**Comment by normanck** [comment]
@mathiascode Yeah, it seems something is off with taglib. I was using the standard pytaglib as provided by openbsd packages but through pip it works just fine, altough I had to tweak it a little to make it work. It is now showing my files as expected. Thanks for the help.
