### ISSUE TITLE
blurry tray icon in kde plasma

### ISSUE THREAD

**Issue by gianniqq** [Nicotine-Plus/nicotine-plus#81]
Hi, I'd like to signal that (at least) on KDE-based systems the tray icon is blurry.

![screenshot_20180825_180903](https://user-images.githubusercontent.com/4668449/44620297-fe00f500-a891-11e8-9c9b-bbdf2e162c95.png)

My system information is:
OS: KDE neon
KDE Plasma: 5.13.4
KDE Frameworks: 5.49.0
Qt: 5.11.1
Kernel: 4.15.15-041515-generic

Nicotine+: 1.4.1

**Comment by alekksander** [comment]
confirm

**Comment by alekksander** [comment]
there is still something off about nicotine tray icon. here is how it's displayed on task bar compared to tray icon

![image](https://user-images.githubusercontent.com/3148302/83875729-e7125680-a737-11ea-8073-347aee989da7.png)

it seems the edges are not transparent…?

**Comment by mathiascode** [comment]
How do the default tray icons look? Not sure if anything can be done here, AppIndicator3 handles the rendering.

**Comment by alekksander** [comment]
to my eyes it looks correctly on defaults. could different png size change how it's displayed? what is recommended size?
![image](https://user-images.githubusercontent.com/3148302/83948854-89a60480-a820-11ea-90b7-3e47d66c13fc.png)

**Comment by mathiascode** [comment]
Possibly. The current size of the icons is 32x32.

**Comment by alekksander** [comment]
tried 32x32 and 64x64, but no luck. it remains distorted.
