### ISSUE TITLE
Search problem?

### ISSUE THREAD

**Issue by ladanonoir** [Nicotine-Plus/nicotine-plus#822]
Nicotine+ version:  2.1.2
Operating System/Distribution: Windows 10 Pro

### Describe the bug
When searching for files, for some reason some words do not return results.

In my specific case, if I search for "beatles" or "the beatles", it doesn't find anything.

If I search for any Beatles album, it finds perfectly.

But I can't do a general search by group name.

### Additional context
Screenshots, logs, stacktraces or relevant information.
[nicotine search.pdf](https://github.com/Nicotine-Plus/nicotine-plus/files/5504570/nicotine.search.pdf)

**Comment by mathiascode** [comment]
Certain search terms are blacklisted on the server, see https://www.slsknet.org/news/comment/1520#comment-1520. The only solution is the workaround you've discovered.
