### ISSUE TITLE
windows unstable build can't rebuild shares

### ISSUE THREAD

**Issue by gits68** [Nicotine-Plus/nicotine-plus#829]
Nicotine+ version:  2.2.0-dev1
Operating System/Distribution: Windows 10 20H2

### Describe the bug
windows unstable can't rebuild shares

### Additional context

04:30:04 Impossible de traiter les bases de données suivantes: C:\Users\x\AppData\Roaming\nicotine\files.db
C:\Users\x\AppData\Roaming\nicotine\buddyfiles.db
C:\Users\x\AppData\Roaming\nicotine\streams.db
C:\Users\x\AppData\Roaming\nicotine\buddystreams.db
C:\Users\x\AppData\Roaming\nicotine\wordindex.db
C:\Users\x\AppData\Roaming\nicotine\buddywordindex.db
C:\Users\x\AppData\Roaming\nicotine\fileindex.db
C:\Users\x\AppData\Roaming\nicotine\buddyfileindex.db
C:\Users\x\AppData\Roaming\nicotine\mtimes.db
C:\Users\x\AppData\Roaming\nicotine\buddymtimes.db
04:30:04 Can't save files.db: 'dict' object has no attribute 'close'
04:30:04 Can't save buddyfiles.db: 'dict' object has no attribute 'close'
04:30:04 La base de données des fichiers partagés semble corrompue, veuillez réexaminer vos partages
...
04:30:44 Réexamen commencé
04:30:44 Rescanning normal shares...
04:30:44 0 folders found before rescan, rebuilding...
05:44:25 Can't save files.db: 'dict' object has no attribute 'close'
05:44:25 Serious error occurred while rescanning shares. If this problem persists, delete C:\Users\x\AppData\Roaming\nicotine/*.db and try again. If that doesn't help, please file a bug report with this stack trace included: 
Traceback (most recent call last):
  File "pynicotine/shares.py", line 290, in _rescan_shares
  File "pynicotine/shares.py", line 368, in rescan_dirs
  File "pynicotine/shares.py", line 685, in get_files_index
AttributeError: 'dict' object has no attribute 'close'

**Comment by mathiascode** [comment]
Thanks for the report! Could you install the latest unstable version? It will give some additional information to help me debug this issue.

**Comment by gits68** [comment]
thanks for the traceback, solved, semidbm was not installed by files/windows/dependencies-core.sh.
in fact, I've a problem running pip3 under mingw64, works well with pip3-script.py instead.
not a nicotine problem, but I don'tknow how to solve this yet:
```
$ pip3 install semidbm
failed to create process (\mingw64\bin\python.exe "C:\msys64\mingw64\bin\pip3-script.py" "install" "semidbm").
```

the traceback was:
```
00:28:59 Failed to process the following databases: C:\Users\Cyrille\AppData\Roaming/nicotine/files.db
C:\Users\x\AppData\Roaming/nicotine/buddyfiles.db
C:\Users\x\AppData\Roaming/nicotine/streams.db
C:\Users\x\AppData\Roaming/nicotine/buddystreams.db
C:\Users\x\AppData\Roaming/nicotine/wordindex.db
C:\Users\x\AppData\Roaming/nicotine/buddywordindex.db
C:\Users\x\AppData\Roaming/nicotine/fileindex.db
C:\Users\x\AppData\Roaming/nicotine/buddyfileindex.db
C:\Users\x\AppData\Roaming/nicotine/mtimes.db
C:\Users\x\AppData\Roaming/nicotine/buddymtimes.db
00:28:59 Traceback (most recent call last):
  File "C:\msys64\home\x\git\nicotine-plus/pynicotine/shares.py", line 148, in load_shares
    self.config.sections["transfers"][destination] = shelve.open(shelvefile, protocol=pickle.HIGHEST_PROTOCOL)
  File "C:\msys64\home\x\git\nicotine-plus/pynicotine/shares.py", line 41, in shelve_open_semidbm
    import semidbm
ModuleNotFoundError: No module named 'semidbm'
00:28:59 Can't save files.db: 'dict' object has no attribute 'close'
00:28:59 Can't save buddyfiles.db: 'dict' object has no attribute 'close'
00:28:59 Shared files database seems to be corrupted, rescan your shares
00:28:59 Loading plugin handler
00:28:59 Unable to enable plugin autoban-leechers
00:28:59 Connecting to server.slsknet.org:2242
00:29:00 Listening on port 32234
00:29:00 Connected to server server.slsknet.org:2242, logging in...
00:29:03 1699 privileged users
00:29:03 You have no privileges left. They are not necessary, but allow your downloads to be queued ahead of non-privileged users.
```
