### ISSUE TITLE
Nicotine 2.1.2 fails to launch in FreeBSD due to missing pytaglib

### ISSUE THREAD

**Issue by BSDBro** [Nicotine-Plus/nicotine-plus#843]
Nicotine+ version:  2.1.2
Operating System/Distribution: FreeBSD

### Describe the bug
nicotine fails to launch due to missing "pytaglib" libraries. gives error: pytaglib is missing please install it.

No alternative to this package exists in FreeBSD.

### Expected behavior
Version 2.0.1 launches fine without

### Steps to reproduce the bug
Download source code for nicotine 2.1.2 release and launch it in FreeBSD.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Pytaglib replaced the previous mutagen dependency for file metadata scanning, due to performance issues in the latter. Does pytaglib install fine with pip? https://github.com/supermihi/pytaglib#get-it

**Comment by BSDBro** [comment]
I got this error trying to install pytaglib through pip-37 on FreeBSD:

`$ pip-3.7 install pytaglib
Defaulting to user installation because normal site-packages is not writeable
Collecting pytaglib
  Downloading pytaglib-1.4.6.tar.gz (468 kB)
     |████████████████████████████████| 468 kB 1.8 MB/s
Using legacy 'setup.py install' for pytaglib, since package 'wheel' is not installed.
Installing collected packages: pytaglib
    Running setup.py install for pytaglib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1jt9zg7r/pytaglib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1jt9zg7r/pytaglib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j2qw8l62/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jamie/.local/include/python3.7m/pytaglib
         cwd: /tmp/pip-install-1jt9zg7r/pytaglib/
    Complete output (18 lines):
    running install
    running build
    running build_py
    file src/pytaglib.py (for module pytaglib) not found
    creating build
    creating build/lib.freebsd-12.2-RELEASE-amd64-3.7
    copying src/pyprinttags.py -> build/lib.freebsd-12.2-RELEASE-amd64-3.7
    file src/pytaglib.py (for module pytaglib) not found
    running build_ext
    building 'taglib' extension
    creating build/temp.freebsd-12.2-RELEASE-amd64-3.7
    creating build/temp.freebsd-12.2-RELEASE-amd64-3.7/src
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/local/include/python3.7m -c src/taglib.cpp -o build/temp.freebsd-12.2-RELEASE-amd64-3.7/src/taglib.o
    src/taglib.cpp:637:10: fatal error: 'taglib/tstring.h' file not found
    #include "taglib/tstring.h"
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1jt9zg7r/pytaglib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1jt9zg7r/pytaglib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j2qw8l62/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jamie/.local/include/python3.7m/pytaglib Check the logs for full command output.
$
`

**Comment by mathiascode** [comment]
Assuming you had installed the regular taglib before installing pytaglib, perhaps building from source is the only option.
https://github.com/supermihi/pytaglib/issues/11#issuecomment-72209822
https://github.com/supermihi/pytaglib#manual-compilation-general

**Comment by BSDBro** [comment]
Thanks for that! I was able to build pytaglib using the instructions in the link and now the nicotine 2.1.2 launches and works. Thanks again 😃

**Comment by mathiascode** [comment]
You're welcome! Ideally there would be Nicotine+ and pytaglib packages available for FreeBSD too, but someone would have to step up and maintain them. I already have enough on the plate with the Windows, macOS and Flathub builds.
