### ISSUE TITLE
Download Recursive 

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#844]
Nicotine+ version:  
Operating System/Distribution:
Nicotine+ 2.1.2
Linux Mint 20 

### Describe the bug
when i right click a folder and download recursive nothing happens... 

### Expected behavior
download the folder and all sub-folders inside 

### Steps to reproduce the bug
right click folder and select download recursive

### Additional context
Screenshots, logs, stacktraces or relevant information.
It's possible i have asked about this here before, memory not what it used to be, i have been trying to figure this out for a bit now and asked everywhere i could find people talking about soulseek.. but still no idea if its an issue with the app or me doing something incorrectly, any help is appreciated

**Comment by mathiascode** [comment]
This is currently fixed in the unstable builds, and will be fixed in the upcoming 2.2.0 release. https://github.com/Nicotine-Plus/nicotine-plus/issues/790

**Comment by woollarding** [comment]
awesome, thank you for the reply
