### ISSUE TITLE
Cannot select shared folder with XDG_DESKTOP_PORTAL enviroment variable on KDE

### ISSUE THREAD

**Issue by wantija** [Nicotine-Plus/nicotine-plus#869]
Nicotine+ version:  2.1.2
Operating System/Distribution: Arch Linux

### Describe the bug
Cannot choose directory with 'GTK_USE_PORTAL=true' exported as variable on KDE Desktop. Have to export the variable as 'false' and use Gnome file picker. 

### Expected behavior
Use Dolphin file picker to select directory

### Steps to reproduce the bug
Install 'xdg-desktop-portal' and 'xdg-desktop-portal-kde'
Run nicotine+ with 'GTK_USE_PORTAL=true' as environment variable 
Try to select Downloads or Shares folder

### Additional context
Screenshots, logs, stacktraces or relevant information.
With GTK_USE_PORTAL=true the log only goes up to line 24.
https://gist.github.com/wantija/306f4375226103b0bd1c3cbab63c884f

**Comment by mathiascode** [comment]
Is this some quirk on Arch or your installation? I've tested this on Kubuntu, and while Dolpin's file picker does not work when selecting folders (upstream issue/limitation), it falls back to the GTK picker instead, which works fine. Some of the file picker dialogs, mainly the ones created from FileChooserButtons, are not handled by us at all, so nothing can be done there.

**Comment by mathiascode** [comment]
Closing, as there's nothing we can do on our side.
