### ISSUE TITLE
the ability to close tabs using Ctrl-F4 

### ISSUE THREAD

**Issue by gits68** [Nicotine-Plus/nicotine-plus#870]
### Describe the solution you'd like
would it be nice to be able to close tabs using Ctrl-F4

also, would be nice to have tabs almost the same length like chrome or ff,
this help to close them using the cross which is almost to the same place
when the current tab is detroyed while switching to the previous tab.

PS : I've found recenltly it was possible to use the middle mouse button to close tabs while looking at the code...

**Comment by zniavre** [comment]
even with middle clic  the idea is nice and smart enhancement to improve UI ,since close buttons disappear. +1 fot that

**Comment by alekksander** [comment]
how about ctrl+w? never heard of ctrl+f4

**Comment by gits68** [comment]
well, both...
[ctrl-w](https://defkey.com/what-means/ctrl-w)
[ctrl-f4](https://defkey.com/what-means/ctrl-f4)
