### ISSUE TITLE
UI very condensed on high-dpi linux.

### ISSUE THREAD

**Issue by jonathanballs** [Nicotine-Plus/nicotine-plus#88]
Running Nicotine-plus on Arch Linux 64bit with a 4k screen. The application opens at the right size and the text is the correct size however the "spacing" is way off and the application looks unnaturally compacted. This is on two times scaling so I'm assuming that the columns widths have just not been scaled properly.

I am not sure entirely why this is happening. I have built GTK apps before and not had any problems when scaling them however I would be willing to have a look if you don't have time to work on this.

![Screenshot from 2019-04-26 14-09-27](https://user-images.githubusercontent.com/4366510/56810040-427fce80-682d-11e9-8a0f-888d070aadcd.png)

**Comment by mathiascode** [comment]
This is fixed in the master branch thanks to the GTK3 port.

**Comment by kiplingw** [comment]
Thanks @mathiascode.
