### ISSUE TITLE
Python 3.8 Crashes

### ISSUE THREAD

**Issue by fmlatghor** [Nicotine-Plus/nicotine-plus#882]
Nicotine+ version:  2.1.2
Operating System/Distribution:
Fedora Linux 33

### Describe the bug
When I'm using nicotine, nicotine sometimes crashes and gnome gives me the message:
![](https://i.vgy.me/SMmpga.png)

### Expected behavior
I expect to use nicotine without it crashing.

### Steps to reproduce the bug
Just using nicotine. There doesn't seem to be a pattern to when it crashes, it's just the same error.

### Additional context
Screenshots, logs, stacktraces or relevant information.
Logs:
```sh
Gtk-Message: 21:46:28.811: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:46:28.811: Failed to load module "pk-gtk-module"
*** BUG ***
In pixman_region_append_non_o: The expression y1 < y2 was false
Set a breakpoint on '_pixman_log_error' to debug


(nicotine:2): Pango-WARNING **: 21:56:15.948: Invalid UTF-8 string passed to pango_layout_set_text()

(nicotine:2): Pango-WARNING **: 21:56:15.956: Invalid UTF-8 string passed to pango_layout_set_text()```

**Comment by mathiascode** [comment]
Are you doing anything specific when this happens, e.g. downloading/uploading files, being in a chatroom, searching files?

**Comment by fmlatghor** [comment]
> Are you doing anything specific when this happens, e.g. downloading/uploading files, being in a chatroom, searching files?

I said here in the original post;
Just using nicotine. There doesn't seem to be a pattern to when it crashes, it's just the same error. I haven't really had any luck downloading any files, but I've been able to share mine.

**Comment by mathiascode** [comment]
A general idea of what's happening and not happening in Nicotine+ would be helpful, so I can start checking if certain activities are causing issues. Some change in the UI must be causing it, unless it's a bug in the toolkit.

Could you try the latest master (git clone https://github.com/Nicotine-Plus/nicotine-plus), run Nicotine+ in gdb (gdb -ex r -ex bt --args python3 nicotine), and post the backtrace if Nicotine+ crashes again?

**Comment by mathiascode** [comment]
I've discovered one crash related to the feature that retries stuck downloads every 60 seconds. Not sure if it's your crash, but the symptoms are similar.

**Comment by fmlatghor** [comment]
Ok, I'll try building from source and send you a debug if it happens again.
-- 
Leo Coogan



Dec 1, 2020, 11:40 by notifications@github.com:

**Comment by mathiascode** [comment]
The latest commits in master should fix the issue. Can you build from source again, and run Nicotine+ for some time, to verify that it doesn't crash anymore?

**Comment by fmlatghor** [comment]
> The latest commits in master should fix the issue. Can you build from source again, and run Nicotine+ for some time, to verify that it doesn't crash anymore?

Sure, I'll do it when I have time.

**Comment by fmlatghor** [comment]
> The latest commits in master should fix the issue. Can you build from source again, and run Nicotine+ for some time, to verify that it doesn't crash anymore?

Ok, I'm having a problem. I have pyobjet installed, but I get this wehn trying to run nicotine:
`Cannot find pygobject, please install it.`

**Comment by mathiascode** [comment]
Did you follow these instructions? https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md

If so, check that the requirements step finished as expected. Since you already have Nic+ and its dependencies installed from earlier though, simply running 'python3 nicotine' in the cloned nicotine-plus folder should work fine too.

**Comment by fmlatghor** [comment]
> Did you follow these instructions? https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md
> 
> If so, check that the requirements step finished as expected. Since you already have Nic+ and its dependencies installed from earlier though, simply running 'python3 nicotine' in the cloned nicotine-plus folder should work fine too.

Yea, that's what I followed. All the dependencies should be installed. I'll try that.

**Comment by fmlatghor** [comment]
Just runnning ./nicotine in the nicotine folder worked. I'll let you know if the issue shows up again.

**Comment by fmlatghor** [comment]
Ok, in the upgrade downloads actually work.

**Comment by fmlatghor** [comment]
Everything seems to be working with the nicotine+ I built from source. Going to keep using the one I built until the new version shows up in my package manager.

**Comment by mathiascode** [comment]
Great, thanks for testing!
