### ISSUE TITLE
Finish running transfers and quit

### ISSUE THREAD

**Issue by hboetes** [nicotine-plus/nicotine-plus#885]
Maybe it would be nice if there was an option to allow the currently running uploads to finish and then quit?

**Comment by mathiascode** [comment]
This shouldn't be difficult to implement, it's mainly the design I've been thinking about. I wonder if a toggleable item in the menu would do?

![Screenshot from 2022-09-14 16-24-18](https://user-images.githubusercontent.com/8754153/190166134-2369da61-daaa-47dd-ba8a-510fc8690a8c.png)

I thought about a separate quit action in preferences -> user interface, but the main issue is that quitting would appear broken if uploads are active and the X button does nothing. There would also be no way to revert the action, and no indication that it's active.

**Comment by slook** [comment]
> the main issue is that quitting would appear broken if uploads are active and the X button does nothing

And the other problem is that after any amount of time the application will suddenly quit, by which time it may be unexpected, so there does need to be an obvious visual indication that the application is waiting to quit.

The dilemma is understandable, but I do think a separate 'Finish Uploads and Quit' action could be preferred over the proposed menu item, if ideally the main window will be frozen and a dialog box would be displayed stating something like "Nicotine+ will quit after _x_ uploads are finished" and giving the options "Return to Nicotine+", "Hide Nicotine+" and "Quit Nicotine+ Now".

**Comment by hboetes** [comment]
Perhaps add a notification bar at the download/upload window under the button bar, that says:

> n+ will close down as soon as these uploads/downloads have finished. Further uploads will be queued and started at the next start of n+
> To cancel this press: button

**Comment by slook** [comment]
If a notifcation is used then it would need to be visible in every part of the application, not only the downloads/uploads tabs.

**Comment by hboetes** [comment]
I'm not against that proposal.

**Comment by slook** [comment]
The menu item idea would work if combined with an InfoBar warning of the impending quit, or some other equivalently ugly and obtrusive interface component.

What happens if new uploads are queued since the Quit request? I suppose the active upload count would need to reach zero?

**Comment by h8uthemost** [comment]
Would love to have this. I actually came here to request this, glad I searched first.

**Comment by mathiascode** [comment]
Having thought some more about this, here's an idea I had:

Menu -> Quit always shows a confirmation dialog, but never contains a checkbox. We could place the toggle for this option here:

![](https://github.com/nicotine-plus/nicotine-plus/assets/8754153/3d50ce39-9379-4968-81b8-73caf22985d2)

When a shutdown is in progress, the status area in the statusbar could indicate this. This would still allow you to use Nicotine+ in the meantime, like SoulseekQt. Pressing the button would stop the shutdown process:

![](https://github.com/nicotine-plus/nicotine-plus/assets/8754153/eb6555b4-72fb-4fd4-8b00-b6962b77003b)

Note that the icon/string choice isn't necessarily final.

**Comment by hboetes** [comment]
That's a great solution indeed.

**Comment by slook** [comment]
If the 'Wait for uploads to finish' option was added to the 'When closing Nicotine+' option setting in Preferences, then perhaps it would be possible to retain (or replace?) the 'Remember choice' functionality.

**Comment by slook** [comment]
> Note that the icon/string choice isn't necessarily final.

Consider "Pending Shutdown" -> "Quitting", because the word "shutdown" is ambiguous with powering-off the machine.
