### ISSUE TITLE
No icons in FreeBSD

### ISSUE THREAD

**Issue by BSDBro** [Nicotine-Plus/nicotine-plus#889]
Nicotine+ version:  2.2.0
Operating System/Distribution: FreeBSD 12.2

### Describe the bug
No app icons appear nor system tray icons (tested with FVWM and XFCE as well as stalonetray system tray) appear. System tray icon is blank. App icon appears as generic app icon.

### Expected behavior
To see an icon on the window titlebar or in the case of older window managers see an icon when the app is "iconified". Also it is expected to see the app icon in the system tray when the app is maximized or minimized. 

### Steps to reproduce the bug
Start nicotine 2.2.0

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Icons were visible when I tested Nicotine+ in Xubuntu recently. How are you installing/starting Nicotine+?

**Comment by BSDBro** [comment]
Hi,
I installed it by just downloading the tarball and extracting it to a folder and starting it with an executable file with the collowing:

`#!/bin/sh

python3.7 /home/jamie/.git/nicotine/nicotine`

**Comment by mathiascode** [comment]
Do any icons appear in Preferences -> Interface -> Icons? Do the icons render properly when browsing them in a file manager?

**Comment by BSDBro** [comment]
I don't see the icons in app itself but I do see them in the github folder under nicotine-plus/files/icons

**Comment by BSDBro** [comment]
Hey it works now. I added the correct folder. **nicotine-plus/files/icons/themes/original**

**Comment by mathiascode** [comment]
Seems like custom icon themes work fine then, but there's still some issue detecting default Nicotine+ icons on your system.

Could you try running the following branch, enable "Statistics" debug logging, and post the log? It should give more information about the icon loading process. `git clone -b iconlog --depth 1 https://github.com/mathiascode/nicotine-plus`

**Comment by BSDBro** [comment]
Good news. The newer icons are showing up in the app and in my system tray. Here's the statistics log:

`19:44:56 Creating Port Mapping rule via UPnP...
19:44:56 UPnP: Discovering... delay=2 seconds
19:44:56 UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 2\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\n'
19:44:56 UPnP: Sent M-SEARCH IP request 1
19:44:56 UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 2\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\n'
19:44:56 UPnP: Sent M-SEARCH PPP request 1
19:44:56 UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 2\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n'
19:44:56 UPnP: Sent M-SEARCH IGD request 1
19:44:56 UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 2\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\n'
19:44:56 UPnP: Sent M-SEARCH IP request 2
19:44:56 UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: "ssdp:discover"\r\nMX: 2\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\n'
19:44:56 UPnP: Sent M-SEARCH IGD request 2
19:44:56 Loading local icons, using path /usr/home/jamie/.git/test/nicotine-plus/files
19:44:56 Detected Nicotine+ icon: org.nicotine_plus.Nicotine.svg
19:44:56 Detected tray icon: org.nicotine_plus.Nicotine-away.svg
19:44:56 Detected tray icon: org.nicotine_plus.Nicotine-connect.svg
19:44:56 Detected tray icon: org.nicotine_plus.Nicotine-disconnect.svg
19:44:56 Detected tray icon: org.nicotine_plus.Nicotine-msg.svg
19:44:56 Connecting to server.slsknet.org:2242
19:44:56 Listening on port 56307
19:44:58 UPnP: 0 device(s) detected
19:44:58 UPnP exception: UPnP does not work on this network
19:44:58 Failed to automate the creation of UPnP Port Mapping rule.
19:44:58 Rescanning started
19:44:58 Rescanning normal shares...
19:44:58 4549 folders found before rescan, rebuilding...
19:45:01 4598 folders found after rescan
19:45:01 Rescanning finished
19:45:01 Connected to server server.slsknet.org:2242, logging in...
19:45:02 1729 privileged users
19:45:02 You have no privileges left. They are not necessary, but allow your downloads to be queued ahead of non-privileged users.`

**Comment by mathiascode** [comment]
Good to hear! Is it possible that you had selected an invalid folder for the icon theme previously?

**Comment by BSDBro** [comment]
The icons wouldn't show up in first launch after I upgraded. I tried every folder with icons until they showed up but they only showed the old icons. The branch you linked shows the new icons. Thanks for the help!😀
