### ISSUE TITLE
Wishlist returns empty results for foreign characters

### ISSUE THREAD

**Issue by morgannunan** [Nicotine-Plus/nicotine-plus#89]
If I add titles to my wishlist that are in the Roman alphabet, I will get results when those titles are located. However, if I add a title in Japanese, when Nicotine finds a match it will pop up a tab, but the tab will be empty.

This implies to me that it's finding results, but filtering them out.

**Comment by mathiascode** [comment]
Is this still an issue for you in the master branch? I can no longer reproduce it.

**Comment by mathiascode** [comment]
I haven't been able to reproduce this on either Linux or Windows.

@kiplingw I suggest closing. If this is still an issue, open a new bug report.
