### ISSUE TITLE
New installation in Big Sur. Doesn't scan shared folders.

### ISSUE THREAD

**Issue by LETRA** [Nicotine-Plus/nicotine-plus#899]
Nicotine+ version:  2.2.0
Operating System/Distribution: macOS Big Sur Stable. 

### Describe the bug
I have installed Nicotine+ and it doesn't scan my disks. I have two external drives and Nicotine does not perform any operation. I have noticed that it does not ask for permissions to access external disks and I have restarted the system but there is no change here.

### Expected behavior

Scanning.

### Steps to reproduce the bug

Add folders. Restart the app. Wait. Restart the system. 

### Additional context
Screenshots, logs, stacktraces or relevant information.

![Captura de pantalla 2020-12-12 a las 5 47 24](https://user-images.githubusercontent.com/16805254/101975525-88c1b580-3c3d-11eb-86d4-0b8d2bfc71da.jpg)

**Comment by LETRA** [comment]
I found this:

https://developer.apple.com/documentation/bundleresources/information_property_list/nsremovablevolumesusagedescription

**Comment by mathiascode** [comment]
Is this only an issue with external disks, or also the main one?

**Comment by LETRA** [comment]
Two external disks, but after several restarts began to index. Anyway the message did not appear and other programs do ask for access to external disks. In any case I went back to SoulseekQt because it took Nicotine fifteen or twenty hours to reindex 800,000 files and SoulseekQt checks the changes and adds new files in half an hour.

**Comment by mathiascode** [comment]
I'm guessing almost all of those are audio files? Scanning times should definitely not last several hours, not sure if this is a macOS exclusive issue or some other bottleneck. Unfortunately I don't have a proper macOS system to test this.

**Comment by foerster-rwth** [comment]
>
> I'm guessing almost all of those are audio files? Scanning times should definitely not last several hours, not sure if this is a macOS exclusive issue or some other bottleneck. Unfortunately I don't have a proper macOS system to test this.

I was hoping that the new Nicotine+ version would improve scanning times. Unfortunately I've not been able so far to make v2.2.0 work (on Windows 10 Education).

Therefore I still run Nicotine+ v1.4.1, and that installation takes -- at the moment -- about 13 hours to scan 200,000 files on the NAS which holds the shares and is accessed via wi-fi. This is with my new router (Linksys ACS 1900 running DD-WRT), with the old router (Fritzbox 6591 Cable) it took considerably less time, about four hours.

**Comment by mathiascode** [comment]
> I was hoping that the new Nicotine+ version would improve scanning times. Unfortunately I've not been able to make v2.1.2 work (on Windows 10 Education). Haven't tried v2.2.0 yet.

Does Nicotine+ not work at all (e.g. not starting), or is file scanning the problematic part? Scanning times should be better than in 1.4.1, and some improvements were also made to scanning in 2.2.X, but I haven't tested network shares personally.

**Comment by mathiascode** [comment]
Feel free to try the latest unstable version of Nicotine+, the scanning process was changed a bit.

**Comment by mathiascode** [comment]
Closing for now. If this is still an issue on 3.0.0, feel free to open a new issue.
