### ISSUE TITLE
invalid byte sequence in conversion input

### ISSUE THREAD

**Issue by rebelmethod** [Nicotine-Plus/nicotine-plus#9]
keep using with windws version - 

 the folder contents could not be displayed 
 invaild byte sequence in conversion input

**Comment by Mutnick** [comment]
rebelmethod are you using one of the .exe's such as Nicotine+-1.2.16.exe or running the sources here?

This may have been fixed with https://github.com/eLvErDe/nicotine-plus/commit/4651e51670640cbcb9a1154b431c6fbc121e8b21

**Comment by gfarmerfr** [comment]
Since this issue should most likely be fixed and we haven't heard back from the user I'm closing this issue.
