### ISSUE TITLE
New Commits - Is Development Back?

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#90]
Hello,

I see there are some new commits for 2019, does this mean development is back, and can we expect any new releases soon?

If development is back, I hope the Columns issue that was reported  3 years ago is fixed...

https://github.com/Nicotine-Plus/nicotine-plus/issues/8

THANKS

**Comment by kiplingw** [comment]
Yes, development is continuing and we are trying to complete a 1.4.3 stable release (Gtk3 port with bug fixes).

**Comment by 0pLuS0** [comment]
Sounds great, I appreciate the reply.

I truly hope that this will get fixed too;

https://github.com/Nicotine-Plus/nicotine-plus/issues/79

Take care & be safe! :)
