### ISSUE TITLE
File not shared !

### ISSUE THREAD

**Issue by gits68** [Nicotine-Plus/nicotine-plus#905]
Nicotine+ version:  2.2.1-dev
Operating System/Distribution: Windows 10

### Describe the bug
bcoz of different problems, I had to reinstall/reconfigure nicotine.
I'm using the -dev version.
shares are on samba mapped to a driver letter.
I can access and read files outside nicotine w/o pbs.
I can browse my files but I can't download them => File not shared !
tried also using a local file w/o success...

### Expected behavior
downloads happen

### Steps to reproduce the bug
no idea

### Additional context
no special message, debug is on
[config.txt](https://github.com/Nicotine-Plus/nicotine-plus/files/5698572/config.txt)

**Comment by mathiascode** [comment]
I suspect Windows' idiotic backslashes are causing issues again. I'll investigate.

**Comment by gits68** [comment]
well, back to release 2.2.2 solve the problem...
will see if that happen again, thanks anyway.
in other words, don't investigate too much :^)

**Comment by mathiascode** [comment]
Thanks, I was worried we'd have to do a 2.2.3 release too. :P

**Comment by gits68** [comment]
Hi, happy new year, 2.2.2 runs fluently, no more crash no more memory eat.
just switched to 2.3.0-dev, same, so, you may close this issue if you want.

**Comment by gits68** [comment]
sorry, but 2.3.0-dev still have the "File Not Shared" pb, switch bak to 2.2.2

**Comment by mathiascode** [comment]
As nothing has changed in the source code, I can only guess that this is somehow caused by a difference in the way the stable and unstable builds are generated.

Could you use 2.3.0-dev1 again, enable connections + messages + transfers debug output, and try to download the files again?

**Comment by gits68** [comment]
hi,
here is the logs : [debug.7z](http://cyrillelefevre.free.fr/temp/debug.7z)
debug_1610239985.log using the last commit 4f011801 from today
debug_1610240409.log using release 2.2.2
search for cover.jpg

**Comment by mathiascode** [comment]
Thanks! Could you check if the latest unstable build fixes the issue?

**Comment by gits68** [comment]
it works, I stay on -dev for a while...

PS : I've a lot of "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 12: invalid start byte" during te startup on the console window, any idea ?

**Comment by gits68** [comment]
Backup Config File add .tar.bz2 2 times:
Config backed up to: C:\Users\lambda\AppData\Roaming\nicotine\config\config backup 2021-01-11 01_22_54.tar.bz2.tar.bz2

**Comment by gits68** [comment]
console output:
```
(org.nicotine_plus.Nicotine:2004): Gtk-CRITICAL **: 01:40:14.323: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(org.nicotine_plus.Nicotine:2004): Gtk-CRITICAL **: 01:40:14.324: gtk_notebook_get_menu_label: assertion 'list != NULL' failed
Traceback (most recent call last):
  File "C:\msys64\home\Cyrille\git\nicotine-plus/pynicotine/gtkgui/frame.py", line 594, in on_network_event
    self.np.events[i.__class__](i)
  File "C:\msys64\home\Cyrille\git\nicotine-plus/pynicotine/pynicotine.py", line 1451, in get_user_status
    self.userbrowse.get_user_status(msg)
  File "C:\msys64\home\Cyrille\git\nicotine-plus/pynicotine/gtkgui/userinfo.py", line 125, in get_user_status
    self.set_text(tab.Main, msg.user)
  File "C:\msys64\home\Cyrille\git\nicotine-plus/pynicotine/gtkgui/utils.py", line 968, in set_text
    tab_label.set_text(label)
AttributeError: 'NoneType' object has no attribute 'set_text'
```

**Comment by mathiascode** [comment]
The UnicodeDecodeError occurs when loading icons. I haven't found a way to fix it, but it doesn't seem to affect icon loading.

The other issues are solved.
