### ISSUE TITLE
Reviewed key binding in the folder tree of user browse

### ISSUE THREAD

**Issue by gits68** [nicotine-plus/nicotine-plus#912]
### Describe the solution you'd like
the current key bindings in the folder tree of user browse are not so practicle.
down key always open (expand) the folder, rigth & left keys does nothing.
ok for the home, end, +, - and * bindings

how about to use the windows key bindings ?

down key only go to the next folder below without to automatically open it
up key only go to the previous folder without to automatically open it,
    if the prev folder is openned, go to the last child of the previous folder
prev/next page should not automatically open the target folder, just jump to it
right key open the current folder if closed, go to the first child folder if any
left key close the current folder if opened, go to the upper folder if closed

well, even on windows, the * binding doesn't seem to have an opposite,
how about to close all the below folders on * again ?
how about to bind / to go to the current root tree ?

hope the explanations was clear ? ah, ah ?

**Comment by gits68** [comment]
ping

**Comment by mathiascode** [comment]
Please refrain from pinging, there's enough work on my plate already. I will look into this issue when I have time.

**Comment by mathiascode** [comment]
Folders are no longer expanded, but keybindings are currently handled entirely by GTK. This will require more work.
