### ISSUE TITLE
Fix viewing of shared files

### ISSUE THREAD

**Issue by 82d** [Nicotine-Plus/nicotine-plus#919]
Viewing shared files does not have the required functionality. It is not possible to view the properties of the file as it is done in the search window.
I propose to do everything in the menu exactly the same as in the menu of the search window. I also consider it necessary to add the function of copying the file name, as well as the directory, including doing this on other windows. This is sorely lacking in comparison with the official client in the process of finding the necessary information about the tracks on the Internet.

**Comment by mathiascode** [comment]
The official client seems to have a Ctrl-C shortcut for copying folder and file names. Is there any other method I've missed?

**Comment by 82d** [comment]
> The official client seems to have a Ctrl-C shortcut for copying folder and file names. Is there any other method I've missed?

 Yes, I think this is the only method ..
