### ISSUE TITLE
nicotine-plus.org certificate expired

### ISSUE THREAD

**Issue by mathiascode** [Nicotine-Plus/nicotine-plus#922]
The certificate for nicotine-plus.org expired on December 28, 2020. I suggest we proceed with https://github.com/Nicotine-Plus/nicotine-plus/issues/409#issuecomment-747186103.

@eLvErDe

**Comment by mathiascode** [comment]
@eLvErDe Sorry for pinging again. I know you're likely busy, but I'd appreciate an approximate time frame for when to expect this issue to be solved (either renewing the certificate, or pointing the DNS records to GitHub Pages).

**Comment by mathiascode** [comment]
Certificate seems to be renewed now.

**Comment by mathiascode** [comment]
@eLvErDe The certificate has expired again. Could you please check what's up with the auto-renewal, or move the domain to GitHub Pages? Thanks!

**Comment by mathiascode** [comment]
@eLvErDe Any update?

**Comment by eLvErDe** [comment]
Fixed and made sure to add a hook reloading nginx on renew, should never occurs again ;)
