### ISSUE TITLE
Is there a way to exclude a file/directory from a share? + Some feedback

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#924]
Recently started using Nicotine+ (never used the official client).

I'm not sure if I'm overlooking something, but I can't find a way to exclude a file/directory from a share. Instead of having to reorganize my shared directory on-disk and move out content that doesn't make sense to be shared with others (but does make sense to be grouped together for personal convenience), it'd be easier to be able to omit/hide a path within a share via Nicotine+ making it unknown publicly. The only other option I can think of is adding every directory individually, of which there are many.

And a small bit of feedback: I'd find it useful if more options in the preferences had tooltips explaining what they do. For example in Downloads > "Lock incoming files…" is a bit of a mystery. Maybe any documentation written for the official client would largely apply since I don't see any for Nicotine+.

And a UI/UX improvement: Mouse wheel scrolling on the horizontal list of open rooms does nothing. Perhaps it could scroll left and right by default, and if a modifier was held, scroll *and* switch tab at the same time? Hopefully GTK has this ability.

Thanks!

**Comment by mathiascode** [comment]
Thanks for your feedback! There currently isn't any option to exclude folders/files in Nicotine+ itself. The only way to accomplish this is to prepend a dot to the names of the unwanted folders/files.

The "Lock incoming files…" option seems to prevent other processes from modifying a file while it's being downloaded. The description could definitely be improved here. If there are any other unclear options, I would appreciate a list of them.

Not sure if scrolling is possible to implement, but I'll check.

**Comment by redactedscribe** [comment]
That's a shame, though the info about dot-prepended files/folders is useful, but still would require me to change my naming scheme. It feels like I have to bend to Nicotine+'s will in this respect. Should a path exclusion feature be introduced at any point, I'll be happy. Till then, I can make-do since there are only a few paths I'd ideally exclude.

Compiling a list of unclear options is a little subjective, but I'll see what I can do.

Thanks for your efforts. It's a nice front-end.

**Comment by redactedscribe** [comment]
These are all from the perspective of a new Nicotine+/Soulseek user, but not a user new to torrent and other common sharing clients:

**General > Searches > Enable sending search results to other users:** Through use of the program, this may become clear, but I don't know when it happens and what use it is. Seems like a Soulseek-only thing. It's enabled by default, though I decided to turn it off. By poking around, I've noticed the Wishlist. Does this preference affect the wishlist from working at all? Again, forgive my ignorance  as it's only been ~24 hours since installation.

**General > Searches > Search Filters:** Just realized there's a Help > About search filters. These are more like result filters than search filters as they are named. Was confused how to use them at first as I thought they were applied when searching, not afterwards. Filters could be enabled by default maybe, but with blank fields so they do nothing other than at least present themselves.

**General > Searches > Text to Speech:** Seems like this only affects chat messages. Otherwise it could belong under the Chat category.

**Transfers > Shares > Rescan shares on startup:** Maybe a word about having to manually rescan if not enabled?

**Transfers > Shares > Buddies-Only Shares:** It has a tooltip, but I find it unclear what it means, perhaps due to a word missing here or there. If enabled, are public (or "normal" as written in the tooltip) shares disabled? The tooltip makes it vague, but I assume that only happens when you enable "Share only to buddies". I think the tooltip should read something like "Enables private shares that only users on your buddy list buddies can access. If disabled, users will only be able to access your public shares.".

**Transfers > Shares > Buddies-Only Shares:** Could read "Disables public shares." even though it's somewhat clear from the graying-out.

**Comment by mathiascode** [comment]
Thanks for the comprehensive list, it helps a lot! Many of these options have been added by various developers over the past ~20 years, so some of them do indeed feel bit clunky. I'll make corrections over time.

**Comment by redactedscribe** [comment]
Just thought I'd let you know, I'm working on a pull request to polish the label formatting in the preferences overall (without changing much of the wording so any translations still make sense).

**Comment by redactedscribe** [comment]
@mathiascode What does the preference "Reopen closed search tabs that haven't been ignored when new results come in" do? I could rephrase it / add a tooltip if you can clarify its function.

**Comment by redactedscribe** [comment]
Also, the "Max stored results per search" is ambiguous. What purpose does storing them server?

**Comment by mathiascode** [comment]
> @mathiascode What does the preference "Reopen closed search tabs that haven't been ignored when new results come in" do? I could rephrase it / add a tooltip if you can clarify its function.

If a search tab is closed without pressing the "Ignore" button on the tab page, the tab will reappear if new search results are sent by other users.

**Comment by mathiascode** [comment]
> Also, the "Max stored results per search" is ambiguous. What purpose does storing them server?

I imagine this is to have more results at hand when filtering searches, but I'm not entirely sure if this was the original purpose.

**Comment by redactedscribe** [comment]
> If a search tab is closed without pressing the "Ignore" button on the tab page, the tab will reappear if new search results are sent by other users.

@mathiascode When testing this, I noticed [the code](https://github.com/Nicotine-Plus/nicotine-plus/blob/eb4e9f214fac4ba3c8b4e32177c1990885e9e925/pynicotine/gtkgui/search.py#L1264) shows that a wishlist search term will be removed when pressing ignore on a result list - it does - but with "Reopen closed search tabs that haven't been ignored when new results come in" enabled, it made clear that manually removing a wishlist item doesn't ignore it. That is to say, items no longer on the wishlist are still being searched for (and maybe until the program restarts) which I'd argue doesn't make sense. In both cases, i think it would be reasonable  for these events to be linked: Ignore removes the wishlist item, and removing a wishlist item ignores it.

Maybe these searches do actually stop when the "Reopen..." option is disabled? I thought this may be highlighting an underlying issue.

Perhaps there should be an "Ignoring search results removes the search term from the wishlist" option? I can't imagine the user wanting the opposite "Removing a wishlist search term ignores it too" option (I believe it should be default due to reason above). Then again, I could be missing something.

**Comment by redactedscribe** [comment]
> > Also, the "Max stored results per search" is ambiguous. What purpose does storing them server?
> 
> I imagine this is to have more results at hand when filtering searches, but I'm not entirely sure if this was the original purpose.

Ah yes. I think I could make this clearer.

**Comment by 82d** [comment]
я почитал и решил предложить идею как исключить один каталог из лбщих.

**Comment by redactedscribe** [comment]
@mathiascode Not sure if you see comments on closed issues unless I tag your username.

Some recent thoughts/suggestions/bugs:

- Fonts can't affect the UI elements, for example: tabs, label text, text fields, User Info information section, and the debug logging checkbox labels. Probably only a Windows issue as if i recall, it's easy to change the global system font on GNU/Linux.
- The font of the application could do with the default font being "_Segoe UI Semibold Semi-Bold_" ("_Segoe UI_" is the system UI default, which looks like it may actually be using semibold too). The default font sizes could go up by 1pt too (to 10). With both changes, I think the text's more visually appealing and shows less ClearType subpixel artifacts. The height of the rows doesn't change. It should be available on all Windows 8+ systems at least.
Normal 9pt vs Semibold:
![normal9pt](https://user-images.githubusercontent.com/25013746/106059340-4247ed80-60fb-11eb-92c0-01be6241d7a9.png) ![semibold9pt](https://user-images.githubusercontent.com/25013746/106059352-46740b00-60fb-11eb-895f-5feae79cab42.png)
Normal 10pt vs Semibold:
![normal10pt](https://user-images.githubusercontent.com/25013746/106059364-4aa02880-60fb-11eb-81ec-80f003e7ccf4.png) ![semibold10pt](https://user-images.githubusercontent.com/25013746/106059369-4c69ec00-60fb-11eb-87cd-8c48cd49b6d4.png)
An especially poor example of the UI's font (that cannot be changed by the Windows user), Chat Rooms help:
![current-UI-font-artifacts](https://user-images.githubusercontent.com/25013746/106057556-ce0c4a80-60f8-11eb-8d6f-7f8972e22dda.png)

- The debug log could have its own settable font via preferences (not to follow the Chat font setting).

- Preferences _always_ loads with the Logging tab as the tab in focus. In fact, for some reason, it now always loads the User Info tab first (and five minutes later, now Ban List), and it doesn't seem to be because it's adhering to any "last used/modified" tab thing. Maybe this is a side-effect of lazily loading the preferences?

- Set the main tabs' label angle to `-90`/`90`: Text and icon is _not_ centered, unlike at `0`.
- Now set main tabs to be positioned on the left: text and icons _are_ centered, but they could be equally spaced/expanded like when the tab bar is at the top.
- In this configuration (above), if a tab has a notification, it looks odd with the text unaligned to the rest of the tabs' labels (maybe notification icon should be next to tab icon?).

- I can't recall the default tab order, but I propose Buddy List > Private Chat > Chat Rooms > User Info > Search Files (is centered) > User Browse > Downloads > Uploads > Interests.

- A preference to not connect on start-up (would require hamburger icon > Connect each time).

- The tooltip given to the country result filter mentions "UK" but it must actually be "GB" instead.

**Comment by mathiascode** [comment]
>     * Fonts can't affect the UI elements, for example: tabs, label text, text fields, User Info information section, and the debug logging checkbox labels. Probably only a Windows issue as if i recall, it's easy to change the global system font on GNU/Linux.

I've now added an option to set the global font.

>     * The font of the application could do with the default font being "_Segoe UI Semibold Semi-Bold_" ("_Segoe UI_" is the system UI default, which looks like it may actually be using semibold too). The default font sizes could go up by 1pt too (to 10). With both changes, I think the text's more visually appealing and shows less ClearType subpixel artifacts. The height of the rows doesn't change. It should be available on all Windows 8+ systems at least.
>       Normal 9pt vs Semibold:
>       ![normal9pt](https://user-images.githubusercontent.com/25013746/106059340-4247ed80-60fb-11eb-92c0-01be6241d7a9.png) ![semibold9pt](https://user-images.githubusercontent.com/25013746/106059352-46740b00-60fb-11eb-895f-5feae79cab42.png)
>       Normal 10pt (odd letter spacing) vs Semibold:
>       ![normal10pt](https://user-images.githubusercontent.com/25013746/106059364-4aa02880-60fb-11eb-81ec-80f003e7ccf4.png) ![semibold10pt](https://user-images.githubusercontent.com/25013746/106059369-4c69ec00-60fb-11eb-87cd-8c48cd49b6d4.png)
>       An especially poor example of the UI's font (that cannot be changed by the Windows user) which looks aliased and reddish, Chat Rooms help:
>       ![current-UI-font-artifacts](https://user-images.githubusercontent.com/25013746/106057556-ce0c4a80-60f8-11eb-8d6f-7f8972e22dda.png)

The default font weight can't be changed, but the size could be increased. I'm not sure why the font rendering seems so bad, is this a GTK issue, or just a Windows thing?

>     * The debug log could have its own settable font via preferences (not to follow the Chat font setting).

I don't like adding another font button just for the debug log, and would prefer to rename the chat font label to something like "Text view font".

>     * Preferences _always_ loads with the Logging tab as the tab in focus. In fact, for some reason, it now always loads the User Info tab first (and five minutes later, now Ban List), and it doesn't seem to be because it's adhering to any "last used/modified" tab thing. Maybe this is a side-effect of lazily loading the preferences?

Contextual settings open depending on the tab you're on, if you press the cog button.

>     * Set the main tabs' label angle to `-90`/`90`: Text and icon is _not_ centered, unlike with `0` angle.
> 
>     * ...Now set main tabs to be positioned on the left: text and icons _are_ centered, but they could be equally spaced/expanded like when the tab bar is at the top.
> 
>     * ...In this configuration (above), if a tab has a notification, it looks odd with the text unaligned to the rest of the tabs' labels (maybe notification icon should be next to tab icon?).

Possibly the least tested option in the program. If I feel motivated, I'll look into this.

>     * I can't recall the default tab order, but I propose Buddy List > Private Chat > Chat Rooms > User Info > Search Files (is centered) > User Browse > Downloads > Uploads > Interests.

The tab order was changed very recently, and I'd like to avoid reordering things again. The first half contains the sharing-related tabs, like search, downloads, uploads and user browse, as that's the main point/focus of Nicotine+ after all. The second half contains the social ones. The chat room tab is second to last, mainly because it was the previous default tab, which IMO was confusing, and not the best feature to emphasize nowadays due to the toxicity there.

>     * A preference to not automatically connect on start-up (would require hamburger icon > Connect each time).

I can see this belonging in the server settings, not a fan of emphasizing such a feature in a menu where space is already at a premium.

>     * The tooltip given to the country result filter mentions "UK" but it must actually be "GB" instead.

Good catch.

**Comment by redactedscribe** [comment]
> I've now added an option to set the global font.

I'm not sure why it looks as bad as it did. At least in the previous italicized screenshot, it looks like it's forcing a Regular font to be italic rather than using the Italic version. Just a guess. Other than that, I have no clue. Compared to before, now with (in my opinion) better global font style set, the same text has improved:
![global-font-improvement](https://user-images.githubusercontent.com/25013746/106117981-45bf9100-615c-11eb-91b0-1dbc90920fbb.png)

> Contextual settings open depending on the tab you're on, if you press the cog button.

Ah right, that makes sense.

> Possibly the least tested option in the program. If I feel motivated, I'll look into this.

I realize it's a bit niche, just thought I'd make you aware of it.

> I can see this belonging in the server settings, not a fan of emphasizing such a feature in a menu where space is already at a premium.

This is in fact what I meant 🙂

**Comment by mathiascode** [comment]
Closing in favor of #910.

**Comment by thewriteway** [comment]
Was this resolved in a way that you have an option to exclude specific file types from being shared?

**Comment by mathiascode** [comment]
This is not implemented yet. #910
