### ISSUE TITLE
Cyrillic characters don't display correctly in chat rooms (Unicode issue?)

### ISSUE THREAD

**Issue by baselline** [Nicotine-Plus/nicotine-plus#925]
Nicotine+ version:  2.2.2-1
Operating System/Distribution: Arch Linux

### Describe the bug
When I join Russian chat rooms all messages are displayed with Unicode characters such as "íà óëèöå" instead of Cyrillic. The encoding in the example is supposedly "MACCYRILLIC". I'm pretty sure all other members of the conversation can understand each other.

### Expected behavior
All other tabs and modes in the app show Cyrillic characters correctly (Search, Downloads, Uploads, etc.).

### Steps to reproduce the bug
Join any Russian-speaking chat room (for instance, "RUSSIA") and wait for some messages to appear.

### Additional context
Excuse me if this is a known issue, but i couldn't find any specific forum thread or setting to set the encoding. I tried changing the font, but the characters stay the same.

**Comment by jpdillingham** [comment]
I confirmed that these messages are falling back to ISO-8859-1.  Forcing encoding to Unicode doesn't produce readable text.  I was able to send a message in cyrillic and it was displayed correctly on both ends, so I'm pretty sure that was decoded as UTF-8.

I'm guessing the official client is using a codepage between ISO-8859-1 and UTF-8, perhaps Windows-1251.

**Comment by mathiascode** [comment]
These users are likely using Soulseek NS or some other old client. These characters don't display properly in SoulseekQt either, unless you specify a code page in the settings there.

While we could try decoding incoming chat messages as Windows-1251, and they would display properly for us, these users would not be able to see our Cyrillic messages encoded as utf-8. Nicotine+ had an option to specify the message encoding at one point, but this was dropped to simplify the code and extend utf-8 usage across the network, as Nir wanted with SoulseekQt.

If only people stopped using ancient clients...

**Comment by baselline** [comment]
Okay, so this is not a Nicotine+ issue. Thanks for clarifying. I found [this forum thread for SoulseekQt](http://www.soulseekqt.net/news/node/274) dating back to 2011-2012, so I was under impression that all users should be using UTF-8 by now. Like 10 years have passed. I guess not.
