### ISSUE TITLE
Config resetting when quitting and opening again

### ISSUE THREAD

**Issue by iomughch** [Nicotine-Plus/nicotine-plus#934]
Nicotine+ version: 2.2.2
Operating System/Distribution: Windows 10 Pro

### Describe the bug
If I quit nicotine+, then open it again, my config resets and it asks me to set it up again.

### Expected behavior
I expect my config to save.

### Steps to reproduce the bug
Quit nicotine+ after going through the configuration process that it gives you when using nicotine+ for the first time

### Additional context
There is this message at the bottom:
![image](https://user-images.githubusercontent.com/54216358/103965883-aeeb5000-512c-11eb-9efc-6be6f9cdd83d.png)
I did the configuration and then quit nicotine+, checked the config.new file, and I saw that it had all my settings that I chose saved there. Those settings only reset when I start nicotine+ again after quitting it. I used to use nicotine+ on windows 7 without this problem, it only started when I started trying to use nicotine+ on windows 10.

**Comment by mathiascode** [comment]
Is the "config" file that already exists empty (0 bytes)?

**Comment by iomughch** [comment]
Yes, it is.
![image](https://user-images.githubusercontent.com/54216358/104048012-991f6e80-51b0-11eb-8750-0c13ef7d6a9e.png)

**Comment by mathiascode** [comment]
Could you check if the latest unstable build fixes the issue? https://github.com/Nicotine-Plus/nicotine-plus#unstable

**Comment by iomughch** [comment]
Yes, this fixes it. I also must add, the new ui in that build looks great, I love it.

**Comment by mathiascode** [comment]
Thank you!
