### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by 8wB5JyC8QoqtWJU8PYrxh4psxf8YPwgzn4zEI** [Nicotine-Plus/nicotine-plus#94]
Please consider adopting the freedesktop.org [standard.](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

This would reduce home directory pollution and follow the expected behavior of linux applications, which can also help with backup programs which ignore `~/.cache`.

The change should be simple, generally it's just checking for the XDG base directory environmental variables, and if they don't exist, default to using `~/.config` for configurations, and `~/.cache` for cache. `~/.application_name` should be avoided.

**Comment by gahag** [comment]
Can I work on this?

**Comment by eLvErDe** [comment]
Sure, if you're wiling to

**Comment by gahag** [comment]
Ok, in progress. Should be done by tomorrow, will hit you up if anything.

**Comment by mathiascode** [comment]
Issue should be closed.

**Comment by kiplingw** [comment]
It should be, but for some reason I'm still seeing ~/.nicotine/ and not ~/.config/nicotine.

**Comment by mathiascode** [comment]
~/.config/nicotine will only be created and used if the legacy ~/.nicotine/ folder isn't present.

**Comment by kiplingw** [comment]
Yup. You are right.
