### ISSUE TITLE
Bug: Browsing your own shares with "Share only to buddies" enabled isn't possible via User browse

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#940]
Nicotine+ version:  2.2.2
Operating System/Distribution: Windows 10 20H2

### Describe the bug
With "Share only to buddies" enabled, attempting to browse your own shares isn't possible via the "Browse files" context menu option or "User browse" tab. Disabling this shares option enables browsing yourself in this manner regardless if "Buddy-Only Shares" is enabled or not. Adding yourself to your buddy list makes no difference.

In fact, if browsing your own shares via the menu's "Shares > Browse Buddy shares" is used, then browsing yourself _does_ work when "Share only to buddies" is enabled.

### Expected behavior
Browsing your own shares (public or buddy) should always be possible whichever method the share owner chooses to browse it by.

### Steps to reproduce the bug
1. Enable "Share only to buddies".
2. Attempt to browse your own username's shares via the User browse tab / context menu.

**Comment by redactedscribe** [comment]
Just to note: with "Make public shares buddy-only" enabled, right-click > Browse Files on _yourself_ shows all your files (i.e. as if you're a buddy. With it disabled (but "Buddy Shares" still enabled), you can only see the files you share publicly (i.e. as if you're _not_ a buddy). Maybe there's a good reason for this, but on first impression, it's curious. I think it'd make sense to always show your shares as if you're a buddy since they're your own files (you can always browse yourself as if not a buddy via "Browse Public Shares" to see exactly what non-friends see).

**Comment by mathiascode** [comment]
Fixed in https://github.com/Nicotine-Plus/nicotine-plus/commit/f11ecf10291ca7bc2ba3292e7f154986f6419d96

**Comment by redactedscribe** [comment]
It works, and is more intuitive now.

---

Something somewhat related that I've noticed is, with:

Only public shares enabled, but with shares added to both.
Public share: 1 file
Buddy shares: 2 files
Files shown in the chatroom: 1

1. Enable Buddy Shares > OK.
```
22:10:43 Rescanning started
22:10:43 Rescanning Buddy Shares started
22:10:43 Rescanning normal shares...
22:10:43 1 folders found before rescan, rebuilding...
22:10:43 Rescanning buddy shares...
22:10:43 2 folders found before rescan, rebuilding...
22:10:43 1 folders found after rescan
22:10:44 Rescanning finished
22:10:45 2 folders found after rescan
22:10:45 Rescanning Buddy Shares finished
```
2. Enable "Make public shares buddy-only".

```
<no log activity>
```

Files shown in the chatroom: 1 (still)

3. Rescan buddy shares:
```
22:14:08 Rescanning Buddy Shares started
22:14:08 Rescanning buddy shares...
22:14:08 2 folders found before rescan, rebuilding...
22:14:10 2 folders found after rescan
22:14:10 Rescanning Buddy Shares finished
```
Files shown in the chatroom: 3 (updated)

Maybe toggling "Make public shares buddy-only" should rescan your buddy shares to update this reported file count? Seeing as it only takes ~2 seconds since no files have actually been added/removed, maybe it's worth it to keep this file count accurate?
