### ISSUE TITLE
Bug: Displayed shared files count in Chat rooms / User info inconsistent

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#941]
Nicotine+ version: 2.2.2
Operating System/Distribution: Windows 10 20H2

### Describe the bug
The file count shown in chat rooms shows the total count of files shared (public + buddy) when "Share only to buddies" is enabled. But then when disabled, only the "Public Shares" file count is displayed instead (even if "Buddy-Only Shares" is still enabled - its state has no effect on this issue). Whether this is only a cosmetic issue or if this number is transmitted across the network, I don't know.

### Expected behavior
Buddy shares files shouldn't be counted when publicly displaying a total number of files shared. Or it should be optional.

### Steps to reproduce the bug
1. Add 1 file to public shares, and 2 to buddy shares.
2. "Share only to buddies" _disabled_: chat room file count reads `1`, why not `3`?
3. "Share only to buddies" _enabled_: chat room file count reads `3`.

### Additional context
If it is possible to limit _who_ sees what value, only buddies should see the real total value (public + buddy) by default. If such control is not possible, the next best thing could be to allow Nicotine+ users to define what value is shown to others as the total of files shared: "Public share total" or "Public and private shares total". These values would then be displayed in both the chat room and the User info, but wouldn't limit how many files can actually be browsed by anyone.

For example, I may want to show sharing `0` files (due to having no Public Shares) when I'm only sharing to buddies anyway, or for other reasons, show the total count (public + buddy) because otherwise it looks like I share nothing at all on the network which can be important (again, if I have no Public Shares).

**Comment by mathiascode** [comment]
The server only tracks one value, and displays it to all users. I would argue that this value should always be the number of publicly shared files, as anything else would be deceiving for the average user.
