### ISSUE TITLE
Running CLI on raspbian

### ISSUE THREAD

**Issue by plagasul** [Nicotine-Plus/nicotine-plus#95]
Is it possible to use nicotine to connect to soulseek via CLI , particularly on raspbian? 

Thank you

**Comment by mathiascode** [comment]
There is no CLI interface for Nicotine+, and creating one isn't really a realistic goal. There's a lot of protocol logic, and it's quite ingrained in the GUI part of the program.

**Comment by mathiascode** [comment]
An alternative is Museek+, which seems to have been a sister project of Nicotine+ for a long time, but I'm not sure how well it works anymore. https://github.com/eLvErDe/museek-plus

**Comment by mathiascode** [comment]
@kiplingw Can you close this?
