### ISSUE TITLE
Feature Request: A method to quit via Tray Icon

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#951]
### Describe the solution you'd like
Currently (`2.3.0.dev-1`), when right-clicking Nicotine+'s tray icon on Windows, nothing happens. It'd be nice to have the option to quit / exit via a tray icon context menu. Later, other options could be added to this, such as away status toggling.

**Comment by mathiascode** [comment]
I think my recent context menu refactor killed the tray menu. I'll check what's wrong.
