### ISSUE TITLE
Windows Bug: Can't bring Nicotine+ to the foreground if one of its popup windows are open

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#953]
Nicotine+ version: 2.3.0.dev1
Operating System/Distribution: Windows 10 20H2

### Describe the bug
If Nicotine+'s preferences popup window is open, and it is then covered by another program's window - but some of Nicotine+'s main window is still visible, clicking the main window to focus Nicotine+ doesn't work. Only clicking on part of the preferences popup, or the Start bar's application icon, does main window and popup jump to the foreground. Also happens with the help topics popups.

### Expected behavior
Clicking anywhere on Nicotine+ should bring the main window and its siblings to the foreground.

### Additional context
This doesn't seem to be a problem on Ubuntu / linux builds, though it some quirks are exhibited when it comes to trying to move the main window when the preferences popup is showing (dragging the preferences popup title bar when Nicotine+'s main window is maximized, causes the entire window to be restored and move around - not sure if that's expected).

**Comment by mathiascode** [comment]
I'm a bit worried that this might be a GTK issue. I can reproduce this in the GTK demo.

> This doesn't seem to be a problem on Ubuntu / linux builds, though it some quirks are exhibited when it comes to trying to move the main window when the preferences popup is showing (dragging the preferences popup title bar when Nicotine+'s main window is maximized, causes the entire window to be restored and move around - not sure if that's expected).

Perhaps the preferences window would be better off being non-modal.

**Comment by mathiascode** [comment]
Preferences window is no longer modal. I don't think the other dialogs will stay open for long enough to be a major issue.
