### ISSUE TITLE
Windows Bug: Preferences popup window is slow to open on occasion

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#954]
Nicotine+ version:  2.3.0.dev1
Operating System/Distribution: Windows 10 20H2

### Describe the bug
For unclear reasons, the preferences popup is slow to open on occasion, sometimes taking ~4 or more seconds to open. Though I have no shares added on the Linux version, that version never seems to experience this slowdown (and generally seems more responsive). Perhaps other parts of the UI on Windows are affected too, however I haven't noticed it switching from tab to tab, only when opening the preferences, and in fact, sometimes when displaying the popup that shows on clicking the X to quit.

When it's working, it only takes about 150–500ms (usually closer to 500ms) to draw and display the popup. On Linux (VM), it looks instant.

### Expected behavior
Opening the preferences window and other popups should be more responsive on Windows.

**Comment by mathiascode** [comment]
My guess is that it takes long to load and parse all the ui files, at least this is the reason behind the half-second delay in Linux when opening the preferences window after startup. Why it's so much slower on Windows is a good question though...

**Comment by redactedscribe** [comment]
It's a shame because the application exhibits sluggishness fairly often.

Some things I've noticed:

It seems tab switching is snappy when quickly clicking between any of User Info, Downloads, Uploads, User Browse, Interests, and Buddy list (possibly because they have less or no content to parse). Switching between the other tabs seems predictably sluggish.

A side effect of this slowness may be why I was able to make some tab text become offset:
![tab-text-blank-because-offset](https://user-images.githubusercontent.com/25013746/105888683-f4a58500-6015-11eb-8d72-be5039bfbf96.jpg)
Dragging another tab but the blank tab just moved the offseted text, but attempting to re-order the blank tab itself fixed the issue; text now attached and aligned to the tab again.

Sluggishness is reproducible every time one changes focus from Nicotine+ 3.0.0.dev1 and switches back (easily demonstrated by clicking the desktop, then back on the application). As something that is done very often, it exposes this sluggishness regularly.

**Comment by mathiascode** [comment]
I'll investigate this deeper when I have time, but I suspect this is an issue on the toolkit level, as there are no performance issues on Linux (GTK has been notoriously lackluster on Windows).

**Comment by mathiascode** [comment]
I suppose you could try running Nicotine+ in MinGW, just to ensure that packaging doesn't contribute to this issue. https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/PACKAGING.md#windows

**Comment by redactedscribe** [comment]
> I suppose you could try running Nicotine+ in MinGW, just to ensure that packaging doesn't contribute to this issue. https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/PACKAGING.md#windows

Built it using MSYS2 and there was no noticeable difference sadly.

`gtk3-demo` runs beautifully, though of course, it's just a simple example application.

I can't do much else I'm afraid (other than verify a potential fix); the program's useable, but not giving off the best of impressions. Hopefully you'll come across something to improve the situation, but it's understandable if it's out of your hands (GTK's issue).

**Comment by mathiascode** [comment]
Could you check how some other GTK 3 programs like Quod Libet and Inkscape perform?

**Comment by mathiascode** [comment]
The preferences dialog now loads significantly faster, although some pages still take slightly longer to load the first time (due to https://github.com/Nicotine-Plus/nicotine-plus/issues/975).

**Comment by redactedscribe** [comment]
Downloading via MSYS2 is quite slow for some reason, making installing Inkscape and its dependencies unreasonable. `pacman -Ss quod` couldn't find anything. Do you have another example of an application using GTK I could try?

**Comment by mathiascode** [comment]
You could just use the installers from their websites.

**Comment by redactedscribe** [comment]
Perfect 😀

**Comment by redactedscribe** [comment]
From giving Quod Libet a quick go, it seems to run as if native. It doesn't use the GTK title bar though, and it doesn't look like it does any substantial parsing of (I assume) *.ui files as the interface is quite static. I can try Inkscape. I also have yet to try the fixes you made for Nicotine+.

**Comment by redactedscribe** [comment]
I couldn't make Inkscape behave slowly either.

Nicotine+'s preferences window however is noticeably better with lazy-loading.

Another observation I've made is: one thing all the slower-to-load main tabs share in common is that they automatically focus a text field. Notice that even though Search Files is blank like User Browse, only Search Files is slow (if switching quickly between it and say Downloads) and has pre-defined focus on the text field. Other than that, from a black-box perspective, they share nothing else but their poor performance as far as I can tell.

**Comment by mathiascode** [comment]
Great observation! As I'm having trouble reproducing this on my VM, could you try commenting out these two lines, and see which one of them is causing issues (should be easy in MinGW)?
https://github.com/Nicotine-Plus/nicotine-plus/blob/master/pynicotine/gtkgui/frame.py#L1411
https://github.com/Nicotine-Plus/nicotine-plus/blob/master/pynicotine/gtkgui/frame.py#L1445

**Comment by redactedscribe** [comment]
I'll give it a go.

**Comment by redactedscribe** [comment]
MSYS2 was running fine and compiling `Nicotine+.exe` was successful yesterday. After waking my computer today, `gtk3-demo`, `pip`, and `pyinstaller` could not be found. Uninstalled MSYS2 completely, rebooted, reinstalled everything according to the instructions, and immediately getting `gtk3-demo: command not found`, `./dependencies-core.sh: line 31: pip3: command not found`, and the same for `dependencies-packaging.sh`.

Installed packages:
```
$ pacman -Qs pip
local/mingw-w64-x86_64-python-pip 21.0-1
    An easy_install replacement for installing pypi python packages (mingw-w64)
```
```
$ pacman -Qs gtk
local/glib2 2.66.4-2
    Common C routines used by GTK+ and other libs
local/mingw-w64-x86_64-glib2 2.66.4-1
    Common C routines used by GTK+ 3 and other libs (mingw-w64)
local/mingw-w64-x86_64-gspell 1.8.4-1
    Spell-checking library for GTK applications (mingw-w64)
local/mingw-w64-x86_64-gtk-update-icon-cache 3.24.24-1
    GTK+ icon cache updater (mingw-w64)
local/mingw-w64-x86_64-gtk3 3.24.24-1
    GObject-based multi-platform GUI toolkit (v3) (mingw-w64)
local/mingw-w64-x86_64-python-gobject 3.38.0-2
    Python Bindings for GLib/GObject/GIO/GTK+ (mingw-w64)
```

Not sure what's happening but it's strange. If you can compile a potentially fixed version for me, I can test it that way then.

**Comment by mathiascode** [comment]
Auto-focus for the search field is disabled in these builds: https://github.com/mathiascode/nicotine-plus/actions/runs/515925991

**Comment by redactedscribe** [comment]
Auto-focus for only the Search Files tab is disabled, and it's a big difference.

Private Chat and Chat Rooms could use the same, though I realize in terms of user-friendliness it's not ideal.

**Comment by mathiascode** [comment]
Good to know that's the reason. I'll see if I can come up with some way to focus these entries without causing lag.

**Comment by redactedscribe** [comment]
It may be worth seeing if you can disable the window graying-out/in that happens when focus is lost/gained (on Windows, if you have a way to build differently per platform). At least, that's my best guess for the slow-down that happens there.

**Comment by mathiascode** [comment]
Can you check if this build helps with the tab switch delay at all? https://github.com/mathiascode/nicotine-plus/actions/runs/517708834

**Comment by redactedscribe** [comment]
It looks like an improvement upon the current available master build as far as I can tell, but not as good as when there was no focus on the title bar.

**Comment by mathiascode** [comment]
Could you perhaps create screen recordings of the current delay when switching tabs, as well as other potential performance issues still existing? Also, does it still happen when you disable the header bar (Menu -> View -> Use Header Bar)?

I'm still unsure why I can't reproduce the tab issue in my Windows VM (maybe because it's running Windows 7?).

**Comment by redactedscribe** [comment]
I just temporarily moved the application's configs dir elsewhere and ran it again. I canceled the first time wizard popup and tested the tabs: no slowdown occurring, not for tabs or when app is losing/gaining focus.

It seems to only happen where Nicotine+ has content to display (although, Search Files is blank yet still slow - focused text field?).

This video capture is from _master_ efdb2ac (center is censored): ![2021-01-28 15-06-12.zip](https://github.com/Nicotine-Plus/nicotine-plus/files/5887303/2021-01-28.15-06-12.zip). Pink circle is when I click (yet not every click is captured for some reason).

The last 4 tabs on the right show no slowdown, neither does User Info (contrary to what you think you see in the video). Something possibly critical I just noticed is that _none_ of the tabs are slow when it comes to switching _to_ them, it's only when switching _away_ that the unmentioned tabs cause a delay.

[Your build above](https://github.com/Nicotine-Plus/nicotine-plus/issues/954#issuecomment-768497094) is actually _worse_: there is a delay switching to _and_ away from the laggy tabs.

**Comment by redactedscribe** [comment]
Here's another just showing the slow losing and gaining of focus: [2021-01-28 15-23-50.zip](https://github.com/Nicotine-Plus/nicotine-plus/files/5887409/2021-01-28.15-23-50.zip).

**Comment by redactedscribe** [comment]
Found the answer: It probably should've been more obvious to me than it was, but due to the number of chat rooms that were set to auto join, the program was running poorly. It was roughly 50. Why the some other tabs are affected and others not, I don't know. That's part of what threw me off.

Guess I'll have to be more selective about which rooms I'm a part of. The reason for so many was just convenience as to be aware of any interesting topics. 50 rooms is quite high, is that unreasonable to expect to run decently?

**Comment by mathiascode** [comment]
> Found the answer: It probably should've been more obvious to me than it was, but due to the number of chat rooms that were set to auto join, the program was running poorly. It was roughly 50. Why the some other tabs are affected and others not, I don't know. That's part of what threw me off. Though it still could potentially be related to text fields having focus as it's not entirely ruled out.
>
> Guess I'll have to be more selective about which rooms I'm a part of. The reason for so many was just convenience as to be aware of any interesting topics. 50 rooms is quite high, is that unreasonable to expect to run decently?

I noticed similar behavior after joining a lot of rooms, but profiling reports show nothing. Possibly happening deeper inside GTK, I'll have to investigate.

>     * Chat rooms aren't logged.

Can you elaborate? Works fine for me as long as logging is enabled in a room.

>     * The UI seems to perform fine (scrolling chat / the top log / selecting users) once switched to a room, but switching tabs is delayed like the main ones.

There doesn't seem to be any obvious performance impact like I've usually seen in profiling reports, the tabs just take slightly longer to switch for some reason. As mentioned above, I'll have to investigate.

> **Bug:** Tabs with certain symbols show for example `&gt;`, rather than the actual symbols themselves `>`. The User List displays these characters just fine, as does the Room List. Just not the tabs.

I'll see what I can do.

**Comment by mathiascode** [comment]
> Here's another just showing the slow losing and gaining of focus: [2021-01-28 15-23-50.zip](https://github.com/Nicotine-Plus/nicotine-plus/files/5887409/2021-01-28.15-23-50.zip).

This also seems to be caused by the large number of chat room tabs, even on Linux.

**Comment by mathiascode** [comment]
Latest commit in master should improve the situation. Can you check if that's the case for you too?

**Comment by mathiascode** [comment]
I don't think the auto-join rooms are covered by this change yet. Let me fix that.

**Comment by mathiascode** [comment]
Alright, should be ready now.

**Comment by redactedscribe** [comment]
> Latest commit in master should improve the situation. Can you check if that's the case for you too?

Latest build (https://github.com/Nicotine-Plus/nicotine-plus/commit/a2ebbcbbdb835df753316acc651c1297fa038a96) seems fixed from what I can tell. A considerable improvement overall! No more slowdowns losing focus of the main app, popups such as the preferences and the quit dialog are no longer laggy, the chatrooms don't load each tab like a slideshow any more, no more tab switching slowdowns. Very snappy.

Great work!

**Bug?:** When disconnected (launched with auto-connect off), the top Add buddy... field is not disabled (unlike the others).

**Suggestion:** Downloads and Uploads could have the option to have their columns mirrored, i.e. "Upload mode's columns mirrors that of Downloads'" / "Upload and Downloads share the same column layout", (the former would be more self-evident as to how I see it actually working). I can see why people would like different settings for each, but it could also be nice to have only one "setting" (arrangement) for both so they stay in sync, which could be a better experience by default.

Anyhow, looks like this issue is solved 🙂 I'll let you know if I notice anything related.

**Comment by mathiascode** [comment]
Good to hear!

> **Bug?:** When disconnected (launched with auto-connect off), the top Add buddy... field is not disabled (unlike the others).
Adding users doesn't require being connected to the server, if I remember correctly.

> **Suggestion:** Downloads and Uploads could have the option to have their columns mirrored, i.e. "Upload mode's columns mirrors that of Downloads'" / "Upload and Downloads share the same column layout", (the former would be more self-evident as to how I see it actually working). I can see why people would like different settings for each, but it could also be nice to have only one "setting" (arrangement) for both so they stay in sync, which could be a better experience by default.
Can you open a separate feature request so it can be tracked?

**Comment by redactedscribe** [comment]
Just to be clear, there is minor slowdown still present (mostly noticed when losing/gaining focus), but it's vastly better than before and I'd say is very acceptable.

**Comment by mathiascode** [comment]
I noticed that too, but I'm not sure if anything can be done about that.
