### ISSUE TITLE
The queue limits the number of simultaneous uploads.

### ISSUE THREAD

**Issue by 82d** [Nicotine-Plus/nicotine-plus#956]
Nicotine+ 2.2.2:  
Operating System/Distribution: Arch  Linux

For example, I want to set conditions so that my files can be downloaded simultaneously by many users at a low speed. I set the speed in the settings, remove all queue restrictions. In practice, only two users are automatically downloaded, while the rest are waiting in line.If I select the others in the queue and click Continue, they continue to download, but only up to one file, and then they will queue again. How can I remove or expand the queue?

**Comment by 82d** [comment]
in the beta version, something seems to have improved. and now it automatically gives it to seven people at once, but no more. I would like more than seven if possible.

**Comment by mathiascode** [comment]
There shouldn't be any limit, but I will review the PR for potential errors soon.
