### ISSUE TITLE
Flagged by antivirus

### ISSUE THREAD

**Issue by omrisim210** [Nicotine-Plus/nicotine-plus#96]
On my Windows 10 PC Malwarebytes flags `Nicotine.-1.4.1.exe` as "Generic.Malware/Suspicious".
Interestingly enough, on Virustotal ([link](https://www.virustotal.com/gui/file/e025535a85d946f88b0551c98410a52e72f121951caef3ec4e47b7df0b19c5e8/detection)) MB doesn't flag the same file but some other antivirus programs do.

Is there a reason to suspect Nicotine+ or is this a false alarm?

Also, would getting the installer signed make it more trustworthy? I don't know much about Windows development but I can imagine that it's a non-trivial process

**Comment by kiplingw** [comment]
Hey @omrisim210. Thanks for reporting. I doubt the stable release contained a virus. Most likely this is a false positive.

I'd strongly encourage you to consider upgrading your operating to one that does not require anti-virus software. Unless someone else is prepared to contribute patches to maintain the Windows port, it will likely eventually be abandoned.

But the suggestion you've raised is actually already implemented on all Debian based operating systems. All packages are digitally signed. They've been doing this for over twenty years now.
