### ISSUE TITLE
Feature Request: Search Wishlist: Change "Select All" Button to "Clear All"

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#963]
### Describe the solution you'd like
The `Select All` button seems redundant: its purpose is only to select all and then press `Remove`. There is no other reason to select all items in the wishlist.

It'd be best suited to reorder these buttons to `Remove` and then a `Clear All` button, like is the convention elsewhere in the software. Obviously, the button should clear all and not select all now.

The `Select All` > `Remove` sequence may have been a shortcut to not implement `Apply`, `Cancel`, `OK`, as these would likely need to be present to make `Clear All` > `Cancel` a way to undo accidental clear-alls.

### Additional context
An `Add` button isn't needed, as there is no need for a popup yet. This may change if wishlists network searches ever become more advanced, such as supporting predefined values for the result filter.

**Comment by mathiascode** [comment]
We could make the behavior similar to the transfer statistics dialog - show a confirmation popup when attempting to clear all items. The `Add` button has already been removed in unstable.

**Comment by redactedscribe** [comment]
That approach will work too. Simpler.

I hadn't noticed there was an `Add ` button to begin with. I'm on unstable too.

**Comment by mathiascode** [comment]
https://github.com/Nicotine-Plus/nicotine-plus/commit/5b9c6940f2211e36d223ffcd8ac5b38ce78a5499
