### ISSUE TITLE
Feature Request: Option to choose the search result filter's tab bar position

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#965]
### Describe the solution you'd like
Recently, the filter's tab bar position was moved to the bottom. Aesthetically, it's pleasing, but functionally, less convenient than before I'd argue. Maybe this was necessary for some reason, but if not, then I'd like to see an option to be able to choose its placement: top/bottom.

`v3.0.0.dev1`

**Comment by mathiascode** [comment]
I changed the position to be more in line with the download/upload pages, due to the layout feeling very top-heavy previously. Maybe an option can be added somewhere, I'll see.

**Comment by mathiascode** [comment]
Wonder if there would be a better way to present the filter feature. Adding https://github.com/Nicotine-Plus/nicotine-plus/issues/677 would push the current bar to its limits.

**Comment by redactedscribe** [comment]
You're right about it being a bit too top heavy. If it were possible to merge the search results tab bar with the row containing Results ####, Filter Results, and Add Wish, then a row could be removed. For instance, a row could be split in two, the majority taken up by the result tabs, and the rest containing the Filter Results button etc, then with the filter bar at the top, it wouldn't look like as much space is wasted. Where the filter bar is at the moment (at the bottom, above the log), a thin status line of sorts could be introduced, containing the "Results ####" count (because having that on the same line as the Filter Results button etc wouldn't make contextual sense since it's "outside" of a specific results list). This status line could also display the currently selected item's full file path, or the number of selected items, and even the sum of their file sizes.

That's potentially a lot of work however. To keep it simple, letting the user choose where to position the filter bar would be easy. By default, it can be left at the bottom. But of course, it's not absolutely necessary to change its position, I just found it to be a design choice too biased towards form over function.

As for the issue you referenced, I have the same thoughts as those already raised there, so I just added some additional ideas.

**Comment by mathiascode** [comment]
I moved the bar back to the top, and replaced the labels with entry icons and placeholder texts similar to the rest of the UI, which should help with potential long translations.

Improvements to the tooltips are welcome (potentially add https://github.com/Nicotine-Plus/nicotine-plus/issues/677#issuecomment-765950791 etc.)
