### ISSUE TITLE
MacOS 11.1, wrong flag in buddy list

### ISSUE THREAD

**Issue by neiljt** [Nicotine-Plus/nicotine-plus#972]
Nicotine+ version:  2.22 (installed through brew)
Operating System/Distribution: MacOS 11.1 on an intel system.

I added myself to the buddy list as the 1st step to checking why i was being reported as sharing nothing. the flag that appears before my name is wrong. i am in london, england, nicotine+ is showing the czech republic's flag.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Country data is pulled from IP2Location's database. If you right-click your name, and press "Show IP address", is Czech Republic also the country reported there?

**Comment by mathiascode** [comment]
I've updated the country database to the latest available one, but otherwise there's nothing we can do.
