### ISSUE TITLE
Windows: Toggle show / minimize app on taskbar icon click

### ISSUE THREAD

**Issue by Inso-m-niaC** [Nicotine-Plus/nicotine-plus#976]
Nicotine+ version:  3.0.0.dev1
Operating System/Distribution: Windows 7 Home Premium

### Describe the bug
Nicotine won't minimize when the taskbar icon is clicked

### Expected behavior
It should toggle show / hide with each click

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment]
Unfortunately this seems to be a GTK issue. https://gitlab.gnome.org/GNOME/gtk/-/issues/2785
