### ISSUE TITLE
What is causing the log `Filtered out inexact or incorrect search result ... from user X`?

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#979]
I've seen this appearing in my logs in recent builds and I don't believe it was present in v`2.x.x`.

Would this be triggered by having wishlist items? It quite spammy and appearing for no apparent reason. Maybe it should only appear when manually searching? If wishlists are responsible to begin with. Should I be aware something is being filtered even if it's happening automatically and in the background?

In future, the UI log could prepend `Warn:`, `Search:`, `Conn:`, `Msg:`, `Tx:`, `Stat:` after the time.

**Comment by mathiascode** [comment]
This is only supposed to appear if a client sends bogus results. Can you post the search term used, as well as some of these messages?

**Comment by redactedscribe** [comment]
I have 4 items in my wishlist. Each term is comprised of 2-3 words. Some words appear in twice but only in different terms. No term has the same word appearing twice. No special chars. The only words in one of my terms appearing in the logs for this user is `flac`.

```
XX:XX:42 Filtered out inexact or incorrect search result @@ksizp\Afib - Monteiro\Afib - Monteiro - 09 How This Feels To Me - What This Means To You.flac from user X
XX:XX:42 Filtered out inexact or incorrect search result @@ksizp\Afib - Monteiro\cover.png from user X
XX:XX:42 Filtered out inexact or incorrect search result @@ksizp\The Murder of Rosa Luxemburg - Self Titled\Black, Amber.wav from user X
XX:XX:42 Filtered out inexact or incorrect search result @@ksizp\The Murder of Rosa Luxemburg - Self Titled\I lost all my hair in a skiing accident.wav from user X
```

I don't have Connections or Messages enabled on the log, so I may have missed something related.

**Comment by redactedscribe** [comment]
When searching `music`:

```
XX:XX:52 Filtered out inexact or incorrect search result @@vqbcz\Triple H\[2011] Mawaru Penguindrum Character Song Album - HHH\10 - HEROES ~ Eiyuu Tachi.mp3 from user A
XX:XX:52 Filtered out inexact or incorrect search result @@vqbcz\Triple H\[2011] Mawaru Penguindrum Character Song Album - HHH\folder.jpg from user A
XX:XX:55 Filtered out inexact or incorrect search result @@cklna\Cross (Leaked)\01. Genesis.mp3 from user B
XX:XX:55 Filtered out inexact or incorrect search result @@cklna\Cross (Leaked)\02. Let There Be Light.mp3 from user B
```

**Comment by mathiascode** [comment]
> When searching `music`:
> 
> ```
> XX:26:52 Filtered out inexact or incorrect search result @@vqbcz\Triple H\[2011] Mawaru Penguindrum Character Song Album - HHH\10 - HEROES ~ Eiyuu Tachi.mp3 from user A
> XX:26:52 Filtered out inexact or incorrect search result @@vqbcz\Triple H\[2011] Mawaru Penguindrum Character Song Album - HHH\folder.jpg from user A
> XX:26:55 Filtered out inexact or incorrect search result @@cklna\Cross (Leaked)\01. Genesis.mp3 from user B
> XX:26:55 Filtered out inexact or incorrect search result @@cklna\Cross (Leaked)\02. Let There Be Light.mp3 from user B
> ```

I don't see any "music" in there. Seems like invalid responses sent by those clients.

> And related(?):
> 
> ```
> XX:27:32 <class 'pynicotine.slskmessages.FileSearchResult'> unpack requires a buffer of 4 bytes trying to unpack <class 'int'> at 'b''' at 137777/39
> XX:27:32 Exception during parsing FileSearchResult: unpack requires a buffer of 4 bytes
> ```

Possibly from some ancient client, I'll check.

**Comment by mathiascode** [comment]
Seems like SoulseekQt also filters a lot of incorrect results when searching for "music". Why those results are sent by clients in the first place, I have no idea.

**Comment by mathiascode** [comment]
> ```
> XX:27:32 <class 'pynicotine.slskmessages.FileSearchResult'> unpack requires a buffer of 4 bytes trying to unpack <class 'int'> at 'b''' at 137777/39
> XX:27:32 Exception during parsing FileSearchResult: unpack requires a buffer of 4 bytes
> ```

This user is sending an incomplete search result message, likely due to some bug in their client. Not much we can do here.

**Comment by mathiascode** [comment]
> This user is sending an incomplete search result message, likely due to some bug in their client. Not much we can do here.

Turns out Nicotine+ could behave like this if the file index database was incomplete or corrupted. I've pushed a change to master that ensures we don't send an incorrect search result message in such cases.

**Comment by redactedscribe** [comment]
A quick somewhat related question, do you know if some search terms are blacklisted on the protocol/network? I've searched `Beatles` in the past assuming I'd get a full list of results for testing, but not a single hit would be returned. An immediate follow-up search for `music` would succeed.

**Comment by mathiascode** [comment]
Yup, certain terms are blacklisted on the server: https://slsknet.org/news/comment/3295#comment-3295

**Comment by mathiascode** [comment]
Closing, as there isn't much we can do about the situation. I'd prefer to keep these debug messages.
