### ISSUE TITLE
Feature Request: Improve folder folding behavior + Add Collapse/Expand All

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#981]
### Describe the solution you'd like
Folders and any subfolders are expanded by default. When collapsing the root and then expanding it, all previously expanded subfolders (in this case, those shown via User Browse), are now collapsed too.

It may not be ideal for this to be the case. For example, if you had all but a few folders of interest collapsed, then collapsed and re-expanded the root, your "visual bookmark" will have been lost.

I think what may be ideal is to not change the expanded state of child folders when collapsing a parent, and only do so if a Collapse All command is used. Having only the root expanded to show the directories makes for an easier visual browse when scrolling down often long lists. Convenient for User Browse, but not something the search results should do by default since the files themselves are what are typically of interest, even if the mode is "group by folder".

Should all folders and subfolders be expanded by default when browsing a user (as they are now)? It doesn't matter so much if there is control over collapsing or expanding all.

The same folder behavior found in User Browse is shared in the search result grouping modes.

`Nicotine+ v3.0.0.dev1`

**Comment by redactedscribe** [comment]
Collapse/Expand All should be applied at whatever point in the folder tree it is performed on. E.g. To expand everything, "Expand All" on the root.

**Comment by mathiascode** [comment]
> Folders and any subfolders are expanded by default. When collapsing the root and then expanding it, all previously expanded subfolders (in this case, those shown via User Browse), are now collapsed too.

It seems like this behavior is hardcoded in GTK, so we can't do much about it.

**Comment by mathiascode** [comment]
Since the behavior can't be changed, is there anything left to do?

**Comment by dchmelik** [comment]
> Since the behavior can't be changed, is there anything left to do?

Ask GTK, and everything being initially collapsed (or to a certain level) should be a permanent option in the download & upload tabs.  I spend more time collapsing directories/folders there than doing anything else in Nicotine+.

**Comment by mathiascode** [comment]
> > Since the behavior can't be changed, is there anything left to do?
> 
> Ask GTK to improve/enable this, and everything being initially collapsed (or to a certain level) should be a permanent option in the download & upload tabs. I spend more time collapsing directories/folders there than doing anything else in Nicotine+.

Click the "Expand/Collapse All"-button to collapse everything, and it will be remembered permanently. Set "Group by User" to collapse user rows, and "Group by Folder" to collapse folder rows.
