### ISSUE TITLE
Bug: Private chat tabs closed/discarded without manually doing so

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#983]
Nicotine+ version: Nicotine+ 3.0.0.dev1
Operating System/Distribution: Windows 10 20H2

### Describe the bug
For currently unknown reasons, all my private chat tabs were closed.

### Expected behavior
Private chats should remain open as tabs for as long as they are not closed.

### Additional context
Could this be related to the new auto-connect on start-up feature? A quick test said no. I don't believe I've noticed this happening before.

**Comment by mathiascode** [comment]
Seems to happen if you open Nicotine+ and close it without connecting.
