### ISSUE TITLE
Bug: Unable to reliably close search tabs via middle mouse button click

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#984]
Nicotine+ version: Nicotine+ 3.0.0.dev1
Operating System/Distribution: Windows 10 20H2

### Describe the bug
For some reason, attempting to close a search tab isn't reliable. It seems Nicotine+ can get stuck in some state where MMB clicking does nothing, until it does, and closing tabs is fine. Then, it won't work again. May also relate to tabs in general.

### Expected behavior
100% success rate.

### Steps to reproduce the bug

1. Search for `music`.
2. Attempt to close the `music` tab.
3. May or may not succeed at closing the tab.

### Additional context
Not sure if it's only related to MMB closing, or related to clicking the X button (which I have disabled from being shown).

**Comment by mathiascode** [comment]
Does this only apply to search tabs? All I can think of is that the click may have been on the edges of the tab, where no signal handlers are connected.

**Comment by redactedscribe** [comment]
I haven't used N+ for a while, but I do recall that the clicks were squarely in the middle of the search result tab. Not just a single click but many consecutive MMB clicks with no effect. I have moved the search tab bar to the left and so it's vertical, which may be relevant.

**Comment by mathiascode** [comment]
Thanks, that makes sense. The label box (which catches the clicks) currently doesn't extend beyond the width of the text, so any empty space is affected by the issue.
