### ISSUE TITLE
Suggestion: Room wall improvements

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#985]
### Describe the solution you'd like
At some point, room walls for each chat room could have some improvements made:

- With Interface > Fonts & Colors > Colored and clickable usernames enabled, usernames in the room wall could also use this feature.
  - For example, when clicking Browse Files on a user, what should happen? Close the room wall and then proceed as normal? Or should the room wall be non-modal too? If  so, can only one room wall popup ever be open at one time? Will it be re-used when clicking the room wall button in another chat room?
- I'm unsure why the unique messages on the wall are displayed in the order that they are, but perhaps they should be organized alphabetically by username?
- When you've set a message on a room's wall, there could be an indication somewhere that you have done so (without needing to open every room's wall to check).
- Online status indicator could be displayed: Green/yellow/red(offline). As an observation, red typically means busy in many programs, but in Nicotine+ it appears to mean offline. To reduce potential confusion, tooltips could be added to the colored dots Online/Away/Offline(?) (similar to country flags).
  - Flags could also be shown. Since some people may be offline, display no flag (as is done currently), or introduce a blank flag of sorts.
- A more obvious way to clear your room wall message than pressing Enter to submit a message of no length.
  - The "Set wall message..." could display your set message. This would let you modify it and resubmit it easily, and you wouldn't need to browse through the list of wall messages to find your own. A "Set" and a "Clear" button next to this field would then make sense.
- A statistic to show when you set your message.
  - If it's possible to know this for others' messages, perhaps this could be shown too.

Nicotine+ 3.0.0.dev1

**Comment by mathiascode** [comment]
> I'm unsure why the unique messages on the wall are displayed in the order that they are, but perhaps they should be organized alphabetically by username?

The latest messages are displayed first.

> If it's possible to know this for others' messages, perhaps this could be shown too.

Unfortunately, no dates are provided by the server.
