### ISSUE TITLE
Feature Request: Log Viewer / Context menu items to browse logs in system text editor

### ISSUE THREAD

**Issue by redactedscribe** [Nicotine-Plus/nicotine-plus#986]
### Describe the solution you'd like
A way to view chat histories and other Nicotine+ logs on the system.
- A window that can read and display the log file for a given chat, chat room, or debug/transfer log etc.
  - Window could be tabulated, similar to the main Nicotine+ tabs which are then further divided into subtabs:
    - Private, Rooms, Transfers, Debug:
      - Private and Room: a tab for each log found.
      - If the transfers and debugs log ever split, then they would need the same.
  - A way to open it in the system's text editor / shortcut to the log on disk.
  - Find feature included so log text can be searched.
- "View Chat Log" context menu entry for users which have a log file on disk that opens in the window described above.
- "View Room Log" context menu entry above the already "Delete Room Log".
- "View Debug Log" for the debug logging bottom window.
- "View Transfers Log" for the debug logging bottom window (or maybe for the Downloads/Uploads modes?).

### Additional context
Implementing a log browsing window is potentially a lot of work, so instead, it'd be acceptable to just add context menu entries that launch the system's default text editor. This would improve upon having to navigate to where Nicotine+ saves its logs when wanting to browse them.

Using the word "view" over "browse" due to there already being a "Browse Files" on user context menus.

Nicotine+ 3.0.0.dev1

**Comment by mathiascode** [comment]
I'm more inclined to add context menu items that open the folder locations in the system's file manager, rather than increasing the maintenance burden in Nicotine+.
