### ISSUE TITLE
Failure to report buddy shares

### ISSUE THREAD

**Issue by neiljt** [Nicotine-Plus/nicotine-plus#988]
Nicotine+ version:  2.2.2
Operating System/Distribution: MacOS 11.1

### Expected behavior:

in earlier versions of nicotine+ you added yourself to the list of friends in order to check other people's views of what you share. later a menu function was added to do that without having to add yourself. at some later point, this function was obviously removed, so we're back to having to add ourselves as a friend.

### Steps to reproduce the bug
1) Create an account, set it to buddy-only shares.
2) Add some directories to the buddy shares.
3) add yourself to buddy list.
4) obtain your own shares list.
= reports "User's list of shared files is empty..."

### Additional context
None

**Comment by mathiascode** [comment]
In the upcoming 3.0.0 release, pressing "Browse files" in the context menu for your own username will show you your buddy shares, unless they are disabled. The menu function to do this was never removed though, it exists under Shares -> Browse Public shares in the menu bar.
