### ISSUE TITLE
Pluginsystem related issues, views and ideas [Updated]

### ISSUE THREAD

**Issue by Inso-m-niaC** [Nicotine-Plus/nicotine-plus#990]
I felt pressed to make this post since i get the feeling that 3.0.0 release date is somewhere near. Here i have made a collection all things Pluginsystem related.

##### Some things i have noticed
- _OutgoingPrivateChatNotification_ does not appear to be issued. :heavy_check_mark: [Resolved]

- _IncomingPrivateChatEvent_ and _IncomingPrivateChatNotification_ are each issued _twice_ per single event. :heavy_check_mark: [Resolved]
-  \_\__privatecommands_\_\_; When not passing an argument via a /command, the _args_  variable is then populated with the _user_ value. :heavy_check_mark: [Resolved]

- A non-issue. When plugins are loaded  _init()_ gets called twice;  _->init() ->loadNotification() ->init()_ :heavy_check_mark: [Resolved]

##### Some things i would like
- Implementation of _Gtk.RadioButton_ in Plugin Properties GUI.

- Implementation of _Gtk.FileChooser_ in Plugin Properties GUI (for file selecting only). :heavy_check_mark: [Added]

**Comment by mathiascode** [comment]
Thanks for reporting shortcomings in the plugin system. I'm postponing this for a future release, since I'm not very familiar with the plugin-related code right now, and I want to release 3.0.0 this week (hopefully).

**Comment by Inso-m-niaC** [comment]
Great job! That clears up everything i know of. Shall i close?

**Comment by Inso-m-niaC** [comment]
One last thing. About those notices to self with colours, is something like this feasible? * i can get by without it of course.*

```python

    """ privatechats """
    def appropriate_name(self, line, tag=None, tag_name=None):
        timestamp_format = self.frame.np.config.sections["logging"]["private_timestamp"]
        if tag_name: # Used explicitly by plugin system
            tag = getattr(self, tag_name)
        append_line(self.ChatScroll, line, tag, timestamp_format=timestamp_format)

    """ pluginsystem """
    def notice_private(self, user, line, tag="chat_local"):
        #  tags: chat_me, chat_local, chat_remote, chat_hilite
        self.frame.privatechats.users[user].appropriate_name(line, tag_name=tag)
```

I don't know if the actual code would work, but in theory the method could be used by privatechats too for some messages and remove some of those timestamp_format declarations. it's understandable if you don't want to add a horrid hack like this :]
