### ISSUE TITLE
Practical: change share from public to buddy and vice versa.

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#991]
Would it be nice if it was possible to switch shares between public and buddy mode?

I just realized I had to delete a share and create a new one to change it from public to buddy mode. No big deal, but maybe my suggestion would be even nicer.

**Comment by redactedscribe** [comment]
When version 3.0.0 of Nicotine+ is released, you'll be able to do this via the "Make public shares buddy-only" preferences option (the option of a similar name doesn't work as you'd expect in the current 2.2.2 version if I recall correctly). In 3.0.0, you should just be able to toggle the option on/off to achieve what you're asking for. You can try out the latest [unstable builds](https://github.com/Nicotine-Plus/nicotine-plus#download-nicotine) if you want this functionality now, but of course, you may experience some bugs.

**Comment by mathiascode** [comment]
I think what's asked for here is an easier way to convert a single shared folder from public to buddy, and vice versa. I've previously been thinking about combining the public and buddy share list views, with a checkbox column indicating whether a shared folder is public or not.

**Comment by hboetes** [comment]
Sounds like an excellent solution.
